### PR TITLE
Treat abstract Groovy classes with no fields as `Managed` types

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
Didn't this PR fix https://github.com/gradle/gradle/issues/16982?

**Comment by bamboo** [comment]
It is not enough to fix that particular issue. We still need to bypass the constructor when deserializing instances.

**Pull request merged**
