### PR TITLE
GRADLE-3091 Adds support for preemptive auth to enable maven repositories hosted in Github and Bitbucket.

### PR DESCRIPTION
**Pull request by rharter**
Per the discussion in Jira, I've implemented this feature using a preemptive flag on the credentials.

There was some discussion on the mailing list about having this be automatically set for github and bitbucket, but I'm not sure of the best approach there.  I'm not generally a fan of hard coding things, especially hostnames, but I think this is a good first step.  The next step for this is to have the flag automatically set for certain services, like github and bitbucket, but IMHO the flag should remain so that users can override or force it when needed.

### CODE REVIEW

**Comment by bigdaz** [comment]
Thanks for the pull request. We'll take a look at it soon.

In the meantime, if you haven't yet signed a contributor agreement (as per http://www.gradleware.com/contributor-agreement/), that will help when we come to merge your changes.

**Comment by rharter** [comment]
Thanks Daz, I have already filled out the form.

**Comment by sadevelopment** [comment]
This would be a great feature to have in - well done Ryan. We use a lot of private repo's and this fix has allowed us to finally update Gradle from 1.x, Android Studio and IntelliJ to the latest and greatest as we now reference this build in our wrapper. Without it, we would be falling behind with Gradle and IDE's.

**Comment by paleozogt** [comment]
+1 Being able to use private repos is a big deal for our team as well.

**Comment by bigdaz** [comment]
Hi @rharter. Unfortunately your CLA seems to have been lost somewhere along the line, and I can't find any record of it. Would you be able to please resubmit?

We are currently planning what will go into Gradle 2.4 and I'd like to include this functionality. On further discussion with @adammurdoch we're thinking a DSL that specifies the authentication scheme(s) for a repository might be better than a 'preemptive' setting. This would fit better with the principle of describing to Gradle the 'what' rather than telling Gradle the 'how'.

For a repository that supports only 'basic' auth we could then retry on 404 with an authenticated request. We don't want to do this for a repository that supports 'digest' or 'ntlm' auth, since this could result in our sending the password over the wire when this isn't desired by the user.

We need to do a bit more thinking about how the DSL might look, but would you be interested in getting this into shape for Gradle 2.4? I expect getting an RC out will take at least 3 weeks.

**Comment by rharter** [comment]
Sorry about the CLA, @bigdaz, I must have screwed up the confirmation or something.  It's finished now.

As for the DSL comments, I think that makes a lot of sense.  Are you guys thinking something like this for the DSL?

```credentials {
    username 'username'
    password 'password'
    auth 'basic'
}```

I'll do my best to help get this ready for 2.4.

**Comment by bigdaz** [comment]
We'd rather not conflate the 'scheme' with the 'credentials', since one represents information about the user, and the other represents information about the authentication supported by the repository. Another point is that the `credentials` block is something we'd rather move out of the repository declaration: we'd like to make 'credentials' much more of a first class citizen in Gradle, and make it possible to define them and source them in many different ways.

To start with, we could go with something like:
```
repositories {
    maven {
        authentication {
            scheme 'basic'
            scheme 'ntlm'
        }
    }
}
```

We can discuss this more on the dev list, but I reckon that would work to get us going. 

When specified, we'll need to configure HttpClient to only use the named scheme(s). Then, when 'basic' is available we could retry on 404 with authentication. (Or maybe use pre-emptive auth when _only_ 'basic' is specified).

**Comment by adrianbk** [comment]
@bigdaz @rharter I'm looking at reviving a discussion on the dev forums around this and some [initial design work](https://github.com/gradle/gradle/pull/391) on making credentials 1st class citizens in gradle. It would be good to sync up on all of this and use this real need to drive things.  

I'm a bit confused here @bigdaz with the DSL example you gave - how would basic http work? if there is no credentials block on the repository where is the username/password coming from? 

Also, should that authentication block be strongly typed to allow other authentication mechanisms? 
 
```groovy
maven {
        authentication([BasicHTTP,NtlmHTTP,WeNeverConsideredThisOne]) 
    }
```

In this particular scenario there are multiple authentication mechanisms (httpbasic, httpntlm, etc.) It's possible that there may be multiple authentication mechanisms, each one requiring different credentials - I'm struggling to figure out how this is going to work without explicitly setting credentials (or a credentials provider) on either the repository or authentication block?

**Comment by freezy** [comment]
Is there any way this PR would go upstream before the whole "make credentials a first class citizen" discussion (which seems to take its time)?

Right now, there's simply no way of referencing a dependency sitting in a private GitHub repo, which is a huge hassle for a lot of people. Someone wrote even a [plugin](https://github.com/layerhq/gradle-git-repo-plugin) for this use case, which temporarily clones the referenced repo but comes with all kind of other complications (it doesn't work on Windows, for starters).

**Comment by sadevelopment** [comment]
@freezy - we applied @rharter 'preemptive' change to gradle 2.2.1 & 2.4 and it has been working really well for us. We will continue using it until the issue is sorted.

**Comment by freezy** [comment]
@sadevelopment: So you guys are all using a patched version of Gradle and maintain it parallel to Gradle's release cycles?

**Comment by sadevelopment** [comment]
@freezy: yes, we took the latest production release src and applied a patch to it. We did the same to the latest 2.4 code base as well. We had to as we were stuck using old versions of Android Studio and Intellij with an old version of gradle - that worked fine with private repos. Its not ideal but in general we haven't needed to update gradle passed 2.2.1 and don't plan to for the foreseeable future ... The patched jar is distributed internally with our code to our developers and all projects are preconfigured to use it.

**Comment by freezy** [comment]
@sadevelopment: Cheers for the explanations. That sums about up what I feared I'd need to do in order to go forward with our project.

@bigdaz: Any way you could spare us this in a timely manner? ;)

**Comment by mitchhentges** [comment]
Looking forward to this

**Comment by bigdaz** [comment]
So while we haven't merged this PR, there's a fix in master that allows a user to explicitly enable `BasicAuthentication` for an http repository. When explicitly enabled in this way, Gradle will use preemptive authentication on all http requests.

**Comment by mitchhentges** [comment]
The documentation for the comment above is [here](https://github.com/gradle/gradle/blob/1a927612ed7ecfeaab1036a82cd11d379764529b/subprojects/docs/src/docs/release/notes.md#support-for-preemptive-authentication-i).

So, IIRC:
```
repositories {
    maven {
        credentials {
            username 'user'
            password 'password'
        }
        url "http://repo.mycompany.com/maven2"
        authentication {
            basic(BasicAuthentication) // enable preemptive authentication
        }
    }
}
```

**Comment by mark-vieira** [comment]
@mitchhentges that is correct. This is slated for release in Gradle 2.7 but like Daz mentioned this is in master for you to try out if you like.

**Comment by bigdaz** [comment]
Thanks everyone for your input on this: Gradle 2.7 will provide the ability to explicitly opt-in to `BasicAuthentication`, thus enabling preemptive authentication for a repository.

I'm closing this PR: stay tuned for Gradle-2.7-rc-1 in a couple of weeks.

**Comment by freezy** [comment]
With Gradle 2.7, I'm getting the following error:

```
* Where:
Build file 'build.gradle' line: 33

* What went wrong:
A problem occurred evaluating root project 'test'.
> Cannot create a BasicAuthentication because this type is not known to this container. Known types are: BasicAuthentication, DigestAuthentication
```

I've added this to my root `build.gradle` under `allprojects`:

```groovy
maven {
	credentials {
		username "x-oauth-basic"
		password "<hash>"
	}
	url "https://raw.githubusercontent.com/org/repo/master/path/to/static/repo"
	authentication {
		basic(BasicAuthentication)
	}
}
```

Line 33 points to `basic(BasicAuthentication)`. It's an Android project and this block is the only thing I've added (besides updating `gradle-wrapper.properties` to use 2.7). What am I doing wrong?

**Comment by bigdaz** [comment]
Note that you don't require any import in your Gradle build file for this to work: classes in `org.gradle.authentication.http` are automatically imported into a Gradle build file. I guess Android Studio doesn't know about the new classes in Gradle 2.7 which causes it to look for an import.

**Comment by freezy** [comment]
Yeah I suppose not. Anyway, great work, this gets rid of a lot of headache we used to have. Cheers!

**Pull request closed without merging**
