### PR TITLE
Document `Task#usesService` requirement for constraining concurrent access to services

### LINKED ISSUE #14380: Document usage of `usesService` when working with build services
### Related Samples
None.

### Context
A user was reporting that `spec.getMaxParallelUsages().set(1)` did not take effect (build service still called by more than one task at a time) until he added `useseService` to the affected tasks:

```
task abc1(type: SpecialTask) {
    ...
    usesService serviceProvider
    ...
}
abc1.getServer().set(serviceProvider)
```

Can you please add some documentation on when/how to make use of `usesService` whichis currently not documented on docs.gradle.org (except the Javadoc).

### PR DESCRIPTION
**Pull request by bamboo**
Fixes #14380

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by dredom** [comment]
Does not appear to work for composite builds.

`ext.onlyOneProvider = gradle.sharedServices.registerIfAbsent(
    "onlyone", MyBuildService) { spec -> maxParallelUsages.set(1) }`

To test this we have 2 composite build subprojects. 

`includeBuild('projA')
includeBuild('projB')`

Each of them does the above "registration" for the MyBuildService above.

Unfortunately the BuildServiceRegistration (sharedservices) is a **different instance** for each subproject.  It is not a global registration per se, but rather a registration that is project specific, thus not shared, thus does not work to limit parallelism across the subprojects.

**Comment by bamboo** [comment]
Hi, @dredom. Each included build gets its own `Gradle` instance, thus its own separate `sharedServices` registry. Would that explain the behavior you're seeing or you mean something else? If that doesn't explain the behavior you're seeing, could you provide a small repro for the scenario you think it's incorrectly handled?

**Comment by dredom** [comment]
Hi @bamboo. Thanks for the confirmation that each included build gets its own sharedServices registry.

My requirement is for some global locking mechanism across all included builds. Specifically, we have several included build tasks running msbuild assemblies that conflict - so we need to single thread them.

No worries. I'm creating a groovy class that uses a simple global (static) Java `Lock` which, while not necessarily robust, seems to work so far.

**Pull request merged**
