### PR TITLE
Making Option and OptionValues in the public namespace

### PR DESCRIPTION
**Pull request by ethankhall**
Allowing users to specify options to tasks. This will make users able to
use the `--some-option foo` vs having to do `-PsomeOption=foo`.

### CODE REVIEW

**Comment by oehme** [comment]
There are many plugins out there already using this API, even though it's internal. I wonder wether we should leave the old one in place, deprecate it and add a new one. Then remove the old on in Gradle 5.0

**Comment by ethankhall** [comment]
I can do that. Out of curiosity, why not 4.0 vs 5.0? Would it be worth adding a nag warning for it?

**Comment by oehme** [comment]
> why not 4.0 vs 5.0?

3.3 might already be the last 3.x release, so it's too late.

> Would it be worth adding a nag warning for it?

Yes, we definitely should.

**Comment by oehme** [comment]
We should also make sure that the tests cover both annotations while the old one is still supported.

**Comment by ethankhall** [comment]
This isn't going to get done for a while, I'll close it an re-open I can grab it again.

**Pull request closed without merging**
