### PR TITLE
StringBuffer can be replaced with String

### PR DESCRIPTION
**Pull request by vbauer**

### CODE REVIEW

**Comment by big-guy** [comment]
Hi @vbauer, would you mind signing the CLA? http://gradle.org/contributor-license-agreement/

**Comment by vbauer** [comment]
Hi @big-guy, I've just signed it. :)

**Comment by big-guy** [comment]
Thanks @vbauer.  This will be in 2.8

**Comment by vbauer** [comment]
Thank you for merge!

**Pull request merged**
