### PR TITLE
Split VersionRangeResolveIntegrationTest

### PR DESCRIPTION
**Pull request by blindpirate**
Previously the whole class includes 300+ iterations and sometimes runs >8 min. Now we split it into 3 classes.

### CODE REVIEW

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
