### PR TITLE
[maven-aws] Adds support for AWS S3 backed maven repositories (resolutio...

### PR DESCRIPTION
**Pull request by adrianbk**
...n not publishing).

[maven-aws] Adds skeleton S3 transport classes and uses transport scheme to determine credentials type.

[maven-aws] Wiring in AWS sdk and implementing S3 resource accessor

[maven-aws] Code review cleanup

[maven-aws] Sets default credentials to null when specific type has been specified via DSL

[maven-aws] Validates the PasswordCredentials type

### CODE REVIEW

**Comment by breskeby** [comment]
I'm currently working on merging this PR. I think after we merged this, we can have specific jira issues to address certain things separately

**Comment by breskeby** [comment]
Hey Adrian,
I just merged your pull request into master. This stuff will be part of the gradle 2.4 release. Before you go to deep in tackling other related issues. Can I ask you a favor to add some documentation about this into the gradle userguide? Best place might be the already mentioned SFTP support I think. Do you looked into supporting ivy repositories as well here?

**Comment by adrianbk** [comment]
@breskeby thanks! I will add some documentation. Certainly plan on supporting ivy repos but was hoping to support publishing to s3 with maven first - I though it would be more useful to be able to both publish and resolve with one repository type first.

**Comment by breskeby** [comment]
good point. I think you're right and adding publishing support for maven makes sense to have both directions supported.

**Pull request closed without merging**
