### PR TITLE
Remove deprecated WarPluginConvention

### PR DESCRIPTION
**Pull request by donat**

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by donat** [comment]
@bot-gradle test RFM

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Comment by donat** [comment]
Superseded by https://github.com/gradle/gradle/pull/22062

**Pull request closed without merging**
