### PR TITLE
Update Gradle Enterprise Gradle plugin to 3.8.1

### PR DESCRIPTION
**Pull request by sorin-florea**

### CODE REVIEW

**Comment by sorin-florea** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by sorin-florea** [comment]
@bot-gradle test and merge

**Comment by sorin-florea** [comment]
@bot-gradle test and merge

**Comment by sorin-florea** [comment]
@bot-gradle test

**Comment by blindpirate** [comment]
There are some flaky tests blocking us. gradle/gradle-private#3503
I marked them as `@Flaky`.

@bot-gradle test and merge

**Pull request merged**
