### PR TITLE
Misc release notes improvements

### PR DESCRIPTION
**Pull request by ljacomet**
* Contributors list
* UX improvement for release notes tasks
* Update to release notes template

### CODE REVIEW

**Review by hythloda — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test BD

**Comment by ljacomet** [comment]
@bot-gradle test BD

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
