### PR TITLE
Add Gradle wrapper example for Kotlin DSL

### PR DESCRIPTION
**Pull request by StefMa**
### Context
I wanted to "fix" [this comment](https://github.com/gradle/kotlin-dsl/issues/956#issuecomment-403560258) by adding the wrapper task to the userguide/documentation for the Kotlin DSL.

As I started I thought I can use the same pattern/style like @eriwen described here https://github.com/gradle-guides/gradle-guides-plugin/pull/23. Unfortunately I can't 😅.
Means the current guide looks like the following instead of a "tabbed/switching view":

I also haven't found any example inside the doc which provides both - the Groovy & and the Kotlin DSL.

It would be great if someone can give me a hint how can I solve this 😇 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] ~Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective~
- [ ] ~Provide unit tests (under `<subproject>/src/test`) to verify logic~
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by marcphilipp** [comment]
AFAIK, unlike for Guides, the User Guide infrastructure is not yet ready to show both Groovy and Kotlin DSL samples.

@eriwen @eskatos What's the current status on the User Guide infrastructure wrt. Kotlin DSL samples?

**Comment by eskatos** [comment]
Hi @StefMa,
Thanks for the PR!
This is currently blocked on https://github.com/gradle/gradle/pull/5837

**Comment by StefMa** [comment]
Ah ok 👌 
Thanks guys.
Then I'll wait with this PR until #5837 is ready to use.

**Comment by eriwen** [comment]
Thank you for the contribution @StefMa! I'll report here once #5837 is merged. Working hard on it.

**Comment by eriwen** [comment]
Pleas follow #6006 instead.

**Comment by StefMa** [comment]
@eriwen #6006 is closed but with a [comment](https://github.com/gradle/gradle/pull/6006#issuecomment-407898597) from you that it is delivered.

Can I continue on this now? Or is it still blocked somehow?

**Comment by eriwen** [comment]
@StefMa You are absolutely welcome to continue on this. You should update `gradle_wrapper.adoc` now, and here is the syntax you should consider:

```
.Your title here
====
[.multi-language-sample]
=====
.build.gradle
[source,groovy]
----
include::{samplesPath}/path/to/build.gradle[]
----
=====

[.multi-language-sample]
=====
.build.gradle.kts
[source,kotlin]
----
include::{samplesPath}/TOTALLY_DIFFERENT_FOLDERKts/build.gradle.kts[]
----
=====
====
```

Which will come out looking like this

screenshot 2018-07-31 15 31 21

**Comment by StefMa** [comment]
Fixed it ✅ 
geist_1533301673813

I haven't changed the "sample folder" like you said. 
Why should we do that? 🤔 
And where should I move it?
In `subprojects/docs/src/samples/userguide/wrapper/customized-task-kts/build.gradle.kts` ?

**Comment by eriwen** [comment]
@StefMa

I request you move it to `subprojects/docs/src/samples/userguide/wrapper/customized-tasKts/build.gradle.kts` (I know this mixes word boundaries, but we want to standardize on some common suffix for automation purposes).

The majority of samples have sample tests (configured by those `.sample.conf` files) that verify that the sample works. If we mix Kotlin DSL scripts and Groovy DSL scripts in the same sample, then there will be conflicts (considering not just `build.` scripts but `init.` and `settings.`)

We also want users to be able to copy these directories and run them, which becomes a bit complicated having both DSLs in the same project. 

This all said, we're working on a couple better ways to include and test samples that may avoid this type of problem entirely. I'm not sure that'll be ready for another month or 2.

**Comment by StefMa** [comment]
Understood. Make sense 🙃 
Just moved the dir.
Hoped you mean `...taskKts` instead of `tasKts` 😄 
So meaning that all of the "default" dirs just get a `Kts` as prefix ...

**Comment by eriwen** [comment]
Thanks very much @StefMa! I'm working on asciidoctor extensions that make this easier, and what I'd like to do here is:

 * Develop those extensions
 * Update this PR to take advantage of them

@eskatos the sample looks good here, do you agree?

**Comment by StefMa** [comment]
@eriwen 
Yeah, feel free to do whatever you want with this PR 🙃

**Comment by eriwen** [comment]
@StefMa Thank you for your contributions here. I have submitted [a follow-up PR](https://github.com/gradle/gradle/pull/6434) that adds a couple things to your changes:

 * Changes the dirs the samples live in
 * Adds a `settings.gradle.kts` for the Kotlin sample
 * Adds sample.conf to ensure that the given sample gets tested. 
 * Uses a new Asciidoctor macro `include:sample` to make including samples simpler

I'm going to close this PR but will list your contribution with the others for 5.0 — thank you!

**Pull request closed without merging**
