### PR TITLE
Add dependency verification changes for Gradle 8 to release notes

### PR DESCRIPTION
**Pull request by asodja**
Maybe `Dependency verification metadata` xml notes could be written differently, I guess the current version is not easy to understand. 

Fixes https://github.com/gradle/gradle/issues/22355.

[Preview](https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/57941298:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221109092811%2B0000/docs/release-notes.html).

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test BD

**Comment by asodja** [comment]
@bot-gradle test BD

**Comment by asodja** [comment]
Thanks, @nathan-contino for reviewing this. Could you take another quick look after a merge of the master branch?

[Preview](https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/57941298:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221109092811%2B0000/docs/release-notes.html).

**Review by nathan-contino — APPROVED** [review]
LGTM!

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
