### PR TITLE
Revert "Adjust script compilation to use jsr305 strict mode"

### LINKED ISSUE #19088: Provider#map doesn't allows to transform into nullable type in Kotlin DSL
### Expected Behavior
Provider#map allows to transform value of any type into any value of any type.

### Current Behavior
Provider#map doesn't allows to transform into nullable type

### Context
I faced the problem on Gradle 7.4-20211122230135+0000 nightly build. It embeds Kotlin 1.5.31 (the same as Gradle 7.3), but Gradle 7.3 doesn't make such a restriction on Provider#map.

### Steps to Reproduce 
1. Get the project from [gradle-buildscript-nullability.zip](https://github.com/gradle/gradle/files/7588739/gradle-buildscript-nullability.zip)
2. Invoke just `./gradlew` and see the fail
3. Change Gradle version to 7.3
4. Invoke the same command again and see that it passes successfully 

### Your Environment
Build scan URL: https://gradle.com/s/k5j5dqo4fth3i

### PR DESCRIPTION
**Pull request by octylFractal**
This reverts commit 97a5545bffb0a40da55aceeaf2a678117c5785bf.

Fixes #19088.

This change will be reintroduce (with other changes) in Gradle 8.0. Tracking issue will be #12388.

### CODE REVIEW

**Review by big-guy — APPROVED** [review]

**Review by donat — APPROVED** [review]
LGTM.

I think it would be worth mentioning the removal of the strict mode and the disappearance of `nullableTransformer` in the upgrade guide.

**Comment by ljacomet** [comment]
@donat That transformer was never released though, right? I mean it is not part of Gradle 7.3 and so can be removed without any warning IMO.

**Review by ljacomet — APPROVED** [review]

**Comment by octylFractal** [comment]
Confirmed the above from @ljacomet is correct.

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Pull request merged**
