### PR TITLE
Let `signing` plugin publish signatures with configuration caching

### PR DESCRIPTION
**Pull request by bamboo**
By not checking if the original file exists too early in the process.

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Review by tresat — APPROVED** [review]

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by gabrielittner** [comment]
Will an in memory gpg private key be stored in the cache? Asking because they are passed to the extension as string

**Pull request merged**
