### PR TITLE
Pass executable setting to Scala Compiler

### LINKED ISSUE #10685: ScalaCompile task does not respect all JavaForkOptions configuration
### Current Behavior
Configuring fork options on `ScalaCompile` tasks such as `executable` should affect the subsequently launched Scala compile daemon. For example given a script with configuration like below:

```
compileScala.options.forkOptions.executable = 'path/to/some/jdk/bin/java'
```

We would expect Scala compile daemon to be forked using the configured Java executable but that is not the case, this configuration get dropped. When we merge Scala and Java fork options [here](https://github.com/gradle/gradle/blob/a97d31bafe72f212f7cc71d428d5a77ff473ad48/subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/DaemonScalaCompiler.java#L76) we lose a bunch of configuration on `JavaForkOptions`, such as `executable`, `boostrapclasspath` and others. This makes it currently impossible to cross-compile Scala code with a JDK other than the Gradle runtime JDK. This is problematic since Scala still recommends that the [compiler be run with Java 8](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#running-versus-compiling) despite running Gradle with more modern JDKs being increasingly common. This same issue seems to [exist for Groovy](https://github.com/gradle/gradle/blob/a97d31bafe72f212f7cc71d428d5a77ff473ad48/subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java#L88) as well.

### PR DESCRIPTION
**Pull request by jbaiera**
JDK8 is the only supported java runtime to execute some versions of the
scala compiler on, which means that any gradle project using a newer
JDK version cannot compile scala code for older versions of scala
unless the executable for the scala compile task is respected.

This PR copies the executable setting from the java fork options on the
scala compile specification to the fork options used to launch the
compile daemon process.

Signed-off-by: James Baiera <james.baiera@gmail.com>

Fixes #10685

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by jbaiera** [comment]
Just checking in, is anything else needed for this PR?

**Comment by jbaiera** [comment]
I don't think user guide/docs would need to see any updates for this change since it's fixing a problem with passing a setting through, and isn't really user facing. I'm not sure how best to set up an integration test for this change since it requires multiple java home paths to be sensible. Happy to engage with any feedback on that though.

**Comment by mark-vieira** [comment]
Hey @ljacomet any thoughts on this?

**Comment by mark-vieira** [comment]
Thanks, @ljacomet! Jimmy will get right on adding the integ test coverage.

**Comment by mark-vieira** [comment]
@ljacomet Jimmy has added some coverage here, do you mind taking another look?

**Comment by ljacomet** [comment]
The test failures are caused by Gradle running against JDK14 while the support for it is not in this PR yet.

Could you rebase (preferred) or merge the latest master?

**Comment by ljacomet** [comment]
Aside from the conflict, which hopefully is easy to fix, the integration test is failing on Windows.
@jbaiera Can you take a look?

**Comment by jbaiera** [comment]
I'll see if I can troubleshoot the test failure later today. I don't imagine it to be too much to get back to green since the tests aren't changed very much.

**Comment by jbaiera** [comment]
The windows build issue should be resolved now - It was mismatching the paths due to normalization. Also fixed some issues with the test assumptions. Should be good for another check!

**Comment by mark-vieira** [comment]
Thanks, @ljacomet!

**Pull request merged**
