### PR TITLE
Fixed spelling of "Windows".

### PR DESCRIPTION
**Pull request by iluxonchik**
Fixed spelling from "Windowz" to "Windows".

### CODE REVIEW

**Comment by mark-vieira** [comment]
@iluxonchik, could you please sign our [contributor license agreement](https://gradle.org/contributor-license-agreement/)? We cannot merge your changes until we receive a signed CLA. Thanks.

**Comment by iluxonchik** [comment]
@mark-vieira sure, just signed

**Comment by mark-vieira** [comment]
Thanks @iluxonchik. This will be included in Gradle 2.11.

**Comment by iluxonchik** [comment]
@mark-vieira you're welcome, glad to help :smile:

**Pull request merged**
