### PR TITLE
Some initial caching of tooling API models when isolated projects is enabled

### PR DESCRIPTION
**Pull request by adammurdoch**
Fixes #?

### Context

Adds support for caching tooling API models and the results of build actions when isolated projects is enabled.

There are a number of known issues with the caching:

- Does not work when the tooling API client also specifies some additional tasks to run. This includes specifying an empty list of names, which IDEA and Studio currently happen to do. The current contract unfortunately means "see if the build logic happens to hack the `StartParameters` to add some task names" and, equally unfortunately, this contract is taken advantage of.
- The validation does not seem to scale very well, and so ruins the performance of the Gradle invocation that writes the cache entry. Exactly which part of the validation does not scale is currently not known.
- The "BUILD SUCCESSFUL" message is missing from the console output when the cache entry is reused.
- Does not yet work with composite builds.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
There are some conflicts now.

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Pull request merged**
