### PR TITLE
Fix Kotlin DSL regression via `-XXLanguage:+DisableCompatibilityModeForNewInference`

### PR DESCRIPTION
**Pull request by bamboo**
See #15617
See https://youtrack.jetbrains.com/issue/KT-44303

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test QF

**Comment by bamboo** [comment]
@bot-gradle test this

**Review by eskatos — CHANGES_REQUESTED** [review]
Adding this flag produces the experimental compiler flag warning again :(

```
> Task :compileKotlin
w: ATTENTION!
This build uses unsafe internal compiler arguments:

-XXLanguage:+DisableCompatibilityModeForNewInference

This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!
```

**Comment by bamboo** [comment]
I think we should simply silence this one and move on. We can bring back some of the task log message filtering implementation and put it behind a reflection hack this time to avoid misuse.

**Comment by rieske** [comment]
Will handle the compiler warning in a subsequent change.

**Comment by bamboo** [comment]
\o/

**Pull request merged**
