### PR TITLE
Improve deprecated configuration role warning URL

### LINKED ISSUE #26139: Add explanation for deprecations to dependency management documentation

### PR DESCRIPTION
**Pull request by jvandort**
Add a small section in declaring_dependencies.adoc explaining what a deprecated configuration role is

Fixes #26139

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test bd

**Review by ov7a — APPROVED** [review]

**Review by big-guy — APPROVED** [review]
otherwise LGTM

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
