### PR TITLE
Fix broken assertions for gcc toolchain tests.

### PR DESCRIPTION
**Pull request by DPUkyle**
While looking through #20310 , the author mentioned that some of the existing tests weren't working. Indeed, the implicit assertions buried within a closure were returning false but not failing the tests.

I checked with @leonard84 who shared the [modern way](https://spockframework.org/spock/docs/2.1/release_notes.html#_code_argument_constraints_are_treated_as_implicit_assertions) to check these conditions.

I've updated the test to use this method and confirm it now passes on CI. Note that I have changed the test conditions to make it pass, but I'm not sure whether this behavior is truly expected or not. As such, I'm open to suggestions/fixes to the production code as well.

Note I've seen some flakiness from `o.g.a.i.c.LibrariesSourceGeneratorTest.generated sources can be compiled` on java 8, but I don't see how it's related.

### CODE REVIEW

**Comment by DPUkyle** [comment]
@bot-gradle test this

**Comment by DPUkyle** [comment]
@bot-gradle test this

**Comment by DPUkyle** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by DPUkyle** [comment]
@bot-gradle test and merge

**Pull request merged**
