### PR TITLE
Don't warn on bad combinations of configuration usage for legacy confs

### LINKED ISSUE #24197: Gradle 8 reports incorrect Configuration flags despite being configured correctly
As part of the [Nokee project](https://nokee.dev), we encountered the following erroneous reporting from Gradle information log.

### Expected Behavior

There shouldn't be any information logs printed out for each consumable `Configuration`.

### Current Behavior

Gradle reports the following for each consumable `Configuration` part of a dependency resolution:
```
The configuration :fooElements is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
```

### Context

The reports come from [`DefaultConfiguration#logIfImproperConfiguration`](https://github.com/gradle/gradle/blob/5c9b8ef4c2d2ff0760e5d12dc8aa409e0e692fa4/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1743). However, it seems by default `canBeDeclaredAgainst` comes from this new, half-implemented feature,  `ConfigurationRole`. There is no mention in the release notes of any changes with regard to role-at-creation for `Configuration`. It's possible to change the `canBeDeclaredAgainst` flag, but only via an internal setter [`DeprecatableConfiguration#setCanBeDeclaredAgainst`](https://github.com/gradle/gradle/blob/5c9b8ef4c2d2ff0760e5d12dc8aa409e0e692fa4/subprojects/core-api/src/main/java/org/gradle/internal/deprecation/DeprecatableConfiguration.java#L125). In fact, that method is marked as 8.1 which seems to have leaked into Gradle 8.

### Steps to Reproduce 

Suppose the following code:
```
configurations.create('fooElements') {
  canBeConsumed = true
  canBeResolved = false
  attributes {
    attribute(Attribute.of("my.attribute", String), "value")
  }
}

configurations.create('foo') {
  canBeConsumed = false
  canBeResolved = true
  attributes {
    attribute(Attribute.of("my.attribute", String), "value")
  }
}

dependencies {
  foo project
}

tasks.register('sayHello') {
  doLast {
    println 'Hello, world!'
    configurations.foo.resolve()
  }
}
```

Executing `./gradlew sayHello -i` will report incorrect `Configuration` flags.

### Your Environment

Build scan URL:

### PR DESCRIPTION
**Pull request by tresat**
Fixes #24197

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
I don't understand why we're logging at all. This is only going to log first-party configurations since all user-created configurations are LEGACY. Therefore, this log is not actionable.

**Comment by tresat** [comment]
It's an early warning that something will eventually change and to avoid depending on this behavior.  After this change it should be really infrequent, since there aren't many of these.

**Review by ghale — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
