### PR TITLE
Allow opting-out of legacy Maven/Ivy behavior of looking for a jar when metadata is missing

### LINKED ISSUE #3623: Don't look for jars if pom file is missing when legacy Maven behavior is disabled
Provide a way to opt-out of the legacy Maven behavior, which is to try to find a jar file if a module doesn't provide a pom file. This can lead to lots of unnecessary network requests when a module will __not__ be found in a specific repository.

### PR DESCRIPTION
**Pull request by melix**
This pull request implements a way to opt-out from the legacy Maven (and Ivy) behavior of looking for a jar file whenever the module metadata file was missing (POM or ivy file). Looking for a jar is inefficient for most of the cases, where artifacts are published properly with metadata: in this case, the POM or Ivy file would tell that the module exists. However, historically, Gradle has allowed missing metadata, in which case it would look for a jar, and if it was found, infer module metadata.

The problem with this approach is that for each miss in a repository we issue an additional `HEAD` request, to check if the artifact is available. Depending on the number of repositories, this could introduce a significant slowdown.

It is now possible to opt-out by declaring the repository metadata sources:

```
repository {
    maven {
        url = '...'
        metadataSources {
           gradleMetadata() // first try with .module
           mavenPom() // then fallback on POM files
           // stop here
        }
    }
}
```

This flag is not specific to user-defined repositories: it is also possible to use it on any external repository:

```
repositories.all {
   metadataSources {
      gradleMetadata() // Gradle metadata
      artifact() // fallback on artifact
   }
}
```

The PR still misses some DSL shortcuts to avoid using class literals.

Closes #3623

### CODE REVIEW

**Comment by bigdaz** [comment]
Looks like you've missed the 'list versions' case: we also check for artifact files when trying to work out which versions of a module are present in a repository. https://github.com/gradle/gradle/blob/531b7cd1b3f76931a63b0a821785f51e6721e0af/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/ExternalResourceResolver.java#L175-L178

**Comment by melix** [comment]
@bigdaz I have pushed the current state of the refactoring. I still need to change a couple of things, and probably introduce some DSL shortcuts, but it should give you an idea of what I implemented.

**Comment by melix** [comment]
@bigdaz PR is ready for review.

**Comment by bigdaz** [comment]
This was superseded by #3706 and #3707

**Pull request closed without merging**
