### PR TITLE
Add --show-version switch

### PR DESCRIPTION
**Pull request by leonard84**
### Context
Prior to this PR gradle could only print the version or perform another task.
This PR adds a new set of flags '-V', '--show-version' which print the version and continue on with the regular execution.
To achieve this, the interface `ComposableAction` is added which can be returned from `CommandLineAction.createAction` instead of a plain `Runnable`,
to indicate that the action can be composed with others.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by leonard84** [comment]
@lptr if you think that the approach in this PR is viable, then I'll add the user docs.

**Comment by lptr** [comment]
Could you give some context around this? What is the use case? Can we instead simply add something like `println gradle.version` in a build script or an init script where we need the version number?

**Comment by lptr** [comment]
Is this a typical feature perhaps for command-line tools? I'm not aware of this pattern, though I'm not well-versed in CLI tools.

Can't the user just run `./gradlew --version` first, and then run the build afterwards?

**Comment by leonard84** [comment]
@lptr it's is a feature I miss when comparing Gradle to Maven, which has this functionality. 

It is commonly used in ci environments, to quickly show which gradle version/jvm was used in that build without having to open a buildscan (if GE is even used). Currently, this requires two invocations of gradle, or as you suggested some custom `println` code added to the build (which is a non-portable solution and does not help if something breaks before).

See these two examples:
https://github.com/spockframework/spock/blob/3ebb5d38f1a342935c97f4c331276ae4bcf515f6/.github/workflows/branches-and-prs.yml#L61-L64
https://github.com/junit-team/junit5/blob/709fd6e1d6d311a5950e0a957283ac37530e41fd/.github/workflows/main.yml#L67

**Comment by tresat** [comment]
We are going to merge https://github.com/gradle/gradle/pull/20374, instead, which builds off of this solution.  We think the implementation there is a little clearer, and the related cleanup improves the overall clarity of `DefaultCommandLineActionFactory`.

**Comment by leonard84** [comment]
Thanks for picking it up and improving the design @tresat

**Pull request closed without merging**
