### PR TITLE
Intern more paths/path segments for file snapshots

### PR DESCRIPTION
**Pull request by wolfs**
It seems like https://github.com/gradle/gradle/commit/f781104015885c7d42495dace0935ad00b555a3c caused quite an increase on memory usage for multi project builds. We observed this in an increased Garbage collection time when building `sanityCheck` on Gradle itself (10s -> 2minutes).

This PR reduces the memory footprint by interning path segments and relative paths in file collection snapshots.

### CODE REVIEW

**Comment by oehme** [comment]
I wonder why our performance tests didn't indicate this earlier, they have 100K class files, so you would think they would run into this. Is there some case they are not capturing well? Or do they just have too much heap space assigned so we don't notice?

**Comment by oehme** [comment]
I checked and this significantly improves memory usage for our large test projects, they probably just have too much memory for their needs. I think we could lower both of them to 1G heap (compilation is out of process).

The duplication is still there in CachingPatternSpecFactory#CacheKey by the way. I.e. each segment is in memory twice.

**Comment by wolfs** [comment]
Yeah, I was also surprised that no performance test failed. 👍 for to lowering the heap for both of them.

I guess the duplication in CachingPatternSpecFactory#CacheKey comes from the fact that we do not intern any `RelativePath` segments any more, but only the segments created when snapshotting. When we actually walk the filesystem these segments are not interned any more and end up in `CachingPatternSpecFactory#CacheKey`.

Do you think the duplicate entries in `CachingPatternSpecFactory#CacheKey` can be a problem?

**Comment by oehme** [comment]
They are just as much of an overhead as the duplicate names of the physical snapshots - every single file name is kept in memory twice.

**Pull request merged**
