### PR TITLE
Set context classloader on created threads explicitly to avoid leak

### PR DESCRIPTION
**Pull request by bamboo**
The context classloader of each thread will be set to the context classloader
found during `DefaultExecutorFactory` service instantiation.

This avoids leaks caused by unintentional capture of the context classloader at
thread creation.

See https://github.com/gradle/gradle/issues/16797#issuecomment-818426755

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by jdochez** [comment]
Hey Rodrigo, it fixes part of the leak. I think there are more, I will eventually spend a bit more time on this to confirm or close the issue as fixed.

**Comment by bamboo** [comment]
Thanks, @jdochez!

**Comment by eygraber** [comment]
I am running into this issue with Gradle 7.1. Is there any way to test the fix with a prebuilt binary, or do I need to wait until 7.2 RC is released?

**Comment by eskatos** [comment]
@eygraber you can try a nightly, see https://gradle.org/nightly/

**Pull request merged**
