### PR TITLE
Introduce test fixtures for TestKit

### PR DESCRIPTION
**Pull request by bmuschko**
### Context

- Reduces boiler plate code in functional tests leading to more maintainable tests
- Provides a test framework-specific implementation

For some reason the Spock implementation doesn't work properly yet. The test `FixturesEndUserIntegrationTest.can use Spock-based test fixture` currently fails.

Whenever a Spock-based test is run it doesn't seem to recognize that the class extends `spock.lang.Specification` and executes 0 tests. I suspect an issue in `RuntimeShadedJarCreator`. If I unzip the generated TestKit runtime JAR and repackage with the `jar` command (e.g. `jar cvf gradle-test-kit-4.2-20170811040000+0000.jar *`) then it magically works. Any ideas would be appreciated!

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs

### CODE REVIEW

**Comment by wolfs** [comment]
I think you need to add `spock/lang` to the excludes for relocation: https://github.com/gradle/gradle/blob/3a59865d436691fc1bbf71885b39eb347fabd2cc/subprojects/dependency-management/src/main/java/org/gradle/api/internal/runtimeshaded/PackageListGenerator.java#L51-L69
In order to avoid needing to build Gradle with an updated version of Gradle you can set the excludes  directly in the definition of the task: https://github.com/gradle/gradle/blob/b940b51ad55b7b17273f182510160ac738dfdd65/subprojects/runtime-api-info/runtime-api-info.gradle#L28-L31

**Comment by bmuschko** [comment]
@wolfs Good idea but that isn't it. The Spock library is declared with `compileOnly` and therefore is used for shading. I also had a look at the byte code of `SpockFunctionalTest`. The usage of `spock/lang/Specification` is correct in there.

**Comment by ldaley** [comment]
I don't think providing the super classes is a good idea. Super classes are hard to keep compatible over time as they evolve. I think it would be better to just provide focussed fixture utilities that authors can pull into their tests, and possibly a Groovy trait. 

I think we would be better served in the long term to improve our fixtures first, before aiming for minimal boilerplate for users. In this PR, we have just smooshed somethings together.

There are basically three pieces to functional testing:

1. Building projects under test
2. Defining the Gradle invocation(s)
3. Asserting on the outcome

I think we should first focus on a discrete piece that is (1) and incrementally add layers of convenience after that would get us closer to the zero-boilerplate goal of this PR.

I think this PR is trying to address a very real and worthwhile issue. We _should_ make this easier for our users. I think a slightly different, more evolvable and composable, approach is required though. We should do some more design first.

**Comment by bmuschko** [comment]
> I don't think providing the super classes is a good idea. Super classes are hard to keep compatible over time as they evolve.

Thanks for your feedback. I was kind of concerned about that as well. That's why I had actually started with `DefaultFunctionalTestSupport` that can follow the delegation pattern. I guess the use of the class in Groovy test classes would be relatively straight-forward if you apply the `@Delegate` annotation. In Java you'd have to implement the relevant method and delegate to it. Maybe we can split up `DefaultFunctionalTestSupport` into smaller pieces so that users could pick and choose what they want.

> I think we would be better served in the long term to improve our fixtures first, before aiming for minimal boilerplate for users.

This PR was born out of the need to provide test fixtures for the Gradle guides. The only other use case for TestKit I see at the moment in Gradle core are the smoke test for third-party plugins.

> I think this PR is trying to address a very real and worthwhile issue. We should make this easier for our users.

I can only speak for myself but I have probably duplicated a similar setup 3-4 times in my external plugins by now.

>  I think a slightly different, more evolvable and composable, approach is required though. We should do some more design first.

Sounds good. Currently, this work is not lined up with the priorities of the build tool core team. I was doing it on the side lines. We'll see if the need arise anytime soon and then reprioritize.

**Comment by bmuschko** [comment]
Closing the PR for the time being.

**Pull request closed without merging**
