### PR TITLE
WIP Change ImmutableSet builders for Files to LinkedHashSet + unmodifiable

### PR DESCRIPTION
**Pull request by paplorinc**
WIP, it's [a lot slower currently](https://builds.gradle.org/viewLog.html?buildId=23336204&buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux&tab=artifacts&branch_Gradle_Util_Performance=lorinc%2Fimmutable-sets-to-wrappers#%2Fresults%2Fperformance%2Fbuild%2Ftest-results-performanceAdhocTest.zip!%2Fflames), will investigate, why

### CODE REVIEW

**Comment by oehme** [comment]
LinkedHashSet has terrible locality and a huge memory overhead per entry. I see no way this could be faster than ImmutableSet.

**Comment by paplorinc** [comment]
Currently it's not, it's why it's a WIP draft :)

**Comment by paplorinc** [comment]
The JMH benchmarks do show it to be a lot faster: https://github.com/gradle/gradle/pull/9559/files#diff-e8e9ed4326f9761a1fc9c5a036cba0efR45

Will publish it for review once I figure out what's going on

**Comment by vlsi** [comment]
@paplorinc , have you considered use of https://koloboke.com/ ?
It provides fast and memory efficient collections, and it can implement the required interfaces at the same time.

**Comment by oehme** [comment]
Unless we have a flame graph showing this as a bottleneck, I suggest we close and move on to more pressing issues :)

**Comment by paplorinc** [comment]
This can be closed indeed, thanks @vlsi and @oehme for the reactions.

**Pull request closed without merging**
