### PR TITLE
Fix integer overflow during resolved artifacts comparing

### PR DESCRIPTION
**Pull request by dimorinny**
Fixes integer overflow during resolved artifacts comparing

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by dimorinny** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

**Review by donat — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle cancel

We still plan to include this for 7.4, but we want to branch first.

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@dimorinny thank you for your contribution!

**Pull request merged**
