### PR TITLE
Add in nullability annotations to getters and setters in `AbstractArc…

### PR DESCRIPTION
**Pull request by mkobit**
…hiveTask`

issue https://github.com/gradle/kotlin-dsl/issues/1206

Signed-off-by: Mike Kobit <mkobit@gmail.com>

### Context

Better `kotlin-dsl` IDE support, and will fail in the future if `kotlin-dsl`

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
I already did most of this in this PR: https://github.com/gradle/gradle/pull/7435

**Comment by mkobit** [comment]
Oh nice! That one adds in some nice `Property`/`Provider integration, so I'll let the Gradle team close this one out in favor of yours. It looks like yours is on track to get merged, but I'll leave this open until they resolve yours.

**Comment by mkobit** [comment]
Looks like this will be resolved in 5.1 from #7435 - closing

**Comment by big-guy** [comment]
Thanks @mkobit, I meant to come back around to this one and close it.

**Pull request closed without merging**
