### PR TITLE
Merge release into master

### PR DESCRIPTION
**Pull request by wolfs**
There were quite a few conflicts: 
```
CONFLICT (content): Merge conflict in subprojects/composite-builds/src/test/groovy/org/gradle/composite/internal/DefaultIncludedBuildTaskGraphParallelTest.groovy
CONFLICT (content): Merge conflict in subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java
CONFLICT (content): Merge conflict in subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalGroup.java
CONFLICT (content): Merge conflict in subprojects/core/src/main/java/org/gradle/execution/plan/OrdinalNodeAccess.java
CONFLICT (content): Merge conflict in subprojects/core/src/main/java/org/gradle/execution/plan/TaskInAnotherBuild.java
```

Mostly between `OrdinalNodeFactory` and the changes in `OrdinalNodeAccess`.

### CODE REVIEW

**Comment by wolfs** [comment]
Looks like I broke the CC tests: https://ge.gradle.org/s/kzojrkinurge2/tests/overview?outcome=failed

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
[finalizer can depend on finalized entry point task and have other dependencies that are finalized by tasks that finalize their own dependencies](https://ge.gradle.org/s/v3efz5h2osyni/tests/:core:configCacheIntegTest/org.gradle.api.FinalizerTaskIntegrationTest/finalizer%20can%20depend%20on%20finalized%20entry%20point%20task%20and%20have%20other%20dependencies%20that%20are%20finalized%20by%20tasks%20that%20finalize%20their%20own%20dependencies?top-execution=1) is still failing on the branch. It is very flaky/fails with configuration caching.

**Comment by bamboo** [comment]
Thanks, @wolfs. I'll take a look.

**Comment by wolfs** [comment]
@bot-gradle cancel

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
