### PR TITLE
Fix Property Upgrade codegen default values

### PR DESCRIPTION
**Pull request by asodja**
Now we return default value instead of directly call `.get()` since property could be empty.

Fixes https://github.com/gradle/gradle/issues/25835

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Review by mlopatkin — APPROVED** [review]
lgtm

**Comment by asodja** [comment]
@bot-gradle test and merge

**Review by h0tk3y — COMMENTED** [review]
LGTM

**Pull request merged**
