### PR TITLE
Do not resolve FileCollections in non-file task inputs

### PR DESCRIPTION
**Pull request by lptr**
`FileCollection` instances should not show up as regular `@Input` properties.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by lptr** [comment]
@bot-gradle test and merge this.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by lptr** [comment]
@bot-gradle test and merge

**Pull request merged**
