### PR TITLE
Adds `plusAssign` to Kotlin Property DSL extensions

### PR DESCRIPTION
**Pull request by gmazzo**
### Context
https://blog.gradle.org/simpler-kotlin-dsl-property-assignment mentions the addition of `=` overload operator for `Property` API, but it seems you didn't include the possibility of using `+=` for appending elements to a `ListProperty`, `SetProperty` or `MapProperty`.

This PR contributes to `PropertyExtensions.kt` by adding some `plusAssign` extension functions for them, for single and multiple elements (but excluding `vararg` or `Pair`s for map)

I couldn't find test/intTests for `PropertyExtensions.kt`, I can add them it's required.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by asodja** [comment]
Thank you for the contribution and interest in the better Kotlin DSL. 

Unfortunately we can't accept the PR right away, since we want to be consistent across supported DSL languages, and we cannot implement `+=` for Groovy that easily. We are working on a spec that should also address the `+=` issue in general and we plan to implement it in one of next releases.

If it's ok with you I will keep the PR open since we might use it as part of that work, but we might also reimplement the thing on our own.

**Comment by gmazzo** [comment]
> Thank you for the contribution and interest in the better Kotlin DSL.
> 
> Unfortunately we can't accept the PR right away, since we want to be consistent across supported DSL languages, and we cannot implement `+=` for Groovy that easily. We are working on a spec that should also address the `+=` issue in general and we plan to implement it in one of next releases.
> 
> If it's ok with you I will keep the PR open since we might use it as part of that work, but we might also reimplement the thing on our own.

Fair enough, I totally forgot about Groovy once again.

**Comment by lptr** [comment]
Thanks again for your contribution. We are planning to implement this in another way soon that also supports Groovy. I'm going to close this now.

**Comment by gmazzo** [comment]
> Thanks again for your contribution. We are planning to implement this in another way soon that also supports Groovy. I'm going to close this now.

Would you mind sharing the PR here once is ready? I'd like to take a look at the approach

**Pull request closed without merging**
