### PR TITLE
Help the IDEs to infer the correct types on Closure parameters

### PR DESCRIPTION
**Pull request by hegyibalint**
Fixes [#27077](https://github.com/gradle/gradle/issues/27077)

Issue [#27077](https://github.com/gradle/gradle/issues/27077) describes the situation pretty well, but the issue in a nutshell:
 We don't annotate our Closure parameters well. This causes the `it` parameter's type to not be inferred by the IDE. This is a suboptimal IDE experience.

## Work being done by this PR

This PR should mitigate and prevent such cases in the future:

Mitigation should be done by simply supplying the annotation for our current use cases.
 - Actual code (i.e. `Closure` parameters) are the simplest: we should add the annotation
 - Code generation should be fixed so the `Closure` methods generated from an `Action` parameter are correctly annotated.

Prevention:
  - An ArchUnit rule should be made so no Closure methods could be introduced without the proper annotations

### CODE REVIEW

**Comment by donat** [comment]
This is still relevant.

**Comment by donat** [comment]
This change is still relevant.

**Comment by hegyibalint** [comment]
Still planned!

**Comment by donat** [comment]
Currently, we don't have the capacity to further look into this issue.

**Pull request closed without merging**
