### PR TITLE
Add missing newlines at gradle script files

### PR DESCRIPTION
**Pull request by hegyibalint**
Bite size version of #24665, focusing on `.gradle[.kts]` files.

### CODE REVIEW

**Review by wolfs — APPROVED** [review]

**Comment by hegyibalint** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
> [Pre-tested commit build](https://builds.gradle.org/viewLog.html?buildId=64426107) failed.

Looks like Github checkout problems.

**Comment by hegyibalint** [comment]
Indeed, not the first occurrence this week that GH's git-backend struggles to work.

**Pull request merged**
