### PR TITLE
Add optional support for publication

### PR DESCRIPTION
**Pull request by noproxy**
### Context

Implement #7415

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by noproxy** [comment]
Is there anyone who can help me review the code for any advice? Thank you so much!

**Comment by blindpirate** [comment]
@gradle/dependency-management would you mind taking a look? I think this would be a simple and reasonable improvement.

**Comment by melix** [comment]
The name `optional` is a bit misleading here, as it carries a _lot_ of context in the Java ecosystem (optional dependencies). I think something like `ignoreIfAbsent` would be closer to the actual semantics of this feature.

However, I'd like to understand a bit more about the context: you're adding an artifact to a publication, which is an _additional_ artifact, and say that it's produced by the `javadocJar` task (or any other task, just an example). Then Gradle should automatically execute `javadocJar` and find the appropriate artifact. If it's missing, it probably means you disabled the task, so the publication is not complete. It sounds like a reasonable, safe, behavior to fail here: you probably don't want to publish _without_ javadocs. Can you give us some use cases where it actually makes sense to ignore?

**Comment by noproxy** [comment]
>  I think something like `ignoreIfAbsent` would be closer to the actual semantics of this feature.

I agree with this.

> Can you give us some use cases where it actually makes sense to ignore?

In more complicated scenarios, it is difficult to simply determine whether an artifact will be generated.  For example, in the Android Application project, one of the artifacts of task `processDebugResources` named `R.txt` often needs to be published, because it's need to reduce the android apk size and circumvent some Android system bugs in subsequent product releases. This file is much like symbol table for android resources and can only be generated when the project (including external dependencies) contains specific resources. And even if the required resources exist, AAPT (the compiler) may inline or strip it during compilation, and may not generate the `R.txt` file. So the android developer can only determine if this file will be generated after this task has been executed.

**Pull request closed without merging**
