### PR TITLE
Smoke test Kotlin Gradle Plugin 1.5.0-RC

### PR DESCRIPTION
**Pull request by eskatos**
See https://github.com/JetBrains/kotlin/releases/tag/v1.5.0-RC

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle test ACC

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
