### PR TITLE
 Introduce @RequiresNonFinalSubClasses

### PR DESCRIPTION
**Pull request by eskatos**
Marks a type as requiring non-final subclasses.

Types decorated by the Gradle runtime need to be non-final. This annotation allows
linters, IDEs, DSLs, compiler plugins to validate them or make them non-final.

See https://github.com/gradle/kotlin-dsl/issues/390

### CODE REVIEW

**Comment by big-guy** [comment]
Is there maybe a different way to accomplish this?  To properly use this annotation, you basically need to put this on _every_ type touched by Gradle's instantiator.  This includes all user extensions, objects added to containers, etc.  So it would seem like instead of saying "make sure your type is open", we're instead asking people to add `@ RequiresNonFinalSubClasses`?

https://github.com/gradle/kotlin-dsl/issues/390 isn't clear why this is necessary? If the class is final, you get a decent-ish error message now.

**Comment by bamboo** [comment]
> So it would seem like instead of saying "make sure your type is open", we're instead asking people to add `@RequiresNonFinalSubClasses`?

The `@RequiresNonFinalSubClasses` is meant for annotating user extensible Gradle types such as `Task`.

With that annotation in-place, the Kotlin DSL can configure the allopen Kotlin compiler plugin to automatically open subclasses of the annotated types.

In other words, users won't have to write `open` anymore nor will they have to annotate their classes.

**Comment by big-guy** [comment]
> With that annotation in-place, the Kotlin DSL can configure the allopen Kotlin compiler plugin to automatically open subclasses of the annotated types.
> In other words, users won't have to write open anymore nor will they have to annotate their classes.

This only applies for user types that extend Gradle types.  I would argue that there are many that do not.  As I said above, user extensions need to have `open` (or use this annotation). Elements of domain object containers are another common case.

And then there are things like the worker API (implements Runnable) and dependency management rules (I think most extend some Gradle type).  Anything that Gradle instantiates either needs `open` or this annotation.

It seems to me that it's a lot easier to say "you must always use open" than to explain why you need open sometimes--because it's a type that doesn't extend a Gradle type or we forgot to annotate it.  

I think this comes down to a convenience that doesn't outweigh the costs. If someone forgets _open_, their build just won't work. There's no harm otherwise. I'm 👎 on this.

**Comment by bamboo** [comment]
> It seems to me that it's a lot easier to say "you must always use open" than to explain why you need open sometimes--because it's a type that doesn't extend a Gradle type or we forgot to annotate it.

Agreed.

**Comment by eskatos** [comment]
Agreed too. Let's drop this

**Comment by adammurdoch** [comment]
I think there's some value in statically declaring that a type is intended to be used as part of the Gradle model. I would do this by asking people to use some super type or container type, rather than using an annotation ("container type" just means some kind of composition, not "DomainObjectContainer"). This is because an annotation does not capture all of the aspects of what it means to be used as a model element. For example, it does not expose the extensions of the type nor the lifecycle nor any Gradle provided aspect.

**Pull request closed without merging**
