### PR TITLE
#20612 remove unmappable character (0x9D)

### LINKED ISSUE #20612: error during build: BuildOperationType.java unmappable character (0x9D) for encoding windows-1252
There's something about the quote ` “process”` that causes an error.

https://github.com/gradle/gradle/blob/36cad0c3425102540db84b80ec85702f69b948a0/subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationType.java#L58

 
```
> Task :build-operations:javadoc FAILED 
\gradle\gradle\subprojects\build-operations\src\main\java\org\gradle\internal\operations\BuildOperationType.java:58: error: 
unmappable character (0x9D) for encoding windows-1252
 * completed, in order to ÔÇ£process´┐¢? them on a separate thread.                        
```
 

If I replace it with 'normal' quotes the error seems to go away.

### Your Environment

Gradle repo at this commit: https://github.com/gradle/gradle/commit/36cad0c3425102540db84b80ec85702f69b948a0

Windows 10.

Build scan URL: I can't run a build scan because the Gradle repo is too resource intensive and the tests are too flaky

### PR DESCRIPTION
**Pull request by aSemy**
Fixes #20612

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
@gradle/bt-developer-productivity shouldn't we be passing file.encoding=utf-8 to the forked java compiler?

**Comment by blindpirate** [comment]
@big-guy Yes, I think we should.

**Comment by blindpirate** [comment]
@big-guy Seems like we already configured utf8 for compilation: https://github.com/gradle/gradle/blob/aea7381eb7bd2e045e3f280e30db4085fee76dcb/build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts#L106

**Comment by blindpirate** [comment]
Oh, that error comes from `javadoc`.

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
