### PR TITLE
Fix ordering problems with clean tasks

### LINKED ISSUE #2488: `gradle clean build` can run clean after tasks that produce output by depending on other tasks
If a `clean` task depends on other tasks, `clean` can be reordered and made to run after the tasks that would produce output.  This can lead to build failures or just strangeness with seemingly straightforward builds (e.g., `gradle clean build`).

### Expected Behavior

`clean` would respect "destroyable" information and command-line order.

### Current Behavior

When `clean` depends on another task (the example below uses "clean" from another project, but it can be any task), we seem to reorder the clean task in a way that allows it to run after tasks that produce output and in ways that appear to be the opposite of the user's intention (e.g., we appear to be running `gradle build clean` instead of `gradle clean build`).

### Context

This originally showed up in composite build integration tests, but this occurs in regular multi-project builds too.

### Steps to Reproduce (for bugs)
Given this `build.gradle`:
```
allprojects {
    apply plugin: 'java'
}

clean {
    dependsOn ":sub:clean"
}

dependencies {
    compile project(":sub")
}
```

And `settings.gradle`:
```
include 'sub'
```
Running `gradle clean build` will run `:clean` after everything has been built.

Example output:

> :sub:clean
> :processResources NO-SOURCE
> :processTestResources NO-SOURCE
> :sub:compileJava NO-SOURCE
> :sub:processResources NO-SOURCE
> :sub:classes UP-TO-DATE
> :sub:jar
> :compileJava
> :sub:assemble
> :compileJava NO-SOURCE
> :sub:compileTestJava
> :classes UP-TO-DATE
> :sub:compileTestJava NO-SOURCE
> :jar
> :sub:processTestResources NO-SOURCE
> :sub:testClasses UP-TO-DATE
> :sub:test NO-SOURCE
> :sub:check UP-TO-DATE
> :sub:build
> :assemble
> :compileTestJava NO-SOURCE
> :testClasses UP-TO-DATE
> :clean
> :test NO-SOURCE
> :check UP-TO-DATE
> :build

### LINKED ISSUE #10889: When 'clean' depends on another task, it can happen in the middle of a build, breaking it
### Expected Behavior

Build should not fail.

### Current Behavior

Build fails.

### Context

Because of this issue, I have to run `./gradlew clean && ./gradlew build assembleAndroidTest` instead of a single gradle invocation.

### Steps to Reproduce 

1. `git clone git@github.com:square/leakcanary.git`
2. `./gradlew clean build assembleAndroidTest`

It is possible to make this build succeed by either:
1. Removing `tasks.getByName('clean').dependsOn installGitHooks` from the root `build.gradle` or
2. Adding the following to the root `build.gradle`
```
    def deleteTasks = project.tasks.withType(Delete)
    project.tasks.configureEach { Task task ->
      if (!(task instanceof Delete)) {
        task.mustRunAfter(deleteTasks)
      }
    }
```

### Environment
Nothing special. This is not even my project and I was able to reproduce on my local machine with the repro steps provided above.

### PR DESCRIPTION
**Pull request by ghale**
Fixes #10889
Fixes #2488

### Context
This fixes ordering issues related to running both destroyers and producers on the same command line.  It addresses the problem by introducing "ordinal" nodes in the task graph which allow us to prevent producer tasks from executing before destroyer tasks that may be delayed by dependencies (and vice versa).

For instance, if I run "clean build" I expect all of the clean tasks from a project to run before the build tasks.  If my clean task has a dependency on a task in another project, it will be delayed until the dependency completes.  This allows a "build" task (a producer) to jump in and start executing, which delays the clean task until _after_ the build task.  

The ordinal nodes depend on any dependencies of the clean task and the succeeding producer tasks depend on the ordinal task, which means the producer cannot start until the dependencies of any preceeding destroyer tasks complete and normal task ordering and conflict management will dictate whether the destroyer or producer will run next.  

The same applies for destroyers.  They will depend on any preceding "producer" ordinal nodes and cannot run until the dependencies of any preceding producers are complete.

Tasks that are neither producers or destroyers will not have any relationships to ordinal nodes.

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test RFM

**Comment by ghale** [comment]
@bot-gradle test RFM

**Comment by ghale** [comment]
@bot-gradle test RFM

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by ghale** [comment]
@bot-gradle test RFM

**Comment by ghale** [comment]
@bot-gradle test RFM

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
