### PR TITLE
Allow setting --stacktrace with gradle property

### LINKED ISSUE #13708: Make --stacktrace and --full-stacktrace options available through gradle.properties
Currently, we can configure logging behavior via `org.gradle.logging.level` property in global `gradle.properties`. It would be great - especially for CI environments - to configure the stacktrace default behavior through gradle.properties as well.

### Context

Build problems aren't always very obvious, especially when run non-interactively in a CI environment. Therefore, in such environments, it is usually a good idea to increase logging and stacktrace behavior by default.

There are already ways to do this, but none of them is really great:

- Change stacktrace behavior in build.gradle via `gradle.startParameter.showStacktrace` - Downsides: Has to be done in all projects. Also. this changes the default independent of environment, i.e. also for interactive developer environments.
- Use command line options when calling Gradle in the CI pipeline definition - Downside: This makes Gradle invocations more verbose and tends to get forgotten. Ideally, the pipeline definition should not be concerned with this; we already can define sensible CI defaults for Gradle in most other instances.

### PR DESCRIPTION
**Pull request by donat**
Fixes #13708

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by mihalyr** [comment]
In 8.x this property is still there, but the documentation is missing https://github.com/gradle/gradle/issues/30278

**Pull request merged**
