### PR TITLE
Remove unnecessary modifier of variables inside of Project.java

### PR DESCRIPTION
**Pull request by hotchemi**
- Just removed `public static final` since `Project.java` is interface.

Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

### CODE REVIEW

**Comment by hotchemi** [comment]
🙇

**Comment by lacasseio** [comment]
Thanks @hotchemi for this PR. Unfortunately, one of our engineers already addressed that independently of your PR. I will close it however, I'm looking forward to your next PR.

**Comment by bamboo** [comment]
I'm sorry I haven't noticed this PR. I was working on that file and the unnecessary modifiers bothered me as well.

**Comment by hotchemi** [comment]
@lacasseio @bamboo No problem! Thx for the review 😃

**Pull request closed without merging**
