### PR TITLE
Use partial stack traces as key to identify deprecation messages

### PR DESCRIPTION
**Pull request by blindpirate**
In https://github.com/gradle/gradle/issues/16688, a change was made to identify a deprecation message by its message and stacktrace.

However, this caused quite a lot flakiness (10~15%) in `DeprecationHandlingIntegrationTest` because even when two deprecation messages are emitted from the same location, the stack traces at very bottom might be different due to thread pool scheduling.

To resolve this issue, we cut the first 10 lines of stack traces as the "key" to identify a dprecation message. In this way, the change at the bottom of call stack doesn't cause the deprecation message to be re-displayed.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test qf

**Comment by blindpirate** [comment]
@bot-gradle test qf

**Review by jbartok — APPROVED** [review]
LGTM

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
