### PR TITLE
Test Kotlin 2.0.0-Beta1

### PR DESCRIPTION
**Pull request by eskatos**
https://github.com/JetBrains/kotlin/releases/tag/v2.0.0-Beta1

also adding 1.9.21 in favor of 1.9.10 and 1.9.20-RC

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AFT AST APT

**Comment by eskatos** [comment]
@bot-gradle test AFT AST APT

**Comment by eskatos** [comment]
@bot-gradle test AST APT

**Review by ljacomet — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle merge

**Pull request merged**
