### PR TITLE
Remove restriction on subgroups in version catalogs

### LINKED ISSUE #17170: Better error message for typed deps from a TOML file.
put this in your version catalog TOML: 
```
test-containers = { module = "org.testcontainers:testcontainers", version.ref = "testContainers" }
test-containers-junit = { module= "org.testcontainers:junit-jupiter", version.ref="testContainers" }
```

### Expected Behavior

Error message with more detail and a suggested remediation.
```
org.gradle.api.InvalidUserDataException: Cannot generate accessors for test because it contains both aliases and groups of the same name: [containers]
> Cannot generate accessors for test because it contains both aliases and groups of the same name: [containers]
[test-containers] conflicts with [test-containers-junit], add a suffix to [test-containers] to avoid this issue. 
E.g. change [test-containers] to [test-containers-mysuffix] 
```

### Current Behavior

you will get this error:
```
org.gradle.api.InvalidUserDataException: Cannot generate accessors for test because it contains both aliases and groups of the same name: [containers]
> Cannot generate accessors for test because it contains both aliases and groups of the same name: [containers]
```

### PR DESCRIPTION
**Pull request by melix**
This PR removes the restriction that you cannot have an alias which is both an accessor for a dependency (or version or bundle) and a subaccessor for other dependencies. This is now allowed:

```
implementation libs.top
implementation libs.top.bottom
```

Fixes #17170

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
LGTM 👍 

Can you also add something to the release notes for these changes?

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge

**Pull request merged**
