### PR TITLE
Update Gradle Enterprise Gradle plugin to 3.11.4

### PR DESCRIPTION
**Pull request by guylabs**

### CODE REVIEW

**Comment by guylabs** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]

**Review by blindpirate — APPROVED** [review]

**Comment by guylabs** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
Fuck, I know what's going on. Fixing.

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by guylabs** [comment]
@bot-gradle test and merge

**Comment by guylabs** [comment]
Thanks @blindpirate to get this merged!

**Pull request merged**
