### PR TITLE
Fix UndefinedBuildExecutionIntegrationTest

### PR DESCRIPTION
**Pull request by wolfs**
Instead of checking that the Gradle user home does not exist in this test, we check instead that it doesn't contain any project level caches, since that is what we want to avoid.

### CODE REVIEW

**Review by blindpirate — APPROVED** [review]
LGTM, thanks for fixing this this!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@adammurdoch Is the test after my changes still testing what it is supposed to be testing?

**Comment by wolfs** [comment]
@bot-gradle cancel

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
