### PR TITLE
Fix typo in Marge Simpson full name used in sample

### PR DESCRIPTION
**Pull request by LouisCAD**
Her full first name was missing an "r". This PR fixes it.

### Context
This tiny typo appears in the documentation [here](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures).

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] ~Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective~
- [ ] ~Provide unit tests (under `<subproject>/src/test`) to verify logic~
- [ ] ~Update User Guide, DSL Reference, and Javadoc for public-facing changes~
- [ ] ~Ensure that tests pass locally: `./gradlew <changed-subproject>:check`~

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
@LouisCAD could you fix the DCO check? https://github.com/gradle/gradle/pull/13771/checks?check_run_id=866964500

**Comment by LouisCAD** [comment]
@big-guy I could, but that cannot be done through GitHub UI and requires to clone the entire repo or update a fork (if any) for just 2 typos.

There's plenty of repos of Apache 2 Licensed software that don't have this inconvenient requirement, including among your dependencies (e.g. Kotlin).

Can you ditch this apparently unneeded/dissuasive DCO check, at least for minor documentation edits?

**Comment by big-guy** [comment]
@LouisCAD I wish we could.  Thanks for pointing out the typo, I've fixed it on master.

**Comment by LouisCAD** [comment]
> I wish we could

@big-guy Can you tell why you can't?

**Pull request closed without merging**
