### PR TITLE
Fix ElementSource#isEmpty correctly handling empty providers

### PR DESCRIPTION
**Pull request by fawind**
Fixes https://github.com/gradle/gradle/issues/22707

This PR fixes a bug in [`AbstractIterationOrderRetainingElementSource#isEmpty`](https://github.com/gradle/gradle/blob/01dee043b04beb42c77ed9baa8e1baf18ffcd122/subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java#L63-L65) which occurs when an empty provider is added to the ElementSource. Because the ElementSource did not evaluate the contained values of its inserted elements, it would wrongfully report `#isEmpty()` as `false` in such cases, even though `#size()` evaluates to `0` (see the added test case, which would fail before this PR).

To fix this, we have to evaluate the emptiness of all inserted elements. Unfortunately, this breaks constant time access which is needed for `ElementSource#constantTimeIsEmpty`.

### Context

Tried to create a real-world reproducer in a minimal java project here:  https://github.com/fawind/gradle-is-empty-repro

This bug introduces unexpected behavior when e.g. trying to filter configurations with empty `DependencySet`'s. Users can work around by checking for `size() == 0` instead of `isEmpty()` but it's confusing and can lead to subtle bugs in build logic and plugins. Given `DependencySet` extends `java.util.Set`, it should follow its invariants.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test this

**Comment by jbartok** [comment]
@bot-gradle help

**Comment by jbartok** [comment]
@bot-gradle cancel

**Comment by jbartok** [comment]
@bot-gradle clean

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
This PR causes a test failure: `./gradlew plugins:fIT --tests JvmTestSuitePluginIntegrationTest`

**Comment by jbartok** [comment]
@gradle/bt-jvm can you pls. look into the (genuine) failure in `JvmTestSuitePluginIntegrationTest`?
I took a quick look, but it's not clear to me where/how we rely on the functionality changed by this PR. 
It's not directly in the functionality that's being tested. 
The changes made by the PR do make perfect sense, but apparently we somehow rely on how it worked before.

**Comment by tresat** [comment]
The `"Only one suite with a given test type allowed per project (including the built-in test suite)"` test that is failing after the change should still pass.  Adding a second test suite with the same test type remains invalid, and the expected error should still occur.

The change to `constantTimeIsEmpty()` looks safe to me, and the test passes with just this change.  The change to the `isEmpty()` calculation prevents the realization of lazy attributes in `DefaultMutableAttributeContainer#realizeAllLazyAttributes()` from running, as the `lazyAttributes` container will only possess a single, unrealized provider (i.e., an `element` with `size() == 0`) when the check is made.  This will prevent the modified `isEmpty()` check from returning `false`.  

Unfortunately, that single, unrealized provider needs to be realized to needed to drive the duplicate test type check and print the expected message.

It looks like there are 2 problems, one easy to fix and one harder.  The easy one: In that `realizeAllLazyAttributes()` method, I think we should be fine to drop the if empty check.  It looks like solely an optimization - if `lazyAttributes` is truly empty, there will be no keys, so there will be no insertions.

The harder one: In `JvmTestSuitePlugin` there's a block which adds an artifact lazily:
```java
    variant.getOutgoing().artifact(
        target.getTestTask().flatMap(AbstractTestTask::getBinaryResultsDirectory),
        artifact -> artifact.setType(ArtifactTypeDefinition.DIRECTORY_TYPE)
    );
```
With the change to `isEmpty`, the artifact is never resolved for the outgoing variant, since the `org.gradle.api.artifacts.Dependency` is now determined to be empty.  The lazy artifact added in the code above, doesn't cause the the changed empty check to return `false`.  This prevents the `realizeAllLazyAttributes()` method from being called at all.

I'm surprised this is the only test that fails with this change.  I'd suggest adding a simpler case and making sure it works:

1. Create a new outgoing variant
2. Add an artifact to it using the same lazy syntax as above
3. Resolve that variant
4. Assert that the artifact was resolved (the current changes should prevent this)

@big-guy - What do you think?

**Comment by tresat** [comment]
Forgot to mention, when debugging this, changing `isEmpty` to:

```java
    @Override
    public boolean isEmpty() {
        boolean newIsEmpty = true;
        for (Element<T> element : inserted) {
            if (element.size() != 0) {
                newIsEmpty = false;
                break;
            }
        }
        return inserted.isEmpty();
    }
```

and add a conditional breakpoint on the return `newIsEmpty && !inserted.isEmpty()` makes it easy to see where the behavior will change.

**Comment by ljacomet** [comment]
@tresat Can you make a decision about this issue for Gradle 8.1?

**Comment by tresat** [comment]
@ljacomet - I'm bumping this to 8.2, as I haven't heard anything further from the committer yet and don't have a solution to the issues preventing merging this change as is.

**Comment by fawind** [comment]
Sorry for the silence on my side. Definitely appreciate the review and comments here! Thanks!

Tbh, I expected this to be a simple fix. I'll try to find some time the upcoming weekend to think about the two problems outlined by tresat [here](https://github.com/gradle/gradle/pull/23059#issuecomment-1420959296). But I'm very unfamiliar with the code base so not sure if I can drive the PR to completion without additional guidance.

I'll start with adding a test case for the variant with a lazy artifact and see where the blockers are. But if one of you wants to take this over, feel free to do so!

**Comment by tresat** [comment]
@fawind - It's not a problem, we're just cleaning out issues for the next upcoming release and don't have the capacity to work on this any further right now.  Especially since we're not quite sure what a solution would look like.  

If you are able to experiment some more with this, we'd be very interested to see what you come up with.

**Comment by tresat** [comment]
@fawind - Any update on this?  I'm bumping this to 8.4 for now, unless you've got something immediately ready here.

**Comment by fawind** [comment]
> @fawind - Any update on this? I'm bumping this to 8.4 for now, unless you've got something immediately ready here.

Sorry, no meaningful progress on my side and unsure if I'll get to anything in the near future. Bumping sounds good. Also feel free to close out this PR and continue tracking in https://github.com/gradle/gradle/issues/22707 until we have a more concrete fix here, if you prefer!

**Comment by cobexer** [comment]
This issue needs a decision from the team responsible for that area. They have been informed, and it is on their triage board. 
***
Hey @gradle/bt-jvm do you plan to address this issue, or should it be closed?

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by fawind** [comment]
Thanks for pushing this through! 🎉

**Pull request merged**
