### PR TITLE
Backport "Fix incremental compilation with modules" to 7.6.1

### LINKED ISSUE #23224: Backport to 7.6.1 "Fix for Incremental compilation with modules"
Backport #23119 to 7.x line to fix https://github.com/gradle/gradle/issues/23067 in 7.x line.

### PR DESCRIPTION
**Pull request by asodja**
Backport from #23119 to 7.6.1.

Also backport from #23251 to 7.6.1 
    
Fixes #23224

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
