### PR TITLE
Require JDK 18 instead of Python for serveDocs

### PR DESCRIPTION
**Pull request by octylFractal**
This removes a requirement on an unrelated language. It also allows the build to auto-provision the JDK once Adoptium releases it, reducing friction for testing doc changes.

### CODE REVIEW

**Review by tresat — APPROVED** [review]

**Review by big-guy — APPROVED** [review]
I think it would be interesting to also try to use `RunApplication` instead of `JavaExec` because that should allow us to support `-t`

**Comment by octylFractal** [comment]
`RunApplication` can't be used as it doesn't allow controlling the Java launcher. We could add that feature in another PR, update our nightly wrapper, and then make the change to `RunApplication`.

**Comment by octylFractal** [comment]
Delaying the merge of this until Adoptium offers JDK 18 on all OSes, see progress at https://github.com/adoptium/adoptium/issues/131.

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Pull request merged**
