### PR TITLE
Migrate BuildCache properties

### PR DESCRIPTION
**Pull request by abstratt**
### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by abstratt** [comment]
@bot-gradle test PRF

**Comment by abstratt** [comment]
@bot-gradle test PRF

**Comment by abstratt** [comment]
@bot-gradle test PRF

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Pull request merged**
