### PR TITLE
GRADLE-1574 fix

### PR DESCRIPTION
**Pull request by idlsoft**
Adds a wildcard exclusion for non-transitive dependencies, fixes [GRADLE-1574](https://issues.gradle.org/browse/GRADLE-1574).
Wildcard extensions are supported since [MNG-3832](https://issues.apache.org/jira/browse/MNG-3832) was resolved.
Related post: http://www.smartjava.org/content/maven-and-wildcard-exclusions

### CODE REVIEW

**Comment by adrianbk** [comment]
@idlsoft Thanks for the contribution. Could you please sign the [CLA](https://gradle.org/contributor-license-agreement/)?

**Comment by idlsoft** [comment]
Done

**Comment by bigdaz** [comment]
One thing we'd want to test for is that when a Gradle build depends on the published maven module, we get the same dependencies resolved as when we depend on the project itself.

So if I have `projectB` that has a _non-transitive_ dependency on `moduleC` and a transitive dependency on `moduleD`, then we get the same result for an `projectA` that has:
- A compile dependency `project(":projectB")`
- A compile dependency `org.mystuff:projectB:1.0` (the maven publication of `projectB`)

In the test case, both `moduleC` and `moduleD` should have a dependency, to ensure the transitivity is honoured only where it should be.

**Comment by idlsoft** [comment]
The scenario you're describing is how I encountered the inconsistency in the first place and the reason I wrote the fix.

**Comment by bigdaz** [comment]
Yes, that's why it needs to be covered by an integration test.

**Comment by idlsoft** [comment]
Unfortunately that's outside my expertise, and I'm not sure I'll have the time for it.
In fairness the existing code is not covered, or otherwise it would be failing.

**Comment by bigdaz** [comment]
OK thanks for letting us know, and thanks for your contribution. We have a very strict policy on not making code changes without integration test coverage, so we won't be applying the pull request in it's current state.

I've updated the Jira issue with a link to this PR. Closing for now, until I or someone else has time to pick it up again.

**Comment by idlsoft** [comment]
Superseded by https://github.com/gradle/gradle/pull/570

**Pull request closed without merging**
