### PR TITLE
Add a configure method to the testing block to allow for configuring multiple test suites and avoid duplication

### PR DESCRIPTION
**Pull request by tresat**
Related to #19870 and #19686

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Review by octylFractal — CHANGES_REQUESTED** [review]

**Review by big-guy — CHANGES_REQUESTED** [review]
This is a nice idea, but I don't think we should do this in a special way for test suites. As Octavia pointed out, there's a way to configure multiple things with a single block already. This also encourages more eager configuration by requiring users to get TestSuite instances vs a Provider to them.

I think there are acceptable solutions for now:

- Duplicate the block for each test suite
- Apply the block to "all" test suites (`suites.configureEach {}`)
- Apply the block conditionally to "all" test suites (`suites.configureEach { if (...) {} }`)
- Extract the block to a variable and use it multiple times (`suites.foo.configure(blockVar); suites.bar.configure(blockVar)`)
- Use `project.configure(...)` like Octavia suggested

We could have a `configureEach(String names..., Action action)` (with a better name) that's available on the named domain object container so all containers can do this. This could iterate over `names` and be sugar for `names.forEach(name -> named(name, action))`. 

For now, I wouldn't change anything here. I think we would need to consider a few more things:
- Is the list of names eagerly iterated? If so, is it expected/useful to fail when a name doesn't exist. This is how it would work with the way I described it above.
- If you ask for a name that doesn't exist, should it be created? This is related to the question above. That's what would happen if you tried to do this other ways (e.g., duplicating the configuration).
- Is by name the most useful way to identify elements in a container? e.g., what about types or arbitrary properties?

**Comment by tresat** [comment]
I like the idea of lazy registration with a `configureEach` for suites, but don't we need to specify the type of the suite as to be created (`JvmTestSuite`) well?  I suppose we'd just assume everything we're configuring is that same type.

This was just a quick change per the example in the 7.6 work document.  I didn't realize there was a method on `Project` that would work with these already.  I was aware using the `all` block with a filtering `if` to filter the selection would work, but I didn't think it was something we want to encourage, if we want to emphasize a declarative DSL.  I think it's easier to discuss these alternatives with some real code to look at, this was a quick change I'm happy to throw after in favor of something better.

Extracting a block to use an argument to `configure` is a little unintuitive, but maybe that's all we need.  We should probably add a snippet to the docs demonstrating that if we think it's the best solution.

**Comment by big-guy** [comment]
> I like the idea of lazy registration with a configureEach for suites, but don't we need to specify the type of the suite as to be created (JvmTestSuite) well? I suppose we'd just assume everything we're configuring is that same type.

Right, type is probably important here too. You can always get a more specialized type with `withType(...)`, so `configureEach(String names..., Action action)` would be the type of the container.

> I think it's easier to discuss these alternatives with some real code to look at, this was a quick change I'm happy to throw after in favor of something better.

I don't think this is something we want to recommend right now, but another idea here would be to make it easier to extend `JvmTestSuite` and get all of the same goodies.

So if you had multiple test suites that were supposed to be configured "the same", instead of writing:
```
testing {
    suites {
        integTest(JvmTestSuite) {
            // configuration
        }
        anotherIntegTest(JvmTestSuite) {
            // another copy of configuration
        }
    }
}
```
You could extend `JvmTestSuite` as `MyTestSuite` and write...
```
testing {
    suites {
        integTest(MyTestSuite)
        anotherIntegTest(MyTestSuite)
        withType(MyTestSuite) {
            // configuration
        }
    }
}
```
The test suites would be treated as `JvmTestSuite`s in all other ways, but you'd have a way of identifying them as special and configuring them in their special way.

I think this fits into how we want test suites to be used by other ecosystems. 

> Extracting a block to use an argument to configure is a little unintuitive, but maybe that's all we need. We should probably add a snippet to the docs demonstrating that if we think it's the best solution.

I think "best solution" is a little strong. Inevitably, I don't think test suites are similar enough to one another that it'll make sense to try to de-duplicate a few lines. I think I would follow...

1. Duplicate it
2. If it truly applies to all, use `all`
3. If you have exceptions, make a trade-off between:
- Duplicate it all again
- Extract the common configuration to a block and apply that to the right elements
- Use `all`, but filter things out with an `if`

None of these are wrong. They just span the gamut between declarative and imperative.

**Comment by tresat** [comment]
> You could extend `JvmTestSuite` as `MyTestSuite`

I was wondering how this would work, since how would the binding know to create which class for the new interface?  I don't think it does without writing a plugin and re-implementing all the methods in `DefaultTestSuite`:

```
def "custom test suite type with shared config"() {
        given: "a build containing an interface extending JvmTestSuite"
        file("build.gradle") << """
            plugins {
                id 'java-library'
            }

            ${mavenCentralRepository()}

            interface MyCustomSuite extends JvmTestSuite {}

            testing {
                suites {
                    tests1(MyCustomSuite)
                    tests2(MyCustomSuite)

                    withType(MyCustomSuite) {
                        useSpock()
                    }
                }
            }

            task checkConfiguration {
                dependsOn tests1, tests2
                doLast {
                    assert configurations.tests1RuntimeClasspath.files.any { it.name == "spock-core-${DefaultJvmTestSuite.Frameworks.SPOCK.getDefaultVersion()}.jar" }
                    assert configurations.tests2RuntimeClasspath.files.any { it.name == "spock-core-${DefaultJvmTestSuite.Frameworks.SPOCK.getDefaultVersion()}.jar" }
                }
            }
        """

        expect:
        succeeds("checkConfiguration")
    }
```

yields: 

```
* What went wrong:
A problem occurred evaluating root project '5wrdk'.
> Cannot create a MyCustomSuite because this type is not known to this container. Known types are: JvmTestSuite
```

I started to look at adding something like:

```
interface MyCustomSuite extends JvmTestSuite {}
abstract class DefaultMyCustomSuite extends org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite implements JvmTestSuite {
                DefaultMyCustomSuite(String name, ConfigurationContainer configurations, DependencyHandler dependencies, SourceSetContainer sourceSets) {
                    super(name, configurations, dependencies, sourceSets);
                }       
            }

testing {
    suites.registerBinding(MyCustomSuite.class, DefaultMyCustomSuite.class);
}
```

which gets closer, but still yields:

```
* What went wrong:
A problem occurred evaluating root project 'cnyku'.
> Could not create an instance of type DefaultMyCustomSuite.
   > failed to access class org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite$VersionedTestingFramework from class DefaultMyCustomSuite_Decorated (org.gradle.api.plugins.jvm.internal.DefaultJvmTestSuite$VersionedTestingFramework is in unnamed module of loader 'app'; DefaultMyCustomSuite_Decorated is in unnamed module of loader org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ScriptClassLoader @6f28a07e)

```

**Comment by tresat** [comment]
> I think I would follow...
> 
>     Duplicate it
>     If it truly applies to all, use all
>     If you have exceptions, make a trade-off between:
> 
>     Duplicate it all again
>     Extract the common configuration to a block and apply that to the right elements
>     Use all, but filter things out with an if
> 
> None of these are wrong. They just span the gamut between declarative and imperative.

It's probably worth adding a "Sharing Configuration Between Suites" section to the docs with some snippets demo-ing these and noting the preference order and any tradeoffs, as well as showing how to use the `configure` method on `Project`.  

Want me to make a ticket for that for 7.6?

**Comment by big-guy** [comment]
> I was wondering how this would work, since how would the binding know to create which class for the new interface?

Yeah, it's not straightforward to do right now.  One approach would be to get rid of `DefaultJvmTestSuite` and somehow implement it based entirely on the managed properties in `JvmTestSuite`. That's tricky because we have state/bridging in there to keep old behavior working. 

A variant of that is to move some of the implementation into `JvmTestSuite` as default methods or by making `JvmTestSuite` an abstract class. Neither of those options are as neat/clean.

> It's probably worth adding a "Sharing Configuration Between Suites" section to the docs with some snippets demo-ing these and noting the preference order and any tradeoffs, as well as showing how to use the configure method on Project.

That sounds good to me.

**Pull request closed without merging**
