### PR TITLE
Allow overriding of the wrapper network timeout

### LINKED ISSUE #17575: Allow setting a custom timeout for gradle wrapper download
### Expected Behavior
It should be possible to set custom timeouts for the download of the wrapper jar

### Current Behavior
The connect and read timeouts are [hardcoded to 10s](https://github.com/gradle/gradle/blob/f54ff0afbd0b40a6d0cc4cc25d44e909fc1df0dc/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L98..L99)

### Context
This causes us a problem sometimes, in our organisation we don't have direct access to maven central and so set a custom download URL in gradle-wrapper.properties to download from an internal artifact cache that proxies out to central.  When the artifact cache is busy (it has thousands of users, and runs anti virus scans etc) the read can timeout.

I'm happy to contribute a PR for this, however I'd like some advice on the preferred approach?

- Create new properties in gradle-wrapper.properties for the connection and read timeouts
- Read system properties for connection and read timeouts (like [other things](https://github.com/gradle/gradle/blob/f54ff0afbd0b40a6d0cc4cc25d44e909fc1df0dc/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L188) do currently)

Any preference on naming for these properties?
Would it be acceptable to get this in both gradle v6 and v7 (again, happy to contribute)

Thanks!

### PR DESCRIPTION
**Pull request by sll552**
Fixes #17575

### Context
This is a resurrection of #17830 I would like to finish the work done there and get this finalized as the original author seems to have abandoned his PR.

For the general Information on what this change does etc. please see the original PR #17830

I left the commit of the original author intact and did the changes that came up during the review in a separate commit. I don't know if there is any best-practice for this kind of work but I have no problem amending my changes to the original commit if that is required/wanted.

The tests currently fail because of a cast error which I assume was already mentioned in the review comment (`@Option` not supporting `Integer` to `String` conversion) that this could happen. As I am not very familiar with the codebase and how those annotations work I would be grateful for guidance on how to best resolve this.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by sll552** [comment]
@ljacomet @big-guy you were involved in the original PR, maybe you could take a look?

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by sll552** [comment]
No problem, thanks for adding the missing parts and getting it merged 👍

**Pull request merged**
