### PR TITLE
Fix setter selection in presence of a typed and untyped setter

### PR DESCRIPTION
**Pull request by jjohannes**
This is a follow up to #1866
Attempting to fix the issue discovered in #2239

### CODE REVIEW

**Comment by eskatos** [comment]
@jjohannes, @bamboo and I were looking at this a bit more and had the following thoughts.

If there're overloaded setters but none taking an `Object` (e.g. `String` vs. `URI`), then the current fix doesn't work.

Another thing is that there might be performance overhead when running through conversion when it's not needed.

The method could return a specialized/composite `PropertyMutator` depending on the number of setters. For simple cases the existing `FieldBacked*` or `MethodBacked*` `PropertyMutators` would do, but when there's more than one setter then we would use a e.g. `OverloadedPropertyMutator` which delays the resolution until the `value` becomes available and dispatches to the most specific setter.

**Comment by jjohannes** [comment]
In general I agree with all your comments. And yes, the value would already be available for type analysis. So I think delaying the type analysis would not give us any advantage as we will eventually always do it.

I am concerned about performance since this is a pretty hot code path during configuration phase. I don't wanna do any unnecessary additional work here. I think there is no need to turn `JavaReflectionUtil.writeablePropertyIfExists` into a fully sophisticated reflection utility. It should be enough to cover the cases we actually have and do that as efficient as possible.

The existing implementation is efficient by not doing any type analysis, using the assumption that there is only one setter.

The new assumption is that there is, potentially, one generic setter and one specific setter (i.e. String vs. URI is not a real case we need to cover). Having `Object`* for the _traditional_ setters used from Groovy scripts and the typed setter for Kotlin should be enough (if I did not miss anything).

*Looking at #1866 again, we should check for `Iterable` in addition to `Object` to cover multi-value properties.

**Comment by bamboo** [comment]
> The new assumption is that there is, potentially, one generic setter and one specific setter (i.e. String vs. URI is not a real case we need to cover).

Can this code path be executed against arbitrary user types?

**Comment by eskatos** [comment]
In line with Rodrigo's question: a user type could definitely contain overloaded setters but none taking `Object`.

**Comment by jjohannes** [comment]
Follow up PR #2386

**Pull request closed without merging**
