### PR TITLE
Update Groovy to 3.0.10

### PR DESCRIPTION
**Pull request by octylFractal**
Required for JDK 18 support. Partial work on #19283.

### CODE REVIEW

**Comment by octylFractal** [comment]
Waiting on https://github.com/javaparser/javaparser/issues/3516.

**Comment by big-guy** [comment]
@octylFractal could you see if `GroovyCoverage` also needs to be updated?

**Comment by octylFractal** [comment]
`GroovyCoverage` uses the current version + a list of previous ones. No other `3.0.x` is listed here, so I don't think there's a reason to add one, unless you would like to start doing so to be sure we cover all patch versions.

**Comment by big-guy** [comment]
Hrm, there probably should have been a 3.0.x at some point. Don't worry about it now

**Comment by ice1000** [comment]
Nice!!

**Comment by ice1000** [comment]
> Waiting on [javaparser/javaparser#3516](https://github.com/javaparser/javaparser/issues/3516).

HOw is that issue blocking this? Aren't all checks passed here?

**Comment by octylFractal** [comment]
It's a security concern, related to https://github.com/gradle/gradle/pull/20177#commitcomment-68672618 -- I am unsure if the change is intentional, and if it wasn't, then it could be a sign of malicious code. Obviously we prefer not to distribute malicious code :)

**Comment by ice1000** [comment]
https://github.com/javaparser/javaparser/issues/3516#issuecomment-1073128838

**Comment by ice1000** [comment]
I think nothing's blocking this now, right? 😉😉😉😉😉

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by ice1000** [comment]
Noice

**Pull request merged**
