### PR TITLE
Refactor API jar generation

### PR DESCRIPTION
**Pull request by cbeams**
This series of commits refines and restructures the implementation of API member selection and extraction and the subsequent assembly of an `ApiJar` based on that content.

These changes are being submitted as a pull request for several reasons, but primary among them is to prompt a discussion about the future organization and structure of the Gradle codebase. To this end, please read the first five commit messages in this PR (particularly the fifth). For convenience, here they are in order:

1. f216da1dde85e265d11c899f1ecf3914e5efc78a -> 2. 17663638b7be27d68731f09cb344fe59b3332ea2 -> 3. 81837af6325f06bcc0e746fa358508a683824a6b -> 4. 417b36d24174f049304c40a5d0ddb87d93e99915 -> 5. a37a3ef90bc4b56355c48df56d9aee9e3ac9bf95

Together, these commits make a case for careful package design and placement, and in particular make a case for the use of package-private visibility as a mechanism for reducing the surface area of our own public API. In conjunction with our `@Incubating` annotation, better packaging and visibility management can perhaps help us move away from over-reliance on "internal" package techniques.

Package-private visibility is not a panacea and these commits don't intend to make that case. Rather they suggest that we treat it as an important tool in helping us evolve our public API, manage compatibility concerns, and so on.

The remainder of the commits in this PR are also intended to be read in order, but in the somewhat more focused context of a code review of the API jar generation feature itself.

Barring any particular objections, this PR will be merged tomorrow (Friday) after discussion with the original authors of the code that's been refactored here. Again, the PR itself exists primarily as a means of raising awareness about these ideas and a place to discuss them in context.

### CODE REVIEW

**Comment by melix** [comment]
I have no strong objection on the renames (in fact, there is a difference between allowed and exported: allowed packages are not necessarily the same as exported ones. Take the example of the java-base module. It is actually surprising that no test fails after removing `JavaBaseModule`, because it is used in validation).

As for package private classes, I am -1 on this. I don't like this mechanism. For me package privacy is broken. Should have it been inherited by sub-packages, or through class hierarchy (A in package pkg1, B extends A in pkg2, C extends A in pkg1), I would have maybe a different thinking. 

But I *really* like the separation of internal package. It gives a lot of flexibility, and it is actually what is going to be publicized with Jigsaw modules. I am not sure we're not moving in the right direction doing this. In general, I consider that almost all types can be public, and it should be documented when to use or not to use one class. In particular, users might want to use internal classes. I did it in the past, and the fact that it's in a package named "internal" makes you aware that it might be broken in the future, but you are aware. On the other hand, if it had been package private, I wouldn't be able to do it, or I would just have worked around it using a class in the same package. Which is dirty.

Last but not least, `@Incubating` in Gradle has a tradition of saying "it's an experimental API". Yet, they belong to the public API. I don't remember any class marked as `@Incubating` which has been removed. On the other hand, I feel ok to remove, rename or move a class in an internal package. And as soon as it moves into a package that doesn't contain `internal`, to me, it becomes public API.

**Comment by big-guy** [comment]
+1 for moving the task to a "public" package.  We probably want to support users being able to say `tasks.withType(ApiJar) { /* configure */ }`, which means ApiJar needs to be public.

-1 for moving the supporting classes to a non-internal package.  It makes determining what we consider public a lot harder, even if the classes are package private.  We've been trying to move internal-but-not-in-an-internal-package into internal packages over time.

**Comment by cbeams** [comment]
Thanks, @melix and @big-guy; I'll hold off on a response to see if others would like to weigh in too. In the meantime, I just realized that the original PR description called out the first four commits in the series, but it's actually the fifth that is the most important with regard to the visibility and public API surface area conversation. I've updated the description to reflect, but for convenience, here is the fifth commit: a37a3ef90bc4b56355c48df56d9aee9e3ac9bf95

**Comment by bigdaz** [comment]
I'm also -1 on using package privacy for internal classes. I think we give
up more than we gain. I'd be +1 for more consistency with how we structure
our internal packages.
I strongly recommend not making this change without explicit go ahead from
Adam.

**Comment by cbeams** [comment]
Based on feedback thus far, I am holding off on merging this today. Will discuss with @adammurdoch as @bigdaz suggests. Further comments are welcome.

**Comment by cbeams** [comment]
In the interest of not leaving this PR hanging out too long, I have added commit 7eca9ab6822f0a0542072c511fff88e06dfa87aa, which introduces an internal package, moves all supporting types for `ApiJar` into it, and increases their visibility to `public`.

I'll continue the conversation about structure and visibility with @adammurdoch and others, but in the meantime, it's important that this otherwise substantive refactoring doesn't diverge from the rest of the codebase; I'll merge it shortly.

**Pull request merged**
