### PR TITLE
Introduce a node that resolves project dependency artifacts (plus some scheduling refactoring)

### PR DESCRIPTION
**Pull request by adammurdoch**
Fixes #?

### Context

This PR replaces the "task node finalize action" concept with a real node. This was used to inject a pseudo node into the graph in order to finalize the location of a project artifact prior to starting any nodes that use that artifact as input. Now a real node takes care of this. Using a real node removes the special case logic to resolve and manage these actions.

There are some other changes to node scheduling in this PR:

- Start to split the API to construct an execution plan from the API used by workers to run the execution plan.
- Improve reliability of cancelling all queued work when the health monitoring decides that execution is stuck.
- Fix a deadlock when a task and its finalizers are cancelled due to a failure in some unrelated task and `--continue` is not used.
- Use a consistent mechanism to decide whether a node is ready to run, whether that node has dependencies/must run after constraints, is a finalizer, is a dependency of a finalizer or is a node that bridges into another execution plan. Previously each of these was implemented in a different way with the logic spread across a bunch of places in the scheduling algorithm. This also reduces the number of "execution states".

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
I'm going to rebaseline these performance test and invesitgate. They started being flaky since yesterday.

**Comment by adammurdoch** [comment]
Ok, thanks.

**Pull request merged**
