### PR TITLE
fix(cch22-7): `snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule` sample for configuration cache

### LINKED ISSUE #21804: CCH22-7: Adjust the `snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule` sample for configuration cache
The sample project located under [`subprojects/docs/src/snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-dependency-management-customizing-resolution-classifier-substitution-rule_groovy_resolve.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-classifier-substitution-rule_groovy_resolve.sample)
    ```
    Could not find co.paralleluniverse:quasar-core:0.7.12_r3.
    ```

* `snippet-dependency-management-customizing-resolution-classifier-substitution-rule_kotlin_resolve.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-classifier-substitution-rule_kotlin_resolve.sample)
    ```
    Could not find co.paralleluniverse:quasar-core:0.7.12_r3.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-dependency-management-customizing-resolution-classifier-substitution-rule_groovy_resolve.sample" \
    --tests "*snippet-dependency-management-customizing-resolution-classifier-substitution-rule_kotlin_resolve.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/resolution_rules.adoc`;

### PR DESCRIPTION
**Pull request by p1729**
Fixes #21804 

Needs documentation update for changing the dependency version to 0.7.10 since the committed version is no longer in the maven central repository 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Review by h0tk3y — APPROVED** [review]

**Comment by h0tk3y** [comment]
@p1729 The DCO (commit sign-off) check has failed. Could you please check that all of your commits are [properly signed-off](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages)? Feel free to force-push the branch if you need to adjust the commit messages.

**Comment by p1729** [comment]
@h0tk3y signed all the commits

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Pull request merged**
