### PR TITLE
Backport: Rewrite Build Lifecycle documentation in a consistent docs voice

### LINKED ISSUE #23074: Docs: Build Lifecycle starts halfway through a point
The very first sentence of [Build Lifecycle](https://docs.gradle.org/current/userguide/build_lifecycle.html) starts with:

> We said earlier that the core of Gradle is a language for dependency based programming. In Gradle terms this means that you can define tasks and dependencies between tasks. 

This is quite strange to read. If I land directly on this page from a link or Google, then I don't know what was said earlier. 

Suggestions:

* Directly link to the part in the docs that explains what 'dependency based programming' is
   ```markdown
   [We said earlier](https://docs.gradle.org/current/link-to-relevant-docs-page.html] that...
   ```
* Rephrase to read more naturally
   ```markdown
   Gradle is a language for dependency based programming. In Gradle terms this means that you can define tasks and dependencies between tasks. 
   ```

### PR DESCRIPTION
**Pull request by FrauBoes**
### Context

* Backport of #22455

* Fixes #23074

- [Current page](https://docs.gradle.org/current/userguide/build_lifecycle.html#header)
- [Render of the new page](https://builds.gradle.org/repository/download/Gradle_Release7x_Check_BuildDistributions/60570808:id/distributions/gradle-7.6.1-docs.zip!/gradle-7.6.1-20230119131801%2B0000/docs/userguide/build_lifecycle.html)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by FrauBoes** [comment]
@bot-gradle help

**Comment by FrauBoes** [comment]
@bot-gradle test BD

**Comment by FrauBoes** [comment]
@bot-gradle test BD

**Comment by FrauBoes** [comment]
build_lifecycle.adoc [rendered version](https://builds.gradle.org/repository/download/Gradle_Release7x_Check_BuildDistributions/60562850:id/distributions/gradle-7.6.1-docs.zip!/gradle-7.6.1-20230119085341%2B0000/docs/userguide/build_lifecycle.html)

**Comment by FrauBoes** [comment]
@bot-gradle help

**Review by eskatos — APPROVED** [review]

**Comment by FrauBoes** [comment]
@bot-gradle test and merge

**Comment by FrauBoes** [comment]
@bot-gradle test and merge

**Pull request merged**
