### PR TITLE
Let 'init' put convention plugins into an included build (incubating)

### LINKED ISSUE #15326: gradle init should not create buildSrc but use included build logic builds
From what I understand, ``buildSrc`` is discouraged for new projects, since it has a number of disadvantages, maybe the biggest being that any change in it will force a full rebuild.

Because of this, the ``init`` task should be re-written to:
* no longer create ``buildSrc``
* create build plugins instead (maybe put each build plugin inside a ``build-plugins`` directory)
* reference the build plugins from the settings file using ``includeBuild``

Doing this is particularly important since builds created by ``gradle init`` are probably considered "best-practice" by people unfamiliar with Gradle.

### PR DESCRIPTION
**Pull request by jjohannes**
Fixes #15326

### Context

Instead of `buildSrc`, the included build `gradle/plugins` is used (when using 'incubating mode' with 'init').

The build is included via:

```
pluginManagement { 
   includeBuild("gradle/plugins")
}
```

Rational for using `gradle/plugins` as location:

- Putting it as subfolder of `gradle`:
  I think it is good practice to put as much gradle-related files into the `gradle` folder instead of spamming the root with gradle related files and folders. This is also an advantage over 'buildSrc' which is hard-coded in the root. Other build configuration, like the Version Catalog, is also located in `gradle` by default
- Calling it `plugins`:
  In many samples, the folder is called `build-logic` (or some variation of that). By now, I think `plugins` is a better name because that is the term for what folks will put into this folder - local Gradle plugins. `build-logic` on the other hand is yet another term they have to grasp. Also the term 'logic' is debatable if you only define convention plugins (which are more `build-configuration` than `build-logic` imo).

I think this change is quite straight forward. The one thing debatable would be the name and location of the 'plugins build' folder.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- ~Provide unit tests (under `<subproject>/src/test`) to verify logic~
- ~Update User Guide, DSL Reference, and Javadoc for public-facing changes~
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]
:100:

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by vlsi** [comment]
Would you please clarify what is the difference between `pluginManagement { includeBuild(..) }` vs regular `includeBuild(...)`?

It looks like Gradle's build uses `pluginManagement { includeBuild(..) }` for settings plugin only.

Does that mean there should be two folders under `gradle/...` (one for regular plugins, and another for settings ones)?

**Comment by yogurtearl** [comment]
For reference of any one reading this, this PR https://github.com/gradle/gradle/pull/22141 changed `gradle/plugins` to `build-logic`

**Comment by chkpnt** [comment]
@vlsi: "A special case of included builds are builds that define Gradle plugins. These builds should be included using the includeBuild statement inside the pluginManagement {} block of the settings file. Using this mechanism, the included build may also contribute a settings plugin that can be applied in the settings file itself." (https://docs.gradle.org/current/userguide/composite_builds.html#included_plugin_builds)

**Pull request merged**
