### PR TITLE
GRADLE-3276 Generate Scala SDK instead of Scala facet to support Intellij IDEA 14+

### PR DESCRIPTION
**Pull request by nicklasbondesson**
All the details should be in here https://issues.gradle.org/browse/GRADLE-3276

### CODE REVIEW

**Comment by mark-vieira** [comment]
@nicklasbondesson, thanks for the submission. Our bandwidth for reviewing PRs is a little limited at the moment as we are focusing our efforts on getting the Gradle 2.5 release out the door. We will take a look at this as soon as we can.

**Comment by nicklasbondesson** [comment]
@mark-vieira my pleasure. Will someone have a look soon?

**Comment by nicklasbondesson** [comment]
A friendly reminder..

**Comment by bigdaz** [comment]
We appreciate the work put into this pull request.

The Gradle team doesn't currently have the capacity to deal with all of the bugs, feature requests, great ideas and pull requests that we receive. We already have a pretty big backlog, so it might take some time for us to take a look at this.

Pull requests are interesting because they may seem like they come for "free". Our experience has shown that in order to maintain the level of quality and consistency that Gradle users expect, we need to invest significant engineering effort in all but the most trivial PRs.

We are [actively recruiting](http://grnh.se/mbne6o) to increase our engineering team, so hopefully this is a temporary situation. We ask for patience in the meantime.

**Comment by nicklasbondesson** [comment]
Thanks for the update.

**Comment by cwensel** [comment]
This strikes me as quite useful, would be great if this could get reviewed and merged.

**Comment by josefeg** [comment]
Any plans on merging this one in?

**Comment by nicklasbondesson** [comment]
@bigdaz how's the recruiting going? Any chance someone will have a look soon?

**Comment by nicklasbondesson** [comment]
Pinging you @big-guy since you where my first ever Gradle contact. Perhaps you have some time to spare for this?

**Comment by jasonxh** [comment]
I would really love to see this merged as well. Currently it's a very cumbersome process every time there's a dependency change, which involves closing intellij, gradle cleanidea idea, converting project again, rm -fr projectFilesBackup* ...

**Comment by sganslandt** [comment]
+1 on getting this merged. Feeling left behind still having to run IntelliJ 13, especially now that 15 is just released :)

**Comment by ijuma** [comment]
IntelliJ IDEA 15 has pretty good built-in support for Gradle from my experience? Any reason why you can't just use that? (simply curious)

**Comment by nicklasbondesson** [comment]
No reason, just haven't explored that yet.

**Comment by mark-vieira** [comment]
@nicklasbondesson Taking a look at this again I believe this would introduce a breaking change for those folks still using IntelliJ 13. We don't want to lose support for older IDEs so we should continue to support both. This would likely mean adding some property to `IdeaModel` allowing the user to specify which version of the IDE they were using. We could potentially then "break" folks by defaulting to a later version but still allow them to explicitly generate the older metadata.

Would you be up to making the necessary changes to allow for this?

**Comment by nicklasbondesson** [comment]
@mark-vieira Yep, I'm up for it.

**Comment by nicklasbondesson** [comment]
@mark-vieira all done. Can you please take another look?

**Comment by mark-vieira** [comment]
Thanks @nicklasbondesson I hope to take a look at this soon.

**Comment by mark-vieira** [comment]
@nicklasbondesson I'm looking at this now. We are beginning to prepare for the 2.11 release so right now I am looking to get this included in 2.12.

**Comment by nicklasbondesson** [comment]
:+1:

**Comment by nicklasbondesson** [comment]
Looks like Travis is a bit sad. Why is that?

**Comment by mark-vieira** [comment]
Looks like failures due to unrelated changed introduced into master, you can disregard.

**Comment by mark-vieira** [comment]
@nicklasbondesson this has been merged into master and will be included in Gradle 2.12. Thanks for the contribution.

**Comment by nicklasbondesson** [comment]
@mark-vieira Cool, thanks. I can see that you made some modifications to my commit. Is it possible to set the targetVersion property on the IdeaModel from the command line, gradle properties or system properties? I think the best way would be if you could set/override the value from your local environment since it is not certain that everyone on a team will be running the same Idea version.

**Comment by mark-vieira** [comment]
You could simply set `targetVersion` to the value of a project property if it exists.

    targetVersion = project.hasProperty('ideaVersion') ? project.property('ideaVersion') : null

Then you can do something like `gradle build -PideaVersion=13`

**Comment by nicklasbondesson** [comment]
Yeah, that's pretty much what I did. But the code was changed by someone before you merged. Maybe you could add that?

**Comment by mark-vieira** [comment]
The difference being that we don't want to look for this from a project property by default. The source of truth is `IdeaModel.targetVersion`. Whether this is hard-coded in the build script or set to a value retrieved from an external property is not important. We simply want to avoid using implicit properties as inputs to the build. There are several reasons for this:

1. They are difficult to document. It usually means someone has to read the user guide to know about them rather then showing up in the DSL reference and JavaDocs
2. Type safety
3. Extension properties can be set in a nearly unlimited number of ways, project properties are more limited in how they can be set. We are simply aiming for flexibility.

**Comment by mark-vieira** [comment]
Also, just to clarify, my code example above would be something that should be in the build script, not the implementation for the 'idea' plugin.

**Comment by nicklasbondesson** [comment]
Thanks, it all makes sense :+1: I think I was mislead by not seeing the enclosing `idea { }` for the targetVersion assignment in your example before.

**Pull request merged**
