### PR TITLE
Update tests for 3rd-party plugins that are important to GE-Solutions

### PR DESCRIPTION
**Pull request by bigdaz**
These are plugins that the GE-Solutions team has contributed to directly, or are heavily depended-on by our GE customers. As such, we'd like to maintain basic smoke-test coverage for these plugins.

### CODE REVIEW

**Comment by bigdaz** [comment]
@bot-gradle test this

**Comment by bigdaz** [comment]
@bot-gradle test this

**Comment by bigdaz** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]
Thanks @bigdaz

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
