### PR TITLE
Finish Wrapper Provider API migration

### PR DESCRIPTION
**Pull request by reinsch82**
Fixes #?

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test RFN

**Comment by asodja** [comment]
@bot-gradle test RFN

**Review by asodja — APPROVED** [review]
LGTM

**Pull request merged**
