### PR TITLE
Fix JUnit --tests behavior

### PR DESCRIPTION
**Pull request by AlexLandau**
Make parameterized tests work when --tests is used, and when the --tests argument matches a suite name, run the entire suite instead of displaying an error message that no tests matched the name.

Discussion at https://groups.google.com/forum/#!topic/gradle-dev/kmoJwBVGQHg

### CODE REVIEW

**Comment by pioterj** [comment]
@AlexLandau Thank you for the pull request. I added my comments.

**Comment by pioterj** [comment]
This change will also require an update to the design document at https://github.com/gradle/gradle/blob/master/design-docs/testing-improvements.md. I recommend you do it first so we can review test coverage before you start implementing it.

**Comment by AlexLandau** [comment]
I've just gotten back to this.

To catch up these commits with the rest of the codebase, do you have a preference for rebase vs. merge? I'm not exactly sure how Github copes with them on PRs.

**Comment by big-guy** [comment]
I think rebase is better.  If the PR gets screwy, we can close and open a new one.

**Comment by AlexLandau** [comment]
I tried a rebase, but Github required a merge to keep pushing to the same junit-tests-behavior branch. It looks like that in turn messed up the commits list, so I'm just going to start a fresh PR.

**Comment by AlexLandau** [comment]
The new, rebased pull request is #561.

**Pull request closed without merging**
