### PR TITLE
overloaded registerIfAbsent without configurationAction

### LINKED ISSUE #15826: BuildServiceRegistry#registerIfAbsent method without configuration action
Even if you have no parameters to configure for a build service, you always have to have a configure action.
It would be nice if there were an overload without the configure action.

### PR DESCRIPTION
**Pull request by Taz03**
Fixes #15826 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by cobexer** [comment]
Thank you for your contribution!

The [DCO](https://probot.github.io/apps/dco/) check is failing, please look into that as we can't accept the PR otherwise.

***

Please also make sure to add tests verifying the changed functionality.

**Comment by Taz03** [comment]
I'll need some assistance with implementing tests, rn I see [DefaultBuildServicesRegistryTest](https://github.com/gradle/gradle/blob/master/subprojects/core/src/test/groovy/org/gradle/api/services/internal/DefaultBuildServicesRegistryTest.groovy) which tests [DefaultBuildServicesRegistry](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/services/internal/DefaultBuildServicesRegistry.java), but I only added a method in the interface [BuildServiceRegistry](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/services/BuildServiceRegistry.java) so how do I go about tests?

**Comment by cobexer** [comment]
The classes you indicate are the ones to change indeed.
To add a method to an interface, you need an implementation for it. Note that it could be done with a default method instead.

Then you can do the testing through a class testing said implementation, whether you used a default method or not.

**Comment by cobexer** [comment]
Yes, you do, if you don't feel confident enough to do so please close this PR.

**Pull request closed without merging**
