### PR TITLE
Port from Maven 2 to Maven 3

### PR DESCRIPTION
**Pull request by mizdebsk**
This pull request removes dependency on Maven 2. Sonatype Aether an Maven 3 APIs are used for artifact installation and deployment. Maven 3 JARs don't need to be jarjar-ed because there is no conflict with Maven 2 any longer.

Pros:
- Gradle doesn't use EOL Maven 2, which is not supported any longer
- simplified code (deployment with Maven 3 is a bit simpler)
- Maven 3 JARs don't need to be jarjar-ed any longer
- smaller binary tarball (14 dependency JARs are removed)

Possible problems with backwards-compatibility:
- deployment of non-unique snapshot versions is not supported any longer in Maven
3 (I can try to work this around, *if necessary*)
- Maven model API has changed slightly between Maven 2 and 3 (see http://red.ht/1QBND7A)

### CODE REVIEW

**Comment by alkemist** [comment]
Thank you very much for this @mizdebsk. I see that we already have a CLA for you. We'll get this merged soon.

**Comment by mizdebsk** [comment]
Non-unique versions and optional POM dependencies are fixed. All integration tests should be fixed too, except for unrelated failures.

**Comment by mizdebsk** [comment]
Thank you for merging this pull request!

**Comment by adrianbk** [comment]
@mizdebsk your welcome. Thank you for contributing  :+1:

**Pull request merged**
