### PR TITLE
Merge release into master

### PR DESCRIPTION
**Pull request by leonard84**
Manual merge to resolve a Build Scan plugin version conflict.

Signed-off-by: Leonard Brünings <leonard.bruenings@gradle.com>

### CODE REVIEW

**Review by wolfs — APPROVED** [review]

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Review by lkasso — APPROVED** [review]
Docs look good.

**Review by ljacomet — APPROVED** [review]
LGTM

Would have been good to add in the description that the goal is to resolve merge conflict. Took me a while to understand that.

**Comment by wolfs** [comment]
> Would have been good to add in the description that the goal is to resolve merge conflict. Took me a while to understand that.

Good point. I changed the PR name to `Merge release into master`.

**Pull request merged**
