### PR TITLE
Update documentation about caching of unit tests

### PR DESCRIPTION
**Pull request by bean5**
Fixes outdated documentation on caching of unit tests.

### Context
Previous documentation referenced https://issuetracker.google.com/issues/79122161?pli=1 which is duplicate of https://issuetracker.google.com/issues/115873047 which is completed.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by h0tk3y** [comment]
@bot-gradle test ReadyForNightly

**Comment by h0tk3y** [comment]
@bean5 Could you please ensure that your commits are signed-off?

**Comment by h0tk3y** [comment]
Hello @bean5,
Unfortunately, your commit lacks [a sign-off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff), while Gradle only accepts signed-off commits.

If you accept [the developer certificate](https://developercertificate.org/), please update the commit by adding a sign-off and submit the pull request again. Due to the lack of activity for some time, I'm closing this PR. Feel free to comment if you think we should reopen it.

**Comment by bean5** [comment]
@h0tk3y I will submit the pull request again.

**Comment by bean5** [comment]
Re-submitted at #28737

**Pull request closed without merging**
