### PR TITLE
Don't emit synthetic and redundant op notifications in config cache b…

### PR DESCRIPTION
**Pull request by ldaley**

### CODE REVIEW

**Comment by ldaley** [comment]
@bot-gradle help

**Comment by ldaley** [comment]
@bot-gradle PRF

**Comment by ldaley** [comment]
@bot-gradle test PRF

**Review by adammurdoch — APPROVED** [review]

**Comment by ldaley** [comment]
@bot-gradle test and merge

**Comment by ldaley** [comment]
@bot-gradle test and merge

**Pull request merged**
