### PR TITLE
Prepare 6.9.4

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle cancel

**Comment by ljacomet** [comment]
@bot-gradle test BD

**Comment by ljacomet** [comment]
@bot-gradle test BD

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
