### PR TITLE
[WIP] Attach sources to gradleApi()

### PR DESCRIPTION
**Pull request by rieske**
https://github.com/gradle/gradle/issues/1003

Use sources from Gradle installation's `src` directory (available when using`-all` distribution with the wrapper) to package sources inside the classes jar for `gradleApi()` dependency.

### CODE REVIEW

**Comment by eskatos** [comment]
It's great we start working on fixing the non availability of sources in the IDE!

A few questions from the top of my head:
- what happens if I use Gradle on several builds, some configured with the `-bin` distro, some with the `-all` distro? in different usage order
- what's the performance impact on first use or ephemeral CI agents? generated API jars are already contributing a lot
- was on-demand sources download considered? (we have [something specific to the Kotlin DSL IDE support](https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/SourceDistributionProvider.kt) that could be generalized)

**Comment by rieske** [comment]
Thank you @eskatos.
I need to investigate a bit before I can answer better/resolve or possibly take a different approach.

What I have so far:
> - what happens if I use Gradle on several builds, some configured with the -bin distro, some with the -all distro? in different usage order

From a few quick experiments, this looks to be a problem - since the generated jar lives in `{gradleVersion}/generated-gradle-jars`, the first one that is generated looks to be used in subsequent runs, regardless of whether -all or -bin is used in subsequent runs.

> - what's the performance impact on first use or ephemeral CI agents? generated API jars are already contributing a lot

Good point and I need to measure this. Sources weigh close to 30Mb now and there will surely be an overhead of traversing the directory and adding contents to the jar.

> - was on-demand sources download considered?

Having sources pulled on-demand sounds like something that would be best to have in the end if that is possible. I need to take a deeper look into how this is implemented in Kotlin DSL parts and understand it better first. Thank you for the pointer.

**Comment by eskatos** [comment]
> this looks to be a problem - since the generated jar lives in {gradleVersion}/generated-gradle-jars, the first one that is generated looks to be used in subsequent runs, regardless of whether -all or -bin is used going forward.

This is indeed surprising behaviour, without a solution I can picture lots of support questions from confused users.

> I need to take a deeper look into how this is implemented in Kotlin DSL parts and understand it better first. 

@bamboo and I are off the next two weeks, but happy to discuss that in January if need be

**Comment by lacasseio** [comment]
Paul has great points regarding performance. Maybe it could be a good idea to create a separate PR before this one to create a performance test for this exact scenario: ephemeral execution of Gradle with API dependency.

**Comment by rieske** [comment]
> This is indeed surprising behaviour, without a solution I can picture lots of support questions from confused users.

This turns out to be solvable by generating distinct jars - one with sources, another one without. This way there are no more clashes and the correct one is being used based on Gradle distribution in use.

Now while this solution with bundling sources inside the generated jar does the trick, I find it hacky. Before digging into the performance impact of it, I would like to zoom out a bit and figure how to properly attach sources in the Gradle model instead - either downloaded separately or packaged from the `-all` distribution. Probably the mentioned on-demand solution in Kotlin DSL will give some insights into this.

**Comment by rieske** [comment]
A work in progress alternative that in my opinion makes more sense -  https://github.com/gradle/gradle/pull/11751

Sources should only be attached in IDE models because that's the place where they are needed/used.

**Comment by rieske** [comment]
Closing in favor of https://github.com/gradle/gradle/pull/11751

**Pull request closed without merging**
