### PR TITLE
GRADLE-2263 allow daemon instances to be shutdown.

### PR DESCRIPTION
**Pull request by mottati**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [x] Before submitting a pull request, I started a discussion on the
[Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev)
or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [x] I considered writing a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [x] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [x] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

This is a proposed fix for the issue described in:

https://issues.gradle.org/browse/GRADLE-2263

In GRADLE-2263, a workaround is described that added to a projects  build.gradle
script. This commit is a simple reordering of two statements that are described in that Jira. This
reordering of code effectively implements, for all users,  the workaround described in
that Jira.

This commit simply reorders these two operations so that a monitor port is created prior to performing
the exit if daemon check.

### CODE REVIEW

**Comment by wolfs** [comment]
Thank you for your contribution!

Could you please also adjust SamplesWebProjectIntegrationTest which adds the workaround to the buildScript? If this test still works when removing the workaround this is also some coverage for your change.

**Comment by mottati** [comment]
Wolfs: 

Sure I would be happy to do that. 

Does running :integTest:integTest  from the top level cover all of the testing you wish me to perform? 

I just kicked off the :integTest:integTest target and I am seeing a number of errors having to do with parallel execution:

```
:wrapper:sourceJar UP-TO-DATE
:wrapper:publishLocalArchives
:integTest:integTest

org.gradle.integtests.BuildSourceBuilderIntegrationTest > can simultaneously run gradle on projects with buildSrc FAILED
    org.gradle.integtests.fixtures.executer.UnexpectedBuildFailure at BuildSourceBuilderIntegrationTest.groovy:51

org.gradle.integtests.ParallelProjectExecutionIntegrationTest > executes dependency project targets concurrently FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelProjectExecutionIntegrationTest > executes dependency project targets concurrently where possible FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelProjectExecutionIntegrationTest > project dependency a->[b,c] and both b & c fail FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelProjectExecutionIntegrationTest > tasks are executed when they are ready and not necessarily alphabetically FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelProjectExecutionIntegrationTest > tasks with should run after ordering rules are preferred when running over an idle worker thread FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > feature toggle is required for tasks to run in parallel FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > info is logged when overlapping outputs prevent parallel execution FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > info is logged when task is prevented from executing in parallel due to custom actions FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > two independent parallelizable tasks execute in parallel FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > independent parallelizable tasks from multiple projects execute in parallel FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > two parallelizable tasks with should run after execute in parallel FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > two parallelizable tasks that are dependencies of another task are executed in parallel FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > task is not executed if one of its dependencies executed in parallel fails FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > the number of tasks executed in parallel is limited by the number of parallel threads FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > non parallelizable tasks are not started if there are any parallelizable tasks running FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > parallelizable tasks are not started if there are any non parallelizable tasks running FAILED
    java.lang.AssertionError

org.gradle.integtests.ParallelTaskExecutionIntegrationTest > parallelizable tasks are run in parallel even if there are some non parallelizable tasks running in different project FAILED
    java.lang.AssertionError
> Building 99% > :integTest:integTest > 218 tests completed, 18 failed, 6 skipped
```

Not knowing this build, I am not sure what the cause is, or if there is a setting I can use to force serialized execution. 

One last thing, I noticed in this code in the file you referenced: 

```
    @LeaksFileHandles
    def "can execute servlet"() {
        given:
        def httpPort = portAllocator.assignPort()
        def stopPort = portAllocator.assignPort()
        def url = "http://localhost:${httpPort}/customized/hello"
```

Is there some after test equivalent to the portAllocator? e.g. is there a way to test that the ports passed in for httpPort and stopPort get closed at the completion of the test?

**Comment by mottati** [comment]
I just cloned a fresh copy of the gradle bits and attempted running just the test you referenced. The unmodified test fails as can be seen in the listing below. Note the git status and remote commands at the end of the listing. 

I used ./gradlew to run it, and took the most recent copy I could get. Since the test does not work before the modification, at least on my machine, I am not sure what more I can do. 

I can offer to describe the testing I did prior to submitting the PR.

I started with this project: https://github.com/ziroby/jetty-gradle-hello-world.git

I next moved declarations of  httpPort, stopPort and stopKey up into the script and deleted them from the doFirst, doLast section if the integrationTest task. 

Finally I ran the test repeatedly first under gradle 2.13. With that release the test would never run a second time because of port conflict.

I next ran it with the modified version of Gradle that included my PR change. I was able to run as many of those builds as i wanted to without manual process stopping intervention. 

```
mottati-03:virgin-gradle michael.ottati$ ./gradlew  :integTest:integTest --tests org.gradle.integtests.samples.SamplesWebProjectIntegrationTest 
Downloading https://services.gradle.org/distributions-snapshots/gradle-2.14-20160509000021+0000-bin.zip
.......

[REDACTED]

:integTest:integTest

org.gradle.integtests.samples.SamplesWebProjectIntegrationTest > can execute servlet FAILED
    org.gradle.integtests.fixtures.executer.UnexpectedBuildFailure at SamplesWebProjectIntegrationTest.groovy:99
        Caused by: org.gradle.internal.exceptions.LocationAwareException at SamplesWebProjectIntegrationTest.groovy:99
            Caused by: org.gradle.api.tasks.TaskExecutionException at SamplesWebProjectIntegrationTest.groovy:99
                Caused by: java.net.NoRouteToHostException at SamplesWebProjectIntegrationTest.groovy:99

2 tests completed, 1 failed
:integTest:integTest FAILED
:cleanUpDaemons

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTest:integTest'.
> There were failing tests. See the report at: file:///Users/michael.ottati/z-temp/virgin-gradle/subprojects/integ-test/build/reports/integTest/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 32.361 secs
mottati-03:virgin-gradle michael.ottati$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
mottati-03:virgin-gradle michael.ottati$ git remote -v 
origin	https://github.com/gradle/gradle.git (fetch)
origin	https://github.com/gradle/gradle.git (push)
```

**Comment by wolfs** [comment]
Looks like you are not online/have no network device?
```./gradlew integTest:integTest -DintegTest.single=SamplesWebProjectIntegrationTest```
does the trick for me.

**Comment by mottati** [comment]
I think the network issue was caused by beta VPN software I am running on my laptop. After a reboot this all works fine.  I have attached the output of the modified test. 

[TEST-org.gradle.integtests.samples.SamplesWebProjectIntegrationTest.xml.txt](https://github.com/gradle/gradle/files/271003/TEST-org.gradle.integtests.samples.SamplesWebProjectIntegrationTest.xml.txt)

**Comment by wolfs** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-5983

**Pull request merged**
