### PR TITLE
Weaken recommendation for adding attributes to schemas and explain why

### LINKED ISSUE #27810: Please clarify when an attribute needs to be added to the attributes schema and when not
### Issue type

Wrong or misleading information

### Problem description

The page mentioned below says 
> Attributes must be declared in the attribute schema found on the dependencies handler

This for me implies, that it is always necessary to register a new attribute in the attributes schema.
This is not true though.
I have a component metadata rule that adds a new attribute to some library variants.
And I can resolve those variants using the attribute just fine wihtout ever adding the attribute to the attributes schema.

So I'd like to know when it is necessary to register an attribute in the attributes schema and when not.
Maybe it can also be clarified here in a comment right away. :-)

### Page with the problem

https://docs.gradle.org/current/userguide/variant_attributes.html#creating_attributes_in_a_build_script_or_plugin

### PR DESCRIPTION
**Pull request by tresat**
Fixes #27810.

Changed section is [here](https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/80162169:id/distributions/gradle-8.8-docs.zip!/gradle-8.8-20240326185255%2B0000/docs/userguide/variant_attributes.html#creating_attributes_in_a_build_script_or_plugin).

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle help

**Comment by tresat** [comment]
@bot-gradle test BD

**Comment by tresat** [comment]
@bot-gradle test BD

**Comment by tresat** [comment]
@bot-gradle test BD

**Review by lkasso — APPROVED** [review]

**Review by jvandort — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
