### PR TITLE
Fix start script to run in MingW shell properly

### PR DESCRIPTION
**Pull request by zemian**
This fix will allow classpath conversion from Unix to Windows under
CYGWIN or MINGW platform.

Hi, I have noticed when using MingW shell env, the generated unix startup script during "distZip" will not work if we have multiple entries in the "classpath". The reason it failed is that the classpath is not converted into Windows path properly. It works fine under Cygwin, but it seems to miss the check for "msys" platform. This PR fixes this issue.

To reproduce:
1. Add this to `build.gradle` then run `gradle distZip`.
```
startScripts {
    classpath = files("conf", "lib/*")
}
```
2. Open a MingW bash shell (eg: Use "Git For Windows" shell).
2. Build and then unpack the project zip dist and the run the unix startup script with "-h" option. Error will appear. Example:
```
ZDE@my-windows10 MINGW64 ~/src/zemian/gradle-starter/java-app (master)
$ uname -a
MINGW64_NT-10.0 my-windows10 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys

ZDE@my-windows10 MINGW64 ~/src/zemian/gradle-starter/java-app (master)
$ ./gradlew distZip
$ unzip -d build/distributions build/distributions/java-app.zip
$ build/distributions/java-project/bin/java-project -h
Error: Could not find or load main class zemian.gradlestarter.javaapp.App
```

### CODE REVIEW

**Comment by lacasseio** [comment]
For Gradle to merge this PR, you will need to provide an integration test demonstrating it works as expected. You can assume MingW shell to be already installed on the test machine at a known path. We can do the final fix to the test for our test infrastructure.

**Comment by zemian** [comment]
Hi, I made a improvement to the shell boolean string check.

As for the test, I do not see existing integration tests that test out the shell execution. If you want to guide me I might able to add one in.

**Comment by lacasseio** [comment]
My bad for the delay in looking at this PR. Let's add the integration test in `ApplicationPluginUnixShellsIntegrationTest`. Your test will have to adjust `ApplicationPluginUnixShellsIntegrationTest.shellAvailable(String)` to support `msys`. For now, just hardcode a check for your own system. I'm doing the work to install `msys` on our CI infrastructure. As a bonus, if you can write a similar test for `cygwin` shell as well, that would be great.

Make sure the test you write for `msys` fails without the fix and succeed with the fix.

**Comment by lacasseio** [comment]
In fact, we are going to install `msys`'s `bash`, `sh`, `mintty` and `rxvt` shells so we could test for each one as an extra bonus.

**Comment by lacasseio** [comment]
I tested the `msys.bat` on Windows VM and I was able to start all shell available through the script:
 - `msys.bat -mintty`
 - `msys.bat -rxvt`
 - `msys.bat` # implicit sh

**Comment by big-guy** [comment]
Thanks @zemian, this will be in Gradle 5.6

**Pull request merged**
