### PR TITLE
forgetting the % symbol has caused me some confusion

### PR DESCRIPTION
**Pull request by JenkinsGit88**
### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by marcphilipp** [comment]
The `%` symbol only works on Windows, right?

**Comment by eriwen** [comment]
Thanks for the PR @JenkinsGit88. The `__GRADLE_HOME__` in this doc is intended as a generic environment variable, since they differ between environments. 

I'm happy to entertain other clearer ways to express this, but I'm not sure the PR as-is quite helps. What do you think?

**Comment by akmalick** [comment]
@eriwen  @JenkinsGit88  I can think of this : **Next add the bin of GRADLE_HOME to your `PATH` environment variable**
Explaining every single detail of an installation process is never a good idea, as this is something which has tons of documentations available online and its also expected that most users know this, provided the documentation is not confusing in the first place.

**Comment by akmalick** [comment]
In case you are stuck into this DCO check problem then it looks similar to my situation. I got past it. @JenkinsGit88  please go through https://github.com/gradle/gradle/pull/7469 . I believe that will help you. Don't forget to browse through the StackOverflow question that I posted. Let me know if that helps.

**Comment by big-guy** [comment]
Thanks @JenkinsGit88 - we need to have DCO to accept this change.  I tried tweaking the language used in this section of the installation guide to be more clear and use OS-specific example.

I'm going to close this PR.  Please open another PR if you find any other mistakes.

**Pull request closed without merging**
