### PR TITLE
Smoke test Kotlin 1.6.20-RC2

### PR DESCRIPTION
**Pull request by eskatos**
Adds 1.6..20-RC2 to the tested kotlin versions.
Also drops intermediate 1.4.x kotlin versions in order to reduce the test matrices.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by eskatos** [comment]
Thanks @wolfs!

@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
