### PR TITLE
Upgrade JAnsi to get some (Windows specific) bug fixes

### PR DESCRIPTION
**Pull request by sschuberth**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

This is a trivial change that only upgrades the existing jansi dependency:

This is also in preparation for supporting colored output in Cygwin's /
MSYS2's mintty terminal on Windows.

### CODE REVIEW

**Comment by wolfs** [comment]
Thanks for your PR!

Could you just describe what has been fixed in jansi 1.13 compared to 1.2.1 to better understand why you want to upgrade the version?

**Comment by sschuberth** [comment]
Unfortunately, even the [official changelog](https://github.com/fusesource/jansi/blob/master/changelog.md) is incomplete (neither does it list all releases, nor all fixes for a particular release). But I'm mostly after [support for detecting Cygwin / MSYS](https://github.com/fusesource/jansi/pull/45).

**Comment by wolfs** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-6158

**Comment by wolfs** [comment]
@sschuberth Thanks for your PR. It has been merged and will be included in Gradle 3.1.

**Comment by big-guy** [comment]
I asked Gary to take a look since he's dealt with issues with Jansi/JNA

**Pull request merged**
