### PR TITLE
Mark DependencyCollector as @Restricted to enable usage in declarative-prototypes

### PR DESCRIPTION
**Pull request by tresat**
Supersedes #28070

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by h0tk3y** [comment]
What is the plan behind making this isolated change to just one type, without any other APIs that would use it, and without adding it to any of the schemas?

**Comment by tresat** [comment]
> What is the plan behind making this isolated change to just one type, without any other APIs that would use it, and without adding it to any of the schemas?

No plan, I just wanted to make it easier to work on our prototypes with the latest changes, without having to keep branching and building snapshots to include this.

**Comment by big-guy** [comment]
@tresat can we close this since you're doing something else?

**Comment by tresat** [comment]
Working on doing this without the annotationl.

**Pull request closed without merging**
