### PR TITLE
Use original class name when constructing `TestFailure` from placeholder

### PR DESCRIPTION
**Pull request by marcphilipp**
- Remove unnecessary factory methods since `TestFailure` is public API
- Use original class name when constructing `TestFailure` from placeholder

### CODE REVIEW

**Comment by marcphilipp** [comment]
@bot-gradle test RFM

**Review by pshevche — APPROVED** [review]

**Review by snoopcheri — APPROVED** [review]

**Review by donat — APPROVED** [review]
LGTM. Thanks for adjusting my implementation!

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Review by rpygithub — APPROVED** [review]

**Pull request merged**
