### PR TITLE
Bump the PMD version used by the plugin to 5.5.5

### PR DESCRIPTION
**Pull request by sschuberth**
## Context
To benefit from the fix for https://github.com/pmd/pmd/issues/232.

#### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

#### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by sschuberth** [comment]
Closing for now as the referred issue does not really seem to have been fixed in PMD 5.5.4.

**Comment by sschuberth** [comment]
Sorted it out, PMD 5.5.3 indeed *does* fix the original issue mentioned in https://github.com/pmd/pmd/issues/232.

**Comment by bmuschko** [comment]
Looks like there's already a newer version: 5.5.5. https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.sourceforge.pmd%22%20AND%20a%3A%22pmd%22. Can you please update the pull request? You'll also need to add the new version to the `TargetVersions` in `AbstractPmdPluginVersionIntegrationTest`.

**Comment by sschuberth** [comment]
@bmuschko Done.

**Comment by bmuschko** [comment]
Thanks for touching up the pull request. It has been merged!

**Comment by bmuschko** [comment]
@sschuberth I had to [revert the upgrade of the library version](https://github.com/gradle/gradle/commit/e2e36a0dcaf048020be2ec2484508d37f3fba301). It failed the test `PmdPluginAuxclasspathIntegrationTest` on Windows: https://builds.gradle.org/viewLog.html?buildId=2702555&buildTypeId=Gradle_Master_CommitPhase_WindowsCommit_WindowsCommitJava17_8WindowsCommitJava17&tab=buildResultsDiv

Unfortunately, I don't have time to look into the failed test at the moment. Please provide a new pull request with an appropriate fix if you are still interested in having the new library version in Gradle.

**Comment by sschuberth** [comment]
@bmuschko I see two failing tests, both say

> java.io.IOException: Unable to delete file: C:\tcagent1\work\e94d7a966081366e\subprojects\code-quality\build\tmp\test files\PmdPluginAuxclasspathIntegrationTest\auxclasspath_not_co...g_project\bb54b\pmd-rule\build\libs\pmd-rule.jar

and

> This test looks flaky:
> Different test status of build configurations with the same VCS change

**Comment by bmuschko** [comment]
> This test looks flaky: Different test status of build configurations with the same VCS change

This is just coming from TeamCity I believe.

If you look deeper down the stack trace you'll find this:
 
> 1 PMD rule violations were found. See the report at: file:///C:/tcagent1/work/e94d7a966081366e/subprojects/code-quality/build/tmp/test%20files/PmdPluginAuxclasspathIntegrationTest/auxclasspath_config...g_project/csh9o/rule-using/build/reports/pmd/main.html

**Comment by sschuberth** [comment]
I'll check this.

**Comment by sschuberth** [comment]
Is there a way to instruct the test to keep `main.html` around? Seem like it gets deleted automatically.

**Comment by sschuberth** [comment]
Anyway, looking at the failing tests it seems like they are [expected](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/PmdPluginAuxclasspathIntegrationTest.groovy#L77) to [fail](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/PmdPluginAuxclasspathIntegrationTest.groovy#L97), so the problem likely is something else.

**Comment by bmuschko** [comment]
@sschuberth Ah, ok. Just had a look. It's expected to fail. What's happening here is that the new version of the PMD library holds on to a file handle which doesn't get released. In turn this causes test cleanup logic (which removes the test project files) to fail as it cannot remove one of the files. Given that the test currently passes I suspect an issue in the new PMD library version.

**Comment by sschuberth** [comment]
I bisected it, 5.5.3 succeeds, 5.5.4 fails. Digging further.

**Pull request merged**
