### PR TITLE
Update Gradle plugin to 3.19

### PR DESCRIPTION
**Pull request by facewindu**
### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by facewindu** [comment]
@bot-gradle test this

**Review by ov7a — APPROVED** [review]

**Review by ljacomet — CHANGES_REQUESTED** [review]
RC1 is out - this can only be merged if we do RC2

**Comment by facewindu** [comment]
> RC1 is out - this can only be merged if we do RC2

just to understand @ljacomet 
isn't it ok to merge to `release` anyway?
If an RC2 comes out then it will ship with this, or then it will be on the next release, since I guess you're always releasing from `release`, and merge `release` to `master` in the meantime ?

**Comment by facewindu** [comment]
> > RC1 is out - this can only be merged if we do RC2
> 
> just to understand @ljacomet isn't it ok to merge to `release` anyway? If an RC2 comes out then it will ship with this, or then it will be on the next release, since I guess you're always releasing from `release`, and merge `release` to `master` in the meantime ?

got it
You can't have in 8.12 GA sth that is not part of an RC.

**Comment by facewindu** [comment]
@bot-gradle test this

**Comment by facewindu** [comment]
@ljacomet I moved this to `master`
We can always cherry-pick, should we want this in 8.12 GA (so if an RC2 is scheduled)

**Comment by wolfs** [comment]
@bot-gradle cherry-pick to release

**Pull request merged**
