### PR TITLE
Test Idea 2024.3-rc sync with Isolated Projects

### PR DESCRIPTION
**Pull request by alllex**
- Bump the tested IntelliJ version to `2024.3-rc`
- Re-enable the parallel sync test
- Polish the tests

Should fix https://github.com/gradle/gradle-private/issues/4438

### CODE REVIEW

**Comment by alllex** [comment]
@bot-gradle test this

**Review by abstratt — APPROVED** [review]
LGTM!

**Review by jvandort — APPROVED** [review]

**Review by 6hundreds — APPROVED** [review]

**Comment by alllex** [comment]
>as the flakiness should disappear after the fixes on IDEA side

After I verified that it works locally, for some reason I was sure that IDEA folks landed the change to prefetch dummy models in parallel, as it was discussed at some point. Looking at the r[elease notes of each EAP](https://youtrack.jetbrains.com/articles/IDEA-A-21/IDEA-Latest-Builds-And-Release-Notes), it does appear that there was such a change.

I tried digging deeper, but it turns out the answer is much simpler. It's our forced parallel hierarchy configuration that makes it work like that: when they request `BuildEnvironment` model for the root project, due to configure-on-demand being disabled for IP, we configure everything and in parallel.

image

___

In effect, the test should not be flaky anymore. However, if we revert to having CoD with IP, the test will start failing. But I don't think we'll do that until we make sure the IDEA side is updated to make use of the parallelism.

**Comment by alllex** [comment]
Well, I am not sure anymore. The flakiness in the parallel sync test actually appeared immediately after the forced parallel configuration has been merged (Aug 16th):  https://github.com/gradle/gradle/pull/30050
So on one hand, it's unconditional parallel configuration. On the other hand, the observed flakiness.

Given we do update the IDEA version, I propose to proceed with the merge and see if the flakiness reappears. Maybe there were other factors that played into it.

**Pull request merged**
