### PR TITLE
Ensure project builder properly creates root project so it is closed …

### PR DESCRIPTION
**Pull request by big-guy**
…after test completion

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
