### PR TITLE
resolve https://github.com/gradle/gradle/issues/23620

### LINKED ISSUE #23620: Java toolchain auto-detection on linux should look in /usr/local/java
On Linux, when installing a local java tool chain, not using one of the package managers, it is customary to install it in `/usr/local`, and usually, for Java, in `/usr/local/java`. It would be good if this location could be added to https://github.com/gradle/gradle/blob/master/subprojects/jvm-services/src/main/java/org/gradle/jvm/toolchain/internal/LinuxInstallationSupplier.java#L36.

### Expected Behavior
Gradle should find JVM installations under /usr/local/java/*

### Current Behavior
It doesn't.

### Context
On our linux boxes we have java installed under `/usr/local/java`, and these are not found by gradle. We can work around this by putting in "installation files" for one of the "approved" package managers.

### PR DESCRIPTION
**Pull request by kurahaupo**
Fixes #23620

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by kurahaupo** [comment]
Running `./gradlew jvm-services:quickTest --warning-mode all` I get several reports along the lines of 
```
- Variant 'apiElements' capability gradlebuild:commons:unspecified declares a library, packaged as a jar, and its dependencies declared externally:
  - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
```
which does not seem in any way connected to the change I've made.

I've looked for existing tests for this file and there don't appear to be any, so I'm not even sure where to begin on that point.

I'll leave it to @pwagland to make any further changes.

**Comment by pwagland** [comment]
> I'll leave it to @pwagland to make any further changes.

This works for our needs, thank you!

**Comment by ghale** [comment]
@bot-gradle test this

**Comment by ghale** [comment]
@bot-gradle test and merge

**Comment by ghale** [comment]
@bot-gradle test and merge

**Pull request merged**
