### PR TITLE
Move DaemonScanInfo to the :enterprise subproject

### LINKED ISSUE #19548: Move `DaemonScanInfo` to `:enterprise` subproject
Also move the implementation, so that the GE plugin can access them.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by lptr**
Fixes #19548

### CODE REVIEW

**Review by facewindu — APPROVED** [review]

**Comment by lptr** [comment]
@bot-gradle test and merge this please, thank you!

**Comment by blindpirate** [comment]
@bot-gradle test and mege

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Review by ldaley — APPROVED** [review]

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by lptr** [comment]
Ah, this approach doesn't work... :/

**Pull request closed without merging**
