### PR TITLE
De-incubate or remove many API points

### PR DESCRIPTION
**Pull request by octylFractal**
I left `org.gradle.api.tasks.diagnostics.TaskReportTask.getDisplayGroups()` incubating because it seems like it should be a `Property`, and it has weird behavior with the existing group flag.

### CODE REVIEW

**Review by tresat — APPROVED** [review]

**Review by big-guy — APPROVED** [review]

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@octylFractal based on the failures, I think we need to keep `ProjectBasedReportTask` for now

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Pull request merged**
