### PR TITLE
Remove `GradleKotlinDslBuildPerformanceTest`

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle APTN

**Comment by bamboo** [comment]
@bot-gradle test APTN

**Comment by bamboo** [comment]
@bot-gradle clean

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Review by wolfs — COMMENTED** [review]
LGTM!

**Review by jjnkjdreaminjjnkj — COMMENTED** [review]
subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/kotlindsl/GradleKotlinDslBuildPerformanceTest.groovy

**Pull request merged**
