### PR TITLE
GRADLE-3030: Store classifier in POM for project dependencies

### PR DESCRIPTION
**Pull request by rnavarette**
Implemented suggestion from comments in GRADLE-3030.  Now supports writing artifact classifier for project dependencies when creating pom.  This implementation supports only the upload task, not the publishing task.

### CODE REVIEW

**Comment by rnavarette** [comment]
These tests don't seem to fail when I run them locally.  Is there a way I can rerun to recheck the status through the build system?

It would be really great to get this fairly small fix pulled in, it makes a huge difference for us on how we run our continuous build chain because we can now properly understand the transitive dependencies required for properly running our tests.

Thanks,
ray

**Comment by mark-vieira** [comment]
The failures were unrelated to your changes. I've retriggered the build and it looks to be green.

As for the status of this PR, we unfortunately have limited resources at the moment for reviewing and merging pull requests however we are working through the backlog. We appreciate your patience.

**Comment by mark-vieira** [comment]
@rnavarette, I've taken a look at your submission. The main issue I see is that this fix doesn't take into consideration the scenario of a project dependency configuration containing multiple artifacts with different classifiers. We should handle this scenario properly by mapping to multiple Maven dependencies with different classifiers. For example, if my project dependency configuration 'foo' publishes '-sources' and '-javadocs' jars then I should get two `<dependency>` entries in my POM.

Also, this fix only applies to users of the 'maven' plugin. It would be great to fix this for the 'maven-publish' plugin as well. Would you be interested in investigating this? I think the changes necessary need to be made [here](https://github.com/gradle/gradle/blob/master/subprojects/maven/src/main/groovy/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java#L111-L111).

**Comment by pioterj** [comment]
I'm closing this PR because of a lack of response from the contributor for almost 2 months. @rnavarette If you ever come back to this and address comments from @mark-vieira feel free to reopen.

**Comment by rnavarette** [comment]
I'm still here!

Sorry, been busy lately and haven't gotten back to this.  Hopefully will be able to put some time into it in the next few weeks.

**Comment by mark-vieira** [comment]
@rnavarette feel free to open up a new pull request when you're ready to have this reviewed again.

**Comment by rnavarette** [comment]
@mark-vieira I've addressed the comments above locally about multiple classifiers and was about to update and issue another pull request..  I'm thinking about this now though and wondering if that's what is really desired?  This means that every dependency reference for foo will now pull in foo.jar, foo-javadoc.jar and foo-sources.jar.  That doesn't actually seem to be what we want, at least certainly not for sources and javadocs.

I understand that there's no clear cut way to make the determination about when we would or would not include the additional classified artifacts, so maybe we just need a convention of how we'll behave under these circumstances?

For this convention, perhaps the initial solution was appropriate. For the purposes of dependency management: a configuration will publish a single artifact.  In the case of the default configuration, that artifact will not carry a classifier.  For additional configurations the artifact will carry a classifier.

This convention could help to address (or maybe just explain) an issue I've noticed in using the java plugin and you've classified your default 'jar' artifact: In that case the pom's dependency reference does not include the classifier.  If this was important for you (the artifact was code and should be referenced as such) then you could alternately or additionally attach that jar to another configuration and reference it that way.

Another option for the convention might be that dependencies for the default configuration shall not include the classified artifacts (sources, javadocs, or anything else) but dependencies for any other configuration will.  This would allow for us to reference all the dependencies but seems odd (that we'd behave differently depending on the configuration) and many cases perhaps unwanted.  I can envision scenarios where I would want only a specific jar referenced in my pom dependencies and so it seems appropriate that I'd have to have separate configurations to accommodate this.

**Comment by rnavarette** [comment]
@pioterj Could you reopen this pull request or would I have to resubmit?  I'm not seeing a 'reopen' option, although i could be missing something...

**Comment by pioterj** [comment]
@rnavarette  I just reopened it for you.

**Comment by eljobe** [comment]
@rnavarette Sorry for the delay in getting back to your questions. @mark-vieira has become pretty busy with other projects, and I'm getting up to speed with what's going on in this change.  I'll try to give you some useful feedback soon.

For now, I'm digging into [GRADLE-3030](https://issues.gradle.org/browse/GRADLE-3030) and posting that link to the comment thread for posterity.

**Comment by mark-vieira** [comment]
>  This means that every dependency reference for foo will now pull in foo.jar, foo-javadoc.jar and foo-sources.jar. 

Only if the 'javadoc' and 'sources' jars are added to the 'default' configuration. Typically they would either be added to the 'artifacts' configuration or to none at all and simply attached to a publication if using the 'maven-publish' or 'ivy-publish' plugins.

> I understand that there's no clear cut way to make the determination about when we would or would not include the additional classified artifacts, so maybe we just need a convention of how we'll behave under these circumstances?

They should _always_ be included. If I depend on a configuration that includes 3 artifacts then they ideally should be represented in the POM as things my project needs.

I think we are conflating the publishing aspect with the _dependency_ aspect. This change will not affect what artifacts are included in a configuration for the purposes of resolving dependencies. When using the 'java' plugin we will still only depend on the contents of the 'default' configuration, which will be the main JAR w/o classifier. The generated POM should reflect that. My intention is that this PR address the following poor contrived example:

```
project(':foo') {
    apply plugin: 'java'

    task sourcesJar(type: Jar) {
        classifier = 'sources'
        from sourceSets.main.allSource
    }

    artifacts {
        archives sourcesJar
    }
}

project(':bar') {
    apply plugin: 'java'

    dependencies {
        compile project(path: ':foo', configuration: 'archives')
    }
}
```

Publishing project `:bar` in this case should include both the main JAR and sources JAR of project `:foo` in the pom.xml.

**Comment by rnavarette** [comment]
Ok.  I can implement this with the understanding that we will publish all of the artifacts associated with the configuration and the implication that if users have added additional jars (javadoc, sources, etc) to their default configuration, they too will be published.

I do however want to note that I don't think that the concern is conflating the separate aspects of publishing and dependency resolution.  The problem is that once you're outside of the gradle build, they're on in the same.  If I were to depend on 'mycompany:bar:1.2' using your example above, I'd expect to resolve both the unclassified as well as the sources jar from foo in my dependency scope.  This was where my original concern came from.

Thanks for the feedback.  I'll double check the submission i had ready and look to update the pull request soon.

**Comment by mark-vieira** [comment]
> I do however want to note that I don't think that the concern is conflating the separate aspects of publishing and dependency resolution.

What we might be confusing here is _who_ is publishing/resolving _what_. In the example above we are assuming that 'foo' is publishing the 'archives' configuration. Now 'bar' is the consumer here, and this is the bit we care about. When we generate the pom.xml for 'bar' it should include all artifacts in whatever configuration its depending on.

So I just want to reiterate that we are not changing publication _or_ resolution behavior. We are only changing what gets stuck in the pom.xml. This does not affect what _artifacts_ get published or which are included in dependency resolution. This behavior is already working as intended. The problem is we lose this information currently when publishing as its not translated into the pom.xml.

**Comment by eljobe** [comment]
@rnavarette I just wanted to make sure (since it's been a few days) that it is clear that the ball is in your court. We're looking for updates to this Pull Request in alignment with the changes described by @mark-vieira.

**Comment by rnavarette** [comment]
Definitely.

I'm hitting an issue WRT understanding the proper dependencies to use in the implementation for a given configuration.  It looks like the configuration offers getArtifacts (return artifacts attached directly to the configuration) and getAllArtifacts (returns artifacts from extended configurations as well).  On the surface, keeping this simple, it seems that getArtifacts is the way to go.  Unfortunately, for the default configuration when used with the Java plugin, this does not include the main jar artifact because that is declared on an configuration that "default" extends from.  I see a couple options here, none are ideal:
1) Use getArtifacts but whenever we encounter the default configuration always register an additional unclassified dependency for that project.  This will help us to capture this specific case (default jar artifact) and is essentially what is currently done in the code.  However, it gives conflicting behavior for classified artifacts that may be attached to the same config (runtime in this case i believe).  Since these wouldn't be attached directly to default, they would be ignored.  This just seems a little odd.
2) Use getAllArtifacts always.  This would perhaps be the simplest approach, but it seems that we may be putting more than we want in the pom.  Not sure how much of a problem this may or may not be though.  It all depends on where people would be attaching artifacts whether or not this is desired.
3) Use getAllArtifacts unless the configuration is marked as intransitive.  This seems to handle the potential negative side effect for option 2, but I'm not certain its clear enough of a way to handle this.  This was my initial implementation and seems to work well, but I still have a bit of an off feeling about it.
4) Use getAllArtifacts for the default configuration and getArtifacts for all other configurations.  This feels like it would give the behavior people are looking for in most cases, however, it again doesn't feel appropriate to treat the default configuration differently.

Any input appreciated.

thanks,
ray

**Comment by bigdaz** [comment]
I think we should be using `getAllArtifacts` for the depended-on configuration, and creating a separate `dependency` declaration for each declared artifact.

We will need _integration_ test coverage for POM creation with a project dependency on:
- A configuration with no artifacts
- A configuration with one unclassified artifact
- A configuration with one classified artifacts
- A configuration with one unclassified artifact and multiple classified artifacts

This discussion indicates to me that a design spec might be useful to clarify the behaviour we want.

**Comment by rnavarette** [comment]
Thanks Daz for the response.

I'm pretty sure i've already written integration that cover these cases (except no artifacts perhaps), but I'll make sure they're there.  Would you like me to handle the "transitive" case outlined above in order to restrict to the artifacts directly defined on the configuration, or just use getAllArtifacts in all cases?

**Comment by bigdaz** [comment]
The transitivity of a configuration shouldn't have any impact on whether parent configurations are considered to determine artifacts. For a configuration to be non-transitive means that all of the declared dependencies are considered non-transitive. It doesn't change the fact that dependencies and artifacts are inherited from parent configurations.

**Comment by rnavarette** [comment]
sounds good.  thanks.

**Comment by rnavarette** [comment]
@mark-vieira @eljobe @bigdaz PR updated as per conversation in this thread.

Thanks everyone for the help on this.

**Comment by eljobe** [comment]
@rnavarette Thank you for working through this review and improving how project dependencies are represented when generating POM files for the uploadArtifacts task in Gradle. This is a complicated task, and your perseverance will surely keep others from being confused by the behavior in the future.

Thank you for contributing,
Pepper

**Comment by rnavarette** [comment]
@bigdaz @mark-vieira Hey Guys,

Not sure if this is the proper place to talk about this or on the dev list, but I'll start here since thats where most of the background is.  And, apologies for what may be originally a slimmer amount of information than I'd usually like to put forth, but I wanted to bring up the issue quickly since 2.13 is still in RC status...

There may be a problem with this implementation, or perhaps something more interesting going on with gradle itself.  I'll look at the test cases to see if this is illustrated, but the basic problem is this:
When using allArtifacts to get the full set of dependencies to add to the POM, we may override the scope of a dependency already listed in the pom.  This means that when we use the published pom for dependency resolution, we do not properly see compile scope dependencies because they were overridden as test scope.  Below is a hopefully better example of what i mean, and I'll try and respond in a little while with something better still.

`dependencies{
    compile project('foo')
    testCompile project(path: 'foo', configuration: 'tests')
}`

What we'd like to see in the pom in this case (my initial change produced this) would be something like this:
`
    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>foo</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>foo</artifactId>
      <version>1.0</version>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
`
However, due to using allArtifacts, we actually see the following.  The problem is that since foo (unclassified) is listed with 2 separate scopes, it treats the dependency only as a 'test' dependency (the second entry encountered).
`
    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>foo</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>foo</artifactId>
      <version>1.0</version>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>foo</artifactId>
      <version>1.0</version>
      <scope>test</scope>
    </dependency>
`
Interestingly though, and the reason that i mentioned originally that this may be a deeper problem, gradle 2.12 also displays the problem.  In that case, the dependencies look as they do below, but without the addition of the (needed) classified dependency.
`
    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>foo</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>foo</artifactId>
      <version>1.0</version>
      <scope>test</scope>
    </dependency>
`

**Comment by bmuschko** [comment]
@rnavarette Thanks for continuing the conversation. The [Gradle dev list](https://groups.google.com/forum/#!forum/gradle-dev) is probably a better place for this discussion. Would you mind opening a new post over there? Please also provide a link to this PR. Thanks!

**Comment by rnavarette** [comment]
I think it would have been good to talk about this a little before reverting.  As mentioned in the discussion, this issue existed BEFORE this pull request was applied.  I think the better behavior would be to apply the pull request as we had before and look to fix the additional issue.

**Comment by eskatos** [comment]
@rnavarette we reverted from our `release` branch only, we will pursue with this and fix the issue you reported on `master`. I'll get back to you early next week, again, sorry about the confusion.

**Comment by eskatos** [comment]
@rnavarette so, I'm fixing the underlying issue, almost there, I'm polishing the code and adding some more coverage, will keep you posted

**Comment by rnavarette** [comment]
Excellent, thanks Paul.  Truly appreciate the help on this.

ray

**Comment by eskatos** [comment]
@rnavarette, could you please try the latest nightly and confirm things are working for you?
See https://services.gradle.org/distributions-snapshots

**Comment by rnavarette** [comment]
Looks good.  Thanks!

**Pull request merged**
