### PR TITLE
Upgrade Asciidoctor Gradle Plugin & co. in gradle/gradle build logic

### PR DESCRIPTION
**Pull request by eskatos**
Use the latest stable Asciidoctor Gradle Plugin.
Also use latest stable AsciidoctorJ and AsciitoctorJ-PDF.

This PR also uses the latest version of our `docs-asciidoctor-extensions` that is now split into two artifacts because Asciidoctor now fail hard on `Postprocessors` extensions registered when using non-html backends such as the PDF one. As a consequence `:docs:userguideSinglePage` has been split into two tasks: `:docs:userguideSinglePageHtml` and `:docs:userguideSinglePagePdf`.

The `GradleUserManualPlugin` class is updated to leverage new type safe APIs of the Asciidoctor Gradle Plugin and other niceties.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
Ah, this needs a bit more work. The single page user manual is generated as a PDF but not as a HTML anymore. Will fix

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
Rendered docs from the `'-docs` distro:
 - [User manual](https://builds.gradle.org/repository/download/Gradle_Check_BuildDistributions/41080228:id/distributions/gradle-7.0-docs.zip!/gradle-7.0-20210203141738%2B0000/docs/userguide/userguide.html)
 - [User manual single page HTML](https://builds.gradle.org/repository/download/Gradle_Check_BuildDistributions/41080228:id/distributions/gradle-7.0-docs.zip!/gradle-7.0-20210203141738%2B0000/docs/userguide/userguide_single.html)
 - [User manual single page PDF](https://builds.gradle.org/repository/download/Gradle_Check_BuildDistributions/41080228:id/distributions/gradle-7.0-docs.zip!/gradle-7.0-20210203141738%2B0000/docs/userguide/userguide.pdf)
 - [Samples index](https://builds.gradle.org/repository/download/Gradle_Check_BuildDistributions/41080228:id/distributions/gradle-7.0-docs.zip!/gradle-7.0-20210203141738%2B0000/docs/samples/index.html)

**Review by jjohannes — APPROVED** [review]
🎉  Thanks for diving into this Paul and finally making it happen. Looks all good. 👍

**Pull request merged**
