### PR TITLE
Rebaseline JavaIncrementalExecutionPerformanceTest

### PR DESCRIPTION
**Pull request by blindpirate**
To unblock master while we investigate the 3~5% regression.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
It seems to be consistently fail on windows66: https://ge.gradle.org/scans/tests?search.relativeStartTime=P28D&search.timeZoneId=Asia/Shanghai&tests.container=org.gradle.kotlin.dsl.plugins.embedded.EmbeddedKotlinPluginTest&tests.sortField=FAILED&tests.test=sources%20and%20javadoc%20of%20all%20embedded%20kotlin%20dependencies%20are%20resolvable&tests.unstableOnly=true

And it can be reproduced, only on that machine: https://builds.gradle.org/viewLog.html?buildId=49606379&

**Comment by blindpirate** [comment]
@eskatos @bamboo do you want to investigate this issue or shall I just rebuild the machine?

**Comment by eskatos** [comment]
According to https://gradle.slack.com/archives/C03A0MT6S/p1645456625416079, @adammurdoch will take a look

> According https://gradle.grafana.net/d/o_QUeTi7z/performance-results?orgId=1&from=now-7d&to=now&var-test_id=up-to-date%20assemble%20(parallel%20false)&var-test_project=largeJavaMultiProject&var-weekday=All&viewPanel=2&editPanel=2&var-confidence=0.9 , it seems to be introduced in https://github.com/gradle/gradle/commit/ae0f4ae9036a4c922be056712cd63269282a1d45

**Comment by blindpirate** [comment]
@eskatos sorry I commented in the wrong issue. I was about to mention you in https://github.com/gradle/gradle-private/issues/3508

**Pull request merged**
