### PR TITLE
Reshuffle utilities and instrumentation sources, refine the call interception tool's dependencies

### PR DESCRIPTION
**Pull request by h0tk3y**
- Move some `core` and `base-services` utils to new subprojects `base-common-utils` and `base-instrumentation-utils`
- Move some sources from `internal-instrumentation-processor` out to `internal-instrumentation-call-interception-tool` and `internal-instrumentation-property-upgrades`

The purpose of this change is to make the instrumentation & code generation utilities independent of `base-services` and `core`.

### CODE REVIEW

**Comment by h0tk3y** [comment]
@bot-gradle test RFN

**Comment by h0tk3y** [comment]
@bot-gradle test RFN

**Comment by h0tk3y** [comment]
@bot-gradle test RFN

**Comment by h0tk3y** [comment]
@bot-gradle test RFN

**Comment by h0tk3y** [comment]
@bot-gradle test RFN

**Comment by h0tk3y** [comment]
@bot-gradle test RFN

**Comment by asodja** [comment]
Can we also update annotation processor here:
https://github.com/gradle/gradle/blob/master/build-logic/uber-plugins/src/main/kotlin/gradlebuild.instrumented-project.gradle.kts

Plan for this plugin is, that a developer just applies `gradlebuild.instrumented-project` to the project and annotation processor then works out of the box without any configuration (also generated class names have project name suffix then). This is now used just for Property upgrades, so maybe we should rename this plugin now. Or we can also `internal-instrumentation-call-interception-tool` processor 🤔

**Review by asodja — APPROVED** [review]
LGTM

**Pull request closed without merging**
