### PR TITLE
Revert "Support PMD's analysis cache (#2223)" 

### PR DESCRIPTION
**Pull request by blindpirate**
Revert "Support PMD's analysis cache (#2223)" and "Improve test coverage for pmd incremental analysis (#2961)"

Since there're some issues unreleased in pmd plugin:

https://github.com/pmd/pmd/issues/618
https://github.com/pmd/pmd/issues/608

This reverts commit:

https://github.com/gradle/gradle/commit/79e74d939dd3c9726624d0fef87c4c6a8e136297
https://github.com/gradle/gradle/commit/4c51b741042fbccd6b0a03e0a60491197bf49751
https://github.com/gradle/gradle/commit/d98129f4a34b0fac026a86c0cc1aff19dc541fae
https://github.com/gradle/gradle/commit/c543f98e1f9228e6460b2f7a08dec01314fa2255
https://github.com/gradle/gradle/commit/60fa200ec9276c1c95920f554ccfbe4474843c38
https://github.com/gradle/gradle/commit/bf275854b58f6dfe64e9be72aed4c0b78c1878ab
https://github.com/gradle/gradle/commit/f7a4bf852eec0e02393fc51e3cf2b0a12b9cb3e1

### CODE REVIEW

**Comment by henrik242** [comment]
@blindpirate Is it possible for me to enable the PMD cache in Gradle 4.4?

**Comment by blindpirate** [comment]
Sorry, this is not supported in `4.4`. At that point there were several issues unsolved so this part is reverted. I checked pmd 6.0.0 is released, let's see if we can work it into next release.

**Comment by henrik242** [comment]
Cool, thanks.  Yeah, it was the 6.0.0 release that made me look into this.

**Comment by huxi** [comment]
It would be nice if this could get addressed in the near future.

The two PMD issues referenced above have been closed and released with PMD 6.0.0 in the meantime but the new `This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd/pmd_userdocs_getting_started.html#incremental-analysis` output for every module of a build is introducing quite some noise.

**Comment by jsotuyod** [comment]
@blindpirate PMD 6.0.1 has just shipped, with several bug fixes on PMD 6.0.0.

Any chance to get this back in? Once that's done, I'd love to add support for Java 9 in Gradle (already in PMD 6.0.0), along a few other extras.

**Comment by blindpirate** [comment]
@jsotuyod I'll try to do it in a few days. Thanks for reminding.

**Comment by jsotuyod** [comment]
@blindpirate will this make it into Gradle 4.6.0? Can I help in any way?

**Comment by AdamCarroll** [comment]
I just tested with Gradle 4.6.0 and PMD 6.1.0 and still see the warning "This analysis could be faster..." so it seems the change didn't make it into Gradle 4.6.0.

**Comment by huxi** [comment]
@blindpirate Any chance this will get addressed in Gradle 4.8?

PMD 6.2 is now printing two lines of warnings per project and this makes builds super noisy.

**Comment by huxi** [comment]
No fix in 4.9, either? Would adding PMD checks to the Gradle build help getting this fixed?

**Comment by blindpirate** [comment]
I apologize for this. Currently we don't have enough capacity to move forward. But I think a contribution would be great and I can review it.

**Comment by huxi** [comment]
Perhaps @jsotuyod would like to take another stab at it.

**Comment by Cinderhaze** [comment]
I know that it would be nice if we could get a simple implementation in that simply gives an ability to pass a flag to the PMD process, that would allow us (for now) to simply add  the appropriate `--no-cache` ( https://github.com/pmd/pmd/pull/954 ) or `--cache` argument to the process without requiring anything complicated.  A more complete DSL could be be handled in a future release.

**Pull request merged**
