### PR TITLE
Limit output event queue size

### PR DESCRIPTION
**Pull request by oehme**
To prevent the Gradle client from running out of memory
if a task produces large amounts of output in a short time.
The daemon is less affected by this since it usually has a
much larger heap size and can deal even with hundreds
of thousands of events. But the client only has 64m by
default and needs to flush more eagerly.

This is by no means fool-proof. There could still be a process
generating a single line that contains so much text that the
client runs out of memory. But that seems pretty rare compared
to creating lots of separate lines in a short time.

The particular use case was a Webpack task with verbose logging.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
@eriwen What we talked about the other day ☝️

**Review by eriwen — APPROVED** [review]

**Comment by eriwen** [comment]
Thanks @oehme! LGTM!

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by oehme** [comment]
That test failure seems unrelated - These tests don't even produce much output.

**Comment by oehme** [comment]
Ping :)

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by oehme** [comment]
I assume the above failures were due to some configuration change on the agents? Merged in `master` to hopefully fix that.

**Comment by ljacomet** [comment]
Thanks for being reactive, I was going to rebase it or ask you that.

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by oehme** [comment]
CI looks completely borked to me - `Couldn't lock cache directory`

**Comment by ljacomet** [comment]
I just rebased on the latest master, we had some infra issues with CI. Let's see if it goes better now.

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
