### PR TITLE
Publish checksums for local repositories

### PR DESCRIPTION
**Pull request by octylFractal**
Fix for #22482

### CODE REVIEW

**Comment by octylFractal** [comment]
@ljacomet I made this as an alternative fix for #22482, as I couldn't see anything wrong with adding it. Is there any reason not to do this, when `mvn install -DcreateChecksum=true` would do the same thing, and Maven downloads hashes from the remote to there anyways?

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
Hey Octavia,

I am not sure actually. Given that we really want folks to learn to stop using Maven local as a full fledged Gradle repository, making it easier feels a bit counterproductive.
At the same time, I agree that the fix is very small.

I think it makes sense for the JVM team to take a stance as part of the publication work. So my opinion is above, but feel free to go through with the change if you think it best.

**Comment by big-guy** [comment]
> I am not sure actually. Given that we really want folks to learn to stop using Maven local as a full fledged Gradle repository, making it easier feels a bit counterproductive.

I think there are two parts of this:
1. Using Maven local to share artifacts built by Gradle with Maven.
2. Using Maven local to share artifacts built by Gradle with Gradle.

I think it's OK to suggest people can do (1), so we should be able to publish to Maven local. 

Consider how do we want Maven to see Gradle populated artifacts in m2. If we had published the Gradle built artifacts to a repository and then Maven had resolved them, m2 would have checksums.  Possibly, we should emulate the resolve behavior (populate with checksums) and not the `mvn install` behavior to be less Maven like and more consistent internally.

We don't want people to do (2) because we want people to use composite builds where possible. We want to discourage the use of Maven local for resolution. I don't know if this change would affect this way or the other.

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
After discussing with the JVM team, we decided the original issue does not provide sufficient justification to make this change now. If another use case comes up that isn't better solved by publishing to a `file://` URL, we may revisit this.

**Pull request closed without merging**
