### PR TITLE
Fix VersionNumber Kotlin interop incompatibility

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Currently, compile this fails:
```kotlin
currentAgpVersion != null
```

The error is `No method 'equals(Any?): Boolean' available`.

But this works:
```kotlin
null != currentAgpVersion
```

Pretty sure that's just because `equals` is missing a nullability annotation.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@eskatos I don't the build failures are related.

**Comment by eskatos** [comment]
`org.gradle.util` is an internal package, not public api.

That being said, some test coverage would help moving this PR forward.

About the failures on Travis, could you rebase on top of the latest `master`?

**Comment by SUPERCILEX** [comment]
@eskatos It looks like someone restarted the build and it passes now. As for test coverage, I don't think that's feasible without a lot of work given that the tests would have to be written in Kotlin to catch this bug.

Is this PR good to be merged?

**Comment by SUPERCILEX** [comment]
@eskatos Bump.

**Comment by eskatos** [comment]
@SUPERCILEX, you can add a Kotlin test in `subprojects/kotlin-dsl/src/test/kotlin`, please do so

**Comment by eskatos** [comment]
The compilation failure only happens when `-Xjsr305=strict` is passed to the Kotlin compiler.

@SUPERCILEX could you please grant me push rights to your fork so I can amend the PR with a test?
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by SUPERCILEX** [comment]
@eskatos you should have access. 👍

**Comment by eskatos** [comment]
Thanks @SUPERCILEX!

**Pull request merged**
