### PR TITLE
Ensure symlink test files are properly deleted

### PR DESCRIPTION
**Pull request by lacasseio**
### Context

Fixes: https://github.com/gradle/gradle/issues/8119

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and [CI build status](https://builds.gradle.org/project.html?projectId=Gradle_Check&tab=projectOverview&branch_Gradle_Check=lacasseio%2Fcore%2Fissue-8119)
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by mctdi** [comment]
is there any change to see this backported to 4.x, 5?

**Comment by lacasseio** [comment]
We usually don't backport change unless it's significant. In this case, the link files are in the temporary folder so I don't see this being a significant issue. The suggestion would be to upgrade to 5.3 when it's out, the question would be is there a reason why upgrading wouldn't be a possibility for you?

**Comment by mctdi** [comment]
Spring boot 2.1 don't officially support gradle 5.
https://github.com/spring-projects/spring-boot/issues/15168

**Comment by lacasseio** [comment]
I understand. How is this PR a significant issue that would require a backport to 4.x?

**Comment by mctdi** [comment]
in fact it's not so important, sb 2.1 don't support it officialy... but tried with gradle 5.2.1 and that work fine...

**Comment by lacasseio** [comment]
Great, thanks for getting back on this.

**Pull request merged**
