### PR TITLE
Add @Nullable annotation to ResolvedDependencyResult.resolvedVariant

### PR DESCRIPTION
**Pull request by jjohannes**
### Context
Apparently the `ResolvedDependencyResult.getResolvedVariant()` can be null as the code [here](https://github.com/jjohannes/gradle/blob/1bdc8353b9cc66fcf722982541e1bbfa30c15ff7/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/result/CachingDependencyResultFactory.java#L53-L59) (which gives a warning in the IDE) suggests. This screenshot from a debugging session shows that it is possible: https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/913#issuecomment-1638716592

(Conceptually, I don't know how a resolution can be successful without a selected variant)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- ~[ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective~
- ~[ ] Provide unit tests (under `<subproject>/src/test`) to verify logic~
- ~[ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes~
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by jvandort** [comment]
This is a source-incompatible change for Kotlin. We would need to wait for 9.0 for this change

**Comment by autonomousapps** [comment]
This feels overly cautious to me. As the issue Jendrik linked indicates, the fact that this can return null but there's no clear indication of it is a problem in its own right, and arguably a worse one. Is it really Gradle's policy to permit _no_ source compatibility changes outside of a major version release?

**Comment by jvandort** [comment]
I've asked the rest of the Build Tool team for clarification on our policy here

**Comment by jvandort** [comment]
Last I said I would ask about our nullable policy. I've confirmed we want to stick with source compatibility here and not add nullable anywhere in non major versions. 

However, I think we should be solving the root problem here, in that this code can return null at all. I think the code you linked to is just there to handle the symptoms of having edges without target nodes.

I am curious if you could provide a reproducer for this. 

I did find some in the Gradle integ tests already. Consider this reproducer, which I have found to illustrate at least one way we get into this state:

```
settingsFile << "include 'producer'"
file("producer/build.gradle") << """
    configurations {
        consumable("one") {
            outgoing {
                capability('o:n:e')
            }
            attributes {
                attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.class, "foo"))
            }
        }
        consumable("one-preferred") {
            outgoing {
                capability('o:n:e')
                capability('g:one-preferred:v')
            }
            attributes {
                attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.class, "foo"))
            }
        }
    }
"""
buildFile << """
    configurations {
        dependencyScope("implementation")
        resolvable("classpath") {
            extendsFrom(implementation)
            attributes {
                attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.class, "foo"))
            }
        }
    }

    configurations.classpath {
        resolutionStrategy.capabilitiesResolution.all { details ->
            def selection =
                details.candidates.find { it.variantName.endsWith('preferred') }
            println("Selecting \$selection from \${details.candidates}")
            details.select(selection)
        }
    }

    dependencies {
        implementation(project(':producer')) {
            capabilities {
                requireCapability('o:n:e')
            }
        }
        implementation(project(':producer')) {
            capabilities {
                requireCapability('o:n:e')
                requireCapability('g:one-preferred:v')
            }
        }
    }

    task resolve {
        def root = configurations.classpath.incoming.resolutionResult.rootComponent
        doLast {
            println(root.get().dependencies)
        }
    }
"""
```

In essence, we have some component that produces two variants that each share a capability. Somehow, both of those variants get selected by other nodes in the graph. Then, capability conflict handler comes around and evicts one of the nodes. However, this puts the graph into a bad state, presumably since the feature was never built to handle the corner case where two conflicting nodes are part of the same component. 

I've drilled down the problematic code to around [here](https://github.com/gradle/gradle/blob/4d17e942a95aa53b11ea0fd96b28868c61ea9c31/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java#L1090).

From what I can tell, after a conflict we ask the nodes in the conflicting components to `restart`. For every node of the component, [we find all incoming edges, detach them from their nodes, and re-attach them](https://github.com/gradle/gradle/blob/4d17e942a95aa53b11ea0fd96b28868c61ea9c31/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java#L1082-L1089). 

Afterwards, we do a blanket `incomingEdges.clear()`. This clear fails to update the state of the actual nodes that are pointing to this node. Those edges still think they are pointing to this restarted node. So, we have an edge that targets a node, but the node does not think it is being targeted. 

I've tried to fix this two ways, each with different solutions:
1) Remove the `clearIncomingEdges` line. This causes the evicted nodes to remain present in the final graph. This is not what we want. 
2) Attempt to detach the problematic edges to keep the state consistent between the node and the edge like:
```
List<EdgeState> incomingEdges = ImmutableList.copyOf(this.incomingEdges);
clearIncomingEdges();
for (EdgeState incomingEdge : incomingEdges) {
    NodeState from = incomingEdge.getFrom();
    from.removeOutgoingEdge(incomingEdge);
}
```

This causes the edges to not be present at all in the final graph, something that can be very confusing, as the edge originally existed but is not present in the `ResolutionResult`.  For example, this can cause first-level edges to not appear in the resolution result (in the above reproducer, that means the first declared dependency is not present). It would seem we do not want this solution either. 

What I think is the proper solution is to remove the `clearIncomingEdges` call linked above.  I do not see why this call is here, and looking back at git history, its been there forever.  The `edge.restartConnected` handles disconnecting and re-connecting edges and ensures consistent state between nodes and edges. 

I am not really sure where to go from here. This code is all really complex and stateful. I have a feeling we might be able to mess with [this](https://github.com/gradle/gradle/blob/4d17e942a95aa53b11ea0fd96b28868c61ea9c31/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/NodeState.java#L1066-L1079) method here, since it is already checking the `evicted` flag. 

However, what I think the root of the problem is that after we evict the non-preferred node, it gets re-selected again after `restartConnected -> attachToTargetConfigurations -> calculateTargetConfigurations`. The [actual code](https://github.com/gradle/gradle/blob/4d17e942a95aa53b11ea0fd96b28868c61ea9c31/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/EdgeState.java#L258-L279) that selects new variants does not take into account that a given node is evicted or not. This means that when we restart a given node, we allow the algorithm to select evicted nodes again. The variant matching algorithm then happily selects the variant that has the exact matching capabilities, as opposed to the non-evicted one with  more than the exact requested capabilities. 

I apologize for the wall of text here. This code is quite unfamiliar to me and I understand you might have some experience here. @melix It looks like you've touched a lot of this code as well. Do have any advice?

**Comment by melix** [comment]
Unfortunately I don't recall the details. It is indeed a very complicated piece of code which is easily broken by any change, so I've been careful not to remove things I didn't understand what they were doing....

**Comment by jvandort** [comment]
@melix Thank you for chiming in. Hopefully I'll be able to get to the bottom of this. I'd like for us to be able to maintain this code instead of being afraid to make changes

**Comment by jvandort** [comment]
Linking my working changes for recordkeeping: https://github.com/gradle/gradle/compare/jvandort/iss/26016/reproducer

**Comment by jvandort** [comment]
Adding `@Nullable` here is not what we should do. This is a bug and we should never return null from this method

**Comment by jvandort** [comment]
Closing since this is not the solution we souls pursue

**Pull request closed without merging**
