### PR TITLE
Keep parameter names in compiled class files

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes https://github.com/gradle/kotlin-dsl/issues/464

### Context
See https://github.com/gradle/kotlin-dsl/issues/464

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [x] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by bamboo** [comment]
Why also `-Xlint:-classfile`?

**Comment by bamboo** [comment]
Hm, `javac: invalid flag: -parameters`, is this java 8 only?

**Comment by JLLeitschuh** [comment]
Yes, it seems to be a java 8 only feature. What JDK is used to build your releases? If it isn't JDK 8 then this change is pretty much useless.

**Comment by JLLeitschuh** [comment]
@oehme Are all of these sanity checks failing because they run under JDK 7 which doesn't support these javac parameters?

**Comment by oehme** [comment]
Our releases are still built with Java 7, because that's what we guarantee Gradle will run on. We are currently discussing a move to Java 8 in Gradle 5.0.

We could cross-compile with Java 8, but so far we've preferred to build with the exact version we target as our lower bound to avoid any surprises. I think doing such a change would be pretty contentious at the moment and parameter names are probably not going to make a strong enough case.

**Comment by JLLeitschuh** [comment]
> We are currently discussing a move to Java 8 in Gradle 5.0.

As in fullstop no longer supporting Java 7 in releases 5.0 or greater?

**Comment by oehme** [comment]
> As in fullstop no longer supporting Java 7 in releases 5.0 or greater?

As the JVM Gradle runs on, yes. You'd still be able to cross-compile and test for older versions.

**Comment by JLLeitschuh** [comment]
Wouldn't you be unable to cross compile if you start putting lambdas in gradle code though?

**Comment by oehme** [comment]
Only a tiny fraction of the Gradle code base is used in compiler processes/test processes. That part would still be compiled against Java 6.

**Comment by JLLeitschuh** [comment]
Would it be acceptable to fix this PR such that it only adds these arguments if you are compiling under JDK 8? That way, when gradle does eventually shift to JDK 8 this support will already be there?

**Comment by bamboo** [comment]
The actual culprit here is that we don't preserve parameter names in the generated Gradle API jar, that's what we give the Kotlin compiler.

So theoretically, we could solve this issue by finding a way to preserve parameter names in the generated Gradle API jar without actually changing the Gradle compilation pipeline.

**Comment by oehme** [comment]
Afaik the Gradle API jar is created from the code in the distribution, so it'll contain whatever bytecode we created on CI.

**Comment by JLLeitschuh** [comment]
Any more thoughts on this? Should I close this out? Should I leave it here for later? What would be the most useful right now?

**Comment by bamboo** [comment]
Thanks for the PR, @JLLeitschuh. The solution proposed here will make sense once Gradle moves to Java 8 and we can revisit it then, I'll close it for now.

In the meantime, maybe a solution with https://github.com/paul-hammant/paranamer would be more viable?

**Pull request closed without merging**
