### PR TITLE
Add `documentation` platform to the repository structure

### PR DESCRIPTION
**Pull request by lkasso**
Creates `documentation` platform.
Moves `subproject/docs`, `subproject/docs*`, and `subproject/samples` to `platform/`.

### CODE REVIEW

**Review by eskatos — CHANGES_REQUESTED** [review]
:x: The root `settings.gradle.kts` needs to be updated

**Review by eskatos — APPROVED** [review]
LGTM :+1:

**Review by tresat — CHANGES_REQUESTED** [review]

**Comment by lkasso** [comment]
@bot-gradle merge

**Comment by lkasso** [comment]
@bot-gradle merge

**Comment by lkasso** [comment]
@bot-gradle merge

**Pull request merged**
