### PR TITLE
Rename „META-INF/services“ to „META-INF/groovy“ for Groovy Extension Modules

### LINKED ISSUE #11028: Compliance with Groovy 2.5's Standard Mechanism for Specifying Extension Modules
### Expected Behavior

The Gradle build tool is expected to comply with the standard mechanisms that are specified for correctly configuring the external dependencies it uses. In the context of this issue „*compliance*“ and „*correctly configuring*“ means the configuration specified by the upstream external projects that produce the external libraries that the Gradle build tool depends on.

### Current Behavior

In Gradle version 5.6.2, the *`«$GRADLE_USER_HOME»/caches/5.6.2/generated-gradle-jars/gradle-api-5.6.2.jar`* file contains a service configuration file that — *according to Groovy maintainer @blackdrag* — does not comply with [*the Groovy project's most up-to-date standard mechanism for configuring Groovy Extension Modules*](http://bit.ly/Groovy8480). The same non-compliant configuration can currently be found in Gradle's version 6+ early access releases too.

### Context

As a developer of a library that will be distributed as a JPMS module, I am trying to accomplish unit testing of the classes of my JPMS-modularized library.

During the development and unit testing of my library, I was affected by the JPMS development hurdle reported in Gradle issues *#11027* and *#10408*. 

The specific Groovy project-specified standard mechanism that Gradle is not in compliance with, is prescribed [*in Groovy Issue \#8480*](http://bit.ly/Groovy8480)...

>
> ***org.codehaus.groovy.runtime.ExtensionModule should move to META-INF/groovy***
> ...
> ***Description***
> 
> „*To avoid confusing Java 9's ModuleFinder. We should fall back to the current location to handle existing jars...*“
> ...
>

I was made aware of the above issue by Groovy maintainer, @blackdrag, [*in a jigsaw-dev mailing list discussion*](http://bit.ly/jigsawdev014293)...

> ...
>„...*No idea what gradle uses here, but the standard mechanism uses now*
> *META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule*
> *(https://issues.apache.org/jira/browse/GROOVY-8480). So I assume Gradle*
> *is there still on Groovy 2.4*...“
> ...

As far as I have been able to determine, [*Gradle version 5.6+ uses Groovy version 2.5+*](http://bit.ly/buildInitL89) by default:

```
...
findLatest("groovy", "org.codehaus.groovy:groovy:(2.5,)", versionProperties)
...
```

GROOVY-8480 was resolved in March, 2018. So I would have expected Gradle to have been in compliance with Groovy's standard mechanisms for that version by now.

### The Problem

***TL;DR*** — Even if the hurdle reported in issues *#11027* and *#10408* is successfully gotten around, *`«$GRADLE_USER_HOME»/caches/5.6.2/generated-gradle-jars/gradle-api-5.6.2.jar's`* malformed *`META-INF/services/org.codehaus.groovy.runtime.ExtensionModule`* service configuration file entry means any expectation of using that particular Gradle library as an automatic module is still „*out of the question*“.

A more detailed discussion of the problem can be found in [*this jigsaw-dev mailing list thread*](http://bit.ly/jigsawdev014289).

### Steps to Reproduce 

1. [*Download and unpack this zip-archived project*](http://bit.ly/antiUpLoad)
2. In your computer's file explorer, navigate to *`«$GRADLE_USER_HOME»/caches/5.6.2/generated-gradle-jars/gradle-api-5.6.2.jar`* 
3. Open the JAR file in an archive management tool
    • Do not *extract* the contents. Actually *open* the JAR so that you can navigate it as if it were another file system folder
4. Navigate to the *`META-INF/services`* entry of the JAR
5. Extract the *`META-INF/services/java.security.Provider`* service configuration file entry to a folder on your hard drive
6. Edit the extracted *`java.security.Provider`* file so that it contains the single line shown below:
    
```
org.gradle.internal.impldep.org.bouncycastle.jce.provider.BouncyCastleProvider

```
7. Replace the original, incorrect two-line, *`META-INF/services/java.security.Provider`* service configuration file entry in the JAR file, with the corrected one-line one you just edited in Step 6.
   
8. In a terminal opened in the root folder of the project downloaded and unpacked in Step 1, run the *`:test`* task:

```
./gradlew :test
```
9. Observe the error printed to stdout:

```
...
...[QUIET] [system.out] Error occurred during initialization of boot layer
...[QUIET] [system.out] java.lang.module.FindException: Unable to derive module descriptor for «$GRADLE_USER_HOME»/caches/5.6.2/generated-gradle-jars/gradle-api-5.6.2.jar
...[QUIET] [system.out] Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class moduleName=model-core not in module
...
```

### Your Environment

```
------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          12 (Oracle Corporation 12+33)
OS:           Windows amd64
```

### PR DESCRIPTION
**Pull request by lingocoder**
Fixes #11028

### Context

The proposed change will bring Gradle 5.6.2+ into compliance with [*the Groovy project's most up-to-date standard mechanism for specifying Extension Modules*](http://bit.ly/jigsawdev014293)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by lingocoder** [comment]
Hi @big-guy. Please, can you point me at where in the code base I can find the *`META-INF/services/java.security.Provider`* service provider configuration file that [*this related issue demonstrates is also defective*](http://bit.ly/Issue11027)? I can fix that up real quick.

I have searched like crazy. Two or three different times. But no luck finding it nor any reference to it anywhere in any code. It's like it just turns up in *gradle-api-{version}.jar* out of thin air.

I gotta give it to you Gradle devs. Gradle code is like magic to mere mortal coders like moi :+1:

TIA.

**Comment by lingocoder** [comment]
I ran the wrong git command and screwed up the branch. So I'm closing this and will brb with a do-over.

**Comment by big-guy** [comment]
@lingocoder FYI I think `META-INF/services/java.security.Provider` is probably coming from one of the dependencies we're shading.

**Comment by lingocoder** [comment]
Hey @big-guy,

Yeah. I found it. Thanks. I figured out what was causing the problem in *#11027* and *#10408*. 

I've got a fix and a test coded up. I should have a PR for that #11027 pushed soon-ish. 

I've been wrestling with IntelliJ for the last few hours though. So far, Intellij is winning. 

A little bit off topic, big-guy, but, have you ever had a situation where you could see code you'd changed in the Intellij editor, but in the debugger, all you see is the old code as it was before your change? I'd never seen that anywhere else before until working in the Gradle fork.  I've built and rebuilt the project a half dozen different times now. Can you think of anything off the top of your head I might have overlooked? TIA.

**Pull request closed without merging**
