### PR TITLE
Ensure the changes in the accepted-public-api-changes.json file are alphabetically ordered

### PR DESCRIPTION
**Pull request by tresat**
This adds a new task type in the binary-compatibility that can check if the JSON in the API changes
file is ordered alphabetically.  Since everyone seems to add new changes to the bottom of the file when
removing deprecated elements, this leads to difficult merging.  Keeping the file alphabetized will make
merges much more likely to succeed.

This also adds test-kit tests for the new task, registers a task to run to check the alphabetization prior to
running the arch unit project tests which would use the file, and reorders the existing change file so it passed.

It does NOT have that plugin automatically create and wire the task, unfortunately, as the task was written in Kotlin and
would need to be migrated to Groovy for this to be possible.

Failures report the change nodes in the JSON which are misordered, like this:

```
9: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':architecture-test:verifyAcceptedApiChangesOrdering'.
> API changes in file 'accepted-public-api-changes.json' should be in alphabetical order (by type and member), yet these changes were not:
        Type: 'org.gradle.api.artifacts.ArtifactIdentifier', Member: 'Method org.gradle.api.artifacts.ArtifactIdentifier.getClassifier()'
        Type: 'org.gradle.api.AntBuilder', Member: 'Class org.gradle.api.AntBuilder'
```

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by vlsi** [comment]
An alternative option would be "accept file per `type`" style

**Comment by tresat** [comment]
> An alternative option would be "accept file per `type`" style (many small files instead of one big one). Small files would be easier to merge: they won't conflict if people added accepted changes for classes having similar names.

That is an option, but would be a change to the compatibility check tasks.  It might also just move the merge problems into the per-type files for commonly changed classes with large APIs seeing lots of deprecation.  I think it would be better to keep a single file.

**Comment by vlsi** [comment]
>  but would be a change to the compatibility check tasks

I agree.

> It might also just move the merge problems into the per-type files for commonly changed classes with large APIs seeing lots of deprecation

Not really.
Suppose you add a task that "splits singlefile into multiple files".

Then everyone who just runs the task before they merge.

With single-file, even changes to different types might cause conflicts.
With multi-file the only way there would be conflicts is when people change the same file, at which point it might be worth looking into the lines.

One big file might be not that suitable for editing in IDE.

**Comment by tresat** [comment]
@vlsi  - I'll bring this idea up with the team, but I still think we'd rather just have a quick check on top of the existing file rather than splitting it.  Currently it's only 600 lines as we work towards Gradle 8, a size that is totally manageable.  Thanks for the feedback!

**Comment by tresat** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
