### PR TITLE
Partially apply Nullable state for KDsl in Provider

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes PARTIALLY #12388

### Context
This PR partially fixes the issue linked above, specifically for the `map` case. I ran into a parsing bug in QDox trying to add `@Nullable` to the `flatMap` call as well, that I simply don't have the energy to investigate. I would really appreciate if someone from Gradle could assist in getting that working as well, possibly by replacing QDox since it seems unmaintained.

I did include JB annotations since the JSR305 ones cannot apply to `TYPE_USE`. I hope this is okay as it is the only proper solution.

I would still like to get the partial fix in if possible.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by lptr** [comment]
One downside I see with this is that after the change IntelliJ will offer up both `@Nullable`s for auto-import.

**Comment by octylFractal** [comment]
Yes, I was not confident in doing a full move to JetBrains annotations as the initial spike, but if that would be potentially desirable to avoid that import issue, I can do that too.

**Comment by octylFractal** [comment]
ping for stale bot

**Comment by lptr** [comment]
I don't think introducing the double `@Nullable` annotation and the confusion it brings is worth it for just this use case. I can see a couple ways forward:

- abandon this PR
- figure out how to avoid the duplicate `@Nullable` annotation on the classpath. We could migrate completely to JetBrains annotations (and whether or not that would be good for us).

An option for the latter would be to somehow generate JSR305 annotations from JetBrains annotations during build. Just an idea.

**Comment by bamboo** [comment]
Could we define our own `Nullable` annotation for that scenario?

**Comment by lptr** [comment]
@bamboo Do you mean to add something like a `@NullableType` that only applies to `ElementType.TYPE_USE` and add it to IntelliJ as one more nullable annotation?  I like it!

I think that might be the best course of action, as:
- it allows us keep using `@javax.annotation.Nullable` in most places,
- does not require massive changes throughout the codebase,
- doesn't introduce a duplicate `@Nullable` annotation.

IIUC, we'd need to add it to `.idea/misc.xml` under `NullableNotNullManager/myNullables`. However, that file is not currently tracked in Git, though looking at the contents it probably should be.

If we add a `@NullableType` annotation, we should also add a matching `@NonnullType` annotation, and add that under `NullableNotNullManager/myNotNulls` in `misc.xml` as well.

**Comment by lptr** [comment]
The only problematic thing in `misc.xml` seems to be `ProjectRootManager@project-jdk-name` which I believe points to a machine-local JDK name... 🤔

**Comment by bamboo** [comment]
> Do you mean to add something like a @NullableType that only applies to ElementType.TYPE_USE and add it to IntelliJ as one more nullable annotation?

Exactly. We'd also need to configure the Kotlin compiler to recognize the annotation.

**Comment by lptr** [comment]
Seems like we have a plan. How do we get there?

**Comment by wolfs** [comment]
I am not sure if introducing another annotation for something being nullable makes sense. Does this mean that build script editors also would need to add this annotation to their list of nullability annotations in IDEA? Or would that happen somewhat automatically? We could use this for stuff we have on our internal APIs, though I don't understand what the effect on the public API is and if there is some configuration necessary for the consumers of the public API (aka plugin and build authors).

**Comment by lptr** [comment]
> We could use this for stuff we have on our internal APIs, though I don't understand what the effect on the public API is and if there is some configuration necessary for the consumers of the public API (aka plugin and build authors).

I'd do this for internal APIs only for now. I'm also wondering if there's any initiative to make JSR-305's `@Nullable` applicable to type parameters. 🤔 If that happens at some point, we could adopt it in place of our own annotations.

**Comment by octylFractal** [comment]
JSR-305 is basically dead, and large libraries like Guava are actively investigating ways to move to other annotations: https://github.com/google/guava/issues/2960. The current efforts are mostly focused on [jspecify](https://github.com/jspecify/jspecify), which is backed by [many large players](https://jspecify.dev/#participants) in this space, such as Google, JetBrains, and SonarSource.

Changing this for internal APIs doesn't help with the point of this PR, which is to eliminate the need for workarounds in Kotlin DSL due to strict null checks applied by the Kotlin compiler without these annotations.

**Comment by lptr** [comment]
> JSR-305 is basically dead, and large libraries like Guava are actively investigating ways to move to other annotations: [google/guava#2960](https://github.com/google/guava/issues/2960). The current efforts are mostly focused on [jspecify](https://github.com/jspecify/jspecify), which is backed by [many large players](https://jspecify.dev/#participants) in this space, such as Google, JetBrains, and SonarSource.
> 
> Changing this for internal APIs doesn't help with the point of this PR, which is to eliminate the need for workarounds in Kotlin DSL due to strict null checks applied by the Kotlin compiler without these annotations.

Good points. I wasn't aware of `jspecify`. I wonder how much we should rely on that project, though, as it doesn't seem to be moving very fast either: https://github.com/jspecify/jspecify/pulse

So what happens if we do add our own annotation for public APIs? What breaks?

**Comment by bamboo** [comment]
> Does this mean that build script editors also would need to add this annotation to their list of nullability annotations in IDEA? 

At least for the Kotlin DSL that shouldn't be the case as we can influence the Kotlin compiler settings via the script templates.

**Comment by eskatos** [comment]
Kotlin 1.5.20 added support for jspecify, see https://kotlinlang.org/docs/whatsnew1520.html#support-for-jspecify-nullness-annotations

**Comment by kevinb9n** [comment]
> Good points. I wasn't aware of `jspecify`. I wonder how much we should rely on that project, though, as it doesn't seem to be moving very fast either: https://github.com/jspecify/jspecify/pulse

I can say in our defense that we've been making steady progress in less-visible ways... but yeah, it has been slower going than we'd hoped. We're still serious about it though. Would anyone from this library want to talk further? I'd like to help you figure out what's worth waiting for vs. what can be worked around, etc.

**Comment by octylFractal** [comment]
> Would anyone from this library want to talk further?

Yes, that would be nice. You can reach me at `otogami@gradle.com`.

**Comment by Vampire** [comment]
Please also fix this for `CopySpec#filter` which also has `null` as expected return value.

**Comment by Fleshgrinder** [comment]
This should be closed, because it is not actually going to fix anything (well, it allows Kotlin to compile with just a warning, that is some improvement).

It is not sufficient to mark the `Provider.map` function's `Transformer` `OUT` parameter type as `@Nullable` if the `Transformer` interface itself specifies that that type is `@NotNull` (implicitly through the `@NonNullApi` catch-all annotation).

nullable-not-sufficient

The first step towards a proper fix has to be:

```java
public interface Transformer<OUT extends @Nullable Object, IN extends @Nullable Object> {
    OUT transform(IN in);
}
```

This, however, is impossible because Gradle is for some reason still compiled for Java 6. In Java 6 these kind of annotations are not possible.

java-6-issue

**Comment by octylFractal** [comment]
Superseded by #23164.

**Pull request closed without merging**
