### PR TITLE
Update performance improvements section

### PR DESCRIPTION
**Pull request by wolfs**
with a new graph comparing 6.8 and 7.0.

Fixes gradle/gradle-private#3317

### CODE REVIEW

**Comment by wolfs** [comment]
Rendered version: 
image

**Review by melix — APPROVED** [review]
I don't read base64 encoded strings so I couldn't prove that the image is correct :)

**Comment by wolfs** [comment]
> I don't read base64 encoded strings so I couldn't prove that the image is correct :)

That is why I included a screenshot above.

**Comment by melix** [comment]
This was meant as a joke but I failed :)

**Pull request merged**
