### PR TITLE
Remove duplicate multi-language docs configuration

### PR DESCRIPTION
**Pull request by jvandort**
This js and css is added twice to the final built documentation, since the
MultiLanguageSamplesDocinfoProcessor in 'docs-asciidoctor-extensions-base'
adds them as well.

See: #20701

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test BD

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by tresat — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test BD

**Comment by jvandort** [comment]
@bot-gradle test BD

**Review by big-guy — APPROVED** [review]
This appears to be working on the pages I checked

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by mahozad** [comment]
The icon in used in [Gradle userguide page](https://docs.gradle.org/current/userguide/userguide.html) needs to be updated as well:

screenshot-docs gradle org-2022 07 22-13_32_56

**Comment by big-guy** [comment]
@jvandort ☝️ could you take care of that reference too?

**Comment by DPUkyle** [comment]
> @jvandort ☝️ could you take care of that reference too?

How are these inline svgs created? https://github.com/gradle/gradle/blame/master/subprojects/docs/src/docs/userguide/userguide.adoc#L30

**Comment by big-guy** [comment]
I think it's from https://kotlinlang.org/docs/kotlin-brand-assets.html

**Comment by jvandort** [comment]
@big-guy will take care of it

**Comment by jvandort** [comment]
@DPUkyle @big-guy See https://github.com/gradle/gradle/pull/21359

**Pull request merged**
