### PR TITLE
Prefer dependencies without test sources attribute

### LINKED ISSUE #21968: Depending on multiple configurations leads to broken buildship classpath
### Expected Behavior

Given subproject A:

```gradle
apply plugin: 'java'

configurations {
    testConfig
}

// [...]
```

and subproject B:
```
apply plugin: 'java'

dependencies {
    implementation project(':A')
    testRuntimeOnly project(path: ':A', configuration: 'testConfig')
}
```

Things should work like before: subproject B has an implementation dependency on the main configuration and a test dependency on an additional configuration of subproject A. Those dependencies should work in buildship like in Gradle.

### Current Behavior

There's only a test dependency in buildship, no implementation dependency.

### Context

We use multiproject builds extensively. We usually have one core subproject and a bunch of other subprojects. The other subprojects often rely on some common test resources from the core subproject like logging configurations, test configurations, test keystores etc. So naturally, our subprojects depend on the code from the core subproject for their `implementation` classpath and depend on the test resources (exported in their own "configuration") for their `testRuntimeOnly` classpath.

This stopped working in Gradle 7.5.

### Steps to Reproduce 

I created a minimal project reproducing this error: [buildship-bug.zip](https://github.com/gradle/gradle/files/9546202/buildship-bug.zip)

Unzip it, the build should work when building on the command-line. However, importing this into Eclipse/Buildship, the compiler complains because of the aforementioned classpath issues.

### Your Environment

Windows 10, Java 11, Gradle 7.5.1

### PR DESCRIPTION
**Pull request by oleosterhagen**
When mapping multiple entries on the classpath to a single project dependency in Eclipse Buildship or the XML generator for `.classpath` files, prefer a dependency without the "test sources" attribute, if one exists. Otherwise, dependencies would only be visible for test sources and not the main sources in the dependent project.

If there is more than one entry for a project dependency after applying this rule, the actual entry is chosen in the same order as before.

Fixes #21968, #22838, https://github.com/eclipse/buildship/issues/1206 and https://github.com/redhat-developer/vscode-java/issues/2784

### Context
This change would reduce the number of cases which need manual adjustments of the [EclipseClasspath](https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.eclipse.model.EclipseClasspath.html#org.gradle.plugins.ide.eclipse.model.EclipseClasspath) in the build script, especially when using the `java-text-fixtures` plugin. Often these manual steps need a good understanding of the inner workings of the Gradle Eclipse plugin.

Also on the _Gradle Forums_ it is mentioned that the current behavior does not provide the best first time user experience: [‘testFixtures’ don’t work with ‘implementation’ in Eclipse only](https://discuss.gradle.org/t/testfixtures-dont-work-with-implementation-in-eclipse-only/47275)

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [X] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ov7a** [comment]
Thank you for your contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the design of the implementation choices.

**Review by donat — APPROVED** [review]
Thank you very much for your contribution. Kudos for the well thought-out implementation (both model building and file generation is covered) as well as for the excellent test coverage!

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle merge

**Comment by donat** [comment]
@oleosterhagen Thank you for the contribution!

**Comment by donat** [comment]
> @oleosterhagen Thank you for this! We lost hope and thought we would have to stay on 7.4.2 forever.

Thanks for the feedback! This is the kind of comment which reinforces us to keep investing in the maintenance of this plugin. 

> @donat As we can't make the switch to Gradle 8, is a backport to Gradle 7.x a possibility? 🙏

Frankly, with the given our [roadmap](https://blog.gradle.org/roadmap-announcement) and the resources we have, I'd say it's highly unlikely. Currently we can only do bugfix releases for the latest released Gradle version.

**Comment by donat** [comment]
What's blocking you from upgrading to Gradle 8.0?

**Pull request merged**
