### PR TITLE
Changed to not clear the preferred version when setting a strict version

### LINKED ISSUE #12661: In version constraints, the order of `prefer X` vs `strict Y` matters
The [documentation](https://docs.gradle.org/current/userguide/rich_versions.html) suggests that using strict versions should be compatible with using preferred versions, but in practice there are issues when used together.  In particular, the order matters.

### Expected Behavior
The order of `prefer` vs `strictly` should not matter when specifying version constraints

### Current Behavior
Currently, `prefer` has to be placed after `strictly`

### Steps to Reproduce 
I created an example project here:
https://github.com/svermeulen/GradleBugExample-StrictVersionOrdering

Then:
* `cd foo`
* `./gradlew dependencies | grep bar`
* Observe that bar version `1.2.0` is chosen
* Move the `prefer` line to be after the `strictly` line in `foo/build.gradle`
* Execute `./gradlew dependencies | grep bar` again
* Observe the bar version is now chosen as `1.0.0`

### Your Environment
macOS

### PR DESCRIPTION
**Pull request by svermeulen**
Fixes #12661 

### Context
This allows specifying preferred version and strict version and have the result more predictable.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by svermeulen** [comment]
Will do!

**Comment by svermeulen** [comment]
Ok I added a unit test for this change.  It passes, but I'm seeing these errors when I execute `./gradlew dependencyManagement:check`:

image

However, I get these same errors when running the tests on a clean version of master too, so I think they are unrelated

**Comment by ljacomet** [comment]
@svermeulen That's strange, but I would not worry too much. I will run a full build on the branch anyway and I validated locally that your changes allowed `dependencyManagement:check` to pass.

However your second commit does not have the sign off. Could you add it please?

**Comment by svermeulen** [comment]
@ljacomet Oh, oops, forgot about that.  I've fixed this now.

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Pull request merged**
