### PR TITLE
Update search settings for user manual 

### PR DESCRIPTION
**Pull request by lkasso**
### Details
This is a Documentation change ONLY.

### Context
Updates the search box in the documentation user manual to [Algolia DocSearch V3](https://docsearch.algolia.com/) with a new index that is updated weekly for the:
1. User manual
2. Javadocs
3. Groovy DSL
4. Kotlin DSL

The PR:

- Removes old search box in HTML
- Removes some unused CSS
- Removes some old system output
- Mirrors https://github.com/gradle/documentation-portal/pull/269

### Reviewers: 
No notes.

Screenshot 2024-05-29 at 3 32 16 PM
Screenshot 2024-05-29 at 3 32 34 PM

### CODE REVIEW

**Comment by lkasso** [comment]
@bot-gradle test BD

**Review by tresat — APPROVED** [review]
Better docs search functionality will be awesome!

At some point, it might be worth having the front end team look at the styling of the search dialog to make it more similar to the rest of the site.

**Comment by alllex** [comment]
I think we should change the accent color of the Algolia popup from the purple-ish (shown on the screenshot) to one of the Gradle brand colors.

**Comment by MGaetan89** [comment]
> I think we should change the accent color of the Algolia popup from the purple-ish (shown on the screenshot) to one of the Gradle brand colors.

Also, it seems that the Gradle logo in the top left corner turns purple when the popup is open.

**Pull request merged**
