### PR TITLE
Test portback of fix #15637

### PR DESCRIPTION
**Pull request by archfz**
Signed-off-by: Fodor Zoltan <fodor18zoltan@gmail.com>

Attempts portback for #15536 . Cherry picked from #15637

### Context
Need this in 6 as 7 is too far still. This is my first PR to gradle, also I am quite new to gradle, and I am not a java developer :D.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by archfz** [comment]
Initial purpose here is to check if tests pass. I don't see how that can be triggered, or whether there is pipeline for such.

**Comment by blindpirate** [comment]
@archfz I've updated the configuration for `release6x` pipeline, you should be able to access it now. The failures are not your fault, but some stale configurations on the branch. I've fixed it and merged it into your branch.

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Comment by archfz** [comment]
Re

**Comment by ljacomet** [comment]
Thanks for the PR, we are going to do a 6.9.2 but this looks like quite a large changeset and I am not sure it is worth the risks.

Can you rebase it on the latest `release6x` so we can run tests in an up-to-date context?

In parallel, I am looking at the code and asking others internally to assess whether we take this contribution and risk or not.

**Comment by archfz** [comment]
Updated from upstream. Sounds good if it could get included. 
This is important, see in https://github.com/gradle/gradle/issues/15536 all the attempts to have hotfix, none of those work properly for our case.

**Comment by archfz** [comment]
@bot-gradle test RFN

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
This branch needs some recent changes on `release6x` to work. @bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by archfz** [comment]
Do I need to help?

**Comment by blindpirate** [comment]
@archfz No there's nothing your fault, `release6x` is an old branch and we have some problems triggering community builds. I'm taking care of it.

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@archfz Looks like in order to get a build, your PR needs to be rebased again the latest `release6x`. Can you please do that when you have a chance?

**Comment by archfz** [comment]
@ljacomet Updated.

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
This looks like it is passing tests and is isolated enough without follow-ups on the 7.x line.
So should be good to go in the upcoming 6.9.2

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
