### PR TITLE
Fix GradleBuildPerformanceTest retry

### PR DESCRIPTION
**Pull request by eskatos**
by moving runner specs declaration out of the test method
because RetryRule is a MethodRule and reuse the setup test instance.

### CODE REVIEW

**Comment by eskatos** [comment]
Feedback build https://builds.gradle.org/viewQueued.html?itemId=10868704

**Comment by eskatos** [comment]
@oehme I'm not so sure. Our retry `MethodRule` retries test methods without running  `setup()` again. And the [original failure](https://builds.gradle.org/viewLog.html?buildId=10853083&buildTypeId=Gradle_Check_IndividualPerformanceScenarioWorkersLinux) was about declaring a runner spec with a name that already exists. So my understanding is that we need to extract the runner specs declaration into the `setup()` method so they are not run again when retrying. Did I miss something?

**Comment by eskatos** [comment]
But yeah, the feedback build failed this way, so it's not enough. I'll move the `runner` instantiation to `setup()`. If you could shed some light upon me so I understand what I do would be nice :)

**Comment by oehme** [comment]
The retry rule does rerun setup. You are getting this failure because you are reusing the runner (you declared it in a field initializer). All the other code can stay in the test method, only the `new Runner...` needs to go to `setup()`. See https://github.com/gradle/gradle/blob/master/subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/AbstractCrossVersionPerformanceTest.groovy

**Comment by eskatos** [comment]
> The retry rule does rerun setup. 

Then this is confusing right?:
https://github.com/gradle/gradle/blob/bba54cbeacce26f762feffd205e79c0e50b9fec2/subprojects/internal-testing/src/main/groovy/org/gradle/testing/internal/util/RetryRule.groovy#L34

**Comment by oehme** [comment]
Yeah, probably some leftover. Look at the implementation, it clearly runs setup/cleanup.

**Comment by eskatos** [comment]
Feedback build https://builds.gradle.org/viewQueued.html?itemId=10876806

**Pull request merged**
