### PR TITLE
Avoid multiple problem locations in report

### PR DESCRIPTION
**Pull request by donat**
Cherry-picking https://github.com/gradle/gradle/pull/30777 to `release`.
Partially fixes https://github.com/gradle/gradle/issues/30844.

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

**Review by reinsch82 — APPROVED** [review]
LGTM
Thx

**Comment by donat** [comment]
@bot-gradle merge

**Pull request merged**
