### PR TITLE
Retain stacktrace when test method is inherited

### PR DESCRIPTION
**Pull request by vlsi**
By default Gradle is trying to find "test class name" in the stacktrace (which is smart!), however,
there are cases when test class name never appears in the stacktrace.
For instance, it might happen when test class uses inheritance.
The inheritance is typically used to test over different implementations.

The fix is to retain the stacktrace in case none of the lines match.

Fixes https://github.com/gradle/gradle/issues/11220

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by vlsi** [comment]
Oh, `:testingBase:codenarcIntegTest` was failing, and now I've fixed it

**Comment by vlsi** [comment]
It was the first time I'm assigned to a PR in Gradle, so I'm a bit puzzled on the unspoken protocol here.

Did that mean "please fix :testingBase:codenarcIntegTest" errors?
Should I `unassign me` to convey that the changes are applied?

PS. The PR looks OK for me after I fixed codenarcIntegTest

**Comment by rieske** [comment]
Apologies for the delay @vlsi - reviewing the change now.

**Comment by rieske** [comment]
Thank you for the contribution @vlsi!

**Pull request merged**
