### PR TITLE
Don't hide Kotlin compiler configuration when Java 9+ is used

### LINKED ISSUE #17075: Struggling to define KotlinCompileDaemon params with gradle 7.0
Our android build specifies Kotlin JVM args as follows:
org.gradle.jvmargs=..... -Dkotlin.daemon.jvm.options=-Xmx1g  ....

### Expected Behavior
jps -v will show these values during a build e.g.
82861 KotlinCompileDaemon -Djava.awt.headless=true -Djava.rmi.server.hostname=127.0.0.1 -Xmx1g

### Current Behavior
The KotlinCompileDaemon seems to be inheriting the GradleDaemon args.

### Context

Works in 6.8.3, not in 7.0

We are in a memory constrained environment so trying to keep resource use under tight control

### Steps to Reproduce 
Set -Dkotlin.daemon.jvm.options
in org.gradle.jvmargs
Try on gradle 6.8.3 then on 7.0

### PR DESCRIPTION
**Pull request by donat**
Fixes #17075

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by rieske** [comment]
Since this fix is aiming for 7.2, we might as well be able to get rid of the current Java 16 workaround that introduced this regression. The `kotlin-dsl` plugins with Kotlin 1.5.10 looks to be released already: https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm/1.5.10

**Comment by rieske** [comment]
Let's see if this works on Java 16 instead: https://github.com/gradle/gradle/pull/17437

**Review by rieske — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Pull request merged**
