### PR TITLE
Exclude javadoc/sources jar from DistributionTest classpath

### PR DESCRIPTION
**Pull request by blindpirate**
We didn't make them reproducible.

### CODE REVIEW

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
