### PR TITLE
Use Google Snappy to compress task output cache artifacts

### PR DESCRIPTION
**Pull request by lptr**
Use [Snappy](https://github.com/dain/snappy) instead of GZip.

### CODE REVIEW

**Comment by lptr** [comment]
Branch build: https://builds.gradle.org/viewQueued.html?itemId=7526177

**Comment by lptr** [comment]
Looks like the "empty cache" cases are significantly faster with Snappy, but the non-empty ones are slower. Weird, from the JMH benchmarks it seemed that Snappy should be a ton faster than GZip (while not creating much more output).

**Comment by wolfs** [comment]
I did some performance measurements locally and snappy seems to be slower than GZip for unpacking: 
image

**Comment by lptr** [comment]
Let's try with not throwing away compressed data at all, and see what happens: https://builds.gradle.org/viewQueued.html?itemId=7591633

**Comment by lptr** [comment]
We are still slower than using GZip:

```text
Speed Results for test project 'largeJavaMultiProject' with tasks assemble, cleaned with clean: we're slower than 4.1-20170607235835+0000.
Difference: 121.5 ms slower (121.5 ms), 2.04%, max regression: 529.949 ms
```

**Comment by lptr** [comment]
Let's just not do this then.

**Comment by ijuma** [comment]
Might be worth trying zstd.

**Pull request closed without merging**
