### PR TITLE
Remove flaky annotation for script compilation test

### PR DESCRIPTION
**Pull request by ljacomet**
While it was flaky in the past, it is now pretty stable. Since the
flakiness was observed with the configuration cache, marking test as not
flaky for now.

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by mlopatkin — APPROVED** [review]
LGTM, thanks!

**Comment by ljacomet** [comment]
Well, looks like it failed once the `@Category` was removed ... so I am thinking that the issue here is interactions between this test and another one in the class.
Will keep investigating.

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
