### PR TITLE
Fixed typo in parentLoggerProvider's name

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by adrianbk** [comment]
@thedrow can you sign the [CLA](http://gradle.org/contributor-license-agreement/) ?

**Comment by thedrow** [comment]
Done.

**Comment by adrianbk** [comment]
@thedrow the CLA hasn't appeared on our end. Can you try again?

**Comment by thedrow** [comment]
Sure.

**Comment by adrianbk** [comment]
@thedrow thank you for this fix, it's much appreciated!

**Comment by thedrow** [comment]
@adrianbk Got the CLA?

**Comment by bigdaz** [comment]
Hey @thedrow, we never got notice of your signed CLA. Since this is such a minor fix, I'm just going to manually apply it and close the PR. Thanks anyway!

**Comment by thedrow** [comment]
@bigdaz I could never submit it since there was something wrong with your date field in the form.
Every date i typed was invalid.

**Pull request closed without merging**
