### PR TITLE
Remove deprecated method getAnnotationProcessorGeneratedSourcesDirectory

### PR DESCRIPTION
**Pull request by jvandort**
Also add commented out deprecations for 8.1+

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
Didn't realize there was prior work here. We are punting this to 9.0. Will put out a new PR updating the existing deprecation logger. https://github.com/gradle/gradle/pull/17105

**Pull request closed without merging**
