### PR TITLE
Fix WAR plugin configuration hierarchy

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by donat — APPROVED** [review]
LGTM; I just added a minor improvement: https://github.com/gradle/gradle/pull/18090/commits/9b309157390fbad496d9549ff5a93cb1cc05f0db

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
Thanks Donát for pushing it through and good catch on that leftover `compile` reference!

**Pull request merged**
