### PR TITLE
Fix punctuations

### LINKED ISSUE #28228: Fix punctuations
### Issue type

Styling or Accessibility

### Problem description

Fix lines 21, 64, 81

### Context (optional)

_No response_

### Page with the problem

platforms/documentation/docs/src/docs/release/notes.md

### PR DESCRIPTION
**Pull request by helfese**
Fixes #28228

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by lkasso** [comment]
@helfese, can you make the same changes to notes-template.md for this PR to be merged. Our system needs the files to be in sync.

**Review by lkasso — COMMENTED** [review]
Please update the release notes template as well.

**Comment by lkasso** [comment]
Template updated in: https://github.com/gradle/gradle/pull/28321/

**Review by lkasso — APPROVED** [review]

**Comment by hegyibalint** [comment]
Try to update the branch, as the GHA pipeline was broken, and the fixes were not merged.

**Pull request merged**
