### PR TITLE
Fixed a null pointer exception in GcsClient.

### LINKED ISSUE #12221: Dependency refreshing takes a long time with GCS Maven Repository
When dependencies are refreshing with a GCS (Google Cloud Storage) Maven Repository, the process takes a long time since it tries to find all dependencies separately in GCS.

By "dependency refreshing", I don't mean a full refresh with "--refresh-dependencies", only the one that runs before every task (I think, I am not 100% how the gradle decides to check dependencies, could be our `resolutionStrategy.cacheChangingModulesFor 0, 'seconds'` for SNAPSHOT dependencies that makes it happen before every task).

I have identified that a solution is to fix a bug where a value in https://github.com/gradle/gradle/blob/master/subprojects/resources-gcs/src/main/java/org/gradle/internal/resource/transport/gcp/gcs/GcsClient.java#L143 is not null checked (Google APIs returns null instead of empty lists). When fixing this in a separate fork, the dependencies refreshes a lot faster and fixes this issue. I think the list call gets a null pointer exception and then the transport layer fallbacks to getting each dependency individually, which takes more time. I am not sure why it is requesting something that does not exist however, since we have a lot of files in the bucket & path we use.

### Expected Behavior
Running a task with a GCS Maven Repository does not have a 30 sec overhead of checking dependencies.

### Current Behavior
Running a task with a GCS Maven Repository have a 30 sec overhead of checking dependencies.

### Steps to Reproduce
1. Add a GCS Maven Repository like this gcs://<bucket_name>/<sub_folder>/ .
2. Run any task.
3. If it is not slow, add `
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
` and put some dependencies on `changing: true`

### PR DESCRIPTION
**Pull request by Ranzdo**
Issue: #12221
Signed-off-by: Björn Sundahl <bjorn@int32.se>

Fixes #12221

### Context
Fixed a null pointer exception in GcsClient. More information available at #12221 .

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Review by ljacomet — APPROVED** [review]
Looks good to me!

Thanks for the patch.

Could you rebase on the latest master so I could attempt another CI run?
We had some issues in the base commit you used.

**Comment by JLLeitschuh** [comment]
@Mergifyio rebase

**Comment by JLLeitschuh** [comment]
@bot-gradle test this please

**Review by JLLeitschuh — APPROVED** [review]
Thanks for the contribution! LGTM!!

**Comment by ljacomet** [comment]
Thanks @JLLeitschuh 
I will pick that one for `release` given the low risk.

**Pull request merged**
