### PR TITLE
Update Gradle Enterprise Gradle plugin to v3.14

### PR DESCRIPTION
**Pull request by marcphilipp**

### CODE REVIEW

**Comment by marcphilipp** [comment]
@bot-gradle test

**Review by wolfs — APPROVED** [review]

**Comment by ljacomet** [comment]
Hey folks,

RC1 is being released right now. This cannot go on `release` unless we need an RC2.
And even then, can we wait until 8.4 instead?

**Review by ljacomet — CHANGES_REQUESTED** [review]
See comment above

**Comment by marcphilipp** [comment]
@bot-gradle test

**Comment by marcphilipp** [comment]
I have no idea why GitHub/Git complains about a conflict in `subprojects/docs/src/docs/release/notes.md`. I didn't even touch that file in my commit. Any ideas? 🤔

**Comment by marcphilipp** [comment]
I'll try opening another PR.

**Comment by marcphilipp** [comment]
Superseded by #25819

**Pull request closed without merging**
