### PR TITLE
Un-@Deprecate methods without stable replacements

### LINKED ISSUE #19693: Inconsistent Javadoc annotations for org.gradle.api.tasks.testing.TestReport (gradle 7.4)
The gradle 7.4 RC1 javadoc has inconsistent annotations, [getDestinationDir()](https://docs.gradle.org/7.4-rc-1/javadoc/org/gradle/api/tasks/testing/TestReport.html#getDestinationDir--) is marked **deprecated**, to be replaced with ** getDestinationDirectory()**. How can something be deprecated when the replacement is considered EXPERIMENTAL?

### Expected Behavior

Not applicable: code documentation only

### Current Behavior

Not applicable: code documentation only

### Context

We are using the "Deprecated" method calls. But in order to fix them, I have to use new APIs ... that are also creating a warning because "incubating"?!

### Steps to Reproduce 

Skipped, problem is obvious from the Javadoc alone.

### Your Environment

Not applicable: code documentation only

### PR DESCRIPTION
**Pull request by tresat**
Fixes #19693 #19645

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test QFL

**Review by ljacomet — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
I believe so - these methods should be `@Deprecated` again in 7.6.  @DPUkyle - This is intended, correct?

**Comment by Vampire** [comment]
Well, at least currently you still get a complaint about deprecation of those methods, just not at compile time anymore but at runtime and without the JavaDoc to help transition, that's why I wondered that only the JavaDoc was removed but not the nagging. :-)

**Pull request merged**
