### PR TITLE
Fix ordering for welcome and logging.stacktrace props

### LINKED ISSUE #22702: Typo and ordering problem for org.gradle.welcome property in docs
The `org.gradle.welcome` property is not formatted correctly in [the docs](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties) and it is not in the right position in the alphabetical ordering.  Same with `org.gradle.logging.level`.

It is currently
```
`org.gradle.welcome=(never,once)::
```
It should be
```
`org.gradle.welcome=(never,once)`::
```

I'll submit a PR to fix.

### PR DESCRIPTION
**Pull request by sourcedelica**
Fixes #22702

The formatting issue had already been fixed by Paul Merlin in bb48afba60947b907f1cc2544f04275fa0e1ddd2.

### Context
Fixes ordering of last two [Gradle properties in docs](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties).

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
#### Not applicable
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eskatos** [comment]
Hi @sourcedelica,
The DCO check is failing, could you please sign off your commits?
See https://github.com/gradle/gradle/pull/22703/checks?check_run_id=9447119770

**Comment by sourcedelica** [comment]
Fixed - sorry about that!

**Comment by eskatos** [comment]
@bot-gradle test BD

**Review by eskatos — APPROVED** [review]
Rendered result can be seen here https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/58772711:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221125162106%2B0000/docs/userguide/build_environment.html#sec:gradle_configuration_properties

**Comment by xaviarias** [comment]
@bot-gradle test and merge

**Comment by xaviarias** [comment]
@bot-gradle test and merge

**Comment by xaviarias** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
