### PR TITLE
Add functional test source set instead of replace

### PR DESCRIPTION
**Pull request by xaviarias**
### Context 

When using TestKit in tests from the default source set, `GradleRunner` is not found in the tests classpath.

This fix allows the generated Gradle Plugin project to have both functional and default test source sets working with TestKit.

Fixes 
  - #23298

### CODE REVIEW

**Comment by xaviarias** [comment]
@bot-gradle QFL

**Comment by xaviarias** [comment]
@bot-gradle test QFL

**Comment by xaviarias** [comment]
@bot-gradle test this

**Comment by xaviarias** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]

**Comment by xaviarias** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
