### PR TITLE
Move some classes out of model-core to base-asm and core-api project

### PR DESCRIPTION
**Pull request by asodja**
We move some of classes out of model-core, so we can use them in annotation processor and instrument core-api.

We move to base-asm:
- AsmClassGenerator
- AsmClassGeneratorUtils
- BytecodeFragment
- ClassGeneratorSuffixRegistry
- ClassVisitorScope
- MethodVisitorScope

We move to core-api:
- ListPropertyView
- SetPropertyView
- MapPropertyView

Also don't use MethodVisitorScope as API of generated classes.

Relates to https://github.com/gradle/gradle/issues/26544
Based on https://github.com/gradle/gradle/pull/28578

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Review by bamboo — APPROVED** [review]
LGTM!

**Comment by asodja** [comment]
@bot-gradle test QF

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Pull request merged**
