### PR TITLE
Merge release into master

### PR DESCRIPTION
**Pull request by blindpirate**

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test RfR

**Comment by ljacomet** [comment]
Closing this as it actually got merged but I mistakenly pushed before it was closed.
Following up with #22148

**Pull request closed without merging**
