### PR TITLE
Improve layout and vertical rhythm for docs

### PR DESCRIPTION
**Pull request by eriwen**
This change improves readability of documentation pages in the
following ways:
 - Reduce width of content area, making tracking a single line
   easier
 - Unifies vertical rhythm and header styles with other Gradle
   properties
 - Lots of stylistic tweaks that make the pages pleasant
 - Uses system monospace font instead of Ubuntu Mono,
   improving page speed and consistency with other Gradle sites

Issue: gradle/dotorg-docs#61

### Context
The goal here is to make cheap improvements that allow us to avoid so many overrides in the dotcom-docs project, improve speed, improve readability, and improve consistency of the styles with the Gradle Blog and gradle.org

Before and Afters:
screenshot 2017-11-15 12 41 10

screenshot 2017-11-15 12 38 11

screenshot 2017-11-15 12 37 34

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by bmuschko** [comment]
- I noticed a couple of warnings on the console when generating the docs. Is this expected?

```
Loading Xslthl configuration from file:/Users/bmuschko/dev/projects/gradle/subprojects/docs/build/stylesheets/highlighting/xslthl-config.xml...
file:/Users/bmuschko/dev/projects/gradle/subprojects/docs/build/stylesheets/common/common.xsl; Line #1211; Column #20; Warning: multiple "IDs" for constraint linkend: publishing_maven:repositories.
file:/Users/bmuschko/dev/projects/gradle/subprojects/docs/build/stylesheets/common/common.xsl; Line #1197; Column #20; Error: no ID for constraint linkend: sec:external_dependencies.
file:/Users/bmuschko/dev/projects/gradle/subprojects/docs/build/stylesheets/common/common.xsl; Line #1197; Column #20; Error: no ID for constraint linkend: sec:external_dependencies.
file:/Users/bmuschko/dev/projects/gradle/subprojects/docs/build/stylesheets/common/common.xsl; Line #1197; Column #20; Error: no ID for constraint linkend: sec:complete-overwrite.
file:/Users/bmuschko/dev/projects/gradle/subprojects/docs/build/stylesheets/common/common.xsl; Line #1197; Column #20; Error: no ID for constraint linkend: sec:complete-rewrite.
file:/Users/bmuschko/dev/projects/gradle/subprojects/docs/build/stylesheets/common/common.xsl; Line #1197; Column #20; Error: no ID for constraint linkend: library_definition.
file:/Users/bmuschko/dev/projects/gradle/subprojects/docs/build/stylesheets/common/common.xsl; Line #1197; Column #20; Error: no ID for constraint linkend: enforcing_api_boundaries.
```

- The code listings in the release notes don't seem to be rendered properly. At the moment everything is rendered in one line instead of multi-lined and indented.
- Some other sections in the release notes seem to have rendering issues e.g. "Removal of @Incubating methods".
- In the DSL guide some code has a different size than others e.g. "Build script structure" on the index page.
- The Javadocs styling didn't change at all. Was this on purpose? I'd expected a different color scheme.
- User guide: The light green color for Strings, the light brown for keywords and very light yellow for annotations in code listings might be hard to read for some users. Is there way we use a different color with a better pop?

**Comment by lptr** [comment]
I think we should use the same CSS as we do with the Gradle guides. Your recent changes bring the two closer, but there are still some differences:

- [ ] Code blocks are now rendered with Droid Sans Mono ✅ , but the size is 16px instead of 14.5px used on the guides, which looks more in line with the body text. NB: inline monospace text looks good now.
- [ ] The guides have a slightly bigger line-height that works better with the longer line lengths. I'm not sure why we'd want to render the user guide any different, both regarding line height and length.
- [ ] There's a `letter-spacing: 0.01em` in the guides that makes the text look different. Not sure if we want to keep this or not, but it should be consistent.

We could use the `asciidoctor.css` in the user guide most of this ☝️ comes from.

- [ ] I guess we can't get the admonitions to render the same until we actually switch to using Asciidoctor only, but it's a difference. Notes and warnings stand out a lot more in guides than in the user guide.

**Comment by lptr** [comment]
- [ ] Oh, yeah, and I'm really missing the margin below `<li>`s, again from `asciidoctor.css`:

    ```css
    ol>li p, ul>li p, ul dd, ol dd, .olist .olist, .ulist .ulist, .ulist .olist, .olist .ulist {
        margin-bottom: 0.625em;
    }
    ```

**Comment by lptr** [comment]
And while on the topic I can't stop myself to mention that I hate our use of the highlight green (#00C489) for links or any emphasis of body text. It is just unreadable against a white background.

image

I didn't think it can be made worse, but sure it can, with the gray backdrop of monospace stuff:

image

**Comment by eriwen** [comment]
> Code blocks are now rendered with Droid Sans Mono ✅ , but the size is 16px instead of 14.5px used on the guides

I'm not seeing the 14.5px you mention in the guides. Here's a quick comparison (guides left, docs right)
screenshot 2017-11-16 13 52 30

> There's a letter-spacing: 0.01em in the guides that makes the text look different.

Hmm.. I would prefer we remove that from the guides but this is subjective. 

> I guess we can't get the admonitions to render the same until we actually switch to using Asciidoctor only, but it's a difference.

We could, but I hesitate to adopt FontAwesome just for that light bulb icon. We can adjust the display a bit to have a classy way of making them stand out.

I've gone ahead and adjusted the line height and the margin under list items and the coloring of links within code blocks. Regarding the color of links in general, my primary goal is that the user knows what's a link. I would lightly prefer a different style or color, but will default to consistency for now.

In general, I know this won't be perfect, but I think it's better than we were. Agreed @lptr?

**Comment by eriwen** [comment]
@bmuschko One more review? Details below.

> I noticed a couple of warnings on the console when generating the docs. Is this expected?

No, but I also didn't make changes at all to that infrastructure. 

> The code listings in the release notes don't seem to be rendered properly. At the moment everything is rendered in one line instead of multi-lined and indented. 

This is due to improper markup and not due to styles. I'll fix it soon.

> Some other sections in the release notes seem to have rendering issues e.g. "Removal of @Incubating methods".

Again, I think this is due to improper markup but will investigate

> In the DSL guide some code has a different size than others e.g. "Build script structure" on the index page.

Fixed

> The Javadocs styling didn't change at all. Was this on purpose? I'd expected a different color scheme.

On purpose. I did not concern myself with the Javadocs at all because the readership is very low.

> User guide: The light green color for Strings, the light brown for keywords and very light yellow for annotations in code listings might be hard to read for some users. Is there way we use a different color with a better pop?

Fixed to match the guides

> User guide: Some of the fonts (e.g. in the tables) are a little bit too small for my taste but that could just be me.

Also fixed.

**Comment by eriwen** [comment]
@aweida I would love your thoughts on @lptr's feedback here https://github.com/gradle/gradle/pull/3487#issuecomment-344878894 if possible

**Comment by eriwen** [comment]
I got a verbal +1 from @lptr, so merging.

**Comment by aweida** [comment]
> And while on the topic I can't stop myself to mention that I hate our use of the highlight green (#00C489) for links or any emphasis of body text. It is just unreadable against a white background.

@eriwen @lptr this is why we've shifted to blue on the GE side of things 
Ex. https://docs.gradle.com/build-scan-plugin/

@eriwen I think we can begin to make similar changes to dotorg. Lets sync monday during planning.

**Comment by bmuschko** [comment]
@eric The code listings in the user guide look much better now. I noticed that the code listings in the release notes look different from the ones in the user guide though. I think the highlight still uses a different styling.

**Release notes:**

redesign_release_notes

**User Guide:**

redesign_user_guide

**Comment by eriwen** [comment]
Nice spot, @bmuschko! Fixed in a8322a1ed44aacbb8ceb4270d4be22257176a47e

**Pull request closed without merging**
