### PR TITLE
Fix regression with `org.gradle.parallel` property

### PR DESCRIPTION
**Pull request by lacasseio**
### Context
See issue https://github.com/gradle/gradle/issues/1827

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eriwen** [comment]
@lacasseio We can make testing better here. It seems like we ought to have an integration test for this. See https://github.com/gradle/gradle/commit/ba37d8924a6bcb502c30ca5dc45215460a0de7d5

Something you'll consider? BTW, I think the impl as-is will work.

**Comment by lacasseio** [comment]
@eriwen Done.

@adammurdoch I agree this is something is was difficult to work with.

**Comment by lacasseio** [comment]
I'm running the branch on CI and will merge after.

**Comment by pioterj** [comment]
@lacasseio Haven't we lost the test case for the regression this change was intended to fix (`-Dorg.gradle.parallel=false`) in this commit https://github.com/gradle/gradle/pull/1828/commits/f32ae1914da77772f3216704ea3cc9ad3b8194a0?

**Comment by lacasseio** [comment]
Very good point @pioterj. I added back the test cases for `org.gradle.parallel=false`.

**Comment by eriwen** [comment]
This had a concerning CI failure (https://builds.gradle.org/viewLog.html?buildId=2742993&tab=buildResultsDiv&buildTypeId=Gradle_Branches_CoveragePhase_LinuxCoverage_LinuxJava17ParallelIntegrationTest_3) so I'm going to take this over this week.

**Comment by eriwen** [comment]
Aside, I've filed https://github.com/gradle/gradle/issues/1847 to capture what @adammurdoch said

**Comment by w25r** [comment]
Looks like the CI failure is fixed by annotating the method with 
```groovy
@IgnoreIf({ GradleContextualExecuter.parallel })
```
There simply hasn't been another run since then.  I've kicked off a new run and will verify.

**Pull request merged**
