### PR TITLE
Allow user to persist --console setting in gradle.properties

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

See #2744 

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs

### CODE REVIEW

**Comment by eriwen** [comment]
@blindpirate I'm sorry I'm overburdened at the moment and won't be able to do this review this week. Since this is small, perhaps another member of the @gradle/build-tool can pick up this review?

**Comment by blindpirate** [comment]
@eriwen No problem!

**Comment by big-guy** [comment]
I'll merge this first thing in my morning.

**Comment by blindpirate** [comment]
Thanks @big-guy !

**Pull request merged**
