### PR TITLE
Update compatibility matrix for Java 20

### PR DESCRIPTION
**Pull request by ghale**

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

**Review by octylFractal — APPROVED** [review]

**Comment by ljacomet** [comment]
@ghale @octylFractal I have an alternate proposal for this update in #25775 which might work better for the future as well.

let me know what you think.

**Comment by ghale** [comment]
@bot-gradle test and merge

**Comment by ghale** [comment]
@bot-gradle cancel

**Pull request closed without merging**
