### PR TITLE
Change `ConventionReportTask` `@since` annotation from `7.0` to `6.9` in `7.0.1`

### PR DESCRIPTION
**Pull request by bamboo**
Since it has been backported to 6.9 in #16887.

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by big-guy** [comment]
@bot-gradle test QFL

**Comment by eskatos** [comment]
@bot-gradle test QFL

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
