### PR TITLE
Don't check for file existence if specified as optional

### LINKED ISSUE #2016: Expressing optional `@InputFile` and `@InputDirectory` properties
I'd like to express "this is a directory/file that is an input to my task, if it exists" with default values.  This means that if the input exists, my task will use it.  If it doesn't exist, that's OK.  If the input is the wrong type (directory instead of a file or vice versa), I'd like to get an error.  

Due to the way we validate `@InputFile` and `@InputDirectory`, it's not simple to define a property this way because we require that the file or directory exists. If a plugin doesn't define a default value, you can use `@Optional` and a null value for the property.

### Expected Behavior

I should be able to have a property with a default value that is only validated if it exists.

### Current Behavior

Property validation fails before the task executes when the directory/file does not exist.

### Context

I can work around this by using `@InputFiles` or conditionally returning null if the path does not exist.  If I use `@InputFiles`, it's inconvenient to use `File` as my property type because it makes it easy for someone to pass the wrong thing (a file vs a directory) and it looks a little odd to have `@InputFiles File someProp`.  I could also use _two_ properties.  One that's just the `File` that's ignored by up-to-date checks and another that's a `@InputFiles FileCollection`.  This still has the problem that the wrong thing could be used (file vs directory) and it's strange that I would need to use two properties.

### Steps to Reproduce (for bugs)

Here's an example task that fails:
```
class CustomTask extends DefaultTask {
    @InputDirectory
    @Optional
    File inputDir = project.file("does-not-exist")

    @OutputFile
    File outputFile = new File(temporaryDir, "output.txt")

    @TaskAction
    void generate() {
       outputFile.text = "done"
    }
}

task customTask(type: CustomTask)
```

The same would apply for `@InputFile`.

### Your Environment

This always happens.

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Fixes #2016

I couldn't find tests for `ValidationAction`s... would someone kindly point them out to me? 😄

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@wolfs Can I see why the build failed? Tests are passing on my machine...

**Comment by SUPERCILEX** [comment]
@wolfs Oh, finally figured out that I can login as a guest to check the build status. Anyway, it looks like it's failing at `compileGroovy`... not quite sure how my changes are related. Would you mind giving me a pointer?

**Comment by SUPERCILEX** [comment]
Damn, thanks for that super detailed explanation! If we were to go with #<span></span>2, the non-existent file would show up in the task inputs, right? (That's bad IMO) If that's true, then yeah, I definitely think we should just map it to null.

**Comment by SUPERCILEX** [comment]
So actually, I've thought about this some more, and I now disagree. The `RegularFile` stuff is limited in that it must take a `String path`, and it's a pain to get an instance.

Furthermore, optional makes little sense in its current state with regard to files. Why would adding optional blow up if the file doesn't exist? Granted, it does that without optional, but I would call the current state a bug. In my ideal world, adding optional would make the file simply disappear from the inputs if it doesn't exist—just like what happens when you return null. Do you agree?

I've got a prototype for this disappear thing and I would prefer adding it behind a flag that's switched on by default in 5.0 than adding backcompat hacks like a `mustExist` in the annotation. Again, this feels like a bug to me so it might even be reasonable to put this in 4.x.

@wolfs what are your thoughts?

PS: I kinda see why you didn't take this one on now 😂

**Comment by wolfs** [comment]
@SUPERCILEX Sorry for the late response. I think that the current Gradle behaviour is consistent also with respect to properties - `@Optional` means null for them. There is an easy workaround for returning `null` for a non-existant input file. It seems to be different to not specify an input file and specifying an input file which is not there.

Regarding the difficulties to get an instance of `RegularFile`: That is a separate problem and deserves an own issue. Please describe your use-case there.

I'll close this PR now since we don't want to change the meaning of `@Optional` for file inputs. If you want an easier way to specify that missing input files are OK, a simple method on `RegularFileProperty` should be enough, right? That would instruct the `RegularFileProperty` to return `null` if the file does not exist. WDYT?

**Comment by SUPERCILEX** [comment]
See https://github.com/gradle/gradle/issues/2016#issuecomment-417553041. Basically, I agree with you. 😊

**Pull request closed without merging**
