### PR TITLE
Exclude merge simplification

### PR DESCRIPTION
**Pull request by ljacomet**
Changes are based on real world use cases where keeping an allOf(group(s),module(s))
instead of making it a moduleId(Set) had pretty bad downstream consequences.

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test RfN

**Review by tresat — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle help

**Comment by ljacomet** [comment]
@bot-gradle PT

**Comment by ljacomet** [comment]
@bot-gradle test PT

**Comment by ljacomet** [comment]
@bot-gradle test PT

**Pull request merged**
