### PR TITLE
Add jsonDependencyReport task

### PR DESCRIPTION
**Pull request by kota65535**
Fixes https://github.com/gradle/gradle/issues/21894

### Context

Added `jsonDependencyReport` task to [project-report](https://docs.gradle.org/current/userguide/project_report_plugin.html) plugin to output project dependencies in JSON format.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by jvandort** [comment]
I highly doubt we will want to support functionality like this natively within Gradle. In particular, we have no way of managing a JSON schema between Gradle versions, like we do with Java types -- i.e. deprecations and a "schema" (Java interfaces). The JSON used by the HTML and generated by `JsonProjectDependencyRenderer` was never intended to be stable in any manner, and we will likely want to keep it that way. 

That's not to say we shouldn't support this sort of functionality within third-party plugins. We definitely think this should be possible -- our Java/Groovy/Kotlin API should 100% be able to support these sorts of use-cases. If you find that the existing internal JSON-generating code relies on internal APIs which make a non-internal generator impossible, then it is possible we can introduce public APIs to fill those gaps.

**Comment by jvandort** [comment]
In regards to the linked GitHub dependency graph issue -- this is being actively worked on internally. A solution to this issue is being prototyped actively.

**Review by lkasso — APPROVED** [review]

**Comment by cobexer** [comment]
Sorry for the late reply.

According to [Justin](https://github.com/gradle/gradle/pull/25592#issuecomment-1618878728) we will not add this feature so closing this PR.

**Comment by pombredanne** [comment]
Would this be the same as the build scan output?

**Comment by sschuberth** [comment]
> Would this be the same as the build scan output?

No, a build scan has way more information about executed tasks, performance, test results, etc.

**Pull request closed without merging**
