### PR TITLE
Document using dependency resolution results as task inputs

### PR DESCRIPTION
**Pull request by eskatos**
Update existing general task inputs documentation.
Add dedicated section in the chapter about authoring tasks.
Add sample covering multiple use cases.

Previews:

* Release notes
  https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/51656398:id/distributions/gradle-7.5-docs.zip!/gradle-7.5-20220429115349%2B0000/docs/release-notes.html#dependency-resolution-results-can-be-used-as-task-inputs
* Updated general task inputs user manual section
  https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/51656398:id/distributions/gradle-7.5-docs.zip!/gradle-7.5-20220429115349%2B0000/docs/userguide/more_about_tasks.html#sec:task_input_output_annotations
* Dedicated user manual section
  https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/51656398:id/distributions/gradle-7.5-docs.zip!/gradle-7.5-20220429115349%2B0000/docs/userguide/more_about_tasks.html#sec:task_input_using_dependency_resolution_results
* Dedicated sample
  https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/51656398:id/distributions/gradle-7.5-docs.zip!/gradle-7.5-20220429115349%2B0000/docs/samples/sample_tasks_with_dependency_resolution_result_inputs.html

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test QFL

**Comment by eskatos** [comment]
@bot-gradle help

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
Very comprehensive sample 👍

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle cancel

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
