### PR TITLE
Improve error message where the Android studio property can come from

### PR DESCRIPTION
**Pull request by hegyibalint**

### CODE REVIEW

**Review by cobexer — APPROVED** [review]
LGTM

**Review by oleg-nenashev — APPROVED** [review]

**Comment by hegyibalint** [comment]
@bot-gradle merge

**Comment by asodja** [comment]
🤔 Are we sure this is correct? 
We pass `studio.home` to the new Java process, but build parameter that we use is `studioHome`, see [here](https://github.com/gradle/gradle/blob/e9d7e47044e08be2a88a64cb75742a85136da0ff/build-logic-commons/basics/src/main/kotlin/gradlebuild/basics/BuildParams.kt#L130). Maybe we should just unify them to avoid confusion

**Comment by hegyibalint** [comment]
@asodja sorry for the late reply. You are right about this, I will make a new PR fixing this mistake.

**Pull request merged**
