### PR TITLE
Remove deprecated domain object collection constructors

### PR DESCRIPTION
**Pull request by donat**
### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test qF

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
Breaks AGP 4.0. We'll remove it later.

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
Successful rFM build: https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_Stage_ReadyforMerge_Trigger&branch_Gradle_Check=donat%2Fdeprecated%2Fmove-archive-task-deprecation&tab=buildTypeStatusDiv

**Review by rieske — APPROVED** [review]

**Comment by donat** [comment]
Thanks @rieske!

**Pull request merged**
