### PR TITLE
Measure work execution time in Santa Tracker performance test for FSW

### PR DESCRIPTION
**Pull request by lptr**

### CODE REVIEW

**Comment by lptr** [comment]
Results: https://builds.gradle.org/viewLog.html?buildId=38702527

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Review by wolfs — APPROVED** [review]
LGTM! Do you know which version of the Kotlin plugin we use for this build? Can we change this version as well by using a system property?

**Comment by lptr** [comment]
Let's do the Kotlin configuration separately.

**Pull request merged**
