### PR TITLE
Slightly more informative debug message when DefaultPersistentDirecto…

### PR DESCRIPTION
**Pull request by mathjeff**
…ryCache content changes

### CODE REVIEW

**Comment by alkemist** [comment]
Hi @mathjeff ,

Would you mind signing the CLA? http://gradle.org/contribute-to-gradle/#CLA

**Comment by mathjeff** [comment]
(Signed!)

**Comment by mathjeff** [comment]
Any update/feedback? The Task.isCurrentlyUpToDate part of this pull request will be particularly important to us in a few months. Is there anything I can do to help?

**Comment by bigdaz** [comment]
@mathjeff Can you please split this into 2 PRs. 
We've recently hired @pioterj who will be working to process some of the outstanding pull requests.

- The first commit is something we can merge without too much discussion.
- The second commit involves changes to the public API of Gradle, and we will almost certainly not be applying it as-is. 

To make this sort of substantive change to Gradle, we'd need to have an initial discussion on the Gradle developers list, and probably will require a formal design specification. More details on contributing to Gradle are here: http://gradle.org/contribute-to-gradle/

**Comment by mathjeff** [comment]
Thanks @bigdaz 

Opened updated pull requests at https://github.com/gradle/gradle/pull/539 and https://github.com/gradle/gradle/pull/540

I also moved the task-planning discussion to https://groups.google.com/forum/#!topic/gradle-dev/XGTjFIRr96E

**Pull request closed without merging**
