### PR TITLE
Allow HttpBuildCache to optionally follow redirects

### LINKED ISSUE #14433: HTTP Build Cache should follow redirects
I suggest to allow redirect. I posted my concerns and use case in #13759 

> I'm trying to implement a GitHub Action which will act as a proxy for GitHub's Caching API and be compatible with Gradle's Build Cache protocol. This proxy will redirect to Azure's shared access signature URL on a cache download request. I've also seen other HTTP caches that uses a similar technique of redirecting to a "pre-authorized" S3/GCP/other storage URL in order to optimize the I/O and make CI builds load directly from storage rather then going though a proxy.

### Expected Behavior

Build cache should respect redirects

### Current Behavior

Throws an exception

### PR DESCRIPTION
**Pull request by ketronkowski**
Fixes #14433

### Context
Some build-cache server implementations require support for HTTP 302 redirects. Jfrog's Artifactory is one of these build-cache implementations. This PR introduces a new option to configure the HttpBuildCache to support HTTP 302 redirects.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ldaley** [comment]
Hi @ketronkowski. Thank you for the contribution. We are currently working through how we want to incorporate this functionality. You can expect more information over the coming days.

There's a little bit more to do as, as-is, this strategy does not work for PUT/upload requests. We can take care of that after integrating your PR.

**Comment by ketronkowski** [comment]
@ldaley Wondering if there have been any updates? If there is anything more that I can do to help please let me know.

**Comment by ldaley** [comment]
@ketronkowski we are committing to this work internally, but it won't happen in time for the 7.0 release. We intend to deliver this soon after. No updates beyond that at this time I'm afraid.

**Comment by donat** [comment]
There's some extra complexity that needs to be tackled when implementing this feature. We'll probably look into this soon.

**Pull request closed without merging**
