### PR TITLE
docs: componentFilter belongs not this but it

### PR DESCRIPTION
**Pull request by KengoTODA**
### Context

In the `spotbugs-gradle-plugin` repo, I tried to bump up Gradle from 8.7 to 8.8.
And I found that the [actual required change](https://github.com/spotbugs/spotbugs-gradle-plugin/pull/1178/commits/bd76a5ec22cb2c7ca3d34fa6e71fd084e9ab29a2) is not same to the [documented one](https://docs.gradle.org/8.8/userguide/upgrading_version_8.html#deprecate_filtered_configuration_file_and_filecollection_methods).

Here I want to suggest a change to the document, to help other Gradle users.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by jvandort** [comment]
I thought I remembered testing this one.

I just tried this again in an integration test and it seems to work on my side using the original code sample.

What error do you get when you use the original sample?

**Comment by KengoTODA** [comment]
> What error do you get when you use the original sample?

```
> Task :compileKotlin FAILED
e: file:///Users/toda_k/ghq/github.com/spotbugs/spotbugs-gradle-plugin/src/main/kotlin/com/github/spotbugs/snom/internal/SpotBugsHtmlReport.kt:54:13 Unresolved reference 'componentFilter'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

You may checkout the [`renovate/gradle-8.x` branch of our repo](https://github.com/spotbugs/spotbugs-gradle-plugin/tree/renovate/gradle-8.x), and make a small change to verify.

**Comment by big-guy** [comment]
Our example works for build scripts.  Are you using the kotlin-dsl plugin to develop your plugin? This should work if you are.

**Comment by KengoTODA** [comment]
No, we do not use the kotlin-dsl plugin.  
And I got the point, I will close this issue. Thanks for your investigation! 🙌

**Pull request closed without merging**
