### PR TITLE
Fix build event listener registration with ProjectBuilder

### LINKED ISSUE #16774: Failing tests when exercising Android Gradle Plugin version 4.2.0 and Gradle 7.0
### Expected Behavior

When using the `org.gradle.testfixtures.ProjectBuilder` in a test suite, it should be able to apply an Android Gradle Plugin.

### Current Behavior

It throws

```
org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin 'com.android.internal.library'.
Caused by: org.gradle.api.plugins.PluginInstantiationException: Could not create plugin of type 'LibraryPlugin'.
Caused by: org.gradle.internal.service.ServiceCreationException: Cannot create service of type DefaultBuildEventsListenerRegistry using DefaultBuildEventsListenerRegistry constructor as required service of type BuildEventListenerFactory for parameter #1 is not available.
```

when applying e.g. a `com.android.library` plugin on the `Project`.

### Context

I'm trying to test a plugin that interacts with the Android Gradle Plugin. It could be done using a nested Gradle invocation, but they are a lot slower to execute, so the `ProjectBuilder` would be ideal.

### Steps to Reproduce 

[bug-agp-testing-servicecreationexception.zip](https://github.com/gradle/gradle/files/6290730/bug-agp-testing-servicecreationexception.zip)
1. Unzip the archive
2. Run `./gradlew :test`
3. Replace the AGP version in `build.gradle.kts` with e.g. `4.1.3` and see that the tests pass.

### Your Environment

Gradle 7.0
Android Gradle Plugin 4.2.0-rc01
Java 1.8
Build scan: https://gradle.com/s/77oyyy75uian4

### PR DESCRIPTION
**Pull request by alllex**
Plugins that register build event listeners should now be able to applied to the projects provided by `ProjectBuilder`.

In order to make execution of unit tests for project plugins efficient `ProjectBuilder` creates lightweight `Project` instances that do not provide all capabilities of the projects created during an actual Gradle build. Usually this is sufficient for testing of simple or standalone Gradle plugins. However, it can get more complicated in the case of a Gradle plugin that depends on another Gradle plugin. This plugin dependency can justifiably make an assumption that it runs against a full fledged Gradle project. Additionally, although highly discouraged, some plugins can even depend on Gradle's internal APIs.

In order to support more use-cases for third-party plugins applied to `ProjectBuilder`, Gradle API jar now includes `gradle-tooling-api-builders` module.

Fixes #16774

### CODE REVIEW

**Comment by alllex** [comment]
@bot-gradle test qfl

**Comment by alllex** [comment]
@bot-gradle test qfl

**Comment by alllex** [comment]
@bot-gradle test qfl

**Comment by alllex** [comment]
@bot-gradle test this

**Comment by alllex** [comment]
@bot-gradle test this

**Review by eskatos — CHANGES_REQUESTED** [review]
:100: 

Confirmed that the change adds a single module to the Gradle API jar.

I suspect that using TestKit with `withDebug(true)` was impacted in the same way.
TestKit uses the Tooling API to fork Gradle daemons in order to run integration tests but with withDebug(true) it switches to running the build with an embedded Gradle running from the generated API jar.

Please add a similar test but using TestKit in debug mode.

**Comment by alllex** [comment]
After further investigation the TestKit with `withDebug(true)` does not seem to be impacted by the same issue. However, given that this is still a valid use case for testing a Gradle plugin, an additional test was added.

**Comment by alllex** [comment]
@bot-gradle test test

**Comment by alllex** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]

**Comment by alllex** [comment]
@bot-gradle test and merge

**Pull request merged**
