### PR TITLE
Default test suite behavior is no longer to use JUnit 4

### PR DESCRIPTION
**Pull request by tresat**
This is a duplicate of https://github.com/gradle/gradle/pull/19471, from a new branch built off of the release branch.

---
Issues Addressed:

This is incorrectly noted here: https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#sec:jvm_test_suite_tasks

This adds a new integration test to demonstrates this behavior.  This is intentional, see: https://github.com/gradle/gradle/blob/74fb3be30d536b3ee83c97a8d3be0d13c7ad8c54/subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java#L125

This PR also adjust docs to note this.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
