### PR TITLE
[s3-maven-publish] Publishing to an AWS s3 maven repo

### PR DESCRIPTION
**Pull request by adrianbk**
- Fixed issue with maven deployer not generating the correct checksums
- Changes deploy wagon and delegate to work with any internal repository transport
- Port publishing to jets3t
- Uses a file backed S3 stub server to test snapshot publications
- Prevents default repository transport from generating a checksum (somefile.txt..sha1.sha1)
- DelegatingDeployWagon creates destination files when something in the bowels of the maven libraries fails to create files for snapshots
- Adds coverage for WagonRegistry and allows wagon/scheme overrides
- Changes log level to debug for non-existing maven supplied files

### CODE REVIEW

**Comment by adrianbk** [comment]
@breskeby - can you take a look at this? 

Including @adammurdoch as some of this is related to a [discussion on the gradle-dev forum] (https://groups.google.com/forum/#!topic/gradle-dev/3mkUh_F8FFo) around publishing to maven with the existing Gradle repository transports. 

Basically RepositoryTransportDeployDelegate can work with any of the internally supported transports, with one caveat - the sha1 checksum is uploaded twice because of [org.gradle.internal.resource.transport.DefaultExternalResourceRepository](https://github.com/gradle/gradle/blob/564a305dce97279c937b6dd30ac312155b633ff5/subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transport/DefaultExternalResourceRepository.java#L61)

Some questions on this:

- can we move `DefaultExternalResourceRepository#putChecksum` so that sha1 checksums are not uploaded twice.

- can we live with the exception handling in MavenRemoteRepositoryFactory

**Comment by bigdaz** [comment]
Thanks @adrianbk . We'll take a look in the near future.

Without looking deeply, I have a couple of questions/comments:
- I'm not sure what benefit we gain from splitting the 'deploy delegate' from the wagon implementation. It seems like the abstraction for Gradle is in the RepositoryTransport layer, and making it possible to have multiple wagon implementations seems superfluous. Am I missing something?
- Assuming that we know a RepositoryTransport is under the hood, can we just remove the generation of checksums from our Wagon implementation? You've got a comment about the wrong checksum being generated, which I don't quite understand.
- Yes, I think removing the Maven Ant task from the equation would simplify this a lot. I had thought we could only do this for the `maven-publish` plugin, but looking deeper I think we could make this work for the `maven` plugin as well. Although it's a bit hacky, in the past I've done this sort of thing by copying all of the code and then refactoring to remove the cruft we don't need. It's amazing how little ends up being required!!!

Thanks again.

**Comment by adrianbk** [comment]
@bigdaz 

###### 1
- The idea behind splitting the delegate from the wagon implementation was to potentially make it easy to create new plugins which could provide an implementation of AbstractDeployDelegate to take care of the transport without requiring a (for now internal) RepositoryTransport or dealing with any of the maven wagon specific stuff DelegatingDeployWagon takes care of (throwing the right exceptions and firing org.apache.maven.wagon.events.TransferEvents). 

Lets say I wan't to create a new plugin to talk to some new storage service:
  - Define the repo

```groovy
publishing {
    ...
    repositories {
        maven {
            url "fictionalstorage://xyz.com/storage/maven/snapshot"
        }
    }
}
```
  - Provide an implementation of  `AbstractDeployDelegate`, `FictionalStorageDeployDelegate`which interacts with fictionalstorage (putFile, getAndWriteFile, etc)

  - Register the wagon:

```java
 add(new WagonContext<DelegatingDeployWagon, FictionalStorageDeployDelegate>("fictionalstorage", DelegatingDeployWagon.class, fictStorageDeployDelegateFactory()));
```

###### 2
The comment around incorrect checksums is in the method `org.gradle.api.publication.maven.internal.DelegatingDeployWagon#signalMavenToGenerateChecksums` This method needs to fire an event, to the maven deployer, containing all of the bytes of the file which has just been uploaded. Without this event and all of the byes, the maven deployer creates invalid md5 and sha1 checksums which end up getting uploaded to the remote repository (or refused by the remote repo). Because of how the maven wagon deployment works internally, the maven deployer needs to be responsible for generating these checksums. To answer your question: the maven wagon needs to be the one generating the checksums which is why I was wondering if we could move DefaultExternalResourceRepository#putChecksum.

###### 3
Agreed getting rid of Maven Ant tasks would be the way to go, was thinking if we got all of the s3 and other RepositoryTransort publishing working with DelegatingDeployWagon we could then look at stripping it out.

**Comment by bigdaz** [comment]
###### 1 
We absolutely *do not want* to introduce a back-door to allow specification of a new protocol. This has numerous issues, including:
1. It will only work for publishing, not resolution
2. It will only work for Maven, not Ivy publishing
3. It ties us into using Maven Wagon for publishing

The only reason for creating a RepositoryTransport-backed Wagon was to allow us to continue to publish via the Maven Ant tasks: we're effectively going from Gradle -> Maven -> Gradle code. Ideally, we'll remove the Maven bit, and this won't be necessary at all.

We currently support the use of custom Wagon implementations for publishing, but we'd like to deprecate this once we have sufficient repository transport infrastructure. So I think the right way is to continue on the path of making it easier to supply a new RepositoryTransport implementation.

###### 2
I'll need to look deeper, but I'm still not convinced that this can't be resolved in our RepositoryTransport-backed wagon implementation. If the RepositoryTransport creates the correct checksums automatically, then our RepositoryTransport-backed Wagon implementation shouldn't need to do the work. You say that the 'maven deployer' creates invalid checksums, but I'm not sure who the 'maven deployer' is in this case. Need to investigate further.

###### 3
I've already started playing with this: it's a bit of a can of worms. By using the Maven-Ant tasks, we implicitly support all sorts of Maven stuff like profiles and dependencyManagement and who-knows-what-else. A lot of this we would prefer to either a) support explicitly or b) not support. I need to see where this takes me, but it's not pretty :).

**Comment by adrianbk** [comment]
##### 1
If RepositoryTransports are the way forward for external plugins to add transports then yes, we don't need to split the deploy delegate from the Wagon deployer. I guess I was coming at it from an outside-in view, say for example, I want to create a new plugin, building on the maven-publish plugin, to publish (only) to a maven repo using some non Gradle supported transport.
-   I provide an implementation of `AbstractDeployDelegate` which has no dependencies on maven or maven-ant-tasks. Let's imaging github: `GithubDeployDelegate`. This is where I use some library for uploading/downloading files.
- Somehow tell the maven-publish plugin to use GithubDeployDelegate when deploying to the protocol/scheme "github" e.g:
```groovy
plugin.registerDeployer("github", GithubDeployDelegate)
```
Since AbstractDeployDelegate is just a template with simple abstract methods: remoteResourceExist, putFile, etc. it wouldn't matter if maven-ant-tasks was removed 
Anyway, this is probably no benefit if the end game is to make it easy to to implement RepositoryTransports.

##### 2
When I say 'maven deployer' I mean the following classes which actually orchestrate the deployment workflow. 
`org.apache.maven.artifact.deployer.DefaultArtifactDeployer`, 
`org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager`, etc.
Part of this workflow is to generate .sha1 and .md5 checksums which ultimately get uploaded to the remote repo by a callback to `org.gradle.api.publication.maven.internal.DelegatingDeployWagon#put`.  

As the code stands the correct checksums are generated and uploaded because of (org.gradle.api.publication.maven.internal.DelegatingDeployWagon#signalMavenToGenerateChecksums) the problem is that a second .sha1 is being uploaded because of  DefaultExternalResourceRepository#putChecksum. The question really is - who is responsible for generating and uploading the (.sha1 and .md5) checksums - I tend to think that whatever is orchestrating the deploy should to it  (maven-ant-tasks in this case) and not the RepositoryTransport, does it make sense that everything that puts/uploads a file with a RepositortyTransport  also gets an accompanying .sha1 uploaded to the remote destination? Thats why I'm asking can we remove org.gradle.api.publication.maven.internal.DelegatingDeployWagon#signalMavenToGenerateChecksums.

##### 3 
Definitely not pretty and it could end up being quite involved to replicate everything it's doing. At least getting the transport/credentials  stuff out of there will be a nice first step.

**Comment by bigdaz** [comment]
##### 1
As I mentioned, we definitely don't want to add a "back-door" way for adding a new protocol. It either needs to be officially supported, or not there at all. The last thing we want is for people to start using this, and then we end up having to support it, even though there's no documentation, test coverage, and it doesn't work for Ivy, Maven resolution etc. We've been in this situation before (with Ivy) and we're _very_ careful not to go there again.

##### 2
Thanks for your explanation. In trying to remove the Maven Ant tasks, I discovered how deeply integrated with the Maven libraries we are. While the Ant tasks themselves don't add a lot of value, the `ArtifactDeployer` does a lot of stuff like generating `maven-metadata.xml` and the checksum files: stuff we that won't be trivial to replicate, even if we decided we wanted to.

You're absolutely correct when you say:
> who is responsible for generating and uploading the (.sha1 and .md5) checksums - I tend to think that whatever is orchestrating the deploy should to it.

But I think this can be pretty easily solved: when we talk about `RepositoryTransport`, we're assuming that the current API is what a plugin would implement. This probably isn't the case: I think something more like your `S3ResourceConnector` is what we're looking at. Gradle would then instantiate a `RepositoryTransport` backed by a `ResourceConnector`. If our wagon implementation was backed by the same `ResourceConnector` API, then this issue with checksum files will go away...

Unfortunately, we don't yet have this abstraction. So I reckon let's start with your 'checksum hack' in `DefaultExternalResourceRepository`, and remove it later when we convert the wagon to be backed by `ResourceConnector` instead. How does that sound?

**Comment by adrianbk** [comment]
Thanks @bigdaz, I'll consolidate the deploy delegate and wagon, workaround the checksum issue for now and add some more solid test coverage around all of this.

**Comment by bigdaz** [comment]
That would be awesome. Over the weekend I removed the use of Maven Ant tasks (mostly) from our publishing. We are now wired directly onto the Maven `ArtifactDeployer` and `ArtifactResolver`.

This required some integration work on your PR. I tried merging, but ran out of time. If you could rebase your PR off the latest code in master, that would really help the process. (Not sure if it's easier to just open a new PR?)

**Comment by erdi** [comment]
From my experience, rebasing the branch that contains the PR and force pushing will update the PR in github.

**Comment by hansd** [comment]
@bigdaz

**Comment by adrianbk** [comment]
@bigdaz @erdi a rebase and forced push will do it (and retain the comments). Will take this on soon.

**Comment by adrianbk** [comment]
@bigdaz @breskeby 
- rebased with master
- added some more coverage
- Resolved the incorrect/duplicate checksum issues

I tried out adding http to the `WagonRegistry` and all of the publishing http based maven publishing integration tests passed with the exception of the negative cases but only because the error messages coming from RepositoryTransport differ from those produced by the `StreamingWagon` - so initial signs for replacing all of the transports look good.

Is the plan to support publishing via the older maven publishing plugin or will it be deprecated?

**Comment by bigdaz** [comment]
Thanks!
We'll eventually deprecate the old maven publishing, but I think it will be around for long enough that we should support both publishing mechanisms. Shouldn't be too hard: they share the same infrastructure under the covers. But we can certainly add this support as a subsequent step.

We'll take a closer look sometime soon.

**Comment by breskeby** [comment]
Hey,
thanks for this stuff. I noticed that you just added another s3 related server fixture (S3FileBackedServer). I think we should inline this logic into the S3StubServer. Take a look at MavenPublishHttpIntegTest how we test the expected put statements and how we validate them. S3StubServer should be able to verify resolve and publication logic as HttpServer does.

**Comment by adrianbk** [comment]
@breskeby will do!
S3FileBackedServerTest is probably not needed, test for a test.

**Comment by adrianbk** [comment]
@breskeby @bigdaz updated...

I've added some fixtures under `org.gradle.test.fixtures.maven.publication` which I think make it easier to verify publications, especially snapshots.

**Comment by bigdaz** [comment]
Thanks again @adrianbk. I'm hoping to have some time to work on it this week.

**Comment by bigdaz** [comment]
I took a look at the new test fixtures. My concern is introducing a new parallel set of fixtures for the new tests, without retrofitting the existing tests to use them. I think a better approach would be to refactor the existing fixtures like `MavenModule` and `MavenHttpArtifact` with the additional functionality you need. Consistency is pretty important in a codebase the size of Gradle.

In order to merge this, I'm going to need to re-write the integration tests in terms of the existing fixtures. That's not a blocker at this stage, but it means it will take a bit more time.

**Comment by adrianbk** [comment]
@bigdaz What threw me off with the existing fixtures was that MavenHttpModule/MavenModule exposes a publish() method which felt a bit risky in terms of verifying publications.

Regarding the fixtures, I've got limited bandwidth this weekend but I should have time early next week and I can refactor them it that helps. If you make any changes in the meantime do let me know so as we're not doubling up efforts. I'll give you commit access to this repo if that makes it easier to keep in sync.

**Comment by bigdaz** [comment]
Thanks, that would be cool. I'm on vacation for the next 2 weeks, so if I don't make any changes this weekend, you can assume that I won't be touching it until I get back.

**Comment by bigdaz** [comment]
Hi Adrian. Thanks for all your work on this. I've merged the main functionality into master, together with some parts of the integration test coverage. I've also extended the integration test coverage to include publishing to ivy repositories via `ivy-publish` as well as via the `Upload` task. (The only piece missing now is support for `Upload` to a Maven repository).

I didn't merge in most of your extensions to the integration test fixtures, as discussed above. I'm going to close this PR, and we can work on improving the tests in another PR.

Thanks again: this stuff is a great addition to Gradle.

**Comment by adrianbk** [comment]
:+1: 

Cool, we can figure out how to make the tests consistent.

**Pull request closed without merging**
