### PR TITLE
Use decorating instantiator for polymorphic domain object collections

### PR DESCRIPTION
**Pull request by big-guy**
This makes polymorphic containers behave the same way as named domain object containers when using registerBinding.

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by DPUkyle — APPROVED** [review]
LGTM. Thanks for adding the failing test first via 327f679c0536453af0e953511e6e7f6397a4f76d

**Review by tresat — APPROVED** [review]

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
