### PR TITLE
Fix eclipse plugin bug which remove javabuilder from .project

### PR DESCRIPTION
**Pull request by kui**
The current eclipse plugin replace javabuilder with scalabuilder if scala-plugin is enabled.

This patch fix eclipse plugin not to replace but to add scalabuilder.

Simple examples for reproduce
------------------------------

Without scala plugin:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bash
$ cat build.gradle
// apply plugin: "scala"
apply plugin: "java"
apply plugin: "eclipse"
$ ../gradle-latest/bin/gradle-source-build cleanEclipse eclipse
$ grep javabuilder .project
                        <name>org.eclipse.jdt.core.javabuilder</name>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

With scala plugin (current version):

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bash
$ cat build.gradle
apply plugin: "scala"
apply plugin: "java"
apply plugin: "eclipse"
$ ../gradle-latest/bin/gradle-source-build cleanEclipse eclipse
$ grep javabuilder .project
$ echo $?
1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

With scala plugin (patched version):

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bash
$ cat build.gradle
apply plugin: "scala"
apply plugin: "java"
apply plugin: "eclipse"
$ ../gradle-latest/bin/gradle-source-build cleanEclipse eclipse
$ grep javabuilder .project
                        <name>org.eclipse.jdt.core.javabuilder</name>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### CODE REVIEW

**Comment by bigdaz** [comment]
Thanks for the pull request. In order to merge this change, we would need some test coverage to verify it's effect. Is that something you'd be interested in helping out with?

Here is some existing test coverage that could be extended:
https://github.com/gradle/gradle/blob/master/subprojects/ide/src/test/groovy/org/gradle/plugins/ide/eclipse/EclipsePluginTest.groovy#L43
https://github.com/gradle/gradle/blob/master/subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseIntegrationTest.groovy#L60-L62

**Comment by kui** [comment]
I think these tests don't have any appropriate test cases which for this pull request. So, I added some test cases.

**Comment by kemuri-9** [comment]
Question:
When I was on a client project about 3 years ago which had a combination of traditional Java, Scala, and Groovy, I manually did something like this on the project then to try and get things working better in eclipse.
I believe at the time, Eclipse was the Indigo version.
However, at that time, I found that the Java and Scala builders did not "get along" at that time, almost always causing mass compilation failures which seemed to be a by product of one builder clobbering the other's output, with usually the javabuilder "winning"
Has the behavior in the builders changed to where they "get along" better now?
In this particular case of the client I was working with, Scala was eventually dropped to where the problem resolved itself in that fashion.

**Comment by kui** [comment]
@kemuri-9 
ummm... I tried Scala-IDE with this patch:

* Did not clobber other builder
* __Occur scala code syntax error__

I did not notice this problem until your question, because I write Scala code with Emacs and did not use Scala-IDE.

So, I want to drop this pull request.

I think the eclipse plugin problem is using Scala-IDE components even if it is not installed. Java code don't be built on a eclipse project which be created by current gradle and does not install Scala-IDE.

**Pull request closed without merging**
