### PR TITLE
Backport JDK16 support using toolchains to 6.9

### PR DESCRIPTION
**Pull request by rieske**
Backports https://github.com/gradle/gradle/pull/16066

Fixes https://github.com/gradle/gradle/issues/16126

### CODE REVIEW

**Comment by rieske** [comment]
The failed checks are from the wrong pipeline - I initially mistakenly kicked off the `master` pipeline and not `release6x` pipeline.

The `release6x` RFM is green: https://builds.gradle.org/viewLog.html?buildId=42704147&

**Review by donat — APPROVED** [review]
This has already been reviewed. I think it's good to go.

**Comment by rieske** [comment]
@bot-gradle test and merge

**Comment by rieske** [comment]
@bot-gradle test and merge

**Pull request merged**
