### PR TITLE
Remove IncrementalTaskInputs again

### PR DESCRIPTION
**Pull request by asodja**

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test APT

**Review by blindpirate — APPROVED** [review]
LGTM!

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
There is a flaky test failing so I marked it as flaky and started a new one: 

https://github.com/gradle/gradle/commit/efdd62d4cb50bf671a233054abd82de79fe4e0c5

https://builds.gradle.org/viewLog.html?buildId=55485146&tab=buildResultsDiv&buildTypeId=Gradle_Master_Check_ConfigCache_20_bucket2

**Pull request merged**
