### PR TITLE
Improve locality of pending element realization logic

### PR DESCRIPTION
**Pull request by jvandort**
Currently, for any existing `ElementSource` implementation to function properly with pending elements, an `onRealize` callback is required which subsequently calls `ElementSource#addRealized`. This callback which is then assumed to immediately call a method on the `ElementSource` which executed the callback is confusing. 

This PR removes the cycle, and thus eliminates the requirement of the user of an `ElementSource` to provide this "loop". This change greatly increases the locality of the logic required for handling pending elements, thus improving the readability of the code and making it easier to make further changes in this area. 

Overall, this change gives the `ElementSource` much more control over how pending elements are realized.

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by ghale — APPROVED** [review]
This looks good.  I left a few suggestions on things that might be better, but your call whether you want to do follow them or not.

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
