### PR TITLE
Update dark mode

### PR DESCRIPTION
**Pull request by lkasso**
### Details:
This is a Documentation change ONLY.

### Context: 
Fixes https://github.com/gradle/gradle/issues/27763, fixes the toc menu issue found by @ljacomet, and removes the automated dark mode from docs (manual only - too many issues due to different browsers and OSs).

### Reviewers: 
[BUILD LINK](https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/77156056:id/distributions/gradle-8.6-docs.zip!/gradle-8.6-20240124050629%2B0000/docs/userguide/userguide.html)

### CODE REVIEW

**Comment by lkasso** [comment]
@bot-gradle test BD

**Review by oleg-nenashev — COMMENTED** [review]
Would it make sense to just disable it instead of fully removing the configurations? I suppose we are still interested in having this feature, the problem is the manual CSS that glitches on browsers & Co. I do not know the docs engine well, but maybe it makes sense to add support for SCSS and use am existing dark mode library

**Comment by lkasso** [comment]
> Would it make sense to just disable it instead of fully removing the configurations? I suppose we are still interested in having this feature, the problem is the manual CSS that glitches on browsers & Co. I do not know the docs engine well, but maybe it makes sense to add support for SCSS and use am existing dark mode library

A number of reviewers had trouble with the auto mode and it did not work. I will look into a more thorough css/ui review for the docs in another PR.

**Review by oleg-nenashev — APPROVED** [review]
Agreed

**Comment by lkasso** [comment]
@bot-gradle merge

**Pull request merged**
