### PR TITLE
Made it so install tasks perform based on install target os instead o…

### PR DESCRIPTION
**Pull request by ryanniehaus**
Related to developer list post:
https://groups.google.com/forum/#!topic/gradle-dev/9qbMYiPTv7k

I have made the necessary code changes.  However, I don't know what tests would need to change (if any), or how they would need to change.  Please be gentle... this is my first open source project contribution. :)

### CODE REVIEW

**Comment by ryanniehaus** [comment]
Yay!  last commit fixed all test failures.

**Comment by ryanniehaus** [comment]
Please merge

**Comment by mark-vieira** [comment]
@ryanniehaus, do you mind rebasing your changes on 'master' and resolving any conflicts?

**Comment by ryanniehaus** [comment]
@mark-vieira I can do that when I get some spare time.  (Probably this weekend)

**Comment by mark-vieira** [comment]
I'm not sure if it was due to a merge but a bunch of unrelated commits are showing up as associated with this PR. If you don't mind, could you close this PR and open another one?

**Comment by ryanniehaus** [comment]
Yeah.  I was confused by that too.  I can do that.

**Comment by oehme** [comment]
Thank you for the pull request. I have cherry-picked your changes and added a test case.

**Pull request closed without merging**
