### PR TITLE
Move Asciidoc extensions into the project

### PR DESCRIPTION
**Pull request by alllex**
Moved from https://github.com/gradle/dotorg-docs/

This change makes it easier to author improvements to documentation and snippet generation/styling directly inside the Build Tool project.

### CODE REVIEW

**Comment by alllex** [comment]
@bot-gradle test this

**Review by hythloda — APPROVED** [review]
Docs still build

**Comment by jvandort** [comment]
I was under the impression that GE is also using asciidoctor for their build. Do they not use these extensions?

**Comment by hythloda** [comment]
> I was under the impression that GE is also using asciidoc for their docs. Do they not use these extensions?

We should ask @britter just in case?

**Comment by britter** [comment]
We're not using this as far as I can tell.

**Review by big-guy — APPROVED** [review]

**Comment by alllex** [comment]
@bot-gradle test and merge

**Pull request merged**
