### PR TITLE
Updates to JVM documentation

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

**Comment by jjohannes** [comment]
⚠️ @ljacomet I changed the base to `release` but now there is an additional commit in this PR. It was probably rebased to master "too late". Please check before merging.

**Comment by ljacomet** [comment]
I have pushed more updates to this PR, including changes to the table of contents for the part "Authoring Java Builds".
@eskatos Let me know if that matches what we discussed

**Comment by ljacomet** [comment]
@jjohannes I have removed the Java Library Distribution plugin from the TOC. I had doubts when adding it, so your opinion for sure makes me tip in favor of not having it.

About splitting the build java projects, I am not so sure. After all it is a self-contained document.

**Comment by eskatos** [comment]
@ljacomet it does, awesome!

**Pull request merged**
