### PR TITLE
Support for signing with PGP/GPG subkey

### PR DESCRIPTION
**Pull request by szpak**
In some cases it is feasible to use the subkey to perform signing operation.
This change extends the range of key taken into account to all secret keys
available in a keyring (including subkeys), not only the primary ones.

Sorry for non related formatting changes, but Idea doesn't like whitespaces in empty lines and reformat code automatically on focus leave (I can restore it manually out-of-Idea if this is a preferred formatting).

### Implementation details

Previously used `keyRings.keyRings*.secretKey` from Bouncy Castle returns only primary secret keys from the keyring. `keyRings.keyRings*.secretKeys` on the other hand returns a collection (an iterator in fact) of collections with all secret keys, including subkeys.

### CODE REVIEW

**Comment by eskatos** [comment]
Hi Marcin,

Yes, some people may prefer to use specific subkeys for signing operations. This is something we don't support. Being able to revoke subkeys without revoking the associated master keypair is a very strong argument for using dedicated subkeys. Thanks to your PR this will come soon to Gradle users.

Your change make key selection by ID look through all available keys, including subkeys. Before your change, only master keys were looped over. This sounds good to me. Plus you covered the change with proper integration tests. The whitespace changes are ok, they actually fix bad whitespaces.

It also may be good to double check the user guide and eventually change some words there. See https://docs.gradle.org/nightly/userguide/signing_plugin.html and the corresponding `subprojects/docs/src/docs/userguide/signingPlugin.xml`. Would you mind taking a look at this?

/Paul

**Comment by szpak** [comment]
Sure. Is it recommended to make also a reference to external source (like https://wiki.debian.org/Subkeys)?

**Comment by eskatos** [comment]
Yes, you can reference external resources. Especially if they are meant to stay and this one should be.

**Comment by eskatos** [comment]
I just realized this may help you preview your changes:
```
./gradlew docs:userguideHtml
open subprojects/docs/build/docs/userguide/signing_plugin.html
```

**Comment by szpak** [comment]
Thanks. I plan write a proposal during the weekend.

**Comment by szpak** [comment]
I updated the documentation. Feel free to correct/modify it at will.

Btw, I replaced PGP with OpenPGP which in fact is a non-proprietary protocol used by GPG (and others). I was thinking about changing http://www.pgpi.org/ to something more up to date, but I was not able to find anything more current.

**Comment by szpak** [comment]
In the end I changed it to Wikipedia page which contains also external links to some projects and products.

**Comment by eskatos** [comment]
@szpak: all the Gradle signing plugin will soon be able to use subkeys and keep their master keys safe thanks to you. A real concern when it comes to environments like CI.
Again, thanks a lot for your contribution Marcin.

**Comment by Vampire** [comment]
@szpak just if you care, that "Idea doesn't like whitespaces in empty lines and reformat code automatically on focus leave" are both configurable options. In `Editor -> General` you have `Strip trailing spaces on Save` which you can set to `All`, `Modified Line` or `None`. And in `Appearance & Behavior -> System Settings` you have the settings `Save files on frame deactivation` and `Save files automatically if application is idle for xx sec.`.

**Pull request merged**
