### PR TITLE
Speed up attribute matching

### PR DESCRIPTION
**Pull request by oehme**
2nd attempt for #4044. There were performance test failures after I merged it, though I'm not 100% sure they were caused by it or by some other changes that were merged to master since. I'm going to run some more experiments.

### CODE REVIEW

**Comment by jjohannes** [comment]
As far as I can see you did not make any additional changes (yet).
I am also surprised that this had a negative performance impact. Let me know if you want me to have another look at anything specific.

**Comment by oehme** [comment]
The performance tests are still failing on master, so this was not because of my changes. The most likely candidate is now @melix change, which came just before mine: https://github.com/gradle/gradle/compare/f2e3604...2186fd7

**Comment by melix** [comment]
I think it's the result of multiple different things. My commits add a bit of expected overhead, not not that much. It has been measured before merging, including passing performance tests.

**Comment by oehme** [comment]
Can you please check if reverting the change takes us back to previous performance? If yes and the overhead can't be avoided, then let's rebaseline. If not, at least we know to look somewhere else.

**Comment by oehme** [comment]
Merging again since this was not the cause of the failures.

**Pull request merged**
