### PR TITLE
Fix artifact transforms performance tests

### PR DESCRIPTION
**Pull request by asodja**
So comparison with old versions is better

Fixes https://github.com/gradle/gradle-private/issues/4175

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this APT

**Comment by 6hundreds** [comment]
@asodja `ClearArtifactTransformCacheWithoutInstrumentedJarsMutatorTest` coverage is not catching this issue?

**Comment by asodja** [comment]
> @asodja `ClearArtifactTransformCacheWithoutInstrumentedJarsMutatorTest` coverage is not catching this issue?

@6hundreds Good point, I will add it

**Review by 6hundreds — APPROVED** [review]
LGTM!

**Pull request merged**
