### PR TITLE
Fix map property validation with the configuration cache enabled

### PR DESCRIPTION
**Pull request by eskatos**
By reusing the existing validation logic.

This is a follow up to https://github.com/gradle/gradle/pull/18415

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by bamboo — APPROVED** [review]
💯

**Comment by eskatos** [comment]
Thanks @bamboo!

@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
