### PR TITLE
Add extraArgs setting to FindBugs task and extension

### PR DESCRIPTION
**Pull request by sebersole**
Per discussion on the gradle-dev list...

### CODE REVIEW

**Comment by alkemist** [comment]
@sebersole do we have a CLA from you? (http://gradle.org/contribute/)

**Comment by sebersole** [comment]
I have done one a few times before.  Do you (still) have it?  Dunno.

**Comment by alkemist** [comment]
If you've submitted one, it we pre June 2013 when the process changed. Would you mind submitting?

**Comment by sebersole** [comment]
Do you have a corporate agreement with Red Hat?

**Comment by sebersole** [comment]
Just completed it

**Comment by alkemist** [comment]
Thanks @sebersole 

We are preparing for a pull request burst next week.

**Comment by big-guy** [comment]
Hi Steve, I added some extra tests to this and merged it into master.  It'll be included in 2.6 since 2.5 should be a RC very soon.

**Pull request merged**
