### PR TITLE
Adjust snippets for configuration cache

### LINKED ISSUE #21807: CCH22-10: Adjust the `snippets/dependencyManagement/customizingResolution-metadataRule` sample for configuration cache
The sample project located under [`subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-dependency-management-customizing-resolution-metadata-rule_groovy_comonentMetadataRules.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-metadata-rule_groovy_comonentMetadataRules.sample)
    ```
    Could not get unknown property 'configurations' for task ':compileClasspathArtifacts' of type org.gradle.api.DefaultTask.
    ```

* `snippet-dependency-management-customizing-resolution-metadata-rule_kotlin_comonentMetadataRules.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-metadata-rule_kotlin_comonentMetadataRules.sample)
    ```
    Task `:compileClasspathArtifacts` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-dependency-management-customizing-resolution-metadata-rule_groovy_comonentMetadataRules.sample" \
    --tests "*snippet-dependency-management-customizing-resolution-metadata-rule_kotlin_comonentMetadataRules.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/component_metadata_rules.adoc`;

### PR DESCRIPTION
**Pull request by prasad-333**
Adjust the snippets/dependencyManagement/customizingResolution-metadataRule sample for configuration cache.

Fixes #21807 

Signed-off-by: prasad-333 <37048768+prasad-333@users.noreply.github.com>

### CODE REVIEW

**Comment by abstratt** [comment]
Looks good!

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
> [Pre-tested commit build](https://builds.gradle.org/viewLog.html?buildId=56204763) failed.

Is this a proper failure?

**Comment by prasad-333** [comment]
> > [Pre-tested commit build](https://builds.gradle.org/viewLog.html?buildId=56204763) failed.
> 
> Is this a proper failure?

@abstratt To me looks build failing for another task "Execution failed for task ':runtimeClasspathArtifacts'.
> Could not get unknown property 'configurations' for task ':runtimeClasspathArtifacts' of type org.gradle.api.DefaultTask." 
This seems not part of the issue assigned.  https://github.com/gradle/gradle/issues/21807 was failing for `:compileClasspathArtifacts` task this build failure is related to ':runtimeClasspathArtifacts' .

It seems, change required in ':runtimeClasspathArtifacts'  task as well. Ideally separate PR will be good to segregate this new issue. Kindly let me know if this changes needs to be put in this same PR?

Thanks

**Comment by abstratt** [comment]
@prasad-333 Thanks for investigating it. Please include a fix for that problem as part of this PR as well, as proposed here:

https://github.com/gradle/gradle/pull/22038#issuecomment-1250969155

**Review by abstratt — CHANGES_REQUESTED** [review]
Another task needs fixing as well

**Comment by prasad-333** [comment]
> @prasad-333 Thanks for investigating it. Please include a fix for that problem as part of this PR as well, as proposed here:
> 
> [#22038 (comment)](https://github.com/gradle/gradle/pull/22038#issuecomment-1250969155)

hey @abstratt , 
1] I see in build.gradle also has 3rd task "failRuntimeClasspathResolve" which might also need change but as you pointed out its not part of test cases so I am assuming to ignore the same unless you want my attention in that. 

2] I have pushed changes for another task- **runtimeClasspathArtifacts** fix as part of this PR itself but surprised to see now generated report _does not report any issues_ but local docTests fails with following issues 

- [ A] 

> `* What went wrong:
> Configuration cache state could not be cached: field 'actions' from type 'org.gradle.api.DefaultTask': error writing value of type 'java.util.ArrayList'
>  Configuration cache state could not be cached: field 'closure' from type 'org.gradle.api.internal.AbstractTask$ClosureTaskAction': error writing value of type 'build_au7buqcake4gcs6x1mr374cah$_run_closure15$_closure35'
>    > Configuration cache state could not be cached: field 'runtimeClasspath' from type 'build_au7buqcake4gcs6x1mr374cah$_run_closure15$_closure35': error writing value of type 'groovy.lang.Reference'
>       > Configuration cache state could not be cached: field 'value' from type 'groovy.lang.Reference': error writing value of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration'
>          > Could not resolve all files for configuration ':runtimeClasspath'.
>             > Could not resolve org.lwjgl:lwjgl:3.2.3.
>               Required by:
>                   project :`

- [ B] 

> `* What went wrong:
> Script compilation errors:
> 
>   Line 304:         runtimeClasspath.attributes {
>                                      ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
>                                          public fun <T : Configuration> NamedDomainObjectProvider<TypeVariable(T)>.attributes(action: AttributeContainer.() -> Unit): Configuration defined in org.gradle.kotlin.dsl
>                                          public inline fun Manifest.attributes(vararg attributes: Pair<String, Any?>): Manifest defined in org.gradle.kotlin.dsl
>                                          public inline fun Manifest.attributes(sectionName: String, vararg attributes: Pair<String, Any?>): Manifest defined in org.gradle.kotlin.dsl
> 
>   Line 305:             attribute(MachineArchitecture.ARCHITECTURE_ATTRIBUTE, objects.named("x86"))
>                         ^ Unresolved reference: attribute`



I am unable to get anything in configuration-cache docs regarding **attributes** block. Is it in scope of this release? Need your input on this. 

Thanks

**Comment by abstratt** [comment]
Hi @prasad-333, thanks for looking into this.

For the `runtimeClasspathArtifacts` task, the attribute setting needs to be done against `configurations["runtimeClasspath"]`, not against the `FileCollection` local variable, which indeed does not support the `attributes` container.

That solves that task.

Now, the `failRuntimeClasspathResolve` task is supposed to fail with [this error](https://github.com/gradle/gradle/blob/d3c9887a3974feb98d5b71b26e116dbe5f54dd16/subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/tests/failRuntimeClasspathResolve.out).  However, under configuration cache the error reported has a slightly different shape, starting with this premble:

```
Configuration cache state could not be cached: field 'actions' from type 'org.gradle.api.DefaultTask': error writing value of type 'java.util.ArrayList'
> Configuration cache state could not be cached: field 'action' from type 'org.gradle.api.internal.AbstractTask$TaskActionWrapper': error writing value of type 'Build_gradle$14$1'
   > Configuration cache state could not be cached: field '$runtimeClasspath' from type 'Build_gradle$14$1': error writing value of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration'
      > Could not resolve all files for configuration ':runtimeClasspath'.
```

followed by the output that is expected (with a different indentation depth, due to the extra levels introduced above).

Tests that expect failures are hard to get right so they work with/without configuration cache for this exact reason: outcomes are similar but not identical.

Thanks for looking into this. Let's put this issue on hold for now, until we figure out what to do about this case.

**Comment by prasad-333** [comment]
> Hi @prasad-333, thanks for looking into this.
> 
> For the `runtimeClasspathArtifacts` task, the attribute setting needs to be done against `configurations["runtimeClasspath"]`, not against the `FileCollection` local variable, which indeed does not support the `attributes` container.
> 
> That solves that task.
> 
> Now, the `failRuntimeClasspathResolve` task is supposed to fail with [this error](https://github.com/gradle/gradle/blob/d3c9887a3974feb98d5b71b26e116dbe5f54dd16/subprojects/docs/src/snippets/dependencyManagement/customizingResolution-metadataRule/tests/failRuntimeClasspathResolve.out). However, under configuration cache the error reported has a slightly different shape, starting with this premble:
> 
> ```
> Configuration cache state could not be cached: field 'actions' from type 'org.gradle.api.DefaultTask': error writing value of type 'java.util.ArrayList'
> > Configuration cache state could not be cached: field 'action' from type 'org.gradle.api.internal.AbstractTask$TaskActionWrapper': error writing value of type 'Build_gradle$14$1'
>    > Configuration cache state could not be cached: field '$runtimeClasspath' from type 'Build_gradle$14$1': error writing value of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration'
>       > Could not resolve all files for configuration ':runtimeClasspath'.
> ```
> 
> followed by the output that is expected (with a different indentation depth, due to the extra levels introduced above).
> 
> Tests that expect failures are hard to get right so they work with/without configuration cache for this exact reason: outcomes are similar but not identical.
> 
> Let's put this issue on hold for now, until we figure out what to do about this case.

Ok Thanks @abstratt . let me know if any updates needs to be done from my end once decided on this particular use-case.

**Comment by abstratt** [comment]
@bot-gradle test this

**Comment by abstratt** [comment]
This would be a possible approach to make the tests run correctly with and without CC. 

Note that the separation between kotlin and groovy outputs would not be necessary once #22129 is merged.  We should wait until that PR is merged and change this again. It may be possible we don't even need separate outputs between CC and non-CC runs.

**Comment by abstratt** [comment]
#22129 is now in release, but will be in master only tomorrow. I will catch up with master and adjust my commit accordingly. @prasad-333, Hackathon-wise, not other actions required from you, as you fixed the base problem. However, this issue hid an architectural gap we hadn't noticed when we picked it up for the Hackathon. Once this is merged, the issue will be moved to done on the Hackathon board.

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Review by abstratt — APPROVED** [review]

**Comment by abstratt** [comment]
Good news, with https://github.com/gradle/gradle/pull/22129 merged, this change set no longer needs different expectations for kotlin vs groovy, nor for CC vs non-CC.

This is the last Hackathon issue to be merged! Thanks, @prasad-333 !

**Comment by prasad-333** [comment]
> Good news, with #22129 merged, this change set no longer needs different expectations for kotlin vs groovy, nor for CC vs non-CC.
> 
> This is the last Hackathon issue to be merged! Thanks, @prasad-333 !

Great @abstratt , Hackathon completed well within time. 
Congrats to Gradle team!!

**Pull request merged**
