### PR TITLE
Fix broken Kotlin DSL model builders cross version tests

### PR DESCRIPTION
**Pull request by eskatos**
Those tests were broken by https://github.com/gradle/gradle/commit/0139f007e35e344781bd60a055d637323554fca7 that added a `settings.gradle` file to all TAPI tests, interfering with the `settings.gradle.kts` used by the tests. This PR fixes this.

https://github.com/gradle/gradle-private/issues/3500

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle help

**Review by ljacomet — APPROVED** [review]
LGTM!

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
There are some flaky tests blocking us. https://github.com/gradle/gradle-private/issues/3503
I marked them as `@Flaky`.

@bot-gradle test and merge

**Comment by blindpirate** [comment]
Oh, just noticed this PR is intended to solve the problem. Then I'll leave this flaky test to you.

**Comment by eskatos** [comment]
This PR doesn't fix the flakiness but the direct failure of those tests.

@bot-gradle test and merge

**Comment by eskatos** [comment]
Ah I missed that some of the previously completely ignored tests were not annotated as flaky, just fixed that

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
