### PR TITLE
Add `jdk.io.File.enableADS` to list of immutable system properties

### PR DESCRIPTION
**Pull request by robbavey**
This commit adds `jdk.io.File.enableADS` to the list of immutable system properties, to enable the property
to be passed on the command line, rather than set at runtime.

Relates: https://github.com/elastic/logstash/issues/14075
Signed-off-by: Rob Bavey <rob.bavey@elastic.co>

Fixes #?

### Context

A recent update to the JDK, present in `11.0.15+10`, `17.0.3+7` introduced functionality
to check the validity of Windows file paths, rejecting, for example, paths with a `:`
present anywhere other than immediately following the drive letter. Unfortunately, this has the
side effect of throwing exceptions when attempting to write to the `NUL:` device.

This validity check is gated behind a property `jdk.io.File.enableADS`, which is set to `false` for
`11.0.15+10`, `17.0.3+7` releases of the JDK (it will be set to `true` for the next set of JDK releases)
This is causing our gradle jobs to fail, as the property is not set when the gradle daemon starts, as the
property is set after the test to determine the value is performed. This will fail for any Windows builds that
use the affected JDKs, and attempt to write to the `NUL:` device

Relates: https://github.com/elastic/logstash/issues/14075

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Review by h0tk3y — APPROVED** [review]
I verified that the behavior that depends on the property `jdk.io.File.enableADS`, namely handling of the paths to special Windows devices like `NUL:`, cannot be switched by modifying the property in a running JVM. So it is indeed another "immutable" system property, and adding it to the list seems to be reasonable.

**Comment by h0tk3y** [comment]
@bot-gradle test ReadyForNightly

**Comment by blindpirate** [comment]
It seems to be a small change, so I'll trigger a pre-tested commit build directly.

@bot-gradle test and merge

**Comment by h0tk3y** [comment]
@bot-gradle test ReadyForNightly

**Comment by h0tk3y** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@h0tk3y could you also add this to the list of immutable properties in `gradle_daemon.adoc`?

**Pull request merged**
