### PR TITLE
Add toolchain support for Scala plugin

### PR DESCRIPTION
**Pull request by rpalcolea**
### Context
Toolchain support for scala is/was missing

This takes inspiration from the groovy PR. Adds support for `ScalaPlugin` and `ScalaDoc` task

Some sample outputs:

### Toolchain detection
```
Found the following JVMs:
    AdoptOpenJDK 11.0.10  - /Users/rperezalcolea/.gradle/jdks/jdk-11.0.10+9/Contents/Home
    Amazon Corretto JDK 1.8.0_265  - /Users/rperezalcolea/.sdkman/candidates/java/8.0.265-amzn
    Zulu JDK 1.8.0_265  - /Users/rperezalcolea/.sdkman/candidates/java/8.0.265-zulu
    Zulu JDK 1.8.0_242  - /Users/rperezalcolea/.sdkman/candidates/java/8.0.242-zulu
    Zulu JDK 1.8.0_252  - /Users/rperezalcolea/.sdkman/candidates/java/8.0.252-zulu
    Zulu JDK 11.0.7  - /Users/rperezalcolea/.sdkman/candidates/java/11.0.7-zulu
    Zulu JDK 11.0.11  - /Users/rperezalcolea/.sdkman/candidates/java/11.0.11-zulu
    Zulu JDK 11.0.10  - /Users/rperezalcolea/.sdkman/candidates/java/11.0.10-zulu
    Zulu JDK 11.0.6  - /Users/rperezalcolea/.sdkman/candidates/java/11.0.6-zulu
    Zulu JDK 13.0.2  - /Users/rperezalcolea/.sdkman/candidates/java/13.0.2-zulu
    Zulu JDK 14.0.1  - /Users/rperezalcolea/.sdkman/candidates/java/14.0.1-zulu
    Zulu JDK 16  - /Users/rperezalcolea/.sdkman/candidates/java/16.0.0-zulu
    Zulu JDK 16.0.1  - /Users/rperezalcolea/.sdkman/candidates/java/16.0.1-zulu
> Task :compileJava NO-SOURCE
```

### Running compilation:

```
  501 14173 14115   0  6:34PM ??         0:01.20 /Users/rperezalcolea/.sdkman/candidates/java/16.0.0-zulu/bin/java @/Users/rperezalcolea/Projects/github/gradle/gradle/intTestHomeDir/distributions-jvm/.tmp/gradle-worker-classpath17437237116099633258txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 1'
```

### scaladoc 

```
Successfully started process 'Gradle Worker Daemon 1'
Started Gradle worker daemon (0.381 secs) with fork options DaemonForkOptions{executable=/Users/rperezalcolea/.sdkman/candidates/java/16.0.0-zulu/bin/java, minHeapSize=null, maxHeapSize=null, jvmArgs=[], keepAliveMode=SESSION}.
```

Some screenshots
Screen Shot 2021-06-20 at 6 59 48 PM

Screen Shot 2021-06-20 at 6 34 28 PM
Screen Shot 2021-06-20 at 6 36 16 PM

### opportunities

`AbstractScalaCompile` has methods such as `configureCompatibilityOptions` which could be re-used for groovy compilation. Currently the method exists in the `language-java` project. Maybe this should be moved to `language-jvm` so it is re-usable. But that might mean moving some internal compilation classes.

Happy to address this in this PR on in another

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by rpalcolea** [comment]
heads up @ljacomet :)

**Review by ljacomet — APPROVED** [review]
Thanks a lot for this contribution.

Looks good to me, let's see what CI says 😉 

The only missing bit is documentation. Could you take care of it as well?

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by rpalcolea** [comment]
Hi @ljacomet ,

Fixed missing `@Incubating` annotation which broke the API. Also added changes to XMLs and adocs

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by rpalcolea** [comment]
Hi @ljacomet 

It seems CI is failing with https://ge.gradle.org/s/zpm6tl2lhkeyg

```
  | org.gradle.execution.taskpath.ProjectFinderByTaskPath$ProjectLookupException: Project 'functional' not found in root project 'gradle'. |  
-- | -- | --
```
doesn't seem related to my changes

Either way, I updated the branch with latest on `master`

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@rpalcolea @ljacomet Note there is an error in asciidoc check:

```
# Valid links are:
# * Inside the same file: <<(#)section-name(,text)>>
# * To a different file: <<other-file(.adoc)#section-name,text>> - Note that the # and section are mandatory, otherwise the link is invalid in the single page output
#
# The checker does not handle implicit section names, so they must be explicit and declared as: [[section-name]]
ERROR: scala_plugin.adoc:63 Missing section reference for link to toolchains.adoc
    The `ScalaCompile` and `ScalaDoc` tasks can also leverage the <<toolchains.adoc#,Java toolchain support>>.
```

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by rpalcolea** [comment]
Hi @blindpirate, good call

I think https://github.com/gradle/gradle/pull/17494/commits/026f765289bee66f6a965b90f7da7305e2714f36 should take care of it 

```
VFS> Statistics since last build:
VFS> > Stat: Executed stat() x 0. getUnixMode() x 0
VFS> > FileHasher: Hashed 0 files (0 bytes)
VFS> > DirectorySnapshotter: Snapshot 0 directory hierarchies (visited 0 directories, 0 files and 0 failed files)
Received 35 file system events since last build while watching 1 hierarchies
Virtual file system retained information about 31052 files, 2023 directories and 84 missing files since last build
Type-safe project accessors is an incubating feature.

BUILD SUCCESSFUL in 11s
259 actionable tasks: 21 executed, 238 up-to-date
Received 33 file system events during the current build while watching 1 hierarchies
Virtual file system retains information about 31052 files, 2023 directories and 84 missing files until next build
VFS> Statistics during current build:
VFS> > Stat: Executed stat() x 1,076. getUnixMode() x 0
VFS> > FileHasher: Hashed 0 files (0 bytes)
VFS> > DirectorySnapshotter: Snapshot 2 directory hierarchies (visited 13 directories, 52 files and 0 failed files)

```

**Comment by blindpirate** [comment]
Thanks @rpalcolea

There's some issues in CI, I'll take care of it.

@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
