### PR TITLE
Make archive naming snippet work with gradle cache configuration

### LINKED ISSUE #21812: CCH22-15: Adjust the `snippets/files/archiveNaming` sample for configuration cache
The sample project located under [`subprojects/docs/src/snippets/files/archiveNaming`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/files/archiveNaming) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-files-archive-naming_groovy_archiveNaming.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-files-archive-naming_groovy_archiveNaming.sample)
    ```
    Could not find method relativePath() for arguments [task ':myZip' property 'destinationDirectory'] on task ':myZip' of type org.gradle.api.tasks.bundling.Zip.
    ```

* `snippet-files-archive-naming_kotlin_archiveNaming.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-files-archive-naming_kotlin_archiveNaming.sample)
    ```
    Task `:myZip` of type `org.gradle.api.tasks.bundling.Zip`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-files-archive-naming_groovy_archiveNaming.sample" \
    --tests "*snippet-files-archive-naming_kotlin_archiveNaming.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc`;

### PR DESCRIPTION
**Pull request by gabrielrodriguez2746**
Fixes #21812

### CODE REVIEW

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Comment by h0tk3y** [comment]
@gabrielrodriguez2746 Could you please also [add your name and/or Github handle to the contributors list](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md#create-a-pr-with-your-solution) in `subprojects/docs/src/docs/release/notes.md`?

**Review by abstratt — APPROVED** [review]
Looking good, thanks!

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Pull request merged**
