### PR TITLE
Fix failing PropertyUpgradesBinaryCompatibilityCrossVersionSpec

### PR DESCRIPTION
**Pull request by reinsch82**
### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by reinsch82** [comment]
@bot-gradle test ACT

**Comment by reinsch82** [comment]
@bot-gradle test ACT

**Review by asodja — APPROVED** [review]
LGTM

**Comment by reinsch82** [comment]
@bot-gradle test and merge

**Pull request merged**
