### PR TITLE
Normalize internal spelling of metadata

### PR DESCRIPTION
**Pull request by bamboo**
This PR focuses on internal types of dependency-management but also applies the normalization to docs, comments and strings everywhere.

### CODE REVIEW

**Comment by bamboo** [comment]
@bigdaz, could you take a look at this one, please?

**Comment by bigdaz** [comment]
@bamboo You might want to see if someone else can help get this merged. The changes don't look contentious to me. We'll just need to be aware of the impact on existing clones on case-insensitive filesystems, if any.

**Comment by bamboo** [comment]
FTR I've merged this branch locally on two different case-insensitive file systems on two different operating systems (osx and windows) and there was no issue.

**Comment by bigdaz** [comment]
In that case, I would recommend merging. We don't use pre-commit review for other work, and this seems a fairly straightforward change, if pervasive.

**Comment by pioterj** [comment]
@bamboo is this merged already? If yes, can we close it so it doesn't clutter the backlog?

**Comment by bamboo** [comment]
Sure thing!

**Pull request closed without merging**
