### PR TITLE
Introduce a build operation type around the execution phase

### PR DESCRIPTION
**Pull request by wolfs**
So Build Scans don't need to infer from accidental data when this starts.

### CODE REVIEW

**Review by facewindu — APPROVED** [review]

**Comment by wolfs** [comment]
@bot-gradle merge

**Review by big-guy — APPROVED** [review]

**Comment by wolfs** [comment]
@bot-gradle merge

**Comment by wolfs** [comment]
@bot-gradle cancel

**Comment by wolfs** [comment]
@bot-gradle merge

**Pull request merged**
