### PR TITLE
Introduce daemon JVM criteria 

### PR DESCRIPTION
**Pull request by big-guy**
### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test RfR

**Comment by big-guy** [comment]
@bot-gradle test RfR

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle merge

**Comment by big-guy** [comment]
@bot-gradle merge

**Comment by big-guy** [comment]
@bot-gradle merge

**Comment by big-guy** [comment]
@bot-gradle merge

**Comment by gabrielittner** [comment]
@big-guy is there an issue that can be followed for the vendor support that was removed for now?

**Pull request merged**
