### PR TITLE
Add aws-java-sdk-sts dependency

### LINKED ISSUE #15332: Unable to Authenticate on S3 using IAM Roles for Service Accounts (IRSA)
### Expected Behavior

Given you have a S3 bucket configured as a Maven repository and `awsIm(AwsImAuthentication)` is set as authentication, Gradle should be able to use IRSA credentials from inside a K8s Pod with the service account attached.

### Current Behavior

Although the authentication chain used has `WebIdentityTokenCredentialsProvider` as part of it, it is not able to use it as `aws-java-sdk-sts` is not in the class path. The provider mentioned is the one used by the AWS SDK to authenticating using IRSA.
```2020-11-26T18:56:06.653+0000 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path.```

### Context

We use GitHub Actions as our CI platforms, and it executes jobs inside K8s Pods on our infrastructure. The projects should be able to use IRSA to authenticate with AWS and access private Maven repositories backed by S3. Currently it is not possible to do it and you must use the EC2 Instance Role or provide AWS Access Keys for it to be able to access S3 repositories.

AWS documentation regarding IRSA: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/.

### Steps to Reproduce 

1. Create a K8s Pod with IRSA configured.
2. Inside the pod, try to build a project that has a dependency on a private Maven repository that uses S3.
3. Observe that Gradle was not able to authenticate using the service account configured.
```2020-11-26T18:56:06.658+0000 [DEBUG] [com.amazonaws.services.s3.S3CredentialsProviderChain] No credentials available; falling back to anonymous access```

### Your Environment

Build scan URL: (no able to provide as I'm building a closed-source project)

`./gradlew --version`
```
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_275 (Azul Systems, Inc. 25.275-b01)
OS:           Linux 4.14.198-152.320.amzn2.x86_64 amd64
```

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by t0rr3sp3dr0**
Fixes #15332

### Context

As seen in the logs, AWS SDK complains about `aws-java-sdk-sts` not being in the class path when trying to authenticate using `WebIdentityTokenCredentialsProvider`. So I've added it to the dependencies of Gradle and I can confirm I'm able to use IRSA to authenticate on a Maven S3 Repository from inside a Kubernetes Pod.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by t0rr3sp3dr0** [comment]
@ljacomet, could you review this PR?

**Comment by JLLeitschuh** [comment]
Are you able to verify with a test that this indeed fixes this issue? If not, can you leave documentation on the dependency explaining why it is needed?

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, this is the best of a test I could do:

```java
    public static boolean isWorking() {
        WebIdentityTokenCredentialsProvider provider = WebIdentityTokenCredentialsProvider.create();

        try {
            provider.getCredentials();
        } catch (SdkClientException e) {
            if (e.getCause() instanceof ClassNotFoundException)
                return false;
        } catch (NullPointerException ignored) {
        }

        return true;
    }
```

I don't know if this is the kind of test that we would like to put on Gradle, as it relies on looking for generic exceptions and ignoring others.

The code that uses `aws-java-sdk-sts` is underneath an `internal` package and cannot be accessed directly: https://github.com/aws/aws-sdk-java/blob/4cf09503f2fad673f9838601e8173d8a4afdca02/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/securitytoken/STSProfileCredentialsServiceProvider.java#L46-L66.

The workaround was to call `WebIdentityTokenCredentialsProvider#getCredentials`, but invocations to it always fail as we don't have valid AWS credentials. Checking which exception was thrown is the only way to figure out whether or not the provider would have succeeded if we had valid credentials.

**Comment by t0rr3sp3dr0** [comment]
I've added the documentation to the dependency as you requested.

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, can we proceed with the approach of just explaining why the dependency is needed?

**Comment by JLLeitschuh** [comment]
You could check the logs and verify that the exception you were seeing is no longer present

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, I was able to implement a test the way you suggested!

**Comment by t0rr3sp3dr0** [comment]
I don't know if I should also check that instead of

```
[DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path.
```

the output now contains

```
[DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName
````

**Comment by JLLeitschuh** [comment]
@t0rr3sp3dr0 looks like you have a merge conflict. Once you resolve that, I'll push your changes through CI

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, I've pushed another commit solving the conflict.

**Comment by JLLeitschuh** [comment]
@bot-gradle test this please

**Comment by t0rr3sp3dr0** [comment]
@bot-gradle test this please

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, could you trigger the tests for me again?

The `distribution size should not exceed a certain number` and `no additional jars are added to the distribution` tests were failing and I had to increase their limits in `1 MiB` and `1`, respectively.

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, I think you missed my last message. Could you trigger the CI? I don't have access to do it.

**Comment by JLLeitschuh** [comment]
Done, we've had to temporarily halt our use of the `bot-gradle` so setting up a build job takes quite a few more clicks now. Sorry.

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, all tests have passed! Can we merge the PR?

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, are we good to merge?

**Comment by t0rr3sp3dr0** [comment]
@JLLeitschuh, would you like me to modify something on the PR or are we good to merge it?

**Review by JLLeitschuh — APPROVED** [review]
LGTM! Thanks for your contribution!

**Pull request merged**
