### PR TITLE
Extract common `maybeRoundLastModified` method

### PR DESCRIPTION
**Pull request by blindpirate**
To be shared by two unit tests.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
