### PR TITLE
Introduce configuration for compilation and test execution of buildSrc

### PR DESCRIPTION
**Pull request by bmuschko**
### Context

See comment https://github.com/gradle/gradle-promote/pull/13#discussion_r163679395

I wasn't quite sure about the syntax. Some additional comments/questions:

- Why are the promotion steps defined as XML and not as Kotlin?
- I was unsure about some of the IDs given to the elements e.g. `runner id="RUNNER_9"`. Is it OK if there are duplicates? If it's not OK how do I find out a unique number. Seems hacky.
- Is there any way to verify the correctness of the XML?

### CODE REVIEW

**Comment by wolfs** [comment]
Instead of using a PR, you could create the Job via the UI.
I think the id of the runner does not matter.
Anyway, I think this is good to merge, we should sort out the problem by doing changes in the UI until the job succeeds.

**Comment by bmuschko** [comment]
I merged but had to revert. This is hacky. It was conflicting because I used the same UUID of another job. Seems like you need to set it up manually and then derive the XML.

**Comment by bmuschko** [comment]
I set up the configuration manually: https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Promotion_MasterSanityCheck. It is automatically synced to the TeamCity config on GitHub.

**Comment by wolfs** [comment]
LGTM!

**Pull request merged**
