### PR TITLE
Update Gradle Enterprise Gradle plugin to 3.14.1

### PR DESCRIPTION
**Pull request by marcphilipp**

### CODE REVIEW

**Comment by marcphilipp** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
Thanks

I wished we had fewer locations to update

**Review by lkasso — APPROVED** [review]

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Comment by marcphilipp** [comment]
@ljacomet The test failures seem reproducable but it don't see why they would be related to this change. Could you please take a look?

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@marcphilipp Are there any dependency changes in the GE plugin 3.14.1, especially to JUnit platform? Maybe that is causing the failures.

**Comment by marcphilipp** [comment]
Yes, it includes JUnit 5.10 since it requires its new dry-run feature to add support for Gradle 8.3's new `--test-dry-run`. I'll see if I can create a standalone reproducer.

**Comment by marcphilipp** [comment]
I did not manage to reproduce this in a standalone project using a < 5.10 version of JUnit, TD, and Gradle 8.4-20230726231211+0000. Therefore, I think it only occurs in the func tests and can be worked around by requiring a daemon to run the build rather than in embedded mode.

**Review by wolfs — APPROVED** [review]

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Comment by marcphilipp** [comment]
@bot-gradle test and merge

**Comment by marcphilipp** [comment]
@pshevche @wolfs As you can see above I retried merging this a few times without success. Since I'll be offline for a few days, could one of you please see this PR over the finish line? 🙏

**Comment by pshevche** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
FYI there will be an 8.3 RC3 in case you want this change on `release`

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
