### PR TITLE
Remove @Deprecated JacocoMerge task

### LINKED ISSUE #21553: Remove @Deprecated JacocoMerge for Gradle 8.0

### PR DESCRIPTION
**Pull request by tresat**
- Rework jacoco report merging test to use JacocoReport task and test suites.

Fixes #21553

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
