### PR TITLE
Backport Apple Silicon support to 6.9

### LINKED ISSUE #15751: Backport Apple silicon support to 6.x
This is fairly easy and would help people staying on 6.x.

All it should take is to merge this PR to `release`: https://github.com/gradle/gradle/pull/15612.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by melix**
### Context

Fixes #15751 and #16448

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by melix** [comment]
@bot-gradle test and merge

**Pull request merged**
