### PR TITLE
Merge release7x again

### PR DESCRIPTION
**Pull request by big-guy**

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
Not sure how to debug this further, but the failing test passes if we use an anonymous class for this lambda: 
https://github.com/gradle/gradle/blob/4fed83ebb6bc991f754eb374823d47803fc18b1e/subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/AbstractExternalDependencyFactory.java#L76

The failing test which exercises this code has removed the `@UnsupportedWithConfigurationCache` annotation in `release`, which makes this serialization error apparent in 8.0 but not in 7.6. 

I was expecting some kind of configuration cache report but did not see one.

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
