### PR TITLE
Update kts snippet: use `coerceAtLeast(1)` util function

### PR DESCRIPTION
**Pull request by aSemy**
Minor docs tweak to use a more succinct helper function, [`coerceAtLeast()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/coerce-at-least.html)

### Context

This helps make the snippet more comprehensible, as it uses a util function which has a more understandable name, and doesn't require knowledge of `takeIf {}` and the elvis operator.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by eskatos** [comment]
Thanks Adam.
The DCO check is failing, could you please follow the [instructions](https://github.com/gradle/gradle/pull/25268/checks?check_run_id=13967092139) to fix this?

**Comment by eskatos** [comment]
@aSemy, we can't accept a contribution with a failing DCO, could you please follow the [instructions](https://github.com/gradle/gradle/pull/25268/checks?check_run_id=13967092139) to fix this?

**Comment by aSemy** [comment]
@eskatos this should be done now. It's a bit inconvenient to add sign off because I made this PR through the GitHub Web UI which doesn't give an option, and the git commands didn't seem to work for me - I had to play around with them a lot.

**Comment by eskatos** [comment]
Yeah, sorry for the hurdle for this small contribution. It looks good now, thank you!

**Review by eskatos — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
