### PR TITLE
Improve a little bit the userguide for incremental annotation processing

### PR DESCRIPTION
**Pull request by int02h**
Signed-off-by: Daniil Popov <int02h@gmail.com>

### Context
I see that different annotation processors declare category in file `incremental.annotation.processors` in different letter cases. For instance, Dagger's [ComponentProcessor](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/ComponentProcessor.java) uses `@IncrementalAnnotationProcessor(ISOLATING)` to declare category which generates line like the following:
```
dagger.internal.codegen.ComponentProcessor,ISOLATING
```
whereas Room's [RoomProcessor](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/room/compiler/src/main/resources/META-INF/gradle/incremental.annotation.processors) does it in lower-case:
```
androidx.room.RoomProcessor,dynamic
```
But the documentation does not say anything about case-sensitiveness. 

Also, there are questions like [this](https://github.com/gradle/gradle/issues/4930) about in which format a developer should provide a processor name. Documentation has been already fixed in #4959 but I believe example snippet should visualize that.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [not applicable] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [not applicable] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
@int02h Thanks for the documentation improvement.
However your change to the sample breaks it.
Can you have a look at the `SamplesJavaIncrementalAnnotationProcessingIntegrationTest` test and make sure to fix it following your changes?

**Comment by int02h** [comment]
@ljacomet of course. I'll do that. Thank you for theresponse.

**Comment by int02h** [comment]
@ljacomet I've fixed tests for the user guide, but now there is one more test that failed and I have no idea why. I've run integration tests with the command `./gradlew :internalIntegTesting:check` and locally all test has passed. Could you please give me a clue on how to fix the failed test?

**Comment by int02h** [comment]
@ljacomet I've fixed failing tests

**Comment by int02h** [comment]
@ljacomet should I do something else or we can merge it?

**Comment by ljacomet** [comment]
Sorry, have been busy with other things. Will look into that later today or tomorrow

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
Thanks for the contribution!

**Pull request merged**
