### PR TITLE
Remove deprecated local build cache configuration

### LINKED ISSUE #15551: Remove deprecated arbitrary local build cache configuration option
### Summary
- [x] `BuildCacheConfiguration.local(Class)`
- [x] `BuildCacheConfiguration.local(Class, Action)`
- [x] `DefaultBuildCacheConfiguration.local(Class)`
- [x] `DefaultBuildCacheConfiguration.local(Class, Action)`
- [x] `CompatibilitySupportForBuildCacheConfiguration`

### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [ ] Check User Manual for dangling references and outdated documentation
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

### PR DESCRIPTION
**Pull request by melix**
Closes #15551

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test QFL

**Comment by melix** [comment]
@bot-gradle test QFL

**Comment by melix** [comment]
@bot-gradle test RFM

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by melix** [comment]
@bot-gradle test RFM

**Pull request merged**
