### PR TITLE
Remove JCenter from shorthand notation graphic 

### PR DESCRIPTION
**Pull request by donat**
Backport fix for https://github.com/gradle/gradle/issues/18035. (Original commit: https://github.com/gradle/gradle/commit/c6687d123bb062e2b7964fffc1f5a8080139d407)

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by donat** [comment]
@bot-gradle test and merge

**Pull request merged**
