### PR TITLE
Let `kotlin-dsl` fail with reasonable message when required Kotlin compiler arguments have been removed

### PR DESCRIPTION
**Pull request by eskatos**
* Fixes https://github.com/gradle/gradle/issues/24788

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test QFL

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by jbartok — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
