### PR TITLE
Replace AtomicReference by volatile field

### LINKED ISSUE #16794: Redundant atomic access around VFS statistics gathering
Here we are doing stuff with `AtomicReference` that don't make much sense:

https://github.com/gradle/gradle/blob/679e14442a12af29b45cb1568960d5e2fdb9330b/subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java#L85

The original intent was to avoid duplicating/missing events when the `MutableFileWatchingStatistics` gets swapped out in `getAndResetStatistics()` at the end of the build. However, it is still possible to record events duplicated like this.

We should either find a good way to truly guarantee that every event is reported on exactly once, or we should revert to a simpler solution, accepting that events might be reported in duplicate or none at all around the build's end.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by wolfs**
The original intent was to avoid duplicating/missing
events when the MutableFileWatchingStatistics gets
swapped out in getAndResetStatistics() at the end of
the build. However, it is still possible to record
events duplicated like this.

This PR replaces the AtomicReference by a volatile field.
That simplifies things. It is still possible to miss events,
though that is not so important, given that these are
statistics anyway.

Fixes #16794

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test QF

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
