### PR TITLE
Release of JaCoCo 0.7.6 requires update of Gradle Plugin

### PR DESCRIPTION
**Pull request by Godin**
Without those changes JaCoCo Plugin is not usable with JaCoCo versions 0.7.3 - 0.7.5 for some Gradle users - see JaCoCo/JaCoCo#288

### CODE REVIEW

**Comment by jaredsburrows** [comment]
:+1:

**Comment by eljobe** [comment]
@Godin Thanks for keeping our codebase healthy for all of the JaCoCo users out there.

Your help is greatly appreciated.

**Comment by dampcake** [comment]
I am getting `No such property: includeNoLocationClasses` with the `gradle-2.13-20160228000026+0000-all.zip`. Is this to be expected?

**Comment by eljobe** [comment]
@dampcake Can you share your build.gradle file or at least a snippet that shows how you are attempting to use the `includeNoLocationClasses` option?

**Comment by dampcake** [comment]
https://github.com/dampcake/gradle-575 reproduces. Just run the wrapper (no task required).

**Comment by Godin** [comment]
@dampcake I believe that it should be
```
test {
  jacoco {
    includeNoLocationClasses = true
  }
}
```
this property is in the same place as `includes` and so on - see https://docs.gradle.org/current/userguide/jacoco_plugin.html#jacocotesttast , while `toolVersion` is in https://docs.gradle.org/current/userguide/jacoco_plugin.html#configJacoco

**Comment by dampcake** [comment]
@Godin thanks for that put me on the right path. Apparently for Android you should use:
```groovy
android {
    testOptions {
        unitTests.all {
            jacoco {
                includeNoLocationClasses = true
            }
        }
    }
}
```

**Comment by mkjensen** [comment]
Any change of getting this backported to Gradle 2.10 used by Android Studio 2?

**Comment by eljobe** [comment]
@mkjensen It is very unlikely (bordering on impossible) that we would backport this update into another release of 2.10. Sorry.

**Pull request merged**
