### PR TITLE
Delete resolveArtifacts from ModuleComponentRepositoryAccess

### PR DESCRIPTION
**Pull request by big-guy**
This always returns the same answer and we do not need to worry
about the difference between "local" and "remote" repositories

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by DPUkyle — APPROVED** [review]
LGTM. 

Just checking - are any of the tests you deleted worth saving? i.e. would they still work if we stop referencing/downcasting to LocalRepositoryAccess etc.?

**Comment by big-guy** [comment]
> Just checking - are any of the tests you deleted worth saving? i.e. would they still work if we stop referencing/downcasting to LocalRepositoryAccess etc.?

No, the functionality is all gone from those classes.

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
