### PR TITLE
Setup jvm-test-fixtures project, extract java-test-fixtures plugin class

### PR DESCRIPTION
**Pull request by tresat**
Also clean up some other files that didn't or couldn't move to the proper sub-project without this existing, or were left behind in plugins by error.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by octylFractal — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
