### PR TITLE
Update user guide for multiproject

### PR DESCRIPTION
**Pull request by javaducky**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

### CODE REVIEW

**Comment by eriwen** [comment]
@javaducky What does this achieve? Why is this necessary?

**Comment by bmuschko** [comment]
@eriwen It simply renders the files available in the sample project in the relevant documentation page. `build.gradle` is currently missing.

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged.

**Comment by bmuschko** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-6389

**Pull request merged**
