### PR TITLE
Extend configuration from another project

### PR DESCRIPTION
**Pull request by Tanemahuta**
...tend-from-a-configuration-of-another-sub-project

### CODE REVIEW

**Comment by erdi** [comment]
Thanks for the contribution @Tanemahuta, somebody will be having a look at it shortly.

In the meantime, would you mind signing the CLA online at www.gradleware.com/contributor-agreement? Without it we won't be able to accept your contribution.

**Comment by erdi** [comment]
From the forum thread I can see that you have already signed it, thanks.

**Comment by Tanemahuta** [comment]
Well, the tests I have implemented are rather basic. And I have some suggestions for further tests. How can I get in contact (like live)? - Google Talk, or sth?

**Comment by erdi** [comment]
The best way to discuss pull request is to send an email to the dev list at https://groups.google.com/forum/#!forum/gradle-dev.

**Comment by Tanemahuta** [comment]
Thanks.

**Comment by bigdaz** [comment]
As discussed on the dev list, we don't want to support this sort of coupling between projects.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gradle-dev/0O-wCbk6izU/rBFrp_QdcAAJ

For that reason, I'm closing this PR.

**Pull request closed without merging**
