### PR TITLE
Avoid duplicate code in fork options validation

### PR DESCRIPTION
**Pull request by xaviarias**
Extracted duplicate behaviour into a factory method containing additional validations for consistency, i.e. the executable exists and is not a directory.

Fixes: #22023
See also: #21758

Co-authored-by: @jbartok

**NOTE:** This PR will remain a draft until https://github.com/gradle/gradle/pull/22108 is merged in and then needs to be adapted to those changes.

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle

**Comment by xaviarias** [comment]
@bot-gradle test qfl

**Comment by xaviarias** [comment]
@bot-gradle test this

**Comment by xaviarias** [comment]
@bot-gradle test this

**Comment by xaviarias** [comment]
@bot-gradle test QLF

**Comment by xaviarias** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by xaviarias** [comment]
@bot-gradle test and merge

**Pull request merged**
