### PR TITLE
Improve error message when probing toolchain installation fails

### LINKED ISSUE #21872: `JavaToolchainFactory#newInstance` silently discards original exception
### Expected Behavior
When an issue with the configured toolchain is detected, Gradle should provide all available information about the failure.

### Current Behavior
`JavaToolchainFactory#newInstance` discards the metadata information if it is not a valid installation:
https://github.com/gradle/gradle/blob/c4e3c1a39051e97349f870da54fdd66eb8810bec/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainFactory.java#L52-L56

This causes the original exception which is stored in the metadata to not be reported.

### Context
It makes debugging toolchain issues more difficult. For example in my case #20520 seems to have occurred because Gradle is downloading the wrong JDK for Alpine (for other users the cause might be a different one). However, Gradle just reports:
```
Provisioned toolchain '/root/.gradle/jdks/adoptium-17-x64-hotspot-linux/jdk-17.0.4.1+1' could not be probed.
```

Whereas the original exception, included in the metadata which is discarded by `JavaToolchainFactory`, would have been:
```
A problem occurred starting process 'command '/root/.gradle/jdks/adoptium-17-x64-hotspot-linux/jdk-17.0.4.1+1/bin/java''
  Could not start '/root/.gradle/jdks/adoptium-17-x64-hotspot-linux/jdk-17.0.4.1+1/bin/java'
    Cannot run program "/root/.gradle/jdks/adoptium-17-x64-hotspot-linux/jdk-17.0.4.1+1/bin/java" (in directory "/root/.gradle/.tmp/tmp-jvm14264294632786197088probe"): error=2, No such file or directory
      error=2, No such file or directory
```
(the error message from Alpine is not that expressive, but it might have helped debugging this)

### Steps to Reproduce 
Use for example the Dockerfile from https://github.com/gradle/gradle/issues/20520#issuecomment-1118007534

### Your Environment
With the above Docker setup: WSL 2, Docker

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #21872

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
LGTM!

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
There seems to be real failures: https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Platform_4_bucket42/58350106?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true

https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Platform_4_bucket28/58350092?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true

https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Platform_4_bucket30/58350094?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=true

**Comment by jbartok** [comment]
@bot-gradle test this

**Comment by jbartok** [comment]
@bot-gradle test this

**Comment by jbartok** [comment]
@bot-gradle test this

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
