### PR TITLE
Expand generics on Provider.zip()

### PR DESCRIPTION
**Pull request by lptr**
This changes `Provider.zip()` from:

```java
    <B, R> Provider<R> zip(Provider<B> right, BiFunction<T, B, R> combiner);
```

to:

```java
    <B, R> Provider<R> zip(Provider<B> right, BiFunction<? super T, ? super B, ? extends R> combiner);
```

Same for `ProviderFactory.zip()`.

### CODE REVIEW

**Review by eskatos — APPROVED** [review]
This is a good move. Let's see what extended coverage has to say

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Pull request merged**
