### PR TITLE
setting annotation processor classpath in scala compile task

### PR DESCRIPTION
**Pull request by krro**
Issue: #1498

### Context
This is a fix for bug described here https://github.com/gradle/gradle/issues/1498
Scala plugin will now be able to compile code annotated with ex. @Slf4j or others

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by krro** [comment]
I got `./gradlew languageScala:check` passing locally, but there were some issues with `./gradlew scala:check` - some integration tests were failing for me, but those doesn't seem to be related with my changes and seem to fail on master as well?

**Comment by krro** [comment]
As this is a simple fix, is there a chance to possibly retarget the PR to some other branch to get it released relatively earlier?

**Comment by ymwang1984** [comment]
https://github.com/gradle/gradle/issues/2337

**Comment by ymwang1984** [comment]
verified locally that it works

**Comment by bmuschko** [comment]
Thanks for providing the pull request. It has been merged. I am going to go ahead with polishing the code a bit more and adding integration tests.

**Pull request merged**
