### PR TITLE
Don't reprocess derived types if primary type is reprocessed

### LINKED ISSUE #18840: [Regression] Incremental annotation processor fails with "Attempt to recreate a file for type"
This is related to #13767

### Expected Behavior

Incremental Java compilation should succeed.

### Current Behavior

Incremental Java compilation fails with:

> error: Unexpected error: Attempt to recreate a file for type com.example.$Controller$Definition

if using Gradle 7.3-rc-3. It compiles fine with 7.2.

### Context

I was debugging another incremental annotation processing issue and when checking what the behavior with latest Gradle was, I realized it was failing badly.

### Steps to Reproduce 

```bash
$ git clone git@github.com:melix/gradle-73-incremenal-ap-bug.git
$ cd gradle-73-incremenal-ap-bug
$ ./gradlew cJ
$ printf ' ' >> src/main/java/com/example/Application.java
$ ./gradlew cJ
```

### Your Environment

Build scan URL: https://gradle.com/s/vhw3tzhkvnebg

### PR DESCRIPTION
**Pull request by oehme**
Fixes #18840

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
@melix @ljacomet FYI

**Comment by ljacomet** [comment]
@oehme Could you target `release` for these changes?

**Comment by oehme** [comment]
Github got really confused, so I had to add an empty merge commit to make it stop reporting merge conflicts that didn't exist. Probably a race condition between pushing my changes and changing the base branch.

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by asodja — APPROVED** [review]

**Comment by ljacomet** [comment]
@melix Can you confirm this fixes the issue on your side?

**Comment by melix** [comment]
I could confirm the fix works for me, thanks @oehme !

**Pull request merged**
