### PR TITLE
Remove unused entries from verification metadata

### PR DESCRIPTION
**Pull request by melix**
### Context

There is no way for Gradle to automatically determine that an entry in the verification file is redundant (any task can do anything dynamically, so unless you exercise _all_ code paths of a build, you never know).

As such it's the responsibility of folks updating the verification file to remove unused entries.

@jonnybbb FYI

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test QFL

**Comment by melix** [comment]
@bot-gradle test QFL

**Review by ljacomet — APPROVED** [review]

**Comment by lptr** [comment]
I think this could be made easier if there was an option to only _upgrade_ versions, i.e. to drop older versions automatically. If I know that my build should only use one version of Guava, then I don't want to manually have to ensure that the verification XML contains only one.

**Comment by melix** [comment]
The problem is that you cannot guarantee that. Different configurations can resolve different versions and it's perfectly legit. Plus, in Gradle we _don't_ verify metadata (POM files), but if you do, those are verified _during resolution_ (in order to make sure you don't compromise the resolution result itself), which means that any version which appears at some point during the resolution of a graph needs to be added to the verification file.

**Pull request merged**
