### PR TITLE
Replace classycle by archunit test

### PR DESCRIPTION
**Pull request by wolfs**
So that the reporting when we actually have a classycle is better.

The PR replaces our Classycle tasks by an ArchUnit test. The test is defined once in `internal-architecture-testing` and then executed in all subprojects. It only takes the classes of the subprojects into account and does look a cycles between packages in the current project and other projects. The reason for that is that classycle doesn't either and that we have a lot of cycles between subprojects.

For simplicity, the ArchUnit tests only works on the main source set of the production classes. So it doesn't look at test source sets or any other things. I also didn't add these cycle tests for our build logic, since this would require to pull the test even further up. While possible, I am not convinced this is worth the effort.

As a side-effect of the change, you can now define ArchUnit tests simply in the subprojects in the `archUnit` source set. Those ArchUnit test will run against the current project and possible its dependencies.

### CODE REVIEW

**Review by blindpirate — COMMENTED** [review]
IIUC, this PR uses "classycle" as a terminology even it's not using any `classycle` dependency?

**Comment by wolfs** [comment]
> this PR uses "classycle" as a terminology even it's not using any classycle dependency?

@blindpirate I use `packageCycles` for the extension name instead. PTAL!

**Review by blindpirate — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
