### PR TITLE
Let Kotlin DSL script compilation execute via the execution engine

### PR DESCRIPTION
**Pull request by bamboo**
Write both the stage1 and stage2 outputs to the root cache directory (since they are always written to different cache directories).

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
FTR, I'll get back to it later this week.

**Comment by bamboo** [comment]
@bot-gradle test QF

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Comment by bamboo** [comment]
@bot-gradle test QF

**Comment by bamboo** [comment]
There are currently only 3 tests failing in `BuildScriptCompileAvoidanceIntegrationTest`, something related to how the `buildSrc` classpath is handled. I'm looking into it.

**Comment by bamboo** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]
Great stuff \o/
It's nice to see the removal of the now dead code.

LGTM if the performance tests pass.
It might also be worth running `Ready for Nightly` on those changes.


CI agents cleanup should also be updated with the changes to the workspace paths
https://github.com/gradle/gradle/blob/0a1ab845e6e6d557a00c9329ed85bf9155d73a12/buildSrc/subprojects/cleanup/src/main/kotlin/gradlebuild/cleanup/Cleanup.kt#L95-L96

I think we can already get rid of `gradle-kotlin-dsl-accessors` but should wait a bit before removing `gradle-kotlin-dsl`. Let's address both later.

**Comment by bamboo** [comment]
Thanks for the review, Paul! Good point about `Ready for Nightly`. I'll let it go through one more time.

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Pull request merged**
