### PR TITLE
Update JacocoBase.getJacocoClasspath() to use Provider API

### PR DESCRIPTION
**Pull request by tresat**

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test RFN

**Review by asodja — APPROVED** [review]
LGTM, thanks!

**Comment by asodja** [comment]
@bot-gradle test RFN

**Comment by asodja** [comment]
@bot-gradle test RFN

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test help

**Comment by asodja** [comment]
@bot-gradle test this without PTS

**Pull request merged**
