### PR TITLE
Change choosing a log level table to reflect real order

### PR DESCRIPTION
**Pull request by JavierSegoviaCordoba**
There is no open issue, just a message in Gradle Slack.

### Context
As non logger expert I just thought that the table order was the real levels order, but indeed the previous table in the same doc has the right order, but in a diagonal reading you can think both are the same and pick the incorrect level.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by hythloda** [comment]
@JavierSegoviaCordoba can you complete the [DCO](https://github.com/gradle/gradle/pull/24173/checks?check_run_id=11790912460) step? Then it is an easy merge :)

**Comment by hythloda** [comment]
[Slack thread for reference](https://gradle-community.slack.com/archives/CAHSN3LDN/p1678033693544769)

**Comment by hythloda** [comment]
@bot-gradle test and merge

**Review by hythloda — APPROVED** [review]

**Comment by JavierSegoviaCordoba** [comment]
Do I need to update the branch or it is done automatically?

**Comment by hythloda** [comment]
> Do I need to update the branch or it is done automatically?

We are just letting bot do its thing. The timing is weird for this because we are also branching right now. So no changes at the moment.

**Comment by hythloda** [comment]
Not sure why it marked it as closed and not merged. The changes did go into effect: https://github.com/gradle/gradle/blob/release/subprojects/docs/src/docs/userguide/authoring-builds/logging.adoc

**Comment by JavierSegoviaCordoba** [comment]
Perfect 👍, don't worry :)

**Pull request closed without merging**
