### PR TITLE
Use version-specific output directory for JFR output directory

### PR DESCRIPTION
**Pull request by blindpirate**
Previously, we set same JFR output directory for different versions of Gradle,
which caused all JFR recording files in same directory. This PR sets version
specific output directory for JFR output.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@wolfs I realized it's not `gradle-profiler`, but we passed same output directory on Gradle's side...

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Review by wolfs — COMMENTED** [review]
If you tried this out and it works for cross version tests with and without a could daemon on Windows and Linux, then please go ahead and merge it. Please test if `async-profiler` works with this as well.

**Pull request closed without merging**
