### PR TITLE
Remove deprecated methods in `JavaCompile`

### LINKED ISSUE #15548: Remove deprecated methods in JavaCompile
### Summary

- `JavaCompile.compile(IncrementalTaskInputs)`
- `JavaCompile.getSources()`

### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

### PR DESCRIPTION
**Pull request by melix**
Those methods could potentially be used by plugins extending `JavaCompile`
so the scope is quite restricted.

Fixes #15548

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test QFL

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by melix** [comment]
@bot-gradle test QFL

**Comment by melix** [comment]
@bot-gradle test RFM

**Comment by melix** [comment]
@bot-gradle test RFM

**Pull request merged**
