### PR TITLE
Improve handling of enforced platforms

### PR DESCRIPTION
**Pull request by melix**
### Context

This pull request improves the handling of "enforced platforms" in two cases:

- if Gradle is consuming an enforced platform transitively and that a strict dependency conflicts with what the platform declared, it was very hard to figure out from the error message. This is improved by adding the selected variant to the error message, so that we have a clue.
- when publishing, Gradle will by default disallow generation of Gradle module metadata referencing an enforced platform, as it would generally be an error to do so. It is however possible to disable validation.

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Review by ljacomet — COMMENTED** [review]
This is a good improvement indeed.

The validation is however a breaking change. Which is fine if it goes in 7.0 but not for 6.9 I think.
At the same time I do not want it to be only a warning by default.
Any comment on that?

**Comment by melix** [comment]
It's a breaking change but it's extremely unlikely that it's the behavior people want. I actually consider that a bug if you publish such a library...

**Review by ljacomet — APPROVED** [review]
After further discussions, let's have this change in 6.9 or 7.0 anyway.

While it is a breaking change, it will not silently break a build, and it has an escape hatch.

**Pull request merged**
