### PR TITLE
Fix hanging disconnect in Tooling API

### PR DESCRIPTION
**Pull request by donat**
I've implemented an integration test demonstrating that #14634 is still not resolved. I've re-added my initial solution which fixes the bug.

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFR

**Comment by donat** [comment]
@bot-gradle test rFR

**Comment by donat** [comment]
@bot-gradle test rFR

**Comment by ant-druha** [comment]
We are still getting reports for https://youtrack.jetbrains.com/issue/IDEA-250375

```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at java.base@11.0.10/sun.nio.ch.Net.poll(Native Method)
	at java.base@11.0.10/sun.nio.ch.SocketChannelImpl.pollConnected(SocketChannelImpl.java:993)
	at java.base@11.0.10/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:119)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToDaemon(DefaultDaemonConnector.java:269)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.maybeConnect(DefaultDaemonConnector.java:106)
	at org.gradle.launcher.daemon.client.DaemonStopClient.gracefulStop(DaemonStopClient.java:69)
	at org.gradle.tooling.internal.provider.ShutdownCoordinator.stop(ShutdownCoordinator.java:42)
	at org.gradle.tooling.internal.provider.ProviderConnection.stopWhenIdle(ProviderConnection.java:206)
	at org.gradle.tooling.internal.provider.DefaultConnection.stopWhenIdle(DefaultConnection.java:302)
	at org.gradle.tooling.internal.consumer.connection.StopWhenIdleConsumerConnection.stopWhenIdle(StopWhenIdleConsumerConnection.java:38)
	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.stopWhenIdle(ParameterValidatingConsumerConnection.java:78)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor$1.run(LazyConsumerActionExecutor.java:112)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor$1.run(LazyConsumerActionExecutor.java:104)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:130)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.sendStopWhenIdleMessageToDaemons(LazyConsumerActionExecutor.java:104)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.disconnect(LazyConsumerActionExecutor.java:85)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.disconnect(CancellableConsumerActionExecutor.java:50)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.disconnect(ProgressLoggingConsumerActionExecutor.java:72)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.disconnect(RethrowingErrorsConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.disconnect(DefaultAsyncConsumerActionExecutor.java:54)
	at org.gradle.tooling.internal.consumer.DefaultProjectConnection.disconnect(DefaultProjectConnection.java:53)
	at org.gradle.tooling.internal.consumer.DefaultGradleConnector.disconnect(DefaultGradleConnector.java:77)
	at org.jetbrains.plugins.gradle.GradleConnectorService$GradleProjectConnection.disconnect(GradleConnectorService.kt:90)
	at org.jetbrains.plugins.gradle.GradleConnectorService.disconnectGradleConnections(GradleConnectorService.kt:62)
	at org.jetbrains.plugins.gradle.GradleConnectorService.dispose(GradleConnectorService.kt:38)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:138)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:168)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:142)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:130)
	at com.intellij.serviceContainer.ComponentManagerImpl.dispose(ComponentManagerImpl.kt:952)
	at com.intellij.openapi.project.impl.ProjectExImpl.dispose(ProjectExImpl.kt:264)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:138)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:168)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:142)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:130)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$closeProject$4(ProjectManagerImpl.java:377)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$$Lambda$6079/0x000000080427ac40.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:360)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:395)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.closeProjectAndShowWelcomeFrameIfNoProjectOpened(CloseProjectWindowHelper.kt:44)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.windowClosing(CloseProjectWindowHelper.kt:32)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper$2.windowClosing(ProjectFrameHelper.java:219)
	at java.desktop@11.0.10/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop@11.0.10/java.awt.Window.processWindowEvent(Window.java:2086)
	at java.desktop@11.0.10/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop@11.0.10/java.awt.Window.processEvent(Window.java:2045)
	at java.desktop@11.0.10/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop@11.0.10/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop@11.0.10/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop@11.0.10/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop@11.0.10/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop@11.0.10/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop@11.0.10/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base@11.0.10/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.10/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base@11.0.10/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop@11.0.10/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop@11.0.10/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base@11.0.10/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.10/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.10/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.ide.IdeEventQueue$$Lambda$528/0x00000008006d3440.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.ide.IdeEventQueue$$Lambda$527/0x00000008006d4440.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.10/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Should I open new issue @donat ? Thank you.

**Pull request merged**
