### PR TITLE
fix(kotlin-dsl): unable to use `events = setOf()` in testLogging

### PR DESCRIPTION
**Pull request by nbrugger-tgm**
### Context
It fixes a bug that prevents to use `evennts = setOf()` which would be the natural approach for Kotlin DSL. (since EnumSet.of() throws an exception on empty sets)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes. (no user facing change)
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by tresat** [comment]
Thank you for your contribution!

Can you please add some tests to demonstrate and cover your changes.  Is there any particular scenario you are looking to support?

**Comment by nbrugger-tgm** [comment]
Added a unit test.
Its a bug fix so i do not know too well what "particular scenario" i should provide. Using an empty set on the `setEvents` method (default in kotlin dsl) crashes with a Java internal error from EnumSet.

The reason one wants to set an empty `setEvents` is when monitoring tests and so on is purely done via test reports (html/xml) and you don't want the "spam" of failed tests in the cli

**Comment by nbrugger-tgm** [comment]
@tresat

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
