### PR TITLE
Ivy dependency branch support

### PR DESCRIPTION
**Pull request by perrin-metaswitch**
Adds support for declaring branches on Ivy dependencies.

Issue: #1357

### Context

This is a long-standing feature request, in the issue linked above. When using existing Ivy repositories with branches, it is a necessity. 

It turned out to be a lot more involved than simply supporting a `[branch]` field in the Ivy resource patterns. The branch has to be part of the module metadata used in dependency resolution, cache serialization, transitive Ivy dependencies, etc.

### Status

My changes seem to work OK for our projects. I can now declare a dependency like this:
```
    runtime(group="metaswitch", branch="diameter/trunk", name="diameter-base", version="latest.integration", configuration="impl")
```
But it feels like what I've done could be cleaner. (I think there are too many `instanceof` checks for example.)

I didn't want to add a field/accessor for the branch to the core API interfaces, or the default implementations, because this is something Ivy-specific so belongs in Ivy-specific classes. But it was hard to pass the branch to the places it needed to get without doing that. And a lot of the time there was no factory method, and no nice way to decide which type of identifier or selector to create. Hence the somewhat ugly instanceof checks and checks for the existence of a branch scattered throughout.

I've yet to add tests for these changes. I'm creating this PR to get some feedback on what I've done so far (after commenting on the issue). Possibly I've missed some obvious way to implement it more nicely. Perhaps I should have just changed the default implementation classes? I'm very keen to work through whatever is needed to get this into a release.

I am aware of issue #1386, but I decided I needed to focus on branches, at least for this first attempt. It could be that what I've done can be extended into other extra attributes, but I haven't looked at it seriously yet.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by perrin-metaswitch** [comment]
I see my changes have tripped the binary compatibility checks. I think it would be wise to wait for feedback on what I've attempted before looking at what API changes need to be annotated etc.

**Comment by ljacomet** [comment]
The team is quite busy for the moment with the upcoming 6.0 release and this is quite some changes. So expect some delay in getting a comprehensive feedback.

**Comment by perrin-metaswitch** [comment]
We've been running a build from this branch for a while now, as we continue our migration from Ant/Ivy to Gradle. 

We did find a few places where I'd missed adding support for branches, so this pull request has now been updated to fix those.

We also rebased the branch onto master after the 6.0 release, which didn't cause any problems.

What would the next steps be to get this into a release?

**Comment by martinda** [comment]
I keep coming back here because my projects looks like this:
```                                     
                          ,-- 1.0.0-b1
  -- o -- o -- o -- o -- o -- o -- ...
                \                ,-- 1.0.0-b2        ,-- 1.1.0-b2
                  `-- o -- o -- o -- o -- o -- o -- o -- ...
                                           \                ,-- 1.0.0-b3        ,-- 1.0.1-b3
                                             `-- o -- o -- o -- o -- o -- o -- o -- ...
```
And I keep wondering how to make dependency management understand branches.

**Pull request closed without merging**
