### PR TITLE
Remove dead Netbeans link from README

### PR DESCRIPTION
**Pull request by JLLeitschuh**
The link to the Netbeans plugin is dead, and I can't find a replacement.

### CODE REVIEW

**Comment by ljacomet** [comment]
Might be interesting to check a recent Netbeans version and see if there is any kind of bundled Gradle support. If that's the case, simply link to the general Netbeans site. WDYT?

**Comment by eskatos** [comment]
Netbeans now has built-in support for Gradle.
I did not find a resource dedicated to Gradle support in Netbeans but this shows enhancements to the built in support made in Netbeans 12 https://netbeans.apache.org/download/nb120/index.html#_gradle
Linking to the general Netbeans site sounds good to me.

**Comment by JLLeitschuh** [comment]
Fixed, thanks!

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
