### PR TITLE
Update archives and default configuration documentation

### PR DESCRIPTION
**Pull request by jvandort**
Fixes: #17006 

* Update base plugin to add warning not to use archives configuration but instead add task dependencies directly on assemble
* Update samples to not use archives configuration
* Remove documentation references to archives configuration other than in base plugin documentation
* Update `java` plugin doc to reference base plugin docs instead of re-documenting archives and default configurations

Future work: 
Refine [composite build limitations](https://docs.gradle.org/current/userguide/composite_builds.html#included_build_substitution_requirements) - It includes references to the `default` configuration which are likely no longer true. These limitations were [originally](https://github.com/gradle/gradle/commit/340421a4ca32dd1c7aa72f9c02ded86c4ced9f5d) written in gradle 3

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gralde help

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Review by lkasso — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
