### PR TITLE
Remove deprecated class `UnableToDeleteFileException`

### PR DESCRIPTION
**Pull request by donat**
### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation
- [x] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

### CODE REVIEW

**Comment by donat** [comment]
@lptr I've just noticed that the deprecation vas assigned to the Execution team. Is there a reason not to simply delete the class in 7.0?

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by lptr** [comment]
@donat for context I added it to the @gradle/execution team because originally I dealt with the class, and thought we'd be removing it. But this is all fine, please go ahead and remove it.

**Comment by donat** [comment]
Implemented in #15518

**Comment by donat** [comment]
@bot-gradle test rFM

**Review by jjohannes — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Pull request merged**
