### PR TITLE
Use a blocking queue instead of semi-busy wait in daemon log handling

### PR DESCRIPTION
**Pull request by lptr**
`LogToClient`'s `AsynchronousLogDispatcher` shows up as a hotspot in CPU profile snapshots, which can be misleading. It is detected as a hotspot because it implements a kind of semi-busy wait while polling for events: it wakes up from sleep every 10 ms. This is done to avoid having to use `Thread.interrupt()`. The explanation is as follows:

```java
// we must not use interrupt() because it would automatically
// close the connection (sending data from an interrupted thread
// automatically closes the connection)
```

IIUC, this only applies to the actual delivering of events. Here's an attempt to only protect the dispatching from interruption, but not the rest of the code. If this works we can avoid the busy wait and make this code disappear from the hotspot list.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QFL please

**Comment by lptr** [comment]
@bot-gradle test this please

**Comment by lptr** [comment]
@bot-gradle test this please

**Comment by ldaley** [comment]
@melix @oehme Do I recall correctly that you have also tried a similar thing to what @lptr is doing here?

**Comment by melix** [comment]
Yes l did on a local branch, for the same reason (readability of performance graphs). I didn't notice any performance impact but l didn't fully test either.

**Comment by oehme** [comment]
I remember the blocking queue worsening performance, because many different threads write to it. That's why we stuck with the concurrent queue and time-based batching. It won't be a huge deal either way, so if this bit keeps leading people down a profiling rabbit hole, then let's get rid of it.

**Comment by lptr** [comment]
So what shall we do with this? My vote is to merge it.

**Comment by ldaley** [comment]
> So what shall we do with this? 

I have no opinion on that.

**Comment by lptr** [comment]
@melix are you voting to merge this?

**Comment by lptr** [comment]
This is still an issue. I think we can merge this once we reduced the number of useless notifications sent to the client.

**Comment by lptr** [comment]
We still want to do this I think.

**Comment by lptr** [comment]
We still want to do this, but can't until we have so many unnecessary events being pushed to the client.

**Comment by lptr** [comment]
@bot-gradle test RFM.

**Comment by lptr** [comment]
@bot-gradle test RFM.

**Pull request closed without merging**
