### PR TITLE
Move resolution of task mutations to run as a separate node

### PR DESCRIPTION
**Pull request by adammurdoch**
Fixes #?

### Context

Move resolution of task mutations out of `ExecutionPlan.selectNext()` and into worker threads. This work is potentially expensive and can execute user code. Running it in `selectNext()` would block all other threads from starting or finishing nodes, locking or unlocking resources or acquiring or releasing worker leases. Given that dependency resolution can do these things, this also would cause a deadlock when resolving the mutations.

Moving the resolution out addresses these issues, but also has a couple of other important advantages:
- these nodes are dynamically added to the plan, so are a step towards taking coarse grained nodes and exploding them into finer-grained nodes (task nodes are "exploded" into a resolve node and an execute node).
- these nodes run at the correct time to provide a home for other work that "prepares" a task for execution, such as finalizing properties or doing dependency resolution.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
I suppose this fixes https://github.com/gradle/gradle/issues/17013 ?

**Comment by adammurdoch** [comment]
It does.

**Pull request merged**
