### PR TITLE
Set CONSTANT_TIME_FOR_TAR_ENTRIES to epoch + 1 day (#7564)

### PR DESCRIPTION
**Pull request by blop**
Signed-off-by: Olivier Voortman <olivier.voortman@gmail.com>

### Context
Fix for https://github.com/gradle/gradle/issues/7564

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
Hey @blop could you run `ReproducibleArchivesIntegrationTest` and fix the failures?

`./gradlew core:integTest --tests "ReproducibleArchivesIntegrationTest"`

**Comment by wolfs** [comment]
@blop Thank you for your PR. Can you please fix `ReproducibleArchivesIntegrationTest`? See https://builds.gradle.org/viewLog.html?buildId=17198859&buildTypeId=Gradle_Check_Stage_QuickFeedbackLinuxOnly_Trigger for the failures.

**Comment by blop** [comment]
Yes, will do :)

**Comment by big-guy** [comment]
Thanks @blop.  This'll be in Gradle 5.1

**Pull request merged**
