### PR TITLE
Simplify PatternSpec caching

### PR DESCRIPTION
**Pull request by oehme**
Instead of one global cache that all patterns share,
there is now one cache per pattern. This removes the need
for an extra cache key object and also makes each cache
smaller. Together this reduces memory usage and speeds up
lookups.

### CODE REVIEW

**Comment by oehme** [comment]
I ended up with this after trying to remove the caching completely, as it adds quite a bit of memory usage. There is only once scenario (`nativeMonolithicOverlapping`) where caching seems to be faster than just running the specs again.

**Comment by oehme** [comment]
I looked deeper at that `nativeMonolithic` project and I think the only reason it benefits from that cache so much is that all the source files in each project have the same name. I.e. there is  `project1/src1.cpp`, `project2/src1.cpp`, ... So there are only ~200 relative paths in that project even though it has 20K files. That means we might be measuring an unrealistic speedup with that cache in that project.

**Comment by oehme** [comment]
We always have lots of exclude patters (all the default ANT excludes) and for Java we have `**/*.java`. So the native examples are definitely not the only ones.

**Comment by wolfs** [comment]
@oehme IIUC, we removed the `**/*.java` include for the Java compile task. The default exclude patters are in place.

**Comment by oehme** [comment]
The Java include is [here](https://github.com/gradle/gradle/blob/f71d8d69a1f1e031d6ffd105664da0ce9440f04b/subprojects/plugins/src/main/java/org/gradle/api/internal/tasks/DefaultSourceSet.java#L57).

**Pull request merged**
