### PR TITLE
Version catalog clean ups

### PR DESCRIPTION
**Pull request by ljacomet**
* Clean up package names
* Use a feature preview to enable catalog support
* Remove plugin support in TOML file
* Clean up accessor generation

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Review by melix — APPROVED** [review]
Changes LGTM, provided you fix the failing tests of course :)

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Pull request merged**
