### PR TITLE
Test for encoding problems and fix a few on Linux and macOS

### PR DESCRIPTION
**Pull request by lptr**
The overarching goal here is to shake out more encoding problems throughout Gradle by running all our integration tests in a way that the tested code has to deal with non-ASCII characters in file paths. This PR takes a step towards that goal by forcing all our non-Windows integration tests to use such a path.

To keep the scope manageable, this PR does not force non-ASCII paths for Windows. That needs to be enabled in a followup PR where we can deal with Windows-specific encoding problems.

The idea is similar to how we add a space to the `build/tmp/test files` directory's name where all the test output is typically located; this time we replace the `s` in `test files` with an `ŝ` (see [U+015D](https://www.compart.com/en/unicode/U+015D)). Importantly this character is not part of ASCII nor any ISO-8859-X codepage, and cannot be represented by a single byte. (See [Wikipedia](https://en.wikipedia.org/wiki/ŝ)).

There is also an escape hatch for tests that for some reason can't support Unicode paths; these need to be tagged with `@DoesNotSupportNonAsciiPaths`. We have such offenders today:

  - Checkstyle fails because of this bug: https://github.com/checkstyle/checkstyle/issues/13012
  - Java 6 wrapper tests fail because Java 6 barfs on non-ASCII characters in the path

Most of the problems that had to be fixed for Unixes come from the fact that `URI.toString()` does not encode non-ASCII characters, and some tools can't parse string representations of URIs with non-ASCII characters in them.

So some of the `URI`s are now converted to strings using `toASCIIString()` instead. This is the canonical form of a URI, and is the intended way to go when the string form is passed to places where we can't ensure that it will be read with the right encoding (see https://www.w3.org/Addressing/URL/3_URI_Choices.html)

There are followups:
- https://github.com/gradle/gradle/pull/25316
- https://github.com/gradle/gradle/issues/25322

This PR is a followup to the daemon encoding fix in:
- https://github.com/gradle/gradle/pull/25319

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test AFT please.

**Comment by lptr** [comment]
@bot-gradle test RFN please.

**Comment by lptr** [comment]
@bot-gradle test this please.

**Comment by lptr** [comment]
@bot-gradle test this please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test this please.

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test APT

**Comment by lptr** [comment]
I switched from `ș` (s with comma under) to `ŝ` (s with circumflex) on the suggestion of @blindpirate that it's easier to distinguish from the regular `s`.

**Review by asodja — APPROVED** [review]
❔ So I checked some cases:
```
URI uri = new URI("file://tmp/teŝt-files");
System.out.println(uri); // => file://tmp/teŝt-files
System.out.println(uri.toASCIIString()); // => file://tmp/te%C5%9Dt-files
System.out.println(new URI(uri.toASCIIString())); // => file://tmp/te%C5%9Dt-files
uri.equals(new URI(uri.toASCIIString())); // => false
uri.equals(new URI(URLDecoder.decode(uri.toASCIIString()))); // => true
```

What is then correct way to transform URI to a string and then back from a string to URI (e.g. for serialization)?

**Comment by lptr** [comment]
> What is then correct way to transform URI to a string and then back from a string to URI (e.g. for serialization)?

Using `toASCIIString()` gives you a _canonical_ string representation of the URI. It's also the variant that works best when passing it to external consumers we can't trust with using the right encoding, as described here: https://www.w3.org/Addressing/URL/3_URI_Choices.html.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Pull request merged**
