### PR TITLE
Remove deprecated isIncludePrivate method from GroovyDoc for Gradle 8.0

### LINKED ISSUE #21657: Remove @Deprecated Groovydoc.IncludePrivate

### PR DESCRIPTION
**Pull request by tresat**
Fixes #21657

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]

**Review by octylFractal — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
