### PR TITLE
Replace state machine based plugins block parser by a combinator based parser

### PR DESCRIPTION
**Pull request by bamboo**
And add optimization for `kotlin-dsl` plugin accessor.

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test APT

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test APT

**Comment by jbartok** [comment]
Same approach badly needed in [PrecompiledScriptPlugin](https://github.com/gradle/gradle/blob/4b9db4ee7779571397532df4ef4d2866ed60dac5/subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/PrecompiledScriptPlugin.kt#LL139C11-L139C11) too.

**Comment by hfhbd** [comment]
What about adding an optimization for `embeddedKotlinVersion` too:
```
plugins {
  `kotlin-dsl`
  kotlin("plugin.serialization") version embeddedKotlinVersion
}
```

**Comment by eskatos** [comment]
@bot-gradle test APT

**Review by eskatos — APPROVED** [review]
Let's ship this!

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
