### PR TITLE
Let wrapper jar contain Apache License LICENSE file

### PR DESCRIPTION
**Pull request by eskatos**
* Fixes https://github.com/gradle/gradle/issues/14968

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by ov7a — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle cancel

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Review by mlopatkin — APPROVED** [review]
:tada: cool! Thank you for working on this!

**Review by lkasso — APPROVED** [review]

**Pull request merged**
