### PR TITLE
Resolve relative paths to Toolchain installations relative to root project location

### LINKED ISSUE #19193: Paths specified via org.gradle.java.installations.paths are not resolved relatively to the project root directory
When specifying a relative path through the Gradle property `org.gradle.java.installations.paths`, it is not resolved relatively to the project root directory, but relatively to the current working directory of the Gradle daemon process.

The underlying problem is likely caused by `org.gradle.jvm.toolchain.internal.LocationListInstallationSupplier` using `new File(..)` to resolve the directory. According to the [Gradle documentation on Working with Files](https://docs.gradle.org/7.3.1/userguide/working_with_files.html#sec:single_file_paths), `new File(relative path)` should never be used (in build configurations) as it can lead to unexpected behavior:
> Never use `new File(relative path)` because this creates a path relative to the current working directory (CWD). Gradle can make no guarantees about the location of the CWD, which means builds that rely on it may break at any time.

### Expected Behavior
Paths specified through the Gradle property `org.gradle.java.installations.paths` are resolve relatively to the project root directory.

### Current Behavior

Paths specified through the Gradle property `org.gradle.java.installations.paths` are resolve relatively to the current working directory of the Gradle daemon process.

### Context

We're trying to use the Java toolchain feature with a JDK that is provisioned dynamically through a configuration the Gradle build script. URLs to snapshot versions of a JDKs for multiple platforms are checked into Git together with the project source code. A custom task downloads and unpacks the correct JDK to a build directory. Previously, we just configured the JDK path on the `CompileOptions` of the `JavaCompile` task and created a task dependency on the JDK provisioning task. To use the toolchain support, we moved to the provisioning task to the `:buildSrc` project as the toolchain detection already expects the JDK to exist during configuration time (that's not great but ok).

But there doesn't seem to be a way to specify the URL to download or the directory of the pre-provisioned JDK directly through the toolchain APIs. Currently, setting the JDK path through `org.gradle.java.installations.paths` only works when specifying an absolute path, so the information would always need to be injected from outside the build, even though a relative path to the project root directory would suffice. `org.gradle.java.installations.fromEnv` has the same issue.

### Steps to Reproduce 

Add the following configuration to a simple Java Gradle build:
```
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=relative/path/to/jdk
```
Run the Gradle Java build or just the `javaToolchains` task:
```
$ ./gradlew javaToolchains
> Task :javaToolchains

Directory '/home/user/.gradle/daemon/7.3/relative/path/to/jdk' (system property 'org.gradle.java.installations.paths') used for java installations does not exist
 + Options
     | Auto-detection:     Disabled
     | Auto-download:      Disabled
```

### Your Environment

```
------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.13 (Red Hat, Inc. 11.0.13+8)
OS:           Linux 5.14.15-200.fc34.x86_64 amd64
```

Note that the relative path resolution behavior seems to be different depending on the Java version that is used to run Gradle (specified through `JAVA_HOME` for the Gradle wrapper). With JDK 8, `org.gradle.java.installations.paths` is resolved relatively to the directory where the Gradle wrapper is started from (if necessary with `-p` to set the project root directory). But that just underlines that the current behavior is inconsistent and unexpected.

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #19193

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Review by hegyibalint — APPROVED** [review]
Nice work, got no remarks or questions; it's pretty clear what's happening here.

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Review by ljacomet — APPROVED** [review]
LGTM!

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
