### PR TITLE
Remove some @Incubating annotations

### PR DESCRIPTION
**Pull request by jbartok**

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Review by ljacomet — APPROVED** [review]
LGTM!

And nice to see that we do not need to approve the API changes explicitly.

**Comment by ljacomet** [comment]
@xaviarias Here is an example of `@Incubating` removal, even simpler that what I explained

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
