### PR TITLE
Clickable headers p2

### PR DESCRIPTION
**Pull request by pledbrook**
Gives easy access to the direct URLs for sections of the user guide from within the guide itself.

### CODE REVIEW

**Comment by bmuschko** [comment]
@big-guy I remember that you [cherry-picked a related change](https://github.com/gradle/gradle/commit/7b10a127277f2bf6dd81f61ca8500e8de8ef5cf8) into the "release" branch. Can you comment on whether this change is complimentary?

**Comment by pledbrook** [comment]
@bmuschko The cherry-picked commit conflicts with this PR as both the CSS and the XSL changes are different.

**Comment by big-guy** [comment]
@bmuschko agree with Peter.  It conflicts, but it's a better/superset of the other change.

@pledbrook can you update your copy of the docs on http://pledbrook.github.io/gradle/userguide.html with this change?

**Comment by pledbrook** [comment]
@big-guy What's on GitHub Pages currently corresponds to this and the other pull request (for TOC per chapter) combined.

**Comment by big-guy** [comment]
Shouldn't there be a license appendix?

**Comment by pledbrook** [comment]
Yes, good point. I've republished. You may need to refresh a few times to see the new appendix entry in the TOC.

**Comment by bmuschko** [comment]
@big-guy Thanks for the clarification.

**Comment by breskeby** [comment]
merged into master

**Pull request closed without merging**
