### PR TITLE
Fix contradictions in Working with files doc

### PR DESCRIPTION
**Pull request by 6hundreds**
Fixes https://github.com/gradle/gradle/issues/20857
See also discussion at forum https://discuss.gradle.org/t/confusing-doc-on-working-with-files/42996

### CODE REVIEW

**Review by eskatos — APPROVED** [review]
LGTM :+1:

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by 6hundreds** [comment]
@bot-gradle test and merge

**Pull request merged**
