### PR TITLE
Enable load-after-store for docs tests

### PR DESCRIPTION
**Pull request by alllex**
Most of the tests that started to fail after enabling of load-after-store are failing due to tasks running in parallel or in different order due to being isolated.

In the majority of the cases, `allow-disordered-output: true` was enough to fix the test. A few tests are not supported by the CC, so they were filtered out in the build file.

### CODE REVIEW

**Comment by alllex** [comment]
@bot-gradle test this

**Comment by alllex** [comment]
@bot-gradle test this

**Review by abstratt — APPROVED** [review]
Looks good, Alex, thanks!

**Comment by alllex** [comment]
@bot-gradle test and merge

**Pull request merged**
