### PR TITLE
Support for gradle wrapper distribution mirror

### PR DESCRIPTION
**Pull request by samrocketman**
I don't plan to develop this further until someone from the gradle team provides feedback.

### Context

I first [opened a discussion on the Gradle forums][discuss] back in May 6th, 2018.  I hadn't seen any activity one way or another.  The full context can be read there.

I feel this is a very relevant feature for any company who desires to use gradle in significant capacity.  It makes sense for a company to mirror sources of download for all of their project dependencies.  Gradle through Gradle wrapper is no different from that desirable perspective.

Hopefully, this is up to snuff for the Gradle devs.  Nobody from the development team responded to my original forum post before I did this work.

[discuss]: https://discuss.gradle.org/t/support-for-gradle-wrapper-distribution-mirror/26838

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by marcphilipp** [comment]
Thanks for creating the issue and sorry for not responding to your forum post!

Have you considered simply checking in the `gradle.properties` file with the URL that points to your mirror?

How do you populate the mirror with distributions?

**Comment by samrocketman** [comment]
Hi @marcphilipp , I'm aware of `gradle.properties` file containing the URL.  Right now I use something along the lines of
```bash
if [ -x ./gradlew ]; then
  sed -i.bak 's#\(distributionUrl=\)https\\://[^/]\+\(.*\)#\1https\\://nexus.example.com\2#' gradle/wrapper/gradle-wrapper.properties
  ./gradlew clean check
  # or whatever the user overrides with
fi
```

> How do you populate the mirror with distributions?

I tend to manage Sonatype Nexus Repository Manager 3 (Nexus for short) in my environments.  Nexus has a feature in which it can create a [raw proxy to remote URLs](https://help.sonatype.com/repomanager3/raw-repositories-and-maven-sites#RawRepositoriesandMavenSites-ProxyingandGroupingRawRepositories).

So I can create a raw proxy to `https://services.gradle.org/` and then by using the `sed` command above swap out the URL and we cache all binaries downloaded from Gradle.

This has a couple of benefits.

1. Internet outages out of our control are less likely to affect our software development lifecycle.
2. By proxying and caching we're not abusing Gradle services which means our usage of gradle is not an expensive transfer cost for the Gradle project.

Perhaps it would help if I give some context and background.

# Context and background

I manage a build and deployment automation environment for an entire company.  It's typically my role at any company I go to now a days.  In any case, what this means in terms of mirroring gradle is that there are thousands of projects which may use gradle _if the project owner chooses it_.

That is to say, it's not really scale-able for me to open a PR on thousands of projects to update their Gradle URLs.  So for now the `sed` command works.

However, in general other build tools provide a means to define mirrors in which binaries can be bootstrapped so we set this in those configurations.  It would be nice if Gradle did, too.

I feel like I found the appropriate place to define where the mirror should override.  What are your thoughts on it?

**Comment by ddimtirov** [comment]
> services.gradle.org is backed by a CDN. Are you certain your internal mirror has a better uptime/availability?

For many orgs reaching out to internet is simply not an option, so you have to go to internal mirror in all cases. As WAN networks often are slow, if you have dispersed team you typically have multiple mirrors with different URLs. 

I've implemented equivalent patch in 2 different companies already, and without it the gradle adoption would have been an order of magnitude more painful.

**Comment by ddimtirov** [comment]
See also https://github.com/ddimtirov/gwo-agent for agent-based implementation that you can apply on stock Gradle Wrapper (requires env variable)

**Comment by samrocketman** [comment]
@ddimtirov that’s a neat alternative.  I’ll try it out.  It’s unfortunate that mirroring is not taken more seriously by the gradle project which is attempting to be an enterprise build tool solution replacing Maven.

**Comment by flstaats** [comment]
Just a comment on an alternative approach we use.  On our CI servers instead of invoking the Gradle Wrapper we have our Jenkins pipeline inspect the gradle/wrapper/gradle-wrapper.properties file and extract the version of Gradle requested by the build and map it to a Jenkins tools preinstalled version of Gradle which is put on the path.  This gives us a redirection point to catch the requested version of Gradle but saves us the overhead of installing multiple copies and a filter to prevent unapproved versions in our production builds.

**Comment by sgleske-ias** [comment]
@marcphilipp 

> services.gradle.org is backed by a CDN. Are you certain your internal mirror has a better uptime/availability?

It's not about availability or uptime.  It's about quality control.  Large businesses do not like to rely on infrastructure outside of their control for release pipelines.  If you go to any company that is larger than 1000 employees and ask, "do you guys cache dependencies for your release pipelines?" most of the time the answer is "yes" in my experience.

Caching provides a few benefits:

- Uptime and availability is more within the scope and control of the team managing the caching server.  It's the same reason why some companies decide to go with GitHub enterprise rather than rely on github.com uptime (as an example).  Arguably github.com is more available than an on-premise GitHub Enterprise but it is not subject to the same attack surface or risks involved with using github.com as a service.
- If the source goes down (i.e. Gradle CDN), gets deleted, or is compromised (hacked binaries get uploaded or replaced within Gradle CDN) it will not affect the cached release pipeline.  The primary purpose is to preserve the integrity.  This doesn't protect a cache from pulling in a hacked dependency but doesn't hurt it if it already has cached the known good version.
- When building within cloud infrastructure, if your caching infrastructure lives inside of the same infrastructure as your build and release pipelines you typically do not get charged for transfer.  This is more of a cost-saving measure which matters when you've got more than 5000 projects regularly pulling down dependencies for builds within ephemeral environments.  Gradle wrapper bootstrapping Gradle is a solid example of a dependency that gets pulled down during build time.

**Comment by samrocketman** [comment]
@marcphilipp 

> services.gradle.org is backed by a CDN. Are you certain your internal mirror has a better uptime/availability?

It's not about availability or uptime.  It's about quality control.  Large businesses do not like to rely on infrastructure outside of their control for release pipelines.  If you go to any company that is larger than 1000 employees and ask, "do you guys cache dependencies for your release pipelines?" most of the time the answer is "yes" in my experience.

Caching provides a few benefits:

- Uptime and availability is more within the scope and control of the team managing the caching server.  It's the same reason why some companies decide to go with GitHub enterprise rather than rely on github.com uptime (as an example).  Arguably github.com is more available than an on-premise GitHub Enterprise but it is not subject to the same attack surface or risks involved with using github.com as a service.
- If the source goes down (i.e. Gradle CDN), gets deleted, or is compromised (hacked binaries get uploaded or replaced within Gradle CDN) it will not affect the cached release pipeline.  The primary purpose is to preserve the integrity.  This doesn't protect a cache from pulling in a hacked dependency but doesn't hurt it if it already has cached the known good version.
- When building within cloud infrastructure, if your caching infrastructure lives inside of the same infrastructure as your build and release pipelines you typically do not get charged for transfer.  This is more of a cost-saving measure which matters when you've got more than 5000 projects regularly pulling down dependencies for builds within ephemeral environments.  Gradle wrapper bootstrapping Gradle is a solid example of a dependency that gets pulled down during build time.

**Comment by marcphilipp** [comment]
@samrocketman Understood, thanks for the explanations!

@big-guy Could you please take a look at this?

**Comment by big-guy** [comment]
Thanks for your contribution. I'm sorry we didn't get back to you in a reasonable amount of time.  At the moment, we're not planning to support a feature like this.

**Comment by samrocketman** [comment]
Unfortunate, but thanks for considering.

**Comment by samrocketman** [comment]
Cross linking this helpful comment which has a suggested grade configuration for developers who use and upgrade grade to use a mirror.

https://github.com/gradle/gradle/issues/4210#issuecomment-361946301

**Comment by sgleske-ias** [comment]
@big-guy any chance this feature would be reconsidered?  Our CI pipelines have gone through an outage because of Gradle distribution mirror issues and our general advice internally is to switch the wrapper `distributionUrl` (or we can roll out a preprocessor which uses `sed` to substitute the file).

This general feature seems to be a regular desire in my experience.

Note: this is my proprietary GitHub profile; samrocketman is my open source profile for when I develop on my own time.

**Pull request closed without merging**
