### PR TITLE
Allow hexadecimal groovy versions Issue: #2623

### PR DESCRIPTION
**Pull request by MeneDev**
### Context
Allows to use snapshot versions of groovy (i.e. via jitpack.io)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by DerMene** [comment]
I am not 100% comfortable with this change. The GroovyJarFile version will be 0.0.0 if it cannot be parsed with GroovyJarFile.parse. That is not a change compared to previous version, however that may have implications I cannot see. 

One implication I can see is in GroovyRuntime.java line 103: if the major version is >= 2 add groovy-ant to bring in Groovydoc. That won't work for snapshots. But maybe that's a different bug altogether.

**Comment by DerMene** [comment]
I feel you. This would also fix the problem with the wrong version reported by the GroovyJarFile instance. I'd be in favor of looking into the jar, but I cannot foresee the performance drag caused. If someone "official" says that's the way to go, I'd be happy to implement it.

**Comment by bigdaz** [comment]
@melix Any way forward here?

**Comment by big-guy** [comment]
Sorry, we're not going to merge this as-is.  I think instead of relaxing the expected version, it would be better to find another way to determine the Groovy version that didn't require sniffing the jar name--perhaps by invoking `groovy.lang.GroovySystem#getVersion` via reflection of the given classpath in `GroovyRuntime`. 

Thank you for interest!

**Pull request closed without merging**
