### PR TITLE
Compress Gradle runtime jars

### PR DESCRIPTION
**Pull request by bmuschko**
### Context

There's no good reason I can think of why we should turn off compression for the runtime JARs. This change enables default compression which creates JARs with roughly half the size as before. It will also save some disk spaces for users of multiple Gradle versions in parallel or in an upgrade scenario.

__Before change:__

gradle-api JAR: 99.1MB
gradle-testkit JAR: 86KB

__After change:__

gradle-api JAR: 41MB
gradle-testkit JAR: 41KB

Branch build: https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_Stage_BranchBuildAccept_Trigger&branch_Gradle_Check=bm%2Fcompress-runtime-jars&tab=buildTypeStatusDiv

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs

### CODE REVIEW

**Comment by ldaley** [comment]
@bmuschko the speed at which they are generated is more important than the size. If this makes generation noticeably slower we should reevaluate.

**Comment by melix** [comment]
Regarding speed, it could improve using the same technique as in #2774. Maybe we should ship the 2 in the same version, we would have smaller size *and* faster.

**Comment by jjohannes** [comment]
I started another performance test agains the latest nightly. There are quite a few performance improvements on master at the moment which have not been rebased yet. I just want to see how this change performs in directly comparison to current master.
https://builds.gradle.org/viewQueued.html?itemId=7883085

**Comment by ldaley** [comment]
Any performance regression won't show unless we are particularly testing for this scenario, which is first resolve of `gradleApi()` for a gradle version/home.

**Comment by jjohannes** [comment]
Right. @bmuschko can you check if we can add a performance test for this? Or find another way to measure the speed impact of the change?

**Comment by bmuschko** [comment]
We already have a performance test in place: [GradleImplDepsPerformanceIntegrationTest](https://github.com/gradle/gradle/blob/master/subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/impldeps/GradleImplDepsPerformanceIntegrationTest.groovy). However, I noticed that the time measured for the generation of the JAR files is off. Currently, the generation of JAR files is triggered independent of its actual use in the build. I logged the issue https://github.com/gradle/gradle/issues/2815 for it. The tests would need to be adjusted and the issue would potentially need fixing.

I did some preliminary measurements for just the code that's responsible for the generation of the JARs. It is a bit slower. For the Gradle API JAR roughly 2 secs, for the Gradle TestKit JAR roughly 10 ms. 2 seconds doesn't sound too bad to me for a one-time generation.

__Before change:__

gradle-api JAR: ~5000-5500 ms
gradle-testkit JAR: ~20-30 ms

__After change:__

gradle-api JAR: ~6700-6900 ms
gradle-testkit JAR: ~29-32 ms

**Comment by bmuschko** [comment]
@jjohannes @ldaley Do you think it's worth pursuing this? I am probably going to close this PR if we are not on the same page.

**Comment by jjohannes** [comment]
I think I would lean towards **not** making the change as speed should always be the main concern. I see that the impact might be small, but I also do not see an urgent need to reduce the size of the jar(s).

**Comment by bmuschko** [comment]
> I think I would lean towards not making the change as speed should always be the main concern.

Fair enough. Can't argue with that.

> ...urgent need to reduce the size of the jar(s).

Many customers complain about the size of the cache in general and that it is never purged. That's a bigger discussion though. With this change I tried to make things a little bit better at least.

**Comment by lptr** [comment]
Did we measure how much slower/faster it becomes to _use_ the generated JARs? I mean, we generate it somewhat slow in the beginning, but having to read half as much data from disk could make things faster in subsequent builds.

**Comment by bmuschko** [comment]
> Did we measure how much slower/faster it becomes to use the generated JARs?

You make a good point. I haven't measured that.

**Pull request closed without merging**
