### PR TITLE
Wordsmithing Improvements to "What is Gradle?"

### PR DESCRIPTION
**Pull request by tresat**
Suggests some tweaks for the What is Gradle section.  I really like the overall direction of the change.

### CODE REVIEW

**Review by lkasso — APPROVED** [review]
Very happy with this update. Thank you @tresat. 

Good catch on the "built" typo.

New favorite line:
> while effortlessly benefiting

**Comment by tresat** [comment]
> New favorite line:
> 
> > while effortlessly benefiting

Effortlessly might be me *slightly* overselling it. 😛

**Comment by lkasso** [comment]
Removing "effortelessly" would be better. It will feels less like an advert.

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
