### PR TITLE
Added a preferProjectModules option to ResolutionStrategy

### PR DESCRIPTION
**Pull request by idlsoft**
Thank you very much for your contribution. We highly appreciate the time
and effort you put into pull request. Before you submit the pull request,
please:

- [x] Review the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Sign the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [ ] Ensure basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [x] Before submitting a pull request, you started a discussion on the
[Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev)
or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [x] You considered writing a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. You can find [samples](https://github.com/gradle/gradle/tree/master/design-docs)
in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [ ] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
you ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by idlsoft** [comment]
This is a replacement for https://github.com/gradle/gradle/pull/631 and https://github.com/gradle/gradle/pull/564

**Comment by bigdaz** [comment]
Thanks a lot for the PR, and for your patience as we come up with an acceptable solution.

I should be able to take a look at this next week. In the meantime, my main feedback is that the one integration test is not consistent nor easy to read: it combines coverage for  'force' on a dependency declaration and a dependencySubstitution rule for projects, but doesn't actually provide any coverage for "dependency resolve rules" even though it lives in `DependencyResolveRulesIntegrationTest`.

Here are some suggestions:
- I think in general it's ok to assume that the various dependency resolution rules will do their job to get the correct modules provided into conflict resolution: the test coverage for this feature should focus on the effect of `preferProjectModules` on the resolution.
- The exception is the `force` attribute that is put directly on a dependency declaration: Gradle provides a special conflict resolver for this case, and we should have test coverage for it. 
  - The `preferProjectModules` attribute does not trump the `force` attribute on the dependency. 
  - Note that this is quite different from the `ResolutionStrategy.force()`
  - There is no equivalent `force` option for a project dependency.
- The `force` attribute can also be in a dependency declared in a published Ivy module. We should have test coverage that resolves such an Ivy module and shows that `preferProjectModules` does not override this `force` attribute.
- Any coverage using `dependencySubstitution` rules should be split out and put into `DependencySubstitutionRulesIntegrationTest`

**Comment by idlsoft** [comment]
The permutations in the unit-test reflected the gradle-dev discussion, so various aspects of dependency management got lumped together as a result.

I'll try to find some time to split them.

**Comment by idlsoft** [comment]
I took another look at the test, and while I agree that it mixes the responsibilities of `DependencySubstitutionRulesIntegrationTest ` and `DependencyResolveRulesIntegrationTest ` there is only one case out of six that belongs in `DependencyResolveRulesIntegrationTest`.
There is some beauty in having all the permutations related to `preferProjectModules` in one place, maybe separating it from both makes sense?

It'll be just one method with 6 permutations, but will get to avoid duplication.

**Comment by idlsoft** [comment]
This is done now, the tests have moved to a separate class.

**Pull request closed without merging**
