### PR TITLE
GRADLE-2208 Provide a default config file for checkstyle plugin

### PR DESCRIPTION
**Pull request by stavytskyi**
I think we should change default checkstyle version. A lot of rule from [google config file](http://checkstyle.sourceforge.net/google_style.html) was commented by me because checkstyle 5.7 doesn't provide its.

### CODE REVIEW

**Comment by ben-manes** [comment]
If Gradle upgrades the dependency, then please use the google config file bundled into the jar. That way improvements will be automatically available instead of Gradle maintaining its own style. This is [what I do](https://github.com/ben-manes/caffeine/blob/master/gradle/code_quality.gradle) after setting the `toolVersion` and have not had any compatibility problems so I think an upgrade is safe.

**Comment by stavytskyi** [comment]
@ben-manes as I understand `gradle` fetch `checkstyle` tool from maven central repo so dependency only related to default configuration. Anyway `checkstyle.jar` isn't delivered with `gradle`. When you apply `checkstyle` plugin in your script grade looks to which tool it needs to download from repo. Without `repositories.mavenCentral()` you cannot run checkstyle tasks. In current pull request I have disabled all rules which is not supported by version 5.7. But if we decide to change `toolVersion` to higher we can uncomment rules too. So I think this decision should take grade team. Either leave old version of `checkstyle` with restricted `google style` or increase the version and uncomment rules.

**Comment by stavytskyi** [comment]
Dear colleagues, could you give feedback about the pull request? Currently I don't understand does project need this change or not? If not why you don't reject pull request and didn't close(reject) issue in the Jira. Could somebody explain contribution flow?

**Comment by alkemist** [comment]
Hi @stavytskyi ,

Apologies for the delay in responding. We are currently overwhelmed with pull requests, and right now have little discretionary time to allocate to incorporating them. That is, we have other hard commitments which have to take priority. That said, one month without any response is inexcusable.

We are currently working on prioritising and setting up a better process for working with contributions in a timely manner. Unfortunately, the queue is somewhat long. 

We appreciate your contribution and hope you can allow us a little more time.

**Comment by bigdaz** [comment]
Thanks @stavytskyi. I've made some comments on your commits. One thing that's missing is some integration test coverage for the case when the user doesn't provide a checkstyle config file. You'd need to add some test cases to `CheckstylePluginIntegrationTest` or add another test case like it.

**Comment by bigdaz** [comment]
Hi again @stavytskyi. I'm very sorry it took so long to get back to you with initial feedback.

If you're interested in taking this pull request further, please respond to my comments on the code.

**Comment by stavytskyi** [comment]
Hi @bigdaz I'm going to review your comment in couple of days and I will answer to you.

**Comment by stavytskyi** [comment]
Hi @bigdaz I have reviewed your comments. Could you give me your feedback, please?

**Comment by pioterj** [comment]
@stavytskyi The Gradle team doesn't currently have the capacity to deal with all pull requests in a timely fashion. We expect this situation to be temporary. We ask for patience in the meantime.

**Comment by mark-vieira** [comment]
@stavytskyi could you please address @bigdaz's latest comment? Also, there look to be test failures when this is merged against what is currently in master. We'll need to address the lingering questions above, address these test failures and add the requested integration test coverage before merging.

https://builds.gradle.org/viewLog.html?buildId=500744&tab=buildResultsDiv&buildTypeId=Gradle_PullRequest_LinuxJava17withSanityChec

**Comment by stavytskyi** [comment]
Hi @mark-vieira, I will try to review and fix the problem during this week.

**Comment by mark-vieira** [comment]
Just click "Log in as a guest" if you're asked for credentials. Guest users have the ability to view build results.

**Comment by pioterj** [comment]
@stavytskyi I'm closing this pull requests for now as we haven't heard from you for a month and a half. If you wish to continue working on this, feel free to re-open it once you address the comments or have additional questions.

**Pull request closed without merging**
