### PR TITLE
Remove restriction on subgroups for version catalog for platform, enforcedPlatform, testFixtures and variantOf

### LINKED ISSUE #18229: Allow version catalog sub-accessors for platform, enforcedPlatform, test-fixtures and variantOf
Currently using sub-accessors for `platform, enforcedPlatform, test-fixtures and variantOf` do not work.

### Expected Behavior
```
   dependencies {
        implementation(libs.myLib)
        implementation(platform(libs.myLib.bom))
    }
```

Works, there is no compilation/runtime issue.

### Current Behavior
```
   dependencies {
        implementation(libs.myLib)
        implementation(platform(libs.myLib.bom))
    }
```
Fails with error:
```
> Cannot convert the provided notation to an object of type Dependency: org.gradle.accessors.dm.LibrariesForLibs$MyLibLibraryAccessors@2492f6fb.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().
```

### PR DESCRIPTION
**Pull request by asodja**
Fixes #18229

I found another bug with sub-accessors. Looks like platform, enforcedPlatform, testFixtures and variantOf do not work currently.

Few more methods added to DependencyHandler.

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test QFL

**Review by ljacomet — APPROVED** [review]
Good catch!

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
