### PR TITLE
Avoid creating dependency locking handler eagerly in script handlers

### PR DESCRIPTION
**Pull request by big-guy**
We have special code to avoid the creation of ConfigurationContainers,
but creating a dependency locking handler implicitly creates a configuration
container.

This may have a small performance improvement with many scripts.

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
LGTM!

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
This isn't a big enough improvement to worry about right now.

**Pull request closed without merging**
