### PR TITLE
Warn cli option

### PR DESCRIPTION
**Pull request by mkobit**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [ ] Before submitting a pull request, I started a discussion on the [Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev),
      the [forum](https://discuss.gradle.org/) or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I considered writing a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [x] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [x] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by mkobit** [comment]
I realized after this that I should make an additional change for the output when the build fails and it displays text to the user to enable `--stacktrace`, `--info`, or `--debug`. It probably makes sense to also include `--warn`.

**Comment by mkobit** [comment]
I thought it would make sense to add the `--warn` to the outputs I mentioned above. Looking at it now, it doesn't fit because those outputs are around producing more log output, not less.

I think this is ok for review for https://github.com/gradle/gradle/issues/935

**Comment by eriwen** [comment]
@mkobit Thank you very much for the PR. 

There's still a major user concern unaddressed by this (through absolutely no fault of yours) that Gradle does not configure and route logs from subprocesses properly. 

I am speccing significant improvements to logging, and they make this change obsolete.

Are you good if we close this, with our full appreciation? Is there any particular need you must address in this area now?

**Comment by mkobit** [comment]
@eriwen definitely fine with closing it.

Was using it as the first opportunity to kinda dive into the Gradle source as it seemed like a fairly simple fix, and hopefully make a contribution. I don't have an immediate need for it.

I'll keep an eye out for a different issue to jump on.

**Comment by eriwen** [comment]
@mkobit That is very honorable all the way around. You can always check the [`help-wanted` label](https://github.com/gradle/gradle/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Ahelp-wanted%20) if you like. I'm looking forward to your future contributions :)

**Comment by eriwen** [comment]
@mkobit It seems that the logging changes I mentioned earlier won't be implemented soon, so I'm going to resurrect/merge this change in the meantime.

**Pull request closed without merging**
