### PR TITLE
Update FileReferenceFactory.java

### PR DESCRIPTION
**Pull request by petersg83**
Add a missing comma to toString().

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged.

**Comment by bmuschko** [comment]
@petersg83 Did you actually sign the CLA? I couldn't find you in our list. What's the name you use?

**Comment by petersg83** [comment]
Hi,
It's now done. Tell me if you still don't find me.

**Comment by bmuschko** [comment]
Just got it, thanks!

**Comment by petersg83** [comment]
You're welcome !

**Pull request merged**
