### PR TITLE
Let Kotlin DSL source path calculation properly look into `platforms/`

### PR DESCRIPTION
**Pull request by eskatos**
* Fixes https://github.com/gradle/gradle/issues/27405

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by jbartok — APPROVED** [review]
LGTM

**Review by ov7a — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle merge

**Pull request merged**
