### PR TITLE
Replace dependency kotlin-stdlib-jdk8 with kotlin-stdlib

### PR DESCRIPTION
**Pull request by quaff**
`kotlin-stdlib-jdk8` is merged into `kotlin-stdlib` since 1.8.0. 
See https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target

### CODE REVIEW

**Review by lkasso — APPROVED** [review]
Ok for docs.

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by quaff** [comment]
@bot-gradle test this

**Comment by quaff** [comment]
I can not built it locally, please trigger a build.
```
Calculating task graph as no configuration cache is available for tasks: :plugin-development:configCacheIntegTest
Type-safe project accessors is an incubating feature.

> Configure project :build-logic-commons:code-quality-rules
Kotlin DSL property assignment is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/zhouyanming/workspace/gradle/build-logic/settings.gradle.kts' line: 24

* What went wrong:
Error resolving plugin [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.4.0']
> A problem occurred configuring project ':build-logic-commons:commons'.
   > Dependency verification failed for configuration ':build-logic-commons:commons:classpath'
     One artifact failed verification: gradle-kotlin-dsl-plugins-4.1.0.jar (org.gradle.kotlin:gradle-kotlin-dsl-plugins:4.1.0) from repository Gradle Central Plugin Repository
     If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file. For more on how to do this, please refer to https://docs.gradle.org/8.3/userguide/dependency_verification.html#sec:troubleshooting-verification in the Gradle documentation.
     
     Open this report for more details: file:///Users/zhouyanming/workspace/gradle/build/reports/dependency-verification/at-1692751393517/dependency-verification-report.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

```

**Comment by jbartok** [comment]
@bot-gradle test this

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
