### PR TITLE
Remove log4j and commons-io jars from documentation snippets

### PR DESCRIPTION
**Pull request by eskatos**
Using empty jars for fictive libraries instead.

* Supersedes https://github.com/gradle/gradle/pull/23403
* Fixes https://github.com/gradle/gradle/issues/23378

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test BD

**Comment by eskatos** [comment]
@bot-gradle test BD

**Comment by eskatos** [comment]
Rendered preview available at https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/60155060:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20230106114239%2B0000/docs/userguide/migrating_from_ant.html#migant:filesystem_deps

**Review by jbartok — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
