### PR TITLE
Add a PowerShell version gradlew

### PR DESCRIPTION
**Pull request by FantasqueX**
PowerShell is a modern shell for Windows. A script written in PowerShell is more readable than the same one written in bat.

Closes https://github.com/gradle/gradle/issues/21081

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by cobexer** [comment]
Thank you for your interest in Gradle.

We cannot accept the PR as is, because the wrapper scripts are generated files.

The script needs to be added as a template to the application plugin in https://github.com/gradle/gradle/tree/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins

Then the `application` plugin needs to optionally generate the PowerShell script and the `wrapper` task may want to expose that option as well.

If you are interested in doing that let us know so we can confirm with the team responsible for that area that the approach would be accepted.

**Comment by FantasqueX** [comment]
@cobexer Hi, thanks for your response. I'm interested in changing the `application` plugin.

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
@gradle/bt-jvm would you be ok with adding an optional PowerShell version of the startup script?
***
@FantasqueX please wait for confirmation before investing time into a proper implementation.

**Comment by big-guy** [comment]
We're not opposed to a Powershell script to be generated for the application distributions.  

There are several questions that need to be answered before we continue this:
- Will we be deprecating/removing the batch file option eventually?
- Will powershell scripts be expected to work on non-Windows too?
- These scripts are also used for the Gradle wrapper, so should we also add powershell for it?

In addition, we'll need integration tests that show the powershell scripts work.

We think that discussion should happen in the issue and not here, so we're going to close this PR.

**Comment by FantasqueX** [comment]
@big-guy Hi, is there any issue opened to discuss those things you mentioned?

**Comment by jvandort** [comment]
#21081

**Pull request closed without merging**
