### PR TITLE
Bump checkstyle version

### LINKED ISSUE #14906: Upgrade checkstyle to make text block(JEP-378) support available.
Please upgrade checkstyle to make text block(JEP-378) support available. 
As I see in https://github.com/checkstyle/checkstyle/issues/7103 checkstyle had issue related to text block fixed in `8.36` and current version supported by gradle is `8.35`

### Expected Behavior
Code with textblocks should not fail to pass checktyle.

### Current Behavior
Checkstyle report parsing issues like:

```
Caused by: MyClass.java:**:**: expecting RPAREN, found '"
                sting in text block
                line 2 of text block
"'
```
 or  
 ```
MyClass.java:**:**: expecting SEMI, found '"
                sting in text block
                line 2 of text block
"'
```

### Context
This blocks me from using hava 15 text blocks feature.

### PR DESCRIPTION
**Pull request by logart**
to support JEP-378 https://openjdk.java.net/jeps/378

Fixes #14906 

### Context

This will unblock using textblocks from java 15+

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ljacomet** [comment]
@logart Can you please make sure you do the sign off of your proposed contribution? Otherwise we cannot accept it.

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by JLLeitschuh** [comment]
@logart please amend your comits so they are signed off

**Comment by ljacomet** [comment]
`8.37` has been released, will open another PR for this.

Closing this one as obsolete, replaced by #15252 .

**Pull request closed without merging**
