### PR TITLE
Allow to configure auxclasspath for PMD

### PR DESCRIPTION
**Pull request by jsotuyod**
- The property is called classpath for consistency with FindBugs

### CODE REVIEW

**Comment by alkemist** [comment]
Great, thanks.

Have you signed the CLA? http://gradle.org/contributor-license-agreement/

**Comment by jsotuyod** [comment]
Yes I did, last Friday.

**Comment by alkemist** [comment]
Great, thanks.

**Comment by jsotuyod** [comment]
Any feedback on this? Is there somehow I can help move this forward?

**Comment by alkemist** [comment]
Hi Juan,

We'll need some kind of test coverage to verify that this actually works.

I'm also wondering if we should match the name of the property, i.e. call it auxclasspath.

**Comment by jsotuyod** [comment]
@alkemist thanks for the reply.

[I did ask on the mailing list for pointers as to how to test this a week ago](https://groups.google.com/forum/#!topic/gradle-dev/Qrk-6sfkEIs) but got no replies. I looked at similar properties and found no tests either. The best I can come out with is "set the property, run PMD and see it doesn't break", but not if the ant task is actually seeing the property properly defined (I have done manual tests to make sure of this, but nothing that can fit nicely into a unit test, since using the android checks for PMD would require the whole Android SDK just to build Gradle).

If just doing a "set it and make sure it doesn't break" is enough for you, I can have it right away.

I have no issue renaming the property, I was just trying to be consistent with other code quality plugins. [FindBugs ALSO has an `auxclasspath` variable, wich is set through the `classpath` config var](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/findbugs/FindBugsSpecBuilder.java#L185) but whatever you guys are comfortable with.

Please let me know and I can have everything changed and ready by tomorrow at most.

**Comment by alkemist** [comment]
> I did ask on the mailing list for pointers as to how to test this a week ago but got no replies.

Sorry, I missed that.

> If just doing a "set it and make sure it doesn't break" is enough for you, I can have it right away.

Not quite, we have to make sure it actually does what it is supposed to. What's the difference in the result when this property is set correctly and when it isn't? We should be able to write an integration test for this pretty easily. 

> I have no issue renaming the property, I was just trying to be consistent with other code quality plugins. FindBugs ALSO has an auxclasspath variable

That's a good enough reason (i.e. consistency) to keep it as it is.

I didn't realise that FindBugs has something analogous (which makes sense now I understand what this property actually is). We'll have to wire this in through the source set in the same way.

https://github.com/gradle/gradle/blob/release/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/FindBugsPlugin.groovy#L115-115

**Comment by jsotuyod** [comment]
> Not quite, we have to make sure it actually does what it is supposed to. What's the difference in the result when this property is set correctly and when it isn't? We should be able to write an integration test for this pretty easily.

None directly visible in the `pmd.xml` file. The classpath is available for PMD rules that want to determine the hierarchy of a class, allowing for instance to determine if your class extends from [`android.app.Activity`](http://developer.android.com/intl/es/reference/android/app/Activity.html) even when this is defined in the Android SDK, and not on your own code.

The best you can get is that some rules start reporting issues they would miss without it. I don't know of any other ruleset other than Android that uses this, but I confess I haven't researched it.

> I didn't realise that FindBugs has something analogous (which makes sense now I understand what this property actually is). We'll have to wire this in through the source set in the same way.
> 
> https://github.com/gradle/gradle/blob/release/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/FindBugsPlugin.groovy#L115-115

No problem, I can do that. For Android it will be useless  (since Android plugin doesn't use standard Java sourceset yet), but may be usefull for someone else (or when Android plugin gets fixed).

**Comment by jsotuyod** [comment]
Confirmed. Only Android rules are currently relying on the `auxclasspath`. Requiring the Android SDK to build Gradle is certainly not an option.

The alternative would be to find (or write) a custom rule in a plugin to set to PMD through `pmdClasspath` and make sure the rule reports new issues when the `classpath` is properly set...

I feel like writing a rule, and having Gradle build it into a jar for another test to pass is a little bit too much... Having the jar directly into the project as a test resource would be easier, but I'm no fan of having a binary blob in the repository...


On another topic, I just added the automatic classpath config just like FindBugs, and added a test for it.

**Comment by alkemist** [comment]
> I feel like writing a rule, and having Gradle build it into a jar for another test to pass is a little bit too much... Having the jar directly into the project as a test resource would be easier, but I'm no fan of having a binary blob in the repository...

I've got no idea how hard it is to write a rule. If it's just java, then this wouldn't be too hard to wire together as the rule would just be another project in the build.

**Comment by jsotuyod** [comment]
Just to make sure I''m understanding correctly. You would like me to add a directory under `subprojects` called `pmd-test-rules` or something of the sort, that would contain a gradle module generating a jar, and have the `code-quality` test suite depend on such project, to include that jar into a PMD run and check the generated results. Right?

If so, I can write a rule that will directly report a specific error if the classpath is defined, and have it run with / without the classpath and check for the report results.

**Comment by big-guy** [comment]
I think what @alkemist is trying to say is your integration test could be a multi-project build where the rule comes from one project and the other project uses PMD + the first project's jar on the auxclasspath.

**Comment by big-guy** [comment]
Here's an example of a multi-project integration test: https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/ProfilingIntegrationTest.groovy

You'd write out a settings.gradle that included your 'rule-using' and 'rule' project.  Then you can put everything else in the build.gradle in the root to build them both and add the 'rule' project to 'rule-using' project's auxclasspath.  Then write out the source files, then run the PMD task in the 'rule-using' project looking for success/failure.

**Comment by jsotuyod** [comment]
@big-guy thanks for your repy, sory I couldn't get to it earlier.

I'm still not sure if my code for both the 'rule-using' and 'rule' projects would have to be actual files I check in in this PR and have those modules as dependencies for my test, or be embeded in the integration test as are those in https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/PmdPluginIntegrationTest.groovy#L188 and have those generate the jar as part of the integration test.

Thanks in advance.

**Comment by bigdaz** [comment]
The best way to develop an integration test would probably be to first develop a sample build that demonstrates the use of `auxclasspath`, without any external dependencies. This sample would:
- Have a `projectA` that defines some additional classes/rules required by PMD, and compiles them into a Jar
- Have a second `projectB` that runs PMD, adding the jar output of `projectA` to the new PMD classpath variable.
- When `:projectB:pmd` is executed, there should be way to tell if the correct stuff is in the classpath: task failure, rule failure, whatever.

Once you have this sample project, it won't be hard to convert it into an integration test: there are a few ways to provide the source files to the test case, either by embedding the source directly in the test case, or by including them as resources.

**Comment by jsotuyod** [comment]
Done! Added an integration test that builds a rule and configures it. It checks it works for the newly autoconfigured classpath, and it fails to detect the violation if the classpath is cleared.

Hope that's good enough, but let me know if it isn't.

**Comment by bigdaz** [comment]
Thanks. We'll get onto this pretty soon.

**Comment by big-guy** [comment]
Thanks @jsotuyod 

This will be in Gradle 2.8.  I simplified your integration tests to just detect if the auxclasspath was set/not set.

**Comment by jsotuyod** [comment]
@big-guy awesome! Thanks!

**Pull request merged**
