### PR TITLE
Apply polish to artifact selection

### PR DESCRIPTION
**Pull request by jvandort**
While browsing this code to learn how it works, I felt it was difficult to reason about. This PR removes a layer or two of indirection and cleans up some other stuff along the way

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test apt

**Review by ghale — APPROVED** [review]
This seems fine to me.

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
