### PR TITLE
Update Test Distribution Gradle plugin to 2.1

### PR DESCRIPTION
**Pull request by snoopcheri**
Subject says it all

### CODE REVIEW

**Comment by snoopcheri** [comment]
@bot-gradle test rFM, please

**Comment by snoopcheri** [comment]
The CI Status is red but I assume the reason for this was that the master was red when I've created this PR. All the other checks are green. So I guess it's safe to merge?

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
