### PR TITLE
Normalize APP_HOME in the Windows app start script

### PR DESCRIPTION
**Pull request by sschuberth**
Normalizing an app home like

    C:\app\cli\build\install\ort\bin\..

to

    C:\app\cli\build\install\ort

results in a more readable and shorter path. The latter is especially
useful to shorten the total length of the CLASSPATH variable which uses
APP_HOME to refer to all required JAR libraries. This in turn might help
to avoid running into Windows' command line length limitation when
java.exe is called with CLASSPATH.

Also see the related discussion in issue #1989.

Fixes #?

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by sschuberth** [comment]
Thanks @rieske for updating the test for me!

**Comment by rieske** [comment]
Thank you for the contribution @sschuberth 
After some internal discussions, we are a bit concerned about the use case being solved by this change and would like to get some better understanding first.
Would you mind providing a sample that demonstrates the problem and how this change addresses it?
It would help a lot if you could demonstrate how the fix actually helps improve the size of paths used.

**Comment by sschuberth** [comment]
Sure @rieske, let me quickly provide you with some background information. The underlying issue was reported to our project at https://github.com/heremaps/oss-review-toolkit/issues/1938, and I've worked around it with https://github.com/heremaps/oss-review-toolkit/pull/1939.

While Gradle 6.0 added [Automatic shortening of long command-lines for Java applications on Windows](https://docs.gradle.org/6.0/release-notes.html#automatic-shortening-of-long-command-lines-for-java-applications-on-windows), this does not fully address https://github.com/gradle/gradle/issues/1989 as [the Gradle wrapper still concatenates all JARs to a single string to generate the classpath](https://github.com/gradle/gradle/issues/1989#issuecomment-550192866).

I admit this change is not a full fix, but it helps to shorten the classpath and thus reduces the risk to run into the classpath limit on Windows by shortening all classpath entries from something like

    C:\oss-review-toolkit\cli\build\install\ort\bin\..\lib\config4k-0.4.1.jar

to something like

    C:\oss-review-toolkit\cli\build\install\ort\lib\config4k-0.4.1.jar

So it saves 7 chars per classpath entry, and as a bonus in makes the classpath more readable.

BTW, I decided against fixing the issue by simply using a wildcard for the classpath like I did in my work-around for our project and as suggested [here](https://github.com/gradle/gradle/issues/1989#issuecomment-395001392) for security reasons, because that would also use (potentially malicious) JARs that have been copied to the *lib* directory afterwards.

In any case, I regard this only as an intermediate step towards a full fix.

**Comment by big-guy** [comment]
@rieske this looks like a small enough change that we should accept it as-is, even if it doesn't fix the underlying issue.

**Comment by rieske** [comment]
Thank you @sschuberth!

**Pull request merged**
