### PR TITLE
Create plugins-application project and cleanup plugins project

### PR DESCRIPTION
**Pull request by tresat**
- Extracts much of the remaining code from the plugins project to `plugins-application`.
- Migrates plugin property files remaining in `plugins` to appropriate projects.
- Simplifies `plugins` build and applies `projectHealth` recommendations to it.
- Migrates many integration tests left in `plugins` to more appropriate projects.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
