### PR TITLE
Support third-party templates in build-init plugin.

### PR DESCRIPTION
**Pull request by ajoberstar**
I made a first pass at a spec for this feature. The current structure used within the plugin doesn't seem amenable to third-party use, so I focused on a fairly declarative packaging approach with some examples of how it could be used.

I can formalize it more if this seems like a good approach.

### CODE REVIEW

**Comment by adammurdoch** [comment]
Thanks for writing this up. I've had a read and will start a thread on the dev list soon.

**Comment by bigdaz** [comment]
Hi @ajoberstar. This PR has gotten a bit stale. Are you interested in pursuing this further?

I think the next step would be to update the design spec based on the feedback in the ensuing conversation on the mailing list: https://groups.google.com/forum/#!msg/gradle-dev/GtbxqCxBImw/MiVfPPkFvGwJ

We should come up with some concrete steps to take. It seems like the first thing to do is work on the registration process whereby internal plugins register templates so that they are available for `gradle init`. Then we can open that up to external plugins applied via an init script. This will involve working out what services are supplied to the template generators, and extracting some public APIs for those to use.

Once we have a mechanism for registering a new type of project to init, we can look at making this more feature rich: templating mechanism, user prompting, etc.

**Comment by ajoberstar** [comment]
Hi @bigdaz. I've since drifted on to other ideas/projects that are taking my time for the foreseeable future, so I don't think I'll be able to resume work on this. I will be interested in what comes from this though.

**Comment by bigdaz** [comment]
Thanks for your contributions @ajoberstar. Hopefully it won't be too long before we can dedicate some time to address this feature. When that time comes, this PR and the ensuing conversation will serve as a good starting point.

**Pull request closed without merging**
