### PR TITLE
build-init kotlin template support

### PR DESCRIPTION
**Pull request by dwerner**
Sidenote: this is my first PR against gradle, so please let me know how I can make my patch more appealing 

I wanted a quick way to create a new kotlin project from the command line, and I already know and love gradle.

Create a new project referencing kotlin with:
```gradle init --type kotlin-library```

Cheers,

Daniel

### CODE REVIEW

**Comment by dwerner** [comment]
Sorry, missed the existence of the CLA, have since signed.

**Comment by pioterj** [comment]
Thank you for the pull request. We should receive your CLA soon. Please note that we currently have limited capacity to deal with all pull requests in a timely fashion. This is a temporary situation. We ask for patience in the meantime.

**Comment by pioterj** [comment]
@dwerner We still don't have your CLA. We should have it in our system by now so probably something went wrong. Could you try to sign it again?

**Comment by dwerner** [comment]
Signed and resubmitted the CLA, please let me know if you get it.

**Comment by pioterj** [comment]
We have it now, thanks.

**Comment by iamsteveholmes** [comment]
+1

**Comment by gzoritchak** [comment]
+1

**Comment by pioterj** [comment]
This is something that we would like to support. Would you mind updating the design document at https://github.com/gradle/gradle/blob/master/design-docs/build-initialisation.md? Creating or updating a design document is something that we do at Gradle for all non-trivial changes, especially when changing the behavior or public API. We would like to use the same standards for pull requests. 

This change will need better test coverage before it gets merged.

**Comment by pioterj** [comment]
In addition to the design document, now there are also merge conflicts that needs to be resolved. @dwerner Are you still interested in pushing this forward?

**Comment by pioterj** [comment]
I'm closing this pull request because there was no response from the contributor for almost two months. 

If you are interested in this feature, the best course of action would be to start a discussion on [Gradle Developer List](https://groups.google.com/forum/#!forum/gradle-dev). Instead of adding support for another language to the existing solution we should consider making the Build Init Plugin more extensible.

This is something that was discussed in the past but not finalized: https://groups.google.com/forum/#!msg/gradle-dev/GtbxqCxBImw/MiVfPPkFvGwJ The design proposed in PR https://github.com/gradle/gradle/pull/402 could be a good starting point.

**Pull request closed without merging**
