### PR TITLE
Move ParallelismConfiguration to a public package

### PR DESCRIPTION
**Pull request by ghale**
This moves `ParallelismConfiguration` to a public package so that `StartParameter` is not leaking an internal type.

### CODE REVIEW

**Comment by ghale** [comment]
No, it didn't exist.  I wasn't aware of the aversion to "api" and that package just seemed to make sense.  I'll change it to something else public.

**Comment by ghale** [comment]
Package changed to "org.gradle.concurrent".

**Comment by lacasseio** [comment]
`ParallelismConfiguration` was introduced to communicate the max worker count to the console as we needed to process the CLI flags earlier with the logging flags. Now that we grow the number of work in progress items dynamically, we don't really have a need to communicate that information. Depending on where we want to move in the future for the console, we could get rid of the changes around `ParallelismConfiguration` and revert to what we had previously.

@eriwen @bmuschko Do you have an idea if this is required for the future? More importantly, how do we plan to shrink the number of work-in-progress items (if we plan to do so)?

**Comment by lacasseio** [comment]
For reference, I just saw https://github.com/gradle/gradle/issues/2411 which this work could be part of if we decide to revert the change. PR https://github.com/gradle/gradle/pull/1554 is where the `ParallelismConfiguration` and all the piping to connect to the console was introduced. If we revert, we should also revert most of the change in the PR.

**Comment by oehme** [comment]
@lacasseio this is no longer only used for the console, but also for the worker API.

**Comment by ghale** [comment]
Unfortunately, there aren't really any existing public packages in `baseServices` that are not under "api".  I've added the new package to docs.  

Frankly, I don't see a lot of advantage or disadvantage to this being a public interface (i.e. we need to expose these methods on `StartParameter` either way) so I'm not highly opinionated about whether we should instead just remove the `extends`.  If you feel strongly about it, let me know your reasoning.

**Pull request merged**
