### PR TITLE
Fixes #11180, ProjectLayout will resolve directories in expected style.

### LINKED ISSUE #11180: ProjectLayout.dir seams to not resolve relative to directory
`Directory` relative resolving is broken when using `ProjectLayout.dir`.
Some how resolving a directory and then resolving a directory of this directory results in resolving from project root directory instead.

### Expected Behavior
```java
final Provider<File> provider = testProject.provider(() -> testProject.file("win/client_installer"));
testProject.getLayout().dir(provider).get();
//<project>\win\client_installer
 testProject.getLayout().dir(provider).get().file("icon.ico");
//<project>\win\client_installer\icon.ico
```
`Directory.dir` is expected to resolve relative to previous Directory. 

### Current Behavior
```java
final Provider<File> provider = testProject.provider(() -> testProject.file("win/client_installer"));
testProject.getLayout().dir(provider).get();
//<project>\win\client_installer
 testProject.getLayout().dir(provider).get().file("icon.ico");
//<project>\icon.ico
```
But current behavior is that `Directory.dir` aquired by `ProjectLayout.dir` still resolves relative to project directory. 

### Context

Use of  `Directory.dir` is not consistent all over Gradle. Looks like the FileResolver does not use the correct path. 

DefaultProjectLayout:
``` java
@Override
public Provider<Directory> dir(Provider<File> provider) {
    return new AbstractMappingProvider<Directory, File>(Directory.class, Providers.internal(provider)) {
        @Override
        protected Directory mapValue(File file) {
            return new FixedDirectory(projectDir.fileResolver.resolve(file), projectDir.fileResolver, fileCollectionFactory);
        }
    };
}
```
The resolver sould be relative to the resolved directory.
``` java
@Override
public Provider<Directory> dir(Provider<File> provider) {
    return new AbstractMappingProvider<Directory, File>(Directory.class, Providers.internal(provider)) {
        @Override
        protected Directory mapValue(File file) {
            final File resolved = projectDir.fileResolver.resolve(file);
            return new FixedDirectory(resolved, projectDir.fileResolver.newResolver(resolved), fileCollectionFactory);
        }
    };
}
```

### Steps to Reproduce 

- get a `Project` instance
- call `ProjectLayout.dir()`
- call `dir` on resolved `Directory` again
Resolving does not happen on first `Directory`, but instead on project root.

### Your Environment

Gradle Version: 6.0-rc-1
Build scan URL:

### PR DESCRIPTION
**Pull request by scholzi100**
Fixes #11180
Continues #11245 (closed by accident)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by lacasseio** [comment]
That is an awesome fix. We will need an test so we can accept this PR. Do you think you can help with that?

**Comment by scholzi100** [comment]
As mentioned in #11245 "I will try." I just need to figure out how to write a compliant agroovy test.

**Comment by scholzi100** [comment]
@big-guy will it still make it into 6.2 RC1?

**Comment by scholzi100** [comment]
@lacasseio any changes required on my side?

**Comment by lacasseio** [comment]
@scholzi100 I asked @big-guy to look into merging this soon. Thanks for the PR.

**Comment by scholzi100** [comment]
Fixed with 5b66952a6982a19fce964caa5cac3312e5633ecf

**Pull request closed without merging**
