### PR TITLE
Remove deprecated SourceDirectorySet methods

### PR DESCRIPTION
**Pull request by rieske**
https://github.com/gradle/gradle/issues/17151

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test this

**Review by nathan-contino — APPROVED** [review]
LGTM

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
