### PR TITLE
Implement proper `ValueSnapshot` for arrays of primitives

### PR DESCRIPTION
**Pull request by bamboo**
Instead of encoding them as Java serialized snapshots.

Follow-up to #27598 and final step in implementing #26596
### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by bamboo** [comment]
@bot-gradle test

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Comment by bamboo** [comment]
@bot-gradle clean

**Review by asodja — APPROVED** [review]
LGTM

**Comment by bamboo** [comment]
Thanks, @asodja!

**Comment by bamboo** [comment]
@bot-gradle merge

**Pull request merged**
