### PR TITLE
ApplicationPlugin configurability

### PR DESCRIPTION
**Pull request by bashnesnos**
Hello,
Just thought it might be useful to make ApplicationPlugin configuration a bit easier. Basically, it's hard because the root spec in CopySpec is immutable in terms of the child specs manipulation. Say, if I want to have an application plugin structure other than 
````
/whatever
|-- /bin
|-- /lib
````
I can't do that without full replacement of installApp, distZip/Tar task and createStartScripts too due to hardcoded default applicationDistribution CopySpec. I've implemented another task which will take care of that re-configuration if it's configure closure is triggered. If the task is not there, then it falls back to the defaults like before the change.

E.g. the script before the proposed change (which is ok as a work around for installApp, but something like that would need to be done to distZip too):
````groovy
installApp {
	applicationDistribution.with copySpec {
		from(processResources) {
			includeEmptyDirs = false
		}
		from(startScripts) {
			fileMode = 0755
		}
	}

	if(project.hasProperty('installDir')) {
		destinationDir = new File(installDir)
		cleanInstallDir.delete destinationDir.getAbsolutePath()
		clean.dependsOn(':cleanInstallDir')
	}

	doLast {
		new File("${destinationDir.getAbsolutePath()}/bin").deleteDir()
	}

}

startScripts {
	mainClassName = "bla.bla.bla.Main"
	classpath += files('/config')

	doLast {
		def windowsScriptFile = file getWindowsScript()
		def unixScriptFile = file getUnixScript()
	 	windowsScriptFile.text = windowsScriptFile.text.replace('%APP_HOME%\\lib\\config', '%APP_HOME%\\config').replace('set APP_HOME=%DIRNAME%..','set APP_HOME=%DIRNAME%')
	 	unixScriptFile.text = unixScriptFile.text.replace('$APP_HOME/lib/config', '$APP_HOME/config').replace('cd "`dirname \\"$PRG\\"`/.." >&-','cd "`dirname \\"$PRG\\"`" >&-')
	}
}
````
And after:
````groovy
configureDist {
	applicationBinDir = "."
	applicationDistribution.with {
		from(processResources) {
			includeEmptyDirs = false

		}
	}
}

installApp {
	if(project.hasProperty('installDir')) {
		destinationDir = new File(installDir)
		cleanInstallDir.delete destinationDir.getAbsolutePath()
		clean.dependsOn(':cleanInstallDir')
	}
}

startScripts {
	mainClassName = "bla.bla.bla.Main"
	classpath += files('config')
}
````
The last bit with 'config' dir to classpath addition relates to GRADLE-2333

### CODE REVIEW

**Comment by bashnesnos** [comment]
Hi Luke,

It's been a while, but I've done more digging and more nice changes so why not to resurrect this pull request.

Here is the changelist:
- CreateStartScripts now extends Copy
    - Adding custom templates allowed (GRADLE-2299)
    - Adding custom tokens allowed
- Ability to add folders to a generated script's classpath
- Ability to rename 'lib' and 'bin' directories (GRADLE-2333)
- Integration test for the plugin
- Quoting JVM opts passed in CreateStartScripts is customizable now (GRADLE-3084)

Basically, CreateStartScripts will have two copy specs - one for windows scripts, the other for unix scripts with default templates added initially. Each spec whould have it's own FilterReader implementation basing on StarScriptGenerator. So we'll have the benefits of execution time initialization rather than during configuration - because CreateStartScript task instance would be passed to a FilterReader with all the relevant parameters.

This allowed to introduce custom templates, custom tokens, and custom JVM opts quoting via a closure. E.g.:
     
            startScripts {
                mainClassName = 'Ok'
                defaultJvmOpts = ['-Dmyopt=']
                quoteJvmOpts { system, jvmOpt ->
                    switch(jvmOpt) {
                        case '-Dmyopt=': return system.equals('nix') ? (jvmOpt + '\$MY_ENV_VAR') : (jvmOpt + '%MY_ENV_VAR%')
                        default: return jvmOpt
                    }
                }
                token 'myprop', 'myvalue'
                classpath += files('config')
                windowsStartScripts.from('src/main/resources/scripts') {
                    exclude('myscript')
                }
                windowsStartScripts.exclude('**/windowsStartScript.txt')
                unixStartScripts.from('src/main/resources/scripts') {
                    exclude('myscript.bat')
                }
                unixStartScripts.exclude('**/unixStartScript.txt')
            }

And if you omit all that (except mainClassName, it's behaviour is the same), it will work fine with defaults.

FilterReader implementations are unit tested the same way StartScriptGenerator is and they literally use it to process files, so they should be reliable. New and old ways to run the plugin integration tested, so we should be safe here too. It proves changes are backwards compatible, so applying refactored plugin should be painless and seemless.

All the added fields/classes have documentation/comments.

Let me know your thoughts.

**Comment by breskeby** [comment]
Hey Alexander,
thanks for all your work and coming back to us with this. I'll have a look on this pull-request soon!
cheers,
René

**Comment by bashnesnos** [comment]
Hi Rene,

Any news on this one?

**Comment by breskeby** [comment]
Hey Alexander

As Luke already suggested we should introduce a new extension here instead of pushing all the customization functionality in the StartScripts tasks. So instead of configuring the generate start scripts task directly the new application configuration api might be looking a bit more like this:
    
    application {
         mainClassName = "SomeGeneralMainClass" // in synch with applicationName convention property
         applicationName = "SomeCustomApplicationName" // in synch with mainClassName convention property
         startScripts {
                mainClassName = 'Ok'
                defaultJvmOpts = ['-Dmyopt=']
                quoteJvmOpts { system, jvmOpt ->
                    switch(jvmOpt) {
                        case '-Dmyopt=': return system.equals('nix') ? (jvmOpt + '\$MY_ENV_VAR') : (jvmOpt + '%MY_ENV_VAR%')
                        default: return jvmOpt
                    }
                }
                ...
            }
    }

Once we have this extension in place we can use this extension to configure the according tasks. At one point we might be able to deprecate the application plugin convention properties

**Comment by bashnesnos** [comment]
No worries, I'm glad it's moving on.

So you're saying we should introduce an application plugin extension and keep the existing convention and in-task configuration abilities (which would possbily be deprecated later).

Adding the extension on top of that shouldn't be that hard (though we would need to define config precedence rules like 'in-task' > 'extension' > 'convention').

Anything else concerning the added features/implementation details?

**Comment by breskeby** [comment]
for the precedence rules I would be fine with latest change wins for now. I guess start script templates we can simplify the api for now by just referencing a file object.

**Comment by dr3amr2** [comment]
Hey there, just a random guy stopping by, who's interested in the features that @bashnesnos implemented.  Are there any plans to fix the merge conflicts and pull into the main gradle repo any time soon?

**Comment by bmuschko** [comment]
@bashnesnos Thanks for providing the pull request. Some of the provided functionality already exists in Gradle (naming the ability to use custom templates). Some of the other functionality and the implementation approach is still in [discussion](https://groups.google.com/forum/#!msg/gradle-dev/DM_x73w_m1U/z668-E1vuoEJ). That's why we won't merge your pull request as is. If you'd like to move forward, please join into the conversation on the Gradle dev list and we'll take it from there.

**Pull request closed without merging**
