### PR TITLE
Creating configuration from code quality plugins produces a non-consumable configuration

### LINKED ISSUE #21760: Update AbstractCodeQualityPlugin.createConfigurations to become an error in Gradle 8
Configurations should be resolvable only.

### PR DESCRIPTION
**Pull request by tresat**
Fixes #21760

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Review by big-guy — APPROVED** [review]

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
