### PR TITLE
Backport to 6.9: Fix renaming project directory causing lost file system notifications on Windows

### LINKED ISSUE #17950: Backport to 6.9: Renaming and recreating the project directory causes Gradle to lose track of changes on Windows
Backport the fix for https://github.com/gradle/gradle/issues/17865 to the 6.9.x stream.

This means backporting https://github.com/gradle/gradle/pull/17922.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by lptr**
Fixes #17950

It's a backport of PR https://github.com/gradle/gradle/pull/17922.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test RFM please.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by blindpirate** [comment]
@bot-gradle test and merge please.

**Comment by blindpirate** [comment]
@bot-gradle test and merge please.

**Comment by blindpirate** [comment]
@bot-gradle test and merge please.

**Comment by blindpirate** [comment]
@bot-gradle test and merge please.

**Comment by blindpirate** [comment]
@bot-gradle test and merge please.

**Pull request merged**
