### PR TITLE
Merge release7x into release

### PR DESCRIPTION
**Pull request by jvandort**
Ensures the 7.6 regression fixed in https://github.com/gradle/gradle/pull/23246 is included in 8.0

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test rfn

**Comment by jvandort** [comment]
@gradle/bt-support Please merge at your discretion.

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
