### PR TITLE
docs: Remove extra spaces before footnote symbols to fit in viewer on Part 5 of tutorial

### PR DESCRIPTION
**Pull request by tyknkd**
Due to a large number of character spaces, the footnote symbols (e.g., `// <1>`) do not fit within the code viewer of the web page when viewed in a Chrome browser on Ubuntu 22.04 machine at standard resolution (https://docs.gradle.org/current/userguide/partr5_build_scripts.html). The user must scroll horizontally to view them. 

Reducing the number of character spaces between the code and the footnote symbol, similar to other pages within the same tutorial remedies this (e.g., https://docs.gradle.org/current/userguide/partr4_settings_file.html#partr4_settings_file).

### Context

Users will be able to see the footnote symbol together with the code without having to scroll back and forth horizontally.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

(NB: Cannot locate tasks that match ':platforms:quickTest' as project 'platforms' not found in root project 'gradle'.)

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

(This is my first pull request here, so I apologize in advance if I have done things incorrectly or out of order. If I have, please let me know what I can do to correct it. I'm trying my best, and I want to learn.)

### CODE REVIEW

**Comment by tyknkd** [comment]
Here is a screen shot showing the issue:
Screenshot from 2024-01-12 08-07-30

**Comment by lkasso** [comment]
@bot-gradle test BD

**Comment by cobexer** [comment]
Thank you for your contribution!

This PR has a valid DCO. The relevant team for this area will confirm the design of the implementation choices.
***
@lkasso could you confirm this is fine when it's rendered?

**Review by lkasso — APPROVED** [review]
LGTM

**Comment by lkasso** [comment]
@bot-gradle merge

**Pull request merged**
