### PR TITLE
Check if distribution url is reachable

### PR DESCRIPTION
**Pull request by StefMa**
### Context
See https://github.com/gradle/gradle/issues/6137.

TBH I'm not quite sure if this the right/best solution to do so.
If you have a better idea please tell me 👍 

I also don't know how to mock this away from the tests... 🤔 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] ~Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective~
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by StefMa** [comment]
Hey @big-guy thanks for the comment 👍 
There is really a lot to think about 🤯.

From my point of view - and as a Gradle user - the most used argument is `--gradle-version` only (and maybe the `--distribution-type`). What I want to say is that I think we shouldn't care about the `gradle-distribution-url` argument because this is something what only "expierenced" Gradle users do. And I think they do it with care (know that the URL is reachable). That is also the reason why I only added the check to the "gradle-version case".
But of course - adding a check for these cases make also sense. But with low priority.

> maybe it would be worth spending time on something else (better errors, making it easier to upgrade so you're not dealing with versions at all).

When I read this I think about to change the `wrapper` task (running with **no arguments**) to something like the `init` task. Where we get a selection of all available Gradle versions and the user can pick the one he want to use.
I know there is somewhere at gradle.org a json with all the available version. Maybe we could parse these and display the versions... 
What do you think about this solution?
Would be a great solution especially for beginners. Who don't know which versions are available...
Could you please give me a link to the URL? That would be great :)

**Comment by eskatos** [comment]
@StefMa, see http://services.gradle.org/, especially "Version Information"

**Comment by StefMa** [comment]
Thank you Paul.
What do you think about this solution? Is it worth to implement?

**Comment by big-guy** [comment]
@StefMa I've just come back around to this PR.  I'm trying to work off the backlog of community PRs and respond a bit quicker than we have before. 

This is what I think we should do to make Gradle a little bit better:

1. As part of `Wrapper.generate()`, check if the URL is reachable. If it's not, fail the task with a useful message.
   - Add an integration test to `WrapperGenerationIntegrationTest` that passes an unreachable URL as the distribution URL (e.g., http://always.invalid`) and check that the build fails with a useful message and does not modify any other files.  "generated wrapper scripts for given distribution URL from command-line" is a good place to start.
2. As part of `Download.downloadInternal()`, make the message for an invalid distribution URL nicer.
   - Add an integration test to `WrapperUpgradeIntegrationTest` that generates a working project and then modifies the gradle-wrapper.properties to a "bad" URL and tries to use it.  Verify that the nicer message is produced.

Please keep in mind that the distribution URL doesn't necessarily mean HTTP.  It could be a file:// 

How does that sound? Thanks for your help in advance.

**Comment by big-guy** [comment]
I'm going to close this PR for now.  Please feel free to submit a new one based on my [comment above](https://github.com/gradle/gradle/pull/8406#issuecomment-504604517)

**Pull request closed without merging**
