### PR TITLE
Add support for generating HTML reports to the Checkstyle plugin

### PR DESCRIPTION
**Pull request by sschuberth**
The committed XSL file was taken from [1].

[1] https://svn.apache.org/repos/asf/hive/trunk/checkstyle/checkstyle-noframes-sorted.xsl

### CODE REVIEW

**Comment by breskeby** [comment]
Hey Sebastian,
thanks for this pull request. Being tired navigating through xml files, I like the idea of having html support for checkstyle. We're currently quite busy with a quite long backlog, so it might take some time to get a detailed review of your PR. 
cheers,
René

**Comment by sschuberth** [comment]
BTW, this PR partly addresses [GRADLE-2209](https://issues.gradle.org/browse/GRADLE-2209) in the sense that it equalizes the Checkstyle plugin with the PMD plugin by creating both XML and HTML reports by default.

**Comment by sschuberth** [comment]
@breskeby More than one month later, now that Gradle 2.7 has been released, do you think there is some time to review this PR so it will make it for Gradle 2.8?

**Comment by sschuberth** [comment]
Another month has passed and Gradle 2.8 has been released without this PR even being initially reviewed.

**Comment by alkemist** [comment]
Thanks for your patience and persistence. This will be in 2.10. We missed the window for 2.9.

**Pull request merged**
