### PR TITLE
Turn validation warning into error: missing task dependency

### PR DESCRIPTION
**Pull request by lptr**
Turn this validation warning into an error: https://github.com/gradle/gradle/blob/e1e47198f0c7c1d82e69f6d12b3259edf629721a/subprojects/core/src/main/java/org/gradle/execution/plan/MissingTaskDependencyDetector.java#L168-L181

See https://github.com/gradle/gradle/issues/21648

### CODE REVIEW

**Review by asodja — APPROVED** [review]
LGTM

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Review by asodja — APPROVED** [review]
LGTM

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Pull request merged**
