### PR TITLE
Prepare Java 10-specific builds similar to Java 9 setup

### PR DESCRIPTION
**Pull request by bmuschko**
### Context

See https://github.com/gradle/gradle-private/issues/1066 for more information. I believe @donat already installed JDK 10 on all agents. Can't find the coresponding issue anymore.

I wasn't quite sure `JvmVersion.java8`. That seems to be wrong already for `TestCoverage(TestType.java9Smoke, OS.linux, JvmVersion.java8)`.

### CODE REVIEW

**Comment by jjohannes** [comment]
The `JvmVersion` parameter was originally used for the version we run the build with. Now we run all builds with Java8. And the parameter is used to say which version to use to run the tests.
So yes it should be Java9 now.

But there must also be some hackery in the Gralde build. Because the tests actually run with Java9 now already.
I think these PRs from @eskatos fix that. Wait until they are merged again, before continuing here:
- https://github.com/gradle/gradle/pull/3756
- https://github.com/gradle/gradle/pull/3755

I think then we should do this:
- Add `JvmVersion.java9` and `JvmVersion.java10`
- Run the test type `java9Smoke` for both. We can maybe rename that to reflect that it is for all versions `java9+`. Or did you already introduce a `java10Smoke` in the Gradle build? The only difference to a calling the normal `integTest` is that it excludes some tests we know are not working for Java9.
https://github.com/gradle/gradle/blob/47fa1358f5efca71fa5a122a4554893b61474198

If we are serious about this, I think we should also re-evaluate that list and see if all tests still fail. And also if some pass again with java10. (I assume more tests will fail and there will be more follow up work). Therefore, I would not put this into the normal pipeline yet. Because the tests might fail and suddenly master is broken. My suggestion would be to add this to a later stage first. Maybe to _Release Accept_.

**Comment by eskatos** [comment]
I just opened the two required cleanup PRs:

- https://github.com/gradle/gradle/pull/4164
- https://github.com/gradle/gradle/pull/4165

**Comment by bmuschko** [comment]
> If we are serious about this, I think we should also re-evaluate that list and see if all tests still fail. 

This will happen in a follow-up issue: https://github.com/gradle/gradle-private/issues/1079

> My suggestion would be to add this to a later stage first. Maybe to Release Accept.

I'll move it there then though I don't see a big difference. Broken is broken. ;-)

**Comment by bmuschko** [comment]
@jjohannes Do my changes look about right now? I wasn't quite sure if we should _just_ use the smoke tests for Java 10 for now.

**Comment by bmuschko** [comment]
@jjohannes Thanks for your comment. I think I will just create a completely new PR. I also closed the other PR as the merging would take some time to figure out.

> So I would probably keep it in "Release Accept" for now. But we can discuss that separately.

I think I am going to just at job but not hang it into the pipeline for now.

**Pull request closed without merging**
