### PR TITLE
Groovy and Scala support for central repository declaration

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
Added a commit that also enables init scripts to modify `settings.dependencyResolutionManagement`

**Review by jjohannes — APPROVED** [review]
👍

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Pull request merged**
