### PR TITLE
Restructure LocalComponentMetadata

### PR DESCRIPTION
**Pull request by jvandort**
This PR updates `DefaultLocalComponentMetadata` and `DefaultLocalConfigurationMetadata` to be much more immutable, removing their `BuildableX` interfaces. Instead, the configuration data is provided by a `ConfigurationMetadataFactory` which is supplied at component metadata construction. An eager implementation of this factory is used for configuration cache and a lazy implementation is used for for local configurations via a `ConfigurationsProvider`. 

This PR further splits a `DefaultLocalConfigurationMetadata`, by separating the _defined_ dependencies into a separate caching mechanism, so that now we no longer need to create this metadata for dependency configurations, as they are not exposed outside of the component metadata. 

## Performance
Due to `DefaultLocalConfigurationMetadata` now being immutable, both dependencies and excludes must be calculated at the same time. Previously, these two properties of a configuration metadata were calculated independently. Due to this, there is a ~2.5% performance regression in the `excludeRuleMergingBuild` performance test, as previously the test did not need to realize configuration metadata dependencies. However, IMO this is outweighed by the ~3.5-4.5% performance improvement in `largeGroovyMultiProject`, both abi and non-abi, and the ~2.5% improvement in `santaTrackerAndroidBuild` non-abi change.

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test apt

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle help

**Comment by jvandort** [comment]
@bot-gradle test pt ast prf

**Comment by big-guy** [comment]
@bot-gradle test pt ast prf

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
