### PR TITLE
Align names of internal attributes types

### PR DESCRIPTION
**Pull request by tresat**
Followup to #30667.

Adjust the naming of types in `org.gradle.api.internal.attributes` so they reflects actual usage - it's not an `ImmutableAttributesFactory`, it is the single factory used for all attribute container types.

Many file changes, but it's just the downstream consequences of renaming the types in that package.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Review by octylFractal — APPROVED** [review]

**Review by mlopatkin — APPROVED** [review]
CC and core-runtime LGTM

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
