### PR TITLE
Upgrade smoke tested plugin versions

### PR DESCRIPTION
**Pull request by eskatos**

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Review by ljacomet — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
