### PR TITLE
Rename a few elements of the Kotlin DSL Reference docs

### LINKED ISSUE #26359: Clarify page title and filter buttons/tabs in the Kotlin DSL reference
### Issue type

Wrong or misleading information

### Problem description

The title of the Kotlin DSL reference page is confusing:

> I landed on the page by Googling for gradle mapproperty generic value. The top hit was https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.provider/-map-property/index.html. Other than kotlin-dsl in the URL which I didn't see, there's nothing on the page to tell me that I'm looking at the Kotlin DSL. 

The current title is `Gradle <version>`.
It should be revised to be more explicit, something like `Gradle Kotlin DSL Reference for Gradle 8.3`.

----

The `Java API` and `Kotlin DSL` buttons and tabs are confusing. Clicking the `Java API` button or tab doesn't show the Javadoc as it could be expected but still shows Kotlin signatures. This is expected but the name is confusing.

Renaming these to simply `API` and `DSL`, should alleviate the confusion.

### Context (optional)

This issue is the result of a discussion following feedback from @wilkinsona 

### Page with the problem

https://docs.gradle.org/current/kotlin-dsl/index.html

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #26359

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test BD

**Comment by eskatos** [comment]
Result can be seen at https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/71931632:id/distributions/gradle-8.4-docs.zip!/gradle-8.4-20230919114429%2B0000/docs/kotlin-dsl/index.html

**Review by eskatos — APPROVED** [review]

**Review by lkasso — APPROVED** [review]
Thank you @jbartok.

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
