### PR TITLE
Fix disambiguation rule for Usage with Java projects

### PR DESCRIPTION
**Pull request by DPUkyle**
Otherwise we would never fall into the javaApi arm of this conditional logic

### CODE REVIEW

**Comment by DPUkyle** [comment]
@bot-gradle test this

**Review by ljacomet — CHANGES_REQUESTED** [review]
I understand the change, but I wonder about the impact.

Could you add a test that shows the impact and explains why it is necessary?

**Review by big-guy — APPROVED** [review]

**Comment by DPUkyle** [comment]
> I understand the change, but I wonder about the impact.
> 
> Could you add a test that shows the impact and explains why it is necessary?

I added a regression test which fails without this change.

**Comment by DPUkyle** [comment]
@bot-gradle test and merge

**Pull request merged**
