### PR TITLE
Capability to allow additional Resources to be rendered within a Testreport

### PR DESCRIPTION
**Pull request by detlef-brendle**
Beeing able to render additional test results within a Testreport, could give users the chance to include other resources that have been created into one test report.
My for this is when running Geb functional UI Tests, the results that Geb can produce are the screenshots of the Application. 
Also downloaded files generated by the WebPage i.e. documents, XML files and others can be included in the Testreport.

Howto use:
- extend the DefaultTestReport and overwrite 'additionalResource' method
- within the test configuration of your build.gradle set your testReporter to be used
- run your task and see the outcome in the testreport.
Here is an example of the generated testreport.

testreport

Here is the GebTestReport that I wrote to complete my modification:

<pre>
package ch.prospective.njc

import org.gradle.api.internal.tasks.testing.junit.report.DefaultTestReport
import org.gradle.api.internal.tasks.testing.junit.report.IAdditionalTestResultResource
import org.gradle.api.internal.tasks.testing.junit.report.TestResult

class GebTestReport extends DefaultTestReport {

    @Override
    protected List<IAdditionalTestResultResource> additionalResourceListeners() {
        return [new IAdditionalTestResultResource() {
            @Override
            List<File> findResources(TestResult test) {
                File classResultFolder = new File("build/geb-reports/${test.classResults.name.replaceAll('\\.', '/')}")
                List<File> result = []
                def testRFile = classResultFolder.listFiles().find {
                    it.name.contains(test.name.replaceAll("[^\\w\\s-]", "_"))
                }
                if (testRFile) {
                    String testResultFilePrefix = testRFile.name.substring(0, 3)
                    result = classResultFolder.listFiles(new FilenameFilter() {
                        @Override
                        boolean accept(File dir, String name) {
                            name.startsWith(testResultFilePrefix)
                        }
                    })
                }
                return result.sort { it.name }
            }
        }]
    }
}
</pre>

Would be nice to see this hook become part of gradle in the near future.

Thanks,
Detlef

### CODE REVIEW

**Comment by breskeby** [comment]
Hey Detlef.
I like the idea of that pull-request. would you mind adding some unit/integ test coverage. also some checkstyle stuff fails the build. see https://travis-ci.org/gradle/gradle/builds/48612180 for details

**Comment by detlef-brendle** [comment]
Hi Rene,
I'va added a testcase plus fixed the coding conventions.

Thanks,
Detlef

**Comment by detlef-brendle** [comment]
@breskeby : Could you integrate this pull request yet ?
Thanks,
Detlef

**Comment by breskeby** [comment]
Hey Detlef,
at the moment the TestReport is internal api. So we need some more work todo here in opening up this API to be public first before we can apply the pull request. So please be patient as we are currently a bit busy and havn’t worked on this pull-request yet. Would you mind signing the CLA in the meantime? see http://www.gradleware.com/contributor-agreement/ for details.

cheers,
René

**Comment by bigdaz** [comment]
Hi Detlef. 

As Rene mentioned, the functionality modified by this pull request is all internal API. We don't want to add functionality to the internal API that is intended for end users: that defeats the purpose of it being 'internal'.

Instead, we'd want to model the entire test suite in a richer way, so that the reporting can automatically include the correct resources. This will require a bunch of design discussion and probably quite a bit more work, but in the end the result will  be much better.
I'm going to close this pull request, and if you're interested in sparking off a discussion on the Gradle developers list on how to move forward, that would be great. Thanks so much for your work on this. 

cheers
Daz

**Pull request closed without merging**
