### PR TITLE
Update Gradle installation guide in User Manual with clearer definition of project

### PR DESCRIPTION
**Pull request by lkasso**
### Details
This is a Documentation change ONLY.

### Context
1. This is an update to the Gradle installation guide based on @hugobuddel's comment: https://github.com/gradle/gradle/pull/24913#issuecomment-1859052815

### Reviewers: [Build Link](https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/76024246:id/distributions/gradle-8.6-docs.zip!/gradle-8.6-20231218190948%2B0000/docs/userguide/installation.html)
- Please make sure the changes address @hugobuddel's comment

### CODE REVIEW

**Comment by lkasso** [comment]
@bot-gradle test BD

**Comment by lkasso** [comment]
@bot-gradle cancel

**Comment by lkasso** [comment]
@bot-gradle test BD

**Comment by lkasso** [comment]
@bot-gradle clean

**Review by akshayabd — APPROVED** [review]

**Comment by lkasso** [comment]
@bot-gradle merge

**Pull request merged**
