### PR TITLE
Extract CompileServices from Plugins

### PR DESCRIPTION
**Pull request by tresat**
- This class doesn't belong in plugins, and this allows us to further trim some dependencies from plugins.
- Also removes duplicate copy of file.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by octylFractal — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
