### PR TITLE
Add --groups option to tasks task

### LINKED ISSUE #19509: Support multiple --group for TaskReportTask
### One should be able to pass several groups to the task report task

Working with complex builds and many subprojects you might give hints which tasks are the most convenient for a project.
Often tasks from several groups are important.

### Current Behavior
Currently you can display one group only or _all_ groups. Nothing in between.

### Context

I am writing example projects for my colleagues.
Each combines various topics of interest.
Those example projects shall display only tasks of groups that are important for that specfic use case.
Those tasks are not always contained in one single group.
It would be nice to have all examples in one repository and make each project display the essential stuff.

I'd appreciate an interface similar to _--tests_ which is a repeatable option.

*edit*
I could try to do it by myself with a little help...

### PR DESCRIPTION
**Pull request by apalopta**
This commit adds the `--groups` option to the tasks task.

Similar to the `--tests` option the `--groups` option is repeatable.
If the `--group` option is given using `--groups` will append the given
group.

The option accepts Strings.

Signed-off-by: Anja Papatola <mamadev@apalopta.de>

Fixes #19509

### Context

In large projects you might want to give users a hint of what the most important tasks are.
Currently you can display one group only or _all_ groups.
The first might be less, the latter to much information.

I missed an "intermediate" solution in some of my projects that provide examples to my colleagues.
My intention was to show only those task groups that are of interest for specific use cases.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [ ] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Review by jbartok — CHANGES_REQUESTED** [review]
All good overall, the only change I would ask for is to add some more tests to `AggregateMultiProjectTaskReportModelTest`, which exercise the new param too. I'm thinking of making some existing tests parametrized to provide the group via the old and then the new way.

**Comment by apalopta** [comment]
Thank you, I am working on it already :-)

**Review by jbartok — APPROVED** [review]

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by apalopta** [comment]
Thanks, really enjoyed it.
Great workflow :-)

**Pull request merged**
