### PR TITLE
Upgrade to Spock 1.0 everywhere

### PR DESCRIPTION
**Pull request by lptr**
[Review on Reviewable](https://reviewable.io/reviews/gradle/gradle/503)

### CODE REVIEW

**Comment by lptr** [comment]
Doing this as a pull-request because it's not very important right now, but easy to test if it works already without a hitch.

**Comment by pioterj** [comment]
@lptr I understand that you'll merge it yourself when you have some time, right?

**Comment by lptr** [comment]
Forgot about this. Will take a look, thanks.

**Comment by lptr** [comment]
I've pushed this to master instead.

**Pull request closed without merging**
