### PR TITLE
Fix for #11036 – Provide messages for null pointer exceptions when map property literals contain `null`

### LINKED ISSUE #11036: NullPointerException when using empty value in map
### Expected Behavior
I expected that I could use null values (not keys) in a Map used in a task. At least I expected a real error message and not just a NullPointerException with no more information.

### Current Behavior
A NullPointerException is thrown (because of a null access) without any furhter information.

### Steps to Reproduce 
Use the provided gradle project in [gradle-param-bug.zip](https://github.com/gradle/gradle/files/3724808/gradle-param-bug.zip) and run gradle hello

### Your Environment
$ gradle -version
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.4 (AdoptOpenJDK 11.0.4+11)
OS:           Windows 10 10.0 amd64

### PR DESCRIPTION
**Pull request by kiwi-oss**
Fixes #11036.

Recreates #16648 with additional changes as requested in the review. As it was only mentioned which method triggers the validation and I didn't know how it's triggered from the build file, I only added an extra unit test for that method.

### Context

This solves the issue that `null` values in map properties provided as literals result in null pointer exceptions without error message, making it difficult to identify the issue without debugging Gradle.

`Null` values and keys were already checked and even resulted in useful error messages, but only if they are added to a map property via `put`.

I didn't update any documentation because I don't think the changes require it. The null pointer exceptions were thrown already, they just didn't contain a message.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@kiwi-oss your PR still makes some tests fail: https://ge.gradle.org/s/p4dnt3jrhnc6g/tests/overview?outcome=failed

**Comment by kiwi-oss** [comment]
I'm surprised because I had run all the tests and they passed, but I'll take a look.

**Comment by kiwi-oss** [comment]
I still can't reproduce that locally. I updated the branch after your merge of the main branch and ran `./gradlew :model-core:check --no-configuration-cache` (because it failed for some other reason with the configuration cache). I chose that subproject because that is where `MapPropertyIntegrationTest` is located.

**Comment by donat** [comment]
@kiwi-oss  running `configCacheIntegTest` should reproduce the problem:
image

**Comment by kiwi-oss** [comment]
Thank you, now I see the errors, too. I will look into that.

**Comment by donat** [comment]
@gradle/configuration-cache please advise

**Comment by eskatos** [comment]
@kiwi-oss, please annotate the offending tests with `@ToBeFixedForConfigurationCache`, we'll take care of them

**Comment by kiwi-oss** [comment]
Thank you, @eskatos, I added the annotation.

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test and merge

**Review by donat — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@kiwi-oss thank you for the contribution!

**Comment by kiwi-oss** [comment]
Thank you, I'm happy that it worked out in the end!

**Comment by eskatos** [comment]
Follow up fixing the configuration cache usage at https://github.com/gradle/gradle/pull/19596

**Comment by kiwi-oss** [comment]
Thanks! I'm glad it was an easy change. I didn't have enough insight into the code to figure it out quickly.

**Pull request merged**
