### PR TITLE
Discard constructor after the service has been created

### PR DESCRIPTION
**Pull request by big-guy**
### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
Does it have a measurable effect in memory usage?

**Comment by alllex** [comment]
@bot-gradle test without pts

**Comment by pablobaxter** [comment]
Confirmed that this had a 0.1gb savings in memory on the 6200 project build.
image

**Comment by big-guy** [comment]
@bot-gradle merge

**Pull request merged**
