### PR TITLE
PatternSet.getAsExcludeSpec: don't exclude everything if there are no patterns

### PR DESCRIPTION
**Pull request by SpecLad**
It is normally impossible to have no exclude patterns, because `DirectoryScanner.getDefaultExcludes()` is always added to their list. However, it can happen if Ant's global exclude list is emptied by the user beforehand.

In GRADLE-1883, the workaround by Björn Kautler contains this rather unnatural part:

```groovy
DirectoryScanner.addDefaultExclude 'something has to be in here or everything gets excluded'
```

This PR removes the need for that.

### CODE REVIEW

**Comment by bigdaz** [comment]
Thanks very much for the pull request. We've got a bit of a backlog at the moment, but will take a look as soon as we can.

**Comment by bigdaz** [comment]
A couple of things that will help get this merged:
1. Some unit test coverage for this change
2. Instead of using the user-configurable list of default excludes from Ant, we should be using the true source of these defaults (org.apache.tools.ant.DirectoryScanner#DEFAULTEXCLUDES). Unfortunately this is protected, so we'll probably need to be using a bit of reflection to access it.

Is this something you'd be able to help out with?

**Comment by SpecLad** [comment]
> 1. Some unit test coverage for this change

Well, the thing is, to exercise the behaviour affected herein, I'd need to modify global state (Ant's default excludes). I doubt that's a good thing to do in a unit test.

> 2. Instead of using the user-configurable list of default excludes from Ant, we should be using the true source of these defaults (org.apache.tools.ant.DirectoryScanner#DEFAULTEXCLUDES). Unfortunately this is protected, so we'll probably need to be using a bit of reflection to access it.

Um... that would be rather contrary to my goal here. I'm doing this because I _want_ to configure this list.

**Comment by bigdaz** [comment]
Thanks. I already added the unit test, that does exactly that (modify Ant's default excludes).

@adammurdoch mentioned that he would have preferred that didn't honour Ant's modified set of excludes: the intention was just to use this as a base set for convenience. But I think we'd need to support the use case in GRADLE-1883 if we wanted to make this (breaking) change.

This PR has been merged and will be in Gradle 2.4. Thanks for the contribution.

**Comment by adammurdoch** [comment]
Why do you want to configure the list?

**Comment by SpecLad** [comment]
Some of the files that I want to archive match the global excludes. And in fact, I know the exact list of files to archive, so I don't need any exclusions to be done for me.

**Pull request merged**
