### PR TITLE
Let the configuration cache handle build cancellation gracefully

### PR DESCRIPTION
**Pull request by eskatos**
By stoping build logic instrumentation, fingerprint collection, state writing if build cancellation happen while they are running.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by adammurdoch** [comment]
Cancellation is one of many ways that a partial cache entry can be produced. For example, the daemon may crash or be killed while writing the cache entry or may fail to completely garbage collect an entry that is later reused. So, rather than trying to implement a solution for each the different ways that things can go wrong, I would add a solution that works for relatively well all of them and that does not treat cancellation as a special case.

For example, we might write a marker file to the entry once everything has been written and not reuse an entry that does not have an entry. We could potentially use the fingerprint file as such a marker, by writing it a temporary name and then atomically renaming it. It's not completely fool proof but would be more reliable than just handling cancellation.

Another strategy might be to write to a journal/index when the entry is ready. I suspect we'll end up with an index at some point anyway, for example to allow us to reuse entries with the unchanged requested tasks but with other inputs that are different (eg switching between two values for a system property input).

**Comment by eskatos** [comment]
Thanks for the comments Adam. The changes in this draft PR are naïve and exploratory. We already use the fingerprint file as the marker of a reusable entry but we write it a little bit too soon and then later delete it if something goes wrong to mark the entry as invalid. This leaves a small window open for an invalid state to be considered as reusable. I'll rework this PR to make this more robust.

**Comment by eskatos** [comment]
Actually, reading the code again, the window is currently pretty narrow. We first write the state file, then commit the fingerprint file to disk. Immediately we catch any error and delete the fingerprint if that happens. Should be fine. Closing

**Pull request closed without merging**
