### PR TITLE
Remove unused PropertyValidationAccess class

### PR DESCRIPTION
**Pull request by lptr**
This has been left over from an old refactor. It has been replaced by `org.gradle.plugin.devel.tasks.internal.PropertyValidationAccess`.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle run QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Pull request merged**
