### PR TITLE
De-incubate GradleConnector.disconnect()

### PR DESCRIPTION
**Pull request by donat**

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test RFM

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Review by eskatos — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by lptr** [comment]
@bot-gradle cancel merge please.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Pull request merged**
