### PR TITLE
Don't ask for user input on non-interactive console

### PR DESCRIPTION
**Pull request by bmuschko**
### Context

- See https://github.com/gradle/gradle/issues/3081
- [Branch build](https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_Stage_BranchBuildAccept_Trigger&branch_Gradle_Check=bm%2Fdetect-interactive-console&tab=buildTypeStatusDiv)

### CODE REVIEW

**Comment by bmuschko** [comment]
> We should add a tapi test, otherwise this looks great.

@oehme What exactly would we test here? That the field `StartParameter.interactive` is true if standard input was provided? Or would you go as far as resolving `BuildScanUserInputHandler` from the service registry and requesting a user input? IMHO that's already covered in `GradleRunnerConsoleInputEndUserIntegrationTest`? We also already have `ConsumingStandardInputCrossVersionSpec` for capturing standard input.

**Comment by oehme** [comment]
I'm looking for an end to end test showing that no input is requested when we run through the tapi without stdIn. So far we only have one showing that we do prompt when stdIn is passed.

**Comment by bmuschko** [comment]
> I'm looking for an end to end test showing that no input is requested when we run through the tapi without stdIn. So far we only have one showing that we do prompt when stdIn is passed.

done

**Comment by jfresen** [comment]
This doesn't seem to work with pipes, e.g. `yes | ./gradlew myTask` where myTask asks a yes/no question

**Comment by lacasseio** [comment]
@jfresen Please open an issue with a reproducible example that we can decide what is the problem.

**Pull request merged**
