### PR TITLE
Fix inefficient `Optional.orElse` usage by Cpp and Swift plugins

### LINKED ISSUE #21334: Cpp and Swift plugin classes use `Optional.orElse` inefficiently
### Current Behavior
It looks like several Cpp and Swift plugin classes use Java's `Optional.orElse` inefficiently, see code snippets below. This causes all the alternative values to be computed, even if they are not needed. Maybe they should use `Optional.orElseGet` to only evaluate the alternative value if it is really needed.

- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppApplicationPlugin.java#L87-L92
- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppLibraryPlugin.java#L102-L105
- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/cpp/plugins/CppUnitTestPlugin.java#L114-L116
- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftApplicationPlugin.java#L91-L96
- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftLibraryPlugin.java#L103-L106

I have not measured the performance difference, but just noticed this (probably) ineffecient usage of `Optional`; hopefully this bug report is useful nonetheless.

### PR DESCRIPTION
**Pull request by Marcono1234**
Fixes  #21334

### Context
See #21334; some Cpp and Swift plugins seem to use `Optional.orElse` inefficiently, always evaluating the fallback value even if it is not used.

Note that I have not measured the performance impact this has.

I am not familiar with these plugins and cannot really say whether these changes may have any side effect. In case this eager evaluation is desired it might be worth to refactor the code (e.g. introduce separate local variables and add comments) to make the intention a bit clearer.

If you think further changes to this are needed, feel free to directly edit this PR branch, or create a separate PR based on it. That will probably be more efficient since you are familiar with the code and also have the Gradle development tools properly set up locally.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`
    :x: There are test failures, however I am not sure if they are related to these changes:
    - Multiple integration tests (e.g. `AssemblyLanguageIncrementalBuildIntegrationTest`) failed with:
          ```
          Assembler failed while compiling sum.s.
          ```
          And the detailed log containing:
          ```
          fatal error A1000:cannot open file : ks386.inc
          ```
          Originally Windows Defender was slowing down the build; not sure if that might have caused this issue, or whether my build setup is incomplete.
    - The test "Class recompiles binary when toolchain changes from #toolChainBefore to #toolChainAfter" failed with:
        ```
        AssumptionViolatedException: 2 or more tool chains are required for this test
        ```
        I think `AssumptionViolatedException` should actually be reported as skipped test (if I understand it correctly), though for me it was reported as failed.

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
