### PR TITLE
Migrate build-types plugin to Kotlin

### PR DESCRIPTION
**Pull request by eskatos**
Feedback for and follow up to #4342

### CODE REVIEW

**Comment by eskatos** [comment]
Feedback build: https://builds.gradle.org/viewQueued.html?itemId=11028576

**Comment by bamboo** [comment]
New feedback build: https://builds.gradle.org/viewLog.html?buildId=11062357 ✅

**Comment by big-guy** [comment]
@eskatos @bamboo I reverted this PR in https://github.com/gradle/gradle/pull/4409 -- this was causing all quickTest builds to just run clean (you can see this in the feedback build).  I didn't look deeper as to what was going on.

**Comment by bamboo** [comment]
Thanks, @big-guy. I'll investigate further.

**Comment by bamboo** [comment]
An off-by-one error, who would have thought?

**Comment by bamboo** [comment]
Superseded by #4412.

**Pull request merged**
