### PR TITLE
Enable PTS for all Test tasks

### PR DESCRIPTION
**Pull request by blindpirate**
Now all `Test` tasks (including subtypes) are supported.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Review by marcphilipp — CHANGES_REQUESTED** [review]
@blindpirate This also requires updating the TD Gradle plugin but the latest release is incompatible with Gradle 7.6 or later (see also #20491) which is blocked by #15067.

**Comment by blindpirate** [comment]
But all tests passed, do they fall back to no-PTS?

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by marcphilipp** [comment]
@bot-gradle test this

**Review by marcphilipp — APPROVED** [review]

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
