### PR TITLE
Gradle tooling: find the correct wrapper on project import

### PR DESCRIPTION
**Pull request by idlsoft**
When importing projects in IDEA and using the "Use default gradle wrapper" option it looks for the gradle wrapper in the buildLayout.rootDirectory, and ignores the project directory.
So if there is a wrapper in the project dir and a settings.gradle in the parent the wrapper is not found.
However it works just fine from command line, so the behavior is inconsistent.

### CODE REVIEW

**Comment by idlsoft** [comment]
TestExecutionRequestActionRunnerTest failure seems unrelated to this change, it fails without it as well.

**Comment by idlsoft** [comment]
I'll try but that code was there before, I added a few lines above it.

**Comment by bigdaz** [comment]
Thanks for the contribution @idlsoft. In order to fix this issue, we'll first need to get a clear indication of the current behaviour, and the expected behaviour. We'd then encode this behaviour into some integration tests to verify that the issue is indeed fixed.

Is that something you'd want to help out with? Perhaps the first step would be to describe the issue in detail on http://discuss.gradle.org.

**Comment by idlsoft** [comment]
I've created a sample project, which should help replicate the issue here:
https://github.com/idlsoft/gradle-tooling-wrapper-location-bug

**Comment by mark-vieira** [comment]
I'm not sure what we expect the pattern to be when using a "flat" multi-project layout. With regards to the sample you provided, if there was a 'module2' and 'module3' each would have their own wrapper?

I think the more conventional thing would be to place the wrapper in the 'master' project and run builds from there. That way all projects share the same wrapper. In that case, we should fall back to searching for the wrapper in root project directory, rather than the subproject.

**Comment by idlsoft** [comment]
Yes, each module has its own wrapper.
In our setup we allow modules to be built independently or as part of multi-module, if master is present.
The developer gets to choose, and it works fine from command line, but not IDEA.

**Comment by mark-vieira** [comment]
If I understand correctly, in the case where the 'master' directory isn't present, importing the project into IntelliJ should use the wrapper in the project directory since that directory would also be the root directory.

**Comment by idlsoft** [comment]
It should use it in both cases.
When you run from command line ./gradlew is your starting point, and is recognized as such by IDEA.
It doesn't have to be the root directory as well, that gets determined after gradle is already loaded.
Everything works correctly when master isn't present, but breaks when it is.

**Comment by mark-vieira** [comment]
That brings up another question, which is, should we prefer the wrapper located in the project directory to one in the root directory, even if it exists?

In general, since this is a change to the behavior of the tooling API we should have a larger discussion on this. Do you mind starting a topic on the [mailing list](https://groups.google.com/forum/#!forum/gradle-dev) about this? We typically recommend starting with such a discussion in accordance with our [contribution guidelines](http://gradle.org/contribute-to-gradle/).

In any case, if the consensus is this is the preferred solution then we will require test coverage to confirm the new behavior prior to merging.

**Comment by idlsoft** [comment]
The way I see it, the tooling behavior should be consistent with command line.
When you run from command-line, the wrapper is always taken from the current directory.
Gradle then decides if this is a standalone project or part of a larger one, but the wrapper never changes.

When you import from IDEA, it only enables using the wrapper if it sees one in the directory you're importing from.
But then it ignores it, (which I think is also a bug) and calls gradle tooling, which uses a different algorithm, fails to find it, and picks the default.

**Comment by mark-vieira** [comment]
I think that may very well be the way to go. That said, since this is a PR that changes behavior it must coincide with a design discussion, potentially a formal design spec and most importantly, test coverage. Would you be willing to initiate such a discussion on the mailing list where we might come to a consensus on what the best way forward should be and identify the necessary test coverage?

**Comment by idlsoft** [comment]
Sure, just want to point out the old behavior is still functional, and, I think, has precedence.
I only added an additional check if nothing is found.

**Comment by mark-vieira** [comment]
Thanks. Yes, it does look as though the old behavior would be the default and we would only fall back to using the wrapper in the project directory if one could not be found in the root project directory. That seems the safest way to go.

**Comment by idlsoft** [comment]
Technically this keeps it inconsistent with command line.
But it's a very safe, backward compatible change.

**Comment by mark-vieira** [comment]
As a result of the discussion on the [mailing list](https://groups.google.com/forum/#!topic/gradle-dev/PFdVsUYEYMQ) I'm going to close this PR.

**Pull request closed without merging**
