### PR TITLE
[GRADLE-2799] Replace Bash redirect operator >&- with >/dev/null

### PR DESCRIPTION
**Pull request by john3300**
Discussed on gradle-dev here:
https://groups.google.com/d/topic/gradle-dev/y9Gi0SJwRBw/discussion

### CODE REVIEW

**Comment by john3300** [comment]
Travis CI failed due to a Checkstyle failure in an unrelated area of code.

:modelCore:checkstyleMain[ant:checkstyle] /home/travis/build/gradle/gradle/subprojects/model-core/src/main/java/org/gradle/model/internal/registry/ModelNodeInternal.java:204:5: Definition of 'equals()' without corresponding definition of 'hashCode()'.
 FAILED

**Comment by lptr** [comment]
That was me, should be fixed now.

**Comment by john3300** [comment]
Thanks, Lóránt.  Can the Travis CI job be resubmitted?  Or do I need to do another pull request?

**Comment by lptr** [comment]
The pull request is triggered by a merge commit created by GitHub. So restarting the build would only reproduce the same error. I guess the easiest way would be to push an empty commit to this branch.

**Comment by big-guy** [comment]
Thanks, @john3300 

I see you've signed the CLA.  I can take it from here.

**Comment by big-guy** [comment]
I merged just your first commit.  This missed the boat for 2.7, but it'll be in a nightly soon and be included in 2.8.  Thanks!

**Pull request closed without merging**
