### PR TITLE
More strict Regex in FindBugsClasspathVaildator

### PR DESCRIPTION
**Pull request by mahmoud-k**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [x] Before submitting a pull request, I started a discussion on the
[Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev)
or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).

### CODE REVIEW

**Comment by mahmoud-k** [comment]
Group discussion:
https://groups.google.com/forum/#!topic/gradle-dev/fMXJ6mRTK4c

**Comment by wolfs** [comment]
Thank you for your contribution!

The change to the production sources looks good to me. Please add some test coverage for the change. FindBugsClasspathValidatorTest seems to be the right place to do that.

**Comment by mahmoud-k** [comment]
Thanks for the feedback.
Updated the unit test in FindBugsClasspathValidatorTest.

**Comment by wolfs** [comment]
Thank you for writing a test. I would prefer if it would be a new test, leaving the old tests in place. You can use a where-clause in the test to have different classpath entries. For the test it would be good that the jars starting with findbugs have a different version in order to distinguish the result.
Could you please adjust the test accordingly?

**Comment by mahmoud-k** [comment]
Hi, Stefan. Apologies for taking long to get back to you.
So I write a new class FindBugsVersionVaidatorTest, and address your feedback about using where-clause and different versions.

**Comment by wolfs** [comment]
Internal Review: https://code-review.gradle.org/cru/REVIEW-5994

**Pull request merged**
