### PR TITLE
Ignore `.tmp` for UndefinedBuildExecutionIntegrationTest

### PR DESCRIPTION
**Pull request by wolfs**
`.tmp` only shows up in Gradle user home directory, not in the project caches
directory.

### CODE REVIEW

**Comment by donat** [comment]
I think we should accept `.tmp` only if it's empty.

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
Better late than never; I've added my review.

**Pull request merged**
