### PR TITLE
OOP-ize the simplification of intersecting exclude rules

### PR DESCRIPTION
**Pull request by tresat**
Creates a registry (list) of intersections types that can be simplified, then searches the registry to find the appropriate simplification for any pair of `ExcludeSpec`s.  This avoids needing to carefully read and maintain long `if-elseif-elseif`... which had missing intersection conditions.

All unmodified existing tests still pass.

- Removes the (hidden) necessity for testing the intersections in the proper order in the `if-else` block.  This should make it much harder to accidentally miss a type of intersection which can be simplified 
- Easy to debug - set a breakpoint in the `intersect` lambda in `tryIntersect` and step and you'll see exactly which intersect logic is running
- Simpler to explain.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
Un-stale.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@tresat can you get Louis to look at this and see if it's worth merging in some form soon (8.8)?

**Comment by tresat** [comment]
@bot-gradle test APT

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@ljacomet is this worth merging?  This was an old PR that Tom had around that you guys looked at together 2 years ago

**Comment by tresat** [comment]
I've got a meeting to talk to Louis about this later this week.  I think it's worth merging.

**Comment by tresat** [comment]
Discussed this change with Louis, everything looks good, going ahead with merging it.

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
