### PR TITLE
Corrected property name srcDir in customizedLayout

### PR DESCRIPTION
**Pull request by bdurepo1**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [ ] Before submitting a pull request, I started a discussion on the
[Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev)
or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I wrote a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [ ] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by wolfs** [comment]
Thanks for your contribution!

Why would you want to change from `srcDir` to `srcDirs`? We should probably add `srcDir` to the list of important methods in the table below the example. See https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html

**Comment by bdurepo1** [comment]
Yes, adding srcDirs to table would be more clear to users. I am completing the Udacity course on Gradle now and this was a sticking point. Either adding the srcDir method to the documentation in the accompanying table or updating the sample as I have done should do it.

**Comment by wolfs** [comment]
Please add srcDir to the table.

**Comment by bdurepo1** [comment]
Would it be appropriate to refer users to 18.2?
[https://docs.gradle.org/current/userguide/working_with_files.html#sec:file_collections](url)

**Comment by wolfs** [comment]
Sure. I see you already did this.

Should we remove the reference to srcDirs? I think the most common usecase is to use srcDir. WDYT?

**Comment by bdurepo1** [comment]
I'll remove it. It becomes redundant if the user delves deeper into the API. I am just a beginner with Gradle so i don't have the common use case intuition yet.

**Comment by big-guy** [comment]
Hey @bdurepo1, thanks for the interest in trying to improve Gradle's documentation.

I think you've found a good example of where things can be confusing for everyone.  The table in 45.7.1 is referring to important properties available in a [`SourceSet`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html).  Properties here are in the Java Bean/Groovy sense (fields that have a getter and setter).  In this case, `java.srcDirs` is referring to the `srcDirs` property on [`SourceDirectorySet`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html), which is made up of `setSrcDirs` and `getSrcDirs` methods.  We use the same terminology in the DSL section of the user guide.  There's also a `srcDir` and a `srcDirs` method, but these are convenience methods for `getSrcDirs().add(...)` or `getSrcDirs().addAll(...)`.  I think we need to keep the table consistent (and refer to properties), which means we need to keep `java.srcDirs`. 

Could you describe a bit of what you had trouble with from the Udacity course? If I had to guess, most examples probably use `srcDir` and not `srcDirs` to add directories to a source set and it's not clear which type you could look at to find that method.

It's really helpful to have your fresh perspective on these things. Would it be clearer to you if separate from the 45.7.1 table there was a "Important source set directory methods" that called out `srcDir`, `srcDirs`, `include` and `exclude`?  In that case, we'd remove `resources.srcDirs` and `java.srcDirs` from the existing table and put the new table directly underneath.

**Comment by bdurepo1** [comment]
Yes I think a separate table for the source set directory methods would be useful. In Udacity's lesson 2.03 in their Gradle course you happen upon this concept. Here is a link to the specific lesson.

[https://github.com/udacity/ud867/tree/master/2.03-Exercise-ConfigureTheJavaPlugin](url)

**Comment by wolfs** [comment]
I would be great if you could take a shot at adding this table. Feel free to change this pull request or open a new one. Thank you for your time and effort!

**Comment by bdurepo1** [comment]
I am sorry for not getting to this yesterday. I have been quite busy. I will take a look at it tomorrow. Thanks for making such a great tool.

V/R,

Brandon Durepo
[bdurepo@gatech.edu]

**Comment by wolfs** [comment]
@bdurepo1 : Are you still interested in working on this?

**Comment by bdurepo1** [comment]
No
V/R,

Brandon Durepo
[bdurepo@gatech.edu]

**Comment by wolfs** [comment]
Then I will close this PR.

Thank you very much for your time and effort involved in creating this pull request and the discussion about it.

**Pull request closed without merging**
