### PR TITLE
Promote ValueSource APIs

### LINKED ISSUE #15577: Promote incubating `org.gradle.api.provider.ValueSource` and family
### Summary

- org.gradle.api.provider.ValueSource
- org.gradle.api.provider.ValueSourceParameters
- org.gradle.api.provider.ValueSourceParameters.None
- org.gradle.api.provider.ValueSourceSpec

### Checklist
- [x] Validate whether we should de-incubate the API in the 7.0 release.
    - If the removal is not possible, create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=1195622786)
- [x] Update release notes (add API to promoted features)
- [x] Check User Manual (it might mention that the API is still incubating)
  - Think about updating snippets and samples to use this API
- [x] Deprecate existing API that is replaced by the new one
  - If it's not immediately possible, create a follow-up issue with a milestone (e.g. `7.1 RC1` or `8.0 RC1`)
- [ ] Check Incubation Report on TeamCity ([example](https://builds.gradle.org/viewLog.html?buildId=40024670&buildTypeId=Gradle_Check_SanityCheck&tab=report_project951_Incubating_APIs_Report)) 
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit?ts=5fcfefb8#gid=0).

### PR DESCRIPTION
**Pull request by mlopatkin**
Fixes #15577

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test BD

**Review by bamboo — APPROVED** [review]
💯

**Review by hythloda — APPROVED** [review]
If there is no need for this in the main section, I approve.

**Review by yujincheng08 — CHANGES_REQUESTED** [review]
#22494

**Comment by mlopatkin** [comment]
> #22494

I'm not sure what this comment means. Promoting feature to stable doesn't mean it has no bugs or it won't change in a backward-compatible way in the future. We discussed the linked issue and concluded that:
* excessive invalidation of cache entries doesn't affect correctness, so it is more a wasted performance opportunity.
*  fixing the issue and skipping cache invalidation may be considered a breaking change to some extent, but we consider that the benefits outweigh the risks in this case.

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
