### PR TITLE
Handle inconsistent vendor info for IBM Semeru runtimes (backport)

### LINKED ISSUE #23053: Auto-provisioning/auto-detection of IBM Semeru toolchains is broken with Gradle 7.6
### Expected Behavior
Build works with gradle 7.5.1 and jdks are auto provisioned as declared in build.gradle:

```
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
        vendor = JvmVendorSpec.IBM_SEMERU
        implementation = JvmImplementation.J9
    }
}
```

### Current Behavior

Upgrading to gradle 7.6 the build now fails with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':buildSrc:compileGroovy'.
> Could not resolve all dependencies for configuration ':buildSrc:compileClasspath'.
   > Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
      > Unable to download toolchain matching the requirements ({languageVersion=11, vendor=IBM_SEMERU, implementation=J9}) from 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk'.
         > Toolchain provisioned from 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk' doesn't satisfy the specification: {languageVersion=11, vendor=IBM_SEMERU, implementation=J9}.
```

### Context

Auto-detection/auto-provisioning of Gradle toolchains is broken with gradle 7.6

### Your Environment

Detected toolchains:

```
❯ ./gradlew -q javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + IBM JDK 11.0.17+8
     | Location:           ~/.gradle/jdks/ibm-semeru-open-jdk_x64_linux_11/jdk-11.0.17+8
     | Language Version:   11
     | Vendor:             IBM
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Auto-provisioned by Gradle

 + IBM JDK 11.0.15+10
     | Location:           ~/.gradle/jdks/ibm_semeru-11-x64-openj9-linux/jdk-11.0.15+10
     | Language Version:   11
     | Vendor:             IBM
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Auto-provisioned by Gradle
```

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #23053

It doesn't make sense to have both the IBM and IBM_SEMERU vendor values.

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Review by ljacomet — CHANGES_REQUESTED** [review]
We should fix the vendor matching string for `IBM` _and_ `IBM_SEMERU` so that current use cases work and then _deprecate_ `IBM_SEMERU`.
But I do not think we should remove it altogether without a deprecation.

**Comment by blindpirate** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
