### PR TITLE
Store feature preview state in configuration cache

### LINKED ISSUE #21714: Snippet "snippet-groovy-compilation-avoidance" is not compatible with the configuration cache
The snippet works fine without CC but with CC the compilation fails when running from cache:
```
startup failed:
/tmp/junit12037034537601836968/snippet-groovy-compilation-avoidance_kotlin_groovyCompilationAvoidance.sample/ast-transformation-consumer/src/main/groovy/Main.groovy: 1: unable to resolve class MyAnnotation for annotation
 @ line 1, column 1.
   @MyAnnotation
   ^

1 error
```

Build scan URL:
* https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket3SnippetsTest/snippet-groovy-compilation-avoidance_groovy_groovyCompilationAvoidance.sample?top-execution=1
* https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket3SnippetsTest/snippet-groovy-compilation-avoidance_kotlin_groovyCompilationAvoidance.sample?top-execution=1

### PR DESCRIPTION
**Pull request by mlopatkin**
Feature flags are configured at the configuration time and may be accessed at the execution time, so storing their values is necessary to ensure correctness. Some flags, currently "stable configuration cache", affect the configuration and can be toggled with system properties. It makes sense to mark such system properties as configuration cache inputs.
Fixes #21714

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Review by h0tk3y — APPROVED** [review]
👍

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
