### PR TITLE
Setup ArchUnit rules banning Guava Collection factory methods

### PR DESCRIPTION
**Pull request by tresat**
The Javadoc on these methods notes that they should be treated as deprecated.

This PR replaces these methods with simple constructor calls.  It adds an ArchUnit rule that prevents them being added.  It only affects the no-arg versions, as the argument-taking overloads are still valid.

Affected methods:
- `Lists.newArrayList`
- `Lists.newCopyOnWriteArrayList`
- `Lists.newLinkedList`
- `Maps.newConcurrentMap`
- `Maps.newHashMap`
- `Maps.newLinkedHashMap`
- `Maps.newIdentityHashMap`
- `Maps.newTreeMap`
- `Sets.newCopyOnWriteArraySet`
- `Sets.newHashSet`
- `Sets.newLinkedHashSet`
- `Sets.newTreeSet`

The large number of files changed here should just be replacing these calls with the appropriate constructor calls and cleaning imports as needed.  The new rules are in `GuavaCollectionFactoryUsageTest.java`.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]
LGTM

**Review by big-guy — CHANGES_REQUESTED** [review]

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
