### PR TITLE
Introduce repositories declared via settings

### PR DESCRIPTION
**Pull request by melix**
## Context

This is a replacement for the good old:

```
allprojects {
   repositories {
   }
}
```

pattern.

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test QF

**Comment by melix** [comment]
@bot-gradle test RFM

**Comment by melix** [comment]
@bot-gradle test RFM

**Review by ljacomet — APPROVED** [review]

**Pull request merged**
