### PR TITLE
Move Copy.destinationDir and Sync.destinationDir to Provider API

### PR DESCRIPTION
**Pull request by asodja**
Exception for smoke tests with AGP:
```
* Exception is:
java.lang.NoSuchMethodError: 'java.io.File org.gradle.api.tasks.Sync.getDestinationDir()'
  at com.android.build.gradle.internal.tasks.PackageRenderscriptTask.getDestinationDir(PackageRenderscriptTask.kt:40)
  at com.android.build.gradle.internal.tasks.PackageRenderscriptTask_Decorated.getDestinationDir(Unknown Source)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:77)
```

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by lptr** [comment]
This has been merged into https://github.com/gradle/gradle/pull/20818.

**Pull request closed without merging**
