### PR TITLE
Add snippets for BuildService implementing OperationCompleteListener

### LINKED ISSUE #22612: Add a sample demonstrating build service receiving task execution events
[The paragraph](https://docs.gradle.org/current/userguide/build_services.html#operation_listener) covering the use of build services as `OperationCompletionListener` has no samples. It could benefit from having one. Another related use case that might be worth covering is when the service implements the listener interface to be restored by the configuration cache at the beginning of the build.

### PR DESCRIPTION
**Pull request by mlopatkin**
Fixes #22612.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test BD

**Review by bamboo — APPROVED** [review]
Nice! 👍

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
