### PR TITLE
Move org.gradleinternal package under org.gradle

### PR DESCRIPTION
**Pull request by lptr**
In https://github.com/gradle/gradle/pull/16248 some Maven-related types have been moved to an `org.gradleinternal` (sic!) package. This was done to avoid loading them via the Gradle runtime classloader, to avoid loading types from Maven via a different classloader. We are essentially simulating a third-party plugin here.

This PR moves these classes back under `org.gradle.unexported`, and adds explicit filtering for this package to have the same effect without using a contorted package name.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Review by alllex — APPROVED** [review]
LGTM!

**Review by big-guy — APPROVED** [review]

**Comment by asodja** [comment]
This was not accidental it seems, see @jjohannes response https://github.com/gradle/gradle/pull/16248#issuecomment-2175847402

That also explains failing tests, since classes are loaded in a different classloader.

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle help

**Comment by asodja** [comment]
@bot-gradle test this without PTS

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
One way I found that it's possible to make this work is by filtering a package out of Gradles cores classpaths, see https://github.com/gradle/gradle/pull/29591/commits/9139c5f77d30b0a7d37b87a504f853d23b12d5d0

**Comment by asodja** [comment]
Explanation from @ghale 
> Gary Hale
I think this is reasonable.  The problem is that the Maven2GradleWorkAction class is getting loaded from the Gradle runtime classloader hierarchy rather than the worker classloader, meanwhile the maven Settings object is getting loaded from the worker classloader (because it is not visible through the filter between classloaders).  These need to be loaded from the same classloader, wherever it is.  Your solution blocks Maven2GradleWorkAction from getting loaded through the filter between classloaders, which is fine, I think. The other option would be to poke a hole for the maven Settings object, but that seems like it cause problems elsewhere.  Yet another option would be to not pass a Settings object in the parameters object, but to pass something else that can be transformed into a Settings object in the work action, but that feels pretty ugly, too.

> This is a general problem with WorkAction objects inside the Gradle codebase, but isn't a problem for 3rd party objects.  We could probably solve this more generally by creating a better filter between classloaders such that it could only reach public api stuff or something, but I imagine that would open an enormous can of worms.  Or, I wonder if it would be enough to just always prevent the work action and parameters object from being loaded through the filter?  Dunno what problems that might create.  What you've done is probably fine, but it could get us in trouble if, say, a 3rd party plugin is loading a MavenProjectsCreator or something else (which would be a public api violation, but would still break builds).

> I suppose another option would be to somehow recognize that the work action and parameters object are in the Gradle runtime classloader hierarchy and use the runtime classloader to deserialize the parameters object.  I don't know if that would cause problems for other work actions or not.

> The problem is that we are referencing a non-Gradle object in a parameters object that is in the Gradle runtime.  So, if the action/parameters and everything the parameters object references are in the Gradle runtime classloader, all good.  If the action/parameters object and everything the parameters object references are all outside of the Gradle runtime classloader (i.e. in a plugin classloader), all good.  If the action/parameters object are outside of the Gradle runtime and reference something in the Gradle API, also all good.  But if the action/parameters object are in the Gradle runtime classloader and reference something outside of the "Gradle API" (like maven) then there's a problem because the API filter blocks it from being accessed from the worker classloader when we are deserializing the parameters object.

**Pull request merged**
