### PR TITLE
Update "State of support in popular annotation processors"

### PR DESCRIPTION
**Pull request by ColtonIdle**
Updated with more accurate information regarding Butterknife, Dagger, Room, Lifecycle, Epoxy

### CODE REVIEW

**Comment by ColtonIdle** [comment]
I just made the PR via the github web interface. Not sure how to address that "Action Required".

**Comment by big-guy** [comment]
Hey @ColtonIdle,

You need to sign off your commits to pass the Developer Certificate of Origin (DCO) check.

You can do that with the instructions here: https://github.com/gradle/gradle/pull/11981/checks?check_run_id=404576027

I think you may also be able to do it by adding the message to your commit message manually via the UI. It needs to be at the end of the commit message and in the form of
> Signed-off-by: Random J Developer <random@developer.example.org>

**Comment by ColtonIdle** [comment]
@big-guy added. Let me know if that is enough.

**Comment by big-guy** [comment]
@ColtonIdle, that's close, but the sign-off has to be part of all the same commit.

**Comment by ColtonIdle** [comment]
Closing and will re-open

**Comment by ColtonIdle** [comment]
Tried re-opening via https://github.com/gradle/gradle/pull/12063

**Pull request closed without merging**
