### PR TITLE
Just a missing dot in a sentence

### PR DESCRIPTION
**Pull request by Anton-Vasilev**
Fixes #?

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Review by jbartok — APPROVED** [review]

**Comment by jbartok** [comment]
Pls sign off on your commit with `git commit --amend --signoff`

**Comment by Anton-Vasilev** [comment]
> Pls sign off on your commit with `git commit --amend --signoff`

@jbartok I did. But not sure it's working :/. 
You can close it if it's not possible to pull like this. It's about just a small typo in https://docs.gradle.org/current/userguide/tutorial_using_tasks.html.

**Comment by jbartok** [comment]
Ok, it was simplest for me to just create another PR (https://github.com/gradle/gradle/pull/19156). But thank you for finding the typo.

**Comment by Anton-Vasilev** [comment]
I was happy to help. And sorry for the Inconvenience.

**Pull request closed without merging**
