### PR TITLE
Add Property upgrades interceptors stub

### PR DESCRIPTION
**Pull request by asodja**
Even though we don't have any interceptor yet, we try to initialize interceptor classes, but if they don't exist exception is thrown that has some performance impact.

Looks better vs 8.2-commit-c7ab13564eb:
https://builds.gradle.org/buildConfiguration/Gradle_Master_Util_Performance_AdHocPerformanceScenarioLinuxAmd64/65961947?buildTab=tests&suite=&package=org.gradle.performance.regression.java&status=passed&expandedTest=build%3A%28id%3A65961947%29%2Cid%3A5425

Fixes: https://github.com/gradle/gradle-private/issues/3851
Fixes: https://github.com/gradle/gradle-private/issues/3867

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test APT

**Review by lptr — APPROVED** [review]
Can we put this behind some flag, so our test branches can still make them work?

**Comment by asodja** [comment]
It looks like adding stub helps. see test for [99858b2](https://github.com/gradle/gradle/pull/25087/commits/99858b2a25e87ceff24cbc0d5e5f8b3596e731be):
https://builds.gradle.org/buildConfiguration/Gradle_Master_Util_Performance_AdHocPerformanceScenarioLinuxAmd64/65979692?buildTab=tests&suite=&package=org.gradle.performance.regression.java&expandedTest=build%3A%28id%3A65979692%29%2Cid%3A5443

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test APT

**Review by lptr — APPROVED** [review]
LGTM, would like to get feedback from @mlopatkin and/or @h0tk3y.

**Review by mlopatkin — APPROVED** [review]
lgtm!

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
