### PR TITLE
Use Adoptium for Toolchain auto-provisioning when possible

### LINKED ISSUE #20344: Toolchain cannot download JDK 18
Hello,

i have setup my project to use toolchains, but Gradle fails to download JDK 18 when running in Github Actions.
This is the error i get:

```
> Unable to download toolchain matching these requirements: {languageVersion=18, vendor=any, implementation=vendor-specific}
         > Unable to download toolchain. This might indicate that the combination (version, architecture, release/early access, ...) for the requested JDK is not available.
            > Could not read 'https://api.adoptopenjdk.net/v3/binary/latest/18/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk' as it does not exist.
```

### Expected Behavior
Gradle should be able to download JDK 18.

### Current Behavior
Gradle fails to download JDK 18.

### Context
I am trying to run tests for my project with Github Actions. Given my project will use JDK 8 and 18 to run tests via the Gradle toolchain feature, i haven't installed any JDK via Github Actions, since Gradle is supposed to be able to download them. 

I also use the [Gradle build action](https://github.com/gradle/gradle-build-action) which can cache the downloaded JDK, so it makes sense to let Gradle download the necessary JDK, keeping my workflow file simpler, and letting Gradle do its magic.

### Steps to Reproduce 
You can check my repo which is public: https://github.com/gotson/NightMonkeys/tree/ci
Running `gradle build` in an environment that doesn't have an installed JDK 18 will fail.

### Your Environment

[gradle.build file](https://github.com/gotson/NightMonkeys/blob/8a0d355aa0d8b545df8d9e4cf803609ef164fb79/imageio-jxl/build.gradle)
[Github Action run that failed](https://github.com/gotson/NightMonkeys/runs/5768501038?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #20344

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Review by octylFractal — APPROVED** [review]
LGTM!

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
