### PR TITLE
Build Init plugin: use configuration avoidance for task registration …

### PR DESCRIPTION
**Pull request by epeee**
…(kotlin part)

Signed-off-by: Erhard Pointl <epeee@users.noreply.github.com>

A follow up of  #12734

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFM

**Comment by eskatos** [comment]
Thanks for the PR @epeee. Could you please rebase it on top of `master`, your branch starts from a broken `master`.

**Comment by epeee** [comment]
@eskatos done

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
Thanks @epeee!

**Pull request merged**
