### PR TITLE
Add encoding property for zip task

### PR DESCRIPTION
**Pull request by AlphaHinex**
@bigdaz New PR for #405

### CODE REVIEW

**Comment by bigdaz** [comment]
Thanks @AlphaHinex. Looks pretty good. I just made a few suggestions for (minor) improvements to the test coverage. After that, we should be good to merge.

**Comment by bigdaz** [comment]
The travis-ci build is failing due to an unused import, and I've reiterated a comment about the need for a separate test for using an encoding that doesn't support the input file names.

Once that's done we'll be ready to merge.

**Comment by bigdaz** [comment]
Thanks @AlphaHinex. This has been merged into master, and will be in Gradle 2.8 (just missed the cut for 2.7, unfortunately).

I was thinking that it would be good to have similar support for the `Tar` task: are you interested in contributing that as well?

**Comment by AlphaHinex** [comment]
Thanks @bigdaz and I will try to do it

**Pull request merged**
