### PR TITLE
Better out-of-date message when tasks with actions declare no outputs

### PR DESCRIPTION
**Pull request by lptr**

### CODE REVIEW

**Comment by lptr** [comment]
Build: https://builds.gradle.org/viewQueued.html?itemId=11197173

**Comment by lptr** [comment]
Build: https://builds.gradle.org/viewQueued.html?itemId=11216286

**Comment by lptr** [comment]
Build: https://builds.gradle.org/viewQueued.html?itemId=11216680

**Comment by lptr** [comment]
> Should we check how the build scan plugin determines that the task is a lifecycle task? We better should not break that.

@ldaley WDYT?

**Comment by ldaley** [comment]
Scans use https://github.com/gradle/gradle/blob/301738c86f3dbbcb03f9ac187d2d20716de9dcfc/subprojects/core/src/main/java/org/gradle/api/internal/tasks/TaskStateInternal.java#L119

AFAICT, this is unchanged by this change set.

**Pull request merged**
