### PR TITLE
Enable CC load-after-store testing in `:kotlin-dsl-plugins` and `:kotlin-dsl-integ-tests`

### PR DESCRIPTION
**Pull request by eskatos**
* Fixed tests in `:kotlin-dsl-integ-tests`.
* Disabled tests in `:kotlin-dsl-plugins` because of https://github.com/gradle/gradle/issues/25483

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by abstratt — APPROVED** [review]
LGTM, thanks!

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
