### PR TITLE
Update embedded Kotlin version to 1.4.31

### LINKED ISSUE #16330: Upgrade embedded Kotlin to 1.4.31
See https://github.com/JetBrains/kotlin/releases/tag/v1.4.31

### PR DESCRIPTION
**Pull request by donat**
Fixes #16330

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Review by eskatos — APPROVED** [review]
:100:

**Pull request merged**
