### PR TITLE
Improving logic for matching J9 JVMs

### PR DESCRIPTION
**Pull request by jbartok**
Fixes: #16897

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle cancel

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test RFM

**Review by ljacomet — APPROVED** [review]

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
