### PR TITLE
Replace teneray operator with Optional API

### PR DESCRIPTION
**Pull request by britter**
Co-authored-by: Marc Philipp <marc@gradle.com>

### CODE REVIEW

**Comment by britter** [comment]
@bot-gradle please test this

**Comment by lptr** [comment]
Are you testing something?

**Comment by lptr** [comment]
I don’t think the change as is is making anything better. If at all, we are allocating slightly more with it, as we are creating one more `Optional` instance that we throw away immediately. It feels like using `Optional` just for the sake of using it.

What would be an improvement I think is if instead of using a field directly, we’d have `unpack.getResult()` return an `Optional`. It would still add the extra allocation, but at least the API of `Unpack` would be somewhat better as a result.

Either way it seems like a very small change I’m not sure worth implementing either way by itself.

**Comment by britter** [comment]
Makes sense!

**Pull request closed without merging**
