### PR TITLE
Fix Groovy and Java joint compilation failure on Java class private dependency change

### LINKED ISSUE #22531: Groovy and Java joint compilation failure on Java class private dependency change
When compiling Groovy and Java in joint compilation incrementally, Groovy compiler can fail with `NoClassDefFoundError`. 

Error from gradle/gradle: https://ge.gradle.org/s/nchdihafkxkzs.

Groovy compiler throws an error through reference:
ResolveTestFixture.configurationCacheEnabled -> GradleContextualExecuter -> AbstractDelegatingGradleExecuter -> AbstractGradleExecuter:

```
:internal-integ-testing:compileGroovy FAILED
startup failed: General error during conversion: java.lang.NoClassDefFoundError: org.gradle.integtests.fixtures.executer.AbstractGradleExecuter
```

A simple reproducer can be seen [here](https://github.com/gradle/gradle/blob/69b48824dd62c46530f1606f8901f1bc4166f4a1/subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskGroovyJavaJointIncrementalCompilationIntegrationTest.groovy#L29-L45).

This seems like an old issue that surfaced with latest changes to `ResolveTestFixture`. It happens because we delete `.class` files before we invoke Groovy compiler. But Groovy compiler wants to resolve some types when analyzing Groovy code. And if these types are from Java source, this can fail.

### PR DESCRIPTION
**Pull request by asodja**
General idea: if there is Groovy/Java joint compilation, we delete/stash files only just before Groovy runs Java compiler in [here](https://github.com/gradle/gradle/pull/22519/files#diff-5df77ba0e5a0123a434e2040725291330e3acd9a72c5c1c7576c4be8969c433a).

We split CompileTransaction in to [JavaCompileTransaction](https://github.com/gradle/gradle/pull/22519/files#diff-0a748b5e588dd9618cdf8c1d45ee74dcfc95e839616c6bd00dd9b805d89010bd) and [GroovyCompileTransaction](https://github.com/gradle/gradle/pull/22519/files#diff-ae65e45d006df8128e7b834a8c5f238857949ad20e0d41a962c095d20c1d88ba). The difference is, that GroovyCompileTransaction has this special logic for Groovy/Java joint compilation.

Fixes #22531.

### CODE REVIEW

**Comment by asodja** [comment]
This is already reproducible with at least Gradle 7.5, so it's an older bug that surfaced. Removing 7.6 milestone.

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
`CompileTransaction.java` was actually renamed to `AbstractCompileTransaction`, here is the diff if it helps in anyway:
```diff
33a34
+ import java.io.Serializable;
54,57c55
- /**
-  * A helper class to handle incremental compilation after a failure: it makes moving files around easier and reverting state easier.
-  */
- public class CompileTransaction {
---
+ public abstract class AbstractCompileTransaction implements CompileTransaction {
67c65
-     public CompileTransaction(
---
+     public AbstractCompileTransaction(
97c95
-         StashResult stashResult = stashFilesThatShouldBeDeleted();
---
+         StashResult stashResult = collectFilesThatShouldBeStashed();
98a97
+             doStashFiles(stashResult.stashedFiles);
113a113,114
+     abstract void doStashFiles(List<StashedFile> stashedFiles);
+ 
187c188
-     private StashResult stashFilesThatShouldBeDeleted() {
---
+     private StashResult collectFilesThatShouldBeStashed() {
195d195
-             moveFile(sourceFile, stashedFile);
256,257c256
-     private static class StashResult {
- 
---
+     private static class StashResult implements Serializable {
305c304,306
-     private static class StashedFile {
---
+     static class StashedFile implements Serializable {
+         private static final long serialVersionUID = 1L;
+ 
313a315,318
+         public void stash() {
+             moveFile(sourceFile, stashFile);
+         }
+ 
318a324
- 
```

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle cancel

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by wolfs** [comment]
I am not sure this is the right way to solve the problem. It seems that in order to do the AST analysis of a class which is not part of the current compilation unit, the Groovy compiler tries to load the class using the compilation classpath. Loading the class also means loading all dependent classes, without taking any visibility into account. So it seems like the Groovy compiler cannot deal with only recompiling the classes which need to be recompiled due to ABI changes within the same source location. I wonder if recompiling all classes which are affected by a change in the same compilation unit makes sense in that case and would be another solution to the problem.

Another thing we should be doing is to raise this problem with the Groovy team. Maybe the Groovy compiler fixes this in Groovy 4 and doesn't try to load classes any more.

**Comment by octylFractal** [comment]
After my investigation into the root cause of this, I think the alternative fix is safer -- leaving the old class around seems ripe for more strange issues, whereas the alternative fix basically reverts it to a normal compilation.

**Pull request closed without merging**
