### PR TITLE
Upgrade GroovyCompile to use lazy properties

### PR DESCRIPTION
**Pull request by donat**
Fixes https://github.com/gradle/gradle/issues/31200

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by asodja** [comment]
@bot-gradle test RFN

**Review by asodja — APPROVED** [review]
LGTM

**Pull request merged**
