### PR TITLE
Init task should support creating a directory for the new project with the specified path

### LINKED ISSUE #22625: Init task should support creating a directory for the new project
Creating a project with `gradle init` requires creating a project directory upfront. In most cases, the name of the directory is going to match the project name. In that case, the project name needs to be repeated at least 3 times to actually create the project:

```bash
mkdir my-new-project
cd my-new-project
gradle init --project-name my-new-project
```

The ability to force Gradle to create the new project in the new directory with the same name could potentially avoid a whole class of problems, such as https://github.com/gradle/gradle/issues/21867.

A solution to this could be an introduction of a new flag for the `init` task like `--project-directory`. This flag would ensure that the directory with the project name (`my-new-project`) is created if it doesn't already exist. The new project is then generated inside of this directory.

### PR DESCRIPTION
**Pull request by bodhili**
Fixes #22625 

### Context

- It is no longer necessary to create a new project directory
- any directory that does not contain a `settings.gradle.kts` file
- how to use： `gradle init  --project-directory=my-new-project-path`
- if the parameter `--project-directory` is not used, it is consistent with the previous version, using the directory where the command `gradle init` is executed as the project root directory; otherwise,  the directory specified by `--project-directory` is used as the root directory

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by bodhili** [comment]
@ghale please review. thanks

**Comment by bodhili** [comment]
@ghale Please review it for me, looking forward to your reply.  thanks

**Comment by alllex** [comment]
Thank you for the contribution!

I'll trigger the tests to see what's affected.

@bot-gradle test this

**Comment by bodhili** [comment]
@alllex  Well...  Since the initial submission of this PR, the version of gradle has been iteratively updated many times. Maybe this PR is not suitable for the latest version.

**Comment by ljacomet** [comment]
We are closing this since there has been no update in a while.

@bodhili Reply here if you want to pick this up or you can open a new PR

**Comment by bodhili** [comment]
> We are closing this since there has been no update in a while.
> 
> @bodhili Reply here if you want to pick this up or you can open a new PR

ok! thanks

**Pull request closed without merging**
