### PR TITLE
Provide a more reliable bytes “downloaded” metric

### PR DESCRIPTION
**Pull request by alkemist**
Please see commit message for rationale. This change is required to enable build scans to give some indication of network transfer rate.

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by alkemist** [comment]
@bigdaz how would you like to review this for me? You would?!? Great, thanks.

**Comment by alkemist** [comment]
@oehme or if you want to review it. I'm sure Daz wouldn't mind.

**Comment by bigdaz** [comment]
Sure, I can take a look

**Comment by facewindu** [comment]
@breskeby There are some failing tests in the branch. Could we sync up to go trough them?

**Pull request merged**
