### PR TITLE
Introduce some shared abstractions for build options, internal options and feature previews

### PR DESCRIPTION
**Pull request by adammurdoch**
Fixes #?

### Context

Introduce a service to determine the value of an internal option. This service lives with the `BuildOption` types. Refactor a bunch of places that were trying to figure out whether a system property might be set later in the build lifecycle to use this service.

Also move the feature preview service to live with these other types, and allow a feature preview to be enabled by a system property, for those previews that take effect before the settings script is executed, such as 'stable configuration cache'.

This way, an internal option is simply a build option that is not publicly advertised and a feature preview is a boolean build option that can be enabled in the DSL. Over time, these concepts should become more consistent, so that they can all be set persistently using a `gradle.properties` or the DSL, or dynamically calculated by build logic.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by adammurdoch** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
I think I fixed something.

@bot-gradle test and merge

**Comment by adammurdoch** [comment]
thanks

**Pull request merged**
