### PR TITLE
Avoid calling the Kotlin compiler for simple `plugins` blocks

### PR DESCRIPTION
**Pull request by bamboo**
By directly interpreting simple declarative plugins block.

This implementation is a simple state-machine based parser built atop the official Kotlin lexer to recognize simple `plugins` blocks containing a sequence of plugin requests, supporting `id(...) version "..." apply ...` and `kotlin(...) version "..." apply ...`:

```kotlin
plugins {
    id("plugin-id-1")
    id("plugin-id-2") version "1.0"
    id("plugin-id-3") apply false
    id("plugin-id-4") version "1.0" apply false
    kotlin("kotlin-id-1")
    kotlin("kotlin-id-2") version "1.0"
    kotlin("kotlin-id-3") apply false
    kotlin("kotlin-id-4") version "1.0" apply false
    // ...
}
```

----

Using version catalog aliases is not supported and falls back to calling the Kotlin compiler as usual:

```kotlin
plugins {
    alias(libs.plugins.jmh)
}
```

Given the current state of the version catalog support in the `plugins {}` block on the Kotlin DSL, see below issue, it sounds reasonable to postpone the support in the interpreter.

* https://github.com/gradle/gradle/issues/22797

----

Using plugin specs accessors is not supported and falls back to calling the Kotlin compiler as usual:

```kotlin
plugins {
    `java-library`
}
```

Supporting plugin specs accessors in the interpreter would be nice and is feasible but would require more changes to the script compilation flow to split the gathering of the accessible ones from their generation in order to feed the interpreter with them. This can be added incrementally later.

----

When encountering non declarative code or an unexpected token, the implementation falls back to calling the Kotlin compiler as usual.

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
On https://github.com/eskatos/huge-android-build-kotlin-dsl of ~5300 projects with a `buildSrc api change` scenario, build time is ~21% faster (from ~14m down to 11m), gc time is ~25% lower.

**Comment by bamboo** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
Still ~17% performance improvement on `buildSrc abi change` scenario with the `largeJavaMultiProjectKotlinDsl` template

https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestSlowLinux_Trigger/58214713:id/performance-test-results.zip%21/report/tests/buildSrc-abi-change---largeJavaMultiProjectKotlinDsl---BuildSrcApiChangePerformanceTest.html?redirectSupported=false

Still ~9% performance improvement on `first use` scenario with the  `largeJavaMultiProjectKotlinDsl` template

https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestSlowLinux_Trigger/58214713:id/performance-test-results.zip%21/report/tests/first-use---largeJavaMultiProjectKotlinDsl---JavaFirstUsePerformanceTest.html?redirectSupported=false

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
🎉

**Comment by nathan-contino** [comment]
Can we give more than 2 hours for a docs review in the future, or ping me if merging is urgent? I didn't even get a chance to read these changes before this PR merged :(

**Comment by eskatos** [comment]
Sorry about that Nate. Please take a look, if something needs fixing we can do so in a subsequent PR.

**Pull request merged**
