### PR TITLE
Clean up TestPreconditions

### PR DESCRIPTION
**Pull request by big-guy**
Remove preconditions that no longer make sense

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by rpygithub — APPROVED** [review]

**Review by leonard84 — APPROVED** [review]

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by leonard84 — APPROVED** [review]

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
