### PR TITLE
Extract more suggestions from error messages

### LINKED ISSUE #24568: Use consistent presentation for suggestions across Gradle
Depends on
- https://github.com/gradle/gradle/issues/24560
- https://github.com/gradle/gradle/issues/24510

This is a finalizer issue for moving suggestions from error messages under ` * Try:` in Gradle the error output. Below is the list of the identified snippets in Gradle that we should clean up:
- Build option
   - ~~[ ] [ParallelismBuildOptions](https://github.com/gradle/gradle/blob/59719502c13c133005601d00a8affd7793b81d90/subprojects/core/src/main/java/org/gradle/initialization/ParallelismBuildOptions.java#L68)~~
   - ~~[ ] [LoggingConfigurationBuildOptions](https://github.com/gradle/gradle/blob/808abba497f3d496c7c11bb02480469eceba731b/subprojects/logging/src/main/java/org/gradle/internal/logging/LoggingConfigurationBuildOptions.java#L127)~~
- Daemon
  - [x] [DaemonBuildOptions](https://github.com/gradle/gradle/blob/917a6278dc77c6c64aadec1bd88f28259f9a20a9/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonBuildOptions.java#L78)
  - [x] [DaemonClient](https://github.com/gradle/gradle/blob/a20a480bfdf73e5c94522b34ab327409c0bf78e3/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/client/DaemonClient.java#L172)
- Tooling API
  - ~~[ ] [Exceptions](https://github.com/gradle/gradle/blob/e1eff9140bd61335d408ccd98d0d4334db332b0f/subprojects/tooling-api/src/main/java/org/gradle/tooling/model/internal/Exceptions.java#L28)~~
- Precompiled script plugin
  - [x] [PrecompiledGroovyPluginsPlugin](https://github.com/gradle/gradle/blob/039b790a265054d33b90ba13a3b00f0315d4571a/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/internal/precompiled/PrecompiledGroovyPluginsPlugin.java#L44)
- Build cache
  - [x] [DefaultHttpBuildCacheServiceFactory](https://github.com/gradle/gradle/blob/8ad679896ea4ceaac1af6f3c3ba564aaeabba1dc/subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/DefaultHttpBuildCacheServiceFactory.java#L119)
- Script plugin
  - [x] [HttpScriptPluginIntegrationSpec](https://github.com/gradle/gradle/blob/7b670f1cc10fb080b18404d37cf310e2772dd276/subprojects/core/src/integTest/groovy/org/gradle/api/HttpScriptPluginIntegrationSpec.groovy#L96)

There might be multiple places where the suggestions should be moved (e.g. build option), but the list should give a fair clue on where we should clean up the suggestions.

### PR DESCRIPTION
**Pull request by donat**
Fixes #24568

This PR moves more suggestions from the error message to the suggestions (i.e. the bit after `* Try:`)

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Review by lptr — APPROVED** [review]
LGTM.

**Review by eskatos — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@eskatos @lptr thanks for the review!

**Comment by donat** [comment]
@bot-gradle test and merge

**Pull request merged**
