### PR TITLE
CCH22-1: Adjust the snippets/artifacts/defineRepository sample for configuration cache

### PR DESCRIPTION
**Pull request by dmarin**
Checking directly the local variable repoNames as it is done in the kts version

### CODE REVIEW

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Comment by bamboo** [comment]
@bot-gradle test this

**Review by bamboo — APPROVED** [review]
🎉

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by dmarin** [comment]
Updated the branch with master 🤞

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Pull request merged**
