### PR TITLE
Upgrade War plugin API to use lazy properties

### PR DESCRIPTION
**Pull request by lptr**

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by lptr** [comment]
@bot-gradle test this.

**Comment by lptr** [comment]
@bot-gradle test this.

**Comment by lptr** [comment]
@bot-gradle test this.

**Pull request merged**
