### PR TITLE
Remove @Unroll from most tests

### PR DESCRIPTION
**Pull request by big-guy**
This was generated by creating a list of files to modify with:
```
git grep --name-only -e '@Unroll$' -- subprojects/*/src/*Test/groovy subprojects/*/src/test*/groovy build-logic/ >> list
```

This restricted the modified files to only those in build-logic and test related Groovy classes. It also only identified files that had a `@Unroll` without anything after it.

I then deleted all the `@Unroll` lines with:
```
cat list | xargs -L1 gsed -i '/.*@Unroll$/d'
```
And then deleted all the imports for `@Unroll`:
```
cat list | xargs -L1 gsed -i '/import spock.lang.Unroll$/d'
```

I had to then manually update a dozen classes to fix any place where a class had both a `@Unroll` and a `@Unroll("...")` since we removed the import for those classes too. I removed the `@Unroll(...)` and renamed the method if necessary.

I also had to fix a dozen classes that were missing `def` at the start of the test method. Apparently that worked as long as you had a `@Unroll` before the method.

There are still ~74 places with `@Unroll` mentioned, but those appear to be almost all cases of `@Unroll(...)` and would need to be fixed manually.

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
Thank you @big-guy! I looked through the changes and removed some double empty lines. There was also one test which needed fixing, since it relied on a line number.

Finally, there is `can run spock with @Unroll`. I am not sure if we should remove the unroll there or not.

I'd like to merge this, so the huge Unrolls are out of the way and we can do follow-up PRs for the smaller ones.

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle cancel

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
