### PR TITLE
Cleanup snippets directory structure

### PR DESCRIPTION
**Pull request by donat**
Some snippets are under `docs/src/snippets` and some are under `docs/src/snippets/userguide`. All samples are used in the same way, so there's no reason for the distinction. This PR moves all snippets to the`docs/src/snippets` directory.

My ultimate goal here is to provide a consistent directory structure. Initially, I had the idea to flatten the snippets directory, but that might be an overkill. The alternative is to use the following structure: `docs/src/snippets/${snippet-category}/${concrete-snippet}`. @big-guy @rieske WDYT?

### CODE REVIEW

**Comment by donat** [comment]
Current state passes CI: https://builds.gradle.org/viewLog.html?buildId=33996315&tab=buildResultsDiv&buildTypeId=Gradle_Check_Stage_ReadyforMerge_Trigger&branch_Gradle_Check=donat%2Fflatten-snippets

**Comment by donat** [comment]
To verify my changes, I've run `userguideMultiPage` with and without my changes and compared the content of the `docs/build/working/usermanual/final` directory. They are identical.

**Comment by rieske** [comment]
What I was wishing for when working with documentation together with snippets was a structure that would make it straightforward to map and navigate from a specific documentation page to a snippet used in that page.
Given a documentation page `docs/foo/bar.adoc`, its snippets living in `snippets/foo/bar/`.
I guess such a structure would break if/when we want to share the same snippet for multiple documentation pages.

**Comment by donat** [comment]
That is indeed a good suggestion. I think this should be the default convention. I haven't seen a snippet that we referenced more than one time.

**Pull request merged**
