### PR TITLE
Kotlin dsl cid is a system property

### PR DESCRIPTION
**Pull request by 6hundreds**

### CODE REVIEW

**Comment by eskatos** [comment]
The CID being provided by the TAPI client, the IDE, this would need the IDE to be changed to use a system property and would require coordination with IDE vendors so that they use a system property starting with a given Gradle version. Correct?

**Comment by 6hundreds** [comment]
> The CID being provided by the TAPI client, the IDE, this would need the IDE to be changed to use a system property and would require coordination with IDE vendors so that they use a system property starting with a given Gradle version. Correct?

I'm not sure that IDE should be changed then, since we are declaring a way how cid is propagated, in a `KotlinBuildScriptModelRequest` file in `ProjectConnection.modelBuilderFor(parameters: FetchParameters)`

**Comment by eskatos** [comment]
The correlation ID is only used for the legacy script dependency resolver. This is used by IntelliJ on unknown scripts via the `@ScriptTemplateDefinition` annotation when you click on `Load script configuration`. But this integration has seen lots of changes on the IJ side since it was introduced. You might still want to double check with the JB team.

**Comment by 6hundreds** [comment]
@paul-eeoc As an alternative, if we keep `cid` as a project property, but adding some logic to ignore it (see https://github.com/gradle/gradle/pull/26385) then we won't break any compatibility. Does it preferable way?

**Comment by bamboo** [comment]
@eskatos would you expect the `cid` to be set on TAPI requests happening during _sync_?

**Comment by eskatos** [comment]
I would not expect it but given this has been reworked on the IJ side I think it's better to just ask them about it to prevent any surprise.

**Pull request closed without merging**
