### PR TITLE
Clarify kotlin dsl plugins block interpreter unsupported syntax

### PR DESCRIPTION
**Pull request by eskatos**
By showing actual examples of what is not supported.

Rendered release notes
https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/61086734:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20230202072942%2B0000/docs/release-notes.html#improved-script-compilation-performance

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test BD

**Comment by vlsi** [comment]
Could you please clarify if `id("java-library") apply false` is supported?
Is there a property so it emits a warning when it runs into an unsupported syntax?

**Comment by ephemient** [comment]
Thanks, the examples do help.

**Review by ephemient — APPROVED** [review]

**Comment by eskatos** [comment]
@vlsi this is case `<2>` in the snippet

image

**Comment by eskatos** [comment]
@vlsi there's a debug log when it falls back to the Kotlin compiler

**Comment by vlsi** [comment]
@eskatos , by the way, have you noticed a missing `"` after `1.0` in `version "1.0 apply`?

Well, the item `<2>` mentions both `version` and `apply`, and it is not clear if `just apply false` is supported.
For instance, `<1> ` looks the same as `<2>`, however, the doc explicitly mentioned `<2>` case, so I it might be that plain `apply` were not supported.

**Comment by eskatos** [comment]
Yes, the missing `"` was fixed in 8.0 RC2, the screenshot above is from the RC1 release notes.

Item <2> says "with version **and/or** the plugin application flag". That includes the 3 possibilities, just version, just apply-false, or both. You're saying that we should list all those explicitly in the snippet?

**Comment by vlsi** [comment]
> Item <2> says "with version and/or the plugin application flag"

Well, I somehow missed that. Now as you point it, it is clear. Sorry for the confusion.

**Comment by eskatos** [comment]
@bot-gradle test BD

**Review by ljacomet — APPROVED** [review]

**Pull request merged**
