### PR TITLE
fix(file-collections): declare parameter as nullable; #22645

### LINKED ISSUE #22645: API: parameter is marked not-null while explicitly allowing null
### Expected Behavior

I expect the method to declare `@Nullable` on its parameter, like the super and actual implementation do.

### Current Behavior

The method does not declare its parameter as `@Nullable`.

### Context

This method (which is what `DirectoryProperty` inherits from) does not declare its parameter as `@Nullable`. In the implementation, it just calls the parent...

https://github.com/gradle/gradle/blob/b354be64009fc84aca19a0b072562b93ae1afe32/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java#L242-L246

... which is:

https://github.com/gradle/gradle/blob/b354be64009fc84aca19a0b072562b93ae1afe32/subprojects/model-core/src/main/java/org/gradle/api/internal/provider/DefaultProperty.java#L103-L111

... and is documented:

https://github.com/gradle/gradle/blob/b354be64009fc84aca19a0b072562b93ae1afe32/subprojects/core-api/src/main/java/org/gradle/api/provider/Property.java#L121-L135

### Steps to Reproduce 

See above code; this is an API issue.

### Your Environment

I use Gradle 7.5.1, and this is still present in `master` (as of writing); links to code are above.

### PR DESCRIPTION
**Pull request by Proximyst**
Declares a parameter in `DefaultFilePropertyFactory.AbstractFileVar` as `@Nullable`, as its superclass (`DefaultProperty`) defines it to be.

Fixes #22645.

### Context

A method was incorrectly unannotated with `@Nullable`, resulting in IDE warnings (and presumably even breaking Kotlin code); this fixes that fact.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Review by big-guy — APPROVED** [review]

**Review by octylFractal — APPROVED** [review]

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by octylFractal** [comment]
Thank you for your contribution!

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
👀

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
