### PR TITLE
Update build scan plugin to 1.13.1

### PR DESCRIPTION
**Pull request by guylabs**

### CODE REVIEW

**Comment by wolfs** [comment]
I think we also need to update the version here: https://github.com/gradle/gradle/blob/850cd9b5412b44694551d99c5f3c0122812511dc/buildSrc/subprojects/profiling/profiling.gradle.kts#L10

**Comment by wolfs** [comment]
And this should probably be removed: https://github.com/gradle/gradle/blob/263845859b94f5ec28e50a6a89349e5e643ffdbd/buildSrc/build.gradle.kts#L114

**Comment by guylabs** [comment]
I adapted the pull request and will incorporate the `gradle/buildSrc/subprojects/profiling/profiling.gradle.kts` update into our release process. Thanks for the review!

**Comment by wolfs** [comment]
I made some changes on `release` so we don't use a snapshot version for the build scan plugin anymore there: https://github.com/gradle/gradle/pull/5005

As soon as this is merged to `master`, I guess this PR will need to be re-adjusted. For example, changing `gradle/init-scripts/build-scan.init.gradle.kts` will not be necessary any more.

**Comment by guylabs** [comment]
Wanted to merge it during the commit freeze but then this got out of sight. Merging it now. Thanks @blindpirate for the ping!

**Comment by blindpirate** [comment]
Thanks @guylabs !

**Pull request merged**
