### PR TITLE
Enable @Unroll automatically on tests

### PR DESCRIPTION
**Pull request by bmuskalla**
* Use [spock-global-unroll](https://github.com/szpak/spock-global-unroll) to have `@Unroll` enabled by default on any Spock test
* Remove most `@Unroll` annotations in favor of test name
* `@Unroll` can still be used if necessary
* `@Roll` can explicitly be used to opt-out

### CODE REVIEW

**Comment by blindpirate** [comment]
Can we also have this in our build: https://github.com/gradle/dotcom/blob/6cbf88c11d7e1adbf37647d657b2bf72f53c60b6/testlib-base/src/main/groovy/com/gradle/testbase/spock/UniqueNameProvider.groovy

Context: if developers accidentally have `@Unroll`ed tests with same names, something might be broken in the build.

**Comment by bmuskalla** [comment]
@bot-gradle test QF

**Comment by bmuskalla** [comment]
@bot-gradle test QF

**Comment by bmuskalla** [comment]
@bot-gradle test QF

**Comment by bmuskalla** [comment]
@bot-gradle test QF

**Comment by bmuskalla** [comment]
@bot-gradle test RFM

**Comment by bmuskalla** [comment]
@bot-gradle test QFL

**Comment by bmuskalla** [comment]
@bot-gradle RFM

**Comment by bmuskalla** [comment]
@bot-gradle test RFM

**Comment by bmuskalla** [comment]
Closing this for now while I focus on other things. Will reopen once I have some time to tackle this

**Pull request closed without merging**
