### PR TITLE
Add Daemon toolchain TAPI cross version tests

### PR DESCRIPTION
**Pull request by vmadalin**
### Context
This PR represents the continuation of the initial proposed PR https://github.com/vmadalin/gradle/pull/47 of adding TAPI tests by reusing the same tests via specific CLI and TAPI executor to avoid duplicating the tests. However, this now follows the Gradle cross-version tests but also is more aligned with the [shared guidelines](https://github.com/gradle/gradle/pull/29222) even if that requires duplicating them. 

#### Testing
Integration tests:
[DaemonToolchainCoexistWithCurrentOptionsCrossVersionTest.groovy](https://github.com/gradle/gradle/pull/29252/files#diff-31ae7ef28846ca5a37fb63ec5c1e4be3ed99db84c401382a6b507f4c3244708b)
[DaemonToolchainCrossVersionTest.groovy](https://github.com/gradle/gradle/pull/29252/files#diff-86c7b3ad2aaf456e2918c03efe4d3a1ca13d8869db4637920cb5eff01a942d6f)
[DaemonToolchainInvalidCriteriaCrossVersionTest.groovy](https://github.com/gradle/gradle/pull/29252/files#diff-2ac2f8f176e341f9d6628a451ba31f02c89473d4563cd857d7b0284739be31d0)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### CODE REVIEW

**Comment by ljacomet** [comment]
Thank you for your contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the design of the implementation choices.

**Comment by ljacomet** [comment]
@gradle/bt-ide-experience Please coordinate with @big-guy who has been following this work

**Comment by reinsch82** [comment]
@bot-gradle test ACTR

**Comment by vmadalin** [comment]
@blindpirate Thank you for triggering the tests, however, since the `BuildEnvironment` change is broking quite some tests I considered to better keep it separate so any issue can be addressed separately

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle merge

**Comment by big-guy** [comment]
@bot-gradle merge

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle merge

**Pull request merged**
