### PR TITLE
Ensure completed() and failure() does not error for skipped tests

### PR DESCRIPTION
**Pull request by gaiazov**
### Context

When a test class completes, all the in-progress tests have their `TestState` set to `SKIPPED`. In some cases, there can be a race condition between an in-progress test getting marked as `SKIPPED` and the test actually completing/failing. This can happen, for example, due to the test class having a timeout class rule.

The solution is for `StateTrackingTestResultProcessor` to keep track of which tests have been skipped, and short-circuit if these tests try to `completed()` or `failure()` later.

A better solution would be to ensure that the test class `completed()` is called **after** the test  `completed()`. But it looks like that's how JUnit4 works, and the test `completed()` is called after the test class `completed()`

Issue: #8112

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
@marcphilipp is this something you can weigh in on?

**Comment by marcphilipp** [comment]
Sure, I'll take a look.

**Comment by marcphilipp** [comment]
Moreover, the new test failed in the build:
https://builds.gradle.org/viewLog.html?buildId=19063155&tab=buildResultsDiv&buildTypeId=Gradle_Check_Platform_Java11_Openjdk_Windows_testingJvm

@gaiazov Could you take a look and let me know if you need help?

**Comment by marcphilipp** [comment]
@gaiazov Do you have time to continue to work on this issue or shall I take over?

**Comment by big-guy** [comment]
@marcphilipp This looks like a useful thing to have, but if it's not quick to finish, I would close the PR.  We can always open it again if there's interest again.

**Comment by marcphilipp** [comment]
@gaiazov Closing for now. Feel free to reopen should you find the time.

**Pull request closed without merging**
