### PR TITLE
Obtain types for JDK classes when generating accessors

### LINKED ISSUE #22968: Kotlin DSL generated accessors for JVM types are typed Any, should be typed properly instead
### Expected Behavior

Gradle Kotlin DSL generated accessors for JVM types, e.g. a Project extension whose type is declared in the JDK, should be propertly typed.

### Current Behavior

They are considered inaccessible and thus typed `Any`.
Types from the Kotlin stdlib are currently working (e.g. `List`), so this is really about types from the JDK that aren't handled by the Kotlin stdlib.

See `AccessorsClassPath.loadAccessibilityInfoFor(className: String): TypeAccessibilityInfo`

### Context

* https://github.com/gradle/gradle/pull/22967

### Steps to Reproduce 

See the reproducer test introduced in https://github.com/gradle/gradle/pull/22967/commits/b4e04649927d775d1aac2f77b9a4e54a5429b2ea

### PR DESCRIPTION
**Pull request by jbartok**
* Fix #22968
* Fix https://github.com/gradle/gradle/issues/10771

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test APT

**Comment by jbartok** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
@bot-gradle test this APT

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test APT

**Review by eskatos — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
