### PR TITLE
Update smoke tested plugin versions

### PR DESCRIPTION
**Pull request by cobexer**
### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by cobexer** [comment]
@bot-gradle test AST

**Comment by cobexer** [comment]
@bot-gradle test AST

**Comment by cobexer** [comment]
@bot-gradle test AST

**Comment by cobexer** [comment]
@bot-gradle test AST

**Comment by cobexer** [comment]
@bot-gradle test AST

**Comment by cobexer** [comment]
@bot-gradle test AST

**Comment by cobexer** [comment]
@bot-gradle test AST

**Review by ov7a — APPROVED** [review]

**Pull request merged**
