### PR TITLE
8.0 notes polish

### PR DESCRIPTION
**Pull request by hythloda**
[slack conversation](https://gradle.slack.com/archives/C03GCM93XCG/p1675358288432069)

[Here are the rendered docs to view](https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/61128171:id/distributions/gradle-8.0-all.zip!/gradle-8.0-20230202180743%2B0000/docs/release-notes.html)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by hythloda** [comment]
@bot-gradle test BD

**Comment by hythloda** [comment]
[Here are the rendered docs to view](https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/61128171:id/distributions/gradle-8.0-all.zip!/gradle-8.0-20230202180743%2B0000/docs/release-notes.html)

**Comment by hythloda** [comment]
@FrauBoes tagging you for approval since you are doing the release tomorrow.

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
