### PR TITLE
Align versions of all Kotlin components in generated projects

### PR DESCRIPTION
**Pull request by mig4**
This means newly generated Kotlin projects (using `gradle init`) will
import version recommendations for all Kotlin components from a BOM file
published upstream, which should ensure uniform versions across direct
and transitive dependencies.

This is done using platform dependencies introduced in Gradle 5.0.

### Context

In a Kotlin project generated with `gradle init` we depend on Kotlin and its stdlib at a given version. If a user then adds a dependency on another library that depends on more Kotlin components like `kotlin-reflect` at another version, the build will warn that we're using mismatched versions of Kotlin components.

For example, to a `build.gradle.kts` generated with `gradle init --dsl kotlin --type kotlin-application` add dependency on _fuel-jackson_ (which depends on _kotlin-reflect_):

``` kotlin
implementation("com.github.kittinunf.fuel:fuel-jackson:2.0.1")
```

when `gradle build` is run it will produce:

```
> Task :compileKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/mig/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.3.21/d0634d54452abc421db494ad32dd215e6591c49f/kotlin-stdlib-jdk8-1.3.21.jar (version 1.3)
    /home/mig/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.21/d207ce2c9bcf17dc8e51bab4dbfdac4d013e7138/kotlin-stdlib-jdk7-1.3.21.jar (version 1.3)
    /home/mig/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.2.51/36b719a7b84452dd13eeec979d8c82bfb765c57d/kotlin-reflect-1.2.51.jar (version 1.2)
    /home/mig/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.21/4bcc2012b84840e19e1e28074284cac908be0295/kotlin-stdlib-1.3.21.jar (version 1.3)
    /home/mig/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.21/f30e4a9897913e53d778f564110bafa1fef46643/kotlin-stdlib-common-1.3.21.jar (version 1.3)
w: Consider providing an explicit dependency on kotlin-reflect 1.3 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
```

By adding a platform dependency - `implementation(platform("org.jetbrains.kotlin:kotlin-bom"))` - Gradle will ensure to align versions of components pulled in transitively without having to add a direct dependency. Since this is a rather safe thing to do, my thinking is we can just do this by default for newly generated projects.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective **--** existing tests cover this change
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes **--** current docs don't go into that level of detail, they just say we add a dependency on Kotlin, which seems OK
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by adammurdoch** [comment]
Thanks for the PR. Your changes look good to me. Would you be able to also update the Kotlin Gradle plugin template as well to add the platform dependency (in KotlinGradlePluginProjectInitDescriptor)?

**Comment by mig4** [comment]
Sure, just rebased and I'm going to have a look.

**Comment by mig4** [comment]
Done.

**Comment by adammurdoch** [comment]
Thanks for making the changes. We'll merge the PR soon.

**Comment by adammurdoch** [comment]
Merged, thanks again.

**Pull request merged**
