### PR TITLE
Improve arch test for Map/List/SetProperty

### PR DESCRIPTION
**Pull request by ov7a**
### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Review by asodja — APPROVED** [review]
LGTM

I see report is not any different in the end. But I think it's good we are more explicit

**Comment by ov7a** [comment]
@asodja I'd love to change the message, but this means refreezing the accepted violations (and generating conflicts). If you fine with that, I can update the PR

**Comment by asodja** [comment]
What did you have in mind for the changed message?

I can solve conflicts in that case, since it would mean I would just need to refreeze accepted changes a couple of times

**Comment by ov7a** [comment]
@asodja see the commit - I've added the explicit return type and a list of all possible types

**Review by asodja — APPROVED** [review]

**Pull request merged**
