### PR TITLE
Fix plugin application order (#15664)

### LINKED ISSUE #15664: Application order of plugins in plugins block should be deterministic
Builds should be deterministic, and sometimes (unfortunately, undesirably), plugins are written poorly and create ordering issues. In such a scenario it should be possible for a user to ensure deterministic application of plugins, based on the order in which they're added to the `plugins` block. However, under certain circumstances, it seems that the order of declaration in the plugins block does not fully determine the order in which those plugins are actually applied by gradle.

### Expected Behavior
Given something like this:
```groovy
// subproject/build.gradle
plugins {
  id 'a' version ...
  id 'b' version ...
}
```
Plugin `'a'` should always be applied before plugin `'b'`.

### Current Behavior
If instead of the above we have the following:
```groovy
// root build.gradle
buildscript {
  dependencies {
    classpath 'coordinates for plugin a'
  }
}

// subproject/build.gradle
plugins {
  id 'a'
  id 'b' version ...
}
```
Then I see plugin `'b'` applied first.

### Context

I was actually just trying to explore how the build classpath works in gradle builds, and was experimenting with different ways of specifying plugins and then looking at build scans to help visualize the classpaths. This issue was unexpected. I asked about it in the [gradle community slack](https://gradle-community.slack.com/archives/CA7UM03V3/p1609220513181600) as well as the [kotlin-lang slack](https://kotlinlang.slack.com/archives/C0B8M7BUY/p1609270592104400). 

Ultimately, I'm filing this issue because it seems incorrect that the application order of plugins isn't deterministic.

### Steps to Reproduce 

Given the following scenario:

```groovy
// root build.gradle
buildscript {
  repositories {
    google()
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:4.2.0-alpha15'
  }
}

// subproject/build.gradle
plugins {
  id 'com.android.application'
  id 'org.jetbrains.kotlin.android' version '1.4.21'
}
```
Execute `./gradlew help` and observe it fails with:
```
* What went wrong:
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.android', version: '1.4.21']
> Failed to apply plugin 'org.jetbrains.kotlin.android'.
   > Extension with name 'android' does not exist. Currently registered extension names: [ext, kotlin, kotlinTestRegistry]
```

I am almost certain this is an ordering issue. When I run `./gradlew help -d` and examine the logs, I can see that, in this case, only the Kotlin plugin is ever applied, and it fails, as the Android plugin has not yet been applied and therefore has not yet added the `"android"` extension. This despite the fact that the Android plugin is added first in the `plugins` block. If instead of the above we have
```groovy
// root build.gradle
buildscript {
  repositories {
    google()
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:4.2.0-alpha15'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21"
  }
}

// subproject/build.gradle
plugins {
  id 'com.android.application'
  id 'kotlin-android'
}
```
Then `./gradlew help` succeeds, and `./gradlew help -d` shows that the Android plugin is applied before the Kotlin plugin.

**I am not proposing that this is a normal build script configuration. My point is that plugin application order should be deterministic, and should not depend on how the artifact coordinates are specified (explicitly vs implicitly).** Alternatively, I would like to know if this is expected behavior and, if so, why.

### Your Environment

Build scan URL (successful build): https://scans.gradle.com/s/leiuzdoz4i6k2
Build scan URL (failed build): https://scans.gradle.com/s/t7w3bwv3pingm

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #15664

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- n/a Provide unit tests (under `<subproject>/src/test`) to verify logic
- n/a Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Review by ljacomet — APPROVED** [review]
Could you look into adding an entry in the potential breaking changes in the release notes?

This might effectively impact builds that crafted their plugin declaration order and logic according to the previous "rules".

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by Vampire** [comment]
I can sure add such a note, but I guess not in the release notes, but in the upgrade guide, right? (see the confusion I meant in Slack? :-) )

Do you maybe an idea about the failing test?
I indeed can reproduce the failure here. If I run that failing test, I get the same error after 3 hours:
```
Condition failed with Exception:

validatePlugins()
|
java.lang.IllegalStateException: The following plugins were validated but you didn't explicitly check the validation outcome: [org.asciidoctor.gradle.jvm.AsciidoctorJPlugin]
	at org.gradle.smoketests.WithPluginValidation$AllPluginsValidation.performValidation(WithPluginValidation.groovy:122)
	at org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest.validatePlugins(GradleBuildExternalPluginsValidationSmokeTest.groovy:82)
	at org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest.performs static validation of plugins used by the Gradle build(GradleBuildExternalPluginsValidationSmokeTest.groovy:73)

	at org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest.performs static validation of plugins used by the Gradle build(GradleBuildExternalPluginsValidationSmokeTest.groovy:73)
Caused by: java.lang.IllegalStateException: The following plugins were validated but you didn't explicitly check the validation outcome: [org.asciidoctor.gradle.jvm.AsciidoctorJPlugin]
	at org.gradle.smoketests.WithPluginValidation$AllPluginsValidation.performValidation(WithPluginValidation.groovy:122)
	at org.gradle.smoketests.GradleBuildExternalPluginsValidationSmokeTest.validatePlugins(GradleBuildExternalPluginsValidationSmokeTest.groovy:82)
	... 1 more
```

**Comment by ljacomet** [comment]
Yes in the upgrade guide 😉 
I am not sure I fully understand the failure. Adding that plugin into the ones validated on current main branch does not fail the test. So I suggest you just add it next to the other asciidoc entries.

**Comment by Vampire** [comment]
Do you mean to the list of ids in the `passingPlugins` closure? (I'm not sure what that test is actually doing, so I'm not sure how to properly fix it or if I understood correctly what you mean)

**Comment by Vampire** [comment]
In case I did get you correctly, a new push is there, also including the breaking section

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@Vampire Thank you for the contribution!

**Comment by TWiStErRob** [comment]
@big-guy I was looking for a mention of this in the release notes: https://gradle.org/releases/, but it's not showing there. Is it because of the 7.3-RC1 milestone?

**Comment by ljacomet** [comment]
There is an indirection: because this impacts anyone upgrading across the 7.2 / 7.3 boundary, it is documented in [upgrade notes](https://docs.gradle.org/7.3/userguide/upgrading_version_7.html#changes_7.3) which is linked from release notes.

**Comment by TWiStErRob** [comment]
@ljacomet but the issue/PR is not mentioned in the list of fixes, is it intentionally excluded?

**Pull request merged**
