### PR TITLE
Add new '--profile-as-json' option for outputing profile data in JSON

### PR DESCRIPTION
**Pull request by steffenyount**

### CODE REVIEW

**Comment by bmuschko** [comment]
Initial discussion started on the Gradle forum: https://discuss.gradle.org/t/add-new-profile-as-json-option-for-outputing-profile-data-in-json/16621

**Comment by bmuschko** [comment]
Hi @steffenyount, thanks for the contribution. As proposed in the Gradle forum post, would you mind opening a discussion on the Gradle dev list?

I was wondering if you signed the CLA before. I have an entry in our list of signed CLAs with your last name but a slightly different first name. Could you please provide your email address so I can verify?

**Comment by steffenyount** [comment]
re-posted

**Comment by alkemist** [comment]
Hi @steffenyount ,

After some internal discussion and direct discussion with yourself at the Gradle Summit 2016, we've decided not to incorporate this functionality into the core. Instead, we'd like to suggest that you implement this functionality as an external plugin. If you need any advice on how to do this please let us know via the forums and we'll help as much as we can.

I apologise for the long turnaround on this and any confusion caused.

**Comment by steffenyount** [comment]
I've finally found the time to refactor my change to what we agreed would be acceptable at the Gradle summit. But it seems this pull request has been closed so I can't update it here.

Please see my updated pull request: #670

The conditions were:
1. The feature is hidden behind a secret system property ('org.gradle.profile.ProfileAsJsonReportRenderer.enabled')
2. The JSON report is rendered using the Gson libraries.

Thanks.

**Comment by orafaaraujo** [comment]
Hi, everyone 

I saw that this PR was dropped and asked to add it as a plugin, but I can't find any.

Does someone have a recommendation?

Thanks in advance

**Pull request closed without merging**
