### PR TITLE
GRADLE-3182 Fix wrong single wildcard usage for files/directories match

### PR DESCRIPTION
**Pull request by bearmug**
Hi,
please review this for-fun fix, if JIRA ticket still valid. Let me know if patch review preffered

1. modified logic
 - match any file vs. single wildcard step# with '#' will be ignored, and an empty message aborts the commit.
 - match directory vs. single wildcard step if this directory is not last into the path
 - do not match directory vs. single wildcard if this directory is last element in path
 - on a negative side, now we can not filter directory content non-recursively for files and dirs both (with wildcard). This behavior available for files only, see SingleIncludePatternFileTreeSpec change for details. This change directly related to the issue nature. 

2. major code changes, this section mostly duplicates pull-request body
 - provide opportunity to filter with same approach for other PatternStep implementations
 - extend PatternStep.matches with isFile flag, use it to match single wildcard vs. file positively
 - extend PatternStepFactory.getStep with lastStep flag. Use this flag to match single wildcard vs. not-last-directory-element positively
 - enrich tests with introduced parameteres for PatternStep/PatternStepFactory

### CODE REVIEW

**Comment by mark-vieira** [comment]
@bearmug, for the most part (and as our documentation mentions) we are trying to mimic Ant behavior here. Can you confirm that this new behavior aligns with what Ant does?

**Comment by bearmug** [comment]
Hi @mark-vieira, I did revalidation against Ant 1.9.6
- yep, with the fix above, Gradle got closer to Ant for include('\*')/exclude('\*') statements 
- the only difference is that Gradle does not include 1st level empty dirs for include('\*') expression, see 'canUseSingleWildcardAsIncludes' test from pull-request. But this feature seen before,according to GRADLE-3182 description, don`t think we need fix or change it. Thanks!

**Comment by oehme** [comment]
Since this change will silently break existing builds, we decided not to merge it.

However, we would be very happy if you could document the current behavior instead. Would you be interested in submitting a PR for that?

**Comment by pioterj** [comment]
@bearmug After further discussion we decided we want to fix it after all. Could you resolve the conflicts? We also need to clearly document this as a potentially breaking change in the release notes. It would be great if you could do it too.

**Comment by bearmug** [comment]
@pioterj, @oehme,
appreciate this, thanks. Will do and pop back once ready.

**Comment by eljobe** [comment]
@bearmug Thanks for your contributions in this Pull Request. I am going to take it from here modifying the release notes and any affected design documents.

**Comment by eljobe** [comment]
So, bad news. This Pull Request (PR) actually caused a surprise regression in the behavior of `include "*"` Specifically, before this change a file hierarchy like this one:

src/
|_ dir/
   |_ file2.txt
|_ file1.txt

When copied with a copy task like this:
task cpy(type: Copy) {
    into 'dest'
    include '*'
    from 'src'
}

Would result in "dir" being an empty directory inside of "dest"
dest/
|_ dir/
|_ file1.txt

But, after this PR was merged in, the result was:
dest/
|_file1.txt

We are afraid someone might have been relying on the old behavior, and we don't think it makes sense for this part of the behavior to have changed for this PR.

For this reason, we had to revert the changes related to merging this into the release branch for 2.12 and will be releasing 2.12 without this fix. I'm also updating GRADLE-3182 to mention that it is not actually fixed.

Sorry we weren't able to take this Pull Request, but if you'd like to see it fixed and are willing to make sure that the include use-cases don't also regress next time, please submit a fresh PR and we'll take a look at getting it merged.

**Pull request merged**
