### PR TITLE
Prefer `KotlinCompile.compilerOptions` over `KotlinCompile.kotlinOptions`

### PR DESCRIPTION
**Pull request by eskatos**
`KotlinCompile.kotlinOptions` used JavaBean properties.
`KotlinCompile.compilerOptions` uses Gradle properties.

This is a follow up to
* #22027 

Wrapper update is necessary for the `kotlin-dsl` plugin update. A new wrapper update will be done post-merge to get rid of the branch snapshot.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by reinsch82 — APPROVED** [review]
LGTM
But I guess I shouldn't be the only one :)

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
