### PR TITLE
Fix a broken method from the signing subproject.

### PR DESCRIPTION
**Pull request by chrisgavin**
## Context
This method doesn't work. Note that `this.signatureType` is assigned `signatureType` rather than `type` (self-assignment).

#### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

#### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [x] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by bmuschko** [comment]
Good catch. Would you mind checking if there's a test for using the method `setSignatureType` and add one if it doesn't exist yet?

**Comment by chrisgavin** [comment]
I've realized that the method is still needed for use in DSL so I've fixed it and added a test as requested.

**Comment by w25r** [comment]
Hi @chrisgavin,

Why don't you think we should remove the method?  I'm not sure what you mean by `still needed for use in DSL`  Could you please elaborate?

**Comment by chrisgavin** [comment]
As I mentioned in my comment, I don't think the method should be removed: the Gradle DSL looks for a method with the name `signatureType` or Gradle files relying on it will not work. I most certainly think it should be fixed though so that the method works as expected though.

**Comment by w25r** [comment]
All the following calls in a .gradle file
```
signatureType = newType
signatureType(newType)
setSignatureType(newType)
```
delegate to the setSignatureType method, which works as expected.  I think only explicit calls from Java plugins may reach the flawed method.  As such, I'm tempted to remove it rather than fix it.

**Comment by chrisgavin** [comment]
Ah yes, I see what you mean. I have removed the method.

**Pull request merged**
