### PR TITLE
Support init type modifiers via the --with option

### PR DESCRIPTION
**Pull request by calid**
e.g. `$ gradle init --type java-library --with spock`

This patch adds support for generating the `java-library` init type using Spock instead of JUnit.  Additionally it adds a generic `withModifier` hook so that other ProjectInitDescriptor classes can implement their own modifiers as desired.

ref: https://groups.google.com/forum/#!topic/gradle-dev/gszYkhkMt0g

### CODE REVIEW

**Comment by calid** [comment]
CI failure seems down to Travis weirdness and not the patch.. 3/4 passed, 4th seems to have had VM issues .

**Comment by adrianbk** [comment]
@calid I've restarted the build on TravisCI

**Comment by calid** [comment]
@adrianbk awesome, thanks.  Looks like that did the trick.

**Comment by pioterj** [comment]
Thank you for the pull request. This is something that we would like to support. Would you mind updating the design document at https://github.com/gradle/gradle/blob/master/design-docs/build-initialisation.md? Creating or updating a design document is something that we do at Gradle for all non-trivial changes, especially when changing the behavior or public API. We would like to use the same standards for pull requests.

**Comment by calid** [comment]
@pioterj I've updated the design document.  I've also rebased the branch onto current master.

**Comment by pioterj** [comment]
Thank you. I should be able to look into it soon.

**Comment by pioterj** [comment]
Could you also update the user guide at update user guide page at https://docs.gradle.org/current/userguide/build_init_plugin.html?

**Comment by calid** [comment]
Hi Piotr, done

**Comment by pioterj** [comment]
It's merged. Thank you for the contribution. I'll do some refactoring now. It will be available in Gradle 2.11. If you are interested in contributing more it would be cool to add such modifier for TestNG too after the refactoring is done.

**Comment by calid** [comment]
@pioterj awesome, definitely.  Just give me a heads up when the refactoring is done and I'll go ahead and add the TestNG modifier.

**Comment by pioterj** [comment]
@calid Great. I committed the refactoring to master but there may be some additional changes after a code review. I'll let you know once this is completed (probably early next year due to holidays).

**Comment by calid** [comment]
Cool, no worries.  I'll still get started on this and I can always reshuffle the code if there's further refactoring necessary.

With this merged it opens the door for some other options I think would be nice (e.g. `gradle init --with gitignore`).  The [Contribution Guidelines](http://gradle.org/contribute-to-gradle/) recommend posting to the developer list first.  Should I still do this for non-major fixes/improvements, or can I open a PR directly?

**Comment by pioterj** [comment]
It's always a good idea to start with a discussion on the developer list, especially when changing the API. Adding gitignore modifier is less clear-cut than testng.

**Comment by calid** [comment]
Cool, I'll play it safe and stick with posting to the developer list first, thanks

**Comment by calid** [comment]
@pioterj just a heads up I noticed a very minor typo in [buildInitPlugin.xml](
https://github.com/gradle/gradle/blob/78cab2d4e85b495d971db9f24c5acdecbe122c9e/subprojects/docs/src/docs/userguide/buildInitPlugin.xml#L109), "Tu" should read "To"

**Comment by pioterj** [comment]
Fixed, thanks!

**Pull request merged**
