### PR TITLE
Define rootProject.name in all snippets and samples

### PR DESCRIPTION
**Pull request by donat**
This is a first step for cleaning up our snippets and samples. The PR ensures that all snippets/samples have a settings file with a `rootProject.name` configuration.

### CODE REVIEW

**Comment by big-guy** [comment]
@donat Could you split out the changes to remove the license headers? I think those can go straight in without much review. It looks like there are a lot fewer "real" changes (to add rootProject.name) here than it appears.

For the snippets/samples that use camel-case for the name of their root directory, are we going to make another pass to rename all of those directories to use kebab-case?  It looks like we have a few snippets where we use both camel-case and kebab-case in the same name.

**Comment by donat** [comment]
> @donat Could you split out the changes to remove the license headers?
OK, I'll create a separate PR for that.

> For the snippets/samples that use camel-case for the name of their root directory, are we going to make another pass to rename all of those directories to use kebab-case?
Absolutely. I'm working on it right now. I've just realized how many changes have to be made, so I'll create multiple PRs in order to make it easier for the reviewers.

**Comment by donat** [comment]
@big-guy I've extracted the license header cleanup change to #14181

**Comment by donat** [comment]
@bot-gradle test this

**Review by jjohannes — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test this

**Pull request merged**
