### PR TITLE
Clearly separate legacy artifact resolution path from modern path

### PR DESCRIPTION
**Pull request by jvandort**
DefaultLenientConfiguration implemented VisitedArtifactSet, the modern artifact resolution path. We now implement a separate DefaultVisitedArtifactSet to implement the modern path and create a new LegacyVisitedArtifactSet interface, which DefaultLenientConfiguration implements, to handle the legacy artifact resolution path.

This allows us to remove the dependency spec parameter from VisitedArtifactSet, making it clear that the modern path does not support filtering by dependency spec.

Furthermore, we add new interfaces to ResolverResults, clearly separating the modern results from the legacy results.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test apt

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
