### PR TITLE
Introduce connection pool to performance database

### PR DESCRIPTION
**Pull request by blindpirate**
We've seen performance database connection issues, let's
try connection pool.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
The change looks good from the code side of things. Though it seems like it is not passing CI, since the 30 second timeout seems to small for obtaining the flakiness data. Maybe we should improve the query for the flakiness data, so it is faster? Do we need more indices?

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@wolfs Thanks for review!

The failures were because that I didn't return database connection to connection pool via `Connection.close()`. It was fixed by correct [closing the connection](https://stackoverflow.com/questions/25367261/best-approach-for-returning-connection-objects-to-hikaricp-pool). The database performance itself was not bad:

- ~600ms for write execution data
- ~700ms for querying flakiness data

**Pull request merged**
