### PR TITLE
Update groovy from 3.0.7 to 3.0.8

### PR DESCRIPTION
**Pull request by koppor**
Refs https://github.com/gradle/gradle/issues/16857

### Context

JDK17 is coming. When using Groovy in Gradle, JDK17 does not work.

See https://github.com/gradle/gradle/issues/16857#issuecomment-851785870.

### Contributor Checklist

- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck` --> can't do, because of ` Dependency verification failed for configuration ':build-logic-settings:allprojects-plugin:classpath'`. Not sure how to resolve that.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
The changes had to be reverted because this PR missed a couple locations. Also when these locations are updated, tests fail. Investigating.

**Comment by koppor** [comment]
@ljacomet Thank you for the follow up. I naively used the "find in all files" functionality of IntelliJ. Sorry for the effort caused. My motivation was to make Gradle ready for JDK17.

**Comment by ljacomet** [comment]
No worry, you can look at the follow up on this in #17712 
Unfortunately, Groovy 3.0.8 has a number of regressions that affect our test code. And we need to make sure they would not affect Gradle build scripts or plugins.

**Pull request merged**
