### PR TITLE
Replace custom SSLContext lookup with Apache HTTP SSLContexts

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
### Context

PR fixes https://github.com/gradle/gradle/issues/1782

This is an important update to how Gradle obtains `SSLContext` for its HTTP connections.

ATM, code is using copy-paste from Apache HTTP Client 4.2.2 which was released on Oct 23, 2012 and has custom CA certs lookup that is broken on modern JDK distributions, see #1782 

Release of Apache HTTP Client 4.2.4 (Apr 10, 2013) changed SSLContext lookup to rely on `SSLContext.getInstance("TLS")`, **however Gradle copy was not updated**.

Original change in Apache HTTP Client https://github.com/apache/httpcomponents-client/commit/4d2f49bb6dee02c36c6f234e2cf347fcee11e5dc#diff-2b61663f90e19b0024cea23ce9e5e791

---

PR relies on public `SSLContexts` utility provided by Apache HTTP client, which falls back to `SSLContext.getInstance("TLS")` in if case system context cannot be created normally.

---

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [N/A] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
@mark-vieira may remember more about why we needed this.  I think we need to cache the SSL context because it's expensive to create.

**Comment by mark-vieira** [comment]
Using `getInstance()` is cached, but it doesn't take into account that system properties in the Gradle daemon are mutable. Our custom caching strategy takes [these properties](https://github.com/gradle/gradle/blob/master/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/DefaultSslContextFactory.java#L41-L50) into account and initializes a new SSL context should any of them change. We cannot simply defer to the JDK implementation here unfortunately as we need to explicitly control the caching strategy here.

**Comment by artem-zinnatullin** [comment]
mhm, ok what if we delegate to JDK implementation if these properties are not set, specifically `javax.net.ssl.trustStore=relative/or/absolute/path/trusted-cacerts.jks` and otherwise load custom keystore with similar to the old code?

That will remove faulty default JDK cacerts lookup while still supporting custom keystores

**Comment by mark-vieira** [comment]
That doesn't solve the problem. The issue is if I change an SSL related system property I need to reinitialize the SSL context. If we delegate to the JDK implementation in _any_ scenario it will ignore changes to these properties, including the one you mention above. Quite simply the JDK implementation is not intended for long running processes where system properties change (such as the Gradle daemon).

**Comment by artem-zinnatullin** [comment]
Wait, what I propose in [a comment above](https://github.com/gradle/gradle/pull/6721#issuecomment-420793006) will be very similar to the old code, so it will handle property changes and will use property values as a cache key.

However the difference will be in delegating to the JDK implementation instead of manual file lookup in `java.home/lib/security` in default property values scenario.

Note that I wouldn't expect `java.home` to be a mutable property as Gradle will start a separate daemon if you try to run it with different `JAVA_HOME`

**Comment by mark-vieira** [comment]
Mixing how we create `SSLContext`s based on some implict condition doesn't seem like a great idea. We should just fix our implementation to deal with a missing default keystore properly. Also, that wouldn't work in the scenario where someone specified a custom truststore location, but not a keystore and they keystore is missing.

**Comment by artem-zinnatullin** [comment]
I agree, closing

**Pull request closed without merging**
