### PR TITLE
Add reproducer for null string serialization error

### PR DESCRIPTION
**Pull request by asodja**
Reproducer for https://github.com/gradle/gradle/issues/24405.

### CODE REVIEW

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test QF

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
