### PR TITLE
Do not force AdoptOpenJDK vendor for M1 Macs

### PR DESCRIPTION
**Pull request by DPUkyle**
- Toolchains will attempt to download https://api.adoptopenjdk.net/v3/binary/latest/11/ga/mac/aarch64/jdk/hotspot/normal/adoptopenjdk, which does not exist

Fixes gradle/gradle-private#3429. Note this only affects the build logic for `gradle/gradle` build; this does not affect the Gradle build tool.

### CODE REVIEW

**Comment by DPUkyle** [comment]
@bot-gradle test this

**Review by jbartok — APPROVED** [review]

**Comment by DPUkyle** [comment]
@bot-gradle test this

**Comment by DPUkyle** [comment]
@bot-gradle test and merge

**Comment by DPUkyle** [comment]
@bot-gradle test and merge

**Pull request merged**
