### PR TITLE
Update CodeNarc version to 1.0

### LINKED ISSUE #3939: Upgrade CodeNarc default version
What about updating default CodeNarc version to e.g. 1.0?
The currently used default version is "0.25.2" which was released in April 2016.
It looks like old CodeNarc versions like that are using dynamic versions/version ranges in their poms which can cause problems. I tracked down one particular problem were I had to force certain groovy dependencies to their original version in order to get certain rules to work. Furthermore, it looks like CodeNarc does no longer use dynamic versions/version ranges in their poms starting from 1.0.

### PR DESCRIPTION
**Pull request by epeee**
### Context
fixes #3939 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] Make sure that all commmits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by blindpirate** [comment]
Thanks @epeee for your excellent work!

**Comment by bmuschko** [comment]
@blindpirate Can you please add labels and the milestone? We might also want to mention the upgrade in the release notes.

**Comment by blindpirate** [comment]
Ah yes, thanks for reminding!

**Comment by blindpirate** [comment]
And I've mentioned it in release note, thanks a lot @bmuschko !

**Pull request merged**
