### PR TITLE
Add GraalVM as a detectable JVM vendor

### LINKED ISSUE #15535: Add GraalVM as a JvmVendor
### Expected Behavior

Developers that use the new [JVM toolchain selection](https://docs.gradle.org/6.8/userguide/toolchains.html) feature might want to explicitly choose GraalVM for it's [polyglot features](https://www.graalvm.org/reference-manual/embed-languages/), and thus should be able to specify it to be the chosen JVM. While `ORACLE` will be supported as a [JvmVendorSpec](https://docs.gradle.org/6.8-rc-1/javadoc/org/gradle/jvm/toolchain/JvmVendorSpec.html) in Gradle 6.8, there is no `GRAAL_VM` value in [JvmImplementation](https://docs.gradle.org/6.8-rc-1/javadoc/org/gradle/jvm/toolchain/JvmImplementation.html), which would be the expectation.

### Current Behavior

There is no way to explicitly choose GraalVM as the JVM toolchain.

### Context

I'm trying to ensure in a Gradle build that GraalVM is used so its [polyglot features](https://www.graalvm.org/reference-manual/embed-languages/) can be used.

### PR DESCRIPTION
**Pull request by bmuskalla**
Resolves #15535.

Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>

### CODE REVIEW

**Comment by bmuskalla** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by bmuskalla** [comment]
@bot-gradle test and merge

**Comment by nassimus26** [comment]
Gradle 7.3.3 not working with GRAAL VM 17 

```
Gradle sync failed: Unable to determine version for JDK located at /Library/Java/JavaVirtualMachines/graalvm-ce-java17-21.3.0/Contents/Home. Reason: Command returned unexpected result code: 137
			Error output:
			(82 ms)
```

**Pull request merged**
