### PR TITLE
Add `--with testng` java init modifier

### PR DESCRIPTION
**Pull request by calid**
As discussed with @pioterj in #532

### CODE REVIEW

**Comment by pioterj** [comment]
@calid Thank you for another pull request. 

I see that "JavaLibraryInitIntegrationTest.creates sample source using testng instead of junit" actually fails. I haven't investigated why, could you take a look at that?

Also, we need to somehow verify in this test that TestNG is actually used. Currently assertions are identical to the scenario with JUnit.

**Comment by calid** [comment]
@pioterj I'll look into making the test more explicit.

As far as the test failing, where are you seeing this?  I see this passing both locally and on travis (the one failing job above looks unrelated).

```
~/git/gradle
$ ./gradlew :buildInit:clean :buildInit:build
:buildInit:clean
:buildInit:classpathManifest
:buildInit:compileJava UP-TO-DATE
:buildInit:compileGroovy
:buildInit:generateTemplateVersionFile
:buildInit:processResources
:buildInit:classes
:buildInit:jar
:buildInit:assemble
:buildInit:compileTestJava UP-TO-DATE
:buildInit:compileTestGroovy
:buildInit:processTestResources UP-TO-DATE
:buildInit:testClasses
:buildInit:compileIntegTestJava UP-TO-DATE
:buildInit:compileIntegTestGroovy
:buildInit:processIntegTestResources
:buildInit:integTestClasses
:buildInit:checkstyleIntegTest UP-TO-DATE
:buildInit:checkstyleMain
:buildInit:checkstyleTest
:buildInit:classycleIntegTest
:buildInit:classycleMain
:buildInit:classycleTest
:buildInit:checkstyleGroovy
:buildInit:checkstyleIntegTestGroovy
:buildInit:checkstyleTestGroovy
:buildInit:codenarcIntegTest
:buildInit:codenarcMain
:buildInit:codenarcTest
:buildInit:codeQuality
:buildInit:test
:buildInit:configureIntegTest
:buildInit:integTest
:buildInit:check
:buildInit:build

BUILD SUCCESSFUL

Total time: 1 mins 27.343 secs
```

**Comment by calid** [comment]
woops, accidentally closed when I went to comment

**Comment by pioterj** [comment]
OK, I think what happened is that testng entry was missing from library-version.properties file when I run the test from the IDE before running the Gradle build. In that case making the test more explicit is the only request I have for now. Other that that it looks good.

**Comment by calid** [comment]
@pioterj I updated the TestNG template to use a different test name than JUnit.  This distinguishes between the two and I think more accurately reflects TestNG naming conventions.  Let me know what you think.

**Comment by pioterj** [comment]
Looks good. I'll make a couple of small changes after the merge. Thank you for another useful contribution.

**Pull request merged**
