### PR TITLE
Test that constraining a virtual platform aligns its components

### PR DESCRIPTION
**Pull request by dansanduleac**
### Context

Currently, we test that adding a constraint for a virtual platform (using `enforcedPlatform`) works: https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/alignment/ForcingPlatformAlignmentTest.groovy

However, if we use `platform()` instead, constraining a virtual platform doesn't work, and gradle tries to resolve it as if it were a published platform.

This is a test that should pass but doesn't.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by melix** [comment]
@dansanduleac I'm not sure what you expect. Forcing is exactly what the `enforcedPlatform()` keyword is about. There's no expectation to force anything if you use `platform()`. The `belongsTo` API also provides an explicit opt-in flag to explain if a module belongs to a virtual platform (defaults to true). So if it's not virtual, you should use `belongsTo(..., false)`.

**Comment by dansanduleac** [comment]
@melix Sorry, I guess forcing is not the correct term to use here, I should have used the word constrained.

I expect that virtual platforms (non-forced) should be able to be constrained in the same way how constraining a component of a platform induces alignment of the other components (or fails if that's not possible).

So for instance, if I
* depend on jackson-databind 2.6.7
* make all jackson dependencies belong to a `com.fasterxml.jackson:platform` virtual platform with the same version
* add a constraint on `com.fasterxml.jackson:platform:2.9.7`

Then I'd like my jackson-databind dependency to be aligned to 2.9.7 via the virtual platform.

The reason I can't use `enforcedPlatform` here is that it would override my transitives' version constraints. If we take the previous example and imagine I'm adding a "strictly" constraint on `com.fasterxml.jackson:platform:2.5.0`, then an enforced platform would downgrade everything to 2.5.0, but what I want is a resolution error due to the conflict between my original dependency (jackson-databind requires 2.6.7) and the platform constraint (which implies jackson-databind strictly 2.5.0).

**Comment by melix** [comment]
Thanks for the additional details @danielsiwiec , I'll take a look.

**Comment by danielsiwiec** [comment]
This was meant for @dansanduleac I believe ^^^

**Comment by ljacomet** [comment]
So that's interesting, as I attempted to fix that already ... and looks like I did not cover all cases. See #7590

**Comment by ljacomet** [comment]
Ok, I figured it out. When the platform is the highest level component, its selected version is not considered as a candidate version for the included modules.
The fix needs to be done around [these lines](https://github.com/gradle/gradle/blob/18104a0968b8d62a9591e7bb0dc9df78450f3886/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/VirtualPlatformState.java#L61-L76) so that we include the selected platform version.

Before suggesting you take a shot at it, I recommend waiting a couple days as we are currently fixing something else that may change that exact method as well.

I'll add a comment once that other fix makes it in.

**Comment by ljacomet** [comment]
Your test has been integrated into #7824 as indeed we ended up changing that method where the fix needed to be made. Thanks for your contribution!

**Comment by dansanduleac** [comment]
Thanks @ljacomet, very excited about this!
Is there a nightly I can try this on, or not yet?

**Comment by ljacomet** [comment]
Should be in the next one

**Pull request closed without merging**
