### PR TITLE
Fix dependency verification in init scripts

### LINKED ISSUE #14711: Dependency verification breaks init scripts with external dependencies
Running the example from
[init scripts with external dependencies](https://docs.gradle.org/current/userguide/init_scripts.html#sec:custom_classpath):
`./gradlew --init-script init.gradle -q doNothing`
is not possible if dependency verification is turned on.

### Expected Behavior

Init scripts to still work when dependency verification is turned on, or at least fail with more information.

### Current Behavior

```
./gradlew --init-script init.gradle -q doNothing

FAILURE: Build failed with an exception.

* What went wrong:
GradleProperties has not been loaded yet.
```

### Context

I have a few common plugins that I enable in all my gradle projects by using $HOME/.gradle/init.gradle, I either have to disable dependency verification or remove the init script when I work on a project that uses dependency verification.

### Steps to Reproduce 

Example project: https://github.com/thejk/gradle-init-script-issue
Just run: `./gradlew --init-script init.gradle -q doNothing`

### Your Environment
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10)
OpenJDK 64-Bit Server VM (build 11.0.8+10, mixed mode)

### PR DESCRIPTION
**Pull request by melix**
If an init script was using external dependencies and that
those dependencies were not present in the dependency verification
file, the build would fail with an error message saying that the
GradleProperties couldn't be loaded.

This commit changes the behavior so that we perform verification and
report a verification error message instead.

Fixes #14711

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle help

**Comment by melix** [comment]
@bot-gradle clean

**Pull request merged**
