### PR TITLE
Make Problems API TAPI classes more consistent

### PR DESCRIPTION
**Pull request by donat**
Fixes https://github.com/gradle/gradle/issues/30569

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test this

**Review by reinsch82 — APPROVED** [review]
LGTM

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle merge

**Comment by donat** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle merge

**Pull request merged**
