### PR TITLE
Some renames around snapshotting (cherry-picked to release)

### PR DESCRIPTION
**Pull request by lptr**
This is the cherry-picked version of https://github.com/gradle/gradle/pull/15246.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Pull request merged**
