### PR TITLE
Add dependencies from antlr config to compileOnly instead of compile.…

### PR DESCRIPTION
**Pull request by foragerr**
Any of the checked boxes below indicate that I took action:
- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:
- [x] Before submitting a pull request, I started a discussion on the [Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev),
    the [forum](https://discuss.gradle.org/) or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I considered writing a design document. A design document can be
  brief but explains the use case or problem you are trying to solve,
  touches on the planned implementation approach as well as the test cases
  that verify the behavior. Optimally, design documents should be submitted
  as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
  can be found in the Gradle GitHub repository. Please let us know if you need help with
  creating the design document. We are happy to help!
- [ ] The pull request contains an appropriate level of unit and integration
  test coverage to verify the behavior. Before submitting the pull request
  I ran a build on your local machine via the command
  `./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
  DSL reference and Javadocs where applicable.

… Fixes GRADLE-3325

ref: 
https://issues.gradle.org/browse/GRADLE-3325
https://discuss.gradle.org/t/antlr-plugin-adds-compile-dependency-on-the-whole-antlr/10768

### CODE REVIEW

**Comment by eriwen** [comment]
Thanks for your contribution @foragerr. Here are a couple things that would help me feel sure we can merge this: 
* Can you tell me how this change fixes GRADLE-3325?
* Add a previously failing test case, if possible?

**Comment by foragerr** [comment]
antlr has two dependency binaries, one is a smaller [runtime](https://mvnrepository.com/artifact/org.antlr/antlr-runtime/3.5.2) dependency and another a larger [compile only](https://mvnrepository.com/artifact/org.antlr/antlr) dependency.

gradle [antlr plugin documentation](https://docs.gradle.org/current/userguide/antlr_plugin.html#sec:antlr_dependency_management) says to add the compile only dependency in `antlr` configuration, which is then [added to compile config](https://github.com/foragerr/gradle/blob/d1a57e2d5d23b19891b30c926636cdb563e69a3c/subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrPlugin.java#L66) by the plugin. This results in the compile only dependency being listed as a dependency for any project that uses gradle antlr plugin.

This is a problem for anyone [trying to slim down shipped binaries](https://discuss.gradle.org/t/antlr-plugin-adds-compile-dependency-on-the-whole-antlr/10768/4?u=foragerr). It is a slightly bigger problem for android projects that use antlr plugin, because [android build will complain about the duplicated class files between the two dependency variants](https://github.com/graphql-java/graphql-java/issues/225). 

This change adds antlr config to `compileOnly` instead of `compile` ensuring the bigger antlr dependency doesn't show up in published dependency-manifests (POMs). This change does not affect how the plugin is used and will not require a documentation update.

**Comment by foragerr** [comment]
This fix for GRADLE-3325 is trivial since `configurations.compileOnly` became available.

**Comment by eriwen** [comment]
Thank you for the explanation @foragerr. 

I'm afraid that [SamplesAntlrIntegrationTest](https://github.com/gradle/gradle/blob/master/subprojects/antlr/src/integTest/groovy/org/gradle/integtests/samples/SamplesAntlrIntegrationTest.groovy) is now failing if you run `./gradlew :antlr:check`. Could you please fix that test so we can merge it?

**Comment by foragerr** [comment]
Sorry, I should've caught that in the first place. Fixed now.

**Comment by eriwen** [comment]
Thank you @foragerr! This LGTM

**Comment by big-guy** [comment]
Hey @eriwen and @foragerr,

I had to revert this change on master (https://github.com/gradle/gradle/commit/f481f194d2b02e72ad5841a829aba1f3e84c5c27) because this breaks existing builds that relied on getting the "full" ANTLR dependency (whether that's the right thing or not).  Our test coverage wasn't sufficient to cover the typical use case (build a grammar from one project, use it in another), so I refactored them to be more realistic (https://github.com/gradle/gradle/commit/4581dda52c11bc555842ab31f84ba03d89961dd7).

There were a couple of other issues with this change.
- We were using `compileOnly` and `testCompile` (vs `testCompileOnly`). 
- We need to support ANTLR2, which doesn't have a separation between runtime and tool.

So I think we need to consider the different use cases here.  We can't break working builds except when we have made really egregious mistakes. 
- The build is using ANTLR2 with no explicit version.
- The build is using ANTLR2 with an explicit version defined.
- The build is using ANTLR3 with an explicit version defined and the build expects the "full" dependency.
- The build is using ANTLR3 with an explicit version defined and the build only needs the runtime dependency.
- The build is using ANTLR4 with an explicit version defined and the build expects the "full" dependency.
- The build is using ANTLR4 with an explicit version defined and the build only needs the runtime dependency.

I think the current ANTLR support has evolved to where it is now, so it's not surprising that things are a bit muddled.  I think it makes a lot of sense to treat the ANTLR tool classpath completely separate from the compile classpath.

I haven't thought this completely through, but we could do something like this:
1) Keep `antlr` configuration as-is, warts and all. Deprecate it.
2) Introduce `antlrTool` that is completely separate from `compile`.  `antlrTool` extends from `antlr`
3) Update documentation for the ANTLR plugin to recommend that people use `antlrTool` to select the version of ANTLR to use and `compile` to select the version of the ANTLR runtime to use.  For ANTLR2, the same dependency would be used for both.
4) Bonus points for making parts of 3 automatic somehow.

WDYT Eric?

**Comment by eriwen** [comment]
@big-guy I think I'm going to have to think more about it and follow up next week :)

**Comment by eriwen** [comment]
I have added https://github.com/gradle/gradle/issues/820 including the explanations from both @foragerr and @big-guy. Please let me know if anything I wrote there is off.

We will consider prioritizing this in a future version of Gradle. For now, I have marked it `help-wanted`. Given our aggressive 3.3 schedule, I won't be able to do work out-of-band on this.

**Pull request merged**
