### PR TITLE
Reduce console refresh/logging rate

### PR DESCRIPTION
**Pull request by eriwen**
### Context
Reduce noise and improve performance from trying to update console too quickly.

### Contributor Checklist
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status

### CODE REVIEW

**Comment by adammurdoch** [comment]
I'm not sure about this one. In testing this, 85ms was about as long as we could go without the console starting to become rather jerky. It might be better to instead make the updates smarter.

**Comment by eriwen** [comment]
@adammurdoch I guess is something we might have to try if we want to go this way. Perhaps some screencasts are in order at least.

**Comment by adammurdoch** [comment]
There's 2 separate goals here I think: 1. avoid flickering by updating the screen for things that appear and disappear quickly, and 2. reduce the amount of screen updates we make to reduce the performance impact of the dynamic stuff. The trade-off for both of these is that we want to keep the console as live as possible. We can potentially solve these 2 issues in different ways.

One thing we can do is play with the liveness of different kinds of information. For example, we can probably defer adding or removing things from the 'work in progress' section for quite a long while. So, we might not show a new operation until it's been running for a while (say 300 ms) or once something is shown we might not hide it for a while (maybe even longer). Or perhaps flip it around. It's really the progress information for a particular thing that we want to make live (the % complete for a phase or a task), so perhaps we update the screen more frequently when status changes, but less frequently when there are only start/finish events queued up.

**Comment by eriwen** [comment]
Good thoughts @adammurdoch. Closing this until we can think deeper about it.

**Pull request closed without merging**
