### PR TITLE
GitHub issue/pr links in IDEA Git log

### PR DESCRIPTION
**Pull request by turansky**
### Context
Clickable links in IDEA Git log

Before - `# 12722`, `# 12733`
After - #12722, #12733

Screenshot 2020-04-08 at 14 42 09

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by rieske** [comment]
Thank you @turansky!

**Comment by rieske** [comment]
I am sorry, but I will be reverting this change.

After discussing this with the team, we do agree that this is a good change, but we would prefer it achieved in a different way - particularly by configuring the build via [idea-ext](https://github.com/JetBrains/gradle-idea-ext-plugin) plugin programmatically like we do here: https://github.com/gradle/gradle/blob/e51cfc4f2184fc0540262657d37156a1752927d9/buildSrc/subprojects/ide/src/main/kotlin/org/gradle/gradlebuild/ide/IdePlugin.kt#L100-L114

`idea-ext` does not currently have this functionality, but there is an open issue for it: https://github.com/JetBrains/gradle-idea-ext-plugin/issues/88

If we check in the `.idea/vcs.xml`, we start getting conflicts locally as members of the team have their own personal configurations in it.

**Comment by turansky** [comment]
Solution with `idea-ext` looks better

**Comment by turansky** [comment]
@rieske Do you have plans to create PR to `idea-ext` plugin?

**Pull request merged**
