### PR TITLE
Use junit-platform 5.7.1 consistently in the codebase

### PR DESCRIPTION
**Pull request by donat**

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test @qFLO

**Comment by donat** [comment]
@bot-gradle test QuickFeedbackLinux

**Comment by donat** [comment]
@bot-gradle test rFM

**Review by bmuskalla — APPROVED** [review]

**Comment by donat** [comment]
Thanks for the early review, @bmuskalla! I wanted to wait until CI passes, but it's fine like this as well :)

**Pull request merged**
