### PR TITLE
Introduce JetBrains as a known JVM vendor.

### PR DESCRIPTION
**Pull request by hsz**
### Context
It is possible to use JetBrains Runtime in JVM Toolchain with:

```
kotlin {
    jvmToolchain {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.matching("JetBrains s.r.o")
    }
}
```

Introducing JetBrains as a known vendor would help pick up JBR in a more convenient way:

```
kotlin {
    jvmToolchain {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.JETBRAINS
    }
}
```

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [X] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [X] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Review by ov7a — APPROVED** [review]

**Comment by eskatos** [comment]
Hi @hsz  👋 

Thanks for the PR.
Some checks are failing.
See https://scans.gradle.com/s/5lomvvzfvsdwi/console-log?page=2#L1493-L1499
Your change adds a member to our public API. You need to accept that.
See the linked report and follow the instructions.

**Comment by hsz** [comment]
@eskatos Thank you for the details. I've fixed the issue and provided relevant information for the release notes.

**Comment by eskatos** [comment]
Sorry to bother you again but it looks like the DCO check is now failing.
Could you please fix this?
See https://github.com/gradle/gradle/pull/26014/checks?check_run_id=15591659606

**Review by lkasso — APPROVED** [review]

**Comment by hsz** [comment]
@eskatos Turns out I can't simply accept your suggestion here on GitHub with one click, but I need to craft a similar commit.
Anyways, everything should be fine now. 🤞

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by hsz** [comment]
FTR, I just tested the following code with Gradle built from sources:
```
kotlin {
    jvmToolchain {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.JETBRAINS
    }
}
```

It works well with the FooJay resolver as well:
```
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.6.0"
}
```

It pointed to the following JBR distribution:
```
Download https://api.foojay.io/disco/v3.0/ids/889f2f5999789ae9c926cd06b3376cb6/redirect, took 42 s 564 ms (200.23 MB)
```

**Review by eskatos — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
Thank you Jakub!

This will be in Gradle 8.4

**Comment by hsz** [comment]
FTR: the vendor display name was adjusted to simply `JetBrains` — ref: #26022

**Pull request merged**
