### PR TITLE
Use UTF-8 for the daemon log

### LINKED ISSUE #29302: Daemon logs should use explicit encoding instead of JVM default
### Issue type

Polishing

### Problem description

Currently, daemon logs are written and read with system default encoding, which may cause issues when e.g. TAPI client and the daemon use different defaults. 

### Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by mlopatkin**
### Limit suppression scope and link TODO issue in ArgWriter

This is a trivial change. The underlying issue is much more complex, and has to be tackled separately.

###  Clean up uses of GFileUtils.tail

This method had only one use in the DaemonDiagnostics and overall looks quite ad-hoc, so it makes sense to move it closer to its client, which also allows us to use Guava and Java 8 goodies for simplification.

DaemonDiagnostics runs in the client process which may have a different default encoding, so we're using UTF-8 encoding to write the daemon log. This code is not cross-versioned, so backward and forward compatibility
considerations do not apply.

Fixes #29302. 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
@bot-gradle test this without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test RfN without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test BD

**Review by lptr — APPROVED** [review]
LGTM.

**Review by lkasso — APPROVED** [review]
Docs LGTM

**Comment by mlopatkin** [comment]
@bot-gradle test QFL

**Pull request merged**
