### PR TITLE
Correct handling of multiple svc provider impls in a single SPI file

### PR DESCRIPTION
**Pull request by lingocoder**
Issue: #11027
Signed-off-by: lingocoder <coder@lingocoder.com>

Fixes: #11027 — ***Compliance with the JDK's Standard Mechanism for Configuring Service Providers***
Fixes: #10408 — ***gradle-api-5.6.1.jar is an invalid module***

### Context

The Java Platform Standard Edition-specified standard mechanism for configuring concrete implementations of a service provider interface (*SPI*), is prescribed in [*the JDK's ServiceLoader API documentation*](http://bit.ly/J12SvcLoadr)...

> ...
>
>  ***Deploying service providers on the class path*** 
> ...
> *...The provider-configuration file contains **a list** of fully qualified binary names of service providers, **one per line**...*
> ...
>

The root cause of the defects reported in both #10408 and #11027 is previous and current versions of Gradle's incorrect processing of *`META-INF/services`* provider configuration files as if they contain only *one single* service provider implementation. 

In previous and current versions of Gradle, when there are two or more lines in the provider configuration file, Gradle processes them as a single service provider. So, in the #10408 and #11027 instances, the defect produces the effect of „*relocating*“ only the first service provider implementation listed in the *`META-INF/services/java.security.Provider`* configuration file. 

By effectively *ignoring* all but the first implementation in the list, second, third, etc, implementations that are listed in the file are never „*relocated*“ as expected. The actual provider implementation class files themselves do actually exist as entries in the generated shaded JAR file. However, they are *effectively* non-existent because an expected „*mapping*“ process is done only for the very first provider listed in the configuration file.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by lingocoder** [comment]
Hi @melix,

Thanks for triggering those CI runs. Apologies for the failures. I'm looking into the problems right now.

**Comment by lingocoder** [comment]
Hi @melix,

My most recent commit has most (*7 out of 9*) of the checks passing now.  The two checks that are failing have me stumped though.

I've trawled through the stack traces of the Team City logs. This time I have no idea how to fix the failures it's reporting:

```Caused by: java.lang.RuntimeException: /packages cannot be represented as URI```
...

```
...
* What went wrong:
An exception occurred applying plugin request [id: 'com.gradle.build-scan', version: '2.2.1']
> Failed to apply plugin [id 'com.gradle.build-scan']
   > The build scan plugin is not compatible with this version of Gradle.
     ...
```
...

```
...
* What went wrong:
A problem occurred configuring root project 'junit18308090381040601276'.
> Failed to notify project evaluation listener.
   > modifiers
   > modifiers
   > modifiers
   ...
Caused by: java.lang.NoSuchFieldException: modifiers
...
```

...

```
...
Caused by: edu.umd.cs.findbugs.NoClassesFoundToAnalyzeException: No classes found to analyze in /tmp/junit3006223150751767382/build/classes/java/main/example/Application.class */tmp/junit3006223150751767382/build/classes/java/main *JrtfsCodeBase [file=/opt/files/jdk-linux/openjdk-13_linux-x64_bin.tar.gz/lib/jrt-fs.jar] 
...
```

...and so forth. 

The check failures that I resolved with the recent commit, I could see how they were related to my code changes. These last two check failures though, it's not obvious how (*or even \_IF\_*) they're related to me.

Are those things I should try to resolve? Or are they known issues unrelated to my commit that I can leave to you experts? Please advise?

TIA.

**Comment by big-guy** [comment]
@lingocoder you're good.  The last failing checks are due to your branch being a bit out-of-date from master.  We added JDK13 smoke test coverage and those tests needed to be fixed to pass.

**Comment by lingocoder** [comment]
Ahh! Thanks @big_guy. That's such a relief! :+1:

```
> Will to live: RESTORED 
...
> Imposter Syndrome symptoms: SUBSIDING
...
```

 ;)

**Comment by big-guy** [comment]
I cherry-picked this to release for 6.0 RC2.  Thanks!

**Pull request closed without merging**
