### PR TITLE
Add support for running Gradle on Java 22

### LINKED ISSUE #26162: Support Java 22
### Expected Behavior

Gradle should support the ability to build projects using JDK 22.

### Current Behavior (optional)

As of this writing, Gradle 8.3 presents the following error when building against JDK 22-ea:

```
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66
```

### Context

OpenJDK recommends the following:

```
 If you haven't done so, please start testing your project(s) using JDK 22 Early-Access builds and let us know the results.
```

[Apereo CAS](https://github.com/apereo/cas) is part of the Oracle JDK Compatibility program, and we are trying to help the JDK ecosystem by trying out latest versions of JDK to report feedback, issues, etc. This is no blocker at all and we can continue with JDK 21 builds. I did not see a relevant issue to track support for JDK 22, so thought to open one here.

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #26162 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
Would it make sense to also update asm to latest greatest? I see just few days ago new version was released:
https://asm.ow2.io/versions.html

**Review by cobexer — CHANGES_REQUESTED** [review]

**Review by big-guy — CHANGES_REQUESTED** [review]
DefaultGradleDistribution.doesWorkWith needs to be updated too

**Comment by octylFractal** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Pull request merged**
