### PR TITLE
Mark toolchain package @NonNullApi

### LINKED ISSUE #14825: Make toolchain package NonNull
`org.gradle.jvm.toolchain` package should be annotated with `@NonNullApi`

### PR DESCRIPTION
**Pull request by bmuskalla**
Fixes #14825

### CODE REVIEW

**Review by ljacomet — COMMENTED** [review]
Did you verify the impact on Kotlin type signatures?
We are `@Incubating` so we should be safe to fix, but knowing is better than discovering.

**Comment by bmuskalla** [comment]
Huh. I simply assumed that the API tests would catch such a breakage. 
Other than that, the samples (including kotlin) seem to compile as well so I assume this was ok.
How would you go about verifying we didn't change the kotlin signatures?

**Comment by bamboo** [comment]
`checkBinaryCompatibility` should catch the _non-null returning to null returning_ breaking change.

**Comment by ljacomet** [comment]
@bamboo Will it catch _null returning_ to _non-null returning_ as well? Or is that not a breaking change?

@bmuskalla The fun there is that for build scripts, it is not an issue. For a compiled plugin it is ... At least that's my understanding.

**Comment by bamboo** [comment]
@ljacomet _null returning to non-null returning_ might be a source breaking change with _warning as errors_ enabled. I haven't checked but I don't expect our test suite to catch it.

**Comment by bmuskalla** [comment]
@bot-gradle test this

**Pull request merged**
