### PR TITLE
Update versions of smoke tested plugins

### PR DESCRIPTION
**Pull request by ljacomet**
This is done in preparation of the Gradle 8.4 release.

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle help

**Comment by eskatos** [comment]
It would be good to also update versions in `AndroidCommunityPluginsSmokeTest`

**Review by ov7a — APPROVED** [review]

**Comment by ljacomet** [comment]
@eskatos Right, let me do that in a follow up PR

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
