### PR TITLE
Eagerly compute task graph representation for build scans

### PR DESCRIPTION
**Pull request by wolfs**
to avoid ConcurrentModificationException on publishing build scans.

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Review by eskatos — APPROVED** [review]

**Comment by wolfs** [comment]
@bot-gradle cancel

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle cancel

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
