### PR TITLE
Add missing botGradleGitHubToken and GRADLE_ENTERPRISE_ACCESS_KEY to release6x

### PR DESCRIPTION
**Pull request by blindpirate**

### CODE REVIEW

**Review by wolfs — APPROVED** [review]
LGTM! Can you promote a snapshot from this branch so we see if the build scan works?

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
