### PR TITLE
Use JaCoCo 0.7.9 by default

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by eriwen** [comment]
Hi @Godin could you please confirm you've signed the [Gradle CLA](https://gradle.org/cla)?

**Comment by Godin** [comment]
Hi @eriwen , I confirm - see previous contribution #575

**Comment by eriwen** [comment]
Cool, thanks @Godin.

**Comment by bmuschko** [comment]
@Godin Thanks, this looks good. Would you mind rebasing to resolve the merge conflict? Happy to merge soon.

**Comment by Godin** [comment]
@bmuschko rebased

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged.

**Pull request merged**
