### PR TITLE
support noTimestamp and noVersionStamp groovydoc flags

### PR DESCRIPTION
**Pull request by paulk-asert**

### CODE REVIEW

**Comment by mark-vieira** [comment]
@paulk-asert, do you mind signing the [CLA](http://gradle.org/contributor-license-agreement/)?

**Comment by paulk-asert** [comment]
Signed. Just a couple of comments on the PR changes:
* I didn't know whether you deem `AntGroovydoc.java` to be part of your public api in which case you might want to overload the `execute` method defaulting the two new flags to false.
* I haven't tried to do any version checking. Groovy 2.4.6 will be the first version to support these flags. Earlier versions of `GroovyDocTool` won't care if given additional properties - those entries in the map will be ignored and vice versa, older versions won't do anything if supplied with extra properties. But given the hook via antBuilder, it will likely complain if given parameters not in the Groovydoc ant task but I haven't tested this. It depends really whether this code only runs with a bundled Groovy or if there is a way to run it using any Groovy version.

**Comment by mark-vieira** [comment]
Yes, `AntGroovydoc` is part of the public API. We probably do want to do some kind of version checking here if setting these properties will cause issues in Groovy versions < 2.4.6. Users can control what [version of Groovy is used](https://github.com/gradle/gradle/blob/3b87005d732c9c0c76890339642f7a3ed9145ac0/subprojects/language-groovy/src/main/java/org/gradle/api/tasks/javadoc/Groovydoc.java#L115-L115). Also, I think we'd likely want to wait until Groovy 2.4.6 is released before merging this in so we can add coverage to ensure setting the properties actually _does_ something.

**Comment by pioterj** [comment]
@paulk-asert Groovy 2.4.6 is out. I'm counting on you to finalize this PR.

**Comment by paulk-asert** [comment]
I will create a new PR

**Pull request closed without merging**
