### PR TITLE
PMD priority level support

### PR DESCRIPTION
**Pull request by AdamRoberts**
The PMD Ant task has a minimumPriority option that allows the caller to turn off the lower priority (higher number) warnings. This is desirable as many of the level 4 and 5 warnings don't have enough value to make fixing them worth the effort.  This change adds the option to the Gradle plugin.

### CODE REVIEW

**Comment by bigdaz** [comment]
Thanks for the contribution. I've made some comments on the commits which would need to be addressed before we could merge.

**Comment by bigdaz** [comment]
Hi again @AdamRoberts. I'm sorry it took so long to get back to you with initial feedback.

If you're interested in taking this pull request further, please respond to my comments on the code. Otherwise, I will close this pull request and you can reopen it when you find time.

**Comment by AdamRoberts** [comment]
The property name mismatch was an experiment on my part that I forgot to revert before pushing, that has been corrected.

I updated the integration test to show that the level 3 warnings are ignored, but the level 2 warnings are still failing the build.

**Comment by bigdaz** [comment]
Thanks @AdamRoberts . This PR has been merged into master, with some minor modifications.
This changed missed the cut for Gradle 2.7, but will be Gradle 2.8.

Thanks again for you contribution.

**Pull request merged**
