### PR TITLE
GRADLE-2673 Don't set JAVA_HOME to a cygwin path

### PR DESCRIPTION
**Pull request by Joerg-Schoemer**

### CODE REVIEW

**Comment by bigdaz** [comment]
Hi. Without any context or explanation, this PR is pretty much meaningless. I don't really even understand the commit message: does this mean that the original code comes from another contributor? (That would prove problematic since we need to get a CLA signed).

In light of these issues, I'm going to close this PR. If you want to resubmit with a bit more explanation, feel free. 
Thanks, Daz.

**Comment by Joerg-Schoemer** [comment]
Hi Daz,
sorry for the short commit message.
if running the generated shell script on cygwin the JAVA_HOME ist modified (to something like /cygdrive/c/.../java) which leads to errors in the JVM, because of the unix style path on a windows JVM.
I thought the issue GRADLE-2673 would explain the problem clearly, so I just pointed to that issue...
Kind regards, Joerg

**Comment by bigdaz** [comment]
You're right. Looking at that issue report makes it a bit clearer. Am I correct in thinking that you are not the 'anonymous' Joerg that posted that forum issue, and that you've just applied the patch from that Forum post? (Your names are so similar that I got quite confused!)

**Comment by Joerg-Schoemer** [comment]
Hi Daz,
you're right, I'm not the anonymous Joerg.
I've just applied the patch from the that forum post.

**Comment by alkemist** [comment]
I think deep down inside, we are all the anonymous Joerg.

**Comment by bigdaz** [comment]
Looking a bit more at this, I don't understand why this change wouldn't cause the start script to fail, since JAVA_HOME will no longer be cygpath'd:
https://github.com/Joerg-Schoemer/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt#L74

Can you please verify that the generated start scripts work on Cygwin, with and without a JAVA_HOME environment variable?

**Comment by bigdaz** [comment]
Also, please sign the CLA here: http://www.gradleware.com/contributor-agreement/

Even though you didn't write the original code, we have a policy of not merging pull requests without an accompanying CLA.

**Comment by alkemist** [comment]
@Joerg-Schoemer I'm going to close this off due to lack of inactivity. Please let me know if you are still interested in progressing this, which would be much appreciated.

**Comment by bigdaz** [comment]
FYI: I've just pushed this fix.

**Pull request closed without merging**
