### PR TITLE
Revert capability conflict bugfixes

### PR DESCRIPTION
**Pull request by jvandort**
Fixes: #30969 

We ran into a regression in the case where a dependency conflicts with one of its transtitives, where that transitive
is only referenced by that parent dependency.

This caused the transitive dependency to have no incoming edges at the time of conflict resolution. An attempted refactoring
to capability conflict resolution did not handle this situation correctly.

This introduces a number of tests intended to serve as a regression test against this scenario

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]
Are there any chunks of this that are worth keeping/merging separately (maybe on master)?

**Comment by ljacomet** [comment]
All of the changes are worth keeping, they make Gradle more correct. We however created an unsupported case that results in an infinite loop. We will have to support it properly.

Justin and I discussed that extracting a meaningful subset of changes is probably challenging since these fixes tend to lie in a small area and have ripple effects when done in isolation.

**Comment by ljacomet** [comment]
Let's see if #31013 allows us to keep the changes in!

**Comment by jvandort** [comment]
Closing since we merged a PR that should resolve this issue.

**Pull request closed without merging**
