### PR TITLE
Fix spelling errors in a few subprojects

### PR DESCRIPTION
**Pull request by lipnitsk**
### Context
Spelling errors stand out and make it harder to focus on the coding process. They are an easy fix with modern IDEs, so this change has practically zero risk.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] Make sure that all commmits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by blindpirate** [comment]
Thanks @lipnitsk , I really appreciate your contribution, but I'm afraid that we can't do this change due to some historical reason. For example, `org/gradle/api/tasks/testing/Test.java` is public API and it would be a huge breaking change if we do this. Sorry again but I'll close this. Hope you don't mind and make more excellent contribution in the future.

**Comment by lipnitsk** [comment]
@blindpirate thanks for your feedback. How about only taking the first commit (8e8c464ba9c01acfdff1ec9dfa3c8b5054c0276a). It only touches JUnit and TestNG implementation classes, they don't seem to be a publicly exposed API, are they?

**Comment by blindpirate** [comment]
Sure, it happened that I'm refactoring this part (JUnit and TestNg).please don't delete your branch and I'll cherry-pick it.

**Comment by lipnitsk** [comment]
Okay, I made a small change, but feel free to pick from lipnitsk/master (e70b8d0b17dc2702d1a6ed95b30760cfe95edc1c)

**Comment by blindpirate** [comment]
Would you mind opening an issue to discuss it? I'm not sure I understand you intention completely. Anyway, thanks for your work in advance.

**Comment by lipnitsk** [comment]
Sure, I opened #4067 (which was closed), but it is related to the second comment in #3851

**Comment by lipnitsk** [comment]
My preliminary changes for #4067 and #3851 are in 9f302081fce8a36b4f72e8f0985752eb07accbbd

**Comment by blindpirate** [comment]
@lipnitsk Thanks. I've cherry-picked your change here: https://github.com/gradle/gradle/pull/4094

**Pull request closed without merging**
