### PR TITLE
Fixed bug in generating distributionUrl

### PR DESCRIPTION
**Pull request by er-han**
Bug was only in those locales which contain small dotless I letter (ı).
More detail: https://groups.google.com/forum/#!topic/gradle-dev/JHZqo_EJ2zs

Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [x] Before submitting a pull request, I started a discussion on the [Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev),
      the [forum](https://discuss.gradle.org/) or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I considered writing a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [x] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by lacasseio** [comment]
Thank you very much for providing a PR for this issue. Would you mind adding a test for this PR just so we don't break this use case in the future?

**Comment by er-han** [comment]
@lacasseio I have added a test for this bug fix.

**Comment by lacasseio** [comment]
Thanks for the contribution. I manually merge it as I did a small fixed to the test. We identified that other places in Gradle code base is vulnerable this `toLowerCase` problem. If you feel strongly about this, we could use your help in improving Gradle. Have a look at issue https://github.com/gradle/gradle/issues/1506. We would be looking at adding Firebug or Pmd check to catch this kind of problem and fixing every occurrence.

**Comment by er-han** [comment]
I would be glad if I can help in improving Gradle.

**Pull request closed without merging**
