### PR TITLE
Consider .hpp, .hxx, and .h++ as header files.

### PR DESCRIPTION
**Pull request by pandaninjas**
Addresses https://github.com/gradle/gradle-native/issues/1079

### Context
https://github.com/gradle/gradle-native/issues/1079
.hpp, .hxx, and .h++ are common header file names for C++

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by cobexer** [comment]
Thank you for your interest in Gradle.

Sorry for the late reply.

This PR has been in draft state for a long time, do you have any plans to wrap it up?

***

The List should be consistent with what was done in:
* https://github.com/gradle/gradle/pull/26844

**Comment by pandaninjas** [comment]
> Thank you for your interest in Gradle.
> 
> Sorry for the late reply.
> 
> This PR has been in draft state for a long time, do you have any plans to wrap it up?
> 
> The List should be consistent with what was done in:
> 
> * [expand list of public header file extensions for cpp-library #26844](https://github.com/gradle/gradle/pull/26844)

I will wrap it up soon and apply the suggestions. Thanks!

**Comment by pandaninjas** [comment]
Should the part in [DefaultCppComponent.java](https://github.com/gradle/gradle/pull/26493/files#diff-51bd5abbddf9a105a26712dc9086959056694b0e54f5fb1138b1ae8bf8898d00) be kept? It could be useful for executable projects which use different header endings.

**Comment by cobexer** [comment]
The patterns should be consistent everywhere.

Please make sure all patterns from `subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppLibrary.java` are included in `subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppComponent.java` and `platforms/ide/ide-native/src/main/resources/org/gradle/ide/visualstudio/tasks/internal/default.vcxproj.filters` and it would be nice if you added a comment in those files so future updates do not miss the related locations.

**Review by cobexer — CHANGES_REQUESTED** [review]
Please see above

**Comment by cobexer** [comment]
@pandaninjas The [DCO](https://probot.github.io/apps/dco/) check is failing now, please look into that as we can't accept the PR otherwise.

**Comment by ov7a** [comment]
@pandaninjas PTAL at failing tests

**Review by ov7a — APPROVED** [review]

**Comment by ov7a** [comment]
Thanks, @pandaninjas!

**Comment by ov7a** [comment]
@bot-gradle merge

**Pull request merged**
