### PR TITLE
Improve error message for invalid Maven coordinate

### PR DESCRIPTION
**Pull request by martinda**
### Context

A better diagnostic message will help use find the source of the problem.

Issue #3834

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [n/a] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [n/a] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ljacomet** [comment]
Thanks for the contribution. I've sent it for a full check before merging.

While this greatly improves the situation, I am tempted to leave the issue opened afterwards since there was a suggestion of also being able to provide an indication as to the source of the value, which is not addressed here.

**Comment by martinda** [comment]
How do you suggest the source of the value to be traced to its source? The value could come from so many different places... a file, an env var, a system property, it could be computed by a method, etc.

**Comment by ljacomet** [comment]
Merged, thanks again for the contribution.

I know that Gradle has some tooling around tracing the origin of a change to a build script, but I am not too familiar with it.
As you state though, this is not a trivial operation.
That's why this contribution is already a great improvement!

**Comment by martinda** [comment]
Should this bug fix be listed in the [5.5-rc-1 release notes](https://docs.gradle.org/5.5-rc-1/release-notes.html)?

**Comment by ljacomet** [comment]
I do not think the release notes list pull requests, only issues.
When the issue itself was closed, the milestone information was not added. I have added it, so it should make it in the version of the release notes for final 5.5 or any subsequent RC.

**Pull request merged**
