### PR TITLE
Remove no longer needed JPMS workaround for Kotlin compiler daemon

### PR DESCRIPTION
**Pull request by rieske**
The underlying problem was fixed in Kotlin 1.5.0

Fixes https://github.com/gradle/gradle/issues/17075

### CODE REVIEW

**Review by donat — APPROVED** [review]

**Comment by rieske** [comment]
We will have to first update the embedded Kotlin version and release new versions of `kotlin-dsl` plugins.
https://plugins.gradle.org/plugin/org.gradle.kotlin.kotlin-dsl.base

**Comment by donat** [comment]
> We will have to first update the embedded Kotlin version and release new versions of kotlin-dsl plugins. plugins.gradle.org/plugin/org.gradle.kotlin.kotlin-dsl.base

Is that something we'll do in Gradel 7.2? If not then we should use my workaround of the workaround [here](https://github.com/gradle/gradle/pull/17432).

**Review by big-guy — CHANGES_REQUESTED** [review]
blocked on 1.5 upgrade

**Comment by rieske** [comment]
Will raise a new PR for this.

**Pull request closed without merging**
