### PR TITLE
Adjust snippets for configuration cache

### LINKED ISSUE #21806: CCH22-9: Adjust the `snippets/dependencyManagement/customizingResolution-ivyMetadataRule` sample for configuration cache
The sample project located under [`subprojects/docs/src/snippets/dependencyManagement/customizingResolution-ivyMetadataRule`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/dependencyManagement/customizingResolution-ivyMetadataRule) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-dependency-management-customizing-resolution-ivy-metadata-rule_groovy_ivyComonentMetadataRule.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-ivy-metadata-rule_groovy_ivyComonentMetadataRule.sample)
    ```
    Could not get unknown property 'configurations' for task ':compileClasspathArtifacts' of type org.gradle.api.DefaultTask.
    ```

* `snippet-dependency-management-customizing-resolution-ivy-metadata-rule_kotlin_ivyComonentMetadataRule.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-ivy-metadata-rule_kotlin_ivyComonentMetadataRule.sample)
    ```
    Task `:compileClasspathArtifacts` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-dependency-management-customizing-resolution-ivy-metadata-rule_groovy_ivyComonentMetadataRule.sample" \
    --tests "*snippet-dependency-management-customizing-resolution-ivy-metadata-rule_kotlin_ivyComonentMetadataRule.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_model.adoc`;

### PR DESCRIPTION
**Pull request by prasad-333**
CCH22-9: Adjust the snippets/dependencyManagement/customizingResolution-ivyMetadataRule sample for configuration cache

Fixes #21806 

Signed-off-by: prasad-333 <37048768+prasad-333@users.noreply.github.com>

### CODE REVIEW

**Comment by abstratt** [comment]
Looks good as well!

@bot-gradle test and merge

**Comment by abstratt** [comment]
> [Pre-tested commit build](https://builds.gradle.org/viewLog.html?buildId=56205338) failed.

@prasad-333 Please take a look?

**Comment by prasad-333** [comment]
> > [Pre-tested commit build](https://builds.gradle.org/viewLog.html?buildId=56205338) failed.
> 
> @prasad-333 Please take a look?

@abstratt This is build also failing similar to #22037 

To me looks build failing for another task "Execution failed for task ':runtimeClasspathArtifacts'.

    Could not get unknown property 'configurations' for task ':runtimeClasspathArtifacts' of type org.gradle.api.DefaultTask."

This seems not part of the issue assigned. #21807 was failing for :compileClasspathArtifacts task this build failure is related to ':runtimeClasspathArtifacts' .

It seems, change required in ':runtimeClasspathArtifacts' task as well. Ideally separate PR will be good to segregate this new issue. Kindly let me know if this changes needs to be put in this same PR?

Thanks

**Comment by abstratt** [comment]
> To me looks build failing for another task "Execution failed for task ':runtimeClasspathArtifacts'.
> ```
> Could not get unknown property 'configurations' for task ':runtimeClasspathArtifacts' of type org.gradle.api.DefaultTask."
> ```
> This seems not part of the issue assigned. #21807 was failing for :compileClasspathArtifacts task this build failure is related to ':runtimeClasspathArtifacts' .

Ah, right. I don't understand the reason yet, but that omission was just a problem with filing the issue - please consider that as part of the scope for #21806, and address it in this PR as well. The approach you took for fixing e `compileClasspathArtifacts` should be fine.

**Review by abstratt — CHANGES_REQUESTED** [review]
Another task needs fixing as well

**Comment by abstratt** [comment]
@prasad-333 It seems I don't have permission to make changes to your branch (required for resolving conflicts, for instance)

**Comment by prasad-333** [comment]
> @prasad-333 It seems I don't have permission to make changes to your branch (required for resolving conflicts, for instance)

Well I am not sure by I haven't specifically restricted any branch permission. Even I can't **resolve conflicts** & merge it. 
Gradle team member should have permission to do so as you did before on same branch here https://github.com/gradle/gradle/pull/22038/commits/f5e60a633810ff337b3385d2d4097be75c440845

**Review by abstratt — APPROVED** [review]
Thanks!

**Comment by abstratt** [comment]
@bot test and merge

**Comment by prasad-333** [comment]
> This might explain it: https://stackoverflow.com/questions/59110548/github-resolve-conflicts-button-disabled
> 
> I will resolve the conflict using the git client CLI client.


To me now looks github meshed up both ways? _subprojects/docs/build.gradle_ should not be complex merge in my understanding & SO link you shared as per it Github should revert back to that message of using another client/CLI.

Anyways thanks @abstratt for taking time to looking into it & merging.

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
🎉

**Pull request merged**
