### PR TITLE
Remove deprecated methods from GUtil

### PR DESCRIPTION
**Pull request by donat**
### Summary
 - GUtil.addToCollection(T dest, boolean failOnNull, Iterable<? extends V>... srcs)
 - GUtil.addToCollection(T dest, Iterable<? extends V>... srcs)

### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Review by jjohannes — APPROVED** [review]
Looks good.

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
This change breaks kotlin-mpp 1.3. The methods are simple enough so I think we should just keep them a while longer.

**Pull request closed without merging**
