### PR TITLE
Move task property validation task dependency declaration in the corresponding plugin

### PR DESCRIPTION
**Pull request by eskatos**
This is a follow up to https://github.com/gradle/gradle/pull/4478

### CODE REVIEW

**Comment by eskatos** [comment]
Feedback build https://builds.gradle.org/viewQueued.html?itemId=11265461

**Comment by eskatos** [comment]
Feedback build https://builds.gradle.org/viewQueued.html?itemId=11279255

**Comment by eskatos** [comment]
Feedback build https://builds.gradle.org/viewQueued.html?itemId=11288684

**Comment by bamboo** [comment]
Feedback build: https://builds.gradle.org/viewQueued.html?itemId=11292515

**Pull request merged**
