### PR TITLE
Zinc version update

### PR DESCRIPTION
**Pull request by wolfs**
### Context
This uses the Zinc 1.2 instead of the old 0.x Zinc version.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by klass-ivan** [comment]
Could someone please update PR to fix merge conflicts with `master`?
This feature is of high importance for us we even back-ported it on top of 5.3 and 5.5 release with almost auto-merging, but with 5.6 merge attempts some integration tests are failing at the end.
Thanks.

**Comment by klass-ivan** [comment]
> Could someone please update PR to fix merge conflicts with `master`?
Nevermind, no conflicts if using squashed version from `https://github.com/snazy`.

**Comment by snazy** [comment]
Be careful with that squashed version. It was an experiment and has issues, some builds work, some don’t. And I‘m not confident that the rebase&squash is correct.

**Comment by klass-ivan** [comment]
@snazy Thanks. Then requesting an update again :)

**Comment by moonkev** [comment]
+1 
This too is very important to us.  Most Scala projects are now building out Scala 2.13 dependencies, and with Gradle we are still stuck with 2.11 for the most part.  I fear Gradle will not be a viable option for Scala developers in the near future.  I would much rather use Gradle over SBT, but alas we must be able to update our dependencies and soon many projects are going to cease creating 2.11 packages.

**Comment by klass-ivan** [comment]
@moonkev Not clear why you still stick to 2.11 because we use scala 2.12.8 in our project already. The problem is in outdated `zinc` itself with many critical bugs for an incremental compilation that have been fixed since 0.3.15 to 1.2.5, such as https://github.com/sbt/zinc/issues/417 https://github.com/sbt/zinc/issues/543 https://github.com/sbt/zinc/issues/559
So with the official  gradle distribution you could use 2.12 but with constant pain of frequent `clean` and `--rerun-tasks`

**Comment by moonkev** [comment]
@eyalroth Sorry, it has nearly a year that I tried, but there was definitely something holding us back.  Now that I think about it, it may have been more that the old zinc required scala 2.11 as its own dependency and this was bleeding into the classpath of other plugins that we were looking to move to 2.12 (one of which I believe was Akka grpc).  Sorry, as mentioned been a while so I could be slightly off even here.

**Comment by eyalroth** [comment]
@moonkev Well, indeed there was [that workaround](https://github.com/typesafehub/zinc/issues/87#issuecomment-229943907) needed to be applied in order to make things work fine. Maybe that was what held you back.

**Pull request merged**
