### PR TITLE
Fix #4012 AWS Java SDK libraries are too old

### LINKED ISSUE #4012: AWS Java SDK libraries are too old
Trying to publish to an s3 bucket in Canada, but get:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenJavaPublicationToMaven2Repository'.
> Failed to publish publication 'mavenJava' to repository 'maven2'
   > Could not write to resource 's3://redacted'.
      > Not able to determine region for ca-central-1.Please upgrade to a newer version of the SDK
```
This is because the `aws-java-sdk-core-1.11.6.jar` is missing the Canada region that was introduced back in 2016.

Can these libraries be updated?

### PR DESCRIPTION
**Pull request by dhoer**
Signed-off-by: Dennis Hoer <dennis.hoer@pearson.com>

### Context
Update AWS SDK in order to publish to new regions and avoid "Please upgrade to a newer version of the SDK" warning.

Fix #4012 AWS Java SDK libraries are too old

@bmuschko Tests failed because of deprecation warnings.  I think this is fine, but I will let you guys make the decision whether to accept this as-is or require refactor to remove deprecation warnings.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] Make sure that all commmits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by dhoer** [comment]
Tests failed because of deprecation warnings. I think this is fine, but I will let you guys make the decision whether to accept this as-is or require refactor to remove deprecation warnings.

**Comment by dhoer** [comment]
@bmuschko This is more difficult than I have the bandwidth for.  It is important that latest sdk be in the next release.  Can we go with the deprecation warnings disabled? Also note that sdk 2.0 is coming, but it only supports jdk 8 or higher.  Maybe the time to refactor would be with sdk 2.0 and gradle 5?  Until then, keep the sdk 1.11.x version updated with deprecation warnings?

**Comment by bmuschko** [comment]
@dhoer We can't keep the deprecation warnings as our build is configured to catch them and fail if they are encountered. We'll discuss internally how this can be prioritized.

> Also note that sdk 2.0 is coming, but it only supports jdk 8 or higher.

Gradle likely won't be able to make the switch to SDK 2.0 before we don't make the general decision to drop Java 7 support. I guess it won't be happening before Gradle 5.0.

**Comment by oehme** [comment]
You could use `@SuppressWarnings("deprecation")` on those specific methods. And then with Gradle 5.0 (and dropping Java 7) we can upgrade straight to the 2.0 SDK.

**Comment by uriahcarpenter** [comment]
The replacement for these methods is to construct the S3 client using an AmazonS3ClientBuilder.

`AmazonS3 amazonS3Client = AmazonS3ClientBuilder.standard().withRegion(...).build();`

[Related StackOverflow question](https://stackoverflow.com/questions/41951978/amazons3clientcredentials-is-deprecated/41952575#41952575)

**Comment by dhoer** [comment]
@uriahcarpenter The code uses gets and sets in different methods which causes problems when using AmazonS3ClientBuilder because AmazonS3 should be immutable.

**Comment by dhoer** [comment]
Latest errors are related to uses chunked encoding by default now (rather than sending the raw bytes).  See https://github.com/jubos/fake-s3/issues/164

```
Caused by: com.amazonaws.SdkClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: cBCkDYxUNJqtpajrqxevAA== in base 64) didn't match hash (etag: 57ac448bf48e092bf3326f1d25c42a5d in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@50e69bbb, bucketName: tests3Bucket, key: maven/org/gradle/test/publishS3Test/1.0/publishS3Test-1.0.jar)
```

**Comment by dhoer** [comment]
@bmuschko This PR should be good to go now.  I went with @oehme's suggestion to suppress deprecation warnings.  I also had to disable chunked encoding since it has been enabled since 1.11.16 and causes "Unable to verify integrity of data upload" errors.

I only see 2 checks running instead of all 7?  Is there a way for me to trigger them?

**Comment by dhoer** [comment]
One last question;
How do I ensure Gradle 5.0 will have 2.0 SDK refactor as part of its development?

**Comment by oehme** [comment]
I've scheduled a follow-up issue for 5.0

**Pull request closed without merging**
