### PR TITLE
Add subtree feature to FileTree

### PR DESCRIPTION
**Pull request by kenzierocks**
### Context
This is a more generic solution to #1108. It allows the expansion of any `FileTree` as if it were rooted at a different directory.

I'm open to suggestions on rewordings for the documentation, I'm not sure it's as clear or concise as it could be.

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [X] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by wszeboreq** [comment]
@kenzierocks - so, what is the plan here - do you think it is possible to finalize this feature and have it assigned to some milestone?

**Comment by kenzierocks** [comment]
I am finished on my end with this. It's awaiting the Gradle team to review and merge.

**Comment by kenzierocks** [comment]
Merge conflicts have been fixed. This is ready to be reviewed again.

**Comment by wszeboreq** [comment]
@kenzierocks Great, thanks!

**Comment by wszeboreq** [comment]
Unfortunately, there are some conflicts again. I'm not aware of the Gradle development process details - once conflicts are resolved again, is there any method for increasing the chances that someone from Gradle team will review @kenzierocks changes?

**Comment by kenzierocks** [comment]
Updated to the new doc format and having both a Groovy and Kotlin DSL example. This is ready for review again.

**Comment by wszeboreq** [comment]
I imagine and understand that Gradle team is currently fully booked. But, anyway, maybe someone will find some time for reviewing this feature, please?

**Comment by wpbeckwith** [comment]
I just spent hours looking for a cleaner way to do this.  I hope the gradle team will take note and merge this for 5.0.

**Comment by wszeboreq** [comment]
Dear Gradle team, what are the plans and the situation here - could you please review and merge this feature? Or should it be implemented in some other way?

**Comment by big-guy** [comment]
@kenzierocks Thanks for the PR!

I replied to the underlying issue:
https://github.com/gradle/gradle/issues/1108#issuecomment-458739241

I don't think it makes sense to add a `subTree` to the Project API at this time.  I am going to look at extracting your sample/doc changes and at least demonstrating how this can be done with the existing APIs for 5.3.

Sorry it took us so long to get back to you.  I'm going through our backlog of issues/PRs and getting responses back to everyone.

**Comment by wszeboreq** [comment]
@big-guy, I think the 'subTree()' proposed by @kenzierocks is added to the FileTree API, not to the Project API. So, the example usage:

`zipTree('src/resources/program.zip').subTree('bin')`

**Comment by lacasseio** [comment]
As explained by @big-guy, this use case can be solved with currently available APIs. There is an issue for empty directories that we will address separately. We will not introduce a new API at this time. See https://github.com/gradle/gradle/pull/8494 for the documentation PR.

**Pull request closed without merging**
