### PR TITLE
Update doc tests in snippets/bestPractices

### PR DESCRIPTION
**Pull request by mlopatkin**
This is a major overhaul. All integration tests are replaced with exemplar-based tests to avoid "where are the tests?" confusion. Tests duplicated by the new sanityCheck are rewritten, and missing coverage added to ensure task execution correctness where needed.

Part of #21027

### CODE REVIEW

**Review by nathan-contino — APPROVED** [review]
LGTM

**Review by 6hundreds — APPROVED** [review]
LGTM!

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Review by bamboo — COMMENTED** [review]
👍

**Pull request merged**
