### PR TITLE
Fix native compiler metadata detection on non-english locales

### LINKED ISSUE #15803: gcc native tool chain detection does not work with german locale on linux
The gcc native tool chain detection does not work with german locale on linux:

`LC_MESSAGES="de_DE.UTF-8"`

Instead of gcc the clang toolchain is chosen: `Tool chain 'clang' (Clang)`

When trying to enforce gcc tool chain in build.gradle.kts:
```
for (tc in toolChains) 
  if (tc.name == "gcc")
    compileTask.get().toolChain.set(tc)

```

Gradle fails at `org.gradle.nativeplatform.toolchain.internal.gcc.metadata.GccMetadataProvider:111`: 

```
Execution failed for task ':jni:cpp:compileDebugCpp'.
> Could not determine GCC metadata: could not find vendor in output of /usr/bin/gcc.
```

The problematic gcc is:

```
gcc -dM -E -v -
Es werden eingebaute Spezifikationen verwendet.
COLLECT_GCC=gcc
Ziel: x86_64-pc-linux-gnu
Konfiguriert mit: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread-Modell: posix
Unterstützte LTO-Kompressionsalgorithmen: zlib zstd
gcc-Version 10.2.0 (GCC) 
COLLECT_GCC_OPTIONS='-dM' '-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/cc1 -E -quiet -v - -mtune=generic -march=x86-64 -dM
nicht vorhandenes Verzeichnis »/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/include« wird ignoriert
Suche für »#include "..."« beginnt hier:
Suche für »#include <...>« beginnt hier:
 /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include
 /usr/local/include
 /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed
 /usr/include
Ende der Suchliste.
```

When running gradle with `LC_MESSAGES="en_US.UTF-8"` it works:

Chosen tool chain: `Tool chain 'gcc' (GNU GCC)`

### PR DESCRIPTION
**Pull request by NyCodeGHG**
Fixes #15803

### Context

Users with non-English locales are able to use native toolchains. View #15803 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

I did not add an integration test because I do not know how to run a test with a specific environment variable and how to make sure the non english locale is available on the system. Without this PR some tests fail on my machine because I'm using a german locale. With this PR all tests are passing.

### CODE REVIEW

**Comment by NyCodeGHG** [comment]
I'm not sure if the failing tests are caused by my change. What should I do?

**Comment by TravDev01** [comment]
@NyCodeGHG Hey,
did you find a solution for this issue? 
I'm wondering why this simple fix is still not merged

**Comment by jprante** [comment]
Using the native C locale

```
execSpec.environment("LC_MESSAGES", "C");
```

might be a better alternative.

**Comment by NyCodeGHG** [comment]
@ov7a thank you for picking this up, i rebased my branch and changed the locale to C.

**Comment by ov7a** [comment]
@NyCodeGHG Thank you for a fast reply! Sorry again for dragging this out for so long. 

Sending for merge.

**Comment by ov7a** [comment]
@bot-gradle merge

**Comment by ov7a** [comment]
@bot-gradle merge. (checking if it's just CI problem)

**Pull request merged**
