### PR TITLE
Always use single-use daemon when in no-daemon mode

### PR DESCRIPTION
**Pull request by rieske**
This will always fork a new JVM to run the build and allow a single place for build JVM arguments to be set. 
This is relevant for running with Java 16 where we have to explicitly `--add-opens` for modules that Gradle accesses reflectively
during the build.

This is a possible alternative for https://github.com/gradle/gradle/pull/16434

### CODE REVIEW

**Comment by bigdaz** [comment]
Note that this will break the use case where a running build requires complex user interactions. https://blog.mrhaki.com/2010/09/gradle-goodness-get-user-input-values.html

I don't think we can remove the ability to run without a daemon until we have a solution to https://github.com/gradle/gradle/issues/2842

**Comment by jjohannes** [comment]
Closing this, as we can't "just do it" due to the use cases we might break. We may keep the branch, to reuse something from it if we should get back to this.

**Comment by lestephane** [comment]
Do I understand it correctly that the daemon will always be created, and that this warning is misleading?
```
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Starting process 'Gradle build daemon'
```
Please clarify what the current situation is, I read the entire issue comments, and am now lost.

I wasted some time trying to set JAVA_HOME to match exactly the build jvm args, then I added even more memory, still to no avail. The daemon kept being spawned, and the warning let me down a path that there was a way to disable it. If it's simply not possible, the warning needs to go, and the `--no-daemon` option needs to go.

**Comment by big-guy** [comment]
@lestephane 

> Do I understand it correctly that the daemon will always be created, and that this warning is misleading?

Nothing has changed here in 7.0. Gradle will always create a daemon if the JVM that starts the build is incompatible with what the build needs. Gradle compares Java home, exact JVM arguments and memory requested (a JVM with a larger heap is considered compatible).

> I wasted some time trying to set JAVA_HOME to match exactly the build jvm args, then I added even more memory, still to no avail:

The hard part here is that the arguments that need to be passed to the build are not just what `org.gradle.jvmargs` says. Gradle may also add arguments (like `--add-opens`), so if you want to use the client JVM to run the build, you have to also add those same arguments (in the same order) to make everything line up.

If you run your build with `--info`, you'll see a line starting with `Starting process 'Gradle build daemon'.` followed by the arguments actually passed to the daemon JVM.

Do you actually need to not use a daemon?

**Comment by lestephane** [comment]
If gradle is going to ignore `--no-daemon` , it should have the decency to fail when it cannot honour it, and give contextual information. 

# Suggestion for improvement

## Before
`To honour the JVM settings for this build a single-use Daemon process will be forked. See a-web-page-without-contextual-information`

## After
```
WARNING: -no-daemon won't be honored, because
- host vm has -mx.., build vm needs at least -mx...
- host vm java home is ..., build vm needs ...
- host vm jvm arguments are ..., build vm needs ...
```

or (even better):
```
ERROR: --no-daemon cannot be honored, aborting
- host vm has -mx.., build vm needs at least -mx...
- host vm java home is ..., build vm needs ...
- host vm jvm arguments are ..., build vm needs ...
```

# > Do you actually need to not use a daemon?

I've used gradle in the RUN command of some Dockerfile, and I'd like to have control over whether a daemon is going to start as a side-effect of the RUN command or not, because I don't have any insight as to how the docker daemon manages these children processes forked during docker builds, and I don't care enough about Docker to find out. I come from the maven ecosystem where no process is left over when the build command in a RUN line is over. I want that choice in gradle too, and you added `--no-daemon`, so you wanted it for your users too. Choice is good when you don't know all the use cases of your users.

**Pull request closed without merging**
