### PR TITLE
Pass init scripts to buildSrc

### LINKED ISSUE #14563: TAPI: Offer API to obtain all included builds with nested builds and buildSrc
Currently, tools such as IDEA need to separately request a model of buildSrc. Nested included builds are not found at all (https://youtrack.jetbrains.com/issue/IDEA-204526).

This could be solved by making [GradleBuild.getIncludedBuilds()](https://github.com/gradle/gradle/blob/7f371d8a1dc49006abed56bf75412326ed31f2ee/subprojects/tooling-api/src/main/java/org/gradle/tooling/model/gradle/GradleBuild.java#L57) return all this information or by adding a new API for it.

### PR DESCRIPTION
**Pull request by oehme**
This brings it in line with other included builds and allows IntelliJ to register its custom
model builder for the buildSrc build. This is a prerequisite for them using the new editableBuilds
property instead of doing two separate Tooling API invocations.

Signed-off-by: Stefan Oehme <st.oehme@gmail.com>

Fixes #14563

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by oehme** [comment]
@big-guy can you give this another go? I've fixed the failing tests.

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle help

**Comment by donat** [comment]
@bot-gradle cancel

**Comment by big-guy** [comment]
@oehme I need a bit of time to look into the impact of this. IIRC, we did want to do this, but we may break existing builds that have init scripts that usually never run against buildSrc.

**Comment by oehme** [comment]
Yep, that makes sense. Thanks for looking into it!

**Comment by oehme** [comment]
That sounds great and would make the whole setup easier :+1:

**Pull request closed without merging**
