### PR TITLE
Migrate from Guava cache to Caffeine (fixes #7757)

### LINKED ISSUE #7757: Check Caffeine to replace Guava caches
@ben-manes on [the dev list](https://groups.google.com/d/msgid/gradle-dev/689dae24-5fcf-4399-be6b-594cc91e8d17%40googlegroups.com):

> Since Gradle 5.0 is Java 8-based, the usages of Guava's cache can be replaced with Caffeine. There seem to be [25 files](https://github.com/gradle/gradle/search?p=2&q=%22com.google.common.cache.CacheBuilder%22&type=&utf8=%E2%9C%93) importing it - are any of these performance critical like in your original testing Luke / Lari? If so, you can switch over without much complexity. You may want to set to Caffeine.executor(Runnable::run) if callbacks (like RemovalListener) need to run on a known thread (vs ForkJoinPool). I'd also advise reviewing your ample usage of soft/weak references, since soft is fairly a poor approach in most cases.

We should see how this works as a replacement. The benchmarks look promising: https://github.com/ben-manes/caffeine/wiki/Benchmarks

image

### PR DESCRIPTION
**Pull request by ben-manes**
Fixes #7757

### Context
As requested by @lptr, this migrates usages of Guava Cache to Caffeine. The intent of this PR is to evaluate for performance gains or regressions.

Due to similar APIs, the migration is mostly switching imports and using Java 8 syntax. This is notable because,
- `UnitTestAndCompileExtension` promoted `usedInWorkers` from Java 1.6 to 1.8
- This upgrade adds new compiler warnings, such as heap pollution, which are suppressed as out of scope.
- `ExecutionException`, `UncheckedExecutionException`, and `UncheckedException` are not needed with Caffeine so removed, but possibly upstream catches could be impacted. The changes assume no surprising exception handling.
- Caffeine defers work such as removal notifications to ForkJoinPool, rather than penalizing user-facing threads. This can have a negative impact if user callbacks require a thread-local context or tests query for eviction behavior. If so, the simplest approach is to disable async (via `Caffeine.executor(Runnable::run)`) to mirror Guava.

There are some test failures, e.g. fixture classpath issues, which are not fixed as this PR is for profiling. Similarly, the verification-metadata to add the new dependency grew beyond this scope and might be pruned down.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test QFL

**Review by lptr — CHANGES_REQUESTED** [review]
I think we need to add Caffeine to the worker classpath here: https://github.com/gradle/gradle/blob/f9f7816605305bf71e476b55eadf03db3d9f02ed/subprojects/core/src/main/java/org/gradle/process/internal/worker/child/WorkerProcessClassPathProvider.java#L102-L112

From the performance test results that we already got I don't see much of an improvement.

What worries me a little, too, is the extra thread pool required for handling evictions IIUC. That seems like something we'd at least want to control.

We can't currently upgrade `usedInWorkers` to Java 1.8 as Gradle requires them to be Java 6-compatible, though that can change, especially with Gradle 7 coming.

All of this together makes me think we shouldn't invest further into moving to Caffeine at this time.

We could fix the problem with the worker classpath, and re-run the performance tests as half of them failed because of the above problem, though I doubt the remaining tests would show a significant improvement.

There are some code changes that'd be nice to keep even if we did not move to Caffeine, like the suppressed warnings, and using `Cache.getUnchecked()` instead of handling all those `ExecutionException`s separately. If you are willing to create a PR for that, I'd be happy to merge it.

**Comment by ben-manes** [comment]
> From the performance test results that we already got I don't see much of an improvement.

This was my expectation. The cache data structures do not appear to be bottlenecks for the use-cases, so the improvements have little actual speedup. The typical cases where the cache has a large impact don't match what I saw.
1. Extremely high rate of access, often by multiple threads. For example ErrorProne observed a 30% speedup migrating their AST cache, since the compiler had to evaluate that constantly.
2. High miss penalty, e.g. dozens of milliseconds, where an improved hit rate allows for reducing overall load and downscale expensive resources like a database. For example Expedia observed this for their hotel catalog.
3. Ability to introduce a cache where the hit penalty was previously too high due to synchronization overhead. For example Apache Druid reduced latencies in by offering a Caffeine/Memcached setup, where their prior attempts at a local cache was unsuccessful as caused worse latencies than always going to Memcached.

> What worries me a little, too, is the extra thread pool required for handling evictions IIUC. That seems like something we'd at least want to control.

As mentioned in the PR, this can be disabled using `Caffeine.executor(Runnable::run)`. However that has to be done on each builder, as the default is to defer. The work Caffeine does for evictions is very cheap, but we defer by default to the JVM pool. This is to reduce user-facing latencies as there can be user callbacks that might be slow. Disabling the async behavior has no detrimental effect, but has to be done at every one of your dozen-plus caches.

> All of this together makes me think we shouldn't invest further into moving to Caffeine at this time.

Yes, this was my inclination. I wasn't pushing this change as it seemed unlikely to benefit other than modernizing some old code. The discussions by the Gradle team on the data structure performance was valid, but doesn't translate to your actual bottlenecks.

> There are some code changes that'd be nice to keep even if we did not move to Caffeine, like the suppressed warnings, and using Cache.getUnchecked() instead of handling all those ExecutionExceptions separately. If you are willing to create a PR for that, I'd be happy to merge it.

I think the warnings should be resolved and not suppressed, e.g. heap pollution, but that requires knowing what is safe as it could affect API contracts (may be fine if all are internal). These types of code quality improvements should be done by someone else who is familiar with the internals, e.g. my last PR was in 2012! 😄

**Comment by ben-manes** [comment]
Updated the worker classpath and set the executor to same thread.

**Comment by lptr** [comment]
Looks like there's a compile error, can you please check that?

**Comment by ben-manes** [comment]
Sorry, fixed.

**Comment by lptr** [comment]
Sorry, can you please update to latest `master`? Seems like there are some conflicts.

**Comment by ben-manes** [comment]
done

**Comment by lptr** [comment]
> > What worries me a little, too, is the extra thread pool required for handling evictions IIUC. That seems like something we'd at least want to control.
> 
> As mentioned in the PR, this can be disabled using `Caffeine.executor(Runnable::run)`. However that has to be done on each builder, as the default is to defer. The work Caffeine does for evictions is very cheap, but we defer by default to the JVM pool. This is to reduce user-facing latencies as there can be user callbacks that might be slow. Disabling the async behavior has no detrimental effect, but has to be done at every one of your dozen-plus caches.

Yeah, though we could do this by creating some centralized factory for caches. It's some added complexity but not unreasonable if there are benefits.

> > All of this together makes me think we shouldn't invest further into moving to Caffeine at this time.
> 
> Yes, this was my inclination. I wasn't pushing this change as it seemed unlikely to benefit other than modernizing some old code. The discussions by the Gradle team on the data structure performance was valid, but doesn't translate to your actual bottlenecks.

I ran one more regression test but I still see no evidence of improvements: https://builds.gradle.org/buildConfiguration/Gradle_Check_PerformanceTest10_Trigger/40075297?buildTab=report_project52654_Performance

As you say, this is understandable.

> > There are some code changes that'd be nice to keep even if we did not move to Caffeine, like the suppressed warnings, and using Cache.getUnchecked() instead of handling all those ExecutionExceptions separately. If you are willing to create a PR for that, I'd be happy to merge it.
> 
> I think the warnings should be resolved and not suppressed, e.g. heap pollution, but that requires knowing what is safe as it could affect API contracts (may be fine if all are internal). These types of code quality improvements should be done by someone else who is familiar with the internals, e.g. my last PR was in 2012! 😄

Alright, let's not do this then. I'll try to come back to your PR and salvage the improvements in some ways soon.

Thanks for checking this anyway!

**Pull request closed without merging**
