### PR TITLE
Remove Spock retry logic from continuous build tests

### PR DESCRIPTION
**Pull request by wolfs**
The retry logic shouldn't be necessary any more - the regular test retry plugin should be enough.

### CODE REVIEW

**Comment by wolfs** [comment]
Also move https://github.com/gradle/gradle-private/issues/3499 out of test quarantine, since it doesn't seem to be very flaky any more.

**Review by asodja — APPROVED** [review]
LGTM

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
