### PR TITLE
Remove requirement for extra `#exception` call in `ProblemReporter`

### PR DESCRIPTION
**Pull request by drippypop**
This PR addresses issue #30896, which reports that using the `throwing` method in the `ProblemReporter` requires an extra `#exception` call even when a well-formed problem is defined. This fix ensures that a default exception is provided if none is set, improving the API's usability.

### CODE REVIEW

**Comment by drippypop** [comment]
@bot-gradle test this

**Comment by drippypop** [comment]
This commit aligns with Donát's request:

> * If no exception is provided, it now throws a `RuntimeException`.
> * The exception message will use the `contextualLabel` if specified; otherwise, it will fall back to the display name of the problem Id.

**Comment by drippypop** [comment]
Alright! I'll get to that now.

**Comment by drippypop** [comment]
Hi @ov7a,

I’ve made the requested changes and reformatted everything accordingly. Please let me know if there’s anything else you need!

**Review by donat — CHANGES_REQUESTED** [review]
Looks good, only test coverage is missing. Please add coverage in ProblemsServiceIntegrationTest. In addition, provide cross-version coverage similar to `ProblemProgressEventCrossVersionTest` in the `org.gradle.integtests.tooling.r812` package.

**Comment by drippypop** [comment]
Thank you for the reply.

I'll get to that now!

**Comment by donat** [comment]
FYI, we decided to change the API and require the exception reference a mandatory method argument: https://github.com/gradle/gradle/pull/31844/files#diff-95d67bc14752cba0de62be9a2d229267b91901f498163671ea354a39efad2334R78

**Pull request closed without merging**
