### PR TITLE
Group configuration cache inputs by type in the report

### PR DESCRIPTION
**Pull request by bamboo**
For a better experience.

Before this PR, inputs are not grouped:

Screen Shot 2022-01-06 at 13 51 16

After this PR, inputs grouped by type:

Screen Shot 2022-01-06 at 13 46 08

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
