### PR TITLE
Clean up Version Catalog API

### LINKED ISSUE #18097: Inconsistent name in TOML vs API. [libraries] versus findDependencies
The names of the items in the TOML file all match the `VersionsCatalog.find*` functions except one, which is `[libraries]` versus `findDependencies`. 

`[versions]` -> `VersionCatalog::findVersion`
`[bundles]` -> `VersionCatalog::findBundle`
`[plugins]` -> `VersionCatalog::findPlugin`

but this doesn't match: 

`[libraries]` -> `VersionCatalog::findDependency`

Is it not a dependency until it is added to a configuration in a `dependencies {}` block, until then it is just a library in a catalog. :) 

I propose renaming it to match: 

`[libraries]` -> `VersionCatalog::findLibrary`

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #18097.

This implements the changes discussed in https://github.com/gradle/gradle/issues/18097#issuecomment-988265959.

@melix if you have any opinions on the changes, aside from the specific changes described in the comment above, please let me know.

### CODE REVIEW

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by melix** [comment]
Except the fact I disagree this makes this more consistent (look at `findLibrary` returning an `ExternalModuleDependency` or `DependencyModel` which represent _realized_ dependencies), I do agree that this PR does what it intends to do ;)

**Comment by octylFractal** [comment]
> look at `findLibrary` returning an `ExternalModuleDependency`

I'm confused what you mean by this -- it returns `MinimalExternalModuleDependency`, which despite the name is not even a `Dependency`, nor is it really "realized" beyond the resolution of the `version.ref`. It hasn't been turned into a proper `Dependency` yet.

And a `DependencyModel` is even worse -- it doesn't even necessarily have a realized version reference.

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by melix** [comment]
What I mean is that `MinimalExternalModuleDependency` is a dependency notation which is realized and contains all the required information for Gradle to add a dependency to a container: it has a module identifier and a version constraint. It is recognized by the dependency container and can be added.

I agree though that `DependencyModel` is not a super nice name, but its a step closer to a realized dependency.

**Review by ljacomet — CHANGES_REQUESTED** [review]
LGTM overall!

Two things to fix I believe:

**Review by ljacomet — APPROVED** [review]

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Pull request merged**
