### PR TITLE
adding forked ant worker

### PR DESCRIPTION
**Pull request by ethankhall**
Some things we will need to figure out:

 - How to not fork every time
 - What should the memory setting be?

### CODE REVIEW

**Comment by pioterj** [comment]
@ethankhall From what I learned we'll not merge it in this form so I'm closing this PR for now. @big-guy will get back to you with more feedback. Thank you for continuing to contribute.

**Comment by DPUkyle** [comment]
Hi @pioterj, here's a patch that will allow this PR to compile successfully. It was just a package import mistake, likely covered up by the OP's IDE.

I'm interested in daemonization for other 3rd party tools (discussed with @bigdaz [here](https://groups.google.com/d/msg/gradle-dev/b3VeOWvA8SE/Lf0ykleDEwAJ)) and getting this PR merged would be an interesting step forward.

@ethankhall let's talk if you're still interested in this change.

Thanks,
Kyle Moore

[Patch_for_PR_#524_(89d866).patch.zip](https://github.com/gradle/gradle/files/137037/Patch_for_PR_.524_.89d866.patch.zip)

**Comment by pioterj** [comment]
@DPUkyle Thank you for the patch.

@bigdaz @big-guy Could you follow up on this?

**Comment by DPUkyle** [comment]
Thanks @pioterj. What good timing. I was able to meet and speak with @ethankhall and @hansd last night at a meetup and explain my interest in this PR. Ethan explained that it's better in the long run to stay away from 'specialized worker daemons' specific to certain non-compilation processes, and that's why this PR was closed. 

I completely understand and agree with that direction, so I'm fine to leave this closed as-is. I may try my hand at a contribution of my own in the coming days/weeks, so please have an eye out for that.

Thanks again and sorry for the noise.

**Comment by pioterj** [comment]
@DPUkyle No worries at all. We are looking forward to your contributions. Sorry for the late response.

**Pull request closed without merging**
