### PR TITLE
Bump guides plugin version to 0.21 and fix issues

### PR DESCRIPTION
**Pull request by mlopatkin**
The new version uses `tasks` task for sanityCheck test. The rest of the commit adapts or fixes existing tests.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Review by blindpirate — COMMENTED** [review]
LGTM!

@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
