### PR TITLE
refactor the line with +

### PR DESCRIPTION
**Pull request by counter-reverse**
Fixes [15936](https://github.com/gradle/gradle/issues/15936)

### Context

This commit does not pass the sanity check but is very most likely not responsible of this issue. It still can run.
The unit test fail. It is a problem from my computer.

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [X] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by counter-reverse** [comment]
DCO says my commit is signed with None instead of my email address. It used to be tru but I changed with git config user.email and set my real email address. See: https://github.com/gradle/gradle/pull/15937/commits/b68a8a0bf6f2a79e836193666df26e51af8021be

**Comment by counter-reverse** [comment]
If travis passes the test, then the pull request will be ready to merge.

**Comment by counter-reverse** [comment]
@rieske do you considere it as ready to merge please?

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle.

Using `String.format` provides more readability and the performance impact is irrelevant for an exception message.
Also updating one message in isolation makes little sense.

Note that the agreement in the Gradle team is to _keep_ `String.format` for exception messages.

So this PR will not be merged.

**Pull request closed without merging**
