### PR TITLE
Use credentials defined in Root project

### PR DESCRIPTION
**Pull request by blindpirate**

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Comment by blindpirate** [comment]
The promotion build: https://builds.gradle.org/viewLog.html?buildId=45447321&tab=buildResultsDiv&buildTypeId=Gradle_Master_Promotion_PublishBranchSnapshotFromQuickFeedback

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
