### PR TITLE
Add JDK 21 compiling and testing support

### LINKED ISSUE #25573: Support compiling and testing with Java 21
```[tasklist]
### Steps to complete
- [x] Add JDK to CI (separate PR, so the below is testable)
- [ ] https://github.com/gradle/gradle/pull/25708
- [ ] Remove unsupported warning from `JavaVersion`
- [ ] Add future entry to `JavaVersion` to maintain 2-year window of future version constants
- [ ] Update `JaCoCoCoverage` cutoffs if necessary
- [ ] Update compatibility table
- [ ] Update `GroovyCompileToolchainIntegrationTest#can compile source and run tests using Java #javaVersion for Groovy`, and the similar one for `ScalaCompileToolchainIntegrationTest`
- [ ] Update `JavaVersionSpec` and `JavaClassUtilTest`
- [ ] Update list of cross-compile JavaVersions in `JavaCrossCompilationIntegrationTest`
```

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #25573

### CODE REVIEW

**Comment by octylFractal** [comment]
@bot-gradle test this

**Comment by octylFractal** [comment]
@bot-gradle test this

**Review by lkasso — APPROVED** [review]

**Review by tresat — APPROVED** [review]

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Review by big-guy — APPROVED** [review]
Do we have a test anywhere that shows we can run tests with Java 21?

**Comment by octylFractal** [comment]
That's the Groovy and Scala tests changed in this PR, though I note that we haven't been updating `JavaCrossCompilationIntegrationTest`, so I'll do that in another PR and add it to the issue tasklist for next time.

**Pull request merged**
