### PR TITLE
Not fail the build if cleanup step finds leftover test files

### PR DESCRIPTION
**Pull request by blindpirate**
Previously, if a build (for example [this one](https://ge.gradle.org/s/ujgthnmbkhtqu)) is cancelled or crashed and leaves leftover test files,
the next build cleanup step will fail, which is not right. Let's cleanup everything
in cleanup step.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Review by jjohannes — APPROVED** [review]

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test SC

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle test SC

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle clean

**Comment by blindpirate** [comment]
Thanks @jjohannes !

**Pull request merged**
