### PR TITLE
Fix CollectionPropertyInternal

### LINKED ISSUE #8943: DomainObjectCollection.addAllLater not usable
I was trying to use `configuration.getDependencies().addAllLater(...)` with a self-made provider, and this failed with a class cast exception.

### Expected Behavior

I can pass a self-made `Provider<? extends Iterable<T>>` to the `addAllLater` method of any `DomainObjectCollection<T>` such as `DefaultDependencySet`.

### Current Behavior

In `DefaultDomainObjectCollection`, which is the implementation used for `DefaultDependencySet`'s internal `backingSet`, the `addAllLater` method attempts to do an unchecked cast of the given provider to `CollectionProviderInternal`, of which the only implementation in the entire codebase is `org.gradle.api.internal.plugins.DefaultArtifactPublicationSet.DefaultArtifactProvider`, therefore any other use case of `addAllLater` fails with a `ClassCastException`.

Example of `DependencySet.addAllLater` when given a `project.provider(...)`:

```
Caused by: java.lang.ClassCastException: org.gradle.api.internal.provider.DefaultProvider cannot be cast to org.gradle.api.internal.provider.CollectionProviderInternal
    at org.gradle.api.internal.DefaultDomainObjectCollection.addAllLater(DefaultDomainObjectCollection.java:279)
    at org.gradle.api.internal.DelegatingDomainObjectSet.addAllLater(DelegatingDomainObjectSet.java:94)
```

### Context

I'm trying to all some dependencies to a configuration, but I can only create the dependencies after a task ran. Therefore, I was going to use a provider mapped from that task's output, and pass that to `configuration.getDependencies().addAllLater(...)`.

Specifically, I've had to rely on [this hack](https://github.com/palantir/sls-packaging/pull/484/files#diff-6d4c01f1969f35a1e407e8c9a921d748R49) in https://github.com/palantir/sls-packaging/pull/484, whereas what I really want is to delay the creation of dependencies to after a task has run (which produces the lock-file that I build the dependencies from).

### Your Environment

Build scan URL:

### PR DESCRIPTION
**Pull request by dansanduleac**
Signed-off-by: Dan Sanduleac <sanduleac.dan@gmail.com>

Fixes #8943

### Context

I want to use `addAllLater` on a configuration's dependencies or constraints.
However, I can't, because no matter what I pass in, it fails with a `ClassCastException` as the internal code from `DefaultDomainObjectCollection.addAllLater` expects a `CollectionProviderInternal`, of which there is only a single internal implementation.
https://github.com/gradle/gradle/blob/1fb12afd4f34951c9c2bd8a592fda8ef5da18dd1/subprojects/core/src/main/java/org/gradle/api/internal/DefaultDomainObjectCollection.java#L296

### Solution

Allow `ListProperty`, `SetProperty` to be passed to `addAllLater`, by making `CollectionPropertyInternal` (an interface they implement) extend `CollectionProviderInternal`.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by dansanduleac** [comment]
I don't understand why these tests keep failing, it seems like a flake every time :(

```
* What went wrong:

Execution failed for task ':distributions:checkBinaryCompatibility'.
> Could not resolve all files for configuration ':distributions:japicmp-baseline-Antlr'.
   > Could not download gradle.zip (gradle:gradle:5.6)
      > Could not get resource 'https://services.gradle.org/distributions/gradle-5.6-bin.zip'.
         > Could not GET 'https://downloads.gradle-dn.com/distributions/gradle-5.6-bin.zip'.
            > peer not authenticated
```

**Comment by dansanduleac** [comment]
I'm happy to add tests here too if you think it's worth it, currently all the applicable tests mock a `CollectionProviderInternal` so they never expose the fact that nothing public actually implements it..

**Comment by lacasseio** [comment]
Just to properly understand the issue. Here, we are fixing the issue where you would have something like the following:
```
def c = project.container(String)
def l = project.objects.listProperty(String)
c.addAllLater(l)  // This fails because of the uncheck cast?

// Somewhere else:
l.add('some-string-later')
```

Currently adding the `ListProperty` to the container via `addAllLater` fails because of the uncheck cast? If that is the case, then we can look into adding tests to `AbstractDomainObjectCollectionSpec` to verify all domain object collection behave the same. This PR shouldn't try to solve issues around custom implementation of `CollectionProviderInternal` as this is an internal API and unlikely to be made public or even allow custom implementation by the users.

**Comment by lacasseio** [comment]
We are currently tracking down the `peer not authenticated` issue, you can safely ignore for now.

**Comment by dansanduleac** [comment]
> Currently adding the ListProperty to the container via addAllLater fails because of the uncheck cast
yes that's right

> This PR shouldn't try to solve issues around custom implementation of CollectionProviderInternal as this is an internal API and unlikely to be made public or even allow custom implementation by the users.
Not sure what you mean. This is just the most convenient way, I thought, to make existing collections all pass the unchecked cast.
It also makes sense that `CollectionPropertyInternal` would implement `CollectionProviderInternal`, since `PropertyInternal` implements `ProviderInternal`.
The fact that it's an internal API is even better, as it's not a break to make `CollectionPropertyInternal` implement another class.

**Comment by lacasseio** [comment]
I added the tests to https://github.com/gradle/gradle/pull/10426 which will supersede this PR. As soon as CI pass, we will merge it. Thanks for your contribution.

**Pull request closed without merging**
