### PR TITLE
Improve doc test coverage (maven)

### PR DESCRIPTION
**Pull request by mlopatkin**
Couple of changes in user-visible snippets to ensure configuration cache compatibility. The rest is either clean up of duplicate/misplaced files, or adding missing coverage.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test BD, PRF

**Comment by mlopatkin** [comment]
@bot-gradle test BD, PRF

**Review by 6hundreds — APPROVED** [review]
LGTM!

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Review by bamboo — COMMENTED** [review]
👍

**Pull request merged**
