### PR TITLE
Fixed Broken Link

### PR DESCRIPTION
**Pull request by pieces029**
Removed broken link to codehaus.org and updated with link to groovy-lang site for compiler customizations.

### CODE REVIEW

**Comment by eljobe** [comment]
Hey @pieces029, thanks for cleaning up broken links. Before we can accept a pull request, we need you to sign our CLA. Can you [follow the instructions found here](http://gradle.org/contributor-license-agreement/) to get it signed for us?

Thanks again,
~Pepper

**Comment by pieces029** [comment]
@eljobe No problem, just signed it this morning, and confirmed my email for it right now.

**Comment by eljobe** [comment]
@pieces029 Thanks for fixing broken links. They are the broken windows of a codebase.

We want to make sure all contributors know how much we appreciate the help you provide,
~Pepper

**Comment by pieces029** [comment]
No problem, just doing what I can.

I'll keep my eye out for any more.

**Comment by adrianbk** [comment]
It would be cool to have a test to find and verify all links in our documentation. I'm not saying that should happen as part of this PR :)

**Comment by pieces029** [comment]
If only I had more time! I'll add it to my to-do list. Parse all URLs then do a get to see if they 404 or just search for old codhaus links?

**Comment by adrianbk** [comment]
I think we would want to know about any dead links, so yes all URLs.

**Pull request merged**
