### PR TITLE
try to fix broken wtp tools

### PR DESCRIPTION
**Pull request by bfarka**
http://forums.gradle.org/gradle/topics/wtp-plugin-broken-with-eclipse-lunar-4-4-x?rfm=1

this PR should fix the bug with luna if you have any sugestions how to improve let me know

### CODE REVIEW

**Comment by erdi** [comment]
Thanks for the contribution @bfarka, somebody will be having a look at it shortly.

In the meantime, would you mind signing the CLA online at www.gradleware.com/contributor-agreement? Without it we won't be able to accept your contribution.

**Comment by bigdaz** [comment]
Hi @bfarka. Thanks for you contribution.

Without a signed CLA, we are not able to apply any pull requests. Are you able to sign one online at www.gradleware.com/contributor-agreement?

If not, I plan to close this pull request.

**Comment by bigdaz** [comment]
Before we can consider applying this we'd need a few things:
- A clear definition of the bug that you're trying to solve.
- A breaking test that demonstrates the bug, that is fixed by your changes

These things don't guarantee that we'd be able to merge your PR. But without them we definitely are not able to.

**Comment by alkemist** [comment]
Hi @bfarka 

Can you please the questions from @bigdaz above.

**Comment by pioterj** [comment]
I'm closing this one for now because of the lack of response from the contributor. @bfarka Feel free to re-open it if you'd like to still push it forward.

**Pull request closed without merging**
