### PR TITLE
Check in some inspections to help us find Checkstyle violations early

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

As proposed in https://github.com/gradle/gradle-private/issues/2171 , we want to mark some violations as error in IDEA so we can catch them before pushing to CI.

### CODE REVIEW

**Comment by blindpirate** [comment]
@gradle/build-tool Can you please try it out locally (with this branch) and give me feedbacks? I leave some comments in https://github.com/gradle/gradle-private/issues/2171 :

I reviewed [the most recent `sanityCheck` failures](https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_SanityCheck&tab=buildTypeHistoryList&state=failed) and checked-in the following rule as error in IDEA:

- Unused imports in Java files.
- Field/method naming convention (`a-z][A-Za-z\d]*`)
- Unnecessary parentheses for lambda 
- Empty catch blocks

Some rules reported by codeNarc/Checkstyle but no corresponding rule in IDEA:

- Java - '}' at column 9 should be alone on a line.
- Unused imports in Groovy files - I'm surprised I didn't find it in `Preference` - `Editor` - `Inspections` - `Groovy`
- Groovy - ImportFromSamePackage
- Groovy - UnnecessaryGroovyImport

**Comment by paplorinc** [comment]
FYI @blindpirate, this may be in conflict with https://github.com/gradle/gradle/pull/9939

**Comment by blindpirate** [comment]
Thanks @paplorinc for the heads-up, let's see who can merge it first :-)

**Comment by blindpirate** [comment]
Merge it to benefit developers.

**Comment by melix** [comment]
Thanks a lot for this!

**Comment by paplorinc** [comment]
> Merge it to benefit developers.

you just merged it so you can win the git conflict resolution race :p

**Pull request merged**
