### PR TITLE
Emit deprecation warning if calling setCanBeX on a configuration where isCanBeXed is already true

### PR DESCRIPTION
**Pull request by tresat**
To address the test failures due to unexpected new deprecation warnings that are the result of:

1. The Kotlin Plugin (this is the biggest problem, this plugin frequently redundantly setting usage to true which is already true)
2. The Android Plugin (also frequent usage here)
3. The Shadow Plugin (1 failure in smoke test)
4. The Error Prone Plugin (1 failure in smoke test)

This now modifies the initial spec to add special cases for avoiding emitting this warning for `LEGACY` or `detached`, or specific reserved configurations.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
I know we talked about this already, but I'd like some other input from the team. I worry that this deprecation is going to cause more harm than good. While we do not have any documentation explicitly using the pattern of setting these flags to true when they're already true, I believe this is quite a common pattern and in a way serves as documentation.
```
configurations {
    myConfig {
        canBeResolved = true
        canBeConsumed = false
    }
}
```

[Users are clearly already doing this](https://github.com/search?q=%22canBeResolved+%3D+true%22&type=code)

I think once we make this change, we're going to cause all users (or those who are proactive and update gradle often) to update all their buildscripts -- only to have them need to do it again for 8.3 in the same places in order to use the new configuration roles API.

**Comment by tresat** [comment]
I still think it's worth doing to put a spotlight on unnecessary calls and spread awareness that new configurations created by this mechanism are by default consumable and resolvable.  This will help make the forthcoming changes to configuration make more sense.

It's only a deprecation warning and there will be other warning users have to correct (through no fault of their own) when upgrading Gradle minor versions.

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test APT

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by TWiStErRob** [comment]
@tresat what can we (as end users) do with this?

I get:
> \> Configure project :
> The resolvable usage is already allowed on configuration ':testFixturesRuntimeClasspath'. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Remove the call to setCanBeResolved(true), it has no effect. Consult the upgrading guide for further information: https://docs.gradle.org/8.2-milestone-1/userguide/upgrading_version_8.html#redundant_configuration_usage_activation

for a simple:
```kotlin
plugins {
	id("org.gradle.java-test-fixtures")
	id("org.jetbrains.kotlin.jvm") version "1.8.20"
}
```
in 8.2-milestone-1.

**Comment by tresat** [comment]
@TWiStErRob This is not a combination I considered during development.  Let me investigate further and see what's going on here.

The intention was to carve out exceptions for popular plugins such as these so that the end users would not see these warnings, as there isn't anything you can do other than reach out to their maintainers.

**Comment by TWiStErRob** [comment]
Cool @tresat, thanks, let me know if you need more info.

**Pull request merged**
