### PR TITLE
Update default to latest Zinc compiler version

### PR DESCRIPTION
**Pull request by bigdaz**
Version 1.6.1 of the Zinc compiler brings in a dependency with a critical security vulnerability. While there's no evidence that this issue impacts Gradle, if it can easily
be resolved with this upgrade, then we should do it.

### CODE REVIEW

**Review by ghale — APPROVED** [review]
LGTM

**Comment by ljacomet** [comment]
Force pushed to resolve the doc test issues, see #25909

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Review by ljacomet — APPROVED** [review]

**Pull request merged**
