### PR TITLE
verification-metadata Trust.Reasons and Checksum.Reasons

### LINKED ISSUE #20260: Add reason attribute for <component> elements in verification-metadata.xml
We want to move toward a world in which we verify signatures on all of our dependencies.  However, we can't get there because not all of our dependencies have valid signatures yet.  For these other dependencies, we add checksums to the [components](https://docs.gradle.org/current/userguide/dependency_verification.html#sec:checksum-verification) element in verification-metadata.xml.

However, we want to be sure that when we do this, we are tracking the blocking reasons why we can't use signature verification yet.  Specifically, we'd like to add a `reason` attribute to `<component>`, so that we can add a link to a bug that's tracking the effort to get a signed artifact:

```xml
<component group="g" name="g" version="3.1" reason="Unsigned github.com/foo/bar/issues/43489">
  <artifact name="g-3.1.jar">
    <sha256
      value="f5759b7fcdfc83a525a0336b625ebc282426f16ca137eb5902"
      origin="Generated by Gradle"
    />
  </artifact>
</component>
```

### PR DESCRIPTION
**Pull request by mathjeff**
Fixes #20260

### Context
This should allow us to specify a Reason for Trust entries and sha256 entries.
We're already specifying these values via commands and/or nonstandard attributes, and having Gradle recognize them allows us to observe fewer differences when asking Gradle to regenerate the dependency-verification.xml

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Review by asodja — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by asodja** [comment]
@bot-gradle cancel

**Comment by asodja** [comment]
I forgot that it would be good to update also dependency-verification-*.xsd schema. 

So @bot-gradle test this, for now.

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by mathjeff** [comment]
Thanks!

**Pull request merged**
