### PR TITLE
Share root build cache configuration with included builds loaded from the configuration cache

### PR DESCRIPTION
**Pull request by bamboo**
Fixes #?

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test this

**Review by wolfs — COMMENTED** [review]
I must admit I don't understand most of the changes. I didn't find anything which looked strange to me, though. IIUC, the fix for the root project path in included builds being wrong was to create the Gradle launcher for the included build in a new way. Moreover, now the build layout is now created directly from the configuration cache instead of trying to find the correct layout by using the start parameter.

**Comment by bamboo** [comment]
Thanks for the review, @wolfs! 

> the fix for the root project path in included builds being wrong was to create the Gradle launcher for the included build in a new way

For the root project path, the fix was to get the root directory from `BuildLayout.settingsDir` together with injecting a pre-configured `BuildLayout` in each included build `BuildScopeServices`.

The `createGradleLauncher` change wouldn't be strictly necessary in this PR. That's mostly about robustness, not having a GradleLauncher that can accidentally run any configuration logic when running from the cache.

The other consequential change in this PR is calling `RootBuildCacheControllerSettingsProcessor.process` after loading the build cache settings for the root build from the configuration cache. `BuildCacheCompositeConfigurationIntegrationTest` wouldn't pass without it.

**Pull request merged**
