### PR TITLE
Separate jacoco configurations to consumed and resolved ones.

### LINKED ISSUE #11209: [Jacoco plugin] Consider to fall back to defaults if user provided dependencies do not resolve to jacoco
When adding a platform as a dependency to a configuration, `defaultDependencies` does not run, even if it is the only dependency.

### Expected Behavior

Since a platform can only define constraints, not actual dependencies, it should not prevent `defaultDependencies` from running.

### Current Behavior

When the only dependency is a platform, `Configuration.defaultDependencies` is not run.

### Context

In a project using the `jacoco` plugin, a construct like this attempting to apply a platform to all configurations in a project

```kotlin
configurations.configureEach {
  dependencies.add(configuration.name, platform(project(":platform")))
}
```

The project fails to run tests with this error message

```
> Task :project:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':project:test'.
> Expected configuration ':project:jacocoAgent' to contain exactly one file, however, it contains no files.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Perhaps applying a platform to all configurations like that is not a good pattern (open to suggestions). However, applying a platform to jacoco configurations to manage their versions along with all other versions in a platform, as opposed to having to set the version in the jacoco extension, seems like a valid use case.

Even if this is not considered a valid use case, the error message is too confusing to understand the relationship to the problem (adding platforms to the jacoco configuration isn't supported). In that case, I'd recommend updating the Jacoco plugin to understand this case and provide a better error message or behavior, possibly using `withDependencies`.

### Steps to Reproduce 

https://github.com/anuraaga/gradle-platform-default-dependencies

`./gradlew test jacocoTestReport`

### Your Environment

Gradle 6.0-rc-2, Windows, Java 13 (zulu)

### PR DESCRIPTION
**Pull request by anuraaga**
Fixes #11209

Currently, Jacoco defines two configurations for resolving tools, `jacocoAnt` and `jacocoAgent`. These are "legacy" configurations as they are both consumable and resolvable, which is deprecated as per the documentation.

https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs

Thanks to @jjohannes help in #12016, I learned about these different types of configurations, and a generic way of applying platforms is to make sure they're applied to non-consumable configurations. I feel this is the best solution to my earlier issue, #11209 where I found applying a platform to jacoco configurations breaks the build. `withDependencies` behavior is great already for consumed configurations, and platforms can be applied to resolved ones.

Need help in how to properly deprecate the legacy configurations' `canBeResolved` flag

### Context

- Removes a legacy (`true`, `true`) configuration
- Allows users to apply platforms to jacoco configurations if they would like to manage jacoco tool versions using platforms

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
  - Existing tests
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
  - Existing tests
- [X] Update User Guide, DSL Reference, and Javadoc for public-facing changes
  - Just implementation detail
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`
  - `./gradlew :jacoco:check` fails on master on my machine for `project is relocatable`, and with this change has the same single failure

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by jjohannes** [comment]
Hi @anuraaga, while you are right in general about the configurations, we are not yet at the point that we completely deprecated the "legacy" usage. We only did that in the context of the Java plugins and the configurations it adds. I am inclined to wait with a change here until there is a real benefit.

Unless there is a benefit already. Why do you think this is needed to use platforms here? Is it because of the `defaultDependencies` behavior? If yes, could you please share a complete example of how this change helps there.

**Comment by anuraaga** [comment]
Hi @jjohannes - thanks for the context. I agree there's no need in changing without significant benefit. 

I will get a code example pushed tomorrow but to describe in words, as you've probably realized I have been on a journey trying to use platforms to solve all my dependency management needs. Your comment on this other issue

https://github.com/gradle/gradle/issues/12016#issuecomment-579177392

made me think applying to resolved, non-consumed configurations is the best practice for achieving this.

**Comment by anuraaga** [comment]
Sorry was typing on mobile and accidentally hit the close button (though feel free to close if this PR doesn't make any sense :) )

**Comment by jjohannes** [comment]
@anuraaga In a more involved setup, like the Java library plugin, the recommendation is to have configurations that are `canBeResolved=false` **and** `canBeConsumed=false` as _buckets for dependencies_ (e.g. `implementation`, `api`). You should use these to declare any kind of dependencies: traditional dependencies to libraries as well as platform dependencies.

In a simple case like this one, it is still ok to use one configuration for everything. I.e. have one configuration to declare, resolve (and possible consume). If we want to refine this further, we should do the full split up into all three dependency types (consumable, resolvable, bucket). But for that this PR does not go far enough. And as said, I think it is not worth the trouble here at the moment.

If you have a concrete example/use case, where the current setup is causing a practical problem, please open a separate issue and we can discuss the best solution.

**Pull request closed without merging**
