### PR TITLE
Update Gson library 2.2.4 -> 2.4

### PR DESCRIPTION
**Pull request by vbauer**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [ ] Before submitting a pull request, I started a discussion on the
[Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev)
or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I wrote a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [ ] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by wolfs** [comment]
Hi @vbauer 

Thank you for your pull request. Could you give a short motivation why you want to update gson from 2.2.4 to 2.4? What problem is that solving for you?

**Comment by vbauer** [comment]
Hello @wolfs,

Sorry, I had to add this information before. I've just wanted to suggest to update Gson library. Version 2.4 is the last which is compatible with JDK 1.5 and contains some bug fixes.

Additional information could be found here: https://github.com/google/gson/blob/master/CHANGELOG.md

**Comment by wolfs** [comment]
Your PR has been merged and will be included in 3.1. Thank you very much!

**Comment by wolfs** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-6169

**Comment by vbauer** [comment]
Thank you!

**Pull request merged**
