### PR TITLE
Deprecate any task dependency removal on `Task` instance

### PR DESCRIPTION
**Pull request by lacasseio**
### Context

See https://github.com/gradle/gradle-native/issues/790

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and [CI build status](https://builds.gradle.org/project.html?projectId=Gradle_Check&tab=projectOverview&branch_Gradle_Check=lacasseio%2Flazy%2Fremoving-task-dependencies)
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by GFriedrich** [comment]
@big-guy, thank you very much for your detailed explanation. You definitely should add the list of possible other solutions to the changelog for 4.10.

For me no. 3 should work out. (Somehow I completely missed that ```set``` will clear the dependencies as a first step - which of course makes sense, otherwise it would be ```add``` :man_facepalming: ) And it's good to know that this method will be kept.

As you asked for more information: The situation is a bit more complicated why I need some dependencies to be removed.
I'm using the SonarQube Gradle plugin from https://github.com/SonarSource/sonar-scanner-gradle
This plugin depends on compile and test tasks (which of course makes sense). But in my CI pipeline I don't want the SonarQube to be executed all the time (because it's rather time consuming), therefore the project is regularly build with the ```build``` task and after that has finished, the pipeline decides on some properties whether the SonarQube task should be executed.

Normally this would be fine, because Gradle should skip the compile/test of the project, because it's up-to-date. But unfortunately I'm struggeling with the same problem as people already mentioned here: https://discuss.gradle.org/t/gradle-re-execute-tasks-due-to-alleged-jar-dependency-change/23115
As I was unable to find the root-cause for this problem, I decided to remove the dependency to the compile/test tasks as they are always executed beforehand. So I can get back to this problem, when I have a bit more time for investigation.

Sorry for all this text, didn't want to trigger a bigger discussion on this PR.
And thanks again for all your help! Really appreciate it!

**Comment by big-guy** [comment]
This won't make 4.10, but I think it's a good idea to put this into the user guide + release notes.

**Comment by lacasseio** [comment]
Given the next Gradle version is 5.0, I changed the deprecation to be done in Gradle 6.0 instead.

**Comment by TWiStErRob** [comment]
@big-guy so if I see this right your comment and its third point above means that
```gradle
// Groovy / KTS
task.dependsOn.remove(otherTask)
// KTS
task.dependsOn -= otherTask // compiles to a call to MutableSet<Any!>!.remove()
```
is deprecated in Gradle 5 and throws in Gradle 6, but
```gradle
// Groovy / KTS
task.setDependsOn(task.dependsOn - otherTask)
// Groovy
task.dependsOn -= otherTask // executes as property re-assigment: get+minus+set
```
works fine on all versions?

Note the same syntax giving different behaviors. To me it looks like it just got more confusing and still unsafe as before even with trivial Groovy syntax.

**Pull request merged**
