### PR TITLE
Remove automated publishing deprecation

### PR DESCRIPTION
**Pull request by jbartok**

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Review by ljacomet — CHANGES_REQUESTED** [review]
Changes LGTM, but since we do not have the go for a 7.6 RC1 yet, please target `release` so the deprecation goes away in 7.6 already.

**Comment by ljacomet** [comment]
@breskeby FYI we will keep the flag around

**Comment by breskeby** [comment]
Thank you!

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
> Changes LGTM, but since we do not have the go for a 7.6 RC1 yet, please target `release` so the deprecation goes away in 7.6 already.

Done.

**Pull request merged**
