### PR TITLE
Update the providers-property-convention snippets to be cc compatible

### LINKED ISSUE #21819: CCH22-22: Adjust the `snippets/providers/propertyConvention` sample for configuration cache
The sample project located under [`subprojects/docs/src/snippets/providers/propertyConvention`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/providers/propertyConvention) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-providers-property-convention_groovy_propertyConvention.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket3SnippetsTest/snippet-providers-property-convention_groovy_propertyConvention.sample)
    ```
    Could not get unknown property 'objects' for task ':show' of type org.gradle.api.DefaultTask.
    ```

* `snippet-providers-property-convention_kotlin_propertyConvention.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket3SnippetsTest/snippet-providers-property-convention_kotlin_propertyConvention.sample)
    ```
    Task `:show` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-providers-property-convention_groovy_propertyConvention.sample" \
    --tests "*snippet-providers-property-convention_kotlin_propertyConvention.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/extending-gradle/lazy_configuration.adoc`;

### PR DESCRIPTION
**Pull request by eygraber**
Update the providers-property-convention snippets to be cc compatible

Fixes #21819

### CODE REVIEW

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Comment by abstratt** [comment]
> @eygraber
> 
> Please add your full name and github handle to the list of contributors in the release notes as described [here](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/release/notes.md?plain=1#L6).

Scratch that. I will add your name notes.md while I sync up with latest master.

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
🎉

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by h0tk3y** [comment]
@bot-gradle test and merge

**Pull request merged**
