### PR TITLE
Rework configuration / variant exception messages

### PR DESCRIPTION
**Pull request by ljacomet**
* For ambiguity issues, other attributes are listed before compatible
attributes.
* For incompatibility issues, incompatible attributes are listed first,
followed by other attributes.

### CODE REVIEW

**Comment by ljacomet** [comment]
What about replacing `Other attribute(s)` with `Unmatched attribute(s)` when it comes first?

**Comment by melix** [comment]
+1 I think it would be clearer.

**Comment by ljacomet** [comment]
@melix This passes CI, good to go for you?

**Comment by melix** [comment]
All good

**Pull request merged**
