### PR TITLE
Add SOCKS proxy documentation

### PR DESCRIPTION
**Pull request by big-guy**

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test QF

**Review by big-guy — COMMENTED** [review]
test

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@big-guy test QFL

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
See #20476 for the current state of this work.

**Pull request closed without merging**
