### PR TITLE
Introduce core-execution/execution-e2e-tests project

### PR DESCRIPTION
**Pull request by asodja**
And move Execution engine related tests out of integ-tests to execution-integ-tests.

Fixes https://github.com/gradle/gradle-private/issues/4135

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this

**Review by cobexer — APPROVED** [review]

**Comment by asodja** [comment]
@bot-gradle test QFL

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
