### PR TITLE
Add more logging around starting and stopping file system watching

### LINKED ISSUE #16723: Log overflow type when receiving overflow file system watching event
Here we are not logging the type, which can tell us whether it was the OS or our internal queue that overflew:

https://github.com/gradle/gradle/blob/679e14442a12af29b45cb1568960d5e2fdb9330b/subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java#L96-L107

It's also a bit confusing to re-use the `INVALIDATED` event type that might lead someone to think that this has something to do with a change to the watched root on macOS. We probably should handle this without mentioning `INVALIDATED`.

---
cc: @gradle/execution

### LINKED ISSUE #16725: Stop watching file system if watcher thread quits unexpectedly
If the watcher thread exits due to an exception, we log the following, but do not disable watching:

```text
2021-04-07T08:53:51.765+0200 [ERROR] [system.err] Exception in thread "File watcher consumer" java.lang.RuntimeException: Error!!!
2021-04-07T08:53:51.765+0200 [ERROR] [system.err] 	at org.gradle.internal.watch.registry.impl.DefaultFileWatcherRegistry.lambda$createAndStartEventConsumerThread$0(DefaultFileWatcherRegistry.java:83)
2021-04-07T08:53:51.765+0200 [ERROR] [system.err] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

We should probably do that.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by lptr**
Fixes #16725 
Fixes #16723

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by blindpirate** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
