### PR TITLE
Make KotlinBuildScriptModel construction more lenient

### PR DESCRIPTION
**Pull request by jjohannes**
See: https://github.com/gradle/gradle/issues/15404#issuecomment-839643261

### CODE REVIEW

**Comment by jjohannes** [comment]
@bot-gradle test QF

**Comment by jjohannes** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by jjohannes** [comment]
@bot-gradle test this

**Review by donat — APPROVED** [review]

**Pull request merged**
