### PR TITLE
Upgrade Codenarc plugin

### PR DESCRIPTION
**Pull request by asodja**
Except for config and configFile, since they cause failure of Gradleception that needs more research.

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test AST

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Review by tresat — APPROVED** [review]

**Pull request merged**
