### PR TITLE
Deprecate running tests on Java 7 and lower

### LINKED ISSUE #23490: Deprecate running Gradle workers on Java runtimes below 8

### PR DESCRIPTION
**Pull request by jvandort**
Fixes #23490

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by hythloda — APPROVED** [review]
The messages are clear and verbose.

**Review by tresat — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
