### PR TITLE
Fix `kotlin-dsl` plugin version used in `build-logic-commons/code-quality`

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
Thanks, @blindpirate!

**Pull request merged**
