### PR TITLE
Remove slow test from QuickFeedback by disabling it on embedded executor

### PR DESCRIPTION
**Pull request by jbartok**
Fixes:
* https://github.com/gradle/gradle-private/issues/3842

The slow tests are the Kotlin plugin related ones. 
Disabling those for the embedded executed to remove them from Quick Feedback.

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Review by hegyibalint — APPROVED** [review]
LGTM!

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle cancel

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
