### PR TITLE
Upgrade gradle-kotlin-dsl {0.12.1 => 0.12.2}

### PR DESCRIPTION
**Pull request by bamboo**
v0.12.2 includes the fix for #3250 when the applied script is written
in Kotlin.

See #3250

### CODE REVIEW

**Comment by bamboo** [comment]
CI build: https://builds.gradle.org/viewQueued.html?itemId=8913047

**Comment by eskatos** [comment]
CI build failed with a performance failure and could not finish.
The failing test is biased and was just disabled on `release`, I merged `release` on this branch and triggered another CI build: https://builds.gradle.org/viewQueued.html?itemId=8918081
Will merge as soon as it succeeds.

**Comment by jjohannes** [comment]
@eskatos Sorry I forgot that the commit I cherry-picked to disable the performance test was not correct. 🙁 

Also this performance failure that just appeared on this PR branch is due to connectivity issue with jcenter: [RealLifeAndroidBuildPerformanceTest.help on largeAndroidBuild](https://builds.gradle.org/viewLog.html?buildId=8918310&buildTypeId=Gradle_Check_IndividualPerformanceScenarioWorkersLinux&tab=buildResultsDiv)

I am fine if you merge this PR if there are no other issues showing up on CI.

**Comment by eskatos** [comment]
Roger that @jjohannes! Thanks for the heads up

**Pull request merged**
