### PR TITLE
Remove deprecated methods from TestReport

### LINKED ISSUE #21681: Remove @Deprecated methods from TestReport

### PR DESCRIPTION
**Pull request by tresat**
Fixes #21681

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
