### PR TITLE
Fix cpp native cross compile

### LINKED ISSUE #9950: Gradle Native plugin cross-compile is broken
Native library plugin do not allow building for diffrent hosts

Building a native library using the 'cpp-library' plugin does not allow targeting builds for hosts other than the current host. This is a very common senario when using a cross-compiler. For example using mingw on Linux targeting Windows builds. Consider the following example being run on Ubuntu machine with mingw installed.  

```
plugins {
  id 'cpp-library'
}

model {
  toolChains {
    gcc(Gcc) {
      target('linux_x86')
      target('windows_x86') {
        CppCompiler.executable = 'mingw-g++'
        CCompiler.executable = 'mingw-gcc'
      }
    }
  }
}

library {
  targetMachines = [
    machines.windows.x86,
    machines.linux.x86
  ]
}
```

### Expected Behavior
running `gradle tasks` should produce two sets of assemble and build tasks with naming convention following: `assembleLinuxX86` and `assembleWindowsX86`

### Current Behavior
Gradle creates `assemble` task targeting the local host machine only. It is impossible to cross-compile builds targeting Operating Systems other than the host.

### Context
I work mainly with C/C++ developing cross-platform software. We target Windows, Linux, Mac, and Android. I really like to be able to use Maven for native builds just like its done in the Java ecosystem. 

### Steps to Reproduce 
[example.zip](https://github.com/gradle/gradle/files/3388402/example.zip)

### Your Environment
https://gradle.com/s/vhbk6go52j5uo

### PR DESCRIPTION
**Pull request by dinocore1**
Fixes #9950

### Context

This fix enables cross-compiling native Cpp libraries using the CppLibraryPlugin. Previously, the CppLibraryPlugin did not allow targeting builds for operating systems other than the host (see `Dimensions.tryToBuildOnHost()`).

https://github.com/gradle/gradle-native/issues/989
https://github.com/gradle/gradle-native/issues/1020
https://github.com/gradle/gradle-native/issues/992
https://github.com/gradle/gradle-native/issues/487

This change allows setting up cross-compile builds. For example:

```
plugins {
    id 'cpp-library'
}

model {
    toolChains {

        android_clang(Clang) {
            target('android_armv7') {
                path '/data/apps/android-toolchain-arm/bin/'
                cCompiler.executable = 'arm-linux-androideabi-gcc'
                cppCompiler.executable = 'arm-linux-androideabi-g++'
                linker.executable = 'arm-linux-androideabi-g++'
                staticLibArchiver.executable = 'arm-linux-androideabi-ar'
                stripper.executable = 'arm-linux-androideabi-strip'
            }
        }

        mingw(Gcc) {
            target('linux_x86-64')

            target('windows_x86-64') {
                cCompiler.executable = 'x86_64-w64-mingw32-gcc'
                cppCompiler.executable = 'x86_64-w64-mingw32-g++'
                linker.executable = 'x86_64-w64-mingw32-ld'
                staticLibArchiver.executable = 'x86_64-w64-mingw32-ar'
            }

            target('windows_x86') {
                cCompiler.executable = 'i686-w64-mingw32-gcc'
                cppCompiler.executable = 'i686-w64-mingw32-g++'
                linker.executable = 'i686-w64-mingw32-ld'
                staticLibArchiver.executable = 'i686-w64-mingw32-ar'
            }
        }
    }
}

library {
    targetMachines = [
        machines.os('linux').architecture('x86-64'),
        machines.os('windows').architecture('x86-64'),
        machines.os('android').architecture('armv7')
    ]
}

```

This example creates `assembleLinuxX86-64`, `assembleWindowsX86-64`, and `assembleAndroidArmv7` tasks.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by lacasseio** [comment]
Thanks for the PR @dinocore1, I will try to find some time to look at this PR soon.

**Comment by ThadHouse** [comment]
Is there any chance this could make it into Gradle 6? If this was implemented, it would at least be possible for me to at least look at the new native setup, but until this is implemented there would be no way it could ever handle our builds.

**Comment by capadgett** [comment]
+1 for including this change...

**Comment by pedrolamarao** [comment]
Waiting eagerly for this to get in.

**Comment by WalkerKnapp** [comment]
I would love to see this get merged. It would be a great improvement for my build process.

**Comment by WalkerKnapp** [comment]
> Are there any updates on this? I'm blocked on not being able to cross compile cpp, and will likely have to uproot my entire build unless this patch is introduced at some point.

+1, I've been using a forked gradle distribution with these changes merged (https://github.com/WalkerKnapp/gradle/releases/tag/v7.2cc, https://github.com/WalkerKnapp/devolay/blob/release/gradle/wrapper/gradle-wrapper.properties) for more than a year and a half and haven't had any issues. It would be great to see this merged at some point.

**Pull request closed without merging**
