### PR TITLE
Add Kotlin snippet and add additional information to the custom Gradle distribution section

### PR DESCRIPTION
**Pull request by Mazorius**
No issue opened

### Context

As I think a lot users have init scripts and properties which should be consistently used in their projects a better description of the custom Gradle distribution part would be good.
In this case that is the information that I had needed in the beginning to make the development easier.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
I'm having a hard time understanding the problem you're trying to solve here.

**Comment by Mazorius** [comment]
I do not want to solve a problem.
I want to improve the documentation by adding the missing Kotlin DSL example for custom distributions.

Please feel free to tell me what is so hard to understand ;-)

**Comment by JLLeitschuh** [comment]
I'm wondering if all of this is better extracted into an external plugin instead of existing as documentation. 🤔

**Comment by Mazorius** [comment]
> I'm wondering if all of this is better extracted into an external plugin instead of existing as documentation. 🤔

Should it be an external plugin? I think it should be a plugin that is implemented directly in Gradle, like the distribution plugin is. For example something like `gradle-distribution-pugin`.

**Comment by Mazorius** [comment]
I am waiting for feedback … It is not depending on me.

**Pull request closed without merging**
