### PR TITLE
Update `org.gradle.internal.GradleProjectBuilderOptions` option support

### PR DESCRIPTION
**Pull request by alllex**
The internal `org.gradle.internal.GradleProjectBuilderOptions` property was originally introduced for Android Studio to do performance troubleshooting. Some time after that AS started using it in production to improve sync times. More specifically, it [only uses](https://cs.android.com/search?q=GradleProjectBuilderOptions) `omit_all_tasks` value to avoid task realization during sync.

Even though the property is internal, dropping it entirely is not preferable until Gradle introduces an alternative solution to executing sync without task realization. Currently, IntelliJ IDEA requests `org.gradle.tooling.model.idea.IdeaProject` model during sync, which in turn requires `org.gradle.tooling.model.GradleProject` models to be built by the `GradleProjectBuilder`.

This PR removes support for all other values of the option except `omit_all_tasks`. It also adds tests to ensure this functionality is not dropped accidentally in the future.

Overall, this work serves as the preparation for making model building Isolated Projects-compatible. In particular, making the `GradleProjectBuilder` compatible in the follow up PRs.

### CODE REVIEW

**Review by donat — APPROVED** [review]

**Comment by alllex** [comment]
@bot-gradle test without pts

**Comment by alllex** [comment]
@bot-gradle test and merge

**Comment by alllex** [comment]
@donat, the performance tests revealed that the initial refactoring caused a regression in Studio sync scenarios. This was due to the fact that the value for the build option is not yet set when we register model builder. It means that the option value still has to be read during builder execution time (as it was before).

I refactored the PR a bit around this, but there are no major changes. The performance tests seem to be passing now. I also changed the tests to use `LongRunningOperation.withArguments()` (as opposed to setting JVM arguments) to match what Android Studio uses to set the option value. This will catch the problem in the future.

I'll proceed with merging, but feel free to comment later.

**Comment by alllex** [comment]
@bot-gradle test and merge

**Comment by alllex** [comment]
@bot-gradle test PT

**Comment by alllex** [comment]
@bot-gradle test and mereg

**Comment by alllex** [comment]
@bot-gradle test and merge

**Pull request merged**
