### PR TITLE
Re-enable smoke tests after Spock upgrade

### PR DESCRIPTION
**Pull request by eskatos**
They were simply disabled.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by jjohannes** [comment]
Do we also need to update `GradleBuildConfigurationCacheSmokeTest` to use a Tag instead of a Category. Or does this work work for now due to running with the vintage engine?

**Comment by eskatos** [comment]
@jjohannes I'm wondering the same, let's have a look at what CI runs in each job to see

**Comment by jjohannes** [comment]
@rieske will probably know.

**Comment by eskatos** [comment]
@jjohannes it seems the includes/excludes are working https://ge.gradle.org/s/mzeieipgfzgvg/tests?search=GradleBuild

**Comment by eskatos** [comment]
The CI feedback now is green on this PR.
BUT!
The handling of the `@UnsupportedWithTheConfigurationCache` annotation is broken and actually ignore all tests even when there's an `iterationMatchers` clause. This also affects all of our integration tests.

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Pull request merged**
