### PR TITLE
Trim unnecessary info from exported key

### LINKED ISSUE #20947: Key export should only contain necessary information
Currently, a lot of extra information (non-deterministically) is included in the exported key files.

### Expected Behavior
Only export - in the best case scenario - the public key, as it's the only part of the key we require.

### Current Behavior
Lots of extra information is included (e.g. #20919) when the keys are exported.

### PR DESCRIPTION
**Pull request by hegyibalint**
Fixes #20947

### CODE REVIEW

**Comment by hegyibalint** [comment]
@bot-gradle help

**Comment by hegyibalint** [comment]
@bot-gradle test QFL

**Review by ljacomet — APPROVED** [review]
LGTM!
And great impact on the size of the saved keys!

Can you make sure we have a test confirming that keys saved this way do not have to be downloaded to verify signatures?

**Comment by hegyibalint** [comment]
@ljacomet @asodja made a little bit changed format to the key file, to help readability.
A snippet from the file now:
```
=====KEY INFO=====
pub    80662F8192D749A0

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.68

mQENBE1Hdr8BCACnwSb6j+eHyhhe4RJzAW2BqlYSdxfIsjdaTGm3V6GcPzd3JMvO
/PufaPZ4OXVHCwdU2op7qEHkM3GkLIxUx3ZuZhuirdoatW8VjykshDx6/IsTQ7Jr
J+hLS6SdnhS7KrbiLeC4fmeXkAVow09spSgTufhd+fqZ8RV2gbmfgvxOOf1NK8WZ
7E3Tkm7y6Rbz0DHrSqPYd28Od/3fKogFHHIE/srnAR7MEBf3HfEDJk4xTvH3sQ4+
4QOn+eyE9PnoNMvB9H4BfFMEsjNX8ZyoRv7zMLsB1aY3DmzzrcMiudx8qGntDB/G
ufAsZ5MRKH3gY7hW3SvXKOKp52pXfbJ/CSvPABEBAAE=
=ZPuz
-----END PGP PUBLIC KEY BLOCK-----

=====KEY INFO=====
pub    8067ECAA8D58321C

-----BEGIN PGP MESSAGE-----
Version: BCPG v1.68

uQINBFkgf8UBEADP5J79GAJ/dFcxqIbAPiGinK/PJAtIw30BhHzr/MSxF8HjCm3v
4JRaWnladehjg5mwEHCRXMFkxqtVXC1IXQFLFxRplbYMJ362awE+2GYItACWti9i
RoVxh9Pse3/eNLAHAwbFNtDHBPIvmrmUU+/q6XPPTbojRtfLsKW6uKcvF82mZjRJ
GtkUkmO8uMLWJzJDiDYvfXtXsclosdFn+qgGtDU7KVMFCKKUrujTBXsXIKZ02hLC
kI/tVs5iAdEuLjk8Ig1u/3334XiyFEOUctdBGVgjgLg0AUBu75OftG4qJTMadWLe
LU8TvnF7JQaT2ydVCyZxmI5B80xhtmTWWPi7sQWAM353oWfay3lX3cGRbtaAO1bb
NgA8yAIeOU4HO5+zBoP8UZ3aBVArF0eSLUdEdFAaKiP7La/5v2YC5ouE5NRigvb/
6fVkaRlTd0/8ofBKK1eMLTf5JWQz8MahSHSPzG98Q+Rfq+/GCvyatm9Hw7fGS7p9
iaJjh4mdNakJ72dhndYJ4vIyfJyn/EI2tkKXB3K6bCm6OUkc3jyTSyRK2IkCVEGO
qZYntPtlmZd34qoosou7UCz2MTiutypHWMezl+t4QJ5VJSqMed/qI4VLpQqg8cTW
O4f6y6LXcto9i31Kps2Tjn8bHkuZJzkMaBFSbX0POtVAJKW2/PmtmVprCQARAQAB
=rg9S
-----END PGP MESSAGE-----
```

Note the line breaking between the keys, and a new header announcing a new key. Hopefully, with this, it's not going to be such a mess to read this file.

**Comment by hegyibalint** [comment]
@bot-gradle test RFM

**Comment by hegyibalint** [comment]
> Can you make sure we have a test confirming that keys saved this way do not have to be downloaded to verify signatures?

I will see what we have, but we are not using key servers for Gradle - but fact gradle/gradle compiles gives a good hope that there are no issues.

**Comment by hegyibalint** [comment]
@ljacomet found your suggestion: https://github.com/gradle/gradle/blob/3238372e23173455e2970dc6491a8a310d7e66de/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/verification/DependencyVerificationSignatureCheckIntegTest.groovy#L196-L236

**Comment by hegyibalint** [comment]
(Tests are ok, for some reason the Windows QFL run was flaky, I will keep an eye on that one)

**Comment by hegyibalint** [comment]
@bot-gradle help

**Review by ljacomet — APPROVED** [review]
LGTM!

Although it feels a bit weird that we manage to change the export format that much and still parse it without changes to the import side 🤷

**Comment by hegyibalint** [comment]
> Although it feels a bit weird that we manage to change the export format that much and still parse it without changes to the import side 🤷

@ljacomet the trick is: nothing outside of an `-----BEGIN PGP *-----` matters, so you can put whatever (with reasonable limits) around the keys, BouncyCastle's importing is just going to disregard everything else.

**Comment by hegyibalint** [comment]
Meanwhile, PR needs a bit more work, as the key files contain inconsistent data (message and PK blocks).

**Comment by ljacomet** [comment]
@hegyibalint Is this something we can fix in 7.6?

**Pull request closed without merging**
