### PR TITLE
Run watchFs tests without isolated daemons

### LINKED ISSUE #13366: Cannot cancel watching on Windows due to "device or resource busy"
Sometimes cancelling a watch point fails on Windows with
```
Couldn't cancel watch point <work-dir>\subprojects\ide\build\tmp\test files\CompositeBuildIdeaProjectIntegrationTest\builds_IDEA_metadat...ame_build\8484g\buildA: device or resource busy: device or resource busy
```
See for example https://e.grdev.net/s/r7hh2az6r74qy/tests/:ide:vfsRetentionIntegTest/org.gradle.plugins.ide.idea.CompositeBuildIdeaProjectIntegrationTest/builds%20IDEA%20metadata%20with%20substituted%20dependency%20from%20same%20build#1

It seems that Gradle starts watching the project root and then very shortly after stops watching it again, most probably because nothing is left to watch in the project root.

See https://github.com/gradle/gradle/issues/13135#issuecomment-633445781.

---
cc: @gradle/execution

### PR DESCRIPTION
**Pull request by wolfs**
Isolated daemons should not be necessary when file system watching is enabled.

Also bumps `native-platform`.

Fixes #13366.

### CODE REVIEW

**Comment by wolfs** [comment]
Windows and Linux passed now, and macOS has many failures :(

**Comment by wolfs** [comment]
When using native platform `0.22-milestone-4` the macOs tests pass as well...

**Comment by lptr** [comment]
Fired up three builds:

- Linux: https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_36_Trigger/36797880
- macOS: https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_32_Trigger/36797932
- Windows: https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_38_Trigger/36797984

**Comment by wolfs** [comment]
The Linux and Windows builds pass, the macOS build seems to fail :( https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_32_Trigger/36797932

I re-triggered it, though it seems to fail again: https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_32_Trigger/36799774

**Comment by lptr** [comment]
FTR, the problem was that the continuous build tests don't work on JDK14 on macOS. They do work on JDK8:

https://builds.gradle.org/buildConfiguration/Gradle_Check_WatchFs_37_Trigger/36809952

We're all good! \o/

**Comment by lptr** [comment]
@bot-gradle test QF please

**Comment by lptr** [comment]
@bot-gradle test RfM please.

**Comment by wolfs** [comment]
The performance test failure seems to be unrelated to the changes on this branch and is due to the changes on `master` which need to be included in this branch. I'll merge the PR now.

**Pull request merged**
