### PR TITLE
Add API for modifying all consumable/resolvable configurations instead of all configurations

### PR DESCRIPTION
**Pull request by tresat**
Indiscriminate use of calls to methods only applicable to resolvable or consumable configurations inside of actions passed `configurations.all` is a major headache when trying to restrict `DefaultConfiguration` method calls to the [proper allowed usage](https://github.com/gradle/gradle/pull/24183).

Adding some shortcuts to the API can serve as quick replacements for this pattern by plugins and can help discourage this sort of overly broad usage.

### CODE REVIEW

**Review by jvandort — APPROVED** [review]
LGTM but we should probably have an integration test for this

**Comment by tresat** [comment]
> LGTM but we should probably have an integration test for this

Agreed, I just wanted to get a go/no go before putting in any more effort here.  I'd also want to make at least a first pass through snippets/samples and replace `all` where appropriate.

**Review by big-guy — CHANGES_REQUESTED** [review]
I don't think we want to add this yet because you cannot declare or rely on a Configuration having a particular role. I think this will usually not work for configurations created by users.

e.g.,
```
configurations.allResolvable {}
configurations.create("foo") {
    foo.canBeResolved = false
}
```
This will always match "foo". 

This is also a new kind of pattern (`all*`) for containers and doesn't have a lazy alternative.

There are also some alternatives:

- Use new types (`Resolvable` and `Consumable`) and make `configurations.withType(Resolvable).all {}` work. I'm not sure if this is possible given the type bounds on `withType`.
- Use new types and expose containers for those inside the configuration containers. The containers would be views out of the configurations container. This would let you do `configurations.resolvables.all {}` or have a different top-level element.
- Recommend matching: `configurations.matching(it.canBeResolved).all {}`.  This is just as broken as what `allResolvable` does.

**Comment by tresat** [comment]
After further discussion, we won't be doing this.

**Pull request closed without merging**
