### PR TITLE
make jvm args lists unmodifiable

### LINKED ISSUE #22671: forkOptions.jvmArgs.addAll() silently ignored
### Expected Behavior
It would be nice if forkOptions.jvmArgs could be made immutable (so that attempting to modify it fails, prompting us to call `jvmArgs()`) or if modifications to this list could be incorporated into the original list.

### Current Behavior
Currently, modifications to this list appear to do nothing

### Context
In https://issuetracker.google.com/issues/258704137 we discovered some code that was doing this:

```
forkOptions.jvmArgs?.addAll(executionOptions.get().jvmArgs)
```

and discovered that this had no effect.

This appears to be because [DefaultJavaforkOptions.getJvmArgs](https://github.com/gradle/gradle/blob/7df281862d35b7370845ad484ee26b77713255e2/subprojects/core/src/main/java/org/gradle/process/internal/DefaultJavaForkOptions.java#L77) calls [JvmOptions.getJvmArgs](https://github.com/gradle/gradle/blob/7df281862d35b7370845ad484ee26b77713255e2/subprojects/core/src/main/java/org/gradle/process/internal/JvmOptions.java#L175) which copies the list of arguments before returning them.

### PR DESCRIPTION
**Pull request by reinsch82**
- Fixes #22671

### CODE REVIEW

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle help

**Comment by reinsch82** [comment]
@bot-gradle help

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by eskatos — CHANGES_REQUESTED** [review]
This is looking good :+1: 

We should clarify the contract on the javadoc of public API getters.

**Comment by lptr** [comment]
🤔 It would be better to use Guava's `ImmutableList`. That way we only create one object instance instead of two. This is also in line with how we do immutable collections in other places.

**Comment by reinsch82** [comment]
@bot-gradle test AFT

**Review by eskatos — APPROVED** [review]
:+1:

**Comment by reinsch82** [comment]
@bot-gradle test and merge

**Pull request merged**
