### PR TITLE
Fix AndroidJavaCompile not detecting incremental changes

### LINKED ISSUE #11330: Incremental Java compilation is broken with Android 3.5.1 and Gradle 6.0
See https://issuetracker.google.com/issues/144011039

Changes to sources added by the Android Gradle plugin to `AndroidJavaCompile.getSources()` are ignored for incremental Java compilation in Gradle 6.0. When changing a source file, the output is something like this:
```
> Task :mylibrary1:compileReleaseJavaWithJavac UP-TO-DATE
Task :mylibrary1:compileReleaseJavaWithJavac in app Starting
Build cache key for task ':mylibrary1:compileReleaseJavaWithJavac' is 669111c814f7b237087e6a217a4ff93a
Task ':mylibrary1:compileReleaseJavaWithJavac' is not up-to-date because:
  Input property 'sources' file /home/user/test/mylibrary1/src/main/java/com/test/mylibrary1/LibClass.java has changed.
```

Note that there isn't a mention of the input property `stableSources`, which is actually tracked for changes. Not the property `source` of the `SourceTask` is mentioned.

### PR DESCRIPTION
**Pull request by wolfs**
The method `fun getSources(): FileTree` does not override the method
`protected FileCollection getSources()`, since the AGP plugin 3.5.1 has
not been compiled against Gradle 6.0, and therefore the necessary bridge
method is not generated.

Fixes #11330.

### CODE REVIEW

**Comment by wolfs** [comment]
@lptr Please take a look!

**Comment by big-guy** [comment]
Can we update one of the Android smoke tests to do an incremental compile too?

**Comment by wolfs** [comment]
@big-guy We can and we should.

**Comment by wolfs** [comment]
I'll do the smoke test(s) on `master`, given we changed quite a bit in those test already.

**Pull request merged**
