### PR TITLE
Off-by-one error on Windows path length checks

### LINKED ISSUE #21712: Off-by-one error on Windows path length checks
`LongCommandLineDetectionUtil` has an off-by-one error for Windows checks.

The Windows documentation says:
> The maximum length of this string is 32,767 characters, including the Unicode terminating null character.

So the value of 32,767 encoded in Java is wrong, as the Java String _will not include_ the terminating line character.

The value should be updated to account for this, by using 32,766.

### PR DESCRIPTION
**Pull request by Korov**
Fixes #21712 

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Review by blindpirate — APPROVED** [review]

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
Thanks for the contribution. It will be in 8.0.

**Comment by ljacomet** [comment]
We might consider cherry picking this for 7.6

**Pull request merged**
