### PR TITLE
Fixed unpacking of certain valid tar files by switching to Apache commons-compress

### PR DESCRIPTION
**Pull request by pedjak**
Some perfectly valid tar files could not be unpacked by using the following snippet:

```
copy {
  from tarTree("/path/to/foo.tar")
  into "bar"
}
```

i.e. Gradle breaks with the following message:

```
Caused by: org.gradle.api.GradleException: Unable to expand TAR '/path/to/foo.tar'
  The tar might be corrupted or it is compressed in an unexpected way.
  By default the tar tree tries to guess the compression based on the file extension.
  If you need to specify the compression explicitly please refer to the DSL reference.
```

due to this error:

```
Caused by: java.io.IOException: failed to skip current tar entry
        at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:279)
        at org.apache.tools.tar.TarInputStream.paxHeaders(TarInputStream.java:419)
        at org.apache.tools.tar.TarInputStream.getNextEntry(TarInputStream.java:335)
        at org.gradle.api.internal.file.archive.TarFileTree.visitImpl(TarFileTree.java:103)
        at org.gradle.api.internal.file.archive.TarFileTree.visit(TarFileTree.java:85)
```

Basing `NoCloseTarInputStream` to `TarArchiveInputStream` of Apache commons-compress
(already a part of Gradle dependencies) fixed the issue.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
@pedjak Do you have a reproducible example of this?  What's special about the tarball?

We can't just swap out one implementation for another without some integration coverage for this particular case as this may impact existing builds.

**Comment by pedjak** [comment]
@big-guy I have the tarball, and there is nothing special about it, regular `tar` command unpack it without any issues. However, I need to clarify first if I am allowed to share it.

**Comment by pedjak** [comment]
@big-guy 
[foo.zip](https://github.com/gradle/gradle/files/2643857/foo.zip) contains the minimal project that reproduce the issue with Gradle 5.0 or any older version.

Regarding switching the implementation: if I remember correctly, `org.apache.commons.compress.archivers.tar.TarArchiveInputStream` is an evolution of `org.apache.tools.tar.TarInputStream`, see the statement on [Apache Commons Compress](https://commons.apache.org/proper/commons-compress/):

> The bzip2, tar and zip support came from Avalon's Excalibur, but originally from Ant, as far as life in Apache goes

Otherwise the patch could not be so small.

**Comment by pedjak** [comment]
@big-guy did you have a chance to take look at the attached archive?

**Comment by big-guy** [comment]
Hi @pedjak - could you tell me how you created the tarball that doesn't work?  I'd like to recreate it in our integration tests and I'd like to report this upstream to Ant too.

Thanks!

**Comment by pedjak** [comment]
@big-guy I got the tarball from a docker container, using `docker cp` command. Not always the tarball was problematic, and I do not have any steps to reproduce it. However, you can use that tarball in the integration tests...

**Comment by rieske** [comment]
Thank you for the contribution @pedjak!
I have added a test for the fix and will merge it with https://github.com/gradle/gradle/pull/11632 once the CI builds pass.

**Comment by rieske** [comment]
Unfortunately, the changes break other existing tests and we can not merge it as-is.
You can see the build failure here https://builds.gradle.org/viewLog.html?buildId=29389720&buildTypeId=Gradle_Check_Stage_ReadyforMerge_Trigger
Specifically, the `DefaultFileCollectionSnapshotterTest`.

If you intend to fix it, you can rebase from https://github.com/gradle/gradle/pull/11632 which includes a test that addresses the problem being fixed with this PR.

**Comment by lptr** [comment]
I think `commons-io`'s TAR implementation is much slower than what we use right now. It would be good to check our performance tests before investing more into this direction.

**Comment by lptr** [comment]
Actually, I think I remembered wrong, as we are also using TAR from `commons-compress` in the build cache's `TarBuildCacheEntryPacker`. Sorry about the noise, carry on.

**Comment by rieske** [comment]
Closing due to inactivity. @pedjak, if you have any progress regarding https://github.com/gradle/gradle/pull/7901#issuecomment-563966787 please reopen or create a new PR.

**Comment by mkjois** [comment]
There is another potential issue with tarballs in certain environments that can cause this, which I've documented in [this comment](https://github.com/gradle/gradle/issues/23391#issuecomment-1878979127). Just wanted to post this here for visibility, since I came across this thread when trying to debug my own issue. Long story short, make sure your system locale is some form of UTF-8.

**Pull request closed without merging**
