### PR TITLE
Disambiguate extra attributes with remaining candidates

### PR DESCRIPTION
**Pull request by jvandort**
Includes changes to attribute matching to eliminate breaking change after the introduction of `compileElements`. Spec is in-progress. 

Additionally includes a regression test to ensure the introduction of compileElements does not change the behavior.

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by tresat — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
