### PR TITLE
Use a plain text keyring

### PR DESCRIPTION
**Pull request by melix**
and make sure that we don't use key servers, in order to stabilize CI.

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test and merge

**Pull request merged**
