### PR TITLE
Cherry pick "Use 17 for toolchain tests" onto `release`

### PR DESCRIPTION
**Pull request by hegyibalint**

### CODE REVIEW

**Review by wolfs — APPROVED** [review]
I don't really understand what is going on here, so as long as it works it looks good to me.

**Comment by hegyibalint** [comment]
@reinsch82 can you have a peek to verify that this is the intended change of yours?

**Comment by hegyibalint** [comment]
@bot-gradle test and merge please

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
