### PR TITLE
Support detecting packages that are not zip entries

### PR DESCRIPTION
**Pull request by scaventz**
Fixes https://github.com/gradle/gradle/issues/18486

## Why do you believe many users will benefit from this change? 
Because it seems that many intellij-platform plugin developers have ran into the issue.

Intellij Platform packaging has changed since 2021.3,  package  `com.intellij.testFramework.fixtures` of class `BasePlatformTestCase` is no longer an zip entry of `testFramework.jar` , which means plugins developer can not run tests out of the box.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle cancel

**Comment by blindpirate** [comment]
This seems to be a real failure, not flaky: https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Master_Check_Platform_4_bucket30&tab=buildTypeHistoryList&branch_Gradle_Master_Check_Platform_4=pre-test%2Fmaster%2Fcurrent%2Fscaventz%2F18486-package-detecting

**Comment by jbartok** [comment]
> This seems to be a real failure, not flaky: https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Master_Check_Platform_4_bucket30&tab=buildTypeHistoryList&branch_Gradle_Master_Check_Platform_4=pre-test%2Fmaster%2Fcurrent%2Fscaventz%2F18486-package-detecting

Yes it is, but I couldn't reproduce it locally and since then I didn't have time to try again. But will take care of it.

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
