### PR TITLE
Remove duplicate 'm' from default Daemon VM args

### PR DESCRIPTION
**Pull request by marcphilipp**

### CODE REVIEW

**Comment by oehme** [comment]
Shouldn't this go to `release`?

**Comment by marcphilipp** [comment]
Good question. As it seems to work with two Ms I don't think it warrants an RC3 in its own right, does it?

**Comment by oehme** [comment]
It works, but it would probably reflect badly on us if `-Xmx512mm` shows up in the output of tools like `ps`.

**Comment by marcphilipp** [comment]
Agreed, I'll change this PR to target `release`.

**Pull request merged**
