### PR TITLE
Handle null Throwable stack trace to avoid NullPointerException

### LINKED ISSUE #1618: Mocked exception type crashes junit runner and gradle exits with success
Previously reported on JIRA: <https://issues.gradle.org/browse/GRADLE-3556>

If a unit throws a mocked exception with a null stacktrace then the junit test runner fails to mark the test as failed and more importantly it incorrectly exits with code 0 even though the test runner itself encountered an error.

### Expected Behavior
The test should be marked as failed because an exception was not expected to be thrown:

```
:test

com.example.BuggerTest > thisTestShouldBeMarkedAsFailed FAILED
    $java.lang.RuntimeException$$EnhancerByMockitoWithCGLIB$$4bc6e699

1 test completed, 1 failed
:test FAILED

FAILURE: Build failed with an exception.
```

### Current Behavior
The test is not marked as failed and gradle exits with success:

```
:compileJava
:processResources NO-SOURCE
:classes
:compileTestJava
:processTestResources NO-SOURCE
:testClasses
:test
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/0:0:0:0:0:0:0:1:48260'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:90)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:263)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at java.lang.Throwable.setStackTrace(Throwable.java:864)
        at org.gradle.internal.serialize.ExceptionPlaceholder.read(ExceptionPlaceholder.java:154)
        at org.gradle.internal.serialize.TopLevelExceptionPlaceholder.read(TopLevelExceptionPlaceholder.java:24)
        at org.gradle.internal.serialize.ExceptionReplacingObjectInputStream.doResolveObject(ExceptionReplacingObjectInputStream.java:67)
        at org.gradle.internal.serialize.ExceptionReplacingObjectInputStream$1.transform(ExceptionReplacingObjectInputStream.java:31)
        at org.gradle.internal.serialize.ExceptionReplacingObjectInputStream.resolveObject(ExceptionReplacingObjectInputStream.java:62)
        at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1583)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.gradle.internal.serialize.Message.receive(Message.java:55)
        at org.gradle.internal.serialize.BaseSerializerFactory$ThrowableSerializer.read(BaseSerializerFactory.java:235)
        at org.gradle.internal.serialize.BaseSerializerFactory$ThrowableSerializer.read(BaseSerializerFactory.java:233)
        at org.gradle.internal.remote.internal.hub.DefaultMethodArgsSerializer$ArraySerializer.read(DefaultMethodArgsSerializer.java:71)
        at org.gradle.internal.remote.internal.hub.DefaultMethodArgsSerializer$ArraySerializer.read(DefaultMethodArgsSerializer.java:60)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.readArguments(MethodInvocationSerializer.java:124)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.read(MethodInvocationSerializer.java:119)
        at org.gradle.internal.remote.internal.hub.MethodInvocationSerializer$MethodInvocationReader.read(MethodInvocationSerializer.java:99)
        at org.gradle.internal.serialize.kryo.TypeSafeSerializer$1.read(TypeSafeSerializer.java:34)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:66)
        at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:79)
        ... 6 more
:check

BUILD SUCCESSFUL
```

### Context
Our unit tests verify that we handle exceptions properly. As we were migrating between library versions the expected exception had changed but our CI test runner did not report which test had failed because gradle exited with success. We only noticed any problem because the mutation tests failed due to "test not being green".

### Steps to Reproduce (for bugs)
I have created a minimum example project here: <https://github.com/spacecowboy/gradle-junit-bug>

There is a line you can uncomment to make the stacktrace "non-null".

### Your Environment
 * Build scan URL: <https://scans.gradle.com/s/e4gf2urqlgq7q>

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

See #1618 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

### CODE REVIEW

**Comment by bmuschko** [comment]
@blindpirate Just making sure you saw my comments. Are you planning to address those soon?

**Comment by blindpirate** [comment]
Sure, I missed it. I'll tackle it today.

**Comment by blindpirate** [comment]
Sorry for the delay, and this is the first time I write an integration test from scratch, so please let me know if there's anything inappropriate.

**Comment by bmuschko** [comment]
Thanks for the pull request. It has been merged.

**Pull request merged**
