### PR TITLE
Use String.intern for interning

### PR DESCRIPTION
**Pull request by kohlerm**
## Context
We are running a build with a rather large project using the gradle daemon and I'm concerned about the memory usage of the daemon. 
I did some analysis with the Eclipse memory analyzer (see my really old blog post here http://kohlerm.blogspot.de/search?updated-max=2009-07-09T13:35:00-07:00) using the group by value feature and found that there a still quite a few String duplicates. Also the current implementation of the String Interner, does have a relatively high overhead because it uses a complicated data structure to make concurrent access to the strings fast. 
Now since Java 7 the integrated String.intern function is IMHO good enough under most circumstances, because the pool size can be configured and because the strings don't get allocated in perm space anymore . For some performance data check http://java-performance.info/string-intern-in-java-6-7-8/.

Therefore, here comes a small patch that just uses String.intern for interning. 
In my test cases there is a significant reduction in memory usage without a noticeable change in performance.

I had to change  one unit test slightly because it returns a strange NPE from the test framework.

#### Contributor Checklist
- [ x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [ x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x ] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

#### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
Hey Markus,

thank you for the suggestion! However, without some hard profiling data we cannot make a decision here. One of the biggest issues of `String.intern()` was thread contention, another is that we have a lot of users on old JDKs or non-Oracle JDKs. So we can't just flick this switch. We'd need some pretty big performance improvement to warrant a deeper investigation.

**Comment by kohlerm** [comment]
Sure, understood. Is there a standard way to do https://martinfowler.com/bliki/BranchByAbstraction.html in gradle? E.g. can we hide make the implementations switchable using some flag?
I will  try to get some numbers, but the savings could vary very much depending on the project. 
Yes concurrent access is of course a concern, but in my experience (see also link above about what others have measured), you have to have very high concurrent access to see a slow down. 
The current implementation also has to use weak references which need more work to be reclaimed by the garbage collector.

**Comment by oehme** [comment]
We usually use system properties when there is a feature that the user might want to toggle, but which isn't important enough to warrant a command line argument.

**Comment by ijuma** [comment]
See https://shipilev.net/jvm-anatomy-park/10-string-intern/ for some of the issues with String.intern.

**Comment by bmuschko** [comment]
@oehme Where do we stand with this PR? From the conversation it looks like we don't want to merge the change as-is.

**Comment by oehme** [comment]
That's right, we need some data first. Ideally we'd have a memory snapshot showing the duplicate Strings and where they are retained from. The answer might be that there is a place in our code that's not using our interner correctly and we just need to fix that. Or it could be that String.intern is truly better by now. Without more data we can't make that call.

I'll close this PR for now, as it is not clear whether using String.intern is a good move or not. @kohlerm please feel free to open an issue with profiler data attached, so we can dig into this together.

**Pull request closed without merging**
