### PR TITLE
Match userguide Asciidoc filenames to declared URLs

### PR DESCRIPTION
**Pull request by eriwen**
This establishes a convention that allows us to programmatically
figure out which Asciidoc file corresponds to which userguide
chapter, under the goal of allowing quick edits on GitHub.

Issue: gradle/dotorg-docs#59

### Context
Note: performance tests failed on this branch build due to a different change.

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by bamboo** [comment]
Does this PR change any plugin documentation URLs? If it does we need to update the `kotlin-dsl` code generation logic.

**Comment by eriwen** [comment]
@bamboo Yes, it does change a couple of them slightly:

* buildDashboard_plugin.html => build_dashboard_plugin.html
* javaGradle_plugin.html => java_gradle_plugin.html
* javaLibraryDistribution_plugin.html => java_library_distribution_plugin.html
* project_reports_plugin.html => project_report_plugin.html

Please let me know if you want my assistance making the change for Kotlin DSL. Once merged, this change would affect the `/nightly` docs as well as Gradle 4.5+. 

@bamboo It might be helpful for us to know how Kotlin DSL manages this. We'll be rearranging the docs more in the future.

**Comment by big-guy** [comment]
@eriwen I think it's this: https://github.com/gradle/kotlin-dsl/blob/6a3c51a65e8423aa33432b816996360cd32e7906/provider/src/main/kotlin/org/gradle/kotlin/dsl/codegen/PluginIdExtensions.kt

@bamboo This reminds me of an idea I had awhile ago...

Maybe we could/should add a doc URL to the plugin metadata (`META-INF/gradle-plugins/<whatever>.properties` or some programmatic way of listing this).

**Comment by bamboo** [comment]
@eriwen thanks, I'll update the code once this is merged.

@big-guy that's the code.

> Maybe we could/should add a doc URL to the plugin metadata (META-INF/gradle-plugins/<whatever>.properties or some programmatic way of listing this).

Yes, that's going to be  more attractive once we start moving plugins to separate repos.

For the small and closed world of plugins we're managing links for, I think the current solution is fine.

**Comment by eriwen** [comment]
Are you good with this change @lptr or @wolfs or @bmuschko?

**Pull request merged**
