### PR TITLE
Further consolidate Maven dependency mapping

### PR DESCRIPTION
**Pull request by jvandort**
Previous work separated component to an inner ComponentParser class. This PR extends this work
to move the ComponentParser to its own file, renamed to MavenComponentParser. This class contains
all logic requried to map a component's dependencies to their maven representation, including any
existing logic which lived in MavenPomFileGenerator.

Now, MavenPomFileGenerator is properly 'dumb'. It holds no state, encapulates minimal logic, and
serves only to map the Gradle types used to represent POM elements into the Maven types required for
writing POMs.

All logic for resolving project dependencies and performing version mapping has been consolidated into
MavenComponentParser. Now, most future work in this area will likely occur in this class and can avoid
widespread changes.

Three methods on GenerateMavenPom have been deprecated. One is a protected injection method, and two
are now unnecessary given that we preserve source variant information later in the version mapping
process. These methods only accepted internal types, meaning they should not have been used publicly,
and they also are unused by KMP and Android.

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by lkasso — APPROVED** [review]
Docs look good.

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
@bot-gradle cancel

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
