### PR TITLE
Re-enable load-after-store for tests in testing-jvm

### LINKED ISSUE #24613: TestNG test listeners not invoked when configuration cache enabled
The issue is seen with our own tests, as long as load-after-store is enabled.

This test case fails due to the methods annotated with `@BeforeClass` or `@AfterClass` not being invoked.

https://github.com/gradle/gradle/blob/4b1028ee9e9f98aa8856831176fe188b39c4eb36/subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/testng/TestNGGroupByInstancesIntegrationTest.groovy#L26

This test fails due to a `beforeTest` closure not being invoked:

https://github.com/gradle/gradle/blob/ad70dec8704538d4161910611f64afcd7f62ec5c/subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/DefaultTestOrderingIntegrationTest.groovy#L70

### PR DESCRIPTION
**Pull request by abstratt**
Reinstate changes from #25257

Fixes #24613

### CODE REVIEW

**Comment by abstratt** [comment]
@bot-gradle help

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Review by bamboo — APPROVED** [review]

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Pull request merged**
