### PR TITLE
docs: View and Debug Dependencies: add a note about `buildEnvironment`

### PR DESCRIPTION
**Pull request by rybak**
Small addition to section "List Project Dependencies" of page "View and Debug Dependencies".

### CODE REVIEW

**Comment by rybak** [comment]
Rendered, the new note looks like this:

Screenshot_20230727

-----

Off-topic: while working on this pull request, I've stumbled upon directory `subprojects/docs/src/snippets/buildEnvironment/`, which contains snippets used by file `subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc`. It is suspicious that

1. directory of snippets `javaCompileOptions` is the only subdirectory in  `.../buildEnvironment/`, and
2. that the rest of snippets in file `build_environment.adoc` use files from directory `subprojects/docs/src/snippets/tutorial/`.

**Review by ljacomet — APPROVED** [review]
Thank you for this addition

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Review by lkasso — APPROVED** [review]

**Comment by lkasso** [comment]
@bot-gradle test and merge

**Comment by rybak** [comment]
Force pushed a rebase onto fresh `master` with a fix to the build failure. Range diff:

```
$ git range-diff 7b20e5425d1...2f088847976
 -:  ----------- >  1:  3cf275f7908 fixed minor  typo in the docs
 -:  ----------- >  2:  0e127cb5295 Adapt Scala - Java compatibility
 -:  ----------- >  3:  9e38604385f Update wrapper following 8.3-rc2 release
 -:  ----------- >  4:  a0a40d8fc55 Change flaky deprecation warnings to "maybe"
 -:  ----------- >  5:  65c759c4657 Fix regression in copy spec fileMode/dirMode mutation
 -:  ----------- >  6:  8690bb4dbfd Refreeze archunit tests for removed overrides
 -:  ----------- >  7:  e1493592dad Add @Issue to regression test
 -:  ----------- >  8:  8fdbc66dafc Change failing deprecation warnings to 'maybe'
 1:  67c629d6a4c !  9:  2f088847976 docs: View and Debug Dependencies: add a note about `buildEnvironment`
    @@ subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/viewin
     +[NOTE]
     +====
     +Graph of dependencies <<tutorial_using_tasks.adoc#sec:build_script_external_dependencies, declared in the `buildscript` `classpath` configuration>>
    -+can be rendered using <<command_line_interface.adoc#listing_project_dependencies, task `buildEnvironment`>>.
    ++can be rendered using <<command_line_interface.adoc#sec:listing_project_dependencies, task `buildEnvironment`>>.
     +====
     +
      === Output Annotations
      
      The `dependencies` task marks dependency trees with the following annotations:
    +
    + ## subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc ##
    +@@ subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc: image::gradle-core-test-build-scan-dependencies.png[Build Scan dependencies repo
    + 
    + Learn more in <<viewing_debugging_dependencies.adoc#sec:debugging-build-scans,Viewing and debugging dependencies>>.
    + 
    ++[[sec:listing_project_dependencies]]
    + === Listing project dependencies
    + 
    + Running `gradle dependencies` gives you a list of the dependencies of the selected project, broken down by configuration. For each configuration, the direct and transitive dependencies of that configuration are shown in a tree. Below is an example of this report:
```

**Comment by rybak** [comment]
From [TeamCity build log of the previous failure](https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_BuildDistributions/69350402?buildTab=overview&expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true#%2Fdistributions):

> Execution failed for task ':docs:checkDeadInternalLinks'. org.gradle.api.GradleException: Documentation assertion failed: found invalid internal links. See file:///home/tcagent1/agent/work/f63322e10dd6b396/subprojects/docs/build/reports/dead-internal-links.txt

Eventually, I figured out what the problem was by launching the task `:docs:checkDeadInternalLinks` locally and reading the code of `FindBrokenInternalLinks.java`. Maybe there is a faster way of deducing the issue?

Is there a way to get to the file `file:///home/tcagent1/agent/work/f63322e10dd6b396/subprojects/docs/build/reports/dead-internal-links.txt` from the web interface? I couldn't find it in the [tab "Artifacts" of TeamCity build](https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_BuildDistributions/69350402?buildTab=artifacts#%2Fdistributions), nor in [results of Build Scan®](https://ge.gradle.org/s/wbt4cxetf3sq6/failure#1). Or are such files only available on the TeamCity host (access to which I obviously don't have)?

**Comment by lkasso** [comment]
> Is there a way to get to the file `file:///home/tcagent1/agent/work/f63322e10dd6b396/subprojects/docs/build/reports/dead-internal-links.txt` from the web interface? I couldn't find it in the [tab "Artifacts" of TeamCity build](https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_BuildDistributions/69350402?buildTab=artifacts#%2Fdistributions), nor in [results of Build Scan®](https://ge.gradle.org/s/wbt4cxetf3sq6/failure#1). Or are such files only available on the TeamCity host (access to which I obviously don't have)?
No that file is only available locally. If I see an issue with ':docs:checkDeadInternalLinks', I always test it locally, fix and push.

**Comment by lkasso** [comment]
> From [TeamCity build log of the previous failure](https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_BuildDistributions/69350402?buildTab=overview&expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true#%2Fdistributions):
> 
> > Execution failed for task ':docs:checkDeadInternalLinks'. org.gradle.api.GradleException: Documentation assertion failed: found invalid internal links. See file:///home/tcagent1/agent/work/f63322e10dd6b396/subprojects/docs/build/reports/dead-internal-links.txt
> 
> Eventually, I figured out what the problem was by launching the task `:docs:checkDeadInternalLinks` locally and reading the code of `FindBrokenInternalLinks.java`. Maybe there is a faster way of deducing the issue?

When I have a dead link issue I don't look at that .txt file, the output of the task is typically enough to understand where the missing or broken link is. In this case:
Screenshot 2023-08-01 at 9 15 41 AM

`> Task :docs:checkDeadInternalLinks FAILED
ERROR: viewing_debugging_dependencies.adoc:28 Looking for section named sec:listing_project_dependencies in command_line_interface.adoc
    can be rendered using <<command_line_interface.adoc#sec:listing_project_dependencies, task `buildEnvironment`>>.
`
This tells me that in the `viewing_debugging_dependencies.adoc` there is a broken link for `command_line_interface.adoc` -> sec:listing_project_dependencies

**Comment by lkasso** [comment]
Thanks for fixing this @rybak, I will see about merging this now.

**Comment by rybak** [comment]
> This tells me that in viewing_debugging_dependencies.adoc there is a broken link for command_line_interface.adoc for the section listing_project_dependencies.

Yep. Only works for people who are familiar with this particular test, though ;-) The link doesn't look dead in browser. But reading the test report locally makes the distinction between implicit and explicit links clear.

> Thanks for fixing this @rybak, I will see about merging this now.

Thank you for review and for helping with the build failures. And for working on the Gradle documentation in general. :-)

**Pull request merged**
