### PR TITLE
Remove Distribution.baseName

### PR DESCRIPTION
**Pull request by donat**
### Summary
- Removed `org.gradle.api.distribution.Distribution.getBaseName()` and `org.gradle.api.distribution.Distribution.setBaseName()`
- Deincubated `org.gradle.api.distribution.Distribution.getDistributionBaseName()`

### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide/release notes
- [x] Check User Manual for dangling references and outdated documentation
- [ ] Check Incubation Report on TeamCity ([example](https://builds.gradle.org/viewLog.html?buildId=40024670&buildTypeId=Gradle_Check_SanityCheck&tab=report_project951_Incubating_APIs_Report)) 
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit?ts=5fcfefb8#gid=0).

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Review by jjohannes — APPROVED** [review]
:+1:

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM please

**Comment by donat** [comment]
@bot-gradle test this

**Pull request merged**
