### PR TITLE
Remove use of deprecated system property

### PR DESCRIPTION
**Pull request by big-guy**

### CODE REVIEW

**Comment by big-guy** [comment]
@eskatos I think this gets rid of these deprecations: https://ge.gradle.org/s/cs3fxn6u6n3uw/deprecations?expanded=WyI0Il0#91

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by monkey-mas** [comment]
Just wanted to know that the property should be removed in `v8.0.0`? [The doc you mentioned](https://ge.gradle.org/s/cs3fxn6u6n3uw/deprecations?expanded=WyI0Il0#91) says `This is scheduled to be removed in Gradle 9.0.`. So it seems like we'll drop it when `v9.0.0-M1` comes? WDYT?

**Review by eskatos — APPROVED** [review]
:+1:

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
> Just wanted to know that the property should be removed in `v8.0.0`? [The doc you mentioned](https://ge.gradle.org/s/cs3fxn6u6n3uw/deprecations?expanded=WyI0Il0#91) says `This is scheduled to be removed in Gradle 9.0.`. So it seems like we'll drop it when `v9.0.0-M1` comes? WDYT?

That's the deprecation message I'm trying to remove.  The default behavior is to act as if this flag is enabled, so we no longer need the flag explicitly set.

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
