### PR TITLE
upgraded Scala zinc compiler to version 1.2.5

### PR DESCRIPTION
**Pull request by pedjak**
### Context
This PR fixes https://github.com/gradle/gradle/issues/2158
* Uses the latest zinc compiler (1.2.5)
* Additionally introduces Scala compiler daemon that remains warm across build, improving further incremental compilation times

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ijuma** [comment]
Great contribution. :)

**Comment by jvican** [comment]
This is a great PR, thanks for the work @pedjak 
  
I'd argue against a raw integration with Zinc with the arguments I added in https://github.com/gradle/gradle/issues/2158, and instead propose that the same thing is achieved with Bloop's build server.
  
This will ensure, among other things described in the above ticket, that Gradle will work with Scala 3.0 as well as Scala 2.0 and all its supported runtimes.
  
An integration via Bloop is the recommended solution because there is likely to be a Zinc 2.0 version that will be breaking many parts of the API/design of the incremental compiler, with the purpose of improving it further. The BSP integration will make sure that no matter what internals are changed, Gradle users can still benefit from the best Scala experience.

**Comment by pedjak** [comment]
> An integration via Bloop is the recommended solution because there is likely to be a Zinc 2.0 version that will be breaking many parts of the API/design of the incremental compiler, with the purpose of improving it further. The BSP integration will make sure that no matter what internals are changed, Gradle users can still benefit from the best Scala experience.

@jvican, I see that more as mid/long-term goal here, in particular because of [this statement in the docs](https://scalacenter.github.io/bloop/docs/integration#build-server-protocol-bsp):

> At the moment, Bloop 1.2.5 partially implements version 2.0.0-M2 and Bloop v1.0.0 implements version 1.0.0

Also looking further at [the docs](https://scalacenter.github.io/bloop/docs/build-tools/overview#built-in-compile-test-and-run), no build tools (even sbt) provides "built-in compile" integration with Bloop. [bsp4j](https://github.com/scalacenter/bsp/tree/master/bsp4j) contains no examples or tests either, so it is very hard to understand how to use the server.

Good docs/examples are the key here. It took me a huge amount time to understand how the actual zinc api works. Reading the source code of Maven and InteliJ plugins was the only available doc, Zinc project was not of any help. 

This PR brings significant speed improvements over the currently used Zinc version and this is what at least developers in my organization desperately want. Integration with Bloop should start as "incubating", deprecating and removing the current one eventually.

BTW, would you like to say that BSP API is not going to change over the time?

**Comment by jvican** [comment]
> @jvican, I see that more as mid/long-term goal here, in particular because of [this statement in the docs](https://scalacenter.github.io/bloop/docs/integration#build-server-protocol-bsp):
  
1.2.6 will just bump up to a stable 2.0.0 BSP, which is 2.0.0-M2 with only a few amendments to some APIs. That version of BSP is being already battle-tested in our metals integration by a few thousand  Scala users.
  
It is true however this is not something immediate we can ship right now, but it's something we could ship during the next two months. I'm not sure what policy will gradle maintainers follow and when the next gradle release will happen (if it's to happen soon I would certainly encourage merging this temporarily), but if we can make the deadline I would recommend we try the bloop-based integration, which is where all Scala integrations are headed anyways).
  
That being said:

> Also looking further at [the docs](https://scalacenter.github.io/bloop/docs/build-tools/overview#built-in-compile-test-and-run), no build tools (even sbt) provides "built-in compile" integration with Bloop.
  
Metals and fury (a build tool) are using the built-in compile via BSP, so is IntelliJ. The idea is that we want to share the build server across all users so that the dev experience is the best.
    
> [bsp4j](https://github.com/scalacenter/bsp/tree/master/bsp4j) contains no examples or tests either, so it is very hard to understand how to use the server.
  
Tests are available in two different subdirectories of the same repo:
* https://github.com/scalacenter/bsp/tree/master/tests/src/test
* https://github.com/scalacenter/bsp/tree/master/testkit/src/main/scala/ch/epfl/scala/bsp/mock
  
There is a PR contributed by JetBrains to add property tests too: https://github.com/scalacenter/bsp/pull/84
https://github.com/scalacenter/bsp/tree/master/tests/src/test
  
> BTW, would you like to say that BSP API is not going to change over the time?
  
Sure, that's exactly one of the reasons why it's a protocol. There's extreme care in not breaking APIs and evolving the project in a backwards compatible way, just as LSP.

**Comment by pedjak** [comment]
> Metals and fury (a build tool) are using the built-in compile via BSP, so is IntelliJ. The idea is that we want to share the build server across all users so that the dev experience is the best. To give more context, I'm also right now implementing built-in compilation for sbt.

Do I understand correctly that InteliJ just supports [importing BSP project](https://scalacenter.github.io/bloop/docs/ides/intellij), but not "built-in compile", or [this table](https://scalacenter.github.io/bloop/docs/build-tools/overview) is not up-to-date?

And speaking about examples - we need some real-world things, even [BloopSuite](https://github.com/scalacenter/bsp/issues/61) is disabled at the moment.

**Comment by jvican** [comment]
> Do I understand correctly that InteliJ just supports [importing BSP project](https://scalacenter.github.io/bloop/docs/ides/intellij), but not "built-in compile", or [this table](https://scalacenter.github.io/bloop/docs/build-tools/overview) is not up-to-date?
  
The table you're looking for is https://scalacenter.github.io/bloop/docs/ides/overview IntelliJ supports compilation because it shows build diagnostics in the IDE. The other table is only for build tools.
  
> And speaking about examples - we need some real-world things, even [BloopSuite](https://github.com/scalacenter/bsp/issues/61) is disabled at the moment.
  
Plenty of real-world things in https://github.com/scalameta/metals and the scala-plugin in intellij. Tests of concrete clients are not enabled in the bsp repository on purpose.
  
--
  
On an unrelated note, @pedjak I'm not saying the bloop integration should be implemented by you -- it's totally fine you haven't looked at Bloop before, it's more or less a recent development anyway. I'm just pointing out I consider gradle to be an important client and would like to provide a more bullet-proof integration than having a custom zinc integration. This change will likely need direct help from the gradle team + me, as bloop author and zinc maintainer, so it's not something you should worry about.

I've been chatting with @oehme over the past months about how to approach this change. As I said before, it doesn't necessarily need to block this PR. I guess it will all depend on what are Gradle team's intentions.

**Comment by pedjak** [comment]
> On an unrelated note, @pedjak I'm not saying the bloop integration should be implemented by you -- it's totally fine you haven't looked at Bloop before, it's more or less a recent development anyway. I'm just pointing out I consider gradle to be an important client and would like to provide a more bullet-proof integration than having a custom zinc integration. This change will likely need direct help from the gradle team + me, as bloop author and zinc maintainer, so it's not something you should worry about.

Sure, I would not mind helping either :)

**Comment by yawaramin** [comment]
Hi @jvican maybe it would be better to file an issue for bloop integration and move this discussion there. Thanks.

**Comment by ijuma** [comment]
Would the bloop integration introduce a new daemon instead of reusing the Gradle daemon?

**Comment by jvican** [comment]
Yes, bloop is a build server shared by many clients. It can be used from IntelliJ, editors using Metals, in-house developer tools and any kind of build tool. The idea is that the build server outlives the lifetime of the clients. You can read more about it in https://scalacenter.github.io/bloop/ and, more concretely, https://scalacenter.github.io/bloop/docs/what-is-bloop

**Comment by deanwampler** [comment]
I know everyone is excited for Bloop, but I could use this PR right now in a project that builds with Gradle and Zinc, which I'm trying to upgrade to Scala 2.12. Any good reason not to merge the PR?

**Comment by moonkev** [comment]
Hi, curious if this is slotted for 6.0?   We would like to upgrade to 2.12 and as @deanwampler mentioned, could really use this PR for now while the direction to use bloop is being hashed out.  It looks like @pedjak put in a decent amount of work in this too, so would be good for it to be brought to fruition.

**Comment by melix** [comment]
Thanks a lot for your PR @pedjak . I have spent some time today reviewing, as well as fixing some left-over tests. We're still not in a position to be able to merge, for different reasons:

- this implicitly mandates users to use Zinc compiler 1.2.0+
- this effectively removes support for Scala 2.9
- there are lots of tests failing with "unable to delete file" under Windows, which indicates that at least a file handle is leaking

For the breaking chances (Zinc 1.2, Scala 2.9) I've added documentation, and we have to decide whether it's fine to ship in 5.5 or we should wait 6.0. Currently we're leaning towards 5.5 given the bugfixes and improved performance, but it may be a problem for some users.

Progress can be followed on [this branch, based on your PR](https://github.com/gradle/gradle/tree/cc/fixit/scala-plugin-zinc-update).

**Comment by pedjak** [comment]
Thanks @melix for taking this. If I can help any further with the tests, do let me know. I do not have any Windows instance where I could try them.

Zinc 1.x in general removed the support for Scala 2.9, so I am not sure how many users are really affected.

This PR introduces Zinc 1.2.5 as the default, but I do think that the older 1.x versions have the compatible API, so users can change the default version by declaring the requested version in `zinc` configuration as before. Perhaps we can add a few tests verifying that we can use 1.0.x and 1.1.x versions?

**Comment by melix** [comment]
I have checked with 1.0.x and 1.1.x and it breaks, the API is different.

**Comment by klass-ivan** [comment]
I got an error when disabling incremental compilation by force = true
`Process 'command '/home/klass/.sdkman/candidates/java/8.0.191-oracle/bin/java'' finished with non-zero exit value 1`
```
    tasks.withType(ScalaCompile) {
        scalaCompileOptions.with {
            force = System.getenv('FORCE_COMPILE') == '1'
        }
    }
```
this env flag was working before

**Comment by moonkev** [comment]
Hi @melix - just wondering if this is still slated for at the very least 6.0?  I ask because many popular scala libraries maintainers are looking to discontinue published builds for anything lower than 2.12, basically leaving gradle+scala users unable to upgrade to new versions of dependencies.  One in particular being akka - of course one of the most (if not the most) popular library in the scala world.

**Comment by melix** [comment]
I didn't have time to continue on this, but I agree it would be good to target 6.0.

**Comment by wolfs** [comment]
Here is an updated PR based on @melix's changes: https://github.com/gradle/gradle/pull/9573

**Comment by deanwampler** [comment]
That's great!

**Pull request merged**
