### PR TITLE
Simplify and de-tangle code showing the console on all log level

### PR DESCRIPTION
**Pull request by lacasseio**
### Context
Address comment on merged PR gradle/gradle#1925.

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and [CI build status](https://builds.gradle.org/project.html?projectId=Gradle_Branches_Checkpoints&branch_Gradle_Branches_Checkpoints=dl-fix-filtering)
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eriwen** [comment]
@lacasseio I'm sorry we never followed up on this. I don't think we need MaxLogLevelChangeEvent and a few other things have changed. Can we reconsider this cleanup when you return?

**Comment by bmuschko** [comment]
@lacasseio Is this still something we'll want to do?

**Comment by lacasseio** [comment]
Yeah, I think you are right that the refactoring is required according to feedback received from Adam. The only part I would remove is the serializer for max worker count as this is now grown as we get more worker event. Basically, instead of filtering for progress events, we are simply setting the log level to null which passes through from the daemon to the client. Then we filter the events created from the progress events with the right log level.

**Comment by eriwen** [comment]
Closing as superceded

**Pull request closed without merging**
