### PR TITLE
Block the browser when a Play application reloads in the middle of a rebuild

### PR DESCRIPTION
**Pull request by big-guy**

### CODE REVIEW

**Comment by benmccann** [comment]
Hi @big-guy. I'm a committer to Play. For Play 2.6, I've removed the SBT dependency from Play's reloader package, so that you can use it in Gradle. I'd love to help make Play + Gradle better, but don't really know Gradle at all. I'd be more than happy to make any changes on the Play side that would help make integration with Gradle smoother. E.g. right now the Play Reloader has only a Scala interface. I'm not sure if you'll have any difficulty calling it. If it's something that would be really helpful, I could add a Java wrapper. If someone on the Gradle side could make an attempt at integrating the Play reloader I'll happily assist with advice and any code changes necessary from the Play side. Play 2.6 release is coming up, so this would be a good time to get any such changes in. Otherwise our next change will be Play 3.0 and we may have to wait over a year.

**Comment by big-guy** [comment]
Hey @benmccann 

Thanks!

I've looked at the [source for run-support](https://github.com/playframework/playframework/tree/master/framework/src/run-support) in Play and the `Reloader` class in particular. One of the challenges is that Gradle handles file watching as a generic feature, so we don't need that part of the `Reloader`. The relationship between the build and the application is also inverted.  The `Reloader`drives when the build should be performed, but the Gradle-Play reload works the other way around.

We implement `BuildLink` here:
https://github.com/gradle/gradle/blob/f24146cc5f956a1b03a515bbee4225e6f861b6ab/subprojects/platform-play/src/main/java/org/gradle/play/internal/run/DefaultVersionedPlayRunAdapter.java#L72-L101

This is wired in by having the Gradle `PlayRun` task register a "deployment", which is a process that can live across builds.  The code from above runs in the Play application JVM and we notify it when a build has started/failed/succeeded.  So there's currently not a way to say "build now" from the Play application. 

Is there any other magic that the run-support library does that we could use?

**Comment by benmccann** [comment]
I actually haven't played with the Gradle Play support at all. Does Gradle support hot reloading of Java classes in Play already? I was sort of under the impression that it didn't yet, but it sounds like maybe you do?

The `Reloader` takes a `FileWatchService`, which calls a callback when a file has changed. Play uses it's own implementation for this, but Gradle could provide its own implementation using its own file watching by implementing the interface, which just has one method.

Yes, in Play, the build is performed when you load the app in your browser and so the app+reloader kick off the build. [Lagom](https://github.com/lagom/lagom) actually has the build kick it off without waiting for a request (which is what it sounds like Gradle does as well). Lagom basically uses a copy/pasted version of Play's `Reloader` with a few minor modifications. I've been trying to combine them into one for Play 2.6, so Play's `Reloader` actually now supports both methods. [We had some discussion of the pros/cons of each method on the Play mailing list](https://groups.google.com/d/msg/play-framework-dev/Qxr9Obzg7zw/RCLEIxSkGAAJ).

If Gradle already supports the hot reloading then I don't think you'd get any new functionality.

**Comment by big-guy** [comment]
Makes sense, thanks @benmccann.

The behavior with this PR is close to what Rich says:

> My personal ideal would be something more complicated that gives me the latest version of the code with minimal waiting.
> - eager compile when changes detected
> - on page reload, if build in progress, either wait for it if it is compiling the latest code or interrupt it and compile again if have been more changes since it started compiling (I get annoyed waiting for an out-of-date build to complete)

When Gradle detects a change, it waits for a quiet period and then starts building. If the build fails, we pass that along to Gradle's `BuildLink` implementation to provide on the next reload. If the build succeeds, we set a flag so that on the next reload we swap out the classloaders. 

While the build is in progress and a reload is requested, we block the reload until the build completes.  This is what the PR adds.

The one issue we have remaining, so I think this is only partially fixed, is if you have multiple changes. We could have a build in progress that's been invalidated by additional changes. I need to spend a little more time to fix this.

**Pull request merged**
