### PR TITLE
[Backport] Use compiler API data for incremental compilation after failure

### LINKED ISSUE #23922: Backport "Use Compiler API data for incremental compilation after a failure" to 7.x
For Gradle 8.1 we improved incremental compilation after failure compared to previous implementation. We should backport that to 7.x.

- [x] #23119 – https://github.com/gradle/gradle/pull/23913
- [x] #23251 – https://github.com/gradle/gradle/pull/23913
- [ ] #23226

### PR DESCRIPTION
**Pull request by asodja**
Backport of #22608, #23226, #23661 and #24880

Fixes #23922

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean test this

**Comment by asodja** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
