### PR TITLE
Upgrade embedded Kotlin to 2.0.21

### PR DESCRIPTION
**Pull request by eskatos**
See https://github.com/JetBrains/kotlin/releases/tag/v2.0.21

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AFT APT

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle RFN APT

**Comment by eskatos** [comment]
@bot-gradle tes RFN APT

**Review by jbartok — APPROVED** [review]

**Pull request merged**
