### PR TITLE
Update GE Gradle plugin to 3.11.3

### PR DESCRIPTION
**Pull request by pshevche**
Update Gradle Enterprise Gradle plugin to 3.11.3

### CODE REVIEW

**Comment by pshevche** [comment]
@bot-gradle test this

**Comment by pshevche** [comment]
@bot-gradle test and merge

**Comment by pshevche** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@pshevche Did you see the error? 

```
Caused by: java.lang.NoSuchMethodError: org.gradle.internal.enterprise.GradleEnterprisePluginRequiredServices.getBackgroundJobExecutors()Lorg/gradle/internal/enterprise/GradleEnterprisePluginBackgroundJobExecutors;
	at com.gradle.scan.plugin.internal.p.c$2.c(SourceFile:82)
	at com.gradle.scan.plugin.internal.p.m.a(SourceFile:213)
	at com.gradle.scan.plugin.internal.p.m.a(SourceFile:117)
	at com.gradle.scan.plugin.internal.p.c.create(SourceFile:35)
	at org.gradle.internal.enterprise.impl.DefaultGradleEnterprisePluginAdapter.createPluginService(DefaultGradleEnterprisePluginAdapter.java:95)
	at org.gradle.internal.enterprise.impl.DefaultGradleEnterprisePluginAdapter.register(DefaultGradleEnterprisePluginAdapter.java:60)
	at org.gradle.internal.enterprise.impl.DefautGradleEnterprisePluginCheckInService.checkIn(DefautGradleEnterprisePluginCheckInService.java:61)
	at com.gradle.scan.plugin.internal.d.d.a(SourceFile:21)
	at com.gradle.scan.plugin.internal.d.a.a(SourceFile:20)
	at com.gradle.scan.plugin.internal.d.a(SourceFile:167)
	at com.gradle.scan.plugin.internal.d.a(SourceFile:112)
	at com.gradle.enterprise.gradleplugin.GradleEnterprisePlugin.a(SourceFile:59)
	at com.gradle.enterprise.gradleplugin.GradleEnterprisePlugin.apply(SourceFile:32)
```

**Comment by pshevche** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@pshevche PullRequestFeedback doesn't contain performance test.

@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle test PT

**Comment by pshevche** [comment]
> @pshevche PullRequestFeedback doesn't contain performance test.
> 
> @bot-gradle help

@blindpirate , I know. Wanted to just take it step at a time. Thank you for pointing other options out

**Comment by pshevche** [comment]
@bot-gradle test and merge

**Comment by pshevche** [comment]
@bot-gradle test and merge

**Pull request merged**
