### PR TITLE
GRADLE-3250 Add NTLM test to prepare support of SNI.

### PR DESCRIPTION
**Pull request by kenji21**
This test check that the 3 messages exchange is OK when using NTLM
authentication.

### CODE REVIEW

**Comment by alkemist** [comment]
@kenji21 I haven't reviewed this code (I expect @bigdaz will relatively soon when he is back from vacation). 

In the meantime though, would you mind [signing the CLA](http://gradle.org/contribute)?

**Comment by alkemist** [comment]
@hansd do you know what the legal implication here is of @kenji21 explicitly declaring that this is public domain and therefore no CLA being required?  Does this meet our legal obligations?

@kenji21 thanks for the contribution. It may take a little bit of time to resolve this CLA issue. The implementation looks good to me, but we'll take a deeper look once the CLA issue is resolved.

**Comment by hansd** [comment]
On Thu, Apr 30, 2015 at 7:36 PM, Luke Daley <notifications@github.com>
wrote:

> @hansd <https://github.com/hansd> do you know what the legal implication
> here is of @kenji21 <https://github.com/kenji21> explicitly declaring
> that this is public domain and therefore no CLA being required? Does this
> meet our legal obligations?
>
We need a CLA. It protects the Gradle community. We need the guarantees
that the code is owned by the contributor (not by the company he might be
working for) and that it is free from copyright issues. We use a similar
CLA like Apache does which is also mandatory for all Apache projects. We
can't accept a contribution without a CLA. It could be a ticking legal time
bomb.

@kenji21: What is your objection with our CLA?

**Comment by kenji21** [comment]
No objection over the CLA, I've done these PR afterwork => individual just signed :-)

**Comment by alkemist** [comment]
Thanks @kenji21 !

**Comment by airborn** [comment]
Do you have any updates on when this could be merged?

**Comment by kenji21** [comment]
As stated in the dev list : https://groups.google.com/forum/#!topic/gradle-dev/RxmS3j2aD8w

Got a failing test after updating to http 4.4.1, it becomes "only testable" on windows, but I have no windows machine available to go further.

**Comment by bigdaz** [comment]
Hey @kenji21. Thanks again for the work you put into this. It's on my list to take a look at.

**Comment by kenji21** [comment]
Did you look at the "test for windows only issue" I got while updating as I said on the dev list ? @bigdaz

**Comment by bigdaz** [comment]
Hi @kenji21. We really appreciate the work put into this pull request.

The Gradle team doesn't currently have the capacity to deal with all of the bugs, feature requests, great ideas and pull requests that we receive. We already have a pretty big backlog, so it might take some time for us to take a look at this.

Pull requests are interesting because they may seem like they come for "free". Our experience has shown that in order to maintain the level of quality and consistency that Gradle users expect, we need to invest significant engineering effort in all but the most trivial PRs. 

We are [actively recruiting](http://grnh.se/mbne6o) to increase our engineering team, so hopefully this is a temporary situation. We ask for patience in the meantime.

**Comment by kenji21** [comment]
In fact, I can't send a PR because updating HTTPClient to 4.4 make it rely on native access for NTLM Auth :

java.lang.UnsatisfiedLinkError: Unable to load library 'Secur32': dlopen(libSecur32.dylib, 9): image not found

And I have no idea how to make this test "only windows", maybe it has already happened for other tests ?

**Comment by mark-vieira** [comment]
@kenji21, do you mind rebasing on master? Looks like there have been some changes that causes compilation to fail.

https://builds.gradle.org/viewLog.html?buildId=487292&tab=buildResultsDiv&buildTypeId=Gradle_PullRequest_LinuxJava17withSanityChec

**Comment by kenji21** [comment]
sure, my PR was on gradle branch REL-2.2.1... maybe there will be some work

**Comment by kenji21** [comment]
Ok, updated this PR from master. This first one adds a tests to show that NTLM auth is OK.
Now, have to update the patch provided at https://groups.google.com/forum/#!topic/gradle-dev/RxmS3j2aD8w to update to HttpClient  4.4.1

**Comment by mark-vieira** [comment]
Thanks @kenji21. I am looking to get this pulled in the next release once we get Gradle 2.10 out the door.

**Comment by kenji21** [comment]
Ok, so I can add a second commit to this that adds HttpClient update (and make the added test still pass) ?

**Comment by mark-vieira** [comment]
That should be a separate pull request.

**Comment by kenji21** [comment]
Ok, so I should create another branch (issue-3250-phase2 ?), and name the PR "GRADLE-3250 Update HttpClient to 4.4.1"

**Comment by mark-vieira** [comment]
@kenji21 sounds like a good plan.

**Comment by kenji21** [comment]
nice. 18 tests are failing after moving to HttpClient 4.4.1 (and having made some changes, and many deprecation removals)

**Comment by mark-vieira** [comment]
@kenji21 There are a number of things that need to be addressed here. Mainly, we want to be able to test NTLM authentication in a more general way, similarly to how we currently do for BASIC and DIGEST auth schemes rather than simply add a single NTLM test.

1. We'll want to add a new [`AuthScheme`](https://github.com/gradle/gradle/blob/master/subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpServer.groovy#L61-L61) to the `HttpServer` test fixture for NTLM.
2. This will likely mean implementing (or finding an existing implementation for) a Jetty `Authenticator` for NTLM.
3. Implementation should be as real as possible. The code in this PR doesn't look at the Type3Message LanManager or NT responses. This means the password being sent isn't checked at all, only the username.
4. Rather than adding a new integration test we should augment existing ones that use authentication to additionally test NTLM auth. You should be able to search for uses of `HttpServer.AuthScheme`. Note that NTLM auth should only be used in cases where an `authentication { }` block is *not* explicitly configured.

**Comment by mark-vieira** [comment]
@kenji21, is this something you think you'll have time for, or feel comfortable doing. In fact, preferably we'd have coverage for SPNEGO as Kerberos falls under this umbrella as well. Let me know if you won't be able to take this on.

**Comment by mark-vieira** [comment]
@kenji21, I've gone ahead and merged this pull request. I'll take care of the issues I've listed above post-merge. Thanks for the contribution. As for PR #546 we've decided to take that on as a priority in house so it's been closed.

**Comment by kenji21** [comment]
Nice, thank you for help.

**Pull request merged**
