### PR TITLE
GRADLE-2784 - Using a specific snapshot version of an artifact:

### PR DESCRIPTION
**Pull request by noamt**
Added another step during the resolution process to check if the given dependency declaration requests a specific unique Maven snapshot version; in such a case we extract the timestamp, create a new module component identifier to reflect resolution of a snapshot and continue on to the normal snapshot resolution process.

Test cases added: Resolve a unique snapshot from a file or HTTP repository, try to resolve an inexisting unique snapshot, declare dependencies on both unique and non-unique snapshots

### CODE REVIEW

**Comment by cbeams** [comment]
Nice @noamt! I haven't reviewed the PR, but in any case I hope the functionality makes its way in—I could really use it at the moment.

**Comment by noamt** [comment]
I've compiled a version from source and it seems to do the trick

**Comment by cbeams** [comment]
Ping :) @alkemist, @pniederw, any comment on this making it into the next Gradle release? Thanks.

**Comment by noamt** [comment]
I would also very much like to see this in the next release, so if there's anything else I can do to help out

**Comment by bigdaz** [comment]
Thanks for the contribution, @noamt. We're currently planning what will be in Gradle 2.4.

Please be aware that merging, reviewing and polishing pull requests takes a lot of time. And we have a backlog of open PRs to get through. So there's a good chance that this one won't make the cut for Gradle 2.4. We'll be in touch with any review feedback.

**Comment by cbeams** [comment]
Thanks for the update Daz.

**Comment by noamt** [comment]
Thanks Daz, looking forward to any further update.

**Comment by medvedev84** [comment]
Hi, guys. I got the same issue with downloading exact shanpshot from nexus. I updated my gradle to 2.5, but still can not download the exact snapshot. I'm sure you have tested it properly before release, but may be there is some regress for this feature in newer version?

**Comment by bigdaz** [comment]
@medvedev84 Please raise this issue on discuss.gradle.org, with a bit more detail about exactly what you're trying to do and what's not working.

**Comment by dankirkd** [comment]
What is the holdup on this PR?

**Comment by hrstoyanov** [comment]
So how does this work??? where is this fix explained , some sample code please?

**Comment by bigdaz** [comment]
https://docs.gradle.org/2.4/release-notes#depending-on-a-particular-maven-snapshot-version

**Comment by tekumara** [comment]
Thanks @bigdaz the instructions in your link worked!

**Comment by Kas-tle** [comment]
This does not seem to work when a repository is explicitly set as `snapshotsOnly()`. Is this intended?

**Pull request merged**
