### PR TITLE
Use working directory of same length for performance tests

### PR DESCRIPTION
**Pull request by wolfs**
To rule out the influence of the length of paths on performance tests.

### CODE REVIEW

**Comment by oehme** [comment]
Nice! Could you also rebaseline the failing test? I'll look into what's going on there.

**Comment by wolfs** [comment]
@oehme I merged master and ran the performance suite again: https://builds.gradle.org/viewLog.html?buildId=9989318&buildTypeId=Gradle_Check_PerformanceTestCoordinator&tab=buildResultsDiv
As I consequence, I [rebased the performance tests](https://github.com/gradle/gradle/pull/3827/commits/15676f1b8a614557f73378139096e43f76e3358e) which I think have regressed already. Do you agree with my analysis?

**Comment by wolfs** [comment]
Note that some performance tests show quite some improvements (e.g. get IDE model for...), we should probably lock those in.

**Comment by oehme** [comment]
Let's merge this and I'll rebaseline everything afterwards/look into potential regressions.

**Pull request merged**
