### PR TITLE
Patch Groovy interoperability in Kotlin DSL for GroovyObject method calls in withGroovyBuilder

### LINKED ISSUE #16297: Groovy3: Investigate init script issues
* Use a recent Gradle version with Groovy 3 upgrade
* Use the following init script
* Expected: works
* Actual: error

```
* Exception is:
org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at Init_gradle.configureExtension(init.gradle.kts:40)
        at Init_gradle$1.execute(init.gradle.kts:28)
        at Init_gradle$1.execute(init.gradle.kts:4)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:95)
```

```
import com.gradle.enterprise.gradleplugin.GradleEnterprisePlugin
import com.gradle.scan.plugin.BuildScanPlugin
import org.gradle.util.GradleVersion
import org.gradle.api.Project
initscript {
    val pluginVersion = "3.4.1"
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.gradle:gradle-enterprise-gradle-plugin:${pluginVersion}")
    }
}
val isTopLevelBuild = gradle.getParent() == null
if (isTopLevelBuild) {
    val gradleVersion = GradleVersion.current().baseVersion
    val atLeastGradle5 = gradleVersion >= GradleVersion.version("5.0")
    val atLeastGradle6 = gradleVersion >= GradleVersion.version("6.0")
    if (atLeastGradle6) {
         settingsEvaluated {
            if (!pluginManager.hasPlugin("com.gradle.enterprise")) {
                pluginManager.apply(GradleEnterprisePlugin::class)
            }
            configureExtension(extensions["gradleEnterprise"], rootProject.name)
        }
    } else if (atLeastGradle5) {
        rootProject {
            pluginManager.apply(BuildScanPlugin::class)
            configureExtension(extensions["gradleEnterprise"], name)
        }
    }
}
fun configureExtension(extension: Any, projectName: String) {
    extension.withGroovyBuilder {
        if (getProperty("server") == null) {
            setProperty("server", "https://e.grdev.net")
        }
        
        getProperty("buildScan").withGroovyBuilder {
            "publishAlways"()
        }
    }
}
```

### PR DESCRIPTION
**Pull request by donat**
Fixes #16297

In Groovy 3, the `getProperty/setProperty/...` methods on the `GroovyObject` interface were converted to default methods. `GroovyBuilderScopeForGroovyObject` implements the `GroovyOject` interface by delegating to a `GroovyObject` instance. Because of the default methods, the delegation breaks the methods are invoked on `GroovyBuilderScopeForGroovyObject` which breaks the functionality.

The solution is to drop the delegation and invoke the `GroovyObject` methods explicitly in `GroovyBuilderScopeForGroovyObject`.

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Review by bmuskalla — APPROVED** [review]
Nice! Thanks for looking into this. Seems ktlint is unhappy :/

**Comment by donat** [comment]
Yep, I've just fixed it.

**Comment by donat** [comment]
@bot-gradle test rFM

**Pull request merged**
