### PR TITLE
Expose wrapped original ProcessingEnvironment

### PR DESCRIPTION
**Pull request by stephanenicolas**
@oehme @melix  In order for Butterknife to become incremental, we need this method. 
The problem is that Butterknife uses `com.sun.source.util.Trees` (a current limitation of incap). The boostrap method for Trees requires the original processing environment, an instance of com.sun.tools.javac.processing.JavacProcessingEnvironment.
See https://www.zgrepcode.com/java/openjdk/10.0.2/jdk.compiler/com/sun/source/util/trees.java line 76.

I tried to hack the call to the underlying method in Trees (getJavacTrees) and pass it hacky parameters, but it didn't work.

What worked though was to access the wrapped processing enviroment (via reflection) and pass it to `Trees.getInstance()`. ButterKnife then works like a charm. 

note: I didn't apply a standard getter name because I don't think it would have been very clear. Of course, feel free to fix it.
note2: I already contributed to gradle and already passed the DCO. I am doing this PR quickly on the web.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
What is the benefit of this getter? You'll have to use reflection anyway, so why not access the field?

**Comment by stephanenicolas** [comment]
@oehme No, I don't need reflection with this getter. Here is an example:
https://github.com/stephanenicolas/butterknife/blob/sni/version-10-incap/butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java#L155

We can simply use the wrapped processing environment to call `Trees.instance`. 
Or maybe I miss something and you're saying the class itself will need to be accessed by reflection ??

**Comment by oehme** [comment]
Sorry I still don't understand. What difference does it make whether you're calling a field or a getter with reflection?

And no we can't remove that warning, since generally it is unsafe to access trees, as it breaks the whole incremental processing contract. You are not supposed to depend on method bodies, unless it's a body inside the annotated class itself. Othwerwise there is no guarantee you're gonna be called again, because Gradle ignores method body changes on dependent classes (like an incremental compiler should)

**Comment by stephanenicolas** [comment]
@oehme I didn't know the class was not visible, I understand what you mean now. Could it be published with its new setter ? That would at least solve this part of the problem.

Why are you talking about method bodies ? I didn't get it. Is it the way BK is using Trees internally you mean ? I didn't check what it's used for yet.

**Comment by oehme** [comment]
I said "generally". It's great if the specific case of BK works, but you asked if we can remove the warning and the answer to that is: No we can't.

Relying on the details of IncrementalProcessingEnvironment and extracting the delegate is generally unsafe and I'd rather have that be explicit by not making it public. If you really know what you're doing, you can already get it with reflection on the field.

**Comment by stephanenicolas** [comment]
I have fixed my fork of BK. But there is something I don't understand @oehme : It looks like this PR is not needed at all indeed with gradle 4.10.3. Whether or not the compilation is incremental, I always receive the original processing environment now in my APs (and by the task duration time I can clearly tell that the compilation is incremental). I am pretty sure though that, maybe with a previous gradle version like 4.9, the class I changed in the PR class was passed only in incremental compilation.

Do you mind to tell me if anything has changed between 4.9 and 4.10.3 at this regard ? Is the original processing environment from javac supposed to be passed directly to APs even in the case of an incremental compilation ? I am just trying to make sure I got it right.

**Comment by oehme** [comment]
We always decorate the environment, no matter if the compilation is incremental or not. You'll never get the original environment in your `init` method.

**Comment by Alonexx** [comment]
This change is not compatible with kapt, since `Trees` via reflection became invalid again. https://github.com/JetBrains/kotlin/blob/master/plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/incremental/incrementalProcessors.kt

**Comment by bingranl** [comment]
Will changing the private field name to `delegate` solve the incompatible issue? https://github.com/JetBrains/kotlin/blob/master/plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/incremental/incrementalProcessors.kt#L63

**Comment by Alonexx** [comment]
> Will changing the private field name to `delegate` solve the incompatible issue? https://github.com/JetBrains/kotlin/blob/master/plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/incremental/incrementalProcessors.kt#L63

Sure!

**Pull request closed without merging**
