### PR TITLE
Fix some inconsistencies between Ant and Zinc scala compilers

### PR DESCRIPTION
**Pull request by maiflai**
Hi,

`scalaCompileOptions.force` currently appears to have no effect for the Zinc compiler. This PR tries to implement a clean compilation mode for both Ant and Zinc compilers when `force` is set to true.

Also, the Ant compiler currently requires the client to handle whitespace in any arguments, yet the Zinc compiler requires that the client does not handle whitespace escaping. This PR therefore tries to handle any unescaped whitespace when the Ant compiler is used and standardises the behaviour to match the Zinc compiler.

### CODE REVIEW

**Comment by bigdaz** [comment]
Thanks very much for the pull request. While we're keen to deprecate and eventually remove the ant-backed Scala compiler, until then it would be good for them to have consistent behaviour.

I've made a few comments on the changes. If you're able to take this a bit further, that will assist with getting it merged.

Thanks again, Daz

**Comment by maiflai** [comment]
Thanks - re: backwards compatibility, several of the tests assert that if the argument is already quoted, then it should be passed through directly. It checks single and double quotes.

I'll check to see if the ScalaDocs task uses the same core scala CommandLineParser.

**Comment by eljobe** [comment]
@maiflai: Thanks for making the Ant Compiler more consistent with the Zinc Compiler. You're a peach!

**Comment by maiflai** [comment]
No worries, thanks for merging it.

**Pull request merged**
