### PR TITLE
#1285 - fixing EOL to be platform specific

### PR DESCRIPTION
**Pull request by fejese**
Fix for #1285 

Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [ ] Before submitting a pull request, I started a discussion on the [Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev),
      the [forum](https://discuss.gradle.org/) or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I considered writing a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [x] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on my local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for providing the pull request. Before we can accept the change we'd like to see an integration test that verifies the correct behavior on Linux and Windows. Could you please provide one?

**Comment by fejese** [comment]
@bmuschko , of course, makes sense. One question though: do you run the tests both on windows and linux (so I could make use of {{%s}} in one test) or do you have a usual way of injecting system properties in tests (I guess by setting the {{line.separator}} system property would be the most correct way of testing this)?

**Comment by eriwen** [comment]
@fejese Yes, we run tests on Windows and Linux. You should be able to find other integration test examples with properties set in the code base. Let us know if you have troubles.

**Comment by fejese** [comment]
@eriwen Thanks for the help. I've looked an it seems that setting the system property for the test is not working as this property is cached already in ``System.lineSeparator()``. So I've updated the test to always check for platform specific line ending. What do you think? The PR is rebased and updated.

**Comment by lacasseio** [comment]
Thanks @fejese for this issue. Thanks to your sharp laser eye, we can use this PR to fix issue https://github.com/gradle/gradle/issues/1546 introduced by the new console. I will see to merge this before 3.5 RC1

**Comment by lacasseio** [comment]
I rebased this PR on `release` and manually merge the PR. I will close this.

**Pull request closed without merging**
