### PR TITLE
Add example and mention of CopySpec and Working with Files

### LINKED ISSUE #29310: Working with Files - CopySpec - should be linked to on the Distribution Plugin doc page
### Issue type

Wrong or misleading information

### Problem description

Often folks don't know how to customize their distribution.  It often involves copying files and moving them around first, and then assembling the distribution.

We currently don't make this easy to discover from the Distribution Plugin doc page.  Specifically, we should mention it here:  https://docs.gradle.org/current/userguide/distribution_plugin.html#sec:distribution_contents

### Context (optional)

I've had many folks ping me and tell me THANKS for writing up an example.  Such as https://stackoverflow.com/questions/25951047/how-to-cherry-pick-zip-contents-with-gradle-distribution-plugin/35929148#35929148
We might also give my example within that answer additionally, and point folks to the "Working With Files" doc for further customization needs.

I'd be happy to improve the Distribution Plugin doc page with a PR, if consensus can be had on what/how we want to say the above.

My suggestion to add after current existing Example 3. :
-----------------
### Example 4. Working With Files using CopySpec

```groovy

distributions {
    main {
        baseName= 'myArchive'
        contents {
            into('bin/config') {
                from 'config'
            }
            into('lib/samples') {
                from 'samples'
            }
        }
    }
}
```

In the example above, the `bin/config` directory is created if not already existing, and the contents of `config` directory are copied into it. Similiarly for the `lib/samples` directory.

For details on using [CopySpec](https://docs.gradle.org/current/userguide/working_with_files.html#sec:copying_files) or working with files generally, please consult our userguide [Working With Files ](https://docs.gradle.org/current/userguide/working_with_files.html)

---------------------

Above Looks good?

### Page with the problem

https://docs.gradle.org/current/userguide/distribution_plugin.html#sec:distribution_contents

### PR DESCRIPTION
**Pull request by thadguidry**
Fixes #29310 

- I strongly preferred to keep the example simple as described in the issue and not link to existing samples.
- although someone could improve this with a sample.  I just didn't understand the samples hierarchy! Sorry!

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by tresat** [comment]
@thadguidry - Thanks for the PR!

This seems like a useful improvement to me, but I'll let our technical writer have the final say on this.  I've added @lkasso as a reviewer.

One thing that does need to change before this can be accepted, however, is to convert the inline example code into a runnable snippet.  This will ensure that the code remains tested and correct, and that it doesn't go out of date as changes are made to Gradle and these APIs.

It's not very difficult to do this:

Under `platforms/documentation/docs/src/snipets/files` there is an existing [copy example ](https://github.com/gradle/gradle/tree/master/platforms/documentation/docs/src/snippets/files/copy)snippet.  You can use this as a template for writing a snippet and add your new `copySpec` example as a sibling directory to it.  Instead of just calling `tasks` in the `*.sample.conf` file, be sure to call your task that demonstrates this usage.

If you add the snippet at that location, you can test run it with the command: `gradlew :docs:docsTest --tests "*snippet-files-copy-spec*"` to make sure it is correct.  Thanks again!

**Comment by thadguidry** [comment]
> You can use this as a template for writing a snippet and add your new copySpec example as a sibling directory to it.

Sibling directory?  Can you explain a bit about the hierarchy your proposing?
I found the [docs for contributing about snippets](https://github.com/gradle/gradle/blob/master/platforms/documentation/docs/README.md#code-snippets), but not sure what you mean with "sibling directory", a subdirectory under `/workspaces/gradle/platforms/documentation/docs/src/snippets/files/copy` to be called ...what `copySpec` ?

**Comment by lkasso** [comment]
@bot-gradle test BD

**Comment by thadguidry** [comment]
@lkasso Thank you !

**Comment by lkasso** [comment]
@bot-gradle test BD

**Review by lkasso — APPROVED** [review]

**Comment by lkasso** [comment]
@bot-gradle clean

**Pull request merged**
