### PR TITLE
Update Gradle Enterprise Gradle plugin to v3.14

### PR DESCRIPTION
**Pull request by wolfs**
Cherry pick of https://github.com/gradle/gradle/pull/25819 to 8.3 RC2.

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Review by facewindu — APPROVED** [review]

**Review by hegyibalint — APPROVED** [review]
LGTM 🎉

**Review by ljacomet — APPROVED** [review]

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Review by lkasso — APPROVED** [review]

**Pull request merged**
