### PR TITLE
Let `AbstractSmokeTest` detect more deprecation warnings

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by lptr** [comment]
Good idea!

**Comment by bamboo** [comment]
@bot-gradle test this

**Review by donat — APPROVED** [review]
LGTM.
Fyi, I've rebased the PR to the latest master.

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
Thanks, @donat! Great to see this merged!

**Pull request merged**
