### PR TITLE
Do not remove duplicate test framework jars

### PR DESCRIPTION
**Pull request by jvandort**
Matching jars based on file name is fragile and does not work in several situations. Instead, we just accept that sometimes we will get multiple versions of a test framework jar on the test classpath at once

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
