### PR TITLE
Update tested AGP version

### PR DESCRIPTION
**Pull request by eskatos**
from 8.1.0-alpha03 to 8.1.0-alpha04

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AST, APT, AFT

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
