### PR TITLE
Removed unnecessary exclusive locking while creating Zinc compiler

### PR DESCRIPTION
**Pull request by fkorotkov**
# Context

We experienced issues in CI while upgrading from Gradle 2.9 to 2.14. Here is our CI setup:
- ./gradlew --no-daemon <list of projects> is executed
- We have `daemon`, `parallel` and `configureondemand` flags enabled
- The build is executed on a c3.8xlarge AWS instance(32 cores)
- We end up with 4 different versions of Scala we need to populate cache for
- Most of our Scala projects are leaf projects that they should appear first in the compilation order

We are getting *"Timeout waiting to lock Zinc compiler cache"* errors.

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':some:project:compileScala'.
> Could not open Zinc compiler cache (/tmp/.gradle/caches/2.14/zinc).
   > Timeout waiting to lock Zinc compiler cache (/tmp/.gradle/caches/2.14/zinc). It is currently in use by another Gradle instance.
     Owner PID: 4117
     Our PID: 1112
     Owner Operation: 
     Our operation: 
     Lock file: /tmp/.gradle/caches/2.14/zinc/cache.properties.lock

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':some:project:compileScala'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.cache.CacheOpenException: Could not open Zinc compiler cache (/tmp/.gradle/caches/2.14/zinc).
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:48)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:28)
	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:80)
	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:50)
	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.doOpen(DefaultCacheRepository.java:138)
	at org.gradle.cache.internal.DefaultCacheRepository$AbstractCacheBuilder.open(DefaultCacheRepository.java:121)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.createParallelSafeCompiler(ZincScalaCompiler.java:132)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.execute(ZincScalaCompiler.java:77)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:66)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:48)
	at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:31)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:87)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	... 2 more
Caused by: org.gradle.cache.internal.LockTimeoutException: Timeout waiting to lock Zinc compiler cache (/tmp/.gradle/caches/2.14/zinc). It is currently in use by another Gradle instance.
Owner PID: 4117
Our PID: 1112
Owner Operation: 
Our operation: 
Lock file: /tmp/.gradle/caches/2.14/zinc/cache.properties.lock
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:264)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:133)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:81)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:68)
	at org.gradle.cache.internal.DefaultCacheAccess.open(DefaultCacheAccess.java:86)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:46)
	... 16 more

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':some:another:project:compileScala'.
> Could not open Zinc compiler cache (/tmp/.gradle/caches/2.14/zinc).
   > Timeout waiting to lock Zinc compiler cache (/tmp/.gradle/caches/2.14/zinc). It is currently in use by another Gradle instance.
     Owner PID: 6832
     Our PID: 4285
     Owner Operation: 
     Our operation: 
     Lock file: /tmp/.gradle/caches/2.14/zinc/cache.properties.lock

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':some:another:project:compileScala'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.cache.CacheOpenException: Could not open Zinc compiler cache (/tmp/.gradle/caches/2.14/zinc).
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:48)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:28)
	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:80)
	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:50)
	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.doOpen(DefaultCacheRepository.java:138)
	at org.gradle.cache.internal.DefaultCacheRepository$AbstractCacheBuilder.open(DefaultCacheRepository.java:121)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.createParallelSafeCompiler(ZincScalaCompiler.java:132)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.execute(ZincScalaCompiler.java:77)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:66)
	at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:48)
	at org.gradle.api.internal.tasks.compile.daemon.CompilerDaemonServer.execute(CompilerDaemonServer.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	... 5 more
Caused by: org.gradle.cache.internal.LockTimeoutException: Timeout waiting to lock Zinc compiler cache (/tmp/.gradle/caches/2.14/zinc). It is currently in use by another Gradle instance.
Owner PID: 6832
Our PID: 4285
Owner Operation: 
Our operation: 
Lock file: /tmp/.gradle/caches/2.14/zinc/cache.properties.lock
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:264)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:133)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:81)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:68)
	at org.gradle.cache.internal.DefaultCacheAccess.open(DefaultCacheAccess.java:86)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:46)
	... 27 more

==============================================================================

BUILD FAILED
```

# Solution

I don't see why an exclusive lock is necessary while calling `ZincScalaCompiler.Compiler#createCompiler` since `zinc.Compiler.getOrCreate` is already using [thread-safe cache](https://github.com/typesafehub/zinc/blob/master/src/main/scala/com/typesafe/zinc/Cache.scala#L39-L47).

The only case when it can break now is when **several independent Gradle processes** will try to populate a cold cache at the same time. It makes sense to notice that when [Zinc compiles a compiler interface](https://github.com/typesafehub/zinc/blob/master/src/main/scala/com/typesafe/zinc/Compiler.scala#L148) an underlying sbt compilation [takes place in a temporary folder](https://github.com/sbt/sbt/blob/0.13.12/compile/src/main/scala/sbt/compiler/AnalyzingCompiler.scala#L142). It means it's highly unlikely that two separate processes will interfere during a few milliseconds spend while writing an archive for a compiled compiler interface. 

# Testing

Tests are passing. I also build a 2.14.1 version of Gradle with this patch cherry-picked and it passed our CI multiple times and we didn't experience any issues while testing.

to: @ghale since you introduced this behavior in b12bfc5bfede5702cad589147a2dcdeaf802b752

### CODE REVIEW

**Comment by eriwen** [comment]
I see that you have signed a CLA. Thank you! I will consult with @ghale on this change - you can expect a response likely Tuesday, Jul 05 (as Monday is a holiday here in the US).

**Comment by fkorotkov** [comment]
@eriwen thanks! 

To notice I tried another solution to lock only if necessary(use `get` instead of `getOrCreate`):

```
return com.typesafe.zinc.Compiler.compilerCache().get(setup, new scala.runtime.AbstractFunction0<com.typesafe.zinc.Compiler>() {
  public com.typesafe.zinc.Compiler apply() {
    // useCache acquires an exclusive lock
    return zincCache.useCache("initialize", new Factory<com.typesafe.zinc.Compiler>() {
      public com.typesafe.zinc.Compiler create() {
        // check cache again
        return com.typesafe.zinc.Compiler.create(setup, logger);
      }
    });
  }
});
```

But it was failing too just less frequently.

I also considered making `DefaultFileLockManager#DEFAULT_LOCK_TIMEOUT` configurable but it looks like avoiding the problem instead of fixing it. :-)

**Comment by ghale** [comment]
@fkorotkov: One thing to understand here is that the Zinc compiler always runs out of process in a compiler daemon.  When a Scala compile is invoked, if a compiler daemon is busy, Gradle will start another compiler daemon to process the compile task.  So, if this is running on a clean system (i.e. Zinc compiler interface jar does not exist) and multiple scala compiles start up roughly simultaneously (in parallel), multiple compiler daemons will start up and try to create the interface jar at the same time.  We noticed intermittent failures in our CI environment and received reports from users on this issue which lead to this synchronization of compiler creation.  Implementing the synchronization fixed the issues we were seeing.  Although you haven't seen the problem yet, my guess is that you eventually would.

Having said that, I don't think completely disabling the synchronization is a viable solution.

I think it would be important to understand why you're getting a timeout.  The lock timeout is 60 sec.  With a 32 core machine, Gradle should (by default) try to run 32 workers in parallel mode.  This is a lot, but it would still require each worker to hold the lock for an average of 2s or more for a timeout to occur (which _seems_ unlikely).  A couple of things you could try:
1. Set the number of workers (--max-workers) lower, to say 8, and see if the issue goes away.  This would prove that excessive synchronization is the issue.  If it doesn't go away, then something else is going on.
2. Insert a simple scala compile task at the beginning of the build that does not compile anything, but would serve to create the compiler jar and do the heavy lifting of zinc compiler initialization.  Once that's done, the other compile tasks (which would depend on this task) should skip right through the synchronized compiler creation.  If this does change the behavior, it would also give you an idea of how long it is taking zinc to create the compiler interface jar since that would be roughly the only thing the task does.  If this doesn't change the behavior, then it shows that there is something else going on during compiler creation that is slowing things down (ie not just the compiler interface jar generation).  
3. Change the Zinc compiler cache location for each scala compile task (set `org.gradle.zinc.home.dir` in options.forkOptions.jvmArgs for each scala compile task).  You can split this up by project or by scala version or even by individual task, but the point is that they will synchronize on different caches and avoid a single cache directory.  This is a variation of 1 but allows you to reduce the synchronization without limiting max workers.

Once we understand what's going on, we can discuss what other changes might be called for with the way we handle Zinc compiler creation.

**Comment by fkorotkov** [comment]
@ghale thanks for detailed reply! Could you please clarify this statement:

> When a Scala compile is invoked, if a compiler daemon is busy, Gradle will start another compiler daemon to process the compile task.

Will Gradle start a separate process? Or maybe a thread? Could you please point me in code where this logic is defined. I would love to learn more about that.

**Comment by ghale** [comment]
Specifically here: https://github.com/gradle/gradle/blob/f24146cc5f956a1b03a515bbee4225e6f861b6ab/subprojects/language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/daemon/CompilerDaemonManager.java#L40

The compiler daemons run in a separate process.  This allows for process-specific settings like different heap sizes, system properties and/or temporary directories.  Note that the compiler daemon infrastructure is generic and used for many things other than just Scala.

**Comment by fkorotkov** [comment]
Thanks! Good to know. Make sense :-)

I've tried to reduce `--max-workers` to 8 on 2.14.1-rc and got the same error. But we have only 4 different scala config so it doesn't seem concluding. I'll try to get some data about interface compilation time.

**Comment by ghale** [comment]
If you want to create a [build scan](https://scans.gradle.com/setup/step-1) I'd be happy to take a look.

**Comment by fkorotkov** [comment]
Unfortunately I can't share information about our internal builds. But I found out that it takes 53 seconds to `ZincScalaCompiler.Compiler#createCompiler` for the very first time. Something is very wrong. Let me dig more into the issue.

**Comment by fkorotkov** [comment]
@ghale sorry for a delayed response I was distracted with some other work. I was thinking a lot in the last week about the problem and that ideally we'd like caches per each Scala setup but such a change requires to much of man power. So I ended up with simply allowing to specify a different default file lock timemout. Please check #671. 

In our case I set it up to 3 minutes and now all our 32 workers can eventually get a lock. Since we cache caches between runs it will affect only the very first CI run. Unfortunately lowering amount of workers is not an option for us since we want to have max performance. And addicting some additional logic to the build seems to me like a hacky solution. :-)

**Pull request closed without merging**
