### PR TITLE
Ignore flaky test

### PR DESCRIPTION
**Pull request by blindpirate**
https://github.com/gradle/gradle-private/issues/977

### CODE REVIEW

**Comment by bmuschko** [comment]
Why are those tests flaky? They look pretty straight forward to me.

**Comment by blindpirate** [comment]
I got notifications from CI: https://builds.gradle.org/viewLog.html?buildId=9068893&buildTypeId=Gradle_Check_Parallel_Java7_Ibm_Linux_dependencyManagement

I guess it's due to `parallelTest` but haven't checked yet.

**Comment by blindpirate** [comment]
And this: https://builds.gradle.org/viewLog.html?buildId=9062023&buildTypeId=Gradle_Check_Parallel_Java7_Ibm_Linux_dependencyManagement

**Comment by bmuschko** [comment]
You might want to try using `@IgnoreIf({GradleContextualExecuter.parallel})` first to see if you are right.

**Comment by blindpirate** [comment]
Let's investigate it first, thank you very much for your excellent solution!

**Pull request merged**
