### PR TITLE
fix issue#22955: Show usage information (e.g. description) when @Option is specified incorrectly on command line

### LINKED ISSUE #22955: Show usage information (e.g. description) when @Option is specified incorrectly on command line
Using Gradle 7.6, when a developer fails to correctly specify an `@Option` input correctly, Gradle will fail like:

```
$ ./gradlew :core:core:updateApi --overridePolicyWithApproval

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :core:core:updateApi from command line.
> No argument was provided for command-line option '--overridePolicyWithApproval'.
```

Where the option is specified as:

```
    @get:Option(
        option = "overridePolicyWithApproval",
        description = "Buganizer ID where overriding Semantic Versioning policy was approved."
    )
    @get:Input
    @get:Optional
    abstract val overridePolicyWithApproval: Property<String>
```

However, it might be more informative to the user to fail with the option's description:

```
$ ./gradlew :core:core:updateApi --overridePolicyWithApproval

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :core:core:updateApi from command line.
> No argument was provided for command-line option '--overridePolicyWithApproval' with description:
> Buganizer ID where overriding Semantic Versioning policy was approved.
```

This is enough for the user to understand how they should have specified the argument.

### Expected Behavior
Fails with description:
```
> No argument was provided for command-line option '--overridePolicyWithApproval' with description:
> Buganizer ID where overriding Semantic Versioning policy was approved.
```

### Current Behavior
Fails with no extra information:
```
> No argument was provided for command-line option '--overridePolicyWithApproval'.
```

### PR DESCRIPTION
**Pull request by bodhili**
Fixes #22955 

### Context
- The prompt information is more complete, which is convenient for users to quickly solve problems

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Review by blindpirate — APPROVED** [review]
This LGTM, but it would be great if you can squash the commits into a single one.

**Comment by bodhili** [comment]
> This LGTM, but it would be great if you can squash the commits into a single one.

I'm sorry, and let me see, I haven't done it yet

**Comment by bodhili** [comment]
> This LGTM, but it would be great if you can squash the commits into a single one.
 @blindpirate I've squash the commits into a single one, thanks for your advice and guidance. and re-review, please

**Comment by bodhili** [comment]
Is there something wrong about `Pre-tested commit build failed.`  @blindpirate

**Comment by blindpirate** [comment]
@bodhili Yes, there're two builds failing (you should be able to see them with "guest" login):

- `org.gradle.api.tasks.options.TaskOptionFailureIntegrationTest.using an unknown option yields decent error message`: https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Platform_3_bucket3/59176705?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=false
- `org.gradle.integtests.WrapperGenerationIntegrationTest.generated wrapper files are reproducible`: https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Platform_3_bucket13/59176715?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=false

**Comment by bodhili** [comment]
> @bodhili Yes, there're two builds failing (you should be able to see them with "guest" login):
> 
> * `org.gradle.api.tasks.options.TaskOptionFailureIntegrationTest.using an unknown option yields decent error message`: https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Platform_3_bucket3/59176705?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=false
> * `org.gradle.integtests.WrapperGenerationIntegrationTest.generated wrapper files are reproducible`: https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Platform_3_bucket13/59176715?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&expandBuildChangesSection=false

@blindpirate yes, I'm gradually familiar with it, and I have fixed these 2 issues, and re-review , please.   thanks

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
