### PR TITLE
Remove deprecated AbstractTestTask methods

### PR DESCRIPTION
**Pull request by rieske**
https://github.com/gradle/gradle/issues/17151

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]

**Review by nathan-contino — APPROVED** [review]
docs LGTM

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
This change requires dropping support for KGP 1.3.72, making the minimum version 1.4.0.

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
