### PR TITLE
Fix flaky tests caused by accidental cache hit (gradle-private#948)

### PR DESCRIPTION
**Pull request by blindpirate**
See https://github.com/gradle/gradle-private/issues/948

When two tests happen to be assigned the same port number, the cache
 is hit by accident. This result in different control flows and flaky tests.

### CODE REVIEW

**Comment by oehme** [comment]
How can two tests get the same port number?

**Comment by blindpirate** [comment]
@oehme I think it's a coincidence, that's why this test is flaky. The port number is assigned by OS randomly here: https://github.com/gradle/gradle/blob/25625363319836e74aea4abed4c52f14b2597f13/subprojects/internal-integ-testing/src/main/groovy/org/gradle/test/fixtures/server/http/HttpServerFixture.groovy#L102 .

Since port number is limited, two tests happen to be using the same port.

**Comment by oehme** [comment]
Maybe we should be using our `PortAllocator` there to ensure that two tests don't get the same one. Otherwise it seems likely that similar problems would pop up in other tests as well.

**Comment by blindpirate** [comment]
Wow, good to know, let me see.

**Comment by blindpirate** [comment]
Thanks @jjohannes , however, I'm thinking if we can solve this problem on `HttpServer` side. Current `PortAllocator` implementation seems not to fit in this scenario where we should avoid allocating same port in a certain build. Maybe we can implement a special `PortAllocator` which persists allocated port number in a file or something to achieve this.

**Comment by jjohannes** [comment]
I was thinking to merge this as a fix for `HttpScriptPluginIntegrationSpec` now. And continue the discussion about a more general fix on the linked issue (I added a comment there).

But you can also discard this PR and do a more general fix directly.

**Comment by blindpirate** [comment]
I'd like to discard this one and create a new PR ASAP. Thanks for reviewing!

**Comment by oehme** [comment]
@blindpirate did you try the `PortAllocator`? What was the result?

**Comment by blindpirate** [comment]
@oehme I've read the code, it has 2 implementations `FixedAvailablePortAllocator` and `ReleasingPortAllocator`, they can only detect available port, allocate or release them, but can't fit in our scenario: we want a `PortAllocator` which can persist allocated ports somewhere and avoid reallocating them.

**Pull request closed without merging**
