### PR TITLE
Add class filters to OperationListener

### PR DESCRIPTION
**Pull request by hegyibalint**
## Description

Workaround of our original solution for solving the perf. regression caused by the `OperationListener`.
As this solution enables us to receive problems from workers, a new feature flag is introduced to `JavaCompileSpec`.

## Feature flagging

The feature flag was [already present](https://github.com/gradle/gradle/pull/27873/files#diff-5149fec16d6f4f78ca138f33a60f513880961589046abdf645a1f059a2782717L95-L99) in the `JdkJavaCompiler`, but realized that system properties are not proxied to worker processes. Thus, we needed another mechanism to tell the compiler if the feature is used or not. Based on the feedback of the JVM team, we integrated the flag into `JavaCompileSpec`. 

@gradle/bt-jvm PTAL if you are happy with the solution.

### CODE REVIEW

**Comment by hegyibalint** [comment]
@bot-gradle test APT

**Review by donat — COMMENTED** [review]
I'm happy with this, but let's wait the JVM team for a final approval.

**Review by ghale — APPROVED** [review]
LGTM

**Comment by donat** [comment]
We decided not to use an OperationListener-based approach to attach information to problem reports.

**Pull request closed without merging**
