### PR TITLE
Issue 142: C++ to leverage library path for GCC linker and loader.

### PR DESCRIPTION
**Pull request by b-john**
Signed-off-by: jb020370 <john.bennewitz@cerner.com>

### Context
Addresses issue 142 for GCC: https://github.com/gradle/gradle-native/issues/142. 

Current State: C++ built binaries rely on dependent binaries (libraries) being in the same absolute file path as was built against. This makes installation (moving the binaries to a different machine) difficult because other machines must mirror the build file system structure in order to execute the binary. 

Proposed State: C++ built binaries rely on the library path (LD_LIBRARY_PATH on GCC Linux) to find dependent libraries to link against and load. This is similar to leveraging the java CLASSPATH for loading JARs as opposed to forcing the loader to load from an absolute path.
 
Notes: 
- There are existing integration test which cover the code changed (CppLibraryIntegrationTest, CppCachingIntegrationTest, CppDependenciesIntegrationTest, etc.). Let me know if there is a more specific automated test we would want to see here. 
- Validated gradle build / existing automated test run successfully as does the existing samples: https://github.com/gradle/native-samples/tree/master/cpp/library-with-tests

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by b-john** [comment]
Any update?

**Comment by lacasseio** [comment]
Thanks @b-john for the great work. I'm looking at it today and see if we merge it tomorrow.

**Comment by lacasseio** [comment]
@b-john Looking at this PR, I can't figure out what this PR bring to what is already present in Gradle. The installation relys on `LD_LIBRARY_PATH` environment variable to relocate the binaries. The split of `-L` and `-l` flags instead of absolute path doesn't change the path recorded inside the binary (at least on macOS). Could you elaborate on why this change is required and how it affects the binary?

**Comment by b-john** [comment]
Thanks @lacasseio! I elaborated/added a test case here with example output in the README here: https://github.com/b-john/gradle-libpath .

I'm running against RHEL / any Linux distro inside of a Docker Container; Sorry, I can try to find an OSx machine if necessary. 

Let me know if the README doesn't answer your questions; To my knowledge, GCC embeds the absolute path into the binary unless we leverage the '-l' option. By switching to "-l", it will leverage the library path instead. 

Appreciate it Daniel, let me know if I can be of any assistance/clarification

**Comment by lacasseio** [comment]
I can confirm this is an issue on at least Linux with GCC. On macOS, clang and gcc disregard the -L/-l massaging and show the path in absolute form. On macOS, if the DYLIB_LIBRARY_PATH is set, it will try to find the file name in those paths before looking in the absolute path. I haven't tried on Windows, but I assume it will be one of the 2 behavior. There seems to be a gap in our test coverage as the install task doesn't work properly. We assume it uses the copied library when in fact it uses the binaries in the path where they got linked.

**Comment by lacasseio** [comment]
@b-john As a step forward, could you add a new intergration test suite for binary relocation a bit like [this experimental branch I did based on your PR.](https://github.com/gradle/gradle/commit/d024c102de25e1d959e9f92a46b891720842bb2d).

**Comment by lacasseio** [comment]
Digging deeper into this, is seems the solution isn't splitting the library include path -L/-l but instead [setting the install name which was done in the software model plugin](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/plugins/NativeComponentModelPlugin.java#L326) but not in the current model plugins.

Here is what I think is missing on this PR:
- [ ] Write relocation integration test
  - The hard part here is to assert using relocatable binaries doesn't cause miss behavors inside IDE such as Xcode and Visual Studio. Bonus point for testing it inside Clion with the new Gradle support.
- [ ] Revert the splitting of library path (-L/-l)
- [ ] Convert [`set/getInstallName`](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/tasks/LinkSharedLibrary.java#L75-L84) into a `Property<String>`
- [ ] Document this breaking change in the release note
- [ ] Ensure all tests setting the install name still works (running the native test suite will allow you to confirm this)
- [ ] Inside the [current model plugin](https://github.com/gradle/gradle/blob/master/subprojects/language-native/src/main/java/org/gradle/language/plugins/NativeBasePlugin.java#L302-L313), set the install name as a provider that resolve the linkFile to get the file name. Don't bother adding anything in the DSL as the software model was.

The Xcode and Visual Studio IDE test coverage will probably work as expected, however linux may have some issue with the relocation as binaries won't be found. The good thing is we don't support any IDE on Linux. It would still be nice to compare the Clion experience with and without the change.

**Comment by lacasseio** [comment]
As the relocation issue affects only Linux, we should just fix the minimum by setting install name only for Linux operating system family. This will avoid any IDE issue with Xcode and co. as the fix will be narrow to the core of the issue.

**Comment by b-john** [comment]
Thanks @lacasseio -- Sorry to clarify on the design here; We're proposing...
* To modify the "install name" attribute of the LinkerSpec into a Property<String>
* For Linux-only, modifying GCC to leverage that install name property list as input into "rpath"? 
** And wanting to set rpath to a default value of something like $ORIGIN? 
** Does the install name property list still have the ability to manipualte the soname? https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/gcc/GccLinker.java#L90 

Appreciate your time & help here!

**Comment by lacasseio** [comment]
The "install name" inside the `LinkerSpec` shouldn't be modified. It's the [property on the `LinkSharedLibrary`](https://github.com/gradle/gradle/blob/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/tasks/LinkSharedLibrary.java#L75-L84) that need to be modified.

At this stage, we wouldn't touch anything related to `rpath`. We would use what is available in Gradle to solve the relocation issue on Linux. The soname isn't exposed through the DSL of the new C++ plugin. Instead of exposing them (which would require an use case to consider and would be part of some other work), we will simply fix it to the file name. It would get rid of the absolute path on Linux and allow for relocation. The install name can still be manually configured by getting the link task from the binary and configure the task directly. What we are doing here is to set the value to a sensible default to allow relocation.

**Comment by lacasseio** [comment]
@b-john I went ahead a did the change on another PR (https://github.com/gradle/gradle/pull/7722). Do you think you could confirm it solve most of your issue and IDE experience isn't totally broken? Note that you still need to pass the `rpath` if you want the executable to search the executable directory for the library. This issue would require a better modeling of the binary relocation at https://github.com/gradle/gradle-native/issues/142. It should allow you to relocate the binary using `LD_LIBRARY_PATH` at the very least until we get the binary relocation modeling done. You can provide some help if you want on that front.

**Comment by b-john** [comment]
Fantastic, thanks Daniel! I'm pretty confident it does and will validate it in the next few days. Appreciate the help!

**Comment by b-john** [comment]
Everything looks good, thanks again Daniel for the assistance & fix here.

**Pull request closed without merging**
