### PR TITLE
Fix the issue that missing 'archiveName' attribute in eclipse wtp.

### LINKED ISSUE #23129: Missing 'archiveName' attribute in eclipse wtp
### Expected Behavior
When generating the `.settings/org.eclipse.wst.common.component` file with the eclipse plugin, project dependencies should include an attribute named 'archiveName' and generated war from Eclipse should include the dependency.

```xml
<dependent-module archiveName="lib.jar" deploy-path="/WEB-INF/lib" handle="module:/resource/lib/lib">
    <dependency-type>uses</dependency-type>
</dependent-module>
```

```bash
$ unzip -l out.war | grep "lib.jar"
1308484  2022-12-13 10:36   WEB-INF/lib/lib.jar
```

### Current Behavior
The 'archiveName' attribute is not generated leading Eclipse to print a warning and the generated war to miss the library.

```xml
<dependent-module deploy-path="/WEB-INF/lib" handle="module:/resource/lib/lib">
    <dependency-type>uses</dependency-type>
</dependent-module>
```

```bash
$ unzip -l out.war | grep "lib.jar"
<no result>
```

image

### Context
Trying to generate a WAR with eclipse to deploy in JBoss

### Steps to Reproduce 
Run `./gradlew eclipse` on https://github.com/Tiller/gradle-eclipse-issue. Import project, and check 'Deployment Assembly' or export war from Eclipse.

### Your Environment
Gradle 7.6, Linux, Java 11

### PR DESCRIPTION
**Pull request by Chaoba**
Signed-off-by: Yanshun Li <qqliys@126.com>

Fixes #23129

### Context
When generating the `.settings/org.eclipse.wst.common.component` file with the eclipse plugin, project dependencies miss the attribute that named 'archiveName' .

Run `./gradlew eclipse `on [https://github.com/Tiller/gradle-eclipse-issue](https://github.com/Tiller/gradle-eclipse-issue) and check file `.settings/org.eclipse.wst.common.component`

Before the change:
```
<?xml version="1.0" encoding="UTF-8"?>
<project-modules id="moduleCoreId" project-version="1.5.0">
	<wb-module deploy-name="app">
		<property name="context-root" value="app"/>
		<wb-resource deploy-path="/WEB-INF/classes" source-path="src/main/java"/>
		<dependent-module deploy-path="/WEB-INF/lib" handle="module:/resource/lib/lib">
			<dependency-type>uses</dependency-type>
		</dependent-module>
	</wb-module>
</project-modules>

```
After the change:

```
<?xml version="1.0" encoding="UTF-8"?>
<project-modules id="moduleCoreId" project-version="1.5.0">
	<wb-module deploy-name="app">
		<property name="context-root" value="app"/>
		<wb-resource deploy-path="/WEB-INF/classes" source-path="src/main/java"/>
		<dependent-module archiveName="lib.jar" deploy-path="/WEB-INF/lib" handle="module:/resource/lib/lib">
			<dependency-type>uses</dependency-type>
		</dependent-module>
	</wb-module>
</project-modules>
```

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation

### CODE REVIEW

**Review by xaviarias — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by Chaoba** [comment]
@donat I have resolved the sanity check, please review and retrigger the build. Thanks.

**Comment by donat** [comment]
@Chaoba I was going to ask you to do exactly what you did in [ffeec88](https://github.com/gradle/gradle/pull/23288/commits/ffeec887f12a8d5a6f45dbf71875845e2ad59bb6), thank you for being proactive.

**Comment by donat** [comment]
@bot-gradle test RFM

**Review by donat — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@Chaoba thank you for your contribution!

**Pull request merged**
