### PR TITLE
Adding design doc for not deleteing symlinks

### PR DESCRIPTION
**Pull request by ethankhall**

### CODE REVIEW

**Comment by mark-vieira** [comment]
@ethankhall just a couple of comments.

1. We should add a property to the `Delete` task to allow users to get the old behavior.
2. We need to default back to using the commons-io implementation for detecting symlinks when using < Java 1.7. This also means that on Java 1.6 on Windows the behavior will remain the same, we will always follow symlinks. Just need to be sure to document this.

**Comment by ethankhall** [comment]
@mark-vieira. I though on the mailing list it was decided that we would document that you could use ant.delete if they wanted to keep the existing behavior. Question about the native-platform, does that have any requirements on java versions?

**Comment by mark-vieira** [comment]
@ethankhall using `ant.delete` is the workaround for `Project.delete()` since there's no simple way to toggle its behavior. It's trivial however to add a flag to the `Delete` task so I don't see a reason why not.

I was conflating native-platform with the JDK nio stuff. Yes, that should work back to Java 1.6. That said the native-platform stuff is a little involved since we aren't currently using the `stat()` capability. For all this stuff in Gradle we have abstractions written around then in case we can't iniitalize the native platform integration. We'll need to do something similar for this by providing a fallback using either `nio.Files` or commons-io (or both).

https://github.com/gradle/gradle/blob/master/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/services/FileSystemServices.java#L47-L47

**Comment by ethankhall** [comment]
Ok cool. I'll update the docs when I get some time (hopefully today)

**Comment by mark-vieira** [comment]
@ethankhall sorry I didn't notice that you had updated the spec. It all looks good to me, we'll just want to ensure that we add test coverage for any changes to the native platform stuff. We can either update the existing pull request or open a new one, it's up to you.

**Pull request merged**
