### PR TITLE
support noTimestamp and noVersionStamp groovydoc flags

### PR DESCRIPTION
**Pull request by paulk-asert**

### CODE REVIEW

**Comment by eljobe** [comment]
@eskatos Would you mind owning this pull request?

**Comment by eskatos** [comment]
My pleasure @eljobe

**Comment by eskatos** [comment]
Hi Paul,
I hope you're doing well.

As you already know, we want such changes to be described in a [design document](https://github.com/gradle/gradle/blob/master/design-docs). Would you mind adding one? Maybe in a `groovy-support.md` file there.

Oh and by the way, I guess that the existing `org.gradle.util.VersionNumber` class could easily replace the `Version` class introduced in this pull-request.

Cheers

**Comment by paulk-asert** [comment]
Hi Paul, I'm doing well. Good catch for Version. I changed that and added some doco. Let me know how that looks.

Cheers, Paul.

**Comment by eskatos** [comment]
Excellent. I reviewed and tested the changes locally and they LGTM.
As the version of the Groovydoc that is used, is the one from the Groovy defined in the build script, I'd say the DSL doc of the associated task should mention that the two added properties work for Groovy >= 2.4.6 only. Let's merge, I'll do that on my side.

Cheers

**Comment by eskatos** [comment]
Paul, thank you!
Your changes are now scheduled to be included in 2.13.
Cheers

**Comment by paulk-asert** [comment]
Thanks Paul.

**Pull request merged**
