### PR TITLE
Added a preferProjectModules option to ResolutionStrategy

### PR DESCRIPTION
**Pull request by idlsoft**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [x] Before submitting a pull request, I started a discussion on the
[Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev)
or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [x] I wrote a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [x] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [x] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by idlsoft** [comment]
This s squashed version of https://github.com/gradle/gradle/pull/635.
The test was moved to a separate class.

**Comment by wolfs** [comment]
Thank you for your pull request.

I am sorry to say that we do not have the capacity to look at this now. We will come back to you in a few weeks. Thank you for your patience.

**Comment by bigdaz** [comment]
Hey @idlsoft, thanks for all your work on this. Unfortunately with Gradle Summit looming, preparing for Gradle 3.0, and a problematic 2.14 release, we're stretched a bit thin at the moment.

You haven't been forgotten and this PR is in our queue of stuff to deal with. As @wolfs said, thanks for your patience while we get back on track.

**Comment by wolfs** [comment]
Looks like this has been also requested in the forums: https://discuss.gradle.org/t/project-dependencies-participate-in-conflict-resolution/18875

**Comment by jjohannes** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-6257

**Comment by jjohannes** [comment]
@idlsoft we finally integrated this. Thanks for the effort you invested in this and for your patience!

This feature will be part of the Gradle 3.2 release.

**Comment by idlsoft** [comment]
This is great, thank you!
Btw the reason the PR originally had preferProjectModules as a property was to be able to set it to false, so that if the default ever changes no additional public interface modifications would be necessary.

**Pull request merged**
