### PR TITLE
Remove build-logic-settings

### PR DESCRIPTION
**Pull request by wolfs**
There is no reason the logic needs to be a settings plugin; it can be a regular plugin as well.

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle PRF

**Comment by wolfs** [comment]
@bot-gradle test PRF

**Comment by hegyibalint** [comment]
How comes that this was a settings plugin?

**Comment by wolfs** [comment]
> How come this was a settings plugin?

That is a good question. I think we had other settings plugins before, though those went away, only leaving this one that actually isn't necessarily a settings plugin.

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
