### PR TITLE
Play plugins removal

### PR DESCRIPTION
**Pull request by ljacomet**
All in the title!

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
Looks like I have a green build 🎉 
@big-guy Can you confirm that the test that was moved was the only one for the external plugin? See first commit.

**Review by jjohannes — APPROVED** [review]
Looks good. Thanks a lot!

**Pull request merged**
