### PR TITLE
Remove test filtering plugin

### PR DESCRIPTION
**Pull request by eriwen**
Prepare to use a new one soon.

### CODE REVIEW

**Comment by eriwen** [comment]
@bot-gradle RfM

**Comment by eriwen** [comment]
@bot-gradle test RFN

**Comment by eriwen** [comment]
@bot-gradle test RFN

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Review by blindpirate — APPROVED** [review]

**Review by pshevche — APPROVED** [review]

**Pull request merged**
