### PR TITLE
Report problem for external process started at configuration time by default

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Review by mlopatkin — APPROVED** [review]
lgtm, thanks for picking this up

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle cancel

**Comment by mlopatkin** [comment]
This is blocked on #24236, I'm working on the latter to unblock and merge this

**Comment by mlopatkin** [comment]
@bot-gradle test ACC, AST

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
