### PR TITLE
Set parallel and caching in gradle init

### LINKED ISSUE #21786: gradlew init should set parallel and caching to true
If you create a new project using `./gradlew init`, it currently creates a project that has `org.gradle.caching=false` and `org.gradle.parallel=false` since those are the default values for Gradle. Given these are brand new projects and these newly initialized projects are compatible with both parallel execution and caching, we should just set these values in `gradle.properties`

### PR DESCRIPTION
**Pull request by gabrielfeo**
Fixes #21786

### Context
Parallel execution and caching are widespread features of Gradle
which gradle init could suggest. Their default, however, is false.

Create gradle.properties in `gradle init` if "use incubating APIs" is
chosen, as suggested by @jbartok. Implementation based on
`GitAttributesGenerator`. Unit test based on `GitIgnoreGeneratorTest`.
Integration tests based on the "uses test suites when --incubating"
tests.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test this

**Comment by gabrielfeo** [comment]
Checks failed with an error that seems unrelated to the diff:

```
...FileNotFoundException: https://downloads.gradle-dn.com/distributions-snapshots/gradle-8.0-20221115075217+0000-bin.zip
```

Could merging master fix that?

**Comment by jbartok** [comment]
> Could merging master fix that?

On it. I'll take care of merging this in, no worries. Thank you for your contribution.

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
