### PR TITLE
Maintain order of classpath when generating start scripts (fixes #2513)

### LINKED ISSUE #2513: CreateStartScripts task generates classpath in wrong order
The transformation of the startscripts' classpath property to the relative classpath used inside the start scripts does not maintain the classpath order.

### Expected Behavior
Relative classpath must have the same order as the configured classpath

### Current Behavior
`getRelativeClasspath()` uses 
```
public static <R, I> Set<R> collect(Set<? extends I> set, Transformer<? extends R, ? super I> transformer) {
        return collect(set, new HashSet<R>(), transformer);
}
```
which uses a new HashSet instance to create the transformed Iterable and therefore the order is undefined.

[CreateStartScripts.java](https://github.com/gradle/gradle/blob/v4.0.1/subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java#L278)

### Steps to Reproduce (for bugs)
Bug is still on master, discovered in version 4.0.1

### PR DESCRIPTION
**Pull request by thhalm-talkwalker**
Change will fix issue #2513

### CODE REVIEW

**Comment by bmuschko** [comment]
Thanks for your contribution. Did you sign the CLA? I haven't found a record with your name.

**Comment by big-guy** [comment]
Thanks @thhalm!

Would you mind adding an integration test to `ApplicationIntegrationSpec`?

I was thinking the test could be setup so that we create two jars with a resource with the same name.  Each resource would have the name of the jar inside of it.  Then in the application's main, we would check that the correct resource is found.

To help you out with some of our test infrastructure peculiarities, something like this would create the two jars and add them as dependencies to the build.  Then it would be a matter of loading the `resource.properties` via `getResourceAsStream` and checking that we see `bar` and not `foo`.  The tests like `canUseEnvironmentVariableToPassMultipleOptionsToJvmWhenRunningScript` in that test class would be a good base.

```
        def testResources = file("resources")
        def resourceFile = testResources.file("resource.properties")
        resourceFile.text = "bar"
        testResources.zipTo(file("libs/bar.jar"))
        resourceFile.text = "foo"
        testResources.zipTo(file("libs/foo.jar"))
        buildFile << """
            dependencies {
                compile files("libs/bar.jar")
                compile files("libs/foo.jar")
            }
        """
```

**Comment by thhalm** [comment]
Hello @bmuschko,
Regarding the CLA our legal department check it and doesn't allow me to sign it.

How we can proceed here? Sorry for the hassle, I wasn't thinking that signing this CLA would be a problem...

**Comment by bmuschko** [comment]
@thhalm I am sorry but we can't accept any pull request without a signed CLA for legal reasons. Could you maybe submit a PR with a private account?

**Comment by thhalm-talkwalker** [comment]
Ok, I checked with my supervisor and I will submit the changes with my new, private account (and sign the CLA)

**Comment by thhalm-talkwalker** [comment]
Replaced by #2570

**Pull request closed without merging**
