### PR TITLE
Introduce :wrapper-shared project

### PR DESCRIPTION
**Pull request by bamboo**
To host the code shared between the wrapper and the distribution.

Follow-up to #17422

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Review by eskatos — COMMENTED** [review]
It seems the distro jar count is wrong
https://ge.gradle.org/s/lrmdgq2c6k3dg/tests/overview?outcome=failed

The wrapper jar hash needs to be updated
https://ge.gradle.org/s/5jd7obzgtmz6c/tests/overview?outcome=failed

**Comment by bamboo** [comment]
Thanks, @eskatos.

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Review by eskatos — APPROVED** [review]

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Pull request merged**
