### PR TITLE
Align JavaVersion format with official Java versioning

### PR DESCRIPTION
**Pull request by alllex**
For backward-compatibility reasons, when converting `JavaVersion` to a string, Gradle returned values that do not match official Java versioning scheme. In particular, the output format for Java 9 and Java 10 was `1.9` and `1.10`.

This PR changes the format to match the official one. Only Java 9 and Java 10 versions are affected:
- `1.8` -> `1.8`
- `1.9` -> `9`
- `1.10` -> `10`
- `11` -> `11`

Parsing of the old format is still supported.

### CODE REVIEW

**Comment by alllex** [comment]
@bot-gradle test qfl

**Comment by alllex** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by alllex** [comment]
@bot-gradle test and merge

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Pull request merged**
