### PR TITLE
More userguide docbook to asciidoc conversions

### PR DESCRIPTION
**Pull request by wolfs**

### CODE REVIEW

**Comment by wolfs** [comment]
@lptr Please review this set of changes. Especially look at https://github.com/gradle/gradle/pull/2595/commits/95db530ec215258e88451f46842b93014897b7c4, where I do the manual fixes on the chapters. If you know how to add a text figure in asciidoc, not all the figure numbers would change (see https://github.com/gradle/gradle/pull/2595/commits/95db530ec215258e88451f46842b93014897b7c4).

**Comment by bmuschko** [comment]
@wolfs Is there anything blocking the review or merge? This could soon become a huge merge conflict issue.

**Comment by wolfs** [comment]
@bmuschko I am looking for a reviewer. If you can have a look at the changes and merge it that would be great.

**Comment by wolfs** [comment]
Closing in favor of smaller PRs, starting with #2733.

**Pull request closed without merging**
