### PR TITLE
Create pluggable custom failure describers for variant selection failures and improve variant selection failure messaging

### PR DESCRIPTION
**Pull request by tresat**
This is Step 2 towards addressing https://github.com/gradle/gradle/issues/24609, after https://github.com/gradle/gradle/pull/27573.

This creates a `FailureDescriber` framework, for replacing generic variant resolution failures with custom messages, and implements an example described for gradle plugin API version unavailable failures.

The large number of changed lines is partly due to the license header being added to a few dozen new files and uninteresting boilerplate data classes to package failure data.  When the exception hierarchy is deleted (see future work), that should bring the overall Added/Deleted totals much closer.

Probably start a review at `ResolutionFailureHandler` and `ResolutionFailureDescriberRegistry`.

# Benefits Delivered Here

## User-Facing

- First custom message replacement: When a plugin requires a higher version of Gradle, this is explained concisely and appropriate resolutions suggested, replacing the old wall of text:
```
Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.example:producer:1.0.
     Required by:
         project : > com.example.greeting:com.example.greeting.gradle.plugin:1.0
      > Plugin com.example:producer:1.0 requires at least Gradle 1000.0. This build uses Gradle 8.5.
```
- There were many cases of capabilities being included in the "Wall of Text" failure error message in cases when capabilities _did not contribute to an incompatibility failure_.  These have been removed to clear potential red herrings from the error language.
- During ambiguity failures, variants which _were incompatible_ were printed.  These have been removed to clear potential red herrings from the message - these variants _did not_ contribute to the ambiguity, there's no need to print them.
- The language `consumable configuration` has been replaced with `variant` in several places, for consistency and correctness.  Configurations create/back variants, and should not be thought of as variants themselves.
- Various lists of variants, attributes, etc., printed in error messages are now alphabetized.

## Internal

- Allows for easy registration of additional custom failure messages for specific scenarios _without any modification to `ResolutionFailureHandler` core logic. 
- Compile time guarantee of data present in the failure data types (`ResolutionFailure` and extensions) - no more `null` fields.
- Easier to understand and modify failure messages for a particular failure type without changing other failure types.

### Minor Cleanup

- Fixed some styling to use `style` instead of writing HTML-ish tags manually.
- Many internal renames and repackaging for increased clarity.

# Next Steps

Much of this has been deferred simply to keep the size of this PR manageable - it has not been forgotten and can be delivered via a series of much smaller changes.

## User-Facing

- Instead of ":", print "the root project" in failure messages for clarity.
- Custom message for JDK mismatch, test case for Spring Boot.
- Custom message for Kotlin version mismatch.
- Custom message for KMP dependency on non-KMP project.
- Replace "Could not resolve all files for configuration ':classpath'." with custom text explaining what this means IRT dependencies needed by a build script.

## Internal

- Collapse exception hierarchy.  Delete all exceptions in `org.gradle.internal.component` just use `VariantSelectionException` for everything.  The hierarchy information will be available as part of the `ResolutionFailure` hierarchy, _not_ as specialized exceptions.  There is no more need for specialized exceptions.  This will also remove a generic argument from the describer hierarchy.
- New exception will provide the `ResolutionFailure` as a field so that consumers (reporting, perhaps) can check this data as well.
- New exception will be immutable, including potential resolutions.
- Extra formatting and testing around capabilities: When ambiguity is due to multiple configurations with the same capabilities, this should be the only thing printed.  Test matching against a normal jar and a far jar variant (with additional capability).  Check tests in `MultipleVariantSelectionIntegrationTest` to move to `ResolutionFailureHandlerIntegrationTest`'s error showcase.
- Register with the Problems API.
- Explode testing into tests per `Describer`.  Test for `ResolutionFailureHandler` should just test proper handoff to the expected described.
- An incompatibility or ambiguity `Failure` instance should be able to provide which attributes _were the cause of_ the problem.  This would allow the `NewerGradleNeededByPluginFailureDescriber` to shrink and be let concerned with "partially re-implementing variant selection" in order to find these attributes.  Describers should primarily be concerned with formatting and describing. 

### Minor Cleanup

- All failure handling code moved under `org.gradle.internal.component.resolution.failure` and sub-packages.
- `ResolutionFailureHandlerIntegrationTest` can likely be cleaned and made more idiomatic.

# Future Explorations

- Explore making explicit distinctions in printed messages between Graph variant and Artifact variant failures; pointing to the steps in the variant matching algorithm as appropriate.
- Possible new HTML formatted failure reports.
- The failures due to a missing configuration by name could just call their proper `Describer` directly.  This would be a little less consistent, but possibly clearer and quicker.  We could avoid putting these describes in the registry.  The messages could also include the list of other configurations, or a "did you mean X" message for potential typos of configuration names.
- We should work towards deprecating the case of depending on a configuration in another project (or the same project) by name completely - this should be done via variant matching.  Named configurations should only be allowed for external deps in Ivy repos.
- For failures when matching a project dependency, suggest as a resolution running `outgoingVariants` on that project where appropriate.
- The generics in the `ResolutionFailureHandler#describeFailure` methods - can they be simplified any?

## Allow Producers To Supply/Publish Attribute Info

- If we had a way for producers to provide a static description of the custom attributes they are publishing, as well as custom resolutions for the cases of incompatibility and ambiguity caused by those particular attributes, it should be possible to enhance the default `Describer` for those cases to check these and include them in the error messages.  This would allow projects and organizations to communicate more clearly why a dependency failed to resolve without writing any executable code.  We could also attach some of these descriptions to the core attributes included in Gradle.  

# Related

- https://github.com/gradle/gradle/issues/12126
- https://github.com/dsavvinov/kmp-var-failure-showcase
- https://github.com/gradle/gradle/pull/25190
- https://github.com/gradle/gradle/pull/19821

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle merge

**Comment by tresat** [comment]
@bot-gradle test and merge please

**Pull request merged**
