### PR TITLE
Add an option to FindBugs to disable analysis progress

### PR DESCRIPTION
**Pull request by blindpirate**
### Context
Many people are bothered by uncontrollable FindBugs progress output as reported in #1307 #1646 #1756 [https://discuss.gradle.org/t/add-an-option-to-pass-quiet-to-findbugs-plugin/554](https://discuss.gradle.org/t/add-an-option-to-pass-quiet-to-findbugs-plugin/554) . It is because '-progress' command line option is always activated when staring FindBugs in FindBugsSpecBuilder. This fix adds an option to FindBugs plugin named 'showProgress' to control it. If set to false, '-progress' will not be passed to FindBugs.

Unit test/integration tests and docs are provided.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

### CODE REVIEW

**Comment by felipecsl** [comment]
Is there any workaround for this while it's waiting to be merged?

**Comment by bmuschko** [comment]
> Is there any workaround for this while it's waiting to be merged?

At the moment there's no way to pass arbitrary command line options to the processing code of the FindBugs plugin. The only other option you have is to roll your own plugin.

**Comment by blindpirate** [comment]
Thank you @bmuschko , today I was still being bothered by this issue.

Actually, that command line option existed in the [original code](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/findbugs/FindBugsSpecBuilder.java#L160), so I just realized it shouldn't be passed all the time. Well, I feel wired too about missing `-progress` in official documentation, but I found it in other docs [here](http://manpages.org/findbugs) and [here](http://manpages.ubuntu.com/manpages/xenial/man1/findbugs.1.html), so I guess it's just a careless omission.

**Comment by bmuschko** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-6551

**Pull request merged**
