### PR TITLE
Re-use Scala compiler between runs

### PR DESCRIPTION
**Pull request by alpar-t**
Relates to #13274

### Context

Tested by changing a single Scala source file.

Before:
```
Compiling with Zinc Scala compiler.
Prepared Zinc Scala inputs: 0.443 secs
Compiling 1 Scala source to /home/alpar/work/elastic/cloud/scala-services/util/build/classes/scala/main ...
Done compiling.
Completed Scala compilation: 5.929 secs
```

After:
```
Prepared Zinc Scala inputs: 0.075 secs
Compiling 1 Scala source to /home/alpar/work/elastic/cloud/scala-services/util/build/classes/scala/main ...
Done compiling.
Completed Scala compilation: 0.694 secs
```

I also used a build with this change to run build for a while without any
side-effects.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by SheliakLyr** [comment]
How does this work with multiple workers and parallel builds? Right now, gradle spawns multiple workers. Each of this workers requires (in my case) over 2GB of memory. That memory is freed after the build, which is quite useful. As I understand, after the proposed changes, the workers will stay in memory. For `--max-workers=4` and beyond this will eat a significant amount of memory.

Am I correct? If so, could this be configurable via a property?

By the way: I think that scala compiling workers should be reused in parallel builds (1 worker <-> multiple parallel modules). They share o lot of the code/classes and spawning separate instances is wasteful.

**Comment by JLLeitschuh** [comment]
None of the other compilers are using `KeepAliveMode.DAEMON`, they are all using `KeepAliveMode.SESSION`. Why should the scala compiler be different?

**Comment by alpar-t** [comment]
I'm not sure about the others, but the Scala compiler is significantly slower on a cold start.
I would argue other compilers should be kept around with the daemon too for performance benefits,
not the other way around. 
This will require more resources for sure, but that's the whole traideoff of the daemon, one could disable 
it entirely if resource consumption is a concern, or scale the memory usage of the workers accordingly.

**Comment by JLLeitschuh** [comment]
There's a question here about whether or not we should enable this for all the compilers across the board. This is something that we're exploring internally. Thanks for bringing this to our attention.

**Comment by JLLeitschuh** [comment]
@bot-gradle test this please

**Comment by JLLeitschuh** [comment]
@ljacomet I was chatting with @big-guy about your exploration around this. Do you want to try flipping this flag over on all of the compilers on the `master` branch and see how our build handles that over the next few weeks?

**Comment by ijuma** [comment]
This is a huge improvement, is it still active?

**Comment by alpar-t** [comment]
@JLLeitschuh I'm still interested in purshuing this. Before I look  at the conflicts, was your last comment aimed at me or @big-guy ?

**Comment by ijuma** [comment]
For Scala users, this is a game changer. How can we get it over the line?

**Comment by alpar-t** [comment]
I'm still here, and interested to push this.

**Comment by lbradstreet** [comment]
@alpar-t I’m still here too. Let me know if you need a tester.

**Comment by lbradstreet** [comment]
What’s the next step here? I see unticked tasks for docs and unit tests, but what else is remaining on the testing side.

For large scala projects the amount of developer time saved by this change is astronomical. When working on Kafka I have to disable to gradle integration and use intellij’s compilation mode to have reasonable iteration times.

**Comment by alpar-t** [comment]
I'm very much interested in pushing this too, but looking for a sign that it's worth it as I didn't get a lot of attention from the maintainers in the past. There's also conflicts that need to be resolved now. I didn't do anything in terms of unit tests or public facing docs as I don't think the change is unit testable and wasn't sure if it needs any additional documentation.

**Comment by lbradstreet** [comment]
@JLLeitschuh do you have any guidance about where we can go with this change? If we're worried about the side effects could we initially make it configurable?

**Review by donat — CHANGES_REQUESTED** [review]
Sorry that we haven't responded to you earlier in a more constructive way. We discussed the proposal with the Gradle team and agreed that it makes sense. At the same time, @JLLeitschuh said, We should not change the default value for all builds. 

The PR should introduce a new `Property` to configure `keepAliveMode`, probably in `ScalaCompileOptions` (or in `BaseScalaCompileOptions`).

**Comment by lbradstreet** [comment]
@donat thanks, that's great.

@alpar-t let me know if there's any way I can help.

**Comment by aishfenton** [comment]
Another vote of excitement for this (and totally fine to have it as an opt-in configuration option for starters). Scala build times in Gradle are significantly slower than other tools (such as SBT). And I think this get's things pretty much on par. One difference with Scala (that might make this feel like a bigger deal to the Scala community than in Java), is that many engineers develop using some form of "continuous" feedback switched on, so the expectation is that you'll get <1s feedback for small changes.

**Comment by donat** [comment]
Any updates on this PR, @alpar-t?

**Comment by alpar-t** [comment]
Sorry, I'm still interested in this but didn't have any time to work on it. Not sure when I will be able to.

**Comment by donat** [comment]
I'll close this PR then.
To anyone watching; feel free to create a new PR, contributions are welcome.

**Comment by ijuma** [comment]
#20579 is a new PR attempting to solve the same issue.

**Pull request closed without merging**
