### PR TITLE
Try to mitigate performance regression in IdeIntegrationPerformanceTest

### PR DESCRIPTION
**Pull request by big-guy**
…hase start"

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle help

**Comment by big-guy** [comment]
@bot-gradle test APT

**Comment by big-guy** [comment]
@bot-gradle cancel

**Comment by big-guy** [comment]
@bot-gradle test APT

**Comment by big-guy** [comment]
@bot-gradle help

**Comment by big-guy** [comment]
@bot-gradle test APT

**Comment by big-guy** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
@bot-gradle test APT

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
