### PR TITLE
Version catalog fixes

### PR DESCRIPTION
**Pull request by melix**
This PR contains quick fixes for reported version catalog bugs. Please review commit per commit.

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge

**Pull request merged**
