### PR TITLE
Replaces java.util.Stack with ArrayDeque

### PR DESCRIPTION
**Pull request by huxi**
Any of the checked boxes below indicate that I took action:
- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:
- [ ] Before submitting a pull request, I started a discussion on the [Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev),
    the [forum](https://discuss.gradle.org/) or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I considered writing a design document. A design document can be
  brief but explains the use case or problem you are trying to solve,
  touches on the planned implementation approach as well as the test cases
  that verify the behavior. Optimally, design documents should be submitted
  as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
  can be found in the Gradle GitHub repository. Please let us know if you need help with
  creating the design document. We are happy to help!
- [x] The pull request contains an appropriate level of unit and integration
  test coverage to verify the behavior. Before submitting the pull request
  I ran a build on your local machine via the command
  `./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
  DSL reference and Javadocs where applicable.

---

This PR replaces all usages of `java.util.Stack` with `java.util.ArrayDeque`.

`Stack` extends `Vector` and is therefore `synchronized`. Using `ArrayDeque` instead gets rid of unnecessary synchronization overhead.

I quadruple-checked that synchronization is definitely not required in the cases that previously used `Stack`. It was only used as a local variable never leaving the scope or in a `ThreadLocal` attribute without leaving the class.

This a zero-risk change with definite performance gains, especially since `DefaultTaskExecutionPlan` is working on those Stacks in nested loops.

I executed the following commands since I changed files in `base-services`, `core` and `platform-native`:
- [x] `./gradlew quickCheck :baseServices:check`
- [x] `./gradlew quickCheck :core:check`
- [ ] `./gradlew quickCheck :platformNative:check`
  - this has test failures for me (see Issue #770), but they are the same with or without the changes of this PR applied.

### CODE REVIEW

**Comment by lacasseio** [comment]
Thanks @huxi for the performance improvement. It would be better to change and use [`Deque`](http://docs.oracle.com/javase/7/docs/api/java/util/Deque.html) and [`ArrayDeque`](https://docs.oracle.com/javase/7/docs/api/java/util/ArrayDeque.html) as they already provide `pop`, `push` and `peek` operations.

**Comment by huxi** [comment]
Good point. I thought they were added in 1.7, not 1.6. My bad.

I'll change the PR accordingly.

**Comment by huxi** [comment]
Done. I force-pushed to reduce noise.

**Comment by huxi** [comment]
@lacasseio I'm a bit confused, to be honest. (The Contribution Guidelines link above 404s and should probably link to https://gradle.org/contribute-to-gradle/ instead.)

On one hand, Gradle is supposed to require Java 1.6 (CG says "Try to ensure that your code & tests will run successfully on Java 6" and "Avoid using features introduced in Java 1.7 or later") so using `Deque` is indeed the right way to go.

On the other hand, the source level is still at 1.5 if not using Java 9... (`sourceCompatibility = javaVersion.java9Compatible ? 1.6 : 1.5`)... and I wonder why that's still the case.

**Comment by lacasseio** [comment]
Thanks @huxi, you are rising very good points. Let me double check with the other engineers and will get back to you on this one.

**Comment by eriwen** [comment]
@lacasseio Thank you for fixing the link to CONTRIBUTING.md in the template.

**Comment by big-guy** [comment]
@huxi @lacasseio WRT the version of Java we support, it's a little complicated.

1. We only support running Gradle on Java 7+.
2. We need to produce a useful error message when trying to run Gradle with an unsupported JDK (Java 6 and older).
3. We support *running tests* on Java 6+.
4. We support *compiling code* with Java 6+.
5. We support running the wrapper with Java 5+.

So we're forced to build parts of the project with target compatibility = 1.5 to produce an "unsupported JVM" error.  The project isn't divided cleanly, so some parts of core/base-services/tooling-api that need to support older versions are forced to target an older version as a whole.  I think we also had weird problems when we tried to mix projects with different compatibility levels.

So, in general, we can use Java 7 classes, but we have to be really careful to not break cases 2-4 above.  `ThreadGlobalInstantiator` is the only class that changed that is near areas that could break compilation or testing.  I think we're OK since we don't have to worry about Java 5 there.

@eriwen This is probably something we should try to explain in the contributors guide ^^^

**Comment by huxi** [comment]
Ah, I see. I do something similar over at [sulky-version Main stub](https://github.com/huxi/sulky/blob/master/sulky-version/src/main/java/de/huxhorn/sulky/version/Main.java).
Thanks for the clarification.

**Comment by huxi** [comment]
- [x] `./gradlew quickCheck :baseServices:check`
- [x] `./gradlew quickCheck :core:check`
- [x] `./gradlew quickCheck :platformNative:check`

with #770 fix in place.

**Comment by huxi** [comment]
Executed `./gradlew quickCheck :core:check` on merge conflict fix.

**Comment by lacasseio** [comment]
This PR is, in fact, a valid change and we appreciate the time and effort you put into this @huxi. However, given we can't quantify the performance gain or how much of a bottleneck it was lead us to simply close this PR. This has been preempted so many time by other higher priority task that's unrealistic to think we are going to merge it soon. If you can provide us a quantitive argument with regards to performance, we would prioritize this higher. Thanks for your time and sorry we couldn't merge your PR at this time.

**Comment by lptr** [comment]
I'd love to use `ArrayDeque` wherever we can. Since this is what the Javadoc on `Stack` actually recommends, I think we should just merge this PR:

```java
/*
 * ...
 * <p>A more complete and consistent set of LIFO stack operations is
 * provided by the {@link Deque} interface and its implementations, which
 * should be used in preference to this class.  For example:
 * <pre>   {@code
 *   Deque<Integer> stack = new ArrayDeque<Integer>();}</pre>
 * ...
 */
```

**Comment by lptr** [comment]
@huxi could you rebase on top of `master` one more time, please?

**Comment by huxi** [comment]
This isn't just about performance. The JIT should be clever enough to make the actual performance difference minuscule.

This is about code hygiene. One simply shouldn't use Java 1.0/1.1 `java.util.Vector`, `java.util.Stack` or `java.util.Hashtable` but their proper replacements instead.

The same is the case for `java.lang.StringBuffer` (synchronized) that should be replaced with `java.lang.StringBuilder` (unsynchronized, since 1.5).

If there are no conditional branches or loops involved then even `StringBuilder` should be avoided and be replaced with simply `+` concatenation.

The rationale for this is that Java 9 `javac` will replace those concatenations with `invokedynamic` calls instead of direct `StringBuilder` calls so bytecode compiled with Java 9 would benefit from potential future performance enhancements without need for recompile (see [JEP 280: Indify String Concatenation](http://openjdk.java.net/jeps/280)). Current Gradle codebase still has 27 `StringBuffer` usages in production code.

`String.format` is another candidate that should be avoided if it is merely used for concatenation, i.e. if the format pattern is solely using `%s` placeholders. It is a shorthand for `return new Formatter().format(format, args).toString();` which creates a new `Formatter` for every call, wasting cycles on parsing the format pattern.

Feel free to call me pedantic for pointing out these things. If I see them, I fix them.

If a Java 1.5 (or later) codebase is using `java.util.Stack` then I consider it a [broken window](https://pragprog.com/the-pragmatic-programmer/extracts/software-entropy).

- [x] `./gradlew quickCheck :baseServices:check`
- [x] `./gradlew quickCheck :core:check`
- [x] `./gradlew quickCheck :platformNative:check`

**Pull request merged**
