### PR TITLE
Let `GeneratePrecompiledScriptPluginAccessors` dispose of `ProjectBuilder` services

### PR DESCRIPTION
**Pull request by bamboo**
To mitigate listener leaks.

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
Is there a big enough leak here that you could run the `GeneratePrecompiledScriptPluginAccessors` task in 100 builds and get a OOM?  or some way to sense that the ProjectBuilder is thrown away (until we can replace it with something else)?

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Comment by bamboo** [comment]
> Is there a big enough leak here that you could run the `GeneratePrecompiledScriptPluginAccessors` task in 100 builds and get a OOM? or some way to sense that the ProjectBuilder is thrown away (until we can replace it with something else)?

After running the build on release 10 times:

```
for ((i = 0; i < 10; i++)); do ./gradlew help --rerun-tasks; done
```

I can observe a listener leak of around 400MB:

Screen Shot 2020-09-17 at 20 19 34

The leak does not reproduce with this PR.

**Pull request merged**
