### PR TITLE
Implement splitting source-sets in Kotlin DSL reference

### PR DESCRIPTION
**Pull request by jbartok**
Fixes 
* #24661

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test BD

**Review by eskatos — APPROVED** [review]
:+1:

**Comment by jbartok** [comment]
@bot-gradle test BD

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
