### PR TITLE
Use U test to determine performance regressions

### PR DESCRIPTION
**Pull request by oehme**
Instead of an arbitrary threshold we now use the Mann-Whitney U test
to calculate how confident we can be in the results.

For now we'll require a 99% confidence before reporting a regression.
We can tweak that value based on whether we miss too many
regressions or report too many non-regressions.

I'm going to do some experiments on this branch before merging.

### CODE REVIEW

**Comment by lptr** [comment]
Can this also recognize performance improvements? I'd love if we could report on those, too.

**Comment by oehme** [comment]
Yes, I changed both methods.

**Comment by oehme** [comment]
This already seems to be a lot better than what we had. It detects [this regression](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/11735964:id/report-performance-performance-tests.zip%21/report/tests/tasks---all-on-largeJavaMultiProject.html) with >98% confidence. Our old logic didn't detect it even after many tries.

**Comment by oehme** [comment]
After playing around with this a bit I noticed that the T test would have very high confidence in regressions for some scenarios, but very low confidence for others, even though their variance was the same. I then looked at the raw data and saw that the problematic scenarios didn't have a normal distribution, but a bi-modal distribution. That's because they have one maximum for "typical" runs and another maximum for runs that contained a major GC pause (every 3-4 builds).

I changed it to use the Mann-Whitney U test, which doesn't require normality. This reliably detects even small regressions that were invisible with our previous approach.

It detected
- [this](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/11744621:id/report-performance-performance-tests.zip%21/report/tests/assembleDebug-on-largeAndroidBuild.html#result1472027613) 1.5% regression 4/5 times (the 5th time it only had 93% confidence, we require 95%)
- [this](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/11744621:id/report-performance-performance-tests.zip%21/report/tests/eclipse-on-largeJavaMultiProject.html) 4% regression 5/5 times
- [this](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/11744621:id/report-performance-performance-tests.zip%21/report/tests/tasks---all-on-largeJavaMultiProject.html) 5% regression 5/5 times

After rebaselining those regressions, 15/15 tests were green.

It seems that we can indeed get rid of our retry logic thanks to this.

**Comment by oehme** [comment]
As expected this test does *not* detect [this](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/11744621:id/report-performance-performance-tests.zip%21/report/tests/test-for-non-abi-change-on-largeMonolithicJavaProject.html) 1.5% regression because we do too few measurements compared to the small difference.

We should probably move such long-running tests into the "once a day" category, but run it with more iterations to get statistically significant results.

**Comment by lptr** [comment]
Looks promising! Why switch to using averages instead of median, though?

**Comment by oehme** [comment]
Because commons-math's documentation said that the test makes a statement about the confidence in a difference in the mean. But after reading some more online it seems that the median is much closer to what the u-test does. So I'll revert to the median value.

**Comment by lptr** [comment]
Can you point to the other sources you read up on? I'd be interested in reading them, too, and it might be a good idea to include some links in the Javadoc as well where relevant.

**Comment by oehme** [comment]
I used wikipedia as my main source, I just hadn't read the full article since my questions on its applicability were answered early. The comment about the median was much further down. The Javadoc already has a link to that article.

Running the full coordinator build seems to show some problems with reproducibility on our agents. E.g. there are tests with plenty of iterations that have a regression with 99% confidence, even though they were rebaselined yesterday. A visual check of the data series supports this, e.g. [this one](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/11753815:id/report-performance-performance-tests.zip%21/report/tests/clean-assemble-on-bigNative-with-local-cache.html) is clearly a bit slower across the board. I'll need a few more runs to see if there is a pattern or if this is random noise on the agents.

**Comment by oehme** [comment]
I tried a couple of things to make the full coordinator build more stable, including a few more iterations and a higher minimum confidence before we report a regression. Unfortunately, we still have runs where one version looks significantly slower than the other even though it isn't if you run it again later or on another agent. This mostly seems random, so I suspect some occasional background work on our agents is interfering with the tests. We'll have to address that first before we can get rid of retries.

I wonder if we should merge the better statistics anyway, but keeping the retries?

**Comment by lptr** [comment]
:+1: to merging whatever improvement we have already. It sounds pretty significant as it is.

**Pull request merged**
