### PR TITLE
Add GraalVM as a detectable JVM vendor

### LINKED ISSUE #15535: Add GraalVM as a JvmVendor
### Expected Behavior

Developers that use the new [JVM toolchain selection](https://docs.gradle.org/6.8/userguide/toolchains.html) feature might want to explicitly choose GraalVM for it's [polyglot features](https://www.graalvm.org/reference-manual/embed-languages/), and thus should be able to specify it to be the chosen JVM. While `ORACLE` will be supported as a [JvmVendorSpec](https://docs.gradle.org/6.8-rc-1/javadoc/org/gradle/jvm/toolchain/JvmVendorSpec.html) in Gradle 6.8, there is no `GRAAL_VM` value in [JvmImplementation](https://docs.gradle.org/6.8-rc-1/javadoc/org/gradle/jvm/toolchain/JvmImplementation.html), which would be the expectation.

### Current Behavior

There is no way to explicitly choose GraalVM as the JVM toolchain.

### Context

I'm trying to ensure in a Gradle build that GraalVM is used so its [polyglot features](https://www.graalvm.org/reference-manual/embed-languages/) can be used.

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #15535.

### Context

Several users already upvoted issue #15535, and [GraalVM](https://www.graalvm.org/) is becoming increasingly popular.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by sschuberth** [comment]
Should I provide a rationale in `architecture-test/src/changes/accepted-public-api-changes.json` why this trivial addition should *not* be marked as `@Incubating`?

**Comment by sschuberth** [comment]
@jjohannes can you also help me with getting this one merged? BTW, why did you remove the "contributor" label?

**Comment by jjohannes** [comment]
I passed this on to @bmuskalla who has more expertise on the toolchain topics.

The `contributor` label was removed altogether when consolidating labels in this repo. It has nothing to do with this PR specifically (it's gone from all PRs and issues because it provided no value to us anymore and was just noise).

**Comment by bmuskalla** [comment]
@sschuberth Thanks for the contribution. I've added a test and fixed some minor nits in surrounding code. And rebased, repushed as #16595 - I'll get that onto master with that PR. Thanks again for your effort

**Comment by sschuberth** [comment]
> @sschuberth Thanks for the contribution. I've added a test and fixed some minor nits in surrounding code. And rebased, repushed as #16595 - I'll get that onto master with that PR. Thanks again for your effort

I guess that should be https://github.com/gradle/gradle/pull/17108 😉 But thanks for fixing up my stuff! 😁

**Pull request closed without merging**
