### PR TITLE
Update gradle-profiler to 0.17.0-alpha12

### PR DESCRIPTION
**Pull request by asodja**

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle help

**Comment by asodja** [comment]
@bot-gradle test PerformanceTest

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by wolfs** [comment]
@bot-gradle help

**Comment by wolfs** [comment]
@bot-gradle PT

**Comment by wolfs** [comment]
@bot-gradle test PT

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
