### PR TITLE
Polish validation warnings

### PR DESCRIPTION
**Pull request by melix**
- Change remaining deprecation warnings to target Gradle 8 for removal
- Code cleanup
- A bit of polish

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test QFL

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
LGTM!

**Pull request merged**
