### PR TITLE
Merge release into master

### PR DESCRIPTION
**Pull request by jvandort**
Fix merge conflicts

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by ghale — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
The test did pass when I ran `@bot-gradle test this`: https://ge.gradle.org/s/utihyfa4hqnbi/tests/task/:kotlin-dsl-plugins:configCacheIntegTest/details/org.gradle.kotlin.dsl.plugins.dsl.KotlinDslPluginCrossVersionSmokeTest/can%20run%20with%20first%20version%20of%20kotlin-dsl%20plugin%20supporting%20Gradle%208_0?top-execution=1

I figured it might have been flaky even though I haven't seen a failure in the test history

**Pull request merged**
