### PR TITLE
enforce project dependency on conflict

### PR DESCRIPTION
**Pull request by idlsoft**
This change will prioritize a project dependency over module regardless of version

### CODE REVIEW

**Comment by pioterj** [comment]
Could you provide some context regarding this change? Why are you making it? Was is raised on [Gradle Developer List](https://groups.google.com/forum/#!forum/gradle-dev) or is there a [Jira issue](https://issues.gradle.org/secure/Dashboard.jspa) associated with it?

**Comment by idlsoft** [comment]
We have 3 git repositories: `common`,`moduleA`,`moduleB`
`moduleA` has a dependency on `common`
`moduleB` depends on both `common` and `moduleA`
Typically developers work on only one repo at a time and use binary dependencies
But it's also possible to use a special `settings.gradle` to work on 2 or more repos at a time.

The problem I was trying to solve is this:
I was working with `common` and `moduleB`.
`moduleB` depends on `common` directly and also transitively through `moduleA`. The version of `common` referenced by `moduleA` was higher, so I ended up with a binary dependency instead of a project one.

Now, normally the version in the source would be higher, but sometimes it can be the same, or in my case `'unspecified'` (we infer the version from git history, and only do it when the build needs to publish artifacts)

The suggested change should ensure that a project dependency always has priority over a binary one, regardless of version.
I'm not sure if this is the best implementation, but the intended behavior, I think, makes sense, so I'd like to see it in future versions.

**Comment by pioterj** [comment]
@idlsoft Thank for clarifying. This is indeed a surprising behavior and probably not what most users expect. Always using project dependencies is a more reasonable default. However making the change the way you proposed could break the behavior for users that depend on it. What we normally do in such cases is provide a way to use the old behavior. There a couple of ways that could be done. Would you be willing to take a stab at it? We could discuss this further on [Gradle Developer List](https://groups.google.com/forum/#!forum/gradle-dev).

**Comment by pioterj** [comment]
@idlsoft I just realized that you already started a thread of dev list. Let's follow up there.

**Comment by idlsoft** [comment]
I added an option to disable project dependency priority.
Btw, I see a build failure, but I'm not sure if it's related to what was changed.

**Comment by pioterj** [comment]
@idlsoft I don't think a simple property is what we want here. We should consider more fine-grained solution that would allow users to express the desired behavior for each dependency. It would be best to finalize the discussion on dev list before you make further changes. Let's discuss available options there.

**Comment by pioterj** [comment]
BTW, the build failure doesn't seem related to your changes.

**Comment by idlsoft** [comment]
I've never done it, so I'm not sure.
I did write down the permutations we discussed in `DependencyResolveRulesIntegrationTest`, they look like a little table there.

**Comment by eljobe** [comment]
@idlsoft We aim do have a very light-weight design process. Basically, in a separate pull request add a document to the [deisgn-docs](https://github.com/gradle/gradle/tree/master/design-docs) directory explaining why you're making (use cases,) what change you're making, the cases we need to test to make sure we aren't breaking anyone and any other details a reader would need to understand what's going on.

We'll circulate the design among the larger team and make sure people understand what's going on and then we'll come back and adjust this Pull Request with any changes needed based on that feedback. Thanks for taking this work on.

**Comment by wolfs** [comment]
I suppose this pull request can be closed since it has been superceded by #596 and #652. Do you agree?

**Comment by idlsoft** [comment]
Yes, those are the only ones still relevant

**Pull request closed without merging**
