### PR TITLE
Speed up dependency resolution

### PR DESCRIPTION
**Pull request by ljacomet**
This is a rework of #19491 to remove the problematic changes

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Review by bamboo — COMMENTED** [review]
@ljacomet, do you have an idea of how much we lose by reverting these changes?

**Comment by ljacomet** [comment]
No I do not. And we should also follow up to see how much we gain with the changes that made it in.

**Pull request merged**
