### PR TITLE
Experiment with summarizing failures of multiple test targets/suites

### LINKED ISSUE #20965: Link failing test tasks to containing targets and suites
This issue is to experiment with adding links from test tasks back to the target and suite which they are associated with (if there is one).

Maybe we can make the local output better with this information.
```E.g., "There were failing tests." -> 
Test suite 'integTest' has failing tests. 
JDK8 target PASSED 10/10
JDK11 target FAILED 8/10 
file://…
JDK17 target did not start.
```

### PR DESCRIPTION
**Pull request by tresat**
Update: the only remaining failing tests are now in `testing-native` and `configuration-cache`.
- Run the 2 new tests at the bottom of `TestSuitesIntegrationTest` to see examples of the results.

Fixes #20965

### CODE REVIEW

**Comment by big-guy** [comment]
@eriwen before we go too far down this path, will this impact the way GE classifies verification/non-verification failures?

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
This is on hold until Gradle 8.0 and will probably need more design consideration.

**Pull request closed without merging**
