### PR TITLE
Extract test-kit BaseGradleRunnerIntegrationTest into testFixtures

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Makes it possible for other projects to rely upon the TestKit `BaseGradleRunnerIntegrationTest` which allows tests to run against multiple versions of Gradle.

My particular use case is to enable writing tests more easily for the Gradle GitHub Dependency Extractor.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
@bot-gradle test this please

**Comment by JLLeitschuh** [comment]
@bot-gradle help

**Comment by JLLeitschuh** [comment]
@bot-gradle test QF

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Review by tresat — COMMENTED** [review]
LGTM

**Review by donat — COMMENTED** [review]
Although I don't mind this being changed, I have to mention that there are other cross-version integration test fixtures available in the build. Check the `CrossVersionIntegrationSpec` base class.

**Comment by JLLeitschuh** [comment]
Thanks @donat, I didn't know about `CrossVersionIntegrationSpec`. It looks like that test only support testing with the current version of Gradle and a previous version, not a variety of versions passed via the command line.

**Comment by JLLeitschuh** [comment]
@bot-gradle test and merge

**Comment by JLLeitschuh** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@JLLeitschuh from `CrossVersionTestInterceptor`'s javadoc:

> A test class can be annotated with {@link org.gradle.integtests.fixtures.TargetVersions} to specify the set of versions the test is compatible with, and {@link org.gradle.integtests.fixtures.IgnoreVersions} to specify the set of versions the
>  test should not be run for.

**Pull request merged**
