### PR TITLE
Make JavaVersion support JDK 11 and JEP-223

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

We've been bitten by `JavaVersion` for a long time. Now it happens again: #4515 . The best solution for this would be a value class similar to [JDK 9 Runtime.Version](https://docs.oracle.com/javase/9/docs/api/java/lang/Runtime.Version.html) and gradually replace all usage of `JavaVersion` to the new value class. However this can't be done in a short time, so for `4.7` I'd like to patch `JavaVersion` again to support JDK 11 version number. Also, the implementation is adjusted to be compatible with [JEP223](http://openjdk.java.net/jeps/223).

In short, JEP223 proposed a new way to present Java version. From Java 9, `java.version` system property becomes `$VNUM(\-$PRE)?` where `$VNUM` is `[1-9][0-9]*((\.0)*\.[1-9][0-9]*)*` (semantic versioning) and `$PRE` is `[a-zA-Z0-9]+`, which supersedes [the previous convention(e.g. 1.3.0_01)](http://www.oracle.com/technetwork/java/javase/versioning-naming-139433.html). 

Now the implementation are:

- Find `java.version` number.
- Truncate all ending neither-digit-nor-dot character. For example, `9.0.0.1-whatever` will become `9.0.0.1`
- Split and analyze the generated integer array, i.e. [9,0,0,1]
- If first number is not 1, take the first number as the major version; otherwise take the second number as the major version.

All major version higher than 11 will be treated as `UNKNOWN`.

### CODE REVIEW

**Comment by blindpirate** [comment]
@melix I don't quite understand, do you mean `JavaVersion.toVersion('9.0.0.1') == JavaVersion.JEP223_COMPATIBLE`? So what should `JavaVersion.toVersion('10.0.0.3')` be?  `JavaVersion.JEP223_COMPATIBLE` is a single instance and can't represent infinite version numbers.

**Comment by melix** [comment]
I mean that any version that we don't recognize yet, but follows the JSR-223 could be identified as such. It would have the same meaning as "unknown" today, the only difference is that we say we recognized the pattern, vs an exotic version number.

**Comment by blindpirate** [comment]
I'd admit `UNKNOWN` is a bad name and a bit misleading, this can be improved to `LATER`/`HIGHER`/`JAVA_X`(what IDEA does) or something like this.  But I don't think there should be a `JavaVersion.JEP223_COMPATIBLE` because it's kind of misleading too. Should `JavaVersion.JEP223_COMPATIBLE.isJava10Compatible()`? If yes, why? `9.0.0.1` is also JEP223-compatible, but obviously it's not Java10-compatible.

**Comment by melix** [comment]
I agree. What about `UNSUPPORTED`, to make it explicit we recognize it but do not officially support?

**Comment by blindpirate** [comment]
I don't like `UNSUPPORTED`. The term "Unsupported" usually refers to the Java version lower than minimum requirements for running Gradle, i.e. currently unsupported versions are Java1 ~ Java6, Gradle 5's unsupported version are Java1 ~ Java7. 

Actually I think for a while and still like `UNKNOWN` best... Let's put it aside @oehme WDYT?

> The most difficult part in programming is naming.

**Comment by oehme** [comment]
I think that "`Unknown` is Java 10 compatible" is wrong. If the version is really unknown it should fail to parse. I think that's what we already do and it's just the name of the constant that is misleading. Should probably be something like `RECOGNIZED_HIGHER` or similar.

**Comment by blindpirate** [comment]
Okay. So let's make it `VERSION_HIGHER`.

**Comment by oehme** [comment]
@melix This approach looks okay from my side, can you give it another review?

**Comment by lenborje** [comment]
Please note that Java 11 does not accept `-source 1.11`. It does accept `1.10` or `10`, `1.9` or `9` etc, but as of version 11, only `11`.

This makes builds fail since `sourceCompatibility=11` will be translated to `-source 1.11`.

So I believe JavaVersion should not use '1.11' as the internal string representation for version 11.

Tested with java 11-ea+4.

**Comment by blindpirate** [comment]
@lenborje Thanks, I believe we've already made it `11` instead of `1.11` in this implementation.

**Comment by eriwen** [comment]
@blindpirate @melix should we say that Gradle supports running Java 10 or 11 in the release notes/docs?

**Comment by oehme** [comment]
@eriwen That depends on whether we can get a patch release for ASM, as 6.1 contains a regression. @blindpirate will keep you updated.

**Comment by eriwen** [comment]
Okay, I trust you folks to add something to the release notes and let me know if anything changes here. Users will want to know if they can use Gradle with Java 10

**Comment by blindpirate** [comment]
@eriwen I've already asked ASM team to release a patch version for us https://gitlab.ow2.org/asm/asm/issues/317815 , however, if they can't make it before we release our `4.7RC`, I think we should let users know that we're still "pretending Java 10 is Java 9".

**Comment by bmuschko** [comment]
@blindpirate I don't think users actually care how it works as long as does work. ;-) The release note should just say _if_ we do support Java 10.

**Comment by blindpirate** [comment]
@bmuschko Oh yes. Have we met any problems with `PatchedClassReader` in all Java 10 test?

**Comment by bmuschko** [comment]
@blindpirate Not that I am aware of.

**Comment by blindpirate** [comment]
Thanks, so I believe we can say we support Java 10 completely.

**Comment by bmuschko** [comment]
@acourtneybrown Can you confirm that there was no more outstanding work for Java 10? You were looking at this recently.

**Comment by acourtneybrown** [comment]
@bmuschko - the only other item I had found when looking at Java 10 was needing to update the `cglib:cglib-nodep` dependencies to `cglib:cglib`.  The `-nodep` version was very old in some cases, and included a relocated version of an even older version of ASM.

**Pull request merged**
