### PR TITLE
Use the vanilla `kotlin-compiler-embeddable`

### PR DESCRIPTION
**Pull request by eskatos**
Before this PR the Gradle distribution contains a custom patched version of the `org.jetbrains.kotlin:kotlin-compiler-embeddable`. After this PR the vanilla artifact is used.

This removes complexity from the `gradle/gradle` build and reason of confusion from the Gradle distribution.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFR

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Review by bamboo — APPROVED** [review]
❤️

**Comment by eskatos** [comment]
Thanks for the review Rodrigo!

@bot-gradle test and merge

**Comment by lptr** [comment]
Yay! <3

**Pull request merged**
