### PR TITLE
Added the ability to turn off gradle testng listener

### PR DESCRIPTION
**Pull request by blestka**
Added the ability to turn off gradle testng listener, since

a. not everyone needs its report
b. it introduces HUGE performance issues (see https://issues.gradle.org/browse/GRADLE-3189)

To turn off gradle test report user needs to set testReportEnabled = false.

### CODE REVIEW

**Comment by blestka** [comment]
Well, I have a fix for [GRADLE-3189](https://issues.gradle.org/browse/GRADLE-3189), but I don't like it very much. I've described it here: https://groups.google.com/forum/#!topic/gradle-dev/L6-C2ZI1zIw. My point was to get rid of thousands of identical TestNGTestResultProcessorAdapter instances by overriding equals method in proxy invocation handler.

**Comment by mark-vieira** [comment]
The result we want to achieve is correct here, which is, don't create a bunch of duplicate listeners. We can discuss what the best way to accomplish this is, whether that be caching, overriding equals to eliminate duplicates or simply not adding duplicate listeners in the first place (my preference is for the latter).

Thanks for linking to the dev list topic here. I think we want to address that rather than merge this PR as-is.

**Comment by eriwen** [comment]
@blestka First off, thank you for taking time to contribute to Gradle. 

Addressing the performance problem directly is preferable because it also benefits those who do care about the TestNG reports. 

I think what you’ve done in [your suggestion to avoid duplicate listeners](https://groups.google.com/forum/#!topic/gradle-dev/L6-C2ZI1zIw) is a better starting place for resolving this issue. 

It would be massively helpful if you could:

- Collect any code samples you have demonstrating the problem
- Submit a new PR (including the samples) with changes to [TestNGListenerAdapterFactory](https://github.com/gradle/gradle/blob/master/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGListenerAdapterFactory.java) and tests in `testing-jvm/src/integTest` or in [TestNGListenerAdapterFactorySpec](https://github.com/gradle/gradle/blob/master/subprojects/testing-jvm/src/test/groovy/org/gradle/api/internal/tasks/testing/testng/TestNGListenerAdapterFactorySpec.groovy) that would help verify new behavior

This would allow us to more easily begin the process of performance testing and verification.

If that is acceptable to you, then we will pursue that solution and close this PR. Let us know right away if we can help you get started on the tests.

**Comment by blestka** [comment]
@eriwen, thanks for your reply! Will open the new PR today or tomorrow.

**Comment by bmuschko** [comment]
@blestka Thanks for your reply. We are looking forward to your PR. Are you still working on it? I haven't seen a new one coming in yet.

**Pull request closed without merging**
