### PR TITLE
Deprecate recognizing Boolean isFoo() as a property

### PR DESCRIPTION
**Pull request by big-guy**
Groovy 4 no longer recognizes these methods as properties.

You need to use either:
- boolean isFoo()
- Boolean getFoo()

fixes https://github.com/gradle/gradle/issues/22218

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by ghale — APPROVED** [review]
A few suggestions on the upgrading doc, but otherwise, this LGTM.

**Pull request closed without merging**
