### PR TITLE
Update tested AGP versions

### PR DESCRIPTION
**Pull request by eskatos**
from 8.1.1 to 8.1.4
from 8.2.0-beta06 to 8.2.2
from 8.3.0-alpha05 to 8.3.0-beta02
introducing 8.4.0-alpha06
bumping nightly

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Review by ov7a — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Review by lkasso — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test AST APT

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AFT AST APT

**Comment by eskatos** [comment]
@bot-gradle test AFT AST APT

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle merge

**Pull request merged**
