### PR TITLE
Expose root variant in ResolutionResult

### PR DESCRIPTION
**Pull request by jvandort**
There is no way to get the root variant of the root component from a ResolutionResult without looping through all varaints and finding the root variant with its display name.

This commit exposes the root varaint so that users do not need to rely on variant display names to begin traversing dependency graphs.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
Blocked by documentation added by https://github.com/gradle/gradle/issues/26007

**Comment by jvandort** [comment]
@bot-gralde test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
