### PR TITLE
Remove "optimization" that omitted -source and -target from javac

### PR DESCRIPTION
**Pull request by rjernst**
See
https://discuss.gradle.org/t/source-and-target-are-only-passed-to-javac-when-java-version-is-different-than-gradle-java-version/17235
and elastic/elasticsearch#18039

Note this is currently untested because the tip of master does not even compile in gradle...

### CODE REVIEW

**Comment by uschindler** [comment]
+1 to commit this. Otherwise Gradle will fail to invoke the compiler whenever a new version of Java comes out!

What is the reason for this strange check? Javac does not complain if you pass -source and -target with the same version it is running.

The bug is triggered by 2 issues:
- Gradle is not able to detect Java 9 correctly (it seems to detect is as Java 8). Maybe this is a Verona-Problem (new versioning scheme)
- Gradle uses the wrongly detected Java version to decide that it does not pass -source/-target (for no reason!)

**Comment by rjernst** [comment]
> Gradle is not able to detect Java 9 correctly (it seems to detect is as Java 8). Maybe this is a Verona-Problem (new versioning scheme)

This isn't actually true. In this case, in order to compile with java 9, we have org.gradle.java.home set to a java 8 home, and JAVA_HOME set to a java 9 home, and then override the executable for JavaCompile tasks to javac under JAVA_HOME (ie java 9). This is why gradle "thinks" it is java 8, and thus does not add the -source or -target to the javac flags.

**Comment by uschindler** [comment]
OK, thanks for clarification. So actually the problem is home-made: we pass a different JDK to the fork command, so Gradle does not know anything about it. So the optimization is falsely applied.

Nevertheless, the optimization is not needed - I see no reason to omit -source and -target if it matches current version. So please remove it.

**Comment by wolfs** [comment]
Please remove the unused import for JavaVersion in JavaCompilerArgumentsBuilder.java:20. You can run the Checkstyle-Checks yourself:
```
./gradlew languageJava:check
```

**Comment by rjernst** [comment]
@wolfs Done. However, even after syncing up with the tip of master, I am still unable to even compile (for reasons completely unrelated to my change, see output [here](https://gist.github.com/rjernst/f56b89c9806372bcd56c99da0596cde6) when running `languageJava:check`)

**Comment by rjernst** [comment]
>  I am still unable to even compile

Actually nevermind, forcing a clean off the tip of master works now...

I have a failure in `JavaCompileParallelIntegrationTest`. I will look more closely tomorrow.

**Comment by wolfs** [comment]
The test fails because we now pass the version of the JVM Gradle is running as source/target version to the forked Compiler - which in this test has a different version than the Gradle JVM.
Without your change no target/source information has been passed to the compiler.
Without your change, the following can happen: You explicitly set sourceCompatibility to 1.7, have the Gradle JVM running on a 1.7 jdk. But you specify a 1.8. JDK for Compilation. Then you would generate class files with sourceCompatibility 1.8 - which is completely unexpected.
This is also the problem you are experiencing.

This is a breaking change but we think it is the right way to go. Please fix the `JavaCompileParallelIntegrationTest` by setting 
```
sourceCompatibility = '1.5'
targetCompatibility = '1.5'
```
in org/gradle/api/tasks/compile/JavaCompileParallelIntegrationTest.groovy:73. If you have a better fix, go ahead.

Thanks for your efforts.

**Comment by uschindler** [comment]
> Then you would generate class files with sourceCompatibility 1.8 - which is completely unexpected.
> This is also the problem you are experiencing.

YES! Because of this we should fix the test. The change is not really a breaking one, because the task is documented to run javac with the given source/target combination - and the example with the Groovy JVM different than compiler VM breaks the expectations by the documentation, because it leads to unexpected results.

Uwe

P.S.: I am happy that Java 9 nukes the source/target difference finally - it is intended to make the new javac only have one setting left to set source and target compatibility together with more changes required for "real" cross compilation

**Comment by wolfs** [comment]
It is breaking for building in the following situation:
You set java home to java 5, but don't set source or target compatibility and you run Gradle with Java 8.  With this change we set source/target to 1.8, so the build breaks. Before that no source/target are set for the compiler, so it "works".

**Comment by uschindler** [comment]
OK, understand. So the "correct " fix would be dependent on the fact if the user has something set explicit! If the user did not specify any version (e.g., it stays "null"), we should not pass -source/-target (but also print a warning - like Maven does).

If the user explicitely sets source/target it should always be passed down. For this it does not matter which version gradle or the compiler fork is running on!

**Comment by wolfs** [comment]
Correct. But this is not so easy since org/gradle/api/plugins/JavaPluginConvention.groovy:133 returns the version of the Gradle-JVM if no source/target is specified.
So the current fix should be sufficient.

**Comment by rjernst** [comment]
@wolfs I pushed a commit with the fix you suggested. However, it had to be 1.6, as 1.5 is not allowed as a source/target version:

```
Source option 1.5 is no longer supported. Use 1.6 or later.
```

**Comment by wolfs** [comment]
Seems like Java 9 doesn't support source/target 1.5 and we need to run the test against Java 1.5 so 1.6 is not an option either. This means the test needs to be changed to use the correct Java Version for the jdk it is compiling against.

**Comment by wolfs** [comment]
I created a gist which shows one possible way to go: https://gist.github.com/wolfs/3601c445c9edf2d7125326e1ed23ea12

**Comment by rjernst** [comment]
Thanks @wolfs, your patch looks good. I applied it and pushed a new commit, check passes for me.

**Comment by wolfs** [comment]
Thank you for you contribution and your time for polishing this pull request.

**Pull request merged**
