### PR TITLE
JavaExec should support the ability to inherit standard streams, #1099

### PR DESCRIPTION
**Pull request by gnodet**
Any of the checked boxes below indicate that I took action:

- [X] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [X] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [X] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [ ] Before submitting a pull request, I started a discussion on the [Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev),
      the [forum](https://discuss.gradle.org/) or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I considered writing a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [ ] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by lacasseio** [comment]
We are hesitant to make such a change as there is a possibility that it breaks on certain scenario. Could you confirm if your change works with (`--daemon`) and without (`--no-daemon`) the daemon?

**Comment by bmuschko** [comment]
@gnodet Are you still interested in this PR? Would you mind responding to @lacasseio's comment?

**Comment by lacasseio** [comment]
I just confirm this isn't working with the following code. As discussed earlier, a better mechanic should be introduced in Gradle to allow user input from Java process embedded inside Gradle runtime JVM.

Main.java:
```
import java.lang.System;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        System.out.println("Main");
        Scanner s = new Scanner(System.in);
        s.nextLong();
    }
}
```

build.gradle:
```
apply plugin: "java"
apply plugin: "application"

mainClassName = 'Main'

run {
    inheritIO true
}
```

**Comment by gnodet** [comment]
Sorry, I missed the earlier comments.
I'm not only interested in the user input, but also access to the real terminal.  Of course the latest could only work if not using a daemon.
Fwiw, I get the example running in non daemon mode with the following:
```
run {
    inheritIO true
    standardInput System.in
}
```
The reason is that standardInput defaults to null, so the example obviously won't work without setting a propery value.

**Comment by mrsarm** [comment]
This looks a good way to avoid the issue from here https://github.com/gradle/gradle/issues/4982 , and it was closed just because it was not properly tested, could you reconsider the patch again?

@gnodet do you see another way to invoke `ProcessBuilder.inheritIO()` before the process is created?

**Comment by gnodet** [comment]
@mrsarm I'm not really a gradle user.  I was just trying to fix an issue that was reported on JLine: https://github.com/jline/jline3/issues/77

**Pull request closed without merging**
