### PR TITLE
Fix for transitive Ivy artifact exclusions

### LINKED ISSUE #3951: Ivy artifact excludes are no longer transitive
<exclude> tags within an ivy.xml targeting a specific artifact are not properly treated as transitive. I believe this is a regression, as it worked properly in 4.2 and seems to have been affected by the recent improved <exclude> caching.

### Expected Behavior

`<exclude artifact="my-cool-jar"/>` should exclude an artifact which is transitively pulled in from an indirect dependency. It is not sufficient to check only artifactExcludes here, since it doesn't include anty of the union / intersection inclusions. It would be sufficient to call `excludeArtifact` on each of the `otherExcludes` and nuke `artifactExcludes` entirely. https://github.com/gradle/gradle/blob/f2acd24b4b87b6b4c8c821497d6dba723403bb7d/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/excludes/ImmutableModuleExclusionSet.java#L110

### Current Behavior

Artifact excludes only apply to the direct dependency, and not any of its transitive dependencies. 

### Context

Ivy modules are unable to exclude artifacts from dependencies which are pulled in transitively.

### Your Environment

Gradle 4.4.1

### PR DESCRIPTION
**Pull request by bigdaz**
For efficiency, we collect separate lists of exclusions that apply to
modules and artifacts: these are applied at different phases of
dependency resolution. Previously, we were being too restrictive when
building the list of artifact excludes: we omitted composite exclusions
that may contain nested artifact exclusions.

All exclusions that _may_ exclude and artifact are now collected and
applied to determine the inclusion of a particular artifact.

Fixes #3951

### CODE REVIEW

**Comment by bigdaz** [comment]
@melix I've requested your review on this PR since you did most of the work in caching of excludes.
@oehme This PR addresses a regression introduced in v4.4. Would you consider including this in 4.5-rc-1?

**Comment by melix** [comment]
It's worth noting that the failing performance test is the same one which fails on my pull request too: https://github.com/gradle/gradle/pull/4045

@oehme do you think it could be related to your changes?

**Comment by oehme** [comment]
I'm afraid you simply got unlucky with the performance test. The switch to bare metal agents will hopefully help make these kinds of outliers disappear.

I'm fine with including this in 4.5 RC2.

**Comment by bigdaz** [comment]
Cherry-picked to `release` for 4.5-rc-2. b0511840bb1aeba04b9f8ac475947c2d9ddb052c

**Pull request closed without merging**
