### PR TITLE
Remove ImmutableJavaForkOptions

### PR DESCRIPTION
**Pull request by asodja**
Since they are not needed anymore.

This addresses https://github.com/gradle/gradle/pull/30590#discussion_r1796616697

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Review by Hjhj789 — COMMENTED** [review]
asodja/remove-immutablejavaforkoptions

**Review by lptr — APPROVED** [review]
LGTM.

:tada: 272 lines of unnecessary complexity removed!

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test this APT

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this APT

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test this APT

**Comment by asodja** [comment]
@bot-gradle test this APT

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle clean

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test APT

**Pull request merged**
