### PR TITLE
Update the user guide section about supported builds for build comparison

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by eriwen** [comment]
@Vampire thanks for the PR. I don't see your name in our CLA system. Have you [signed one](http://gradle.org/contributor-license-agreement/)?

**Comment by Vampire** [comment]
@eriwen there were times where each version of Gradle had at least one contribution from me, so yes, I signed one already. ;-)

**Comment by Vampire** [comment]
To be exact, you have it since 10.07.2014 as requested by @alkemist

**Comment by eriwen** [comment]
@Vampire sorry about the confusion — We changed the system that manages CLAs a couple years ago. We're all good here.

**Comment by eriwen** [comment]
This update looks accurate. Thank you @Vampire for your contribution!

**Comment by Vampire** [comment]
@eriwen You are welcome. Btw., I should be mentioned as contributor this time again, shouldn't I? ;-)

**Comment by eriwen** [comment]
@Vampire Indeed :) https://github.com/gradle/gradle/commit/446468213543e32a0ce1bce0bbedabcfe925c572

**Comment by Vampire** [comment]
Great, thanks. One more issue though, you link to #1266, but the text says #1029 ;-)

**Comment by eriwen** [comment]
@Vampire Argh, stupid typo. Fixed now.

**Pull request merged**
