### PR TITLE
Don't cache `readResolve` methods when writing to the configuration cache

### PR DESCRIPTION
**Pull request by bamboo**
And definitely don't bother making them accessible.

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by adammurdoch** [comment]
It would be good to include some context about the "why" as well as the "what" eg an explanation in the description of what the use case is, or perhaps a test case that describes why the change is necessary.

**Comment by bamboo** [comment]
It's just an optimisation. After the encoding is resolved the method is no longer used and it was being held for no reason.

**Comment by adammurdoch** [comment]
got it, thanks for the details

**Pull request merged**
