### PR TITLE
JGit upgrade

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by cobexer — APPROVED** [review]
LGTM!

**Review by big-guy — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle merge

**Comment by ljacomet** [comment]
Failures look like flakiness in perf tests, retrying merge

**Comment by ljacomet** [comment]
@bot-gradle merge

**Pull request merged**
