### PR TITLE
GRADLE-1945 IDE plugins do not warn that some deps are unresolved

### PR DESCRIPTION
**Pull request by msteiger**
This PR aims to fix [GRADLE-1945](https://issues.gradle.org/browse/GRADLE-1945). It should work equally well for IntelliJ and eclipse. I've tested it with "usual" configurations and a custom one. Also, manipulation through `plusConfigurations` works as expected. The following SSCCE illustrates the effect of the proposed changes:

```gradle
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'

repositories {
    mavenCentral()
}

configurations {
    myConfig
}

dependencies {
    myConfig group: 'myGroup', name: 'myCustomName', version: '1.0'
    runtime  group: 'myGroup', name: 'myRuntimeName', version: '1.0'
    compile  group: 'com.google.guava', name: 'guava', version: '18.0'

    eclipse {
        classpath {
            plusConfigurations += [ configurations.myConfig ]
        }
    }
}
```

Running the eclipse and idea task now reports the missing/unresolved dependencies:

```bash
$ gradleInst/bin/gradle eclipse idea
:eclipseClasspath
Could not resolve: myGroup:myRuntimeName:1.0 (configuration ':testRuntime')
Could not resolve: myGroup:myCustomName:1.0 (configuration ':myConfig')
:eclipseJdt
:eclipseProject
:eclipse
:ideaModule
Could not resolve: myGroup:myRuntimeName:1.0 (configuration ':runtime')
Could not resolve: myGroup:myRuntimeName:1.0 (configuration ':testRuntime')
:ideaProject
:ideaWorkspace
:idea
```

I've signed the CLA using the online form. Thus, it should be available for you already.

### CODE REVIEW

**Comment by alkemist** [comment]
Thanks for the contribution @msteiger.

There's a few things we'll need to sort out here:

1. We'll need at least some integration test coverage
2. Doing the logging in the extractor isn't quite right, it should happen a layer up when the data is actually being used
3. We should be able to provide a better error message via `UnresolvedIdeRepoFileDependency.problem`

As for (2), this could be some construct that the IDEA and Eclipse both use to do _something_ with the failed dependencies, where the implementation of the something is the logging.

**Comment by msteiger** [comment]
Thanks for your feedback @alkemist. I addressed your concerns in three individual commits (in reverse order).

The exception is now stored in `UnresolvedIdeRepoFileDependency`. I added a handler for unresolved dependency reports that is used in `EclipseClasspath` and in `IdeaModule`. The integration tests checks the log output of the SSCCE mentioned above.

**Comment by msteiger** [comment]
Is there anything still missing?

**Comment by msteiger** [comment]
@alkemist I rebased my changes on top of the latest develop branch, since commit c3bb8f01c5bed7d6536 introduced two small merge conflicts.

**Comment by oehme** [comment]
Thank you for the contribution :+1:

**Pull request merged**
