### PR TITLE
Move archive operations to their own service

### PR DESCRIPTION
**Pull request by eskatos**
Follow up to https://github.com/gradle/gradle/pull/13280

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFM

**Comment by eskatos** [comment]
@bot-gradle test RFM

**Comment by lacasseio** [comment]
It's nice to split things up and the comment about Adam regarding ProjectLayout is valid. For what it's worth, having a lot of 2 methods services can take a toll of plugin development as injection is not a zero overhead. It is much smaller thanks to the decoration and ObjectFactory but not easy to follow for plugin authors.

I still believe this new service is probably a good fit. The comment is mostly a general comment around service and injection for plugin authors.

**Comment by eskatos** [comment]
@bot-gradle test RFM

**Pull request merged**
