### PR TITLE
move DEFAULT_JVM_OPTS after APP_HOME

### PR DESCRIPTION
**Pull request by fkowal**
to enable usage of APP_HOME in DEFAULT_JVM_OPTS

in extension

### CODE REVIEW

**Comment by pioterj** [comment]
Thank you for the pull request. Would you mind signing a [contributor license agreement](https://gradle.org/contributor-license-agreement/)? This is required for legal reasons before any code contributions can be accepted into the Gradle codebase.

**Comment by fkowal** [comment]
CLA signed

**Comment by andrejczyn** [comment]
This change gives an opportunity to use application path in java opts. For example for include java gent from classpath, like in our case in https://github.com/allegro/newrelic-gradle-plugin

**Comment by lptr** [comment]
@fkowal Thank you for the work you did on this.

Is there a reason why `APP_NAME` and `APP_BASE_NAME` are now available in `DEFAULT_JVM_OPTS` on Windows, but not on Unix? Would it make sense to modify the Unix template in a similar fashion to the Windows one, and only move `DEFAULT_JVM_OPTS` below  `APP_HOME`?

Could you also add a test case in `ApplicationPluginIntegrationTest`? If using `APP_HOME` in `DEFAULT_JVM_OPTS` is a feature we want to support, we'll need to make sure it doesn't go away in the future.

**Comment by fkowal** [comment]
sure i'll add a test and look into the difference between windows an unit script and respond later

**Comment by fkowal** [comment]
@lptr as requested i added a test, let me know if it meets your standards
i also moved the APP_NAME, APP_BASE_NAME to make unix script consitent with windows script

**Comment by breskeby** [comment]
Hey I merged your pull request manually and updated the integration test a bit. In integration tests we basically don't care of the position of APP_HOME but verifying the use case you described is solved.
thanks again for the work! Happy to get more pull requests from you.

**Comment by fkowal** [comment]
Great idea with that test. Thank you.

**Pull request closed without merging**
