### PR TITLE
Let FileCollection ElementsProvider expose a changing execution time value when appropriate

### PR DESCRIPTION
**Pull request by eskatos**
See https://github.com/gradle/gradle/issues/17542

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Review by bamboo — APPROVED** [review]
🎉

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
