### PR TITLE
Fix scala incremental compilation [backport 7.x]

### PR DESCRIPTION
**Pull request by ljacomet**
Properly testing the fix required backporting more test changes.

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by ov7a — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
