### PR TITLE
Remove CompileView attribute from derived Maven variants

### PR DESCRIPTION
**Pull request by jvandort**
Due to some weirdness with the kotlin multiplatform plugins, there is ambiguity between compileElements and
one of the multiplatform-created variants. The only way to avoid this ambiguity is to disable the
CompileView attribute schema compatibility rule.

This rule is required to allow us to select the derived maven api variant which declared the java-internal
compile view, while we are requesting the java-api compile view. To allow us to continue selecting this variant,
without the compatibility rule, we need to remove the attribute from the derived variant.

Fixes https://github.com/gradle/gradle/issues/22952

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
