### PR TITLE
Move `Either` data type to newly introduced project `data-structures`

### PR DESCRIPTION
**Pull request by bamboo**
So we can have a Java 8 compatible project for common data structures.

A followup to #16612.

### CODE REVIEW

**Review by melix — APPROVED** [review]
Can I suggest moving `Try` and `Lazy` there?

**Comment by bamboo** [comment]
> Can I suggest moving `Try` and `Lazy` there?

Yes, although that means the relationship with `base-services` might need to be inverted, which seems to make sense.

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by bamboo** [comment]
@bot-gradle test RFM

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by lptr** [comment]
Yay for having a place for these now! @wolf I think we should consider moving `ChildMap` here, too.

**Pull request merged**
