### PR TITLE
Refine non-empty directory error messages

### PR DESCRIPTION
**Pull request by blindpirate**
Print 2 files in the non-empty directory to help troubleshooting.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Review by wolfs — COMMENTED** [review]
Looks like I forgot to submit my review :(

**Pull request merged**
