### PR TITLE
Update test-distribution plugin to version 2.0-rc-7

### PR DESCRIPTION
**Pull request by snoopcheri**
Compared to 2.0-rc-5 and 2.0-rc-6 it adds the following:
* fixes sporadic NPE when TD processes a message from a disconnected agent
* single test execution (eg from the IDE) is optimized
* no longer sending back empty output files
* session information is reported
* debug port logging is visible again

Manual tests on local machine:
* `./gradlew depMan:embeddedIntegTest -DenableTestDistribution=true -Pgradle.internal.testdistribution.writeTraceFile=true` ✅ (https://ge.gradle.org/s/f4hp2o4dein4e)
* `./gradlew clean dependency-management:configCacheTest -DenableTestDistribution=true -Pgradle.internal.testdistribution.writeTraceFile=true` ✅ (https://ge.gradle.org/s/rgrktexu7a7em)

### CODE REVIEW

**Comment by snoopcheri** [comment]
@bot-gradle test rFM

**Comment by snoopcheri** [comment]
@blindpirate The three smoke tests up there are pending since several hours and I don't see anything running on TeamCity. Do you know what could have happened there?

**Review by blindpirate — APPROVED** [review]
LGTM, please ignore that pending change. It was some mistake by the bot. I've fixed on latest master.

**Comment by snoopcheri** [comment]
Discussing this with @blindpirate indicates that the TeamCity configuration got updated to JDK 16 yesterday but the gradle-bot was not updated yet. Bo will update that bot now and I can merge this PR.

**Pull request merged**
