### PR TITLE
Persist distributed performance test result

### PR DESCRIPTION
**Pull request by blindpirate**
Previously, we generated scenario list file for scheduling the worker builds and
result json for generating report, then deleted them. Now we put these files
under html report dir so we can check these files in TeamCity artifact page
to help us understand the build.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
See a sample build: https://builds.gradle.org/viewLog.html?buildId=37786256&buildTypeId=Gradle_Check_PerformanceTestCoordinator&tab=artifacts#%2Freport-performance-performance-tests.zip

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by blindpirate** [comment]
Thanks @wolfs !

**Pull request merged**
