### PR TITLE
Make 'Factories' final closed class

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Minor change to prevent cognitive dissonance when looking at the class.

### CODE REVIEW

**Comment by lptr** [comment]
Why do this for this specific class? We typically don't seal our classes like this, or prevent instantiation. (I also don't know why this class was marked `abstract`.)

**Comment by JLLeitschuh** [comment]
It's a static utility class. There's really no need for it to be instantiated.

I'm simply following 'Effective Java: Item 4: Enforce noninstantiability with a private constructor'

**Comment by lptr** [comment]
What problem are we trying to fix here? I don't recall accidental instantiation of utility classes being a major problem. Feels like we are adding unnecessary boilerplate unless there is a good reason to do it. If we do have a good reason (=a problem to fix), then we should do it for all similar classes as well.

**Comment by JLLeitschuh** [comment]
The problem I was trying to fix here was purely a sense of confusion-in-the-moment I had looking at this class while I was modifying this class as a part of a different change. I didn't end up needing that larger change. Instead of trying to roll this change into another PR that was unrelated, this is my attempting to break it out into its own independent PR. I'm not really looking to make a sweeping change of the larger codebase at this point. I more saw this change as a minor bit of sweeping up in a place while I was already looking at the code.

**Pull request merged**
