### PR TITLE
Increase timeout for HTTP timeouts and assign system properties to internal namespace

### PR DESCRIPTION
**Pull request by bmuschko**
### Context

See https://github.com/gradle/gradle/issues/3370 for more information

### CODE REVIEW

**Comment by cdancy** [comment]
Sorry to hijack this PR but we've been waiting for this functionality for quite sometime now. Is the proper way to take advantage of these properties done in the normal fashion?

Via gradle.properties
```
systemProp.org.gradle.internal.http.connectionTimeout=600000
```

**Comment by bmuschko** [comment]
@cdancy The system property isn't meant for consumption by end users. We only use it decrease the execution time when running our integration tests for that functionality. There's nothing stopping you from using it though please be aware that it is internal only (like an internal API). We also might lock that down in the future.

**Comment by cdancy** [comment]
@bmuschko gotcha. You guys did document it in the release notes, giving the impression that perhaps end-users could take advantage of it, but I noticed no example/implementation was given as to how to take advantage of it :)

I'll put a note in our docs stating as much. Thanks.

**Comment by bmuschko** [comment]
@cdancy Which release notes are you referring to? I don't see it here: https://docs.gradle.org/4.3/release-notes.html#timeouts-for-http/https-requests

**Comment by cdancy** [comment]
@bmuschko that's actually what I was referring to. From my point of view, if this were an internal feature only, I would not have expected that to be in the release notes at all.

**Comment by bmuschko** [comment]
@cdancy Maybe it would have been better to put it under "Potential breaking changes". Either way it's a change that directly affects users and therefore needs to have a prominent place in the release notes (even if you can't configure the behavior). I thought you were talking about the system properties specifically.

**Comment by cdancy** [comment]
> I thought you were talking about the system properties specifically.

@bmuschko I am :) Our hope is that by defining those properties, much like I did above, we'd be able to increase the timeout of various gradle/http related use-cases. For example we might see failures when attempting to download dependencies because an Artifactory instance is under heavy load and can't respond in a timely fashion. Can those properties be set like I noted above and would this be a valid use-case for such a thing?

**Comment by bmuschko** [comment]
@cdancy Sure thing!

**Pull request merged**
