### PR TITLE
Use test preconditions in `:kotlin-dsl*` tests

### PR DESCRIPTION
**Pull request by eskatos**
Instead of JUnit `assume`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by hegyibalint — APPROVED** [review]
Awesome work, thanks for the migration 🎉

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
