### PR TITLE
Remove misc deprecated classes and methods in core module

### PR DESCRIPTION
**Pull request by bmuschko**
My assumption for `org.gradle.util.Clock` is that it should be replaced by `org.gradle.internal.time.Clock` where exposed in an API. All APIs I touched were internal APIs. External consumers will not be able to use "public" API `org.gradle.util.Clock` as the class was removed. @bigdaz might have more info here as he added the deprecation.

### Gradle Core Team Checklist
- [x] Verify implementation
- [x] Verify test coverage and CI build status

### CODE REVIEW

**Comment by bigdaz** [comment]
I don't think `org.gradle.util` is part of the public API is it?

From memory, I think that `org.gradle.util.Clock` was used by an earlier version of the build scan plugin, which is why we deprecated rather than simply removing it.

**Comment by bmuschko** [comment]
@bigdaz Thanks for the background information.

@w25r Thanks for the review.

**Comment by bmuschko** [comment]
Reverted the following removals to due the fact that the build scan plugin is using the API:

https://github.com/gradle/gradle/commit/bcf9e4f745500ab7ecdc9e02a34c0cfdd0c397d0
https://github.com/gradle/gradle/commit/0a0c0332f7ca2c430b5baf2efe17c88246ad96a1

**Comment by bmuschko** [comment]
> From memory, I think that org.gradle.util.Clock was used by an earlier version of the build scan plugin, which is why we deprecated rather than simply removing it.

Just talked to Francois. The latest build scan plugin is still using `BuildRequestMetaData.getBuildTimeClock()` which returns the deprecated `Clock` class. We'll have to introduce a replacement method that returns the new `Clock` class before we can remove it.

**Pull request merged**
