### PR TITLE
Allow build operation listeners to log

### PR DESCRIPTION
**Pull request by ldaley**
This change moves build operation listening out of the standard listener infrastructure, to remove serialisation guarantees. As logging output now causes build operation notifications, whenever a build operation listener logged something it would fail due to the listener manager blocking overlapping signals.

By moving build operation listening out, overlapping and concurrent signals are now allowed.
This places more responsibility on listener implementations (e.g. thread safety), but there are few and they are all internal.

CI: https://builds.gradle.org/project.html?projectId=Gradle&tab=projectOverview&branch_Gradle=ldaley%2Foverlapping-build-operation-notifications

### CODE REVIEW

**Comment by ldaley** [comment]
@oehme @adammurdoch the underlying problem here is blocking build scans and @eskatos. If possible, I'd like to prioritise getting to a mergeable state and refining subsequently.

**Comment by oehme** [comment]
Doesn't this create a high chance of deadlock between the two infrastructures? We should add some concurrency tests proving it works.

Have you considered allowing reentrant notifications instead? I'm afraid I'm not deep enough into this problem to tell whether this is a good solution or not. If it works (see my concerns above) I guess we can merge it and reconsider later.

**Comment by ldaley** [comment]
@oehme this makes build operation listeners reentrant. It doesn't increase the risk of deadlock, AFAICT. Making `ListenerManager` bound listeners reentrant would be a bigger, breaking, change.

What kind of concurrent testing do you have in mind?

**Comment by ldaley** [comment]
I'm going to merge to unblock.

**Comment by oehme** [comment]
I thought this could lead to a situation where there could be one thread logging, which would then result in a build operation and there might be another thread already processing a build operation and logging as part of that processing, potentially creating a deadlock. Is this not possible?

**Comment by ldaley** [comment]
No, it's not now. It was before #4661.

There is a test for this: https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/internal/operations/logging/LoggingBuildOperationProgressIntegTest.groovy#L261

Adapting logging events to build operations and observing build operations are both now reentrant, and neither use `ListenerManager`.

**Pull request merged**
