### PR TITLE
Limit ourselves to /bin/sh

### PR DESCRIPTION
**Pull request by alexproca**
Thank you very much for your contribution. We highly appreciate the time
and effort you put into pull request. Before you submit the pull request,
please review the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).

Make sure you check the following boxes.

For all changes:

- [x] Sign the [Gradle CLA](http://gradle.org/contributor-license-agreement/).

For all non-trivial changes that modify the behavior or public API:

- [x] Before submitting a pull request, you started a [discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gradle-dev/Hex2dyYyBCE/A55FeEQCAAAJ) on the
[Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev)
or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [x] You considered writing a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. You can find [samples](https://github.com/gradle/gradle/tree/master/design-docs)
in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [ ] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
you ran a build on your local machine via the command `./gradlew quickCheck`
and the tests for the modified module.
- [x] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

Some systems do not have bash installed. For this reason unixStartScript.txt should be /bin/sh compatible. It seems that only incompatibility was using arrays from line 155 onwards so I replaced use of arrays with some variable substitution.

### CODE REVIEW

**Comment by breskeby** [comment]
Hey Alex, thanks for the contribution. Unfortunately your changes break our integration tests as you can check yourself at https://builds.gradle.org/viewLog.html?buildId=741834&tab=buildResultsDiv&buildTypeId=Gradle_PullRequest_LinuxJava17withSanityCheck Would you mind looking into this? We need these tests to pass to verify Gradle behaves as expected. Thanks and cheers,
René

**Comment by alexproca** [comment]
Fixed it! 

I forgot the script passes first through a template engine and forgot to comment the $ sign in front of $JVM_OPTS thus groovy tried to find this property and failed. The integration tests should be ok now. regarding this incident.

**Comment by breskeby** [comment]
Hey Alex,
there are still unit and integration tests failing with your change. check https://builds.gradle.org/viewLog.html?buildId=743010&tab=buildResultsDiv&buildTypeId=Gradle_PullRequest_LinuxJava17withSanityChec

**Comment by bmuschko** [comment]
@alexproca Thanks for the additional fixes. There're still some [failing tests](https://builds.gradle.org/viewLog.html?buildId=759192&tab=buildResultsDiv&buildTypeId=Gradle_PullRequest_LinuxJava17withSanityChec). Would you mind looking into those?

**Comment by alexproca** [comment]
Hi @bmuschko!  I'm working to solve those too. 

I ran `./gradlew iT` on my machine and did not catch those tests.

**Comment by jaredsburrows** [comment]
@alexproca Have you fixed the conflicts?

**Comment by alexproca** [comment]
@jaredsburrows conflicts fixed ! but still some tests failing

**Comment by wolfs** [comment]
@alexproca: There has been no activity on this PR for one month. Are you still interested in working on this?

**Comment by alexproca** [comment]
@wolfs I would like to have it done but the change is impacting the gradle distribution itself and it triggers many failures in tests run on CI. I cannot reproduce this failures myself. In order to finish it I would need some support from someone in the gradle team to help me understand test failures.

**Comment by wolfs** [comment]
How did you try to reproduce these tests? From the command line you can do for example
```
./gradlew plugins:integTest --tests "*ApplicationPluginIntegrationTest"
./gradlew wrapper:integTest
```

Is this enough information for you or do you need some more guidance?

**Comment by wolfs** [comment]
It looks like that when running the Gradle wrapper script with `--gradle-user-home "some dir"` then this does not work. A test exhibiting this behaviour is `WrapperChecksumVerificationTest`.  Strangely for me it works from the IDE but fails on the command line. Any ideas from your side? It seems to be related to the change in `unixStartScript.txt`, since when reverting those changes the test again works from the command line.

**Comment by wolfs** [comment]
@alexproca : Did you have time to look into this? Do you need further guidance?

**Comment by bmuschko** [comment]
@alexproca Hi, Alex. Did you have chance to look into the failing test?

**Comment by alexproca** [comment]
Hi guys. It seems the environment variable expansion for this variables `\$DEFAULT_JVM_OPTS \$JAVA_OPTS \$APPLICATION_OPTS` is causing troubles. Actually this is the reason bash arrays were used in the first place. I'm thinking of an awk script that can concatenate the content of these variables.

**Comment by wolfs** [comment]
@alexproca `awk` should be fine. Ubuntu migrated from `bash` to `sh`, perhaps some information [here](https://wiki.ubuntu.com/DashAsBinSh) can help you.

**Comment by jjohannes** [comment]
I have investigated this more and I think a good plain solution is to escape the application arguments and JVM options one after another using `$@` and store each as one string.

Something like this:
```
# Escape application args
for s in "\${@}" ; do
    s="\""\$s"\""
    APP_ARGS=\$APP_ARGS" "\$s
done

# Escape and collect JVM options
set -- \$DEFAULT_JVM_OPTS
for s in "\${@}" ; do
    s="\""\$s"\""
    JVM_OPTS=\$JVM_OPTS" "\$s
done
set -- \$JVM_OPTS
for s in "\${@}" ; do
    s="\""\$s"\""
    JVM_OPTS=\$JVM_OPTS" "\$s
done
set -- \$${optsEnvironmentVar}
for s in "\${@}" ; do
    s="\""\$s"\""
    JVM_OPTS=\$JVM_OPTS" "\$s
done
```
And then use this execution command (mix between original and new version):
```
eval "\$JAVACMD" "\$JVM_OPTS" <% if ( appNameSystemProperty ) { %>"-D${appNameSystemProperty}=\$APP_BASE_NAME" <% } %>-classpath "\"\$CLASSPATH\"" ${mainClassName} "\$APP_ARGS"
```
For that part this test would need adjustment again (2 occurrences):
https://github.com/gradle/gradle/pull/621/files#diff-7193b85bfb11e9658cebe0b527f463a0R66

Furthermore we should remove remaining **[[**,**]]** and **==** from the following line to conform to POSIX standard (use single character versions of those instead):

https://github.com/alexproca/gradle/blob/e4135019b30a74b34c23352ee05b1526c0648244/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt#L158

@alexproca would you mind to have a look at this and check if it works for you? And if yes, incorporate these changes. Then we should be able to go forward with integrating this. Thanks a lot.

**Comment by jjohannes** [comment]
Thank you @alexproca for your contribution! This has been integrated now and will be part of the Gradle 3.2 release.

**Comment by bmuschko** [comment]
@jjohannes Can you please create an internal review via Crucible and link to from here?

**Comment by jjohannes** [comment]
Internal Review: https://code-review.gradle.org/cru/REVIEW-6235

**Comment by ricard0javier** [comment]
Great guys, small features like this one make people a bit more open to use this great tool. Good job

**Pull request merged**
