### PR TITLE
Update Gradle Enterprise plugin to 3.8

### PR DESCRIPTION
**Pull request by guylabs**
We should merge this **after** ge.gradle.org is updated to Gradle Enterprise 2021.4.

### CODE REVIEW

**Comment by guylabs** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by guylabs** [comment]
@bot-gradle test and merge

**Comment by guylabs** [comment]
@bot-gradle cancel

**Comment by guylabs** [comment]
@bot-gradle test and merge

**Pull request merged**
