### PR TITLE
Update configuration cache docs to reflect recent changes

### PR DESCRIPTION
**Pull request by mlopatkin**
This commit covers ValueSource improvements and prefix-based filtering of system properties and environment variables.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Comment by mlopatkin** [comment]
I'll also update javadoc for the `ValueSource` to reflect the fact that inputs aren't tracked inside the `obtain()` method.

**Review by bamboo — APPROVED** [review]

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
