### PR TITLE
Expose dynamic data only via Tooling API

### PR DESCRIPTION
**Pull request by donat**
Fixes https://github.com/gradle/gradle-private/issues/3952

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test RFM

**Review by hegyibalint — APPROVED** [review]
Looks nice!
🤔 I do wonder: how does the test worker communicate with the daemon? Will the `gson` dependency be present there?

**Comment by donat** [comment]
There's gson dependency between the two: the worker writes the json to a file. Then, the file is read by the daemon separately. Check `ValidationProblemSerialization` for details.

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle test and merge

**Pull request merged**
