### PR TITLE
Restore cacheability of ScalaCompile

### PR DESCRIPTION
**Pull request by oehme**
This was broken by adding the current JVM's absolute path to CompileOptions.executable
I can't tell why this change was made, as all the tests are passing without this line.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
@bmuskalla FYI since you introduced this change

**Comment by bmuskalla** [comment]
This used to be required as the compiler option had no default anymore with the introduction of toolchains. But I think we changed that around once we fixed all other places. Thanks for catching.

**Comment by bmuskalla** [comment]
Would you mind adding a test case for that as well?

**Comment by oehme** [comment]
A real integration test of this is hard, since it would need two Java installations of the same version, but in different directories. The unit test on the other hand feels almost too trivial (asserting that options.executable==null by default).

**Comment by oehme** [comment]
Yep, that works and ensures Java home relocatability for all tasks.

**Comment by oehme** [comment]
Okay, finally got it working in all tests - Turns out our copy function didn't work with the symlinked Java homes on Windows.

This is ready for another look.

**Comment by oehme** [comment]
Ping :)

**Review by bmuskalla — COMMENTED** [review]
@oehme I'm sorry for the late response here, was out for some time and working through my backlog. The change looks good to me, thanks for doing this!

**Comment by bmuskalla** [comment]
@bot-gradle test and merge

**Pull request merged**
