### PR TITLE
Don't trigger wrapper download when TAPI client disconnects

### LINKED ISSUE #15405: GradleConnector#disconnect can trigger undesirable download of a distribution
### Expected Behavior

When a TAPI client is shutting down, TAPI should not need to download a Gradle distribution to try to stop daemons.

### Current Behavior

When a TAPI client is shutting down, TAPI downloads the full Gradle distribution. 

### Steps to Reproduce 

Reported to JetBrains: https://youtrack.jetbrains.com/issue/IDEA-256542

### PR DESCRIPTION
**Pull request by donat**
Fixes #15405

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test QuickFeedbackLinux

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
Apart from the dev12 network issues, `ToolingApiRemoteIntegrationTest.calling disconnect on existing connection does not re-trigger wrapper download` seems to be failing as well.

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
