### PR TITLE
Use correct signature for Test::useJunit

### LINKED ISSUE #2675: org.gradle.api.tasks.testing.Test::useJunit does not have correct type signature
### Expected Behavior

`org.gradle.api.tasks.testing.Test::useJunit` should have have the signature:
```java
public void useJUnit(Action<JUnitOptions> testFrameworkConfigure)
```

This same problem exists with:
```
org.gradle.api.tasks.testing.Test::useTestNg
```

### Current Behavior

Currently it has the signature:
```java
public void useJUnit(Action<? super TestFrameworkOptions> testFrameworkConfigure)
```

### Context

In order to configure the `JUnitOptions` in Kotlin you need to do this:
```kotlin
useJUnit {
    this as JUnitOptions
    excludeCategories("edu.wpi.first.shuffleboard.app.NonHeadlessTests")
}
```

### Steps to Reproduce (for bugs)

Try using this code in any Kotlin project that has the test task configured:
```kotlin
tasks.withType<Test> {
    useJUnit {
        // The line below this won't compile.
        excludeCategories("edu.wpi.first.shuffleboard.app.NonHeadlessTests")
    }
}
````

### Your Environment

 * Build scan URL: 

Gradle version `4.1` but this also exists in `4.0.2`.

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #2675 

### Context

#2675

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [x] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Any updates on this? Anything else I need to do?

**Comment by JLLeitschuh** [comment]
@bamboo You have a moment to take a look at this?

**Comment by bamboo** [comment]
I'll take a look.

**Comment by bamboo** [comment]
Merged via 4d78bb570b03ec97bd643f4aeabbb9f2c8f85c60.

Thanks, @JLLeitschuh!

**Pull request closed without merging**
