### PR TITLE
Update ASM 6.1 to 6.1.1 to fix a regression

### PR DESCRIPTION
**Pull request by eriwen**
### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eriwen** [comment]
Branch build passed. https://builds.gradle.org/viewLog.html?buildId=11865883&tab=queuedBuildOverviewTab — if you folks approve you can merge ASAP before branching

**Comment by blindpirate** [comment]
Excellent work @eriwen !

**Comment by eriwen** [comment]
@blindpirate would you like me to mention Java 10 in the release notes or do you want the honors?

**Comment by blindpirate** [comment]
@eriwen Please do it. :-)

**Comment by henrik242** [comment]
Great!

**Comment by lptr** [comment]
What was the regression?

**Comment by blindpirate** [comment]
@lptr ASM regression, not ours: https://gitlab.ow2.org/asm/asm/issues/317815

**Pull request merged**
