### PR TITLE
Re-deprecate methods for gradle 7.6

### PR DESCRIPTION
**Pull request by tresat**
- These elements were un-deprecated for Gradle 7.5 because their replacements were not yet stable (see https://github.com/gradle/gradle/pull/19732)
- This commit removes the @Incubating annotation from the replacement and re-deprecates the elements.
- It also adds nagging for usage of the methods in IdeaModule.
- Also adds section to the release notes.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test QFL

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
