### PR TITLE
Optimise ClassPath deserialization from the config cache

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle help

**Comment by bamboo** [comment]
@bot-gradle test PT

**Comment by bamboo** [comment]
PR shows a marginal improvement (~4%) in the cold startup scenario (running `./gradlew help` on `gradle/gradle`).

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Review by eskatos — APPROVED** [review]
👍 

The improvement should be locked in as a follow up if.

**Pull request merged**
