### PR TITLE
Fix for GRADLE-1682

### PR DESCRIPTION
**Pull request by idlsoft**
Prevents navigating down to jdk classes

### CODE REVIEW

**Comment by mark-vieira** [comment]
I think a more targeted fix would be to simply not inspect for superclasses when the current class being visited is `java.lang.Object`. I'd suggest adding that check here: https://github.com/gradle/gradle/blob/master/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitDetector.java#L42-L42

We'll also want some test coverage for this. The scenario seems to be only when `java.lang.Object` is included on the test classpath (not bootclasspath). So that could be a jar dependency (such as org.osgi.foundation) or a class in 'src/main' or 'src/test'.

**Comment by mark-vieira** [comment]
That said, a similar problem likely exists for TestNG which would mean making a change here as well (or refactor this logic to live in `AbstractTestFrameworkDetector`).

https://github.com/gradle/gradle/blob/master/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/testng/TestNGDetector.java#L47-L47

**Comment by pioterj** [comment]
@idlsoft We haven't heard from you for a month so I just wanted to check. Are you planning to address Mark's comments? If not I'd like to close this pull request.

**Comment by idlsoft** [comment]
Sorry, I didn't realize you were expecting a follow-up.
To be honest I haven't looked at those classes very closely, I simply fired-up the debugger when I was having the issue and found a quick way to fix it.
I'm probably not the best person to address it properly, I don't know the code enough.

**Comment by pioterj** [comment]
@idlsoft In this case I'm closing this pull request. I'll add a link to the JIRA in case some one else wants to pick it up. Thank you for your willingness to contribute anyway.

**Pull request closed without merging**
