### PR TITLE
Fix LifecyclePlugin

### PR DESCRIPTION
**Pull request by blindpirate**
### Context 

```
    private
    fun Project.isRequestedTask(taskName: String) = gradle.startParameter.taskNames.contains(taskName)
```

The old code doesn't handle `codeQuality:allVersionsIntegMultiVersionTest` correctly.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Comment by jjohannes** [comment]
@bot-gradle test RFN

**Comment by jjohannes** [comment]
@blindpirate I restored two changes I made last week that got lost. Please pull the branch before fore push.

**Comment by blindpirate** [comment]
Ah... so sorry...

**Comment by jjohannes** [comment]
Multi-version test in ready for release pipeline: https://builds.gradle.org/buildConfiguration/Gradle_Check_AllVersionsIntegMultiVersion_33_Trigger/34459000

**Comment by blindpirate** [comment]
@bot-gradle test RFR

**Comment by blindpirate** [comment]
Thanks @jjohannes !

**Pull request merged**
