### PR TITLE
[credentials-container] Initial design doc for implementing a credential...

### PR DESCRIPTION
**Pull request by adrianbk**
...s container

### CODE REVIEW

**Comment by bigdaz** [comment]
Thanks. Looks like a good start. I'll take merge and add some extra content soon.

**Comment by tomdcc** [comment]
A couple of things that I'd be interested in as a plugin author:
 - Ability to access said credentials including core-defined ones from a plugin. I assume that this is intended, but just thought it should be explicitly mentioned
 - Said credentials should include stuff like http proxy settings, as `JavaSystemPropertiesProxySettings` and friends are internal, so plugins needing to do anything over http/s have to reimplement that code themselves, which sucks.

Another way to deal with the latter is to have gradle provide a general http service that autoconfigures such things, since doing web requests is a pretty common thing to do, but that sounds out of scope for this work.

**Comment by adrianbk** [comment]
@tomdcc hopefully get the ball rolling on this next week. 
The proxy settings and protocol related stuff is an interesting one.. Not sure they are part of 'credentials' per se but I think we do need a way to configure those things.

**Comment by AstroTom** [comment]
What about using AWS EC2 roles [1] instead of explicit credentials in the credentials file (~/.aws/credentials)? This is the AWS best practice when running inside and EC2. Right now gradle seems to require specifying a profileName.

[1] https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html

**Pull request merged**
