### PR TITLE
Link specified as plain text

### PR DESCRIPTION
**Pull request by bodhili**
- Link specified as plain text
- This class `URLClassLoader` implements the interface `Closeable`, so condition 'contextClassLoader instanceof Closeable' is always 'true'

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Review by blindpirate — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by bodhili** [comment]
> LGTM, thanks for the contribution!

Thank you for approving this pull request.

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bodhili A test is failing because you changed the class in wrapper jar. [This hash code](https://github.com/gradle/gradle/blob/0238035f0a177630fe39923a037b150e58b93c3b/subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy#L74) needs to be updated, too.

https://ge.gradle.org/s/dnjnhqbengqzc/tests/:wrapper:forkingIntegTest/org.gradle.integtests.WrapperGenerationIntegrationTest/generated%20wrapper%20files%20are%20reproducible?top-execution=1

**Comment by bodhili** [comment]
> @bodhili A test is failing because you changed the class in wrapper jar. [This hash code](https://github.com/gradle/gradle/blob/0238035f0a177630fe39923a037b150e58b93c3b/subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy#L74) needs to be updated, too.
> 
> https://ge.gradle.org/s/dnjnhqbengqzc/tests/:wrapper:forkingIntegTest/org.gradle.integtests.WrapperGenerationIntegrationTest/generated%20wrapper%20files%20are%20reproducible?top-execution=1

Hmm,  I'm sorry,  I'm still at the beginning, and I don't quite know how to update the hash code, can you help me, thanks

**Comment by bodhili** [comment]
> > @bodhili A test is failing because you changed the class in wrapper jar. [This hash code](https://github.com/gradle/gradle/blob/0238035f0a177630fe39923a037b150e58b93c3b/subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy#L74) needs to be updated, too.
> > https://ge.gradle.org/s/dnjnhqbengqzc/tests/:wrapper:forkingIntegTest/org.gradle.integtests.WrapperGenerationIntegrationTest/generated%20wrapper%20files%20are%20reproducible?top-execution=1
> 
> Hmm, I'm sorry, I'm still at the beginning, and I don't quite know how to update the hash code, can you help me, thanks

Is this hash code `bb7cd61bf1c9aa32212b8ad809abba72f050d162f1eed17acf1321bb80d9ce1f` to replace `577b2de036000db2e0f04f2ec842a4f1e648c8b6f9c87f29a8d8253acb17`?

**Comment by blindpirate** [comment]
Exactly.

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
