### PR TITLE
added support attribute 'group' for IDEA modules

### PR DESCRIPTION
**Pull request by BorzdeG**

### CODE REVIEW

**Comment by alkemist** [comment]
Thanks @BorzdeG 

Can you explain that case you hit where you needed this?

Also, I wonder if this wouldn't be better exposed as “scope” as that is what it is labelled as in the IDEA UI.

This also exposes a modelling flaw in our plugin in that `Path` should be named `Module`. I'm not sure what we can do about this in the short term, or whether it's worth renaming. @adammurdoch @bigdaz any opinions?

**Comment by BorzdeG** [comment]
UI: pic00

This ability to separate the modules by group. For example to select the modules "core" platform which makes the development of additional modules for this platform.

**Comment by alkemist** [comment]
I see.

https://www.jetbrains.com/idea/help/grouping-modules.html

We'd have to make some changes to this implementation:

1. The `group` property should be exposed to be configured via `IdeaModule`
2. We'd need to introduce `ModulePath extends Path` with the group attribute and use this type

Item 2 also implies adding some methods to PathFactory to expose the group property. This is similar to `FilePath`.

**Comment by pioterj** [comment]
I'm closing this pull request because of the lack of response from contributor. @BorzdeG Feel free to re-open it if you'd still like to push it forward.

**Pull request closed without merging**
