### PR TITLE
Support for forcing ipv4 addresses

### PR DESCRIPTION
**Pull request by kensi**
In an environment where ipv6 traffic for some reason is blocked on the
loopback addresses this makes it possible to force the use of ipv4 only

Set the GRADLE_FORCE_IPV4 environment variable to true to force usage of
ipv4 addresses only

Signed-off-by: Kenny Stridh <kenny.stridh@gmail.com>

Fixes #?

### Context
As discussed briefly with Volker Leak.

I have a problem (well the whole company) with a strangely configured VPN were all local IPV6 traffic is dropped by the firewall. After years of trying to change this within the company I would like to have this option in gradle instead.

The problem has a couple of symptoms
1. Unable to ping lock owner
2. Unable to communicate with already running daemon

Only tested it locally but the feature works as expected were all traffic is routed over ipv4 loopback instead of the ipv6 loopback.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by kensi** [comment]
@big-guy Yes, I thought about that too. I'll test it quickly tomorrow and let you know. 

I agree that it's a much nicer solution to used already predefined system properties!

**Comment by kensi** [comment]
@big-guy It works perfectly from what I can see at least. Tested the following scenarios.
1. Two different reps using the same cache, gradle clean build -Djava.net.preferIPv4Stack=true --debug
2. Added -Djava.net.preferIPv4Stack=true to GRADLE_OPTS 
gradle clean --debug
3. Re-importing projects into Intellj during build from terminal
The whole 6.4 dist seems to be faster as well, but that's a different story. Thanks!

**Comment by big-guy** [comment]
@kensi Awesome, I'll get this buttoned up for a PR for 6.4

**Comment by kensi** [comment]
@big-guy Nice, just let me know if there is something I can do

**Pull request closed without merging**
