### PR TITLE
Do not set a context class loader when creating thread.

### PR DESCRIPTION
**Pull request by jdochez**
When creating a thread, the current context class loader (if any) will
be used to set the initial context class loader for the thread.

In Gradle's case, the initial class loader is the VisitableClassLoader
instance for the current build.

Because thread usages will always set/reset the context class loader
before/after any work actions, the initial context class loader
will be kept forever during the lifetime of the daemon.

Issue #16797

Signed-off-by: Jerome Dochez <jedo@google.com>

Fixes #?

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
Thanks, @jdochez. I'll backport the fix to 7.1.

**Comment by bamboo** [comment]
Something went wrong with CI, I'll take a better look Tomorrow.

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
Hi @jdochez, the change causes [quite a few failures](https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Stage_ReadyforMerge_Trigger/43595414?buildTab=dependencies&mode=list&state=failed). Could you take a look?

**Comment by bamboo** [comment]
Hey @jdochez, I have an idea how to fix those tests. I'll keep you posted.

**Comment by jdochez** [comment]
ah cool, sorry I was on vacation. 
seems to me that either the tests (or worse some gradle code) is assuming the context class loader to be set. 

let me know if I can help.

**Pull request merged**
