### PR TITLE
Migrate to JUnit5 Vintage

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

We made an attempt to migrate to JUnit5 but failed by incompatibility between JUnit5 and Spock `@Unroll` tests. All works fine on CI, but if you right click a Spock `@Unroll` test in IDEA, it didn't work. This PR workarounds this issue by falling back to JUnit in IDEA.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by ldaley** [comment]
@blindpirate FYI, this is the issue for the Spock test selection issue: https://github.com/gradle/gradle/issues/13303

**Comment by blindpirate** [comment]
Thanks @ldaley .

**Pull request merged**
