### PR TITLE
Publish more core dependencies as binary artifacts

### PR DESCRIPTION
**Pull request by lptr**

### CODE REVIEW

**Comment by wolfs** [comment]
Looks like composite build works with some tweaks: https://ge-unstable.grdev.net/s/az37q6eqbrpxo/dependencies?focusedDependency=WzEsMSw4ODksWzEsMSxbODg5XV1d&toggled=W1sxXSxbMSwxXV0

**Comment by lptr** [comment]
Can we close this now?

**Comment by wolfs** [comment]
We can. Though the list of project we need to be published will probably still change. So we can merge as is or not merge anything and add the published artifacts when we actually need them.

**Comment by wolfs** [comment]
Closing since we will publish the artifacts when we actually need them.

**Pull request closed without merging**
