### PR TITLE
Enhanced FindBugs plugin to work with SpotBugs which is FindBugs successor

### PR DESCRIPTION
**Pull request by blackbeltdev**
successor.

FindBugs development has been discontinued. SpotBugs is the spiritual
successor of FindBugs, carrying on from the point where it left off
with support of its community.

The FindBugs plugin made an assumption that the FindBugs code was
present in an artifact named "findbugs-3.0.1.jar" in order to
extract the FindBugs version number to ensure it was compatible
with the current JDK.

In order to work with SpotBugs a new optional parameter
named "validateClasspath" which defaults to true was added.

Each updated file was also improved to use immutable parameters and
local variables whenever possible. This is common strategy in other
languages (Kotlin, Scala, JavaScript, etc.)

The documents were also updated to include some helpful tips with
using the FindBugs plugin (e.g. adding the "Find Security Bugs")

See "https://spotbugs.github.io/" and "http://find-sec-bugs.github.io/" for more information.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by blackbeltdev** [comment]
I didn't see an easy way to test my change other than trivial verification of setter values. I did test it against a sample Gradle project:


apply plugin: 'java'
apply plugin: 'findbugs'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    findbugs 'com.github.spotbugs:spotbugs:3.1.0-RC3'
    findbugs configurations.findbugsPlugins.dependencies
    findbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.6.0'
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

findbugs {
    ignoreFailures = true
    validateClasspath = false
}

tasks.withType(FindBugs) {
    extraArgs = ['-html:fancy-hist.xsl']
    reports {
        xml.enabled = false
        html.enabled = true
    }
}

**Comment by bmuschko** [comment]
Thanks for providing the contribution. What's the name associated with your account you used to sign the CLA?

**Comment by big-guy** [comment]
@blackbeltdev Thanks for the PR!

I have a few comments:
- We're still using Java 6 syntax due to some backwards compatibility with Java5/6 we need to maintain for a small part of the Gradle code base (and Intellij doesn't like to mix versions).  So we can't use the diamond syntax.
- Thanks for catching the lack of documentation around extraArgs/findBugsPlugins. It'll get merged quicker as a separate PR.
- I think disabling the classpath validation is the wrong direction for implementing this. We should just bite the bullet and build a classloader with the `findbugs` configuration.  Then in that classloader, we can inspect `edu.umd.cs.findbugs.Version.RELEASE_BASE` and get a version for FindBugs that doesn't require applying a regex to file names.
- I think we should add a dedicated section to the FindBugs documentation chapter about SpotBugs and a sample that uses SpotBugs.  
- We need integration coverage for this added to `AbstractFindBugsPluginIntegrationTest`.  Unfortunately, this test is old enough that it's not doing cross-version testing.  We need that too, but I don't expect you to add it.  I think it might make sense to just extend `AbstractFindBugsPluginIntegrationTest`, call it `SpotBugsIntegrationTest` and change the setup method to add the appropriate dependencies to the build script to use SpotBugs.

We're happy to help move this along through our process and answer any questions you have.

**Comment by blackbeltdev** [comment]
Kirk Rasmussen



On Thursday, July 20, 2017, 2:49:42 PM CDT, Benjamin Muschko <notifications@github.com> wrote:


Thanks for providing the contribution. What's the name associated with your account you used to sign the CLA?

**Comment by blackbeltdev** [comment]
Sorry I had checked the minimum system requirements for Gradle 4 and it said Java 7 so I had assumed diamond operator was ok.
IMO at this point I kind of think FindBugs is dead so not sure worth investing too much into it. I use the IJ plugin w/ Java 8 on a regular basis and it seems to work but I've seen bug reports claiming its buggy. AFAIK JDK 8 isn't officially supported by FindBugs. SpotBugs does however. OTOH SpotBugs hasn't had an official release yet :(

Glad I could help. Is there anything specific I can do to help here? I don't think I quite got the document XML correct. I couldn't figure out how to get the new property I added "validateClasspath" to show up in the user guide. It did show up in the javadoc though. I noticed that updating the XML file in the class section did affect user guide generation but not my new parameter.
Regards,Kirk Rasmussen


On Friday, July 21, 2017, 12:25:51 AM CDT, Sterling Greene <notifications@github.com> wrote:


@blackbeltdev Thanks for the PR!

I have a few comments:
   
   - We're still using Java 6 syntax due to some backwards compatibility with Java5/6 we need to maintain for a small part of the Gradle code base (and Intellij doesn't like to mix versions). So we can't use the diamond syntax.
   - Thanks for catching the lack of documentation around extraArgs/findBugsPlugins. It'll get merged quicker as a separate PR.
   - I think disabling the classpath validation is the wrong direction for implementing this. We should just bite the bullet and build a classloader with the findbugs configuration. Then in that classloader, we can inspect edu.umd.cs.findbugs.Version.RELEASE_BASE and get a version for FindBugs that doesn't require applying a regex to file names.
   - I think we should add a dedicated section to the FindBugs documentation chapter about SpotBugs and a sample that uses SpotBugs.
   - We need integration coverage for this added to AbstractFindBugsPluginIntegrationTest. Unfortunately, this test is old enough that it's not doing cross-version testing. We need that too, but I don't expect you to add it. I think it might make sense to just extend AbstractFindBugsPluginIntegrationTest, call it SpotBugsIntegrationTest and change the setup method to add the appropriate dependencies to the build script to use SpotBugs.

We're happy to help move this along through our process and answer any questions you have.

**Comment by baron1405** [comment]
Will this be coming to a Gradle release soon?

**Comment by big-guy** [comment]
We ended up deprecating our FindBugs plugin in 5.0 and recommend users switch to the SpotBugs plugin instead.

**Pull request closed without merging**
