### PR TITLE
Update to latest nightly

### PR DESCRIPTION
**Pull request by big-guy**
Re-enables performance tests with new baseline

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by DPUkyle** [comment]
Go for it!

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request closed without merging**
