### PR TITLE
Full nagging for deprecation of GUtil

### PR DESCRIPTION
**Pull request by eskatos**
* Fix https://github.com/gradle/gradle/issues/21912
* Fix https://github.com/gradle/gradle/issues/21899
* Follow up for https://github.com/gradle/gradle/pull/21843

No change in the deprecation documentation link as it already said the type was deprecated even if a couple functions from it did not nag yet because of some consumers.

AGP < 7.5 still uses `GUtil`, in some cases only once per Gradle daemon. This makes it hard to assert on deprecation warnings without making all tests use a fresh daemon which would make these tests take way too long. Instead this PR introduces a way to ignore selected deprecation warnings on old version of third party plugins in smoke tests.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by jbartok — APPROVED** [review]
LGTM

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
