### PR TITLE
Fix line chopping code

### LINKED ISSUE #14086: carriage return (`\r`) interpreted as new return
When running gradlew and the program is using carriage returns (e.g. for progress bars), the carriage return will not jump to the begin of the line, but will jump to the next line.

### Expected Behavior

Carriage return jumps to the beginning of the line and overrites, whatever is written there.

### Current Behavior

Carriage return is jumping to the next line and therefore things like progress bars are not really possible

### Steps to Reproduce 

1. Create a new gradle project (i use intellij to create it)
2. create a Main and add some code, that uses carriage return
Example:
```
public class Main {
    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i < 10; i++) {
            System.out.print(i + "\r");
            Thread.sleep(1000);
        }
    }
}
```
3. Run the Main function.

### Your Environment

Java 11
gradle 6.5.1
ubuntu 18.04 LTS
Intellij 2020.2

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #14086

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle test qFL

**Comment by jbartok** [comment]
@bot-gradle test rFM

**Review by donat — APPROVED** [review]
LGTM.

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
I'm looking.

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test rFM

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
🎉 🎉 🎉

**Pull request merged**
