### PR TITLE
Fix configuration cache compatibility in dependency management snippets

### PR DESCRIPTION
**Pull request by mlopatkin**

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, BD

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, BD

**Comment by mlopatkin** [comment]
@bot-gradle test PRF

**Review by ljacomet — APPROVED** [review]

**Review by bamboo — APPROVED** [review]
👍

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
