### PR TITLE
Apply projectHealth recommendations to reporting

### PR DESCRIPTION
**Pull request by tresat**

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Review by ghale — APPROVED** [review]
LGTM

**Review by jvandort — APPROVED** [review]
This applies to all your PRs like this: 
Can we now remove this project from the list of unmigrated projects for the dependency analysis plugin: 
https://github.com/gradle/gradle/blob/master/gradle.properties#L26-L32

**Comment by tresat** [comment]
> This applies to all your PRs like this: Can we now remove this project from the list of unmigrated projects for the dependency analysis plugin: [`master`/gradle.properties#L26-L32](https://github.com/gradle/gradle/blob/master/gradle.properties?rgh-link-date=2024-02-06T04%3A38%3A54Z#L26-L32)

Yes, definitely.  I forgot about we had that list.

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
