### PR TITLE
Split AbstractMultiProjectJvmApplicationInitIntegrationTest

### PR DESCRIPTION
**Pull request by blindpirate**
This class seems to be quite slow because it contains 8 test cases,
and each test case can be as slow as 30s. Now let's further split them.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Review by hegyibalint — APPROVED** [review]

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
