### PR TITLE
Add dark mode to Gradle User Manual

### PR DESCRIPTION
**Pull request by lkasso**
### Details
This is a Documentation change ONLY.

### Context
Many users have requested the support of dark mode for our manual.

### Reviewers: [Build Link](https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/76182081:id/distributions/gradle-8.6-docs.zip!/gradle-8.6-20231221182421%2B0000/docs/userguide/userguide.html)
Please make sure when you turn on dark mode, the manual changes color scheme.

### CODE REVIEW

**Comment by lkasso** [comment]
@bot-gradle test BD

**Comment by hfhbd** [comment]
BTW: The Kotlin DSL uses a grey/white version of the Gradle logo: https://docs.gradle.org/current/kotlin-dsl/index.html, IMHO the blue Gradle logo is too dark.

**Comment by lkasso** [comment]
@bot-gradle test BD

**Comment by lkasso** [comment]
@bot-gradle test BD

**Comment by lkasso** [comment]
@bot-gradle clean

**Comment by lkasso** [comment]
@bot-gradle test BD

**Review by akshayabd — APPROVED** [review]

**Comment by lkasso** [comment]
@bot-gradle test and merge

**Pull request merged**
