### PR TITLE
Work around long path issues on Windows

### PR DESCRIPTION
**Pull request by maiflai**
Multiple plugins launch external Java processes using classpaths built from Gradle dependencies.

The `JavaExecHandler` passes the classpath to the Java Runtime via the command-line,
but Windows supports only a relatively short command-line.

This PR works around the restriction by using a Manifest in a temporary JAR to pass a long classpath to the Java Runtime.

### CODE REVIEW

**Comment by eriwen** [comment]
@maiflai Thanks for the PR. I'm not sure I see your CLA. Can you please confirm the name under which you signed so I can move this PR forward?

**Comment by maiflai** [comment]
Stu Armitage

**Comment by eriwen** [comment]
Thank you very much @maiflai. I'm afraid I don't see that name on the CLA list (unless you submitted one a really, really long time ago). Could you please try [submitting a CLA](http://gradle.org/contributor-license-agreement/) again?

**Comment by maiflai** [comment]
I have a PDF copy of the form dated "September 11, 2014 - 8:29 AM PDT". The Transaction ID is XEXLG48492J3F74.

**Comment by eriwen** [comment]
@maiflai Indeed you're right, I was able to find your CLA in our older system. Apologies for the run-around. 

We'll get to reviewing this, then :)

**Comment by maiflai** [comment]
Is there any feedback please? I tried to work within the existing API but it felt a little clumsy at the time (in that you need to know the projected command line before replacing it with a shorter version).

Thanks,
Stu

**Comment by lacasseio** [comment]
Thanks @maiflai for submitting this PR. Unfortunately, this only address the long path scenario for a very narrow case by adding very specific code in. It would be preferable to address the problem at the root and possibly providing the required utility classes to deal with long Windows path as transparently as possible.

Possible solution path would be to investigate how `JavaExec` (and `java -jar`) handle [NT Object Path](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247.aspx) or even [DOS path](https://en.wikipedia.org/wiki/8.3_filename). Thanks for your contribution and looking forward to your next one.

**Comment by maiflai** [comment]
Please could you clarify what you think a more appropriate solution would be?

I think the root problem is that Gradle tries to launch an external process with a command line that is too long. 

It can't be fixed by using short names, nor is it related to the maximum length of an individual file.

I'm not sure there is a universal solution for external processes, other than Microsoft removing the restriction on the execution of an arbitrary command.

**Comment by lacasseio** [comment]
I understand this is a complex issue. Lots of time the command line size can be shrunk by using shorter file path. This can be done by either using DOS path or relative path. If this fails to generate a command line that is smaller than the limit, the entire command line can be placed inside a batch script and execute the script using `cmd.exe /c`. Those are the most widespread methods. However, with each method, there is an overhead and side effect. This prevents us from implementing a simple straight forward solution. More research is needed to find a compromise.

The most important thing is `JavaExec`, `Exec` and others are all susceptible to this limitation. A solution to this problems needs to address or is on the right path to address all the scenarios.

**Comment by maiflai** [comment]
Yes, I agree it's possible to shrink the path by other means; I personally use `subst` to move my home area (and hence`GRADLE_USER_HOME`) to the root of a drive. I don't think there is a panacea.

I tried to write a simple batch file to test the `cmd /c` suggestion but was unable to get it to work. My understanding is that this is a limit on =CreateProcess= (https://blogs.msdn.microsoft.com/oldnewthing/20031210-00/?p=41553, https://blogs.msdn.microsoft.com/oldnewthing/20031210-00/?p=41553, https://support.microsoft.com/en-us/help/830473/command-prompt-cmd.-exe-command-line-string-limitation), which suggests that there is no simple bypass. 

Even the CLASSPATH environment variable is also limited (http://superuser.com/questions/1070272/why-does-windows-have-a-limit-on-environment-variables-at-all/1070354). Setting this might be simpler than creating a JAR file with a manifest, but has a quite visible limit.

It's a particular problem for Java because we pass the classpath on the command-line, and there is a tendency to use lots of dependencies. I suppose Javascript projects put this information into `package.json` and read it from there rather than the command line. Here we are using the documented JAR mechanism to pass a classpath.

I think it's still down to each individual process-launching task to know what each argument is, and how it can potentially be shortened, so it's fine for this to be handled in a Java-specific way. 

As far as I'm aware the JVM doesn't provide a means to determine the short path to a file, so the dependency handler can't easily provide the 8.3 filenames (which would also be neater and portable to more tasks, but probably more confusing to anyone trying to read paths while debugging issues).

**Comment by maiflai** [comment]
I think `org.gradle.api.internal.plugins.WindowsStartScriptGenerator` will also be affected by this?

**Comment by ovUdemy** [comment]
@maiflai I'm still getting this on Gradle 4.4/ Windows 10

**Comment by maiflai** [comment]
This PR was rejected; it seems from https://github.com/maiflai/gradle-scalatest/issues/30 that a fix has been implemented via a plugin. You may have more luck with that approach.

**Comment by liuzhonghu** [comment]
I am in amazing.

**Pull request closed without merging**
