### PR TITLE
Fix for binary store errors caused by corner cases of conflict resolution

### PR DESCRIPTION
**Pull request by ljacomet**
Still missing tests, see individual commits for details.

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by jbartok — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
