### PR TITLE
Document version catalog improvements

### PR DESCRIPTION
**Pull request by melix**
What the title says.

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle help

**Pull request merged**
