### PR TITLE
Update GE Gradle plugin to v3.6.3

### PR DESCRIPTION
**Pull request by snoopcheri**
Subject says it all.

### CODE REVIEW

**Comment by snoopcheri** [comment]
@bot-gradle test rFM, please

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
The pre-tested commit failure is unrelated to this branch and is taken care of. When it is fixed, I'll re-trigger a pre-tested commit.

**Comment by snoopcheri** [comment]
Thanks @wolfs !

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
