### PR TITLE
Fix RFN tests on `release` for Java 21

### PR DESCRIPTION
**Pull request by eskatos**
* Follows up https://github.com/gradle/gradle/pull/26913

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFN without PTS

**Comment by eskatos** [comment]
@bot-gradle test RFN without PTS

**Comment by eskatos** [comment]
@bot-gradle test RFN without PTS

**Review by ljacomet — APPROVED** [review]
LGTM! Thanks for fixing

**Comment by ljacomet** [comment]
@bot-gradle merge

**Comment by ice1000** [comment]
Is the nightly ready yet?

**Pull request merged**
