### PR TITLE
Add test for GitAttributesGenerator; add *.jar entry to generated .gitattributes

### LINKED ISSUE #28796: Gradle - Build Init Plugin - add a *.jar entry to generated .gitattributes
### Current Behavior

Gradle projects created by `gradle init` will contain a `.gitattributes` file with no `*.jar` entry.

### Expected Behavior

Gradle projects created by `gradle init` will contain a `.gitattributes` file with a `*.jar` entry.

### Context (optional)

It is a best practice to explicitly specify binary files in `.gitattributes`.

[.gitattributes Best Practices - Binary Files](https://rehansaeed.com/gitattributes-best-practices/#binary-files)

[Do I really need to specify all binary files in .gitattributes](https://stackoverflow.com/questions/57030698/do-i-really-need-to-specify-all-binary-files-in-gitattributes)

### Steps to Reproduce

[Gradle - Build Init Plugin - Build init types](https://docs.gradle.org/current/userguide/build_init_plugin.html#sec:build_init_types)

#### basic
```shell
$ mkdir /tmp/example-basic && cd "$_" && gradle init --type basic --dsl kotlin --incubating --quiet --project-name example-basic
$ find . -name '*.jar'
./gradle/wrapper/gradle-wrapper.jar
$ cat .gitattributes
#
# https://help.github.com/articles/dealing-with-line-endings/
#
# Linux start script should use lf
/gradlew        text eol=lf

# These are Windows script files and should use crlf
*.bat           text eol=crlf
```
#### java-library
```shell
$ mkdir /tmp/example-java-library && cd "$_" && gradle init --type java-library --java-version 21 --test-framework junit-jupiter --dsl kotlin --incubating --quiet --project-name example-java-library
$ find . -name '*.jar'
./gradle/wrapper/gradle-wrapper.jar
$ cat .gitattributes
#
# https://help.github.com/articles/dealing-with-line-endings/
#
# Linux start script should use lf
/gradlew        text eol=lf

# These are Windows script files and should use crlf
*.bat           text eol=crlf
```

#### cpp-library 
```shell
$ mkdir /tmp/example-cpp-library && cd "$_" && gradle init --type cpp-library --dsl kotlin --incubating --quiet --project-name example-cpp-library
$ find . -name '*.jar'
./gradle/wrapper/gradle-wrapper.jar
$ cat .gitattributes
#
# https://help.github.com/articles/dealing-with-line-endings/
#
# Linux start script should use lf
/gradlew        text eol=lf

# These are Windows script files and should use crlf
*.bat           text eol=crlf
```

### Gradle version

8.7

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by sdavids**
Fix #28796

### Context

#28796

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by sdavids** [comment]
I mimicked the style of the `GitIgnoreGeneratorTest` for the `GitAttributesGeneratorTest`.

`GitIgnoreGeneratorTest` was not part of an integration test therefore I did not create one for `GitAttributesGeneratorTest`.

**Comment by ov7a** [comment]
Thank you for your contribution!

This PR is complete and simple enough, it will be merged immediately.

**Comment by ov7a** [comment]
@sdavids yes, they are. I've rebased the PR to the latest master as those test we're addressed recently.

**Comment by sdavids** [comment]
I will rebase again ... rebasing via GitHub butchers the GPG signing

**Comment by sdavids** [comment]
I rebased.

---

You—or someone official from the Gradle team—might want to chime in on behalf of Gradle:

https://github.com/orgs/community/discussions/4618

Butchering signed commits during a rebase is just 🤬

**Comment by sdavids** [comment]
Seems like more flaky tests, yay! 😉


Tell when the build is stable again—I will rebase with the then current master and force-push again …

**Review by big-guy — APPROVED** [review]

**Pull request merged**
