### PR TITLE
Use a Java compiler plugin to determine mapping from source to class names

### PR DESCRIPTION
**Pull request by melix**
Previously, mapping from source files to class names was done by extracting
the class names from the class files names, which wasn't 100% accurate.
The Groovy incremental compiler, on the other hand, was implemented using
an AST transformation which could extract the class names from the compiler
itself, therefore giving an accurate mapping from class names to source files.

The same is now done for the Java compiler, using a Java compiler plugin.
This fixes several issues where we could not figure out properly what files
to recompile when the name of the class being used in a dependency wasn't
directly related to the source file name.

However, this introduces a problem when the compiler is not a proper JDK
compiler. In particular, if compiling using a "path to compiler", the
plugin cannot be loaded and incremental compilation will fail.

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test RFM please

**Comment by melix** [comment]
@bot-gradle test RFM please

**Comment by melix** [comment]
@bot-gradle test RFM

**Comment by melix** [comment]
@ljacomet Following our discussion, couldn't find any reasonable explanation for the remaining regressions. So I'm putting this for review and will rebaseline.

**Comment by lptr** [comment]
This PR sounds like an epic battle. Congrats to the victory, @melix! :)

**Pull request merged**
