### PR TITLE
Allow configuring log level from command line using Turkish Locale

### LINKED ISSUE #19585: org.gradle.logging.level=lifecycle fails in tr_TR locale
Gradle 7.3.3:

```
_JAVA_OPTIONS="-Duser.country=TR -Duser.language=tr" ./gradlew help  -Dorg.gradle.logging.level=lifecycle
```

```
* Exception is:
java.lang.IllegalArgumentException: Value 'lifecycle' given for org.gradle.logging.level Gradle property is invalid (must be one of quiet, warn, lifecycle, info, or debug))
	at org.gradle.internal.buildoption.Origin$GradlePropertyOrigin.handleInvalidValue(Origin.java:58)
	at org.gradle.internal.logging.LoggingConfigurationBuildOptions$LogLevelOption.parseLogLevel(LoggingConfigurationBuildOptions.java:138)
	at org.gradle.internal.logging.LoggingConfigurationBuildOptions$LogLevelOption.applyFromProperty(LoggingConfigurationBuildOptions.java:103)
	at org.gradle.internal.logging.LoggingConfigurationBuildOptions$LogLevelOption.applyFromProperty(LoggingConfigurationBuildOptions.java:76)
	at org.gradle.internal.buildoption.BuildOptionSet$2.convert(BuildOptionSet.java:64)
	at org.gradle.launcher.cli.converter.BuildOptionBackedConverter.convert(BuildOptionBackedConverter.java:36)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:226)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

### PR DESCRIPTION
**Pull request by donat**
Fixes #19585

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test RFM

**Review by hegyibalint — APPROVED** [review]
Debated meanwhile peer programming.

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
