### PR TITLE
Make pattern in SdkManJvmLocator compliant with sdkman version declaration convention.

### PR DESCRIPTION
**Pull request by soberich**
This enables `ea` JDKs

this relates to https://github.com/sdkman/sdkman-db-migrations/pull/343

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by soberich** [comment]
What do we need to get this merged?

**Comment by soberich** [comment]
@ljacomet What do we need to get this merged?

**Comment by ljacomet** [comment]
@soberich Thanks for this contribution. We are currently wrapping up the 6.7 release.
After it is out, someone will definitely have a look into that improvement.

**Comment by bmuskalla** [comment]
@soberich I don't quite understand what you're trying to achieve with this change. That parts you touched are responsible for detecting jvms to *build gradle* itself on our infrastructure. 

As far as I can tell, you want to improve support for the new toolchain feature (which does its detection slightly differently, see [`SdkmanInstallationSupplier`](https://github.com/gradle/gradle/blob/fec59ec9a2eb4ced87d65fd46a1eb0a62fdbae80/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/SdkmanInstallationSupplier.java#L28) and doesn't suffer from this limitation.
The code you touched will be gone soon as well and will [rely on the new toolchain mechanism](https://github.com/gradle/gradle/pull/14284). 

The current toolchain support seems to work well for me with ea version (e.g. `15.ea.21-open` installed via sdkman). Happy to guide you if you help me understand the problem you're trying to fix.

**Comment by soberich** [comment]
@bmuskalla 👍 Thanks

**Pull request closed without merging**
