### PR TITLE
DefaultGradleRunner.withJvmArguments part of public API

### PR DESCRIPTION
**Pull request by edeandrea**
Issue: #1043

### CODE REVIEW

**Comment by eriwen** [comment]
@bmuschko Can we pair on this review later this week? I'll assign to you in any case as you're most familiar.

**Comment by edeandrea** [comment]
Thanks for the quick response! Let me know if you need anything from me.

**Comment by bmuschko** [comment]
@eriwen Before jumping to quickly to solutions I'd rather first like to discuss the use cases in #1043. I'll comment there.

**Comment by bmuschko** [comment]
Closing as per comment described [here](https://github.com/gradle/gradle/issues/1043#issuecomment-318744463).

**Pull request closed without merging**
