### PR TITLE
Smoke test Gradle Kotlin Plugin 1.5.0

### PR DESCRIPTION
**Pull request by rieske**

### CODE REVIEW

**Comment by lusu007** [comment]
Can we add version 1.5.10 as well in this PR?
I think it would be generally handy if the compatibility of Kotlin versions could be made more dynamic.

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by rieske** [comment]
@bot-gradle test and merge

**Comment by rieske** [comment]
@bot-gradle test and merge

**Pull request merged**
