### PR TITLE
Let ConfigurationCacheReport use coreAndPluginsScope loader for storing json

### PR DESCRIPTION
**Pull request by eskatos**
This fixes CNFE for Groovy's FastStringServiceFactory

See https://gradle-community.slack.com/archives/C013WEPGQF9/p1624521157046300

Before the fix: https://ge.gradle.org/s/f3iacdlsazub6/tests/:configCacheFunctionalTest/org.graalvm.buildtools.gradle.JavaApplicationWithAgentFunctionalTest/agent%20is%20passed%20and%20generates%20resources%20files%20on%20Gradle%207.0.2%20with%20JUnit%20Platform%205.7.2?anchor=e30&focused-exception-line=0-167&top-execution=1

After the fix: https://ge.gradle.org/s/kobh57ffdh34e/tests/:configCacheFunctionalTest/org.graalvm.buildtools.gradle.JavaApplicationWithAgentFunctionalTest/agent%20is%20passed%20and%20generates%20resources%20files%20on%20Gradle%207.0.2%20with%20JUnit%20Platform%205.7.2?anchor=e30&focused-exception-line=0-78&top-execution=1

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle help

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
Superseded by https://github.com/gradle/gradle/pull/17538

**Comment by bamboo** [comment]
I'm assuming the classloader is no longer needed since we're not encoding objects via Groovy anymore.

**Comment by bamboo** [comment]
I was wrong, the classloader is still needed :/

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
Superseded by https://github.com/gradle/gradle/pull/17550

**Pull request closed without merging**
