### PR TITLE
fixes gradle#23580: Replace property with explicit regex to ensure compatibility below Java 15.

### PR DESCRIPTION
**Pull request by jknair0**
Fixes [gradle#23580](https://github.com/gradle/gradle/issues/23580)

### Context
Due to issues with regex in java when properties are used, the Task abbreviation working was inconsistent in gradle when used with different version of java (<15 vs >=15).

Related Bug Reports in JDK : https://bugs.openjdk.org/browse/JDK-8239887 

In addition, from a user perspective, you can argue that - using extreme short names - invoking `./gradlew pRB ` should select `publishReleaseBundlePublicationToTempPublishRepository (pRBPTTPR)` over `publishReleaseObfuscatedBundlePublicationToTempPublishRepository (pROBPTTPR)`. The key difference is the additional O. which is fixed.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by alllex** [comment]
Thank you for your contribution!

This PR has a valid DCO and tests. The relevant team for this area will confirm the design of the implementation choices.

***

There was a previous attempt at fixing this, and there was a use case it didn't cover [described here](https://github.com/gradle/gradle/pull/24563#pullrequestreview-1502751874).
Could you include a test for this?

**Comment by jknair0** [comment]
Do we have java check that we can add in core module ? I am not able to find one. otherwise we will have to stick to explicit character selection in regex in all java versions.

**Comment by ljacomet** [comment]
Hi @jknair0,

This change "fixes" the reported discrepancy by making selection fail in Java < 15.

But from a user perspective, you can argue that - using extreme short names - invoking `./gradlew pRB` should select `publishReleaseBundlePublicationToTempPublishRepository` (`pRBPTTPR`) over `publishReleaseObfuscatedBundlePublicationToTempPublishRepository` (`pROBPTTPR`). The key difference is the additional `O` in there.

Your correction to the test I propose makes it pass, but then it no longer reflects the original issue.

Now the question is: Is there a way to fix the original problem so that the behaviour from Java 8-14 is visible with Java 15+?

> Do we have java check that we can add in core module ?

If you want to know the current major Java version the daemon is running on, you can use `Jvm.current().getJavaVersionMajor()`

**Comment by jknair0** [comment]
> Hi @jknair0,
> 
> This change "fixes" the reported discrepancy by making selection fail in Java < 15.
> 
> But from a user perspective, you can argue that - using extreme short names - invoking `./gradlew pRB` should select `publishReleaseBundlePublicationToTempPublishRepository` (`pRBPTTPR`) over `publishReleaseObfuscatedBundlePublicationToTempPublishRepository` (`pROBPTTPR`). The key difference is the additional `O` in there.
> 
> Your correction to the test I propose makes it pass, but then it no longer reflects the original issue.
> 
> Now the question is: Is there a way to fix the original problem so that the behaviour from Java 8-14 is visible with Java 15+?
> 
> > Do we have java check that we can add in core module ?
> 
> If you want to know the current major Java version the daemon is running on, you can use `Jvm.current().getJavaVersionMajor()`

@ljacomet Thanks for explanation. I have made those changes to make sure its correct in users perspective. Please review.

**Review by ljacomet — APPROVED** [review]
@jknair0 Sorry for the late reply and thank you for your dedication in fixing this.

I confirm this fixes the issue and makes the behaviour consistent.

**Pull request merged**
