### PR TITLE
Update Exemplar and other modules the the newest version

### PR DESCRIPTION
**Pull request by pbielicki**
Upgrade Exemplar and the related dependencies to the newest versions.

### CODE REVIEW

**Review by britter — APPROVED** [review]
LGTM

**Comment by pbielicki** [comment]
@bot-gradle test this

**Comment by pbielicki** [comment]
@bot-gradle test this

**Comment by pbielicki** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by pbielicki** [comment]
@bot-gradle test and merge

**Pull request merged**
