### PR TITLE
Extract instrumentation agent supporting code out of :core and :integ-test

### PR DESCRIPTION
**Pull request by mlopatkin**
Quick overview of changes:
* New subproject `:instrumentation-agent-services` is introduced to hold agent-related code.
* Code from `:core` that resided in `org.gradle.internal.agents` moved to the new project with `org.gradle.internal.instrumentation.agent` package. We don't use agent for anything but the instrumentation anyway.
* `AgentApplicationTest` moved from `:integ-test` to the new `:instrumentation-agent-services` too.
* `InstrumentingClassLoader` interface residing in `:base-services` moved from `org.gradle.internal.agents` to `org.gradle.internal.classloader`, closer to the classloader implementations. It is not possible to easily move it to the new project and inverse the dependency without making the whole `:instrumentation-agent-services` Java 6-compatible. Extracting instrumented classloader implementation out of `base-services` is even more involved. 
* The rest are dependency and import updates.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this without PTS

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Review by bamboo — APPROVED** [review]
Nice! 👍

**Comment by lptr** [comment]
Nice!

**Pull request merged**
