### PR TITLE
Increase client VM heap for build scan performance

### PR DESCRIPTION
**Pull request by blindpirate**
See https://github.com/gradle/gradle-profiler/pull/337 for more context

Currently, "jvmOpts" and "gradleOpts" is mixed up in performance test infrastructure, this PR renames all previous "gradleOpts" to "jvmArguments"/"jvmArgs" to make it consistent with `JavaForkOptions`. An extra `gradleOpts` is added to configure client VM `GRADLE_OPTS`.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@wolfs PTAL!

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
