### PR TITLE
Update nebula plugins versions for smoke tests

### PR DESCRIPTION
**Pull request by ljacomet**
* Reflect change of coordinates
* Nebula lint still ignored

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by eskatos — CHANGES_REQUESTED** [review]
The `BomSupportPluginsSmokeTest` also needs to be updated

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
