### PR TITLE
Make checkstyle work with toolchains

### PR DESCRIPTION
**Pull request by asodja**
Fixes #?

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by blindpirate** [comment]
Looking.

**Comment by blindpirate** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test AST

**Comment by asodja** [comment]
Replaced by: https://github.com/gradle/gradle/pull/19361.

**Pull request closed without merging**
