### PR TITLE
Update attributes used for verification task output

### LINKED ISSUE #19008: Update outgoing variants for Test Suites and add additional sanity checking
Update the Test Suites, Java and Jacoco Plugins to use the new attributes and categories proposed:

- A new category of verification
- A new attribute type "org.gradle.verificationtype"
- Removal of the Sources interface, DocType constants, Usage.Verification
- Update ban list in https://github.com/gradle/gradle/issues/19007 to include anything in the new org.gradle.verificationtype attribute type

These additional checks below might be better broken out into separate issues, depending on the complexity:
- Ensure if multiple variants with identical attributes are registered, an error is generated at registration time
- Ensure if multiple suites of the same TestType are registered, an error is generated at registration time

### PR DESCRIPTION
**Pull request by tresat**
Fixes #19008

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Review by DPUkyle — APPROVED** [review]
Approved with one request:

Whenever applying attributes in code like this:
```
attribute(Usage.USAGE_ATTRIBUTE, objects.named<Usage>(Usage.VERIFICATION))
attribute(Category.CATEGORY_ATTRIBUTE, objects.named<Category>(Category.DOCUMENTATION))
attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named<DocsType>(DocsType.JACOCO_COVERAGE))
```

can we please sort them in the order they will be enumerated by the `outgoingVariants` task?
```
- org.gradle.category              = verification
- org.gradle.testsuite.name        = integrationTest
- org.gradle.testsuite.target.name = integrationTest
- org.gradle.testsuite.type        = integration-tests
- org.gradle.verificationtype      = jacoco-coverage
```

I know this the nitpick to own all nitpicks, but reconciling a broken variant on the consumption side is so much easier if these lists are in the same order

**Comment by tresat** [comment]
> I know this the nitpick to own all nitpicks, but reconciling a broken variant on the consumption side is so much easier if these lists are in the same order

Looks like I missed some tests in projects I wasn't modifying.  I'll do this as I fix those tests.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
I need to update https://docs.gradle.org/current/userguide/variant_attributes.html as well.

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
LGTM! 🚢 it

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
