### PR TITLE
Fix native memory leak by closing zip streams

### PR DESCRIPTION
**Pull request by jdochez**
A number of zip (or embedded zip within zip) input streams
were not closed properly leading to a 45% of total memory
allocated by jvm to be leaking. Zip implementation in JDK
uses jni and native heap rather than jvm heap.

With these fixes, the leak is reduced from 45% to about
10%, running with jemalloc instead of glibc still shows
some leaks (updatewindow is Inflater again) :

5189917067  84.5%  84.5% 5189917067  84.5% os::malloc@a87750
662324804  10.8%  95.3% 662324804  10.8% updatewindow
175095264   2.9%  98.2% 175095264   2.9% inflateInit2_

I have not been able to pinpoint the remaining leaks but
have identified some questionable code like :
subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/RuntimeClasspathResourceHasher.java

fixing the code above failed a unit test and I did not have
the time to go deeper, someone from Gradle should look.

Signed-off-by: Jerome Dochez <jedo@google.com>

Fixes #?

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test QFL

**Comment by jdochez** [comment]
I do not have access to the Teamcity details. how am i supposed to resolve these failures ?

**Comment by big-guy** [comment]
@jdochez you should be able to login as a guest:
image

**Comment by jdochez** [comment]
@bot-gradle test QFL

**Comment by jdochez** [comment]
Thanks Sterling, I fixed the code style issue.

**Comment by eskatos** [comment]
@bot-gradle test QFL

**Comment by wolfs** [comment]
I ran some performance tests on the branch: https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_PerformanceTest10_Trigger/41814817?buildTab=overview

Some of them failed, because the branch is not up-to-date with master where we changed some performance test names  and we don't apply the Teamcity configuration of pull requests to our pipeline. I looked at some of the test results, though I didn't see neither an improvement nor a regression.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
Thanks @jdochez. It looks like your changes break a couple integration tests: https://builds.gradle.org/viewLog.html?buildId=41836042&buildTypeId=Gradle_Master_Check_Stage_QuickFeedbackLinuxOnly_Trigger&fromExperimentalUI=true

I've fixed a few more formatting differences and pushed the changes to your PR. Could you take a look at the failing tests?

**Comment by jdochez** [comment]
ok I fixed the ConfigureRuntimeClasspathNormalizationIntegrationTest integration test. can you run the tests again to see where we stand.

**Comment by eskatos** [comment]
@bot-gradle test QF

**Comment by eskatos** [comment]
@bot-gradle test RFM

**Comment by wolfs** [comment]
@bot-gradle test this

**Comment by wolfs** [comment]
Thank you @jdochez for finding and fixing the problem! This will be part of Gradle 7.0.

**Pull request merged**
