### PR TITLE
Use idea-ext plugin to allow native Intellij import of gradle/gradle

### PR DESCRIPTION
**Pull request by wolfs**
I ported the changes from https://github.com/nskvortsov/gradle/tree/gradle-idea-settings back to current `master`. 

That should take care of using `org.jetbrains.gradle.plugin.idea-ext` to remove the xml manipulation we use currently and allow importing the `gradle/gradle` project into Intellij.

After doing so, we should be able to import the project into Intellij not using the "separate module per source set option".

### CODE REVIEW

**Comment by wolfs** [comment]
Some things still do not work when using IDEA 2018.2.2:
- running integration tests from IDEA: When trying to run integration tests, it seems like `build-receipt.properties` is not found
- the configured copyright doesn't show up in Intellij
- it would be great to provide Gradle run configurations (i.e. executing some Gradle tasks), instead of trying to run a Java application with `org.gradle.testing.internal.util.GradlewRunner` as the main class
- `useReleaseOption = false` is not picked up by Intellij

The main blocker is that performance tests don't run.

@eskatos Do you have an idea how to fix this?

**Comment by eskatos** [comment]
Thank you @wolfs!

> running integration tests from IDEA: When trying to run integration tests, it seems like build-receipt.properties is not found

Did you import with one module per source set or one module per project?
On the branch you ported running integration tests did work with the latter.
If you used one module per source set then the change to `DefaultModuleRegistry` might need to be adjusted.

> the configured copyright doesn't show up in Intellij

Do you mean that when creating a new source file the configured copyright isn't applied?
It works on `gradle/kotlin-dsl`

https://github.com/gradle/kotlin-dsl/blob/1d81b63f3a35f4122b6a49b9f57f7381b714b9a5/build.gradle.kts#L115-L137


> useReleaseOption = false is not picked up by Intellij

What version of IntelliJ were you using?
@nskvortsov, what version of IntelliJ do support `compiler.useReleaseOption`?

**Comment by nskvortsov** [comment]
`compiler.useReleaseOption` is only available in master. Will be released with 2018.3

**Comment by wolfs** [comment]
@nskvortsov I am using `gradle-idea-ext` plugin `0.4.1`. Should that work with Intellij `2018.2`?

**Comment by eskatos** [comment]
@wolfs, what Nikita mean is that as of now `compiler.useReleaseOption` is supported on IntelliJ's `master` branch only. IOW, it's not supported by 2018.2. Until this lands in an EAP we'll have to tick that box after import.

**Comment by wolfs** [comment]
@eskatos I understood that. I was trying to understand why `copyright` does not work for me. The `kotlin-dsl` repo is using version `0.1` of the `idea-ext` plugin. I tried using `0.4.1` and thought maybe that is the reason why it doesn't work.

BTW, I used the "one module per project" import option.

**Comment by wolfs** [comment]
@nskvortsov Plugin version `0.1` seems to work for configuring the copyright, for all the other plugin versions I don't see the copyright reflected in the Intellij settings.

**Comment by nskvortsov** [comment]
@wolfs I will double-check this and get back with the result

**Comment by nskvortsov** [comment]
sorry, `copyright` is broken since version `0.4`, please try version `0.3`.

**Comment by nskvortsov** [comment]
https://github.com/JetBrains/gradle-idea-ext-plugin/issues/33

**Comment by wolfs** [comment]
@eskatos I still can't run integration tests. Can you try?

**Comment by nskvortsov** [comment]
copyright is fixed in v 0.4.2 (published)

**Comment by wolfs** [comment]
2018.3 EAP is out. That may fix the import.

**Pull request merged**
