### PR TITLE
Fix issue with more worker daemons being started than max workers

### PR DESCRIPTION
**Pull request by ghale**
Fixes an issue where a single task can end up starting more worker daemons than max workers rather than reusing existing workers.

### CODE REVIEW

**Comment by oehme** [comment]
Is this issue in 4.1 M1? If so it might be affecting demos of parallel execution at the summit.

**Comment by ghale** [comment]
Yes

**Comment by ghale** [comment]
It's been around for some time.  We just didn't have test coverage for it.  We had tests that submitted more work than max workers with multiple tasks (which works properly), but not in a single task.

**Comment by ghale** [comment]
> Was this problem in compiler daemons before? If not, didn't we have enough test coverage for them? 

No.  Compile tasks only submit one unit of work, so you would never see this problem with a compile task.

**Pull request merged**
