### PR TITLE
Filter test tasks by AbstractTestTask instead Test in TestTaskExecutionTracker

### PR DESCRIPTION
**Pull request by terrakok**
### Context
Start investigation point was here: https://youtrack.jetbrains.com/issue/KTIJ-20110
In Gradle 7.3.3 TestTaskExecutionTracker was implemented but it has problem: incoming tasks are filtered by sub-type of `Test` but `KotlinTest` tasks are extended from `AbstractTestTask`

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] `N/A` Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] `N/A` Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] `N/A` Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by big-guy** [comment]
This looks sane to me.

Could we add some coverage for this using KotlinTest or a custom AbstractTestTask?

**Comment by terrakok** [comment]
Good idea but I need your advise: where i can do it and there is some example?

**Comment by big-guy** [comment]
`org.gradle.integtests.tooling.r27.TestLauncherCrossVersionSpec` is a good one to get inspiration.

Since this is only going to work on Gradle 7.5+, our convention is to:
- Create a new package `org.gradle.integtests.tooling.r75`
- Mark the test with `@TargetGradleVersion(">=7.5")`

HTH

**Comment by terrakok** [comment]
Is there a chance to lower the fix to the 7.3.* version?

**Comment by terrakok** [comment]
This code works fine with 7.1.1
And fails with 7.3.3+

build.gradle
```groovy
import org.gradle.api.internal.tasks.testing.*
import org.gradle.internal.operations.OperationIdentifier

plugins {
    id 'java'
    id 'application'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url 'https://repo.gradle.org/gradle/libs-releases' }
}

dependencies {
    implementation 'org.gradle:gradle-tooling-api:7.3.3'
    runtimeOnly 'org.slf4j:slf4j-simple:1.7.36'
}

application.mainClass = 'Main'

class CustomTestExecutionSpec implements TestExecutionSpec {}
class CustomTestExecuter implements TestExecuter<CustomTestExecutionSpec> {

    @Override
    void execute(CustomTestExecutionSpec customTestExecutionSpec, TestResultProcessor testResultProcessor) {
        OperationIdentifier rootId = new OperationIdentifier(40L)
        DefaultTestSuiteDescriptor rootDescr = new DefaultTestSuiteDescriptor(rootId, "MyCustomTestRoot")
        testResultProcessor.started(rootDescr, new TestStartEvent(System.currentTimeMillis()))

        OperationIdentifier testId = new OperationIdentifier(42L)
        DefaultTestDescriptor testDescr = new DefaultTestDescriptor(testId, "org.my.MyClass", "MyCustomTest", null, "DisplayName")
        testResultProcessor.started(testDescr, new TestStartEvent(System.currentTimeMillis()))
        testResultProcessor.completed(testId, new TestCompleteEvent(System.currentTimeMillis(), TestResult.ResultType.SUCCESS))

        testResultProcessor.completed(rootId, new TestCompleteEvent(System.currentTimeMillis()))
    }

    @Override
    void stopNow() {}
}

class CustomTestTask extends AbstractTestTask {
    CustomTestTask() {
        binaryResultsDirectory.set(new File(getProject().buildDir, "CustomTestTask"))
        reports.html.required.set(false)
        reports.junitXml.required.set(false)
    }

    @Override
    protected TestExecuter<? extends TestExecutionSpec> createTestExecuter() {
        return new CustomTestExecuter()
    }

    @Override
    protected TestExecutionSpec createTestExecutionSpec() {
        return new CustomTestExecutionSpec()
    }
}

tasks.register("myTestTask", CustomTestTask)
```

Main.java
```java
import org.gradle.tooling.BuildLauncher;
import org.gradle.tooling.GradleConnector;
import org.gradle.tooling.ProjectConnection;
import org.gradle.tooling.events.OperationType;
import org.gradle.tooling.internal.consumer.DefaultGradleConnector;

import java.io.ByteArrayOutputStream;
import java.io.File;

public class Main {
    public static void main(String[] args) {
        GradleConnector connector = GradleConnector.newConnector();
        connector.forProjectDirectory(new File("."));

        // required because invoked build script doesn't provide a settings file
        ((DefaultGradleConnector) connector).searchUpwards(false);

        ProjectConnection connection = connector.connect();
        try {
            BuildLauncher launcher = connection.newBuild();
            launcher.forTasks("myTestTask");

            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            launcher.setStandardOutput(outputStream);
            launcher.setStandardError(outputStream);
            launcher.addProgressListener(event -> {
                System.out.println("TEST ProgressEvent: " + event.getDisplayName());
            }, OperationType.TEST);

            launcher.run();
            System.out.println("Build was successful");
        } finally {
            System.out.println("Cleaning up after the build");
            connection.close();
        }
    }
}
```

**Comment by terrakok** [comment]
After my fix the sample above works fine again.
@big-guy  could you review the PR?

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by donat** [comment]
@bot-gradle test RFM

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle test and merge

**Comment by donat** [comment]
@bot-gradle help

**Comment by donat** [comment]
@bot-gradle cancel

**Review by donat — APPROVED** [review]

**Comment by donat** [comment]
@bot-gradle test and merge

**Pull request merged**
