### PR TITLE
Add modular classpath handling to Java plugin extension

### LINKED ISSUE #12605: Add modular classpath handling configuration to Java extension
This will allow to configure conveniences for all tasks that are instantiated by a Java plugin and have a `modularClasspathHandling` property - in particular `modularClasspathHandling.inferModulePath.set(true)`.

### PR DESCRIPTION
**Pull request by jjohannes**
Fixes #12605 

Documentation will be added separately.

### CODE REVIEW

**Comment by jjohannes** [comment]
I am not sure. I was following what we do for other things. Adding more test tasks is a common pattern because there is currently no other convenience to add them.

Compile tasks on the other hand do not need to be added manually that often, as they are automatically added for each source set.

The ordering issue only exists if plugins want to add tasks and use `convention()`. As long as the user code only uses `set()`, we are good. But yes, it is a good reason not to do it for all user/plugin added tasks.

We could leave it like this and rethink the test task behavior when we add more conveniences for adding new test sets (before or for 7.0)?

**Comment by jjohannes** [comment]
On the other hand, this particular option is a very "basic" one. So maybe you usually want consistent behavior for ALL tasks. 🤔

**Comment by ljacomet** [comment]
Oh right, I forgot that most tasks will be effectively added _when you add a `SourceSet`_!
And thus, the convention will be applied.

**Comment by jjohannes** [comment]
I propose to merge this like it is now. We can still adjust if we get additional feedback.

**Pull request merged**
