### PR TITLE
Removed scala console tasks

### PR DESCRIPTION
**Pull request by lordoku**
From the discussion, located at:
https://discuss.gradle.org/t/scalaconsole-fails-for-gradle-2-6/11147,
it was suggested that the scalaConsole task be removed, since it
doesn't have ay automated test coverage, wasn't documened and
wasn't ever finshed properly.

### CODE REVIEW

**Comment by big-guy** [comment]
Thanks!  I've put in a couple of comments so you can get a green build.

**Comment by lordoku** [comment]
Ok I'll take a look. I'll go ahead and close this pull request and make a new one, once I've made the necessary changes.

**Comment by big-guy** [comment]
Sure, you can push new commits to this one too, doesn't matter to us.

**Comment by mark-vieira** [comment]
I've merged this pull request. This will be included in Gradle 2.11. Thanks for the contribution.

**Pull request merged**
