### PR TITLE
Allow custom implementations of PublishArtifact

### LINKED ISSUE #17273: Adding custom `PublishArtifact` to `MavenPublication` fails
Attempting to add an artifact which is a custom implementation of `PublishArtifact` to a `MavenPublication` fails because at some point the internals attempt to cast this to a `PublishArtifactInternal`.

What I expect to happen is defined in the user-guide: https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html#org.gradle.api.publish.maven.MavenPublication:artifact(java.lang.Object)

To paraphrase:

> The artifact method can take a variety of input:
> 
> * A PublishArtifact instance. Extension and classifier values are taken from the wrapped instance.
> * ...

According to the documentation, any object implementing `PublishArtifact` should be allowed.  but effectively only internally created artifacts are allowed due to this bug.

My (pseudo) code:

```
class ShadowPublishArtifact implements PublishArtifact, TaskDependency {
    ...
}

void doStuff() {
    ShadowPublishArtifact shadowPublishArtifact = ...;
    shadowMavenPublication = publishingExtension.getPublications().create( "mavenShadowArtifacts", MavenPublication.class );
    shadowMavenPublication.artifact( shadowPublishArtifact )
}
```

What actually happens:

```
* What went wrong:
A problem occurred evaluating project ':real-jakarta'.
> Could not create an instance of type org.gradle.api.publish.maven.internal.artifact.PublishArtifactBasedMavenArtifact.
   > class org.hibernate.build.gradle.jakarta.shadow.ShadowPublishArtifact cannot be cast to class org.gradle.api.internal.artifacts.PublishArtifactInternal (org.hibernate.build.gradle.jakarta.shadow.ShadowPublishArtifact is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @33d8bfc8; org.gradle.api.internal.artifacts.PublishArtifactInternal is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @240f8312)

....

Caused by: java.lang.ClassCastException: class org.hibernate.build.gradle.jakarta.shadow.ShadowPublishArtifact cannot be cast to class org.gradle.api.internal.artifacts.PublishArtifactInternal (org.hibernate.build.gradle.jakarta.shadow.ShadowPublishArtifact is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @33d8bfc8; org.gradle.api.internal.artifacts.PublishArtifactInternal is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @240f8312)
	at org.gradle.api.publish.maven.internal.artifact.PublishArtifactBasedMavenArtifact.<init>(PublishArtifactBasedMavenArtifact.java:29)
	at org.gradle.api.publish.maven.internal.artifact.PublishArtifactBasedMavenArtifact_Decorated.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1969)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:468)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	... 180 more
```

My env:

```
------------------------------------------------------------
Gradle 6.8
------------------------------------------------------------

Build time:   2021-01-08 16:38:46 UTC
Revision:     b7e82460c5373e194fb478a998c4fcfe7da53a7e

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.6 (AdoptOpenJDK 11.0.6+10)
OS:           Linux 5.10.8-100.fc32.x86_64 amd64

```

### PR DESCRIPTION
**Pull request by mlopatkin**
These used to work in the past and we don't want to break them
now unless we have a very compelling reason to.

Fixes #17273

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test QF

**Comment by mlopatkin** [comment]
@bot-gradle help

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
LGTM!

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
