### PR TITLE
Call script to flush OS caches in performance tests

### PR DESCRIPTION
**Pull request by lhotari**
Operating system cache state can affect performance test results. This change calls a hook script before warmup runs if such script exists in the environment where the performance tests get run.

On CI there now is a script `/usr/local/bin/gradle_perf_test_prepare_next.sh` on each node.
This script has been configured to gain proper sudo access for the TC build agents.

The current content of the script in our CI is:
```
#!/bin/bash
# Prepares for doing performance test measurements 
# This script gets called by org.gradle.performance.fixture.BuildExperimentRunner#runOsPrepareNextTestScript

# call script with sudo if running as non-root
if [[ $EUID -ne 0 ]]; then
    exec sudo "$0" "$@"
fi

# sync pending changes to disk
sync
# drops operating system caches
echo 3 >/proc/sys/vm/drop_caches
```

### CODE REVIEW

**Comment by oehme** [comment]
We do plenty of warmups, wouldn't those also warm up the OS-level caches?

**Comment by lhotari** [comment]
yes, but this ensures that both test runs start with the same OS cache state.

**Comment by oehme** [comment]
But what does that fix then? If the warm-ups get the caches into the correct state anyway, then I don't see why we need to actively drop them.

**Comment by lhotari** [comment]
Well it depends how you define "the correct state". 

It's a common pattern when running performance tests on Linux to drop caches when you want to reduce any differences in the OS cache state. My goal was to reduce differences and I think it's useful.

**Comment by lhotari** [comment]
The script doesn't just drop caches, it runs `sync` before dropping. `sync` writes all buffered writes to disk. This is useful when reducing differences since both test runs start with the same state. I don't think there is a better way to achieve this. The change is pretty simple to the performance test itself. It simply checks if the hook script exists and runs it if it does. The script implementation is maintained as part of the dev-infrastructure.

**Comment by oehme** [comment]
> This is useful when reducing differences since both test runs start with the same state.

But then the warm-ups run and the caches will be filled with the test data anyway. So how much does it matter what was in the caches before?

> The change is pretty simple to the performance test itself. 

Like any simple change, if we do dozens of them, we still end up with a lot of complexity that everyone needs to understand. I would like to avoid that unless there is a clear signal that this particular change significantly reduces flakiness.

**Comment by lhotari** [comment]
> But then the warm-ups run and the caches will be filled with the test data anyway. So how much does it matter what was in the caches before?

It does make a difference which is relevant in our case. It might be just a few milliseconds, but that is relevant in this case.

> Like any simple change, if we do dozens of them, we still end up with a lot of complexity that everyone needs to understand. I would like to avoid that unless there is a clear signal that this particular change significantly reduces flakiness.

Is there something that should be explained more deeply in this change? I believe that this additional complexity is essential in achieving the goal of reducing flakiness.

**Comment by oehme** [comment]
Like discussed on our call, we'll merge this and revisit it together with the other changes once we have stable performance suite.

**Pull request merged**
