### PR TITLE
Follow up on allocating workspace in execution engine

### PR DESCRIPTION
**Pull request by lptr**
Following up on https://github.com/gradle/gradle/pull/14691:

- [x] Revert ec776737efe90ba1e5954d52f718753c0dc9e46a as it leads to too eager resolution of input properties
- [x] Replace `EnumSet` parameter in `UnitOfWork.visitInput*Properites()` with separate methods
- [x] Add integration test for identity cache in `:execution`

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test this please.

**Comment by lptr** [comment]
@bot-gradle test this please.

**Comment by lptr** [comment]
@bot-gradle test this please.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Pull request merged**
