### PR TITLE
Include test resources in classpath when testing Play applications

### PR DESCRIPTION
**Pull request by chunyang**
When building with SBT, files in test/resources are placed into the test classpath. This pull request replicates this behavior.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@chunyang, do you mind rebasing your changes on 'master' and dealing with any conflicts?

**Comment by chunyang** [comment]
@mark-vieira @ghale Just rebased off of master, thanks.

**Comment by ghale** [comment]
@chunyang Thanks for the pull request.  We actually have a more comprehensive solution to this problem in the works building off of the new JVM test suite execution model (see https://docs.gradle.org/release-candidate/userguide/java_software.html#N18131).  We'll be adapting Play components to use this approach which will allow one to easily add resource directories to the test suite.

Given this upcoming support, I'm going to close this PR for now.

**Comment by tkruse** [comment]
I have similar trouble now, with IntelliJ not properly adding the 'test/resources' folder to the classpath during tests.

It seems the gradle play plugin will use 'test/resources' on the test classpath, but neither is this documented in the gradle play documentation, nor it this configurable via model.components.play?

**Pull request closed without merging**
