### PR TITLE
Add missing syntax validation in TOML file

### PR DESCRIPTION
**Pull request by melix**
This commit adds extra validation of the dependency coordinates
of a library, as well as the version.

I've set the milestone to 7.0-rc-1 in case we have time to merge it. No big deal if it misses the window.

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge

**Comment by melix** [comment]
@bot-gradle test and merge

**Pull request merged**
