### PR TITLE
Improve doc test coverage (groovy)

### PR DESCRIPTION
**Pull request by mlopatkin**
No user-facing changes, just tests cleanup. I filed #22538 to track fix in the groovy cross-compilation

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test this

**Review by 6hundreds — APPROVED** [review]
LGTM

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Review by bamboo — COMMENTED** [review]
👍

**Pull request merged**
