### PR TITLE
Upgrade gradle-profiler and remove hacky maven home setting

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

This PR upgrade gradle-profiler to `alpha7` so we can collect flamegraph from multiple daemons. We also removed the hacky maven home settings.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
LGTM! I kicked off a performance experiment coordinator, to see if it works: https://builds.gradle.org/buildConfiguration/Gradle_Check_PerformanceExperimentCoordinator/38298749

**Comment by blindpirate** [comment]
Seems to be working.

**Pull request merged**
