### PR TITLE
Forbid having unfinished catalog builders

### LINKED ISSUE #18233: Catalog version entry without version and `.withoutVersion()` call produces non-trivial errors
### Expected Behavior
`settings.gradle.kts`:
```
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            version("junit5", "5.4.2")

            alias("junit-platform").to("org.junit", "junit-bom").versionRef("junit5")
            alias("junit-v4").to("junit", "junit")
            alias("junit-engine-vintage").to("org.junit.vintage", "junit-vintage-engine")
            alias("junit-engine-jupiter").to("org.junit.jupiter", "junit-jupiter-engine")
        }
    }
}
```

`build.gradle.kts`:
```
plugins {
    `java-library`
}

dependencies {
    testRuntimeOnly(libs.junit.engine.jupiter)
}
```

Either:
* It just works(tm),
* I get a message that I have to write a `.withoutVersion()` call.

### Current Behavior
```
    testRuntimeOnly(libs.junit.engine.jupiter)
```
Compile error: `engine` not resolved. Looking up why exactly accessor is missing is very non-trivial.

### Context
Works like a charm when catalog is in `gradle/libs.versions.toml` and you don't specify a version, though! Docs show that you can omit a version there.

### Steps to Reproduce 
Code above is sufficient.

### Your Environment
Gradle 7.2

### PR DESCRIPTION
**Pull request by octylFractal**
Fixes #18233

I went for a hard error over a warning, as I don't think there's a legitimate reason to have this and a hard error is more noticeable.

### CODE REVIEW

**Comment by octylFractal** [comment]
@bot-gradle test QF

**Comment by octylFractal** [comment]
@bot-gradle test QF

**Review by ljacomet — APPROVED** [review]

**Comment by octylFractal** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
