### PR TITLE
Make IntelliJ IDEA plugin respect main and test sourceset excludes for the Java plugin

### PR DESCRIPTION
**Pull request by rpanak**
IntelliJ IDEA plugin now generates IntelliJ modules with correctly excluded folders based on sourceset excludes. 

According to the guidelines for contributing I've tried posing on the Gradle Developer List (https://groups.google.com/forum/#!topic/gradle-dev/9F0jhc-xBH4) hoping some Gradle developer would open an ticket for this, but I figured I might as well open the pull request in the meantime.

### CODE REVIEW

**Comment by erdi** [comment]
Hi @rpanak,

Thanks for the contribution, somebody will have a look at it soon.

In the mean time, can you please sing the CLA at http://www.gradleware.com/contributor-agreement if you haven't done so yet?

Cheers

**Comment by rp1337** [comment]
Hi @erdi,
I have already signed it.

**Comment by rpanak** [comment]
Hi @erdi,

I have already signed it.

**Comment by rpanak** [comment]
@erdi,
any progress on the pull request from your side?

**Comment by alkemist** [comment]
Hi @rpanak ,

This change introduces some coupling between the Java plugin and the IntelliJ plugin. From the IntelliJ plugin's point of view, there's no guarantee that there is a main source set. At the moment, this is going to blow up when this isn't the case.

I'm also not sure that this change is entirely desirable as a default. It's a step too far to assume that files excluded for compilation shouldn't show up in the IDE. This is one of many points where mapping from a Gradle project's model to the IDEs more primitive model creates tension.

I apologise that it took so long to provide feedback. If you're willing to progress this, then I encourage you to revive the dev list email thread asking how we might achieve what you're after. We will make a concerted effort to provide faster feedback.

Regardless, thanks for taking the time to submit this contribution.

**Comment by rpanak** [comment]
@alkemist, how about showing the "concentrated effort" in the dev list :) ? I didn't get any reply since my post on Mar 30.

**Pull request closed without merging**
