### PR TITLE
Use correct System properties and working directory for distro download from TAPI

### LINKED ISSUE #12060: Gradle tooling api doesn't respect proxy configuration for distribution downloading
Given all the necessary proxy settings and credentials are in gradle.properties and command line gradlew is able to successfully use it.

### Expected Behavior
No, further proxy configuration is needed for the project import in IDE.
Or at least it should be possible to pass similar proxy configuration to the Gradle tooling api.

### Current Behavior
The import might fail since Gradle tooling client side code doesn't use proxy information for Gradle distribution downloading.
`LongRunningOperation#setJvmArguments` doesn't help to make Gradle distribution downloader aware of proxy system properties.

Related issue from the IntelliJ IDEA issue tracker: https://youtrack.jetbrains.com/issue/IDEA-184697

### LINKED ISSUE #16748: Gradle Daemon created for TAPI request gets unexpected working directory
Gradle Daemon started for Gradle TAPI operation uses working directory of the TAPI client process although `org.gradle.tooling.GradleConnector#forProjectDirectory` has been set.  

Yes, it's a bad practice to have CWD dependant code in a build scripts. But the current behaviour is inconsistent with the terminal user experience and this leads to confusion.

### Expected Behavior
The same behaviour for TAPI and terminal Gradle running.
For terminal run the newly created Gradle daemon is started with current terminal working directry.
For TAPI run the newly created Gradle daemon should be started using `GradleConnector#forProjectDirectory` value.

### Current Behavior
For TAPI run the newly created Gradle daemon is started using IDE cwd.

### Context
This report is not about changing of CWD for existing Gradle daemons which can be reused if it's compatible.
It's only about newly created Daemon processes, so the behaviour will become consistent with the command line usages.

The origin user report and other users complains can be found at https://youtrack.jetbrains.com/issue/IDEA-265203 and linked issues.

### PR DESCRIPTION
**Pull request by oehme**
The TAPI wasn't reading gradle.properties when downloading the Gradle wrapper,
so it didn't pick up authentication properties listed there. It also used the client's CWD
as the wrapper base dir, when it should have been using the project directory. Both of
these are now fixed.

Fixes #12060

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
Putting back into draft, as more CWD-related TAPI issues were reported and I want to add some integ tests for them.

**Comment by oehme** [comment]
@big-guy this is one of the issues that JetBrains will need to fix up 2021.1 (without reintroducing their hack of changing the whole IDE's CWD when invoking Gradle). They are currently using TAPI version 6.8, so I think a 6.8.4 would be appropriate. WDYT?

**Comment by oehme** [comment]
Seems like JB reintroduced their workaround after all. We should fix this anyway though, so they can remove it in the future.

**Review by jjohannes — APPROVED** [review]
This looks very good. Thanks @oehme.

**Comment by jjohannes** [comment]
@bot-gradle test this

**Comment by jjohannes** [comment]
This also fixes #16748

**Comment by oehme** [comment]
@jjohannes no, it doesn't fix that.

**Comment by jjohannes** [comment]
Thanks for clarifying @oehme. Misunderstanding from my side then (for some reason the issue and this PR were linked).

**Comment by oehme** [comment]
There were many complaints mixed in #16748 and this PR fixes one of them, which is why I had mentioned it at some point in this PR. That's probably why it was linked.

**Comment by jjohannes** [comment]
@bot-gradle test this

**Comment by jjohannes** [comment]
@bot-gradle test this

**Comment by jjohannes** [comment]
@bot-gradle test this

**Comment by jjohannes** [comment]
@bot-gradle test and merge

**Pull request merged**
