### PR TITLE
Upgrade build scan plugin to 2.0.1

### PR DESCRIPTION
**Pull request by guylabs**

### CODE REVIEW

**Comment by wolfs** [comment]
@eskatos @guylabs I guess both performance tests are failing since `2.0.1` doesn't work with an older release snapshot and `2.0` doesn't work with the current release snapshot, right?

**Comment by eskatos** [comment]
`help on the gradle build comparing gradle` failed, a new baseline is needed
`help on the gradle build comparing the build` did not fail, it is marked as a regression

**Comment by wolfs** [comment]
I understand that `help on the gradle build comparing the build` did not fail. The regression is still due to the fact that build scan plugin `2.0` does not work with the current version on `release`. So it errs out early, and all the work necessary to collect the build scan is not done.

I found this in the log when executing the old build with the current Gradle version:
```
> Configure project :
This version of Gradle requires version 2.0.1 of the build scan plugin or later.
Please see https://gradle.com/scans/help/gradle-incompatible-plugin-version for more information.
```

So it means that this test needs to be rebaselined, too.

**Comment by eskatos** [comment]
Got it! Would be nice if that test failed instead.

**Comment by wolfs** [comment]
@guylabs Any ideas how we could make the `gradle/gradle` build fail when the build scan plugin version we apply is not compatible?

**Comment by guylabs** [comment]
@wolfs @eskatos see https://github.com/gradle/gradle/pull/7591 for the change to fail early.

**Pull request merged**
