### PR TITLE
Add a classifier property to the Distribution type(fixes #18698)

### LINKED ISSUE #18698: Add a classifier property to the Distribution type
### Expected Behavior
Configure a custom distribution (using the `distribution` plugin) allowing the generated zip/tar files to have a classifier, such as

```groovy
distributions {
    cli {
        distributionBaseName = project.name
        classifier =  "${osdetector.os}-${osdetector.arch}"
        contents {
            from("build/nativeImage") {
                into "bin"
                exclude "*.txt"
                rename "application", project.name
            }
            from(".") {
                include "LICENSE.txt"
            }
        }
    }
}

```

### Current Behavior
There is no support for this. One must grab hold of the computed tasks names and append the classifier, such as

```groovy
tasks.named("cliDistZip", Zip) {
    classifier =  "${osdetector.os}-${osdetector.arch}"
}

tasks.named("cliDistTar", Tar) {
    classifier =  "${osdetector.os}-${osdetector.arch}"
}
```

### Context
I have the need to create platform specific distributions when working with projects that generate native executables with GraalVM Native Image.

### PR DESCRIPTION
**Pull request by scaventz**
Signed-off-by: Xin Wang <scaventz@outlook.com>

Fixes [#18698](https://github.com/gradle/gradle/issues/18698)

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest` (some tests failed, but seem not relavent)

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by h0tk3y** [comment]
I'm going to update it and add some more tests.

**Comment by h0tk3y** [comment]
I found a potential problem with this implementations that would be nice to handle in some way:

If multiple distributions have the same `distributionBaseName` and only different `archiveClassifier`s, then the directories that their `install*Dist` tasks will put the distribution contents are still the same.

This could be fixed by appending the `archiveClassifier` to the `installTask.into(...)` directory [here](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/distribution/plugins/DistributionPlugin.java#L139). If we go with this fix, the `archiveClassifier` will probably not be the best name, as the classifier will not only affect the archive.

Before this change, multiple distributions could have the same `distributionBaseName`, too, but that would hardly have valid use cases. With this change, the use case of building multiple distributions that have the same base name and only different classifiers is the one that can realistically lead to this issue.

**Comment by h0tk3y** [comment]
@bot-gradle test ReadyForNightly

**Review by ljacomet — APPROVED** [review]

**Comment by h0tk3y** [comment]
@bot-gradle test and merge

**Comment by h0tk3y** [comment]
@bot-gradle test and merge

**Pull request merged**
