### PR TITLE
Fix link and name for foojay plugin in docs

### PR DESCRIPTION
**Pull request by StefMa**
### Context

Seems still the old link and name of that plugin was used inside the docs 🙃. 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
Thanks for the patch! It is not a critical issue since there is a redirect and the name, but new versions should be kept up to date

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
@StefMa could you please fix the DCO though (commit body sign-off)? Also, did you submit the patch from the browser? If so, I will ask the team to fix the settings to require DCO from browser patches

**Comment by StefMa** [comment]
Fixed the DCO ✅ and rebased with `master` branch.

> Also, did you submit the patch from the browser? If so, I will ask the team to fix the settings to require DCO from browser patches

Yes, i patched this via github directly. 
In my case with the mobile app.
However, it doesn't matter. The commits made in the browser, mobile app or codepspace are by default authored by the "noreplay.github.com" adress I guess 🤔 

Anyways, I think it is a good think to ignore/disable DCO when commits made via these tools 🙃

**Review by oleg-nenashev — APPROVED** [review]
Thank you!
@bot-gradle merge

**Comment by ljacomet** [comment]
@bot-gradle merge

**Pull request merged**
