### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zosrothko**
Any of the checked boxes below indicate that I took action:

- [x ] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [x ] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x ] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:

- [ ] Before submitting a pull request, I started a discussion on the [Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev),
      the [forum](https://discuss.gradle.org/) or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I considered writing a design document. A design document can be
brief but explains the use case or problem you are trying to solve,
touches on the planned implementation approach as well as the test cases
that verify the behavior. Optimally, design documents should be submitted
as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
can be found in the Gradle GitHub repository. Please let us know if you need help with
creating the design document. We are happy to help!
- [ ] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
DSL reference and Javadocs where applicable.

This quote "Building the Gradle project with Eclipse is currently limited due to Eclipse's lacking Groovy support.
We recommend using IntelliJ IDEA." is no more valid since Eclipse is supporting Groovy and  all imported gradle projects compile without error when using Java 8,

### CODE REVIEW

**Comment by bmuschko** [comment]
Can you please explain the relevance of Java 8 in this context? Or are you just describing your environment?

**Comment by zosrothko** [comment]
Please look at this PR #706 for the detail on using Java 8.

**Comment by bmuschko** [comment]
@donat Would you mind handling this PR as follow up to #706?

**Comment by bmuschko** [comment]
> BTW: Did we ever receive a CLA from you? I couldn't find you in the list. If yes, what's the name you use?

@zosrothko Would you mind commenting on my question?

**Comment by zosrothko** [comment]
Yes, I signed the CLA. My name is Francis ANDRE and my surrogate is zosrothko

**Comment by bmuschko** [comment]
@zosrothko Thanks for the info, found you in the list.

**Comment by donat** [comment]
Hi @zosrothko! I think deleting the recommendation is not the right way to go. You've made the Eclipse integration much better, but - unfortunately - there are still limitations compared to the IntelliJ. The documentation should describe the following items:
- the production code now compiles in Eclipse
- no proper support for the Groovy codebase
- the one-classpath-per-project limitation
- the recommendation is still on IntelliJ
I'll close this PR now, but feel free to open one.

**Pull request closed without merging**
