### PR TITLE
Upgrade junit-platform-launcher

### PR DESCRIPTION
**Pull request by pkoenig10**
Addresses https://github.com/junit-team/junit5/issues/2028

### Context
The current version of `junit-platform-launcher` may skip tests if an exception is thrown during discovery. It's relatively easy to miss the warning log, especially when tests are run in CI.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by iamdanfox** [comment]
Could this be a candidate to backport to 5.X? This was found because tests were silently not being run after an unrelated dependency exclusion (of logback) caused the discovery of some tests to throw `NoClassDefFoundErrors`, and then just not run (while the build was still green).

I think this could affect other projects, who haven't yet migrated to 6.X

**Comment by bmuskalla** [comment]
Thanks @pkoenig10 for the PR and sorry for taking so long to get back to you. Do you happen to have a good approach for integration testing the bug you refer to? I'd love to have an integration test showing that the upgrade indeed fixes the problem as it may depend on how Gradle uses the launcher. I've tried a few things with older versions of `junit-platform` but could not get it to silently ignore the errors. Happy to help with the test if we have an idea how to reproduce it from the outside (maybe @marcphilipp remembers a specific scenario).
Other than that, we need to rebase the PR and remove the old checksums from the `dependency-verification.xml`. Please let me know if you currently have the bandwidth to continue working on this.

**Comment by marcphilipp** [comment]
I'd write a test with a custom `TestEngine` that throws an exception from its 'discover()` method and check that it gets included in the test report appropriately.

**Comment by bmuskalla** [comment]
@pkoenig10 thanks for the fix, I've added tests and fixed the verification metadata. I've done this in a separate PR #12489 but cherry-picked your commit into it so you get the credit :)

**Pull request closed without merging**
