### PR TITLE
Let signature verification detect keyrings file and useKeyServers flag changes

### LINKED ISSUE #19663: Gradle caches keyserver information even when it is disabled
Gradle caches keyserver information even when it is disabled

### Expected Behavior
When the user disables remote keyservers, gradle should invalidate signature verification data and rerun all of it.

### Current Behavior
Gradle caches keychains fetched from previous builds even though keyservers is disabled.

### Context
As part of enabling Gradle signature verification for our build, we ran into this incorrect behavior.

### Steps to Reproduce 

0. Checkout https://github.com/liutikas/gradle-disabled-keyservers
1. `./gradlew jar` <- build succeeds as expected
2. Modify `gradle/verification-metadata.xml` to uncomment `<key-servers enabled="false"/>`
3. `./gradlew jar`

## Expected

Build fails because we are missing keychains that are only available online

## Actual

Builds succeeds

### Your Environment
Linux
Gradle 7.4-rc-1 (same is true for 7.3)

### PR DESCRIPTION
**Pull request by asodja**
By using `keyrings file hash` and `useKeyServers flag`  in the cache key.

Fixes #19663, #18440

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test QFL

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@asodja Can you merge this in `release` please? I have updated the milestones already on the PR and issues.

**Comment by asodja** [comment]
Will do

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

It seems like the newly-created windows machine has something wrong, I've disabled it.

**Pull request merged**
