### PR TITLE
Cherry-pick #23561 'Use 17 for toolchain tests' to release7x

### PR DESCRIPTION
**Pull request by blindpirate**
Cherry-pick #23561 'Use 17 for toolchain tests' to release7x

### CODE REVIEW

**Comment by blindpirate** [comment]
This is failing at https://builds.gradle.org/buildConfiguration/Gradle_Release7x_Check_Soak_35_0/60602285?hideProblemsFromDependencies=false&hideTestsFromDependencies=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

@reinsch82 @jbartok Can you please take a look?

**Review by reinsch82 — APPROVED** [review]

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@wolfs No this won't pass because of the failure. I have DMed @reinsch82 to take a look.

**Comment by reinsch82** [comment]
@bot-gradle test this

**Review by jbartok — APPROVED** [review]

**Pull request merged**
