### PR TITLE
Update smoke tested plugin versions

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle help

**Comment by ljacomet** [comment]
@bot-gradle test AST

**Review by ov7a — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test AST

**Comment by ljacomet** [comment]
@bot-gradle test AST

**Comment by ljacomet** [comment]
@bot-gradle merge

**Comment by ljacomet** [comment]
@bot-gradle merge

**Pull request merged**
