### PR TITLE
Support type-safe configuration for Checkstyle/FindBugs HTML report stylesheet

### PR DESCRIPTION
**Pull request by jjustinic**
### Context
#6543 Checkstyle/FindBugs HTML report stylesheet does not support type-safe configuration

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [X] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by jjustinic** [comment]
This PR simplifies configuration of a custom stylesheet for Checkstyle and FindBugs HTML reports in the Kotlin DSL. Currently, this change depends on the initial version of the Kotlin DSL sample for the code quality plugins. I can reverse the dependency if it is desired to merge this change before the current version of the code quality Kotlin DSL sample.

**Comment by eskatos** [comment]
Thank you @jjustinic. I think this change makes sense. Could you please update this PR so it's only about the API change, leaving the samples changes out?

**Comment by jjustinic** [comment]
@eskatos, I've rebased the API change on master, rather than on PR #6510. Unless you have a different plan, I will mark #6510 as WIP until this is merged and the docs can make use of it.

**Comment by eskatos** [comment]
Thank you @jjustinic!

This PR doesn't contain any added coverage. BUT, the existing coverage exercising `reports.html` 
 (e.g. `CheckstylePluginVersionIntegrationTest`) written in Groovy was relying on reflection. With this change it's simply reaching out to public members now 👍 

This is a binary compatibility breaking change so I expect our binary compatibility check to fail. Given we target 5.0-RC1 it's acceptable. You'll have to accept the breakage, instructions will follow.

I triggered CI on your branch, we'll see results in Github checks in a while.

**Comment by eskatos** [comment]
It failed as expected: https://builds.gradle.org/viewLog.html?buildId=15374822&buildTypeId=Gradle_Check_SanityCheck (login as guest).

You can reproduce locally:
```
./gradlew :distributions:checkBinaryCompatibility
```

Then to review and accept the breaking change:
```
open subprojects/distributions/build/reports/binary-compatibility/report.html
```

scroll down to the two breakages and click the `Accept this change`, follow the instructions, commit the modified files and push.

**Comment by jjustinic** [comment]
@eskatos, binary compatibility breaking changes have been accepted.

**Comment by eskatos** [comment]
Thank you James!

**Pull request merged**
