### PR TITLE
Reproduce #18465 in integration test

### PR DESCRIPTION
**Pull request by big-guy**

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Review by ljacomet — CHANGES_REQUESTED** [review]
Given the history of the changes on the ASM opcode, I wonder if the change is safe ...
See https://github.com/gradle/gradle/commit/ab4c0d2a4e7c469604454590ce287ff8a34d3841

**Comment by big-guy** [comment]
Repeat what I said on Slack...

I found this comment: https://github.com/gradle/gradle/pull/16529#discussion_r594229059
The issue seems to be that the version of the Kotlin compiler was not updated to use ASM9+ yet.  When I look in the shaded dependencies for 1.5.31, it has Opcodes.ASM9 now.

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Review by ljacomet — APPROVED** [review]

**Pull request merged**
