### PR TITLE
 GRADLE-2895 - Add support for user defined JUnit RunListeners

### PR DESCRIPTION
**Pull request by mtau11**

### CODE REVIEW

**Comment by pskrivanek** [comment]
It is possible to finish this merge? What is need for finishing this issue?

**Comment by bigdaz** [comment]
We appreciate the work put into this pull request.

The Gradle team doesn't currently have the capacity to deal with all of the bugs, feature requests, great ideas and pull requests that we receive. We already have a pretty big backlog, so it might take some time for us to take a look at this.

Pull requests are interesting because they may seem like they come for "free". Our experience has shown that in order to maintain the level of quality and consistency that Gradle users expect, we need to invest significant engineering effort in all but the most trivial PRs.

We are [actively recruiting](http://grnh.se/mbne6o) to increase our engineering team, so hopefully this is a temporary situation. We ask for patience in the meantime.

**Comment by pioterj** [comment]
@mtau11 In order to move forward with pull request we'll need a [contributor license agreement](https://gradle.org/contributor-license-agreement/) from you. This is required for legal reasons before any code contributions can be accepted into the Gradle codebase. Would you mind signing it?

**Comment by pioterj** [comment]
@mtau11 Are you still interested in pushing this forward? If yes, could you sign the CLA and resolve the conflicts?

**Comment by pskrivanek** [comment]
@mtau11, it is a very useful feature. I still look forward to it appears in the main line.
Could you please deliver the desired document?

If @mtau11 not sends CLA, it's necessary create another branch with changes for integration to main line?

**Comment by pioterj** [comment]
Unfortunately if we don't get the CLA we won't be able to merge this change. If we don't hear back from @mtau11 I'll close this pull request. @pskrivanek if you are interested in starting this over the first step should be creating a design document describing the use case, implementation plan and test coverage. It can be included here: https://github.com/gradle/gradle/blob/master/design-docs/testing-improvements.md

**Comment by pioterj** [comment]
It's been over a month without a response from @mtau11 so I'm closing this pull request. We cannot merge it without a CLA in place. @mtau11 if you ever come back to this and submit the CLA, feel free to re-open it.

**Comment by raulgd** [comment]
Hi guys,

As @mtau11 is MIA, is there an alternative to load RunListener classes using gradle? I'm a bit new to gradle but handling a test listener on JUnit is something that I think is basic functionality and would be expected to be supported.

**Comment by baev** [comment]
@raulgd agree
In addition it would be nice to have an ability to load listeners via SPI.

PS I can provide a patch for that. What are you guys think?

**Comment by raulgd** [comment]
@baev created https://github.com/gradle/gradle/issues/1330 to restart this task.
I'll take the same code only with enough small changes so it doesn't conflict with this implementation, and I'll be willing to sign the CLA right away, if you want, you can add the SPI thing as well.

**Comment by eriwen** [comment]
@raulgd Great! I'll allow you to decide whether you add SPI support or not. Note that smaller changes are easier for us to review and merge, so without much context here I'll suggest you split them into 2 PRs.

**Comment by baev** [comment]
> I'll suggest you split them into 2 PRs.

+1

**Pull request closed without merging**
