### PR TITLE
Upgrade JUnit version

### PR DESCRIPTION
**Pull request by blindpirate**
As the prerequisite of distributed test, we need to use JUnit platform. Before migration, let's upgrade all JUnit to latest version.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Comment by jjohannes** [comment]
Looks like this is failing consistently: https://builds.gradle.org/buildConfiguration/Gradle_Check_Platform_4_bucket45/34312793?buildTab=log&focusLine=0

https://e.grdev.net/s/qnq5kfcbikjki

Could be a build cache bug?

**Comment by wolfs** [comment]
> Looks like this is failing consistently: [builds.gradle.org/buildConfiguration/Gradle_Check_Platform_4_bucket45/34312793?buildTab=log&focusLine=0](https://builds.gradle.org/buildConfiguration/Gradle_Check_Platform_4_bucket45/34312793?buildTab=log&focusLine=0)
> 
> [e.grdev.net/s/qnq5kfcbikjki](https://e.grdev.net/s/qnq5kfcbikjki)
> 
> Could be a build cache bug?

This looks very much like a problem with unpacking the strange file name on Windows:
`C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\kotlin-dsl-integ-tests\build\classes\kotlin\integTest\org\gradle\kotlin\dsl\integration\ProjectSchemaLambdaAccessorsIntegrationTest$accessors to **typed** java lambda extensions are typed$exception$1.class`

Why hasn't this been a problem before? Is the test new?

**Comment by jjohannes** [comment]
@wolfs The test changed in this PR. See: https://github.com/gradle/gradle/pull/12924/commits/7777dd35cf617dd1556541b978c226229b2e2f02

**Comment by blindpirate** [comment]
Yes, I was trying to replace a deprecated JUnit API. Will investigate it.

**Comment by wolfs** [comment]
> @wolfs The test changed in this PR. See: [7777dd3](https://github.com/gradle/gradle/commit/7777dd35cf617dd1556541b978c226229b2e2f02)

Hmm...
The test changed but the method name didn't.

**Comment by blindpirate** [comment]
It turns out that I added a closure into that class, then the class name exceeds Windows 260 characters path limit.... I hate Windows.

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Comment by blindpirate** [comment]
@bot-gradle test RFN

**Comment by blindpirate** [comment]
No it's not the path length limitation... it's `*` characters in method name. `*` is legal method name in Java bytecode but not legal name in Windows path - I added a closure into a method so a new class was generated: `ClassName$methodName$1`, BOOM!

**Comment by blindpirate** [comment]
Thanks @jjohannes !

**Pull request merged**
