### PR TITLE
Adjust the snippets/testing/test-suite-multi-configure-each-matching …

### LINKED ISSUE #21824: CCH22-27: Adjust the `snippets/testing/test-suite-multi-configure-each-matching` sample for configuration cache
The sample project located under [`subprojects/docs/src/snippets/testing/test-suite-multi-configure-each-matching`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/testing/test-suite-multi-configure-each-matching) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build script in the `groovy` part of the sample project needs to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-testing-test-suite-multi-configure-each-matching_groovy_checkTask.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-testing-test-suite-multi-configure-each-matching_groovy_checkTask.sample)
    ```
    Could not get unknown property 'configurations' for task ':checkDependencies' of type org.gradle.api.DefaultTask.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-testing-test-suite-multi-configure-each-matching_groovy_checkTask.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/jvm/jvm_test_suite_plugin.adoc`;

### PR DESCRIPTION
**Pull request by RicardoJiang**
Fixes #21824

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
Thanks for the submission, @RicardoJiang. Could you please fix 
 the DCO failure as described [here](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#fixing-dco-failuressigning-off-commits-after-submitting-a-pull-request)?

**Review by bamboo — APPROVED** [review]

**Comment by RicardoJiang** [comment]
> Thanks for the submission, @RicardoJiang. Could you please fix the DCO failure as described [here](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#fixing-dco-failuressigning-off-commits-after-submitting-a-pull-request)?

Done

**Comment by bamboo** [comment]
Thanks, @RicardoJiang. Could you please rebase your PR and fix the conflict in the release notes?

**Comment by RicardoJiang** [comment]
> Thanks, @RicardoJiang. Could you please rebase your PR and fix the conflict in the release notes?

Done, Thanks @bamboo

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Comment by h0tk3y** [comment]
@bot-gradle test and merge

**Pull request merged**
