### PR TITLE
Let `sanityCheck` work with the configuration cache enabled

### PR DESCRIPTION
**Pull request by eskatos**
on the `gradle/gradle` build

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
