### PR TITLE
Upgrade embedded Kotlin to 1.4.20-RC

### PR DESCRIPTION
**Pull request by eskatos**
What the title says.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
@bot-gradle test this

**Review by bamboo — APPROVED** [review]
💯 ❗

**Pull request merged**
