### PR TITLE
Make configuration cache reports content addressable

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by bamboo** [comment]
Thanks, @lptr.

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
This is failing: https://builds.gradle.org/viewLog.html?buildId=44703333&tab=buildResultsDiv&buildTypeId=Gradle_Master_Check_Platform_3_bucket16

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Pull request merged**
