### PR TITLE
Automatically capture tooling API console output in cross version tests

### PR DESCRIPTION
**Pull request by jvandort**
Previously, tests called collectOutputs in order to get the tests to collect stdout and stderr. This was the old way to capture these outputs, and new changes -- particularly ToolingApiConnector -- captures these outputs automatically.

Using this manual collect method and also the automatic collection caused the tests to capture duplicate output from the tests.

This change avoids the duplicate output capture, and also simplifes all tests that had to previously manually capture build output.

In addition to this, we improve some questionable cases of dynamic groovy typing by ensuring we are using proper static typing and also properly annotating closure parameters to improve IDE hints.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle help

**Comment by jvandort** [comment]
@bot-gradle test act

**Comment by jvandort** [comment]
@bot-gradle test act

**Comment by jvandort** [comment]
@bot-gradle test act

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test ACTR

**Review by reinsch82 — APPROVED** [review]
nice work :)

if ACTR runs through it should be fine.

**Pull request merged**
