### PR TITLE
Reduce memory usage

### PR DESCRIPTION
**Pull request by big-guy**

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test APT

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test APT

**Comment by big-guy** [comment]
@bot-gradle test APT

**Comment by big-guy** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test RFR

**Comment by big-guy** [comment]
@bot-gradle test RFR

**Comment by big-guy** [comment]
@bot-gradle test APT

**Review by tresat — APPROVED** [review]

**Comment by jvandort** [comment]
Superseded by https://github.com/gradle/gradle/pull/23609. Will merge release7x into release.

**Pull request closed without merging**
