### PR TITLE
Add some tests for ArchUnitFixture

### PR DESCRIPTION
**Pull request by wolfs**
Adds tests for `ArchUnitFixture.haveOnlyArgumentsOrReturnTypesThatAre`.

### CODE REVIEW

**Review by blindpirate — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@bot-gradle test and mereg

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Pull request merged**
