### PR TITLE
Compress verbose console output

### PR DESCRIPTION
**Pull request by kenzierocks**
### Context

This makes verbose output look more like plain output, for consistency.

Resolves: #3325

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

I'm not sure what to do about the one failing test. It fails because AnsiConsole outputs the "erase-forward" command after all newlines, but for some reason it didn't happen before this change. Should I update the test, or is there some bug that I'm hitting in AnsiConsole?

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by bmuschko** [comment]
@eriwen You self-assigned yourself to this PR. Were you planning to review it?

**Comment by bmuschko** [comment]
@eriwen Friendly ping. Were you planning to look at this?

**Comment by eriwen** [comment]
@bmuschko I was hoping to take care of this quickly but haven't. Perhaps you or @blindpirate should take it over.

**Comment by bmuschko** [comment]
@blindpirate Could you have a look?

**Comment by blindpirate** [comment]
Sure, will do it today.

**Comment by blindpirate** [comment]
Thanks @kenzierocks !

**Pull request merged**
