### PR TITLE
Ignore modified file events for directories on Windows

### LINKED ISSUE #12756: Ignore `MODIFIED` events for directories on Windows
If a file or directory is created in a directory, then on Windows the file watcher will report a `CREATED` event for the new file/directory and a `MODIFIED` event for the existing directory.

That causes too many things to be invalidated on Windows, since creating or removing a new directory in the `build` dir will cause all the outputs to be removed from the VFS. The best thing would probably be to ignore `MODIFIED` events for directories, either on the native-platform side or the Gradle side. I wonder if we could somehow obtain the information that the changed location is a directory when we receive the change event.

---
cc: @gradle/build-cache

### PR DESCRIPTION
**Pull request by lptr**
Incorporates https://github.com/gradle/native-platform/pull/287

Fixes #12756

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
Manual testing on Windows 8.1 Enterprise:

With Gradle 7.0.2 nothing shows on the `DEBUG` output. With this branch the following is visible in the `DEBUG` output:

```text
2021-06-10T17:09:44.541+0100 [DEBUG] [org.gradle.internal.nativeintegration.services.NativeServices] Native file system watching is not available for this operating system.
net.rubygrapefruit.platform.NativeIntegrationLinkageException: Native library 'native-platform-file-events.dll' could not be loaded for Windows 8.1 amd64.
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:61)
	at net.rubygrapefruit.platform.file.FileEvents.init(FileEvents.java:35)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:127)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:90)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:42)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\vagrant\.gradle\native\f152e854726e39df286aaa177b3f140d233d02db1042cffab86d50f0d3defff1\windows-amd64-min\native-platform-file-events.dll: The specified procedure could not be found
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:51)
	... 24 more
```

Nothing is visible on the `INFO` or normal outputs on either versions.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Pull request merged**
