### PR TITLE
gradle init creates .gitattributes #9583

### PR DESCRIPTION
**Pull request by teyckmans**
Signed-off-by: Tom Eyckmans <teyckmans@gmail.com>

### Context
Adds the creation of .gitattributes file in order to preserve correct new lines in the gradlew.bat file. This also solves a warning Git will give on the command line in case you don't add the .gitattributes file manually.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by teyckmans** [comment]
I based the org.gradle.buildinit.plugins.internal.GitAttributesGenerator on how the org.gradle.buildinit.plugins.internal.GitIgnoreGenerator is implemented.
- I did not find any documentation about the fact that the .gitignore file is generated.
- I did not find unit test only integration tests. So I just followed how it was done for the GitIgnoreGenerator.

**Comment by JLLeitschuh** [comment]
Related #9505

**Comment by teyckmans** [comment]
@JLLeitschuh thanks for pointer. 

I think it is a good idea to also include the links you added into the .gitattributes file that is being generated with gradle init. Can certainly help others to tweak the file if they have a need for it. What do you think?

Adding the entire .gitattributes as is needed for the Gradle repo itself feels excessive. We have no idea what users need to have an exchaustive .gitattributes file.

I think it is a good idea to keep the *.bat line the same with the comment to make it clear why we add it.

If you agree I will make these changes. 

Just a note on my availability. I am away on holiday for the coming 1,5 weeks after that I'll check back here to see what is needed.

**Comment by big-guy** [comment]
Thanks @teyckmans, this'll be in 6.0.

**Pull request merged**
