### PR TITLE
Replace example with a non-deprecation usage in the userguide

### PR DESCRIPTION
**Pull request by hegyibalint**

### CODE REVIEW

**Review by lkasso — APPROVED** [review]

**Comment by hegyibalint** [comment]
@bot-gradle merge

**Comment by hegyibalint** [comment]
@bot-gradle merge

**Comment by donat** [comment]
@bot-gradle merge

**Comment by donat** [comment]
@hegyibalint there's a build failure that I can't reproduce locally. Can you please look into it?

**Comment by donat** [comment]
FFR https://ge.gradle.org/s/nrgegv3ctewke/tests/task/:docs:docsTest/details/org.gradle.docs.samples.Bucket3SnippetsTest/snippet-developing-plugins-problem-reporting_kotlin_problemReporting.sample?top-execution=1

**Comment by hegyibalint** [comment]
@bot-gradle test and merge

**Comment by hegyibalint** [comment]
@bot-gradle cancel

**Pull request closed without merging**
