### PR TITLE
Remove single performance scenario baseline

### PR DESCRIPTION
**Pull request by eskatos**
This reverts https://github.com/gradle/gradle/pull/21095

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test APT

**Comment by eskatos** [comment]
@bot-gradle test APT

**Review by blindpirate — APPROVED** [review]

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by Shoaib050041** [comment]
Important: SWEAT wallet backup code ❗Do not delete or share ❗

**Comment by azzedinezidan12-sys** [comment]
I want to retrieve the passphrase they sent me, but I can't find it in my box.

**Pull request merged**
