### PR TITLE
Use consistent metric for available memory

### PR DESCRIPTION
**Pull request by oehme**
We were using different data sources for total and free physical
memory on Linux and MacOS, which lead us to detect memory pressure
were there was in fact none, e.g. when running in containers with
resource limits.

We now get both total and available memory from the same OS specific
data source.

### CODE REVIEW

**Comment by ghale** [comment]
I believe this distinction was introduced because the mbean info on linux and macos was incorrect.  It was returning _only_ unused memory and not counting filesystem cache as "free" memory.  So, we were always getting back a very low number and were expiring daemons really eagerly (because it seemed like the system was under heavy memory pressure even though it wasn't - most of the memory was just being used by fs cache).  Unless this has changed with the mbean, I'm skeptical that this is usable on those platforms.  

I wonder if we could detect that we're in a container and get the right information somehow?

**Comment by oehme** [comment]
I see, in that case we'd have to add even more complexity by introducing cgroup handling, similar to what [elasticsearch](https://zgrepcode.com/elasticsearch/apache/6.3.2/server/org/elasticsearch/monitor/os/osprobe.java) does. That's very unfortunate, as I'd much rather lean on the JDK team to get these things right :/

**Comment by oehme** [comment]
@ghale I've adjusted our code so that at least we use the same method for getting total and available memory. So even if we are using the wrong datasource (e.g. looking at host memory when we are inside a container), we at least won't detect bogus memory pressure.

**Comment by oehme** [comment]
@ghale this is ready for your review

**Pull request merged**
