### PR TITLE
Merge `release` into `master`

### PR DESCRIPTION
**Pull request by hegyibalint**
https://builds.gradle.org/buildConfiguration/Gradle_Release_Promotion_Nightly/60377611?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true

### CODE REVIEW

**Comment by hegyibalint** [comment]
@bot-gradle test and merge

**Comment by hegyibalint** [comment]
@bot-gradle test and merge

**Comment by hegyibalint** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
Superseded by https://github.com/gradle/gradle/pull/23543

**Pull request closed without merging**
