### PR TITLE
Remove CompileOptions.bootClasspath

### LINKED ISSUE #6297: Remove CompileOptions#bootClasspath(String)
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java#L272

### PR DESCRIPTION
**Pull request by wolfs**
Fixes #6297.

### CODE REVIEW

**Comment by wolfs** [comment]
Seems like the Android plugin is using `CompileOptions.bootClasspath` :(

**Comment by wolfs** [comment]
Upon closer inspection, only Android 2.x is using the method. So we need to bump the smoke test version and the version we use in our performance tests.

**Comment by wolfs** [comment]
@oehme The [xtend plugin](https://plugins.gradle.org/plugin/org.xtext.xtend) requires a new release to work with Gradle 5.0, since the latest released version still uses `bootclasspath`. Can you release a new version?

**Comment by wolfs** [comment]
Upgrading `perf-android-large` to AGP 3.1 also would need to be reviewed: https://github.com/gradle/perf-android-large/compare/android-30...gradle:android-31

**Comment by wolfs** [comment]
As well as for the `perf-android-k-9` project: https://github.com/gradle/perf-android-k-9/compare/android-30...gradle:android-31

**Comment by oehme** [comment]
@wolfs You can remove the Xtend plugin from the smoke tests, it's not widely used enough. I'll fix it when I find some time.

**Comment by wolfs** [comment]
@oehme I can do that. Note that the problem is already fixed on the `master` of the xtend plugin, so it only requires a new release to work with Gradle 5.0.

**Comment by big-guy** [comment]
@wolfs it looks like AndroidDexingSoakTest also needs Android 2.x

**Comment by wolfs** [comment]
@big-guy Thanks! Should be fixed by https://github.com/gradle/gradle/commit/10d67e25ad290c088e439e6851d9f77c9321074b.

**Pull request merged**
