### PR TITLE
Consolidate jvm-test-suite plugins into single project

### PR DESCRIPTION
**Pull request by tresat**
Send `JvmTestSuite` and `JvmTestSuiteTarget` to `language-jvm` in order to make `plugins-java` -> `plugins-jvm-test-suite` -> `plugins-java-base` as desired.

This seems an appropriate place for it, considering the JVM dependencies block also live here.

Minor adjustments to other project's dependencies to account for the consolidation.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]

**Review by jvandort — COMMENTED** [review]
How come we didn't move `JvmTestSuite` and `JvmTestSuiteTarget` to `plugins-jvm-test-suite`? That sounds more correct to me than `language-jvm`

**Comment by tresat** [comment]
> How come we didn't move `JvmTestSuite` and `JvmTestSuiteTarget` to `plugins-jvm-test-suite`? That sounds more correct to me than `language-jvm`

It needs to be able to return `JvmComponentDependencies`, which lives in `language-jvm`.  I tried moving that class up, but that's no good.  Considering the other stuff that lives in `language-jvm`, I don't think it's the worst thing to include these interfaces, too.

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
This is probably fine for now, but I think it really does make sense that `JvmTestSuite` and `JvmTestSuiteTarget` belong in `plugins-jvm-test-suite`. 

Why can't `plugins-jvm-test-suite` depend on `language-jvm`?

**Comment by tresat** [comment]
> This is probably fine for now, but I think it really does make sense that `JvmTestSuite` and `JvmTestSuiteTarget` belong in `plugins-jvm-test-suite`.
> 
> I mean look at the name. If `JvmTestSuite` doesn't belong in `plugins-jvm-test-suite` then I don't know whats right anymore
> 
> Why can't `plugins-jvm-test-suite` depend on `language-jvm`?

Becuase `JavaPluginHelper` lives in `plugins-java-base` and needs to reference the `JvmTestSuite` type.  But, pulling on these threads a little more led to #26594

**Pull request merged**
