### PR TITLE
Use `ProjectInternal` in `ProblemReportingProject`

### PR DESCRIPTION
**Pull request by 6hundreds**
`ProjectInternal` was changed to `DefaultProject` with following usage of `DefaultProject` API in attempt to close a "hole" in dynamic invocations detection. However, later this approach was reverted back in https://github.com/gradle/gradle/pull/26872 with some enhancements and I'm forgot to return back the types of `referrer` and `delegate`.

The reason, why the scenario from DV tests highlighted the issue is a level of nesting of subrojects - when a parent of a project becoming `ProblemReportingProject`, it can't be casted to `DefaultProject` obviously.

Added a test, that validates similar level of nesting

The test reproduced the ClassCastExcepton producing this stacktrace:
```
java.lang.ClassCastException: class org.gradle.configurationcache.ProblemReportingCrossProjectModelAccess$ProblemReportingProject cannot be cast to class org.gradle.api.internal.project.DefaultProject (org.gradle.configurationcache.ProblemReportingCrossProjectModelAccess$ProblemReportingProject and org.gradle.api.internal.project.DefaultProject are in unnamed module of loader 'app')
	at org.gradle.configurationcache.ProblemReportingCrossProjectModelAccess.wrap(ProblemReportingCrossProjectModelAccess.kt:154)
	at org.gradle.configurationcache.ProblemReportingCrossProjectModelAccess.access(ProblemReportingCrossProjectModelAccess.kt:119)
	at org.gradle.api.internal.project.DefaultProject.getRootProject(DefaultProject.java:384)
	at org.gradle.api.internal.project.DefaultProject.getRootProject(DefaultProject.java:379)
	at org.gradle.api.internal.project.DefaultProject.<init>(DefaultProject.java:239)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2097)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:524)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)

```

### CODE REVIEW

**Comment by 6hundreds** [comment]
@bot-gradle test this

**Comment by 6hundreds** [comment]
@bot-gradle help

**Comment by 6hundreds** [comment]
@bot-gradle test this

**Review by abstratt — APPROVED** [review]
LGTM!

**Review by bamboo — APPROVED** [review]

**Comment by 6hundreds** [comment]
@bot-gradle merge

**Pull request merged**
