### PR TITLE
Update embedded Kotlin from 1.8.20 to 1.8.21

### PR DESCRIPTION
**Pull request by eskatos**
See https://github.com/JetBrains/kotlin/releases/tag/v1.8.21

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test APT

**Review by jbartok — APPROVED** [review]

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Review by lkasso — COMMENTED** [review]
Late but the update to docs looks good.

**Pull request merged**
