### PR TITLE
Bump the PMD version used by the plugin to 5.6.1

### PR DESCRIPTION
**Pull request by sschuberth**
This replaces PR #1623.

## Context
To benefit from the fix for https://github.com/pmd/pmd/issues/232. This also includes the fix for https://github.com/pmd/pmd/issues/337.

#### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

#### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by sschuberth** [comment]
I have verified that

    ./gradlew codeQuality:integTest --tests org.gradle.api.plugins.quality.PmdPluginAuxclasspathIntegrationTest

passes locally.

**Comment by bmuschko** [comment]
What was the actual issue that has been fixed? Can you point us to a description of it?

Did you run the tests you mentioned above on Windows?

**Comment by sschuberth** [comment]
> What was the actual issue that has been fixed? Can you point us to a description of it?

The link is in the commit message: https://github.com/pmd/pmd/issues/337

> Did you run the tests you mentioned above on Windows?

Yes, because only Windows was affected, as only Windows does not permit to delete unclosed files.

**Comment by sschuberth** [comment]
@bmuschko Meanwhile PMD 5.6.0 was released, and I've upgraded my PR to it.

**Comment by adangel** [comment]
@sschuberth Could you please update this PR to PMD 5.6.1 - the original fix (in 5.5.6 and 5.6.0) was unfortunately incomplete and caused another problem. PMD 5.6.1 has the final fix in it (as well es 5.5.7). See https://github.com/pmd/pmd/issues/364 / https://github.com/pmd/pmd/commit/9fae304b6f895d9d517842e720622fd1ca68188e
Thanks!

**Comment by sschuberth** [comment]
Done @adangel, thanks for notifying.

**Comment by eriwen** [comment]
@w25r please don't forget to add this to release notes, thanking the contributor.

**Pull request merged**
