### PR TITLE
Remove test for unsupported old gradle version To Release

### PR DESCRIPTION
**Pull request by reinsch82**
- https://github.com/gradle/gradle-private/issues/3834

### CODE REVIEW

**Comment by reinsch82** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
Note that the milestone should still be 8.2 RC1

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle help

**Comment by reinsch82** [comment]
@bot-gradle test and merge

**Pull request merged**
