### PR TITLE
Another round of JUnit test refactorings

### PR DESCRIPTION
**Pull request by ghale**
Refactors several more tests to be more understandable and manageable.

- Splits the test reporting test into two different functional tests.  One to test functionality across different junit frameworks/versions (AbstractTestReportingIntegrationTest) and another to test framework/version-agnostic functionality (TestReportTaskIntegrationTest).
- Extracts a TestNG test that was buried in the TestOutputListener junit multiversion test into its own test class.

### CODE REVIEW

**Comment by ghale** [comment]
@bot-gradle test this

**Review by octylFractal — APPROVED** [review]

**Comment by ghale** [comment]
@bot-gradle test and merge

**Comment by ghale** [comment]
@bot-gradle test and merge

**Comment by ghale** [comment]
@bot-gradle test and merge

**Pull request merged**
