### PR TITLE
Fix links in plugin doc which go to non-existant DSL pages

### PR DESCRIPTION
**Pull request by tresat**
- Go to existant javadoc instead.

### CODE REVIEW

**Review by DPUkyle — APPROVED** [review]

**Comment by big-guy** [comment]
@bot-gradle test BD

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
