### PR TITLE
Re-enable thread dump on Linux

### PR DESCRIPTION
**Pull request by blindpirate**
In the past we enabled thread dump but soon observed hanging build
on Windows. Now let's at least enable it on Linux to help
troubleshoot timeout build and flaky test.

If lucky enough, we should see the thread dump for [this flaky test](https://ge.gradle.org/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Asia/Shanghai&tests.container=org.gradle.integtests.resolve.transform.ArtifactTransformParallelIntegrationTest&tests.sortField=FLAKY&tests.unstableOnly=true) in one or two days.

### CODE REVIEW

**Review by wolfs — COMMENTED** [review]
LGTM!

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle test this PT

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
