### PR TITLE
Fix init script snippets under config cache

### PR DESCRIPTION
**Pull request by abstratt**
Fixes: #21718

Part of #21027

### CODE REVIEW

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Comment by abstratt** [comment]
@bot-gradle test RFN

**Review by bamboo — APPROVED** [review]
👍

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Pull request merged**
