### PR TITLE
Close System.in after build

### PR DESCRIPTION
**Pull request by blindpirate**
### Context

See #3534 for more details.

In brief, after build finishes, a `DisconnectableInputStream` [will be created](https://github.com/gradle/gradle/blob/e7e9502dbcf5bf8e4ca5e0c1763a301372a9ed83/subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ContinuousBuildActionExecuter.java#L90) in interactive mode, and it never gets closed so it would keep reading in background thread, which might cause https://github.com/gradle/gradle-private/issues/975.

This PR close it after the build finishes. @big-guy I'm not sure it's appropriate so I'd like you to take a review for it.

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by blindpirate** [comment]
@big-guy would you like to take a look? It could be simple.

**Comment by blindpirate** [comment]
@big-guy Thanks for your review, that's a good idea and I've already put them into `DefaultCancellableOperationManager`. And we could reproduce this problem with simple code:

```
    public static void main(String[] args) throws Exception {
        PipedInputStream is = new PipedInputStream();
        PipedOutputStream os = new PipedOutputStream(is);
        new DisconnectableInputStream(is);
        
        is.close();

        Thread.sleep(1000);
    }
```

Unfortunately, I failed to find a way to reproduce this issue via a stable integration test.

**Comment by blindpirate** [comment]
@big-guy Do you mind taking a look again?

**Comment by bmuschko** [comment]
> And we could reproduce this problem with simple code...

Let's at least add a unit test with the code you have in the main method above. The test should fail before making the actual change to verify that we actually fixed something.

**Comment by blindpirate** [comment]
@bmuschko You're right. I added a unit test for this work. @big-guy Maybe you'd like to see it.

**Pull request merged**
