### PR TITLE
Update the Kotlin logo to the latest version

### LINKED ISSUE #20700: Update Kotlin logo used on code snippets
The Kotlin language has updated its branding, including its logo ([YouTrack issue](https://youtrack.jetbrains.com/issue/KT-46792/Update-community-graphic-assets-to-the-new-Kotlin-visual-style), other [YouTrack issue](https://youtrack.jetbrains.com/issue/KT-44340/Design-a-new-Kotlin-visual-style)).

Update the icon used on code snippets in Gradle website to the new one.
The new logos can be grabbed from the [Kotlin official website](https://kotlinlang.org/docs/kotlin-logo.html)

| Old | New |
| ---- | ----- |
|  Old icon |  New icon |

### Expected Behavior
Code snippets should show new Kotlin logo.

### Current Behavior
They show old Kotlin logo.

### Context
Gradle website and documentation.

### PR DESCRIPTION
**Pull request by mahozad**
The logo was grabbed from the [official Kotlin website](https://kotlinlang.org/docs/kotlin-logo.html ) and cleaned a little bit to reduce its size (no change in visuals).

Fixes #20700.

| Old | New |
| ---- | ----- |
|  Old icon |  New icon |

### Context
Kotlin has updated its branding including its logo. Update the logo used in code snippets on the website to the latest version.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test BD

**Comment by jvandort** [comment]
I'm seeing some weird behavior on my side with this, and I just want to confirm that this is working locally for you. I am currently looking into a bug where a duplicate copy of this image CSS is being included into the generated HTML -- except that the duplicate copy has the previous version of the image. Are you seeing this behavior?

**Comment by big-guy** [comment]
I think this one has to be updated: https://github.com/gradle/dotorg-docs/blob/master/docs-asciidoctor-extensions/docs-asciidoctor-extensions-base/src/main/resources/multi-language-samples.css

**Comment by jvandort** [comment]
@mahozad Thank you for this PR. I apologize for the very long turn-around time for this but I've finally gotten around to taking a look. After the input from @big-guy, it was clear that this PR was not sufficient, as there were changes required in a separate repository.

I've incorporated your changes into the separate repository, and now Gradle uses the new logo for its documentation!

**Pull request closed without merging**
