### PR TITLE
Ignore buildSrc directory that does not contain valid Gradle build

### LINKED ISSUE #13491: `buildSrc/build` should not be added to classpath if `buildSrc` contains no sources or build files.
### Expected Behavior
If `buildSrc` contains no source files and no build files `buildSrc/build` should not be added to the buildscript classpath.

### Current Behavior
`buildSrc/build` is always added to the buildscript classpath.

### Context

Projects may remove the `buildSrc` in favor of using either composite/included builds or publishing plugins to a nexus repository. Since `buildSrc/build` is not checked in to source control, it may linger around causing inconsistent build behavior.

This also causes remote build cache misses since the buildscript classpath will be different for all tasks in comparison to the remote server which ran the same build.

We encountered this at SoundCloud and made a little presentation about it: https://speakerdeck.com/runningcode/remote-build-cache-misses-and-how-to-solve-them-by-annoying-your-colleagues?slide=59
And you can watch it here: https://youtu.be/2frfDMJwvf4?t=1485

### PR DESCRIPTION
**Pull request by bigdaz**
Without this change, Gradle will execute a `buildSrc` build whenever a `buildSrc`
directory is detected, even if this directory contains no source files. This happens
frequently when migrating a build with `buildSrc` to one using composite builds:
the `buildSrc/build` directory which is normally ignored by git can be retained
resulting in unnecessary build invocation.

What's worse, the empty `buildSrc.jar` that is generated for an empty `buildSrc`
directory will be added to the build script classpath, which can trigger cache
misses for any custom tasks.

This fix addresses the issue by attempting to detect if `buildSrc` is indeed a valid
Gradle build, by checking for `settings.gradle[.kts]`, `build.gradle[.kts]` and for
a non-empty `src` directory. If none of these are found, the `buildSrc` directory
will be ignored, and the `buildSrc.jar` will not be added to the buildscript classpath.

Fixes #13491

### CODE REVIEW

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Review by ghale — APPROVED** [review]
This looks good to me.  I think we need to mention the new behavior in the release notes somehow, probably with respect to the improved caching behavior when empty buildSrc directories are lying around.

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Comment by bigdaz** [comment]
@bot-gradle test RFM

One last time...

**Comment by bigdaz** [comment]
@bot-gradle test RFM

**Pull request merged**
