### PR TITLE
Create software platform

### PR DESCRIPTION
**Pull request by tresat**
Creates the `software` platform and migrates the `antlr` subproject there.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]

**Comment by jvandort** [comment]
I'm curious why antlr is even part of Gradle. Shouldn't this be an external plugin?

I wonder if it makes sense to move this out of gradle/gradle

**Comment by jvandort** [comment]
Have there been any discussions about the architecture of the software platform?

I think there are multiple parts of the software platform. Dependency management for example is on a completely different level than antlr.

DM is "below" java/antlr/etc in the Dependency graph, so we will likely not want to co-locate these projects in the same platform.

IMO Antlr is a library, should only depend on public APIs, etc.

I feel like antlr and thing like build-init belong in a separate platform compared to DM

**Comment by tresat** [comment]
> I feel like antlr and thing like build-init belong in a separate platform compared to DM

I don't disagree.

First cut is just move the projects into the platform though.  Then we can and should analyze each platform in much more depth.

**Review by jvandort — CHANGES_REQUESTED** [review]
Undoing approval pending discussion

**Review by jvandort — COMMENTED** [review]
We discussed this and have agreed that projects like antlr and build-init likely belong in a separate platform than dependency-management. 

For the sake of moving files out of subprojects, we will continue with this PR even though these files will likely be moved again in the near future.

**Review by big-guy — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
