### PR TITLE
Update the asciidoctor plugin to 4.0

### PR DESCRIPTION
**Pull request by tresat**
This allows removal of the deprecated main property in JavaExecSpec.

This will need to updated from an alpha build after GA is released, but this proves this is the last usage of this property preventing a clean gradle build.

See: https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/643

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by eskatos** [comment]
It looks like our own build is working fine with 4.0 alpha.
Should we consider upgrading just the version used in our build to benefit from the new version and configuration cache compatibility?

**Comment by tresat** [comment]
@eskatos - Is it okay to update to an alpha?  I didn't do any testing with the configuration cache, I was only checking the property removal.

**Comment by eskatos** [comment]
We've been building documentation with alphas in the past. This is mostly about validating it works for us and the output.

**Comment by tresat** [comment]
I made a new PR to just update the plugin for the Gradle build [here](https://github.com/gradle/gradle/pull/23508).

**Comment by tresat** [comment]
Superseded by https://github.com/gradle/gradle/pull/27839

**Pull request closed without merging**
