### PR TITLE
Revert "Make snippets/dependencyManagement/customizingResolution-attributeSubstitutionRule..."

### PR DESCRIPTION
**Pull request by bamboo**
So the fix can be used as a demo during the hackathon kick-off.

This reverts commit a68732516493941d2f30ecd4e64af44a9cb5b575.

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle help

**Comment by bamboo** [comment]
@bot-gradle clean

**Comment by bamboo** [comment]
@bot-gradle test this

**Review by mlopatkin — APPROVED** [review]
:)

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
Hm, looks like it hadn't landed before the kickoff. Does it make sense to land it now, @bamboo?

**Comment by bamboo** [comment]
No, it doesn't. We should just make sure we keep the solutions consistent.

**Pull request closed without merging**
