### PR TITLE
Mark Kotlin assignment as enabled for IntelliJ when gradle.properties file doesn't exist

### PR DESCRIPTION
**Pull request by asodja**
Fixes https://github.com/gradle/gradle/issues/25381

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]
:+1:

**Review by lptr — APPROVED** [review]
LGTM.

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by asodja** [comment]
@bot-gradle cancel

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
