### PR TITLE
Make task descriptions consistent

### PR DESCRIPTION
**Pull request by grv87**
Most of task descriptions are already in third person. I propose to make this a rule.
Task descriptions are noticeable by users. Looking at `gradle tasks` output I'm annoyed that some tasks are out of line.

Signed-off-by: Basil Peace <grv87@yandex.ru>

### CODE REVIEW

**Comment by grv87** [comment]
Usage of definitive article is also inconsistent:
```
compileGroovy - Compiles the main Groovy source.
compileJava - Compiles main Java source.
```
I believe the article should not be used before names.
If you believe the opposite then we should fix `compileJava` description instead.

**Comment by blindpirate** [comment]
Thanks @grv87 !

**Comment by grv87** [comment]
@blindpirate, is there something wrong so that you reverted the commit?

**Comment by blindpirate** [comment]
@grv87 Yes, I made a mistake - I should have started a CI job to verify this PR. After this PR  was merged, there're several failures on our CI so I reverted to avoid blocking other one's job. I'll try to redo it in a few days.

**Pull request merged**
