### PR TITLE
Add a logged warning if the JacocoReportBase::executionData is used improperly

### PR DESCRIPTION
**Pull request by JLLeitschuh**
### Context
Trying to configure the `JacocoReport` with the  [Junit 5](https://junit.org/junit5/) plugin is fraught with peril unless you know exactly what you are doing.
If you want to configure the Junit 5 test task with the current API a naive user would think that this is enough (hint, I was that naive user):

```kotlin
val junitPlatformTest: JavaExec by tasks
val sourceSets = java.sourceSets

task<JacocoReport>("jacocoJunit5TestReport") {
    executionData(junitPlatformTest)
    dependsOn(junitPlatformTest)

    sourceSets(sourceSets["main"])
    sourceDirectories = files(sourceSets["main"].allSource.srcDirs)
    classDirectories = files(sourceSets["main"].output)
    reports {
        html.isEnabled = true
        xml.isEnabled = true
        csv.isEnabled = false
    }
}
```

However, this doesn't work (it fails silently) because you need to first bootstrap the `junitPlatformTest` task by calling `jacoco { applyTo(junitPlatformTest) }`. This results in the following code being required to configure it correctly:

```
val junitPlatformTest: JavaExec by tasks

jacoco {
    applyTo(junitPlatformTest)
}

val sourceSets = java.sourceSets

task<JacocoReport>("jacocoJunit5TestReport") {
    executionData(junitPlatformTest)
    dependsOn(junitPlatformTest)

    sourceSets(sourceSets["main"])
    sourceDirectories = files(sourceSets["main"].allSource.srcDirs)
    classDirectories = files(sourceSets["main"].output)
    reports {
        html.isEnabled = true
        xml.isEnabled = true
        csv.isEnabled = false
    }
}
```

The attached change should make it easier to immediately spot this problem when configuring jacoco.

I haven't attached tests but if you think it would be helpful to add a test that this gets logged, I can.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
DCO isn't smart enough to the email is the same but the capitalization is different.
Anything that can get configured to make it ignore casing?

**Comment by JLLeitschuh** [comment]
@eriwen, @eskatos, @oehme, @bamboo Can one of you take a look at this?

**Comment by eskatos** [comment]
I think emitting a warning makes sense. I fell into that same trap before.

There may be some builds out there relying on the actual behavior to be quiet, passing a bunch of tasks with only a few of them extended with Jacoco, on purpose. Making it less noisy should be considered, maybe by logging once per `executionData(...)` invocation.

There are two tasks impacted by the changes `JacocoReport` and `JacocoCoverageVerification`, which means at least two use cases. It'd also be nice to add some coverage. `JacocoPluginIntegrationTest` should be a good place for an integration test.

**Comment by JLLeitschuh** [comment]
I don't really have the time at the moment.

**Comment by bmuskalla** [comment]
@JLLeitschuh Is this still a problem given native JUnit platform support now in the `test` task?

**Pull request closed without merging**
