### PR TITLE
Final fields are excluded from the API jar (#819)

### PR DESCRIPTION
**Pull request by astellingwerf**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`
- [x] The pull request contains an appropriate level of unit and integration
test coverage to verify the behavior. Before submitting the pull request
I ran a build on your local machine via the command
`./gradlew quickCheck :platformJvm:check`.

### CODE REVIEW

**Comment by eriwen** [comment]
@melix Would you please give this a quick review? You had favorable comments about this change on #819. Note that this did pass Coverage builds in Linux. Windows builds failed due to CI maintenance.

**Comment by astellingwerf** [comment]
Is there anything I need to do more to get this fix to master?

**Comment by eriwen** [comment]
@astellingwerf I'm going to kick off a cross-version and performance test quick as is standard practice. Assuming those go well, I'll merge soon.

**Comment by eriwen** [comment]
Tests passed! This was rebased and merged with 27b823dc42bdab48388f52c5aca140e970571406 and 07373b80ad8cb2d8f461b5a3fadd0188b57e95ac. Thank you @astellingwerf!

**Pull request closed without merging**
