### PR TITLE
Update and restore test filtering

### PR DESCRIPTION
**Pull request by eriwen**
### Context
This applies a new Test Distribution plugin which fixes an issue where the number of remote agents is incorrectly calculated.

### CODE REVIEW

**Comment by eriwen** [comment]
@bot-gradle help

**Comment by eriwen** [comment]
@bot-gradle test ReadyForMerge please

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by eriwen** [comment]
@bot-gradle test and merge

**Comment by eriwen** [comment]
@bot-gradle help

**Comment by eriwen** [comment]
@bot-gradle clean

**Comment by eriwen** [comment]
@bot-gradle test and merge

**Pull request merged**
