### PR TITLE
Discard configuration cache state whenever incompatible tasks are scheduled

### LINKED ISSUE #19622: `notCompatibleWithConfigurationCache` and `org.gradle.unsafe.configuration-cache-problems=warn`
If `org.gradle.unsafe.configuration-cache-problems` is set to `warn`, `notCompatibleWithConfigurationCache` doesn't work and the cache is stored when the task is executed.

Repro: https://github.com/Reproducers/configuration-cache-repro

Task marked as not compatible: `./gradlew spotlessCheck`

### PR DESCRIPTION
**Pull request by bamboo**
Fixes #19622

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by JavierSegoviaCordoba** [comment]
Any workaround for this with 7.4?

**Comment by bamboo** [comment]
We haven't reached an agreement yet.

**Comment by JavierSegoviaCordoba** [comment]
As I mentioned in Slack, this behavior is completely blocking me in what I think is a reasonable use case which should work (marking an error A as a warning allowing configuration cache to work and disabling a task B that doesn't work correctly with configuration cache).

Any place to see comments about why this can be merged?

**Pull request closed without merging**
