### PR TITLE
Move testing related subprojects

### PR DESCRIPTION
**Pull request by ljacomet**
We agreed on having a root `testing` folder to contain those projects that are neither build logic nor production code.

Moved projects
* architecture-test
* distributions-integ-tests
* integ-test
* internal-architecture-testing
* internal-integ-testing
* internal-performance-testing
* internal-testing
* performance
* precondition-tester
* soak
* smoke-ide-test
* smoke-test

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by tresat — APPROVED** [review]

**Review by eskatos — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle merge

**Comment by ljacomet** [comment]
Performance test failures, let's retry in case it is simply flakiness

**Comment by ljacomet** [comment]
@bot-gradle merge

**Comment by ljacomet** [comment]
@bot-gradle merge

**Comment by ljacomet** [comment]
@bot-gradle merge

**Pull request merged**
