### PR TITLE
Upgrade to Groovy 2.5 [WIP]

### PR DESCRIPTION
**Pull request by lptr**
Let's see what breaks.

- [x] Upgrade to Groovy 2.5.1
- [x] Make compilation work (upgraded dependencies shared with Groovy)
- [x] Make test compilation work (fix some actually valid problems in the code)
- [x] Convert to using `def e = thrown Exception` in Spock tests
- [ ] Do not depend on `groovy-all` anymore (`Cannot infer Groovy class path because no Groovy Jar was found on class path` errors)
    Note: packaging of Groovy has changed, `groovy-all` now is just a skeleton POM that pulls in all the real dependencies
- [ ] Fix `@@sourceuri@@` substitution
- [ ] Fix annotation processor deprecation warnings during `CompileGroovy` tasks on certain integration tests

### CODE REVIEW

**Comment by lptr** [comment]
Branch build: https://builds.gradle.org/viewQueued.html?itemId=14924886

**Comment by lptr** [comment]
Had to upgrade a few libraries to get things to compile, and fix some actually wrong Groovy code in tests. Another change is that it seems Groovy 2.5 prefers the Spock syntax:

```groovy
def e = thrown IllegalStateException
```

vs

```text
IllegalStateException e = thrown()
```

...as the latter produces runtime errors in some cases. I fixed these in the code now.

Another big set of problems seems to be that a lot of integration tests just don't find the Gradle installation, because it's `null` here: https://github.com/gradle/gradle/blob/f57452deee2ea40cc83cd480b461f9b52fb9e473/subprojects/core/src/main/java/org/gradle/api/internal/classpath/DefaultModuleRegistry.java#L100

```text
Caused by: java.lang.NullPointerException
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.loadExternalModule(DefaultModuleRegistry.java:100)
	at org.gradle.api.internal.classpath.DefaultModuleRegistry.getExternalModule(DefaultModuleRegistry.java:91)
	at org.gradle.api.internal.DependencyClassPathProvider.localGroovy(DependencyClassPathProvider.java:79)
	at org.gradle.api.internal.DependencyClassPathProvider.findClassPath(DependencyClassPathProvider.java:49)
```

**Comment by lptr** [comment]
Ah, this is about `groovy-all` not being available anymore...

**Comment by lptr** [comment]
Build: https://builds.gradle.org/viewQueued.html?itemId=14929906

**Comment by wolfs** [comment]
FTR: Here is the issue for updating Spock: https://github.com/gradle/gradle-private/issues/1347

**Comment by marcphilipp** [comment]
I move the Spock upgrade issue to https://github.com/gradle/gradle/issues/6327.

**Comment by lptr** [comment]
Argh, do we now have annotation processors in the Groovy runtime?

```text
> Task :buildSrc:compileGroovy
Detecting annotation processors on the compile classpath has been deprecated. Gradle 5.0 will ignore annotation processors on the compile classpath. The following annotation processors were detected on the compile classpath: 'javaslang.match.PatternsProcessor'.  Please add them to the annotation processor path instead. If you did not intend to use annotation processors, you can use the '-proc:none' compiler argument to ignore them.
```

**Comment by lptr** [comment]
Build: https://builds.gradle.org/viewQueued.html?itemId=14935586

**Comment by lptr** [comment]
Down to 465 failed tests in https://builds.gradle.org/viewLog.html?buildId=14935586

**Comment by lptr** [comment]
I made a list of the errors I've bumped into in the description of the issue: those must be fixed, but there are sure to be others to come up while fixing all the remaining tests.

Upgrading to Spock 1.2 doesn't seem to be a requirement actually, so that's good.

**Comment by lptr** [comment]
Build: https://builds.gradle.org/viewQueued.html?itemId=15165355

**Comment by lptr** [comment]
Quick feedback build: https://builds.gradle.org/viewQueued.html?itemId=15311629

**Comment by lptr** [comment]
Closing and retrying in #6682.

**Pull request closed without merging**
