### PR TITLE
Preparatory work for making version catalogs work in kotlin-dsl `plugins {}` block

### PR DESCRIPTION
**Pull request by eskatos**
This PR is preparatory work for
* https://github.com/gradle/gradle/issues/22797

It does the following:
* unify the use of `PluginDependenciesScope` for kts `plugins {}` block in script templates
* unify the use of `ScriptHandlerScope` for kts `buildscript {}` block in script templates
* deprecate `ScriptHandlerScopeDelegate`
* add deprecation nagging for deprecated delegates
* add more test coverage for `PartialEvaluator`
* fix some version catalog tests for the configuration cache
* fix and refine kdoc and comments around kotlin-dsl compilation and evaluation
* rename members in `ResidualProgramCompiler` for clarity
* fix various formatting to limit future changesets

See individual commits for more details.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Review by jbartok — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
