### PR TITLE
ConsoleConfigureAction: Use rich output for Cygwin's mintty by default

### PR DESCRIPTION
**Pull request by sschuberth**
Previously, when running Gradle from Cygwin's / MSYS' mintty terminal,
Gradle did use plain output with --console=auto. Fix this by in fact
forcing ANSI output if the TERM environment variable is set to xterm and
no --color=plain is given.

### CODE REVIEW

**Comment by sschuberth** [comment]
@adammurdoch Mind having a look?

**Comment by eljobe** [comment]
@sschuberth Thanks for making the console output more robust for mintty.

All those poor tortured souls out there forced to develop software on Windows, will soon be in a little less pain because of your kindness,
Pepper

**Comment by eljobe** [comment]
@sschuberth Bad news. https://github.com/gradle/gradle/commit/f3ed866b502aec6b73ce80e0f6f94ae4ae2fe06d

As the commit message explains:
- This code isn't actually sensitive to whether or not there is a tty attached to STDOUT and STDIN.
- If we run ./gradlew tasks > out.log our TERM variable will still say xterm, but the STDOUT stream will not be a tty, and we shouldn't be formatting the output for a terminal.

The advice given internally by @adammurdoch is that you could provide an implementation of [ConsoleDetector](https://github.com/gradle/gradle/blob/master/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/console/ConsoleDetector.java) which forks a process to run `tty -s` which would reliably detect that the process has a tty connection. Adam also stresses that the logic of detection should really live in the ConsoleDetector, and not in ConsoleConfigureAction.

**Comment by sschuberth** [comment]
@eljobe Thanks for the feedback and thorough testing. I'll try to find the time to improve this over the next weeks.

**Comment by sschuberth** [comment]
Looks like the same functionality was now implemented by https://github.com/gradle/gradle/pull/8189 🎉

**Pull request merged**
