### PR TITLE
Set wrapper version on command-line

### PR DESCRIPTION
**Pull request by lptr**
Can now do:

    gradle wrapper --gradle-version 2.0

...without having a `Wrapper` task in `build.gradle`.

### CODE REVIEW

**Comment by breskeby** [comment]
Thanks lorant, we'll merge this soon!

cheers,
René

**Comment by lptr** [comment]
Hey Rene, is anything missing from this to be merged? Let me know and I'll fix it asap. Thanks.

**Comment by breskeby** [comment]
Only thing that is missing is time on my side, sorry. I'm currently abroad but will merge later. This will definitely make it into 2.4. 
cheers,
René

**Comment by talregev** [comment]
Can you add a feature?
Update version gradle from url configuration? 
I ask on [stackoverflow](http://stackoverflow.com/questions/28661192/gradle-wrapper-properties-file-from-url/28666861#28666861)

please help.

**Comment by lptr** [comment]
Thanks.

**Comment by breskeby** [comment]
merged manually. thanks again for the pull-request

**Pull request merged**
