### PR TITLE
Reverts #19370

### PR DESCRIPTION
**Pull request by DPUkyle**

### CODE REVIEW

**Comment by DPUkyle** [comment]
@bot-gradle QF

**Comment by DPUkyle** [comment]
@bot-gradle test QF

**Comment by DPUkyle** [comment]
@bot-gradle test RFR

**Comment by DPUkyle** [comment]
Failures with the parallel runner are present currently on the `release` branch. There are 2 perf regressions that merit discussion.

**Comment by OrionDevelopment** [comment]
Out of curiosity, because we are looking into using #19370 why does it need to be reverted? / Why was this reversion then closed without further comment?

**Pull request closed without merging**
