### PR TITLE
Fix BuildProgressCrossVersionSpec

### PR DESCRIPTION
**Pull request by mlopatkin**
The `7.1-rc.1` is not newer than `7.1` but it already contains
the feature.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test QF

**Review by donat — APPROVED** [review]

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
Pretest failure is an obvious flake and I really want to unbreak things.

**Comment by blindpirate** [comment]
Hi @mlopatkin when you're fixing `master` you can of course merge directly.

**Pull request merged**
