### PR TITLE
Remove spotless plugin

### PR DESCRIPTION
**Pull request by blindpirate**
As we're not using it at all.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@blindpirate Can you also open an issue in the spotless plugin tracker about the memory problems we experienced?

**Comment by blindpirate** [comment]
Sure!

@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
