### PR TITLE
Support camelCase shortcuts for configuration selection in dependencies/dependencyInsight task

### LINKED ISSUE #16141: Support camelCase shourtcuts for configuration selection in dependencies/dependencyInsinght task
Currently `--configuration` parameter in `dependencies` and `dependencyInsight` tasks requires user to type full configuration name.

I propose add `NameMatcher`-based support for camelCase in command line parameter to improve CLI UX like it done for projects and tasks selection.

In case of ambiguous configuration selected by camel case task should fail. 

### Expected Behavior
`gradle dependencies --configuration ruC` should work same as `gradle dependencies --configuration runtimeClasspath` if `ruC` there's only one configuration with such abbrev.

### Current Behavior
Configuration not found

### Context
Current zsh gradle autocompletion don't support configurations (and it would be be quite costly to do so) and when you investigate dependency resolution problems it would be useful.

Also I brought idea in gradle community [slack #general][1] and it found some support. 

[1]: https://gradle-community.slack.com/archives/CA7UM03V3/p1611706682059700

### PR DESCRIPTION
**Pull request by grossws**
This is follow-up for #16142 (it was reverted due to regression) with required fix to support rule-defined configurations with _exact match_ priority, so it shouldn't break existing workflow.

Fixes #16141

### Context
See #16141, #16142 and https://gradle-community.slack.com/archives/CA7UM03V3/p1611706682059700

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by grossws** [comment]
@donat, new PR with exact match priority (using `ConfigurationContainer#findByName`). I have to cherry-pick relevant commits onto master since trivial rebase was intermingled with revert commit. Since I did that with your commits DCO check fails (they didn't have `Signed-off-by` in them).

It works for your snippet from https://github.com/gradle/gradle/pull/16142#issuecomment-859496910 (and similar added to tests).

@lacasseio, I'll be glad if you could test it in your case.

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by grossws** [comment]
@donat, I can squash all these commits into one with mention that they are co-authored since only DCO check is unsuccessful. Please inform me if I should do it.

**Comment by donat** [comment]
>I can squash all these commits into one with mention that they are co-authored since only DCO check is unsuccessful. Please inform me if I should do it.

All of your commits are properly formatted so I think it's safe the ignore the DCO validation error.

**Pull request merged**
