### PR TITLE
Remove upload task remnants

### PR DESCRIPTION
**Pull request by jvandort**
Removes some classes which were previously, but are no longer, used by the Upload task

Follow-up for: https://github.com/gradle/gradle/pull/21440

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test qfl

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle help

**Comment by jvandort** [comment]
@bot-gradle clean

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
