### PR TITLE
Fix kotlinDslAccessors task for Configuration Cache

### PR DESCRIPTION
**Pull request by tresat**

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@ljacomet I'm not sure if this one is also aftermath of the scala change: https://builds.gradle.org/viewLog.html?buildId=46442035&problemId=29540

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
