### PR TITLE
Repository MetadataSources: add public API to retrieve current state

### PR DESCRIPTION
**Pull request by rpalcolea**
Signed-off-by: Roberto Perez Alcolea <rperezalcolea@netflix.com>

### Context
We encountered a use-case where we replace build repositories coming from customers to add some credentials but we do it so by removing the declared repo and add a new one with some internal opinions.

 This has been working great until now that we need to carry over things like `metadataSources `config. 

This change is to provide access to the `MetadataSources` state on a repo so it could be used to configure others.

Same way, this could be used to verify that repositories configurations are ok based provided information

This is for https://github.com/gradle/gradle/issues/10982

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by rpalcolea** [comment]
I wonder why 

```
Execution failed for task ':distributions:checkBinaryCompatibility'.
``` 

Since the interfaces have the `Incubating` annotation for new methods.

**Comment by ljacomet** [comment]
`master` is already on `6.1`, so your `@since` need to be changed to say `6.1`

**Comment by rpalcolea** [comment]
Oh that makes sense... oops tried to make it for 6.0! no luck for me, updating to 6.1 now. 

Let me know if it is still possible to get this one for 6.0 😅

**Comment by rpalcolea** [comment]
Closing this in favor of https://github.com/gradle/gradle/pull/11023

**Comment by rpalcolea** [comment]
Hi @ljacomet , opened this PR again with latest on master

**Comment by rpalcolea** [comment]
find this issue https://github.com/gradle/gradle/pull/12216#issuecomment-585497610

**Comment by bmuskalla** [comment]
Thanks @rpalcolea !

**Pull request merged**
