### PR TITLE
Extract registering `javaToolchains` extension to a separate plugin `jvm-toolchains`

### LINKED ISSUE #19234: JavaToolchainService not available on JVM ecosystem projects
### Expected Behavior

The `JavaToolchainService` service should be available on projects which do not apply the `java` base plugin, but are still working in the Java ecosystem.

### Current Behavior

In order to use toolchains, a project must apply the `JavaBasePlugin` plugin.

### Context

I have a multi-project build where most of the subprojects are Java project, and the root project is an aggregator. As part of aggregation, it needs to generate some Javadocs. The aggregation only requires the application of the `JvmEcosystemPlugin` (to get the usual disambiguation rules for dependency resolution). However, in order to use toolchains for Javadocs, I need to apply the `JavaBasePlugin` which does _too much_ and risks that folks would reintroduce things on the root project that they shouldn't.

It would be good if the toolchains service was created as part of the `JvmEcosystemPlugin`, or, possibly, as part of its own plugin which would then be applied by the `JavaBasePlugin`, but that one could apply independently in their own plugin.

### Steps to Reproduce 

Create a project which only applies the `jvm-ecosystem` plugin: the `JavaToolchainService` service isn't available as an extension.

### Your Environment

Build scan URL: https://ge.micronaut.io/s/n7fjvvx2lrvjq

### PR DESCRIPTION
**Pull request by h0tk3y**
Fixes #19234

### CODE REVIEW

**Comment by h0tk3y** [comment]
@bot-gradle test QFL

**Comment by h0tk3y** [comment]
@bot-gradle test QFL

**Comment by h0tk3y** [comment]
@bot-gradle test AFTN

**Review by jbartok — CHANGES_REQUESTED** [review]
LGTM, but it's hard to tell if everything works as expected. Would be good to have clear integration tests proving that:
- toolchains still work when only the java-base plugin is applied (we probably have this somewhere already)
- toolchains work when only the new plugin is applied

**Comment by h0tk3y** [comment]
@bot-gradle AFTN

**Comment by h0tk3y** [comment]
@bot-gradle clean

**Comment by h0tk3y** [comment]
@bot-gradle test AFTN

**Comment by h0tk3y** [comment]
@bot-gradle test AFTN

**Review by jbartok — APPROVED** [review]

**Comment by h0tk3y** [comment]
@bot-gradle test and merge

**Pull request merged**
