### PR TITLE
Followup on VFS properties

### PR DESCRIPTION
**Pull request by lptr**
Followup for https://github.com/gradle/gradle/pull/14265 and https://github.com/gradle/gradle/pull/14303.

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Comment by lptr** [comment]
@wolfs This follows up on the post-merge reviews of the PRs linked in the description. There is one thing missing which is to add more verbose logging (I only yet restored what we had before). I'll do that in a separate PR.

**Comment by lptr** [comment]
Ah, there's one thing missing, which is the restoring of the event listener in that test. I'll do that tomorrow.

**Review by wolfs — APPROVED** [review]
The changes look good to me!

**Pull request merged**
