### PR TITLE
Adopt the Covenant Code of Conduct

### PR DESCRIPTION
**Pull request by eriwen**
Add a Code of Conduct section to the README that links to
authoritative versions and outlines the scope of its
applicability.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [ ] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by lacasseio** [comment]
I get a 404 error at https://gradle.org/conduct/.

**Comment by lacasseio** [comment]
Hitting the 404 error makes me wonder if the email `conduct@gradle.com` was tested for receiving emails.

**Comment by eriwen** [comment]
@lacasseio see https://github.com/gradle/dotorg-site/pull/515 — Yes the email address has been tested.

**Comment by eriwen** [comment]
Merged with https://github.com/gradle/gradle/commit/fd67ec9145882dd6ccfd5b37609ef99a855b9f98

**Pull request closed without merging**
