### PR TITLE
Support --parameters compilation flag for Groovy lang

### LINKED ISSUE #2487: No support for Java8 parameter name reflection
### Expected Behaviour
The Groovy compiler (groovyc) [supports](http://docs.groovy-lang.org/docs/next/html/documentation/tools-groovyc.html) `-pa` or `--parameters` which enables parameter name reflection. I can see no way to pass this parameter from gradle

### Current Behaviour
See above

### Context
I am trying to enable parameter name reflection and need to be able to pass these compilation arguments to enable it.

### PR DESCRIPTION
**Pull request by katoquro**
Issue #2487

Signed-off-by: Andrew Malyhin <katoquro@gmail.com>

Fixes #2487

### Context
This functionality was requested by community and something similar already works for java. 
Additional details can be found at #2487

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by katoquro** [comment]
I'm not sure about doc point from the checklist. I've checked Javadoc and DSL but were should I update the User Guide? 

Thanks

**Comment by katoquro** [comment]
During the build tests have next messages: 
image

What is the policy about incubation in case of compiler flags? 
Can this functionality be released in Gradle 5.x?

**Comment by big-guy** [comment]
@katoquro Sorry, the earliest we'll be able to get to this will be 6.1.  There won't be any further 5.x releases with new features. 

For new APIs, generally what we do for docs is...
1. Add Javadoc and `@since` for the release the change is destined for
2. Add `@Incubating` to mark it as new
3. Update any DSL XMLs so the API shows up in the DSL reference (in this case `subprojects/docs/src/docs/dsl/org.gradle.api.tasks.compile.GroovyCompileOptions.xml`).

We're starting 6.1 development in the next couple of weeks, and I don't see anything seriously wrong with your PR, so we'll get back to you soon.

**Comment by katoquro** [comment]
@big-guy Thank you for your help!
I've updated docs and annotations but the checker forced me to set `@since 6.0` instead of `6.1`. 
I've tried to rebase on upstream master but the result is the same.

**Comment by big-guy** [comment]
Thanks @katoquro - this will be in 6.1

**Pull request merged**
