### PR TITLE
Let Kotlin DSL precompiled scripts support work without a configuration task

### PR DESCRIPTION
**Pull request by eskatos**

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
