### PR TITLE
Upgrade embedded Kotlin to 1.8.0-RC2 and use language/api 1.8

### LINKED ISSUE #23130: Make a decision wrt staying on Kotlin 1.7 with language 1.5 or moving to Kotlin 1.8 with language 1.8 for 8.0
Moving to 1.8.0 with language 1.8 is the desired goal. Kotlin 1.7.x contains regressions in the IR backend with language/api >= 1.6 that currently block us on language/api 1.5. Kotlin 1.8.0-RC2 will have the fixes for the ones we identified so far ([KT-55065](https://youtrack.jetbrains.com/issue/KT-55065), [KT-55068](https://youtrack.jetbrains.com/issue/KT-55068)).

### PR DESCRIPTION
**Pull request by eskatos**
This PR upgrades the embedded Kotlin to 1.8.0-RC2 and lets the Gradle Kotlin DSL use Kotlin language/api level 1.8.
All the Gradle Kotlin code is also now using Kotlin language/api level 1.8 and SAM conversions to classes.

---

See

* https://github.com/JetBrains/kotlin/releases/tag/v1.8.0-RC
* https://github.com/JetBrains/kotlin/releases/tag/v1.8.0-RC2
* Fixes #23130 

---

Note that this branch currently uses the first RC and ignores tests, snippets and samples broken by it and fixed in RC2.
RC2 is not out yet but development versions have been successfully tested.
To upgrade this branch to RC2 once it is out, the following should be done:

* [x] Replace `1.8.0-RC` by `1.8.0-RC2` in all files
    except in `build-logic-commons/gradle-plugin/build.gradle.kts`
* [x] Include commits from the [eskatos/kotlin/embedded-1.8.0-RC2-NEXT](https://github.com/gradle/gradle/compare/eskatos/kotlin/embedded-1.8.0-RC2...eskatos/kotlin/embedded-1.8.0-RC2-NEXT) branch
    to unignore tests, snippets and samples broken in the first RC
    to adjust regression tests for the first RC
* [x] Update the reproducible hash of Gradle API Kotlin extensions JAR in `GradleApiExtensionsTest`
* [x] Publish `kotlin-dsl` plugins 4.0.0-rc-2 (with next version 4.0.0)
* [x] Publish a wrapper snapshot from this branch
* [x] Update the wrapper on this branch with the newly published one
* [x] Update both the Kotlin version and `kotlin-dsl` plugin version
    in `build-logic-commons/gradle-plugin/build.gradle.kts`
    adding the required entry to `verification-metadata.xml`
* [x] Remove `verification-metadata.xml` entries for previous versions of the `kotlin-dsl` plugin artifact
* [x] Decide what to do with
    https://github.com/gradle/gradle-private/issues/3666
* [ ] Merge this PR
* [ ] Post merge: update the wrapper again with a non-branch snapshot

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test RFR

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
```
Update the reproducible hash of Gradle API Kotlin extensions JAR in GradleApiExtensionsTest
```
It seems it's not needed with an update from 1.8.0-RC to 1.8.0-RC2

**Comment by asodja** [comment]
@bot-gradle test RFN

**Comment by asodja** [comment]
@bot-gradle test APT

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
