### PR TITLE
Improve comparing fingerprint strategies in DefaultCurrentFileCollectionFingerprint

### PR DESCRIPTION
**Pull request by wolfs**
This is a follow up of #17740, which addresses https://github.com/gradle/gradle/issues/17740#discussion_r673067346.

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test QFL

**Review by marcphilipp — COMMENTED** [review]
This should not break anything in the GE Maven extension. 🤞

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
