### PR TITLE
Introduce dependency analysis plugin

### PR DESCRIPTION
**Pull request by ljacomet**
Perform clean up for core project and all its project dependencies.

The `projectHealth` task is wired into `sanityCheck`. It will fail if projects already analyzed regress.

A lot remains to be done:
* Complete applying recommendations for all main source sets of all projects
* ~Investigate if we can use the plugin as well for test sources~ this is now an option for arbitrary source sets but will be done in a second phase.

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by lptr** [comment]
What's the plan with this one?

**Comment by ljacomet** [comment]
To continue as soon as possible ...

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by cobexer** [comment]
@bot-gradle test this without PTS

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle merge

**Comment by ljacomet** [comment]
I am sending this for merge now that I have a green PR feedback build.
There is more work to be done, but this is the start of having enforced API / Implementation separation in Gradle's own code base.

**Pull request merged**
