### PR TITLE
Pin setup-java to v2

### PR DESCRIPTION
**Pull request by nuhkoca**
### Context

Updating the [setup-java](https://github.com/actions/setup-java) action to v2. 

- V2 supports custom distributions and provides support for `Zulu OpenJDK`, `Eclipse` `Temurin` and `Adopt OpenJDK`. V1 supports only `Zulu OpenJDK`.
- V1 supported legacy Java syntax such as 1.8 (same as 8) and 1.8.0.212 (same as 8.0.212). V2 dropped support for legacy syntax.
- Switched to `Temurin` which is an official successor of `Adopt OpenJDK`. See [here](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ljacomet** [comment]
@JLLeitschuh Can you take a look?

**Review by JLLeitschuh — APPROVED** [review]
This LGTM! Thanks for your contribution!

**Comment by JLLeitschuh** [comment]
@bot-gradle help

**Comment by JLLeitschuh** [comment]
@bot-gradle test and merge

**Comment by JLLeitschuh** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle cancel

**Comment by ljacomet** [comment]
We still want to include this but we are branching for 7.4 release first.

@nuhkoca Could you also take care of fixing the DCO?

**Comment by nuhkoca** [comment]
@ljacomet Thanks, signed off!

**Comment by ljacomet** [comment]
@nuhkoca Sorry, I should have warned you. We have branched for Gradle 7.4 and this PR has now `release` as its target.
Your rebase caused you to pull commits that should not go on `release`.

Can you rebase against `release` with only your commit?

**Comment by nuhkoca** [comment]
@ljacomet I think I did something bad 😬 will try to open a new PR, that went over my head, sorry.

**Pull request closed without merging**
