### PR TITLE
Preserve order of operations required by build scans when loading from cache

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by bamboo** [comment]
@bot-gradle test RFM

**Comment by bamboo** [comment]
@bot-gradle test this

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
I have fixed the verification problem on master.

@bot-gradle test and merge

**Pull request merged**
