### PR TITLE
Include task origin plugin in TaskOperationDescriptor

### PR DESCRIPTION
**Pull request by marcphilipp**
The plugin that registered a task is now reported to TAPI progress
listeners as a `PluginIdentifier` returned from
`TaskOperationDescriptor.getOriginPlugin()`.

### CODE REVIEW

**Comment by marcphilipp** [comment]
I've added another commit that now also captures the origin plugin for tasks created from within project evaluation listener callbacks such as `afterEvaluate {}` and configuration callbacks of domain object collections such as `all {}`.

@oehme PTAL!

**Comment by oehme** [comment]
Awesome!

**Comment by breskeby** [comment]
kudos to @tomdcc who did the lifecycle listener work here.

**Comment by marcphilipp** [comment]
Thanks, @breskeby and @tomdcc! 👍

**Comment by tomdcc** [comment]
Nice!

**Pull request merged**
