### PR TITLE
Exclude test-kit-groovy-version snippet from Java12+ run

### PR DESCRIPTION
**Pull request by 6hundreds**
Fixes https://github.com/gradle/gradle-private/issues/3637

### CODE REVIEW

**Comment by 6hundreds** [comment]
@bot-gradle test this

**Review by mlopatkin — APPROVED** [review]
lgtm. This is a better approach than relying on "we're only testing on 11 and 18", sorry for missing that in the previous review.

**Comment by mlopatkin** [comment]
@bot-gradle test RFR

**Comment by 6hundreds** [comment]
@bot-gradle test RFR

**Comment by 6hundreds** [comment]
@bot-gradle test RFR

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Review by blindpirate — APPROVED** [review]

**Pull request merged**
