### PR TITLE
Fix bad link to CreateStartScripts dsl doc in Application Plugin doc

### PR DESCRIPTION
**Pull request by isker**
### Context
https://docs.gradle.org/current/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html does not 404.

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.application.CreateStartScripts.html does.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by marcphilipp** [comment]
Yes, for the sake of consistency I think it should go to the DSL docs as well.

**Comment by isker** [comment]
Got it.  Should be good now.

**Comment by marcphilipp** [comment]
@isker Thanks! Could you please rebase your branch onto `master`? Otherwise, our CI build won't pass.

**Comment by isker** [comment]
Now realize that I blew away your acknowledgement commit.  Sorry for making this so painful.

**Comment by marcphilipp** [comment]
No worries, thanks @isker!

**Pull request merged**
