### PR TITLE
Track user code context

### PR DESCRIPTION
**Pull request by jvandort**
ProblemDiagnostics exposes the source of the user code which triggered the problem. The source is provided by the UserCodeApplicationContext

This makes the current executing plugin accessible to the `DeprecationLogger`

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gardle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by adammurdoch — APPROVED** [review]
👍 looks great

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
