### PR TITLE
Documentation layout update

### PR DESCRIPTION
**Pull request by asodja**
This updates the documentation layout as discussed: with a fixed navigation bar and a reorganization of navigation content.

It does not fix the mobile navigation issue though.

cc. @rlucha

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by asodja** [comment]
@bot-gradle cancel

**Comment by asodja** [comment]
@big-guy I canceled it. We also have to update dotcom-docs I think: https://github.com/gradle/dotcom-docs/pull/116

**Comment by asodja** [comment]
But it is ready for 7.4 now after the dotcom-docs was also fixed.

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
