### PR TITLE
Do not try to load external dependencies from classpath

### PR DESCRIPTION
**Pull request by wolfs**
For some projects `gradle-core-3.0.0.jar` from the AGP is on the
classpath and would be picked up when trying to run from IDEA.

### CODE REVIEW

**Comment by wolfs** [comment]
That blew up pretty bad - let me take another look.

**Comment by jjohannes** [comment]
This would break if Gradle was checked out into a directory called "caches". Unlikely maybe, but still...

Another solution would be to check if the `gradle-<module-name>-classpath.properties` file is in the jar. Only if it is present, the jar would be considered a module. We would only do the check for jars located outside of the Gradle installation. Wdyt?

**Comment by wolfs** [comment]
@jjohannes Better now?

**Comment by jjohannes** [comment]
Looks very good to me. Unfortunately there are still failing CI builds.

**Comment by wolfs** [comment]
@jjohannes Should be fixed now.

**Pull request merged**
