### PR TITLE
allow to configure file exclusions from reports

### LINKED ISSUE #20026: jacoco-report-aggregation should allow for exclusions
### Expected Behavior
When a subproject specifies a file or pattern to be excluded from the test coverage report (jacocoTestReport), the jacoco-report-aggregation should not include the specified file or pattern in the output html report.

### Current Behavior
The jacoco-report-aggregation plugin's output seems to ignore the excluded files that were specified in the subproject's build script.

Example: If I have subprojectA that uses the jacoco plugin and the following in `subprojectA/build.gradle.kts`...
```
val coverageExcludes = listOf("somelib/**)
tasks.jacocoTestReport {
    reports {
        html.required.set(true)
        xml.required.set(true)
        csv.required.set(false)
    }
    classDirectories.setFrom(
        classDirectories.files.map {
            fileTree(it).matching {
                exclude(coverageExcludes)
            }
        }
    )
}
```
... the report that is output to `subprojectA/build/reports/jacoco/test/html/` has the classes in `somelib/**` excluded. They do not appear, which is what I expected. However, when the `testCodeCoverageReport` task is run (invoking the jacoco-report-aggregation plugin functionality), the `somelib/**` classes are included in the report. I wish they were excluded!

This plugin's documentation is a little sparse and I have tried to figure out if the `allCodeCoverageReportSourceDirectories` or `allCodeCoverageReportClassDirectories` could help, but I cannot figure out how to use those and I don't see any samples or examples anywhere.

### Context
The jacoco aggregation report is showing coverage for lots of classes that I don't want to be on my report and so code coverage numbers are way off. 

This is especially difficult because I am moving a project from a single project setup to a multi-project setup and team members are wondering why we can't have nice coverage reports anymore.

### PR DESCRIPTION
**Pull request by GnusinPavel**
Fixes #20026

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by GnusinPavel** [comment]
I would be really happy, if some one helpl me to write a test for that logic. In the final use case it should look like
```groovy
jacocoTestReport {
    exclusions = ['**/foo', '**/bar']
}
```

**Comment by cobexer** [comment]
Thank you for your interest in Gradle.

The implementation does not match the proposed solution on the related issue.
* #20026

Please rework your implementation to match the design.

***
The original issue is about making sure that an aggregate report takes into account the exclusions declared in the original projects, your solution would imply duplicating that information for the aggregate task.

**Comment by GnusinPavel** [comment]
> Thank you for your interest in Gradle.
> 
> The implementation does not match the proposed solution on the related issue.
> 
> * [jacoco-report-aggregation should allow for exclusions #20026](https://github.com/gradle/gradle/issues/20026)
> 
> Please rework your implementation to match the design.
> 
> The original issue is about making sure that an aggregate report takes into account the exclusions declared in the original projects, your solution would imply duplicating that information for the aggregate task.

can you provide link to the comment, which describe the proposed solution, sorry if I miss understood some thing )

**Comment by cobexer** [comment]
@GnusinPavel Please have a look at the expected behavior in the linked issue.

If you believe that this PR fixes a different problem then open a separate issue.

**Comment by ov7a** [comment]
This pull request has been closed due to inactivity. If you intend to work on this pull request, please ask the team to reopen the PR.

**Pull request closed without merging**
