### PR TITLE
Force LF style checkouts

### PR DESCRIPTION
**Pull request by SUPERCILEX**

### CODE REVIEW

**Comment by oehme** [comment]
All our tests are run on Windows 7 and passing. See the latest master build containing [this particular test](https://builds.gradle.org/viewLog.html?buildId=14097871&buildTypeId=Gradle_Check_Quick_Java7_Oracle_Windows_core&tab=testsInfo).

Your git client may be misconfigured, e.g. converting `\n` to `\r\n`.

**Comment by SUPERCILEX** [comment]
@oehme Those are the default Git settings though, and I think external contributors should be able to build Gradle without having to turn too many knobs.

I've updated the test so it'll work regardless of what settings you have on which platform.

**Comment by oehme** [comment]
I'm on the fence about this. We have plenty of other tests that may have this issue and finding them all could be tedious. Also we have nothing to verify that it would actually work, because our CI servers have autocrlf turned off. autocrlf messes up caching, which is why we discourage its use on any Gradle project.

For that reason I'm more inclined to add a sentence to the contributor guide instead of fixing this one test.

**Comment by SUPERCILEX** [comment]
@oehme I think that makes sense. I've updated this PR to force LF style checkouts instead of fixing the test.

**Comment by SUPERCILEX** [comment]
On second thought, simply telling the Git client to checkout correctly seems easier.

**Pull request closed without merging**
