### PR TITLE
Trusted GPG-key should only accept 160-bit fingerprints

### LINKED ISSUE #23945: Backport trusting only full GPG keys in dependency verification [Backport 6.9.4]
* Backport #23667

### PR DESCRIPTION
**Pull request by ljacomet**
Backport from #23667 to 6.9.4

Fixes #23945

### CODE REVIEW

**Comment by ljacomet** [comment]
@hegyibalint If you get the time, I would appreciate. I think I did all that was needed to have the proper behavior and I tested it on a real project.
But if you see a missing bit from the changes when adapting the backport, let me know.

**Comment by ljacomet** [comment]
@bot-gradle test RfN

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by hegyibalint** [comment]
@ljacomet sorry, this one got lost in the sea.
I think in retrospect that it's all-right!

**Pull request merged**
