### PR TITLE
Add support for asdf-vm and linux java installations

### LINKED ISSUE #13871: Detect common Java installation locations
We should try and detect java installations for the following setups by default:
- [x] Windows
- [x] Linux
- [x] MacOSx
- [x] [SDKMAN](https://sdkman.io/)
- [x] ~~[jEnv](https://www.jenv.be/)~~
- [x] [jabba](https://github.com/shyiko/jabba)
- [x] [asdf](https://github.com/asdf-vm/asdf)

Especially for the operating systems, we have a lot of [existing mechanisms we can reuse](https://github.com/gradle/gradle/blob/master/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/AvailableJavaHomes.java) and replace.

### PR DESCRIPTION
**Pull request by bmuskalla**
Support for the asdf package manager.
Support for ubuntu and centos. These use the common location for package managers (yum, apt) as well as
using local rpm packages.

Fixes #13871

### CODE REVIEW

**Comment by bmuskalla** [comment]
This is based on the [windows pr](https://github.com/gradle/gradle/pull/14165) so please ignore the first 4 commits in this PR

**Comment by bmuskalla** [comment]
@bot-gradle test QF

**Comment by bmuskalla** [comment]
@bot-gradle test QF

**Comment by bmuskalla** [comment]
@bot-gradle test QF

**Review by ljacomet — APPROVED** [review]

**Pull request merged**
