### PR TITLE
Restore support for Kotlin 1.3.72

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
One test fails https://ge.gradle.org/s/2bb25s74vmwoa/tests/:smoke-test:smokeTest/org.gradle.smoketests.KotlinPluginSmokeTest/kotlin%20jvm%20and%20java-gradle-plugin%20plugins%20combined%20(kotlin=1.3.72)?anchor=e30&focused-exception-line=0-17&top-execution=1

```
> Task :compileKotlin FAILED
e: /home/tcagent1/agent/work/e67123fb5b9af0ac/subprojects/distributions-full/build/bin distribution/lib/kotlin-stdlib-1.5.21.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
e: /home/tcagent1/agent/work/e67123fb5b9af0ac/subprojects/distributions-full/build/bin distribution/lib/kotlin-stdlib-common-1.5.21.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
e: /home/tcagent1/agent/work/e67123fb5b9af0ac/subprojects/distributions-full/build/bin distribution/lib/kotlin-stdlib-jdk7-1.5.21.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
e: /home/tcagent1/agent/work/e67123fb5b9af0ac/subprojects/distributions-full/build/bin distribution/lib/kotlin-stdlib-jdk8-1.5.21.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
```

**Comment by bamboo** [comment]
It seems that's not such a critical use-case to support, right? That is, compiling a Gradle plugin against a version of Kotlin that is older than the version of Kotlin from the Gradle platform you're compiling against. WDYT?

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
:+1:

**Pull request merged**
