### PR TITLE
Add back the empty cycles list guard that was removed in 869916c5dc08…

### PR DESCRIPTION
**Pull request by fisakov**
…1a75af10548e76e2d1ccbc7687a9.

The test includes the test case attached to the issue #2293. Could not devise a minimal test case.

Issue #2293.

### Context

See the discussion in the issue: https://github.com/gradle/gradle/issues/2293

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [ ] [Link to Design Spec](https://github.com/gradle/gradle/tree/master/design-docs) for changes that affect more than 1 public API (that is, not in an `internal` package) or updates to > 20 files
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew quickCheck <impacted-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by bmuschko** [comment]
@lacasseio Do you think you could have a look? I remember you digging into that code a while ago.

**Comment by lacasseio** [comment]
@fisakov We are looking at validating this issue isn't caused by some underlying issue. Could you convert your test case attached to the issue into an integrated test (see [this example](https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy))?

**Comment by lacasseio** [comment]
@fisakov Could you also simplify the Ant script to a minimal reproducible example?

**Comment by fisakov** [comment]
@lacasseio As much as I'd like to help, I'm afraid there's little I can do now. I had tried to create a minimal test case, unfortunately without success -- reproducibility of the bug depends on what the target names are in the Ant script. Debugging seems to be the only option, but there's only so much time I can spend on this. Perhaps when I have more time, I can dig deeper. 

Is there any reason one should think that enabling the empty list guard is not safe?

**Comment by lacasseio** [comment]
The empty list could be a side effect of a real issue. Simply adding the guard would hide the issue. Given this is the first time we hear about such error and that code where this issue is happening is quite critical, we would rather spend more time and make sure there are no hidden issues.

**Comment by bmuschko** [comment]
@fisakov As explained by @lacasseio we won't accept the pull request as is. Are you still interested in finding out the actual issue that cause this behavior?

**Comment by fisakov** [comment]
Yes, I only need to find the time. The issue is important to us, so I'll
follow up with more details soon.

**Comment by oehme** [comment]
@fisakov I'm going to close this PR, please open another one once you have dug down to the root cause. Feel free to follow up with any question on the original bug report.

**Pull request closed without merging**
