### PR TITLE
Remove unnecessary use of ProjectLayout.files from the snippet

### PR DESCRIPTION
**Pull request by mlopatkin**

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, BD

**Comment by mlopatkin** [comment]
[the updated doc page](https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/59293806:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221209150718%2B0000/docs/userguide/more_about_tasks.html#sec:add_cached_input_output_methods)

**Review by bamboo — APPROVED** [review]
Nice! 👍

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
