### PR TITLE
Upgrade tested AGP versions

### PR DESCRIPTION
**Pull request by eskatos**
from 7.3.0 to 7.3.1
from 7.4.0-beta01 to 7.4.0-beta02
from 8.0.0-alpha01 to 8.0.0-alpha03

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Review by ljacomet — APPROVED** [review]
LGTM!

Though I wished we had a better way of handling expectations than a long list of results.

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
