### PR TITLE
Allow logging null value

### LINKED ISSUE #6661: Logging null results in DaemonDisappearedException
### Expected Behavior
Calling project.logger.quiet(null) prints 'null' to stdout (like other slf4j implementations)

### Current Behavior
Calling **project.logger.quiet(null)** (or any other level) makes Gradle hang for a while and finally results in the following message:
```
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=0d3c598c-02d4-462d-9491-7da05086c761, currentDir=D:\test}
Attempting to read last messages from the daemon log...
Daemon pid: 222216
  log file: D:\.settings\gradle\daemon\4.10\daemon-222216.out.log
----- Last  20 lines from daemon log file - daemon-222216.out.log -----
16:44:48.917 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1908932608, Committed: 1495793664}
16:44:53.917 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 34244706304, Free: 15189139456}
16:44:53.917 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 34244706304, Free: 15189139456}
16:44:53.917 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1908932608, Committed: 1495793664}
16:44:54.445 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
16:44:54.446 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:44:54.446 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:44:54.447 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:44:54.447 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:44:54.448 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:44:54.448 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:44:54.448 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:44:54.449 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:44:54.449 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:44:58.307 [DEBUG] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Received finished message: null
16:44:58.307 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 744: stopping connection
16:44:58.308 [DEBUG] [org.gradle.internal.remote.internal.inet.SocketConnection] Discarding EOFException: java.io.EOFException
16:44:58.308 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 797: received null
16:44:58.309 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 797: Received end-of-input from client.
16:44:58.310 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 744: stopping connection
```

### Cause
I did some debugging and found the root cause. 

An exception is thrown in 
org.gradle.internal.serialize.kryo.KryoBackedEncoder.writeString(CharSequence): IllegalArgumentException("Cannot encode a null string.")

This exception is caught in org.gradle.internal.remote.internal.inet.SocketConnection.dispatch(CharSequence) and rethrown as a MessageIOException

This exception is caught in
org.gradle.launcher.daemon.server.exec.LogToClient.AsynchronousLogDispatcher.dispatchAsync(OutputEvent) where _shouldStop_ is set to true which eventually causes the daemon to stop.

### Steps to Reproduce
run **gradlew bug**
```groovy
task bug{
    doLast {
        logger.quiet null
    }
}
```

### PR DESCRIPTION
**Pull request by cliffred**
Fixes #6661

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [x] Recognize contributor in release notes

### CODE REVIEW

**Comment by cliffred** [comment]
I've changed the commit message.

**Comment by thc202** [comment]
The read method was not changed though.

**Comment by cliffred** [comment]
Changed it

**Comment by cliffred** [comment]
I've created a unit test for it. The LoggingIntegrationTest does not call LogEventSerializer, so logging null actually would already work correctly there before the fix.

**Comment by oehme** [comment]
Thank you!

**Pull request merged**
