### PR TITLE
Url local cache

### PR DESCRIPTION
**Pull request by ethankhall**
This will allow Gradle to use resources that are only avaliable when
offline. This also makes it so that when you apply from the same url in
a lot of projects, the request will only be made once.

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation including proper use of `@since` and `@Incubating` annotations for all public APIs
- [ ] Recognize contributor in release notes

Contains changes from #1900 and the integration test fixes

### CODE REVIEW

**Comment by ethankhall** [comment]
I don't know if that would work, I don't know when the kotlin compiler runs.

**Comment by bamboo** [comment]
The execution model of Kotlin and Groovy scripts is very similar so it _should_ work given that both will be executed as part of `DefaultObjectConfigurationAction#applyScript`.

**Comment by ethankhall** [comment]
Would it only work if the file's extension is kts?

**Comment by bamboo** [comment]
@ethankhall `.gradle.kts`

**Comment by ethankhall** [comment]
@bamboo I added https://github.com/gradle/gradle-script-kotlin/blob/master/samples/task-dependencies/build.gradle.kts as the source to apply and got 

```Caused by: kotlin.KotlinNullPointerException
	at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.<init>(KotlinBuildScriptCompiler.kt:63)
	at org.gradle.script.lang.kotlin.provider.KotlinScriptPluginFactory.compilerFor(KotlinScriptPluginFactory.kt:62)
	at org.gradle.script.lang.kotlin.provider.KotlinScriptPluginFactory.compile(KotlinScriptPluginFactory.kt:50)
	at org.gradle.script.lang.kotlin.provider.KotlinScriptPluginFactory.create(KotlinScriptPluginFactory.kt:41)
	at org.gradle.configuration.ScriptPluginFactorySelector.create(ScriptPluginFactorySelector.java:102)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyScript(DefaultObjectConfigurationAction.java:104)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$000(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$1.run(DefaultObjectConfigurationAction.java:66)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:140)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:38)
	at Build_gradle.<init>(build.gradle.kts:2)
	at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.executeScriptOf(KotlinBuildScriptCompiler.kt:344)
	at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.executeScriptWithContextClassLoader(KotlinBuildScriptCompiler.kt:219)
	at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.executeCompileScript(KotlinBuildScriptCompiler.kt:126)
	at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.executeScriptBodyOn(KotlinBuildScriptCompiler.kt:110)
	at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler.access$executeScriptBodyOn(KotlinBuildScriptCompiler.kt:50)
	at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler$compileTopLevelScript$1.invoke(KotlinBuildScriptCompiler.kt:94)
	at org.gradle.script.lang.kotlin.provider.KotlinBuildScriptCompiler$compileTopLevelScript$1.invoke(KotlinBuildScriptCompiler.kt:50)
	at org.gradle.script.lang.kotlin.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:42)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:58)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:297)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:289)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:166)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:80)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:55)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:62)
	... 57 more```

I'll add the test, but mark it as not implemented.

**Comment by bamboo** [comment]
Thanks, @ethankhall.

The exception is due to [gradle-script-kotlin not expecting `scriptSource.resource.file` to be null](https://github.com/gradle/gradle-script-kotlin/blob/d25a507d1358ae3941692328728eda3f69075d8c/src/main/kotlin/org/gradle/script/lang/kotlin/provider/KotlinBuildScriptCompiler.kt#L63).

We can fix that in the next release.

**Comment by benmccann** [comment]
@ethankhall this one needs to be rebased

**Comment by ethankhall** [comment]
@benmccann do you know what happened to PluginServiceRegistry, GradleUserHomeScopePluginServices, SettingScopePluginServiceRegistry?

**Comment by benmccann** [comment]
I'll defer to the Gradle folks on that question. I'm not sure

**Comment by eskatos** [comment]
@ethankhall, the issue with Kotlin build scripts mentioned above is now fixed on `master`.

@big-guy, could you advise Ethan wrt. recent changes to services registries?

**Comment by bigdaz** [comment]
This was superseded by https://github.com/gradle/gradle/pull/2600

**Pull request closed without merging**
