### PR TITLE
Multiple deprecation removals

### PR DESCRIPTION
**Pull request by ljacomet**
It might be easier to review per commit.

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by jvandort — APPROVED** [review]
Not comfortable enough with tooling API to review those changes, but everything else LGTM

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by jbartok — APPROVED** [review]
LGTM!

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
