### PR TITLE
Retry for daemon connection timeout with older Gradle versions

### PR DESCRIPTION
**Pull request by jjohannes**

### CODE REVIEW

**Comment by pioterj** [comment]
@jjohannes Have you considered using existing generic test [retry mechanism](https://github.com/gradle/gradle/blob/f490bdf61bd9b4f5383cd9fb0d8ffbca93da8c32/subprojects/internal-testing/src/main/groovy/org/gradle/testing/internal/util/RetryRule.groovy)?

**Comment by jjohannes** [comment]
@pioterj The mechanism is used here :) See: https://github.com/gradle/gradle/blob/fbfd6300b7fc2089c2b9ae2ba032f843427cce4a/subprojects/tooling-api/src/testFixtures/groovy/org/gradle/integtests/tooling/fixture/ToolingApiSpecification.groovy#L64

**Comment by pioterj** [comment]
LOL :) I wasn't looking closely enough and it wasn't visible in the diff. Thanks :)

**Comment by jjohannes** [comment]
Thx @ghale!

**Pull request merged**
