### PR TITLE
Eclipse API for unresolved dependencies

### LINKED ISSUE #7733: Tooling API: Allow to explicitly retrieve information about unresolved dependencies
Original issue was posted here: https://issues.gradle.org/browse/GRADLE-1995

The Tooling API doesn't allow to get information about unresolved third-party dependencies.

### Expected Behavior
 There is some API to determine if the dependency is resolved (e.g. `IdeaSingleEntryLibraryDependency.isResolved()`)

### Current Behavior
 Unresolved dependencies are indistinguishable from resolved ones.

### Context
 As a workaround, Gradle Idea import has to rely on names of files produced by `UnresolvedIdeDependencyHandler` for this. It is very fragile approach, e.g. broken in 5.0-rc-2 with Idea 2018.2

### Steps to Reproduce (for bugs)

1. Go to $GRADLE_HOME/samples/java/quickstart;
2. Define, say, version '10.2' for 'commons-collections' dependency at 'build.gradle' there;
3. Start the program below:

```java
package org.jetbrains.plugins.gradle;

import org.gradle.tooling.GradleConnector;
import org.gradle.tooling.ModelBuilder;
import org.gradle.tooling.ProjectConnection;
import org.gradle.tooling.model.idea.*;

import java.io.File;


public class GradleStartClass {

  private static final String GRADLE_PROJECT_PATH = "/home/denis/dev/gradle/gradle-1.0-milestone-6/samples/java/quickstart";

  public static void main(String[] args) {
    test("/home/denis/dev/gradle/gradle-1.0-milestone-6"); // Don't expect exception here
  }

  private static void test(String gradleHome) {
    GradleConnector connector = GradleConnector.newConnector();
    connector.useInstallation(new File(gradleHome));
    connector.forProjectDirectory(new File(GRADLE_PROJECT_PATH));
    ProjectConnection connection = connector.connect();
    ModelBuilder<? extends IdeaProject> modelBuilder = connection.model(IdeaProject.class);
    IdeaProject project = modelBuilder.get();
    for (IdeaModule module : project.getModules()) {
      for (IdeaDependency dependency : module.getDependencies()) {
        if (dependency instanceof IdeaModuleDependency) {
          continue;
        }
        System.out.printf("Dependency: %s%n", ((IdeaSingleEntryLibraryDependency)dependency).getFile());
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by leonardobsjr**
Signed-off-by: Leonardo Jr <leonardobsjr@yahoo.com.br>

Fixes  #7733 

### Context

The way that Gradle reports unresolved dependencies is through a file with "unreleased dependency" on the name. Because of this, Buildship has to rely on parsing the file name to pinpoint the dependency problems. What i want is to create a better way for gradle to pass unresolved dependencies information to buildship.

https://github.com/eclipse/buildship/issues/263
https://github.com/eclipse/buildship/issues/999

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [x] Verify design and implementation 
- [x] Verify test coverage and CI build status
- [x] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by leonardobsjr** [comment]
While i do understand that this issue is directly related to IntelliJ, i was instructed to submit separate PR's if needed.

**Comment by leonardobsjr** [comment]
@donat Have you finished reviewing this?

**Comment by donat** [comment]
Running through CI...

**Comment by donat** [comment]
Side-note: a good follow-up email could be to do the same for the IDEA model.

**Comment by leonardobsjr** [comment]
I can start working on the IntelliJ model on another PR.

**Comment by donat** [comment]
Thank you for your contribution!

**Pull request merged**
