### PR TITLE
Improve doc test coverage (modelRules-Performance)

### PR DESCRIPTION
**Pull request by mlopatkin**
There are some changes in user-visible part of snippets, but nothing substantial - configuration cache compatibility and correctness.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, BD

**Comment by mlopatkin** [comment]
@bot-gradle test BD, PRF

**Review by 6hundreds — APPROVED** [review]
A lot of work! LGTM

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Pull request merged**
