### PR TITLE
Update configurations deprecated for consumption to be non-consumable

### LINKED ISSUE #22365: Update WarPlugin and ScalaBasePlugin configureConfigurations to produce error instead of warning on misuse

### PR DESCRIPTION
**Pull request by tresat**
Fixes #22365

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Review by octylFractal — APPROVED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
