### PR TITLE
Add configuration cache smoke tests for gradle/gradle local dev workflows

### PR DESCRIPTION
**Pull request by eskatos**
This PR adds coverage for local development workflows with the configuration cache enabled on the `gradle/gradle` build.
Subsequent PRs will try to fix the introduced tests.
This will allow us to make sure we don't introduce regressions for these workflows.

Still turning problems into warnings.
None of the added tests pass at this point and are annotated with `@NotYetImplemented`.
One can have a look at the reported problems and failures in the test reports on CI.

The test for building the Gradle documentation is `@Ignore`d for now as it takes 40 minutes to build and is known to be broken by at least the Asciidoctor plugin. It can be used for local investigations and ready to be enabled when it work.

We should get rid of those tests once our CI enables the configuration cache by default as all this will then be covered.

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test RFN

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test AST

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
