### PR TITLE
GRADLE-3299 Handle references to ${parent.artifactId} in pom files

### PR DESCRIPTION
**Pull request by finsterwalder**
- prior to this fix only ${parent.version} and ${parent.groupId} could be referenced

as discussed with Benjamin Muschko, I created a bugfix for the above mentioned bug/problem.

### CODE REVIEW

**Comment by bmuschko** [comment]
Great, thanks for providing a pull request. Could you please also add a test to `org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.GradlePomModuleDescriptorParserTest` that defines two different POM files - one for the resolved `pom.xml` and a `parent.xml`? What I'd expect in that test case is the use of `project.parent.groupId`, `project.parent.artifactId` and `project.parent.version`.

**Comment by finsterwalder** [comment]
I added an integration test, which shows, that the feature works.
The test fails, when I undo my previous commit.

**Comment by bmuschko** [comment]
Yes, exactly. Thanks!

**Comment by finsterwalder** [comment]
I fixed a test, that failed after my changes.
Is there anything else, I can/should do, to help this pull-request?

**Comment by bmuschko** [comment]
I think we are good for now. It's a matter of us finding the time to fully review and merge. Please bear with us.

**Comment by mark-vieira** [comment]
@finsterwalder Thanks for the PR. I've gone ahead and merged this. Since we've begun preparations for the Gradle 2.5 release this will be included in 2.6.

**Comment by finsterwalder** [comment]
@mark-vieira Great. Do you have a rough estimate, when 2.6 might be released?

**Comment by mark-vieira** [comment]
We typically release every 6-8 weeks and we are aiming to release 2.5 in the next couple of weeks.

**Pull request merged**
