### PR TITLE
Remove usage of legacy JUnit 4 rules in Spock examples

### PR DESCRIPTION
**Pull request by Vampire**
### Context
Using JUnit 4 and the `spock-junit4`  module is only necessary if you want to use JUnit 4 rules with Spock 2+.
For the `TemporaryDirectory` rule there is a built-in `TempDir` native extension as a replacement.

All other rules could be used on a best-effort basis with the `spock-junit4` module, but it is preferable to use native Spock extensions for that instead of JUnit 4 rules.

All the examples in the documentation add JUnit 4 as dependency and the `spock-junit4` module.
But this is absolutely unnecessary in all cases.
In some cases not a single `@Rule` was used and in the cases a `@Rule` was used it was always `TemporaryDirectory` which can easily be replaced by `@TempDir`.

This constellation which should only be used if you depend on JUnit 4 rules, more confuses users than it benefits and somehow gives the impression Spock would still use JUnit 4 or whatever. Anyway it is more confusing than anything else, as can also be seen for example at https://discuss.gradle.org/t/spock-tests-dont-run-with-gradle-7-groovy-3/40139/4 and https://gradle-community.slack.com/archives/CAHSN3LDN/p1626283884050700?thread_ts=1619218822.359300&cid=CAHSN3LDN.

This PR removes JUnit 4 and `spock-junit4` from all documentation samples and snippets and also replaces all Gradle internal usages of the `TemporaryDirectory` rule by the `@TempDir` extension.

My recommendation would even be to replace all the custom rules, by custom Spock extensions, but that is not in the scope of this PR which is mainly for better examples for the users.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@Vampire the failures are environmental and should be fixed by rebasing the PR. Can you do that?

**Comment by Vampire** [comment]
I rebased my 3 current PRs, so you could also retrigger those please :-)

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
