### PR TITLE
Versions update for 7.x

### LINKED ISSUE #27638: Backport dependency upgrades to 7.x
The following dependencies are candidates for backport due to CVEs impacting them:
 
* Update Ant to 1.10.13 (see #24797) and also the Ant part of #25892 and its follow up #25931. The rest of the updates there can be left out
* #26126
* #26150 
* #26817

### PR DESCRIPTION
**Pull request by ov7a**
Fixes #27638

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by ov7a** [comment]
@bot-gradle test this

**Comment by ov7a** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
LGTM, thanks for taking care of it.

See minor comment below

**Comment by ov7a** [comment]
@bot-gradle merge

**Review by Editguru — APPROVED** [review]

**Comment by ov7a** [comment]
@bot-gradle merge

**Comment by ov7a** [comment]
@bot-gradle merge

**Pull request merged**
