### PR TITLE
Do not omit build cache URI query parameters when accessing the cache

### LINKED ISSUE #12477: URI query parameters in HttpBuildCache are ignored
Some HTTP servers are using query parameters for authorization (e.g. Azure Blob Storage).
But currently the HttpBuildCache is ignoring any query parameters configured in the URI, preventing this authorization.

The `HttpBuildCacheService` is using `URI.resolve(...)`, which takes the query parameters from the argument only, so query parameters from the base URI are lost.

### PR DESCRIPTION
**Pull request by GisoBartels**
Fixes #12477

### Context
Query parameters in configured URI of HttpBuildCache are preserved.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] ~~Provide unit tests (under `<subproject>/src/test`) to verify logic~~
- [x] ~~Update User Guide, DSL Reference, and Javadoc for public-facing changes~~
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by GisoBartels** [comment]
Please let me know, if anything is missing.

**Comment by JLLeitschuh** [comment]
@GisoBartels would you be willing to resolve the merge conflicts?

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by lptr** [comment]
@bot-gradle test QF please.

**Comment by JLLeitschuh** [comment]
@GisoBartels can you provide an example of what this looks like from an API user perspective?

Also, what the transformation looks like when the URL is generated to actually make the GET/PUT request.

**Comment by GisoBartels** [comment]
@JLLeitschuh : The API was not really changed, because it was possible before to have query parameters in the user configured URL. But before, the query parameters were just ignored / cut off. Now the parameters are actually used in the requests to the remote cache without any transformations.

But feel free to close this PR. We no longer need it, since I developed our own remote build cache plugin.

**Comment by JLLeitschuh** [comment]
@GisoBartels do you mind linking to the plugin for others in the future? Then feel free to self-close.

**Comment by GisoBartels** [comment]
Sure, the mentioned remote build cache plugin can be found here:
[gradle-build-cache-azure-blob-storage](https://github.com/GisoBartels/gradle-build-cache-azure-blob-storage)

**Pull request closed without merging**
