### PR TITLE
Update java testing chapter

### LINKED ISSUE #12912: Testing in Java & JVM projects > Configuring integration tests - Adding some information to ease the guide follow up
### Related Samples

[Testing in Java & JVM projects > Configuring integration tests](https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests) could have a little more links & reminders to ease the implementation of integration tests.

### Context

As a new user of Gradle, I struggled a little bit in order to be able to execute integration tests with coverage following the [Testing in Java & JVM projects](https://docs.gradle.org/current/userguide/java_testing.html) guide.

My objective was to have unit and integration tests being separated as the user guide recommend, but also having jacoco test report being sent to [sonarcloud](https://sonarcloud.io).

When following the guide, focusing on the [Configuring integration tests](https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests) section, I would say that I've got slowed down due to three things 

### 1. Integration test was not executed
Didn't spent a lot of time on this, but maybe having one quick reminder would make things go smoother. When using JUnit 5, a `useJUnitPlatform()` must be added in the integration test task declaration (Example 15). Documentation is based on JUnit 4 so the example is fine like this but maybe adding a one sentence reminder just after the sample that send back to [Using JUnit 5](https://docs.gradle.org/current/userguide/java_testing.html#using_junit5) would do it ?

Or specific tabs for JUnit 5 in the sample ? It could look weird, it looks like there is a convention of only one tab per language in the guides. And doing it so would imply doing it for the whole guide. It seems to add a lot of changes.

### 2. Intellij Idea was displaying integration tests as source route instead of test route
Adding a small paragraph linking to [The IDEA Plugin](https://docs.gradle.org/current/userguide/idea_plugin.html) and other IDE plugins could help.

The IDEA Plugin page could have a sample displaying how to flag folders as test folders like this for an `intTest` sourceSet:
```
idea {
    module {
        testSourceDirs += project.sourceSets.intTest.java.srcDirs
        testSourceDirs += project.sourceSets.intTest.resources.srcDirs
    }
}
```
I haven't tested for Eclipse yet, there is maybe also something to do here. This could be added also. Are there other IDE plugins ?

### 3. JaCoCo report was not including integration test coverage

I had to add the task in JaCoCo test report with an `executionData()` call:
```
jacocoTestReport {
    reports {
        executionData(integrationTest)
    }
}
```

There is no mention of JaCoCo in the Testing Guide, JaCoCo has a guide on his own. I spent quite some time here, maybe we could add a sample about it in the [The JaCoCo Plugin > JaCoCo Report configuration](https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_report_configuration) and provide a link from the integration test section ?

## Follow up

I'm volunteer to participate on this and provide a pull request. Before starting, I would like to get inputs about this topic. Do you think it is relevant to add this ? How could it be added ? As I've never contributed on Gradle, I would very welcome opinion on my suggestions. Is providing links to other guides is ok (it helps keeping an encapsulated documentation :slightly_smiling_face: ) ? Would you prefer to have samples added directly into the testing guide ?

After this, I'm volunteer to be assigned on this issue and provide a pull request. :construction_worker_man:.

Thank you for building this tool and thank you in advance for the feedback !

### PR DESCRIPTION
**Pull request by tresat**
Fixes #12912

This updates the Java Testing and Idea Plugin chapters of the user guide, adding links to point readers to appropriate plugins and an additional snippet.

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle BD

**Comment by tresat** [comment]
@bot-gradle test BD

**Comment by tresat** [comment]
Changed docs for review visible here: https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/52337082:id/distributions/gradle-7.6-docs.zip!/gradle-7.6-20220518194231%2B0000/docs/userguide/java_testing.html

**Review by big-guy — CHANGES_REQUESTED** [review]

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
