### PR TITLE
No Deprecated Configurations In Build Init

### PR DESCRIPTION
**Pull request by Vampire**
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by Vampire** [comment]
Don't you write the release notes yourself usually?
I never did any release notes modification in my PRs afair.

**Comment by marcphilipp** [comment]
No worries, I'm the new guy. 😅

We can certainly take care of writing them but IMHO we wouldn't mind you doing the work for us. 😉

**Comment by Vampire** [comment]
Actually I'm not even sure what I should write there.
"Hey, we generate deprecated build scripts since 3.4.0 and finally we fixed our own stuff"? :-D

**Comment by marcphilipp** [comment]
Well, sounds about right... 😆  I added two commits to your branch and started a CI build.

**Comment by marcphilipp** [comment]
Thanks again, @Vampire! 👏

**Pull request merged**
