### PR TITLE
recover from broken wrapper

### PR DESCRIPTION
**Pull request by reinsch82**
feedback @big-guy

- part of: #12593

### CODE REVIEW

**Comment by reinsch82** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by reinsch82** [comment]
@bot-gradle test and merge

**Comment by reinsch82** [comment]
@bot-gradle test and merge

**Comment by reinsch82** [comment]
@test this

**Comment by reinsch82** [comment]
@bot-gradle test this

**Comment by reinsch82** [comment]
@bot-gradle test and merge

**Pull request merged**
