### PR TITLE
PMD: Default rule is now java-basic since the default version of PMD is > 5

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by vanniktech** [comment]
I just signed the CLA.

**Comment by pioterj** [comment]
Thank you for the pull request. Could you provide some context regarding this change? Was is raised on [Gradle Developer List](https://groups.google.com/forum/#!forum/gradle-dev) or is there a [Jira issue](https://issues.gradle.org/secure/Dashboard.jspa) associated with it?

**Comment by vanniktech** [comment]
Nope. I just saw the note when I wanted to know the default PMD version.

**Comment by pioterj** [comment]
Could you elaborate a little bit on this change? I don't know what note you are referring to.

**Comment by vanniktech** [comment]
[NOTE: should change default rule set to java-basic once we bump default version to 5.0+ this will also require a change to Pmd.run() (convert java-basic to basic for old versions, instead of basic to java-basic for new versions)](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.groovy#L54-L56)

Basically the rule name `basic` was renamed to `java-basic` starting with PMD 5.0. Since someone updated at one point the PMD [default version](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.groovy#L36) to 5.2.3 this 'legacy' can be removed.

**Comment by pioterj** [comment]
Thank you for clarifying.

**Comment by big-guy** [comment]
@pioterj Since I was the last through the PMD code, I thought I'd take a look at this.  I think this looks OK to merge if the integ tests pass locally.  Seems to be no behavior change, just a clean up.  Thanks @vanniktech

**Comment by vanniktech** [comment]
Exactly this is only a minor cleanup with no behavior change.

I run `./gradlew clean test` locally and all tests did pass.

**Comment by pioterj** [comment]
Great, thanks for taking this one on, @big-guy.

**Comment by vanniktech** [comment]
Ping since according to @big-guy this looks okay, the tests pass and Gradle 2.10 was just released.

**Comment by big-guy** [comment]
Thanks, this'll be in 2.11

**Pull request merged**
