### PR TITLE
Consolidate Ivy version mapping and project resolution

### PR DESCRIPTION
**Pull request by jvandort**
With the updates to dependency mapping, version mapping and project resolution will need to work hand in hand. This commit ensures that Ivy interacts with both of these features in the same place, allowing us to more easily modify this code in the future

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by tresat — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Pull request merged**
