### PR TITLE
Standardize snippets structure

### PR DESCRIPTION
**Pull request by donat**
This PR introduces the following changes
- All snippets are located in the `snippets/$category/$snippetName` directory
- The source code are under `snippets/$category/$snippetName/groovy` and/or `snippets/$category/$snippetName/kotlin`
- Optionally, the exemplar test definitions and the readmes are located under the snippet root dir.

This PR is gigantic, but I added each change as a separate commit. Maybe that helps.

### CODE REVIEW

**Comment by donat** [comment]
@big-guy Some snippets have sibling folders for the `groovy`/`kotlin` sources. They contain maven test repositories. Should we leave them where they are?

**Comment by donat** [comment]
I've resolved the remaining todos in a separate PR (based on this one): https://github.com/gradle/gradle/pull/12922

**Comment by big-guy** [comment]
@donat I think this is basically OK to merge, except for these antlr test failures: https://builds.gradle.org/viewLog.html?buildId=34346298&

I fixed this on a branch and kicked off this build: https://builds.gradle.org/viewQueued.html?itemId=34348969&tab=queuedBuildOverviewTab

If this build is green, I think we can merge the sg/65/merges/donat-sample-moves branch.

**Comment by donat** [comment]
@big-guy This PR is not 100% complete. Please take a look at the follow-up here: https://github.com/gradle/gradle/pull/12922

**Pull request merged**
