### PR TITLE
Turn deprecation into error: classpath files containing path separator

### PR DESCRIPTION
**Pull request by lptr**
Turn this deprecation warning into an error: https://github.com/gradle/gradle/blob/a6588a12a71a0ef3598a702cec0c90a3b16bab5c/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/AbstractFileCollection.java#L179-L198

See https://github.com/gradle/gradle/issues/21648

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test QLF please.

**Comment by lptr** [comment]
@bot-gradle test QFL please.

**Review by asodja — APPROVED** [review]
LGTM!

Should we add this to a potential breaking changes?

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Review by asodja — APPROVED** [review]
LGTM

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Pull request merged**
