### PR TITLE
Fix NullPointerException on strict resolution in settings

### PR DESCRIPTION
**Pull request by ljacomet**
Rebased and amended #16362

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by blindpirate** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test QF

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
