### PR TITLE
Initialize report containers upon construction

### PR DESCRIPTION
**Pull request by jvandort**
Report containers are immutable, but contain an initial set of elements. Subclasses of DefaultReportContainer currently call the super constructor, then add their own elements in their own constructor. In order to enforce immutability, DefaultReportContainer overrides teh assertMutableCollectionContents, throwing an exception unconditionally.

In order for subclasses to avoid this exception, the add method is overridden to not trigger the exception, and subclasses add their elements in their constructor. This pattern is unconventional among domain object containers.

In this commit, we rework the way these containers initialize their elements, so that they pass their initial elements to the DefaultReportContainer constructor. This way, after the superconstructor returns, the container is fully immutable. Future work will remove the need for the 'initialized' variable and 'assertMutableCollectionContents' method, but for now these mechanisms are used to only turn on immutability after the container sets its initial elements.

Further work was done to remove the requirement for a report to keep a reference to the task that generates that report, as the Task referene was only used to generate a description for the report.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Comment by jvandort** [comment]
@bot-gradle test this

**Pull request merged**
