### PR TITLE
Fix the removal of empty text nodes in the DOM based XML transformer

### LINKED ISSUE #9385: XmlProviderImpl#removeEmptyTextNodes is flawed
I needed to edit the XML of a POM in a project I'm writing a build for currently.
As I'm using Kotlin, I used `withXml { asElement() }` to do the modifications.
Unfortunately this destroyed the optics, as every second line in the nested elements was an empty line.
`XmlProviderImpl#removeEmptyTextNodes` should remove those empty text nodes and do some manual indenting, but it has a logic error.
grafik
Calling the remove at :one: affects the result of :two:, so if a node is removed, the next node is effectively skipped.
The length of the child list should be retrieved once at the start of the loop and captured in a variable instead.

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #9385

- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
@bot-gradle test this please

**Comment by JLLeitschuh** [comment]
@Vampire this will need a (hopefully simple) release note added.

Can you provide an example of before & after for us to review as well?

**Comment by Vampire** [comment]
I'm not sure what you want to add to release notes, it is just a bugfix.
If you have this simple build:
```kts
plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.logging.log4j:log4j-api:2.13.3")
}

publishing {
    publications {
        create<MavenPublication>("showcase") {
            from(components.getByName("java"))
            pom {
                withXml {
                    //asElement()
                }
            }
        }
    }
}
```
The generated POM is
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId></groupId>
  <artifactId>showcase</artifactId>
  <version>unspecified</version>
  <dependencies>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <version>2.13.3</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```
If you now uncomment the `asElement()` call, the generated POM is
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId/>
  <artifactId>showcase</artifactId>
  <version>unspecified</version>
  <dependencies>
        
    <dependency>
            
      <groupId>org.apache.logging.log4j</groupId>
            
      <artifactId>log4j-api</artifactId>
            
      <version>2.13.3</version>
            
      <scope>runtime</scope>
          
    </dependency>
      
  </dependencies>
</project>
```
This happens due to this indexing bug.
Before the method runs you have (just an excerpt)
```
artifactId node
empty text node
version node
empty text node
dependencies node
    empty text node
    dependency node
    empty text node
```
Due to the indexing bug the method removes the first empty text node, then skips handling the version node, removes the second empty text node, skips the dependencies node.
So only the empty text nodes on the first level are removed.
And the whole thing only happens if you used the `asElement()` method.
With my fix, the result is the proper expected
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId/>
  <artifactId>showcase</artifactId>
  <version>unspecified</version>
  <dependencies>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <version>2.13.3</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

**Review by JLLeitschuh — APPROVED** [review]
This looks good to me! Thanks for the contribution!

I'm going to let someone else from the @gradle/jvm sign off on this too though.

**Review by jjohannes — APPROVED** [review]
This looks good. Thanks for analysing and fixing this @Vampire.

**Comment by JLLeitschuh** [comment]
Thanks for your contribution @Vampire!

**Pull request merged**
