### PR TITLE
Remove deprecated properties from AbstractArchiveTask

### PR DESCRIPTION
**Pull request by donat**
### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

### CODE REVIEW

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@bot-gradle test rFM

**Comment by donat** [comment]
@JLLeitschuh @big-guy IIUC with the `archivePath` property gone, this is no longer an issue: https://github.com/gradle/gradle/issues/10619. Can you please confirm that?

**Comment by big-guy** [comment]
@donat I think so.

It looks like the build failures are related to the Kotlin plugin. We should see what's the oldest version of Gradle they need to support and if we have the new methods available that far back.

Otherwise, we may need to keep these in for another cycle or mix them in at runtime.

**Comment by donat** [comment]
I've talked with the JetBrains folks and the breakage is fine on their side as long as we add a reasonable error message (something like `if(oldKotlinPlugingApplied()) throw new BuildException("Use new version of Kotlin")`.

**Comment by donat** [comment]
Superseded by https://github.com/gradle/gradle/pull/15769.

**Pull request closed without merging**
