### PR TITLE
Support DependencyScopeConfiguration Provider.invoke overload in DependencyHandlerScope

### LINKED ISSUE #26602: 8.4 - New configuration shortcut: DependencyScopeConfiguration.invoke isn't available
### Current Behavior

```kotlin
val c: NamedDomainObjectProvider<DependencyScopeConfiguration> by configurations.dependencyScope("c") {

}
dependencies {
    c("foo:foo:1") // Type mismatch. Required: TypeVariable(T).() → Unit, Found: String
}
```

### Expected Behavior

```kotlin
val c: NamedDomainObjectProvider<DependencyScopeConfiguration> by configurations.dependencyScope("c") {

}
dependencies {
    c("foo:foo:1") // no error
}
```

### Context (optional)

https://github.com/gradle/gradle/issues/24503

Underlaying issue is the Provider interface, which is written in Java, so it does not support Kotlin `out T`. To support the `invoke` operator, adding `out Configuration` to the introduced api should be enough.
AFAIK this is backward compatible.

### Steps to Reproduce

[gradle-issue-reproducer-kotlin-dsl.zip](https://github.com/gradle/gradle/files/12780346/gradle-issue-reproducer-kotlin-dsl.zip)

### Gradle version

8.4-RC-3

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by hfhbd**
Fixes #26602

### Context
Add `out` to the type parameter of the incubating `invoke` overlaods introduced in https://github.com/gradle/gradle/pull/25005
Underlaying issue is the Provider interface, which is written in Java, so it does not support Kotlin `out T` out of the box.

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [X] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [X] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by jvandort** [comment]
This looks like it allows you to add dependencies to any `Configuration` subclass. However, only `DependencyScopeConfiguration`s can have dependencies added to them.

**Comment by hfhbd** [comment]
@jvandort Yeah, if you only want to support `DependencyScopeConfiguration`, which sounds correct after thinking again, will change it ;)

**Comment by jvandort** [comment]
Awesome, thanks!

Also could you add a test to https://github.com/gradle/gradle/blob/54665332ccb0fda03456e34a899dbebbaa606260/platforms/core-configuration/kotlin-dsl/src/test/kotlin/org/gradle/kotlin/dsl/NamedContainersDslTest.kt#L4 ?

**Comment by jvandort** [comment]
I just noticed that test does not already test declaring dependencies, though I don't really see a better place. Its not a standard integ test so if there is any trouble adding that test I can see if there is another place for it

**Comment by hfhbd** [comment]
What about `DependencyManagementIntegrationTest`, or just `GradleKotlinDslIntegrationTest `?

**Comment by jvandort** [comment]
`DependencyManagementIntegrationTest` seems fitting

**Comment by jvandort** [comment]
How did bot-gradle merge this without a test and merge? @big-guy

**Comment by big-guy** [comment]
It was merged in https://github.com/gradle/gradle/pull/26848

**Pull request merged**
