### PR TITLE
Let kts precompiled scripts synthetic builds respect `--offline`

### PR DESCRIPTION
**Pull request by eskatos**
* Fixes https://github.com/gradle/gradle/issues/23564

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AFT

**Comment by eskatos** [comment]
@bot-gradle test AFT

**Review by donat — APPROVED** [review]
lgtm

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
