### PR TITLE
Use GNU-style release flag for Java 9 compiler

### PR DESCRIPTION
**Pull request by ywelsch**
Since JDK9 b135, only the new GNU-style option with double-dashes is supported for the "--release" flag (see https://bugs.openjdk.java.net/browse/JDK-8160851).

I'm not sure why this has not been caught by Gradle's CI servers? Maybe the tests are not run with any recent versions of JDK9? Also, when fixing just the release flag, I got another failure when running the relevant tests ("compile with release option" and "compile fails when using newer API with release option") with JDK9:

```
14:40:02.425 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:40:02.425 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:40:02.425 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:40:02.425 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':compileJava'.
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > --release option specified, but the provided JavaFileManager is not a StandardJavaFileManager.
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
14:40:02.426 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: --release option specified, but the provided JavaFileManager is not a StandardJavaFileManager.
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jdk.compiler/com.sun.tools.javac.main.Arguments.error(Arguments.java:911)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jdk.compiler/com.sun.tools.javac.main.Arguments.handleReleaseOptions(Arguments.java:327)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:364)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:119)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:68)
14:40:02.431 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.createCompileTask(JdkJavaCompiler.java:67)

14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerRunnable.run(AbstractDaemonCompiler.java:87)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.workers.internal.WorkerServer.execute(WorkerServer.java:31)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:38)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:25)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:98)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
14:40:02.427 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 3s
```

By just removing the special handling for `SourcepathIgnoringJavaFileManager`, the tests seemed to pass. I'm not sure why there are no tests failing by removing that class or if it still serves a purpose in recent versions of JDK9.

/cc: @wolfs

### CODE REVIEW

**Comment by eljobe** [comment]
Good catch @ywelsch!

Currently we have a number of integration tests disabled in Java9 because they are failing. Unfortunately, we've chosen to disable them at the TestClass level instead of at the test case level which means that we also disabled some tests which would have caught problems. We'll get this fixed very soon.

The bad news is that `SourcepathIgnoringJavaFileManager` is actually needed. The integration tests that would have failed with its removal are among the ones described above.  The approach we need to take is to make `SourceIgnoringJavaFileManager` implement `StandardFileManager` and extend from `ForwardingJavaFileManager<StandardFileManager>` instead of `ForwardingJavaFileManager<JavaFileManager>`, it would then just wrap the internal `StandardFileManager` instance to implement the methods added to `JavaFileManager` by `StandardFileManager`.

If it's alright with you, I suggest we execute the following plan to get the pull request in shape.
  1. You revert your changes to `SourcepathIgnoringJavaFileManager` and `JdkJavaCompiler` on this branch.
  2. I will create a branch off of this one which adds back the integration tests which should have failed when `SourcepathIgnoringJavaFileManager` was removed, and make sure there is a test which includes passing the `--release` flag.
  3. Either one of us can make the updates to `SourcepathIgnoringJavaFileManager` described above. Your call.

Sound like a plan? Alternatively, I could just do it all in a separate pull request and you could review my PR?

Let me know.

**Comment by ywelsch** [comment]
Thanks for the explanation @eljobe. I've actually tried the change to ` SourcepathIgnoringJavaFileManager` that you suggested before opening this PR, but it led to a different internal failure coming from the Javac compiler (so just forwarding does not seem to work). I would therefore invite you to figure that one out :-)

If you want to do it all in one PR, that works for me too. I'm not sure yet if it's a separate issue and warrants another PR that will be a predecessor for this one.

**Comment by eljobe** [comment]
Okay. I've been looking into this, and it seems like it is pretty hairy. In order to make the Java 9 compiler happy, it seems like the `SourcepathIgnoringJavaFileManager` needs to implement the `StandardJavaFileManager` interface as defined in JDK 9. Doing that would mean needing to compile the class with JDK 9, but we need to be able to compile Gradle with JDK 7.

So, I'm thinking of just creating a separate repository for this tiny utility class and packaging it in a Multi-Release jar file so that java9 can use a compatible version of `SourcepathIgnoringFileManager` and other versions can use one which is compatible with their runtime.  Then, the Gradle build can just consume that multi-release jar file as a library dependency.

Gradle engineers, does this sound like an okay compromise?

**Comment by big-guy** [comment]
@eljobe what forces us to compile against Java9 to implement the methods from `StandardJavaFileManager`?  It looks like it supplies default methods and/or we just wouldn't annotate them with `@Override`?

And if none of those ways work, we could go the uglier way of using a proxy (as an example): https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/internal/run/DefaultVersionedPlayRunAdapter.java#L71

**Comment by eljobe** [comment]
@big-guy, here's what makes it difficult to get right:  We don't just want to implement the methods from the `StandardJavaFileManager` from Java 9. We also want to call those methods on a `StandardJavaFileManager` which will be passed into `SourcepathIgnoringJavaFileManager` which would implement `ForwardingJavaFileManager<StandardJavaFileManager>` and delegate all methods to the `StandardJavaFileManager` instance it is wrapping.

But, if we aren't compiling against the Java9 version of the `StandardJavaFileManager` interface, then it won't be able to delegate correctly, (because the JDK won't know about the additional methods we're trying to delegate to.)  So, one idea would be to copy the entire interface definition over to our codebase and compile against it. But, it uses some Java 8 features like supplying default implementations.  So, we'd have to strip those out to compile against the interface with JDK 7.  I'm willing to give this a shot. In fact, @oehme gave me some pointers that got this started while we were together at the world meeting, but it ran into some issue which I've since forgotten. I guess I'll code it up again and figure out what breaks.

Sure, we can use the power of the Proxy object to just intercept the calls instead of using a `ForwardingJavaFileManager`. In fact, that might be more easy to understand than compiling against the forward compatible interface. I'm actually leaning toward implementing this one if another repository and library dependency is out of the question.

But, the main reason I was leaning toward building a multi-release jar in a separately released repository is that it is just dead simple to accomplish our goal that way, and it is easy to understand what's going on.

This wouldn't be the only part of our codebase that relies on externally maintained libraries. We (or, really, @adammurdoch) essentially maintain the [Native Platform](https://github.com/adammurdoch/native-platform) libraries, and we depend on them.

**Comment by eljobe** [comment]
This should be safe once we merge #2484

**Comment by big-guy** [comment]
@eljobe Is this supposed to be in release too?

**Pull request merged**
