### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zosrothko**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

This update provides an additional paragraph for running or debugging gradle under Eclipse.

### CODE REVIEW

**Comment by eriwen** [comment]
@zosrothko Thanks for your contribution.

Instead of putting all of this stuff in the `README`, we should move most of the Contributing content to [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).

I also see value for a "Debugging a Gradle build with Eclipse" guide. I'm not sure yet where this belongs. 

Your suggestions are welcome.

**Comment by zosrothko** [comment]
That's fine for me if there is a reference of the Getting Started Debugging Gradle Builds in Eclipse in the Eclipse chapter of the README. Otherwise what would be the interest of importing Gradle into Eclipse if not for contributing and debugging?

**Comment by eriwen** [comment]
@zosrothko Would you be willing to write something in [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md) instead?

**Comment by zosrothko** [comment]
@eriwen Yes no problem for writting some guide lines in the CONTRIBUTING.md

**Comment by zosrothko** [comment]
Done with PR#880

**Comment by eriwen** [comment]
Closing this as superseded by #880 — thanks again @zosrothko!

**Pull request closed without merging**
