### PR TITLE
fix the NameMatch pattern

### LINKED ISSUE #23580: Task abbreviation behavior changes based on JDK used
### Expected Behavior

Task abbreviation behavior should not depend on JDK version. It should either always fail or always select the same task.

### Current Behavior

When Gradle runs on Java 8-14, task is selected unambiguously. 
When Gradle runes on Java 15+, the build fails due to an ambiguous task selection.

### Steps to Reproduce 
Given this `build.gradle`:
```
task publishReleaseBundlePublicationToTempPublishRepository
task publishReleaseObfuscatedBundlePublicationToTempPublishRepository
```

Running `gradle publishReleaseBundle` will succeed (and select `publishReleaseBundlePublicationToTempPublishRepository`) when Gradle runs with Java 8-14. 

On Java 15+, the build will fail with:
```
Task 'publishReleaseBundle' is ambiguous in root project 'task-abbreviation'. Candidates are: 'publishReleaseBundlePublicationToTempPublishRepository', 'publishReleaseObfuscatedBundlePublicationToTempPublishRepository'.
```

I suspect this was caused by a [change in the JDK](https://bugs.openjdk.org/browse/JDK-8239887).  Our `NameMatcher` uses the case-insensitive regex mode when doing task selection.

If you change the name of `publishReleaseObfuscatedBundlePublicationToTempPublishRepository` to `publishReleaseobfuscatedBundlePublicationToTempPublishRepository` (lowercase 'O'), you can get this to fail on all versions of Java. 

### Your Environment

This happens on all supported hosts.

### PR DESCRIPTION
**Pull request by Korov**
Fixes #23580 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by ljacomet — CHANGES_REQUESTED** [review]
From my testing, these changes do not fix the issue reported.

You can verify the reported scenario by adding the following:
```
matches("publishReleaseBundle", "publishReleaseBundlePublicationToTempPublishRepository", "publishReleaseObfuscatedBundlePublicationToTempPublishRepository")
```

to `org.gradle.util.internal.NameMatcherTest#prefers case sensitive camel case match over case insensitive camel case match` and running that test with the extra `-PtestJavaVersion=17` to your test run, which will make Gradle use Java 17 to run the tests.

**Comment by Korov** [comment]
> From my testing, these changes do not fix the issue reported.
> 
> You can verify the reported scenario by adding the following:
> 
> ```
> matches("publishReleaseBundle", "publishReleaseBundlePublicationToTempPublishRepository", "publishReleaseObfuscatedBundlePublicationToTempPublishRepository")
> ```
> 
> to `org.gradle.util.internal.NameMatcherTest#prefers case sensitive camel case match over case insensitive camel case match` and running that test with the extra `-PtestJavaVersion=17` to your test run, which will make Gradle use Java 17 to run the tests.

I added a normalizedCaseInsensitiveCamelCaseMatches priority lower than caseInsensitiveCamelCaseMatches

**Review by Korov — COMMENTED** [review]
fixed

**Pull request closed without merging**
