### PR TITLE
Fix some tests broken with CC

### PR DESCRIPTION
**Pull request by mlopatkin**
Fixes for:
- Ivy publishing failures with Java 9+
- `JavaModuleExecutionIntegrationTest`
- most of `WindowsResourcesIntegrationTest` and `WindowsResourceParallelIntegrationTest`
- `ide.visualstudio` tests

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test ACC

**Comment by mlopatkin** [comment]
@bot-gradle test ACC

**Comment by mlopatkin** [comment]
@bot-gradle test ACC

**Comment by mlopatkin** [comment]
@bot-gradle test ACC

**Comment by mlopatkin** [comment]
This is a good chunk of fixes that reduces the noise from CC tests on CI. I'll continue fixing the remaining tests in next PRs.

**Review by reinsch82 — APPROVED** [review]
LGTM.

Honestly though, I don't understand how these changes fixes the issues ;)

**Pull request merged**
