### PR TITLE
support custom task name for javadoc and sources jars

### PR DESCRIPTION
**Pull request by rpalcolea**
Addresses https://github.com/gradle/gradle/issues/12215

### Context
Hi folks,

Gradle 6 introduced Built-in javadoc and sources packaging and publishing via

```
java {
    withJavadocJar()
    withSourcesJar()
}
```

While this is fantastic, we have found ourselves in the need for changing the default task name for one of them.

Historically we leveraged our own sources jar task under `sourceJar` which is not populated across several projects and there are specific configurations like `archiveBaseName`

it would be phenomenal if we could have a way to set the task name for these new tasks.

This is a naive search for usage of `sourceJar` -> https://github.com/search?l=Gradle&q=sourceJar&type=Code

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by rpalcolea** [comment]
I'm seeing the following issues in TravisCI:

```
> Task :docs:docsTest
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > groovy-library-publishing_groovy_publishTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > groovy-library-publishing_kotlin_publishTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > groovy-library_groovy_jarTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > groovy-library_kotlin_jarTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > java-application_groovy_runTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > java-application_kotlin_runTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > jvm-multi-project-build_groovy_runTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > jvm-multi-project-build_kotlin_runTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > kotlin-application_groovy_runTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > kotlin-application_kotlin_runTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > spring-boot-web-application_groovy_testTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
org.gradle.samples.ExemplarExternalSamplesFunctionalTest > spring-boot-web-application_kotlin_testTask.sample FAILED
    java.lang.AssertionError at Assert.java:88
``` 

However, I can't replicate locally 

```
❯ ./gradlew clean :docs:docsTest
Dependency verification is an incubating feature.
Partial virtual file system invalidation is an incubating feature.

BUILD SUCCESSFUL in 1m 19s
249 actionable tasks: 248 executed, 1 up-to-date
``` 

Wondering if I'm missing something?

**Comment by rpalcolea** [comment]
Looking at the build scan: https://scans.gradle.com/s/lxcgshfmsqyfk/tests/h4ehh6s77alfq-rojghltvruzbu, it seems like assertions fail because extra lines in the output, however the behavior looks fine:

```
java.lang.AssertionError: 
Unexpected value at line 7.
``` 

Line 7 was Picked up JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2 but HelloWorld is now on 8

So this is a Travis specific issue because this happens:

```
$ export JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
``` 

Adding the option locally reproduces the issue

**Comment by melix** [comment]
I'm a bit annoyed with the idea of having something which customizes the name of the tasks. We don't have that anywhere else in the code base and it would introduce a precedent. I _feel_ like what you need is the ability to react on the fact the `javadocJar` task exists or not.

So either, there should be something to _not_ create the task if one is already present, _or_, there should be a `withoutJavadocJar`. Also if the goal is to _reuse_ an existing task instead, it feels like if what you're trying to achieve is to actually create a collision, then you have to be aware of the old name before so I don't see how it really helps...

**Comment by rpalcolea** [comment]
Hi @melix ,

Hmm interesting.. didn't think about the "it would introduce a precedent" part of it.

I think my use case is not to prevent duplicates but to migrate folks

So the current use case for us is the following: https://github.com/nebula-plugins/nebula-publishing-plugin/blob/master/src/main/groovy/nebula/plugin/publishing/publications/SourceJarPlugin.groovy#L37

We created a `sourceJar` task years ago and we have found several projects where folks configure the task to modify things like the `archiveBaseName`, ex.

```
sourceJar.baseName = 'my-shadow-artifact'
```

I believe our goal is to stay the closest to Gradle OSS offerings so removing custom code for a source jar task and use the new Gradle features is something we would love to do.

With that said, we could try to migrate people to refactor their build files although it isn't a nice experience for them

That's why I was thinking that providing a way to set the task name would be great as it would ease migration for many other folks. Don't know if that makes sense.

**Comment by rpalcolea** [comment]
Closing this as this was discussed to not be a good fit for a public API

**Pull request closed without merging**
