### PR TITLE
Update tested AGP versions

### PR DESCRIPTION
**Pull request by eskatos**
from 8.0.0-beta03 to 8.0.0-rc1
from 8.1.0-alpha07 to 8.1.0-alpha10

### CODE REVIEW

**Comment by eskatos** [comment]
@bot-gradle test AST, APT

**Comment by eskatos** [comment]
@bot-gradle test AST, APT

**Comment by eskatos** [comment]
@bot-gradle test AST

**Review by jbartok — APPROVED** [review]

**Comment by eskatos** [comment]
@bot-gradle test and merge

**Pull request merged**
