### PR TITLE
Migrate Project.version to a Property<String>

### PR DESCRIPTION
**Pull request by wolfs**
This is a tryout what breakes and what we'd need to fix.

### CODE REVIEW

**Comment by wolfs** [comment]
This is what we'd need to rewrite in Spring boot: https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/tasks/bundling/ResolvedDependencies.java#L48

**Comment by wolfs** [comment]
This is what we'd need to rewrite in the Asciidoctor plugin: https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/master/base/src/main/groovy/org/asciidoctor/gradle/base/AbstractImplementationEngineExtension.groovy#L253

**Comment by wolfs** [comment]
Interesting, for publishing we already have a `MutableMavenProjectIdentity`, which has GAV as `Property` types.

**Comment by wolfs** [comment]
One interesting thing for the `Project.version` migration is that `Project.version` currently is of type `Object`. So a lot of folks are using `Project.version.toString()`. The problem there is that this won't break at compilation/runtime when we migrate to a `Property<String>`, but will return a useless `String` and mess with the usage. This may be a hard to detect breakage and I wonder how we could make it easier for folks to spot the problem when upgrading.

**Comment by lacasseio** [comment]
One thing that can help unintended consequences of Provider#toString() is allow toString() to throw an exception instead of returning a string that is almost always wrong. I'm pretty sure I opened an issue in the past, unless stale bot closed it.

A discussion in the past was to either replace the group and version with an identity object that is provider configurable or get rid of group and version in favour of configuring the publications. In some way, it doesn't really make sense to have a group and version at the project level when considering the project may have multiple components (main, tests, fixtures, etc.)

**Comment by wolfs** [comment]
Closing since we finished with the spiking. This change hasn't been integrated into #20818, though it could be as well if we wanted to.

**Pull request closed without merging**
