### PR TITLE
Use DependencyAdder in DefaultJvmTestSuite

### PR DESCRIPTION
**Pull request by big-guy**

### CODE REVIEW

**Comment by big-guy** [comment]
@bot-gradle test this

**Comment by big-guy** [comment]
@bot-gradle test this

**Review by tresat — APPROVED** [review]

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
Seems like a huge regression...

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
