### PR TITLE
Update kotlin logo on userguide

### PR DESCRIPTION
**Pull request by jvandort**
Original Kotlin logo from here: https://kotlinlang.org/docs/kotlin-brand-assets.html
Original Android logo from here: https://source.android.com/setup/start/brands

Modified SVG for resizing and also changed color scheme to match existing logo.

Before: 
image

After: 
image

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test BD

**Comment by jvandort** [comment]
Rendered page: https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/54283746:id/distributions/gradle-7.6-all.zip!/gradle-7.6-20220726212723%2B0000/docs/userguide/userguide.html

**Review by big-guy — APPROVED** [review]

**Comment by mahozad** [comment]
@jvandort How about a little simplification of the icon from this:
```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="85px" height="85px" viewBox="0 0 85 85" version="1.1">
  <defs>
    <linearGradient id="linearGradient-0" gradientUnits="userSpaceOnUse" x1="500.0035" y1="579.1058" x2="-0.096538" y2="1079.2058" gradientTransform="matrix(0.169966,0,0,0.169966,0.0164082,-98.4283)">
      <stop offset="0" style="stop-color:#377078;stop-opacity:1;" />
      <stop offset="1" style="stop-color:#5CD2DF;stop-opacity:1;" />
    </linearGradient>
  </defs>
  <g id="surface1">
    <path style=" stroke:none;fill-rule:nonzero;fill:url(#linearGradient-0);" d="M 80 80 L 5 80 L 5 5 L 80 5 L 40 40 Z M 80 80 " />
  </g>
</svg>
```

to this:

```xml
<svg version="1.1" width="85px" height="85px" viewBox="0 0 85 85" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="gradient" gradientUnits="userSpaceOnUse" x1="0" y1="85" x2="85" y2="0">
      <stop offset="0" stop-color="#5CD2DF"/>
      <stop offset="1" stop-color="#377078"/>
    </linearGradient>
  </defs>
  <path fill="url(#gradient)" d="M 80 80 L 5 80 L 5 5 L 80 5 L 40 40 Z M 80 80"/>
</svg>
```

**Comment by jvandort** [comment]
@mahozad Sure, if it renders the same then the simpler the better. Would you mind pushing that change up to this branch, and then I'll kick off a build?

**Comment by mahozad** [comment]
The simplified icon renders the same.

Sorry. It seems I cannot directly push to branches of gradle repository.

A sidenote: The Android logo seems to be outdated too.

**Comment by mahozad** [comment]
Thank you. No problem. Would you mind do it yourself?.

**Comment by jvandort** [comment]
Yes, or couse. Thank you for helping out here

**Comment by jvandort** [comment]
@bot-gradle test BD

**Comment by jvandort** [comment]
Rendered output: 
https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/54332097:id/distributions/gradle-7.6-docs.zip!/gradle-7.6-20220727223946%2B0000/docs/userguide/userguide.html

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Review by nathan-contino — APPROVED** [review]
LGTM!

**Pull request merged**
