### PR TITLE
Avoid volatile writes from Atomics default values

### PR DESCRIPTION
**Pull request by dreis2211**
Hi,

this PR avoids some volatile writes from `Atomics` default values.

Cheers,
Christoph

### CODE REVIEW

**Comment by lptr** [comment]
Looks good to me, not sure how much of an impact this has. If it does, it would be good to add some check somewhere to avoid re-adding similar things.

**Comment by dreis2211** [comment]
It's just a minor optimization. I don't see any need to introduce a check for this.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Comment by lptr** [comment]
@bot-gradle test and merge please.

**Review by lptr — APPROVED** [review]
Thanks for the contribution @dreis2211!

**Comment by lptr** [comment]
@bot-gradle test and merge.

**Pull request merged**
