### PR TITLE
 Migrate distributions-publishing project to JVM platform

### PR DESCRIPTION
**Pull request by tresat**

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

**Review by jvandort — CHANGES_REQUESTED** [review]
Publishing sounds like a `software` concept. Why is this part of JVM?

**Comment by tresat** [comment]
> Publishing sounds like a `software` concept. Why is this part of JVM?

This I don't know.  Basics + signing?

Also interesting is that `distributions-native` references publishing (as it should?) saying specifically "configuring publishing is part of the 'language native' support".

I'm going to leave this PR alone and add it to the agenda for the next Arch Council meeting.  I think this might just be a mistake nobody noticed as opposed to a conscious decision to group things coarsely as with Software.

**Comment by big-guy** [comment]
> I'm going to leave this PR alone and add it to the agenda for the next Arch Council meeting. I think this might just be a mistake nobody noticed as opposed to a conscious decision to group things coarsely as with Software.

I think it was a mistake too.  signing and the publishing plugins are all Software.  I think they may have started as JVM and were reassigned, but we forgot distributions-publishing.

**Review by big-guy — CHANGES_REQUESTED** [review]
can we move this to software instead?

**Comment by tresat** [comment]
@bot-gradle test and merge

**Pull request merged**
