### PR TITLE
Use file access time journal for build cache

### PR DESCRIPTION
**Pull request by marcphilipp**
Reuse `DefaultFileAccessTimeJournal` in for tracking file access in
`DirectoryBuildCacheServiceFactory` for consistency with other caches
and to reduce the number of file operations.

Resolves gradle/gradle-private#1337.

### CODE REVIEW

**Comment by marcphilipp** [comment]
This needs to be rebased once #5801 is merged.

**Comment by marcphilipp** [comment]
@wolfs This is now ready to be reviewed. 🙂

**Comment by marcphilipp** [comment]
Good catch, we should indeed.

**Comment by marcphilipp** [comment]
@wolfs PTAL.

**Comment by wolfs** [comment]
@marcphilipp It would also be interesting what the performance improvements introduced by this change are. I think that the tests exercising the local build cache should be faster, right?

**Comment by marcphilipp** [comment]
I think they should be because there are less blocking file operations. Is there an existing performance test we can use to verify this assumption?

**Comment by wolfs** [comment]
There are a few. I guess `clean assemble on largeJavaMultiProject with local cache (parallel: false)` and `clean assemble on largeMonolithicJavaProject with local cache (parallel: false)` would be the ones where I expect most gain.

**Comment by marcphilipp** [comment]
Doesn't look like there's any observable difference in performance:
https://builds.gradle.org/viewLog.html?buildId=13913326&buildTypeId=Gradle_Check_PerformanceTestCoordinator&tab=report_project944_Performance

**Comment by marcphilipp** [comment]
I'm merging this PR anyway because this change increases consistency and does not harm performance.

**Pull request merged**
