### PR TITLE
Compile classpath specific input snapshotting

### PR DESCRIPTION
**Pull request by melix**
This commit is a giant step towards proper compile avoidance. It introduces a new classpath snapshotter which is specific to compile classpath. This snapshotter ignores things that are irrelevant to compiling against a component. For example, when `A` compiles against `B`, `A` doesn't need to know anything about the internal implementation details of `B`, so those are ignored when creating a hash for `B`. The consequence is that all irrelevant ABI changes are ignored.

If used in conjunction with the incremental compiler, it is even smarter by allowing compile avoidance for all changes that are not relevant to the consumer. Typically, if a change in the public API of `B` is made, but that `A` didn't actually _use_ that part of the public API, then `A` doesn't need to be recompiled either.

Performance improvements can be dramatic with this. When tried on the Gradle codebase, running `compileJava` with an ABI breaking change on `core`, with incremental compilation activated, lasts ~5.5s only.

See: gradle/performance#265

### CODE REVIEW

**Comment by melix** [comment]
To the reviewer: Don't look at the giant number of commits, GitHub seems to be confused. The diff is much shorter.

**Comment by melix** [comment]
PR not yet ready to merge, there are failing tests.

**Comment by melix** [comment]
Stage 3 build is now successful. The commits above are mostly unrelated to the changes in the PR, and are just backports of fixes on the `cc-java-library-plugin` branch.

**Comment by adammurdoch** [comment]
I can't merge this into master as it contains all java-library plugin changes. They should not be bound together.

**Comment by melix** [comment]
The pull request is on the cc-java-library branch, not master. I can
backport it, but it would take time and have to wait the end of my
vacations. On the other hand the cc-java-library branch should be close to
ready to merge too.

**Comment by melix** [comment]
@adammurdoch backported this to `master` with a different strategy. Closing.

**Pull request closed without merging**
