### PR TITLE
Improve release notes and prepare for 8.0.1

### PR DESCRIPTION
**Pull request by ljacomet**

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test QD

**Comment by ljacomet** [comment]
@bot-gradle test BD

**Comment by ljacomet** [comment]
[Rendered release notes](https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/61625399:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20230214181244%2B0000/docs/release-notes.html)

**Comment by ljacomet** [comment]
[Rendered release notes](https://builds.gradle.org/repository/download/Gradle_Release_Check_BuildDistributions/61625749:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20230214183514%2B0000/docs/release-notes.html)

**Comment by big-guy** [comment]
@bot-gradle test BD

**Comment by ljacomet** [comment]
@bot-gradle test BD

**Review by hythloda — APPROVED** [review]

**Comment by ljacomet** [comment]
Changes collected here have been published - so no new commits should be pushed.

**Comment by ljacomet** [comment]
Now includes preparing for Gradle 8.0.1

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test APT

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Pull request merged**
