### PR TITLE
Merge `release` into `master`

### PR DESCRIPTION
**Pull request by hegyibalint**

### CODE REVIEW

**Comment by hegyibalint** [comment]
@bot-gradle test and merge please

**Comment by blindpirate** [comment]
I think you forgot this step:

```
- Run `./gradlew :updateReleasedVersions -PcurrentReleasedVersion=8.0-20230210000219+0000 -PcurrentReleasedVersionBuildTimestamp=20230210000219+0000`
```

Also, CompileAll fails: https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_CompileAllBuild/61472945?hideProblemsFromDependencies=false&hideTestsFromDependencies=true&expandBuildProblemsSection=true&expandBuildChangesSection=true

**Comment by hegyibalint** [comment]
@bot-gradle test and merge please

**Comment by hegyibalint** [comment]
@bot-gradle test and merge please

**Pull request merged**
