### PR TITLE
Add a tool for generating call interception code for configuration cache

### PR DESCRIPTION
**Pull request by h0tk3y**
The new interceptors written with this tool can be found in the PR based on this branch: https://github.com/gradle/gradle/pull/23925

### CODE REVIEW

**Comment by h0tk3y** [comment]
@bot-gradle test RFN

**Comment by h0tk3y** [comment]
@bot-gradle test RFN

**Comment by h0tk3y** [comment]
@bot-gradle clean

**Comment by bamboo** [comment]
@bot-gradle test RFR

**Comment by h0tk3y** [comment]
See the other PR that includes these changes now: https://github.com/gradle/gradle/pull/24165

**Pull request closed without merging**
