### PR TITLE
Only assign Intel 32/64 to default GCC and Clang

### PR DESCRIPTION
**Pull request by JacisNonsense**
### Context
The purpose of this change is to prevent the adding of x86 and x86_64 platforms to AbstractGccCompatibleToolchain, and instead have them added by the default Gcc (or Clang) toolchain should no other toolchains be defined in the DSL. This is beneficial for those wishing to implement cross-compiling toolchains, as I described in #2909. 

To try and affect as little existing projects as possible, the default Intel platforms will be added to any toolchain that exhibits the default Gcc or Clang name (gcc or clang). Names that differ from these will be 'bare' toolchains with no default targets.

See this gist for a demonstration of the changes: https://gist.github.com/JacisNonsense/aa55c75e4c9fc784743ecd945c57071a

Please note the AbstractGccCompatibleToolchainTest changes. Tests assuming the default platforms added have been set to use another instance of toolchain where these platforms are added. Another test case has been added to confirm non-default toolchains do not gain this association by default.

As far as I can tell, no additional integration tests would be required as this only affects installed cross compilers, however I'm open to more dialog regarding this.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [x] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
@eljobe is this something your team could look into?

**Comment by eljobe** [comment]
@oehme, we'll be happy to review this contribution and help it land.

**Comment by ghale** [comment]
Thanks for the PR @JacisNonsense - good stuff!

A big issue with basing the behavior off of the name of the toolchain is backwards compatibility.  There may be existing builds out there that assume that a toolchain that doesn't match the default names will have the default platform support that we're trying to remove.  Certainly, they can add it back using `target()` statements, but their scripts will not work until they do so, so this would be a breaking change for them (which is something we want to avoid).

I have some suggestions about how we could move forward in such a way that we can preserve backwards compatibility and still address your use case, but first I'd like to challenge the assumption that this can't be done with the current functionality so that I can better understand your use case.  As I understand it,  the issue is that you want to declare support for the `aarch64` platform, but you want to have two separate toolchains, and because of the default platform support that gets added to each custom toolchain, it tries to use the wrong toolchain (i.e. `xgcc` instead of `gcc`).   The question I have is, do you actually need these specified as two separate toolchains?  For instance, could you do something like this?

```
model {
 platforms {
    x86 { architecture 'x86' }
    x64 { architecture 'x86_64' }
    xaarch64 { architecture 'aarch64' } // Cross-platform
 }

 toolchains {
    gcc(Gcc) {
       target("x86") { ... }
       target("x64") { ... }
       target("xaarch64") { cppCompiler.executable = "aarch64-linux-gnueabi-g++" }
    }
 }
}
```

Or is there something about your use case I'm not understanding?

As far as a potential way forward if this is still not workable with the current functionality, I think the best way would be to introduce a `setTargets(String)` and `setTargets(String, Action)` method on `GccCompatibleToolchain`.  It would change the list of `platformConfigs` in `AbstractGccCompatibleToolChain` instead of adding to it.  This is a pattern you see in other parts of gradle (i.e. a method that adds to a collection and a setter that overwrites it) and it would preserve backwards compatibility of the toolchain.

In any event, thank you for the excellent PR and issue.  I'm sure we can land on a good solution here if we still need to make changes.  Please let me know if you have any questions about anything above.

**Comment by JacisNonsense** [comment]
Hey @ghale, thanks for the suggestion, I'll take that on board when I get some spare time.

The main reason I can't do this in the same toolchain is to support changing the search path of the toolchain. Most of this is intended for plugins that add their own toolchains to support specific targets, as this way we can register a new toolchain type that subclasses AbstractGccCompatibleToolChain and still allow users to override behaviour in the DSL if they so choose. In my experience, it is much cleaner to register another toolchain than attempting to add to the default toolchain's targets.

**Comment by JacisNonsense** [comment]
Closed in favor of #3124

**Pull request closed without merging**
