### PR TITLE
Split GroovySourceIncrementalCompilationIntegrationTest

### PR DESCRIPTION
**Pull request by wolfs**
into different classes. For this I did split all the extra methods from `GroovySourceIncrementalCompilationIntegrationTest`
and moved them to `GroovyIncrementalCompilationIntegrationTest`.
Moreover, I also did split `AbstractSourceIncrementalCompilationIntegrationTest` into `AbstractClassChangeIncrementalCompilationIntegrationTest` causing the split of the sub-classes as well.

### CODE REVIEW

**Comment by wolfs** [comment]
@bot-gradle test QFL

**Review by blindpirate — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
Looks like the longest split still takes around 3 minutes, and the other two parts take 1 and 2:30 minutes: 
image

So there may be still value in splitting `GroovyClassChangeIncrementalIntegrationTest` later on.

**Pull request merged**
