### PR TITLE
Port to Takari Polyglot 0.1.8

### PR DESCRIPTION
**Pull request by mizdebsk**
Use Takari Polyglot instead of Sonatype Polyglot Maven.

Despite seemingly lower version, Takari Polyglot is replacement for Sonatype Polyglot Maven, which is not developed any longer.

### CODE REVIEW

**Comment by adrianbk** [comment]
@mizdebsk what is the motivation for this change? What is different about the takari libraries?

**Comment by bigdaz** [comment]
Hi again @mizdebsk. Since you didn't reply to the request for more information from @adrianbk, I'm going to close this PR. If you're still keen to contribute this change, please re-open the PR and let us know why this is important.
Thanks, Daz.

**Comment by ebourg** [comment]
Hi, Takari Polyglot is used by JRuby, the Fedora and Debian developers maintaining Gradle and JRuby would like to use the same version of Polyglot to build both projects. That's why this upgrade was suggested, if you could merge it that would ease the packaging of Gradle in the Linux distributions.

**Comment by mizdebsk** [comment]
Rebased on top of latest master.

**Comment by mark-vieira** [comment]
@mizdebsk I've merged this pull request. Assuming all of our existing tests pass I'd say we are good to go. Thanks for the contribution.

**Comment by ebourg** [comment]
Thank you Mark

**Comment by mark-vieira** [comment]
*Update:* Post merge we discovered test failures in CI due to the fact that Takari Polyglot requires Java 7. Because of Gradle's requirement to support running on 1.6 JRE we cannot incorporate this change.

**Comment by ebourg** [comment]
That's unfortunate. I got a look at Takari Polyglot and it's quite easy to build it with Java 6 (there is one diamond operator and 3 regexp with named groups in polyglot-yaml, and polyglot-clojure requires a downgrade of the dependency on Maven to the version 3.2.x). The tests are more troublesome, but at least the 2 modules used by Gradle are ok (polyglot-common and polyglot-groovy).

@jvanzyl: any chance polyglot-common and polyglot-groovy could be made Java 6 compatible to allow Gradle to use it?

**Comment by mark-vieira** [comment]
It might be worth noting we only require the common and groovy modules which you didn't mention as using any Java 7 features.

**Pull request merged**
