### PR TITLE
Tweak dependency verification release notes

### PR DESCRIPTION
**Pull request by melix**
See commits

### CODE REVIEW

**Comment by pioterj** [comment]
It's better but I think we should add a little bit more context.

How about something like this:
- Gradle builds typically consume a large number of external dependencies and plugins. This involves a risk of running untrusted code that could be malicious. Such malicious dependency or plugin can even infect the software you build with Gradle.  
- In order to protect against this kind of attack, it's important to be able to verify the integrity (hasn't it been tampered with?) and origin (who signed it?) of external artifacts. 
- Gradle 6.2 allows you to do this automatically thanks to the new dependency verification feature. 
- With dependency verification, you maintain an XML file with checksums and optionally also signatures of all external artifacts used in your project. In case any of them is compromised, the build will fail. 
- See documentation for a complete explanation of how to set it up.
- Recognize the community plugin author.

@jlstrater WDYT?

**Comment by melix** [comment]
This sounds a bit like Gradle is at fault here, when it's any build tool which suffers from this (and I think Gradle would be the first one to have built-in support for verification, so quite unfair).

**Comment by jlstrater** [comment]
The first point does sound scary, but I like the rest. Maybe you could focus on how easy it is to miss [potentially malicious] changes when there are so many dependencies/plugins to check?

In addition, I'd avoid promising to 'prevent/protect against/avoid' attacks and suggest 'minimize the chance of..' since there are still other attack vectors for compromising dependencies/plugins.

Lastly, if Gradle is the first build tool to do this, that would be a nice thing to highlight.

**Comment by melix** [comment]
> Lastly, if Gradle is the first build tool to do this, that would be a nice thing to highlight.

I checked and it's not the case, Bazel allows verifying the SHA1

**Comment by pioterj** [comment]
Good points. The first two paragraphs I proposed should be adjusted to take them into account. @melix Do you want to take another stab at it?

**Comment by melix** [comment]
What about now?

**Comment by pioterj** [comment]
Nice!

I'm wondering if the sentence "Gradle is the first build tool which integrates native verification of checksums and signatures of both dependencies and plugins." wouldn't be more appropriate in a tweet than in release notes.

**Comment by melix** [comment]
I'll remove it for now, we can reintegrate if we think it's worth it.

**Pull request merged**
