### PR TITLE
Remove check that's incompatible with IDEA 2019.2

### PR DESCRIPTION
**Pull request by oehme**
IDEA 2019.2 uses the new PhasedAction API in order to
get a tooling model and run some tasks in the same step.
This API uses a projectsEvaluated listener under the hood,
which fires before the check we had in place to detect the
end of configuration time. As a result, we would falsely
fail, saying that IDEA was "resolving dependencies at config
time".

### CODE REVIEW

**Comment by paplorinc** [comment]
Is there a way to actually fix this, or it's fundamentally invalid now?

**Comment by melix** [comment]
This is quite annoying and counter-intuitive. The Groovy build is doing a similar check.

**Comment by oehme** [comment]
Well, we could hook the tooling API deeper into Gradle so that it is run after all these listeners. The same is true for traditional TAPI actions, which basically run as a `buildFinished` hook and might thus miss things done by other `buildFinished` hooks.

**Comment by melix** [comment]
I wonder about Android, which has a similar check. Does it mean that it's going to break all Android sync actions?

**Comment by oehme** [comment]
Android already uses the phased action API for a while, so they would have noticed if that breaks with their check.

**Pull request merged**
