### PR TITLE
Don't ignore exit value if pushing to green-master fails

### PR DESCRIPTION
**Pull request by blindpirate**
So that we can notice it earlier.

### CODE REVIEW

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by blindpirate** [comment]
Thanks @wolfs !

@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle help

**Comment by blindpirate** [comment]
@bot-gradle clean

**Comment by blindpirate** [comment]
This is going to be worked.

**Pull request closed without merging**
