### PR TITLE
Fix missing quotation marks

### LINKED ISSUE #12916: Minor formatting issue in attribute matching error (for unknown vlaues)
See missing tick `'` for `'modular-jar` - "modular-jar" here is an additional value for LibraryElements. 

[error-out.png](https://images.zenhubusercontent.com/57c7d124e40e5714b16e1e84/20baf183-ced8-4ac8-a2aa-2595ef0c5337)

### PR DESCRIPTION
**Pull request by bmuskalla**
Fixes #12916

### CODE REVIEW

**Comment by bmuskalla** [comment]
I haven't found any tests for those error messages so I didn't anymore now. Let me know if you think we should cover those cases as well. 

I think we should actually fix this on release as well

**Comment by bmuskalla** [comment]
@bot-gradle test RFM

**Comment by ljacomet** [comment]
As we will do an RC3, maybe this could be added indeed.
@melix WDYT?

**Comment by melix** [comment]
We could but I'd like to see full branch coverage first.

**Comment by bmuskalla** [comment]
Build is running

**Pull request merged**
