### PR TITLE
Docs: Correct instructions to increase inotify limits

### LINKED ISSUE #17974: Documentation: Incorrect instructions to increase inotify limits
Documentation at  the end of this page https://docs.gradle.org/current/userguide/gradle_daemon.html shows instructions to increase inotify limits as

```
echo 524288 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p --system
```

Which I assume are incorrect. Could have been either
`sudo sysctl -w fs.inotify.max_user_watches=524288`
or
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf`
followed by reloading sysctl

Let me know if it needs to be corrected and I can submit a pull request

### PR DESCRIPTION
**Pull request by anilkumarmyla**
Issue: #17974
Signed-off-by: Anil Kumar Myla <manil@verizonmedia.com>

Fixes #17974

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Comment by wolfs** [comment]
@anilkumarmyla Thank you for fixing this! The fix will be in Gradle 7.3

**Pull request merged**
