### PR TITLE
Removing apostrophe

### PR DESCRIPTION
**Pull request by jonatasemidio**
Is nice to avoid some characters

### CODE REVIEW

**Comment by erdi** [comment]
Can you please explain the point of this pull request?

**Comment by jonatasemidio** [comment]
Hi Erdi

Some editors or some encoding does not works well with some characters and in this same file we have others exception with "cannot".

I would like to open a issue, but was so simple that I sent a pull request.

This is just my opinion: Avoid some characters when possible

**Comment by erdi** [comment]
Saying "Some editors or some encoding does not works well with some characters" is really vague - there are three "some" in this sentence. I still don't understand why using an apostrophe in an exception message would be a problem.

**Comment by jonatasemidio** [comment]
Not a problem, just a simple/nice(for me) convention. ;)

**Comment by erdi** [comment]
Sorry, but I see no point in this PR. Feels like a change for the sake of changing something therefore I'm closing it.

**Comment by jonatasemidio** [comment]
No problem Erdi and thank you for your attention. ;)

**Pull request closed without merging**
