### PR TITLE
Improve doc test coverage(developingPlugins-E)

### PR DESCRIPTION
**Pull request by mlopatkin**
These are trivial cleanups.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test PRF, BD

**Comment by mlopatkin** [comment]
@bot-gradle test BD, PRF

**Review by 6hundreds — APPROVED** [review]
LGTM!

**Comment by mlopatkin** [comment]
@bot-gradle test and merge

**Review by bamboo — COMMENTED** [review]
👍

**Pull request merged**
