### PR TITLE
Upgrade embedded Kotlin version to 1.5.31

### PR DESCRIPTION
**Pull request by bamboo**
And bump kotlinx-coroutines to 1.5.2.

### CODE REVIEW

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by bamboo** [comment]
@bot-gradle test ACC

**Comment by bamboo** [comment]
@bot-gradle test QFL

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Review by eskatos — APPROVED** [review]
⬆️ 🎉

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Pull request merged**
