### PR TITLE
Disable output capturing in performance tests

### PR DESCRIPTION
**Pull request by lhotari**
- the output isn't inspected in performance tests and since capturing could affect the measurements, it's better to simply not do it.

- this PR also has an unrelated change that fixes a problem in GradleExecuterBackedSession.cleanup

### CODE REVIEW

**Comment by lhotari** [comment]
Build pipeline status for the branch of this PR: https://builds.gradle.org/project.html?projectId=Gradle_Branches_Checkpoints&branch_Gradle_Branches_Checkpoints=lh-perf-tests-no-capturing

**Comment by oehme** [comment]
I have never looked at the output, so I agree. Did you ever use it @melix?

Would we still be testing performance realistically though? E.g. what if we break something in the console output handling in Gradle?

**Comment by lhotari** [comment]
This change doesn't stop output to System.out/System.err. It just removes the capturing to a `ByteArrayOutputStream` on the side. btw. I also extracted `OutputCapturer` in this PR, but I didn't change the buffering implementation.

**Comment by melix** [comment]
The output is important, because it participates in the performance, but capturing the output is not, so :+1:  I don't recall any performance test that adds expectations on the output, but finding out should be trivial.

**Comment by oehme** [comment]
Cool, good from my side then.

**Comment by lhotari** [comment]
I checked that performance tests [don't inspect the output](https://github.com/gradle/gradle/blob/9d7e7519b30eb351780b987f166ee577c8eff22d/subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/GradleExecuterBackedSession.groovy#L57-L57)

**Pull request merged**
