### PR TITLE
Fix dependency verification when Gradle metadata file name doesn't match actual file name

### LINKED ISSUE #20098: Dependency verification fails for signed klib artifacts
### Expected Behavior
(On Linux)
1. Check out [androidx-main](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main)
2. Verify that native tests pass:

```
cd frameworks/support
./gradlew --offline --no-configuration-cache -Pandroidx.kmp.linux.enabled=true collection2:collection2:linuxX64Test
```

3. Comment out the checksum entries for atomicfu-linuxx64, which should be unnecessary, because we have signatures for these libraries:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:gradle/verification-metadata.xml;l=958;drc=b272bd6b539052144693f444342085d10cf9943b

4. Repeat command from step 2.

5. Expect that this command also passes.

### Current Behavior

5. Fails with

```
> Task :collection2:collection2:compileKotlinLinuxX64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':collection2:collection2:compileKotlinLinuxX64'.
> Dependency verification failed for configuration ':collection2:collection2:linuxX64CompileKlibraries':
    - On artifact atomicfu-cinterop-interop.klib (org.jetbrains.kotlinx:atomicfu-linuxx64:0.14.4) in repository 'maven2': checksum is missing from verification metadata.
    - On artifact atomicfu.klib (org.jetbrains.kotlinx:atomicfu-linuxx64:0.14.4) in repository 'maven2': checksum is missing from verification metadata.
  
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.4/userguide/dependency_verification.html#sec:troubleshooting-verification
  
  These files failed verification:
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linuxx64/0.14.4/5327c22844c66040e3ef8023f47cd1a6db8ab4e5/atomicfu.klib
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linuxx64/0.14.4/d8fae915484834b47fab9a42596349589b3b03dd/atomicfu-cinterop-interop.klib
  
  GRADLE_USER_HOME = /usr/local/google/home/saff/.gradle
  
  These files failed verification:
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linuxx64/0.14.4/5327c22844c66040e3ef8023f47cd1a6db8ab4e5/atomicfu.klib
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linuxx64/0.14.4/d8fae915484834b47fab9a42596349589b3b03dd/atomicfu-cinterop-interop.klib
```

### Context
We want to verify signatures on all of our dependencies, for build chain security.

### PR DESCRIPTION
**Pull request by asodja**
The issue in https://github.com/gradle/gradle/issues/20098 is, that `atomicfu-linuxx64-<version>.module` has `files` specified in a way that `name` doesn't match the actual file name. 

This fixes it by always resolving the file name from the relative url in [UrlBackedArtifactMetadata.java](https://github.com/gradle/gradle/compare/asodja/variant-dep-verification?expand=1#diff-12de44ab7d4bee88a8e49d074c2a6d9d2798a1b8b9b709acc00c40e6f944afa2). The same strategy was used only for Maven snapshots before.

Gradle metadata of `atomicfu-linuxx64-<version>.module`:
```
  "formatVersion": "1.1",
  "component": {
    "url": "../../atomicfu/0.17.1/atomicfu-0.17.1.module",
    "group": "org.jetbrains.kotlinx",
    "module": "atomicfu",
    "version": "0.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
    ...
      },
      "files": [
        {
          "name": "atomicfu.klib",
          "url": "atomicfu-linuxx64-0.17.1.klib",
        },
        {
          "name": "atomicfu-cinterop-interop.klib",
          "url": "atomicfu-linuxx64-0.17.1-cinterop-interop.klib",
        }
      ]
    }
  ]
}
```

Fixes #20098

@ljacomet what do you think about this? Can this negatively impact any other part of dependency resolution?

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
Yeah, failures are related to that change in [UrlBackedArtifactMetadata.java](https://github.com/gradle/gradle/compare/asodja/variant-dep-verification?expand=1#diff-12de44ab7d4bee88a8e49d074c2a6d9d2798a1b8b9b709acc00c40e6f944afa2).

**Comment by ljacomet** [comment]
I'll need to thing some more about this, but this change looks very suspicious to me. Either the metadata is broken because we used name to find the file. But that would show in regular dependency resolution.
Or we have a problem with verification that does not handle this case.

**Comment by asodja** [comment]
Ok makes sense.

For the context:
We can fix this particular issue for Dependency verification if we get `IvyArtifactName` from `ComponentArtifactMetadata artifact` and we pass that to `maybeFetchSignatureFile` and we use that to calculate `.asc` from `IvyArtifactName` that has correct file name in `resolveArtifact`:
https://github.com/gradle/gradle/blob/1bb113e36547c3ec5e2714fd22ba4570a2e11b49/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyVerifyingModuleComponentRepository.java#L189-L198

We calculate `.asc` file in `SignatureArtifactMetadata` from the `ModuleComponentArtifactIdentifier` that has the file name equal to one specified in Gradle module metadata, this happens here:  https://github.com/gradle/gradle/blob/1bb113e36547c3ec5e2714fd22ba4570a2e11b49/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyVerifyingModuleComponentRepository.java#L248-L261 where we get file name from: ModuleComponentArtifactIdentifier.

We create `SignatureArtifactMetadata` here in `maybeFetchSignatureFile` that is called from the `resolveArtifact` method:
https://github.com/gradle/gradle/blob/1bb113e36547c3ec5e2714fd22ba4570a2e11b49/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/DependencyVerifyingModuleComponentRepository.java#L157-L165

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Review by ljacomet — APPROVED** [review]
LGTM!

Thanks for fixing this properly!

**Comment by asodja** [comment]
@bot-gradle test and merge

**Pull request merged**
