### PR TITLE
Update to Gradle Enterprise Gradle plugin 3.6

### PR DESCRIPTION
**Pull request by britter**
Co-authored-by: Moran Fine <moran@gradle.com>

### CODE REVIEW

**Comment by britter** [comment]
@bot-gradle please test this

**Review by ljacomet — APPROVED** [review]
LGTM 👍

**Comment by britter** [comment]
The build failures are most likely related to the fast that ge.gradle.org has not been upgraded to Gradle Enterprise 2021.1. I will trigger a re-run once that has happened.

**Comment by marcphilipp** [comment]
@britter @MoranF We've discovered an incompatibility between the Gradle Enterprise plugin 3.6 and the Test Distribution plugin 2.0 and are working on a fix of the latter. I think we should consider this PR blocked until the fix is released.

**Comment by big-guy** [comment]
@bot-gradle test this

**Pull request merged**
