### PR TITLE
TestFixtures can now be used as dependencies to test suites - Old

### LINKED ISSUE #19192: Named argument notation not supported for dependencies in test suite plugin
### Expected Behavior
When declaring [dependencies of a test suite](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#configure_dependencies_of_a_test_suite), it should be possible to use map notation like in top level dependency declarations (e.g. `group = "org.junit.jupiter", name = "junit-jupiter", version = "5.8.2"`), rather than be forced to use string notation (e.g. `"org.junit.jupiter:junit-jupiter:5.8.2"`)

For example, the following should be valid:

```kotlin
testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
            dependencies {
                implementation(group = "org.junit.jupiter", name = "junit-jupiter", version = "5.8.2")
                runtimeOnly(group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "5.8.2")
            }
        }
    }
}
```

### Current Behavior
The test suite plugin requires dependencies to be declared using string notation.  The example above has to be rewritten as:

```kotlin
testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
            dependencies {
                implementation("org.junit.jupiter:junit-jupiter:5.8.2")
                runtimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")
            }
        }
    }
}
```

### Context
In the interests of consistency, and hence ease of migration and also intuitiveness, test suite dependencies should be declared in the same ways as regular module dependencies.

In my opinion, map notation is easier to understand, and less prone to fat-finger errors.

### Steps to Reproduce 
See [example project](https://github.com/markslater/gradle-examples/tree/13356368fdc2e7f7356ed573e2a4e3830d62b051)

### Your Environment
Using Gradle 7.3.1

### PR DESCRIPTION
**Pull request by tresat**
Fixes #19192 

Map notation is also supported (without any changes, it just worked when I added the tests for it).

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test QFL

**Review by DPUkyle — APPROVED** [review]
LGTM

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle cancel

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test QFL

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
@bot-gradle test this

**Comment by tresat** [comment]
Superceded by #21049

**Pull request closed without merging**
