### PR TITLE
Make ShowToolchainsTask work with configuration cache

### LINKED ISSUE #20296: `-q javaToolchains` is not compatible with configuration cache
### Expected Behavior

It should be compatible or at least not fail ungracefully

### Current Behavior

It fails

### Context

Run `gradle -q javaToolchains` twice in a gradle build with configuration caching enabled, you will see this failure the second try

```
gradle -q javaToolchains

FAILURE: Build failed with an exception.

* What went wrong:
Could not load the value of field `specs` of `org.gradle.api.specs.AndSpec` bean found in task `:javaToolchains` of type `org.gradle.jvm.toolchain.internal.task.ShowToolchainsTask`.
> org.gradle.jvm.toolchain.internal.task.ShowToolchainsTask$$Lambda$1901/0x00000008024fd410

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 876ms
```

### Steps to Reproduce 

See above

### Your Environment

Build scan URL: N/A

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #20296

### CODE REVIEW

**Comment by jbartok** [comment]
@bot-gradle test QFL

**Review by mlopatkin — CHANGES_REQUESTED** [review]
Could you please add an integration test to ensure this task won't break in the future?
Somewhere near [ConfigurationCacheJavaIntegrationTest](https://github.com/gradle/gradle/blob/master/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheJavaIntegrationTest.groovy), `ConfigurationCacheJavaToolchainsIntegrationTest` maybe? I don't think we need to check anything but run the task twice and assert that the state was stored and then loaded.

The `configuration-cache` has the nice `AbstractConfigurationCacheIntegrationTest` harness to verify cache load and store, that's why I suggest putting the test here and not closer to the toolchains module.

**Review by mlopatkin — APPROVED** [review]
LGTM, thanks!

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Pull request merged**
