### PR TITLE
Upgrade Kotlin to 1.3.60

### PR DESCRIPTION
**Pull request by eskatos**
https://blog.jetbrains.com/kotlin/2019/11/kotlin-1-3-60-released/
https://github.com/JetBrains/kotlin/tree/v1.3.60

### CODE REVIEW

**Comment by lptr** [comment]
We also need to upgrade Kotlin in Santa tracker, are you planning to do that, too? Let me know if I can help.

**Comment by eskatos** [comment]
@lptr right, if you can take it that would be nice, I'm not done with this one, it seems there are some more issues I need to handle

**Comment by bamboo** [comment]
🎗 Need a new `kotlin-dsl` plugin release to go with it.

**Comment by eskatos** [comment]
`Ready for Release` ✅ 
https://builds.gradle.org/viewQueued.html?itemId=28877781

@bamboo please take a look 👀

**Pull request merged**
