### PR TITLE
Add configuration cache incompatibility note for C++ and Swift samples

### PR DESCRIPTION
**Pull request by mlopatkin**
The documentation pages for the samples are generated, so the generator itself has to be tweaked.

Part of #21027.

### CODE REVIEW

**Comment by mlopatkin** [comment]
@bot-gradle test BD

**Comment by mlopatkin** [comment]
Changed pages:
- https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/58055046:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221111165435%2B0000/docs/samples/sample_building_cpp_applications.html
- https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/58055046:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221111165435%2B0000/docs/samples/sample_building_cpp_libraries.html
- https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/58055046:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221111165435%2B0000/docs/samples/sample_building_swift_applications.html
- https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/58055046:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221111165435%2B0000/docs/samples/sample_building_swift_libraries.html

Unchanged pages (just one to verify):
https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/58055046:id/distributions/gradle-8.0-docs.zip!/gradle-8.0-20221111165435%2B0000/docs/samples/sample_building_kotlin_applications.html

**Review by nathan-contino — APPROVED** [review]
Docs LGTM

**Review by bamboo — APPROVED** [review]
👍

**Comment by bamboo** [comment]
@bot-gradle test and merge

**Comment by blindpirate** [comment]
@bot-gradle test and merge

**Pull request merged**
