### PR TITLE
Switch Windows platform test to use MAX_VERSION

### PR DESCRIPTION
**Pull request by octylFractal**
This changes one of our RfN platform tests to check that 19 is working on Windows as expected.

### CODE REVIEW

**Review by DPUkyle — APPROVED** [review]
LGTM - is there any need to try this change out first on the `experimental` branch, then check the Experimental build configuration on TC?

**Comment by octylFractal** [comment]
@bot-gradle test PRF

**Review by blindpirate — APPROVED** [review]
LGTM, but apparently we have some failures to resolve...

**Comment by octylFractal** [comment]
Yes, I am working on them.

**Comment by octylFractal** [comment]
@bot-gradle test PRF

**Comment by octylFractal** [comment]
@bot-gradle help

**Comment by octylFractal** [comment]
@bot-gradle cancel

**Comment by octylFractal** [comment]
@bot-gradle test PRF

**Review by tresat — APPROVED** [review]

**Comment by octylFractal** [comment]
@bot-gradle test ReadyForNightly

**Comment by octylFractal** [comment]
@bot-gradle test ReadyForNightly

**Comment by octylFractal** [comment]
@bot-gradle test PRF

**Comment by big-guy** [comment]
@bot-gradle test and merge

**Pull request merged**
