### PR TITLE
Introduce `ArtifactResolutionQuery#forComponent(group, name, version)`

### PR DESCRIPTION
**Pull request by bamboo**
So it can be used by `kotlin-dsl` in place of the internal `DefaultModuleComponentIdentifier#newId`.

### CODE REVIEW

**Comment by melix** [comment]
Actually I just see you did. Let's wait for the pipeline to be complete.

**Comment by bamboo** [comment]
Thanks, @melix.

I should have posted the link to the CI job here: https://builds.gradle.org/viewQueued.html?itemId=9655073&tab=queuedBuildOverviewTab

**Comment by big-guy** [comment]
I'm an outsider to this, but it seems a little strange to give GAV-like components a special place in this interface. We have several other component identifiers that don't have group, name and version.  

IOW, should this at least be `forModuleComponent` or there be a factory for creating these kinds of components somewhere else (`DependencyHandler` or something new)?

**Comment by bamboo** [comment]
Thanks for the review, @big-guy.  We're adding the method to avoid introducing a factory and expose more API. I agree that `Module` instead of `Component` in the name would be clearer, my preference would be `forModule`, what do you think?

**Comment by bamboo** [comment]
[CI](https://builds.gradle.org/viewLog.html?buildId=9660823&tab=buildResultsDiv&buildTypeId=Gradle_Check_Stage_MasterAccept_Trigger) is green.

**Comment by bamboo** [comment]
@melix, @big-guy, anything against the new name? (`forComponent` => `forModule`)

**Comment by melix** [comment]
:+1:

**Comment by big-guy** [comment]
Thanks @bamboo, I didn't really have enough context, but I thought it looked odd.  `forModule` sounds fine.

**Pull request merged**
