### PR TITLE
Scala sample projects are made more idiomatic

### PR DESCRIPTION
**Pull request by marc0der**
Any of the checked boxes below indicate that I took action:
- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

For all non-trivial changes that modify the behavior or public API:
- [ ] Before submitting a pull request, I started a discussion on the [Gradle developer list](https://groups.google.com/forum/#!forum/gradle-dev),
    the [forum](https://discuss.gradle.org/) or can reference a [JIRA issue](https://issues.gradle.org/secure/Dashboard.jspa).
- [ ] I considered writing a design document. A design document can be
  brief but explains the use case or problem you are trying to solve,
  touches on the planned implementation approach as well as the test cases
  that verify the behavior. Optimally, design documents should be submitted
  as a separate pull request. [Samples](https://github.com/gradle/gradle/tree/master/design-docs)
  can be found in the Gradle GitHub repository. Please let us know if you need help with
  creating the design document. We are happy to help!
- [x] The pull request contains an appropriate level of unit and integration
  test coverage to verify the behavior. Before submitting the pull request
  I ran a build on your local machine via the command
  `./gradlew quickCheck <impacted-subproject>:check`.
- [ ] The pull request updates the Gradle documentation like user guide,
  DSL reference and Javadocs where applicable.

### CODE REVIEW

**Comment by marc0der** [comment]
Okay, happy change it as requested.

**Comment by eriwen** [comment]
@marc0der I'm afraid `SamplesMixedJavaAndScalaIntegrationTest.canBuildDocs` and 5 other Samples specs are failing.

> java.lang.AssertionError: ...\subprojects\scala\build\tmp\test files\unknown-test-class\r5g6t\scala\mixedJavaAndScala\build\docs\javadoc\org\gradle\sample\Person.html is not a file

Would you please take a look?

**Comment by marc0der** [comment]
@eriwen apologies for not getting onto this sooner but all tests should be green now.

**Comment by eriwen** [comment]
Indeed they are. This looks great, thank you @marc0der!

**Comment by marc0der** [comment]
It's a pleasure!

**Pull request merged**
