### PR TITLE
Change log level of "Watching X directories" to debug

### LINKED ISSUE #26350: Reduce log level of directory watcher
### Current Behavior

Gradle outputs "Watching X directories to track changes" way to often when run with log level INFO. This clutters the CLI both locally and in our CI system.

I can see the `BUILD SUCCESSFUL` message only after scrolling up a few kilometers.

### Expected Behavior

The file system watcher logs should be printed at DEBUG log level only.

### Context (optional)

_No response_

### Steps to Reproduce

Execute a gradle build with log level INFO.

### Gradle version

8.2.1

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by zalintyre**
Fixes #26350

### Context
This log on info level clutters the console output and renders it unusable as described in the previous issue. This PR 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

### CODE REVIEW

**Comment by zalintyre** [comment]
As this PR only changes a logging level, the "lacks tests" label might be inaccurate.

**Comment by jbartok** [comment]
@zalintyre , you missed one usage [here](https://github.com/gradle/gradle/blob/a36788f76e4428878e37c831bce8c05ee64f7996/platforms/core-execution/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java#L125).

Beyond that all good.

**Comment by zalintyre** [comment]
@jbartok you're right, I totally missed that one. I added a commit to fix that, too.

**Review by mlopatkin — APPROVED** [review]
configuration lgtm

**Comment by jbartok** [comment]
@bot-gradle test this

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Review by lptr — APPROVED** [review]
LGTM.

**Pull request merged**
