### PR TITLE
Draft release notes and features for Gradle 4.9

### PR DESCRIPTION
**Pull request by eriwen**
TODO before 4.9 GA: link to blog post and update upgrade instructions.

### CODE REVIEW

**Comment by eriwen** [comment]
@big-guy Would you please consider adding a release notes subsection for lazy tasks?

**Comment by pioterj** [comment]
@eriwen I think we need to polish the coverage of lazy task configuration regarding providing the context, how we position this feature and setting expectations. 

I'd start from the basics that we take for granted that users already know. What is configuration time and why it matters? We can link to the [relevant chapter](https://docs.gradle.org/current/userguide/build_lifecycle.html#sec:build_phases) in the user guide for explanation of the build lifecycle. The reason it matters is because it affects your every single build including the ones that would otherwise take no time to execute.

We are currently positioning lazy task configuration as a thing for early adopters. We don't plan to change the API in dramatic ways but it is not stable yet and may change based on feedback. With that in mind I wouldn't say "plugin authors should read the documentation to learn how to get started using this exciting new feature" yet. I'm not even sure if it should be the first thing in the preamble. 

As for setting expectations, there are big caveats to the level of configuration time improvement that one can expect. Just saying "We have been testing this feature at scale and have seen 10-15% faster configuration times" may be misleading. I'd not expect a noticeable difference for most end users out of the box until the plugins they use adopt the new API. However, if you do expensive work in your custom task configuration, you can see a big improvement when executing unrelated tasks after adopting the new API.

cc @big-guy @adammurdoch

**Comment by lacasseio** [comment]
I'm stepping out for a couple hours, I can complete the coverage for lazy task API in the release note and merge this PR.

**Comment by lacasseio** [comment]
I also had a read of the release note and Eric made them great as usual. What @pioterj wrote for the lazy task seems good, I will copy that over to the release note and polish it to better align with migration guide and blog post. Unless @eriwen gets to it first :)

**Pull request merged**
