### PR TITLE
Release database connection after query

### PR DESCRIPTION
**Pull request by blindpirate**
Previously, we hold the DB connection open during the whole performance test
time, this can cause issues:

1. The connection can be idle for a long time, then lost.
2. With many performance tests running at the same time, we get "Too many connection" error.

This PR fixes this issue by closing the connection immediately after query.

### CODE REVIEW

**Comment by blindpirate** [comment]
@bot-gradle test this

**Review by wolfs — CHANGES_REQUESTED** [review]
I think the strategy is fine for what we are doing in the test JVM running the performance test, since we only write the results at the end.

It think it is not good for the JVM we use to generate the performance report. If we have 140 performance tests then we will have 140 requests to the performance database at least, probably 2x or 3x as much, each of them which needs to open a connection. Can we maybe pass a parameter to the results store to decide whether to close the connection after each `withConnection`?

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by blindpirate** [comment]
@wolfs I think it's fine to open 2x or 3x connections, as long as we're closing them after use. Anyway, let's merge it as is, to unblock `master` for now.

**Comment by blindpirate** [comment]
@bot-gradle test this

**Comment by wolfs** [comment]
>  I think in our case, it's fine to open 2x or 3x connections

How long does it take to open a connection? 500ms? If that is the case, then only opening and closing the connections for creating the report would add about 2 minutes of execution time. I also don't know how expensive this is on the database side to open a new connection. I suppose establishing an ssl connection is pretty costly.

**Comment by blindpirate** [comment]
I see your point, but why it increases report time? On worker's side, the data report is finished in one run: https://github.com/gradle/gradle/blob/3574f40063e727a0ca32011acd0c7401afb2e15c/subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/CrossVersionPerformanceTestRunner.groovy#L149

The only place we're querying in a loop is this code:

https://github.com/gradle/gradle/blob/4774dbe3ce54e377c21758c3cc5a84c0049c52a4/subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/results/report/AbstractReportGenerator.java#L76

But this only happens in report generator side, right?

**Comment by wolfs** [comment]
> But this only happens in report generator side, right?

Yes, that is what I am saying above: Generating the overall performance report will take 2 minutes longer.

**Comment by wolfs** [comment]
@blindpirate If you think this PR fixes the problem, then please go ahead and merge it.

**Comment by blindpirate** [comment]
I'm waiting for CI feedback. I think we can merge it as a temp solution, and I'll measure the impact of this query-per-connection mechanism.

**Review by wolfs — APPROVED** [review]
LGTM!

**Pull request merged**
