### PR TITLE
Docs: update unavailable task property annotations in the runtime API

### LINKED ISSUE #21594: Update docs for adhoc-task property builder runtime API to describe equivalent for all annotations
It seems like several of the annotations can't be described using the runtime API.

* `@Classpath`
* `@CompileClasspath`
* `@LocalState`
* `@Nested` (already documented as unavailable)
* `@ReplacedBy`
* `@Internal`

### Expected Behaviour

The docs are updated 

* Unavailable annotations are documented
* Examples for all available annotations are provided

### Current Behaviour

I am confused by the Gradle documentation, so I have to spend a lot of time researching and trying to find out what I should do.

### Context

I want to add an `@Internal` API property for an existing task. The docs indicate that this should be possible with the `TaskPropertyBuilder` runtime API

> In fact, the runtime API has almost feature parity with the annotations. All it lacks is an equivalent for [`@Nested`](https://docs.gradle.org/7.5.1/javadoc/org/gradle/api/tasks/Nested.html).

https://docs.gradle.org/7.5.1/userguide/more_about_tasks.html#sec:task_input_output_runtime_api

https://github.com/gradle/gradle/blob/65f74264f52ac0dcc14110c95977830cf7327da8/subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc#using-it-for-ad-hoc-tasks

However, it seems this was removed:

https://github.com/gradle/gradle/pull/18662/files#diff-a51bccf29febee74ae20fa3fde1fa0c3cdccadae38914bca2cf48b67ab98f9b5

### Steps to Reproduce 

```kotlin
// build.gradle.kts

tasks.register("someTask") {
  
  inputs.property("internalProperty", "value")
    .internal() // error
  
  outputs.file("$temporaryDir/internalOutputFile")
    .withPropertyName("internalOutputFile")
    .internal() // error
  
  inputs.file("$temporaryDir/internalInputFile")
    .withPropertyName("internalInputFile")
    .classpath() // error
  
}
```

### Your Environment

* Gradle 7.5.1

### PR DESCRIPTION
**Pull request by aSemy**
Fixes #21594

### Context

More accurate documentation, less confusion. 

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Review by nathan-contino — APPROVED** [review]
docs LGTM

**Comment by jbartok** [comment]
@aSemy pls. sign your commit properly (see failed check)

**Comment by aSemy** [comment]
@jbartok I made this commit through the GitHub web gui which doesn't have this option. My GitHub email and username are already in the commit, so it looks like it's redundant information?

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
@bot-gradle cancel

**Comment by jbartok** [comment]
@bot-gradle test and merge

**Comment by jbartok** [comment]
> @jbartok I made this commit through the GitHub web gui which doesn't have this option. My GitHub email and username are already in the commit, so it looks like it's redundant information?

My comment was misleading. A sign-off was needed. I did it now and will merge it in.

**Pull request merged**
