### PR TITLE
Improve the performance of FileUtils.calculateRoots

### PR DESCRIPTION
**Pull request by lixiangconan**
Signed-off-by: Xiang Li <lixiangconan@gmail.com>

### Context
This is an attempt to mitigate the up-to-date check performance issue gradle/gradle#6421. The new algorithm should generate the same result as the old one, but is much faster when both the input files and the output roots have a large size (it changes the worst case performance from O(N^2) to O(N*log(N)) where N is the size of the input files). The new algorithm is not necessarily faster when the size of output roots is small, but performance should not be a concern anyway in those cases.

For the continues build of my project which uses play and gradle and has more than 1000 external jar dependencies, this reduces the total up-to-date check time from around 100s to 30s (with 4 workers). This fix should be benefit for other large projects that rely on continues build. 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#git-commit---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by oehme** [comment]
Closing as this has already been fixed.

**Comment by lixiangconan** [comment]
@oehme Thanks for coming up with the fix. I tested it with my project, it definitely reduced the file watching time, but I think the time can be further reduced with this fix. Here are the up-to-date check times (which are mainly file watching times) for my project:

No fix: around 120 seconds
With gradle/gradle#6401:  around 60 seconds
With both this change and gradle/gradle#6401: around 30 seconds

I don't think the two fixes are conflicted/duplicated in theory as well. The current implementation of FileUtils.calculateRoots is quadratic which is unnecessarily inefficient. gradle/gradle#6401 improves the continues build performance by reducing its usages. However, the method is still used in other places. For example, this [code](https://github.com/gradle/gradle/blob/c77de24690ae61e79d750864bcc4beb324b37bc9/subprojects/core/src/main/java/org/gradle/internal/filewatch/jdk7/WatchPointsRegistry.java#L73) uses FileUtils.calculateRoots and is slow when the input file list is large, which can happen when the input contains a lot of external jar dependencies. Therefore improving the performance of FileUtils.calculateRoots could still be valuable, which is the goal of this fix.

Could you reconsider this request given this information? It should be a safe improvement.

**Comment by oehme** [comment]
Thanks for running the numbers again. You're right, this is unnecessarily expensive. I felt that the algorithm proposed here was more complex than necessary, so I took another stab at it. Do you mind having a look at https://github.com/gradle/gradle/pull/6455?

**Comment by oehme** [comment]
Closing in favor of https://github.com/gradle/gradle/pull/6455

**Pull request closed without merging**
