### PR TITLE
Polish central dependencies declaration

### PR DESCRIPTION
**Pull request by melix**
Fix some review feedback from @eskatos

### CODE REVIEW

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
@bot-gradle test this

**Comment by melix** [comment]
The errors seem to be completely unrelated. It looks like we have a dynamic dependency somewhere...

**Comment by melix** [comment]
@bot-gradle test this

**Review by eskatos — APPROVED** [review]
:+1:

**Pull request merged**
