### PR TITLE
Upgrade Asciidoctor plugin to 3.3.1

### PR DESCRIPTION
**Pull request by lptr**
Fixes https://github.com/gradle/gradle-private/issues/3280

### CODE REVIEW

**Comment by lptr** [comment]
@bot-gradle test RfM please.

**Comment by ljacomet** [comment]
@lptr Could you include a revert of a38921c8f73c8141235365fc41feb33be9c5a6e2 in here?
That was a workaround I introduced to improve the doc generation performance.

**Review by melix — APPROVED** [review]
Yay to the warning removals!

**Comment by lptr** [comment]
> @lptr Could you include a revert of [a38921c](https://github.com/gradle/gradle/commit/a38921c8f73c8141235365fc41feb33be9c5a6e2) in here?
> That was a workaround I introduced to improve the doc generation performance.

Added.

**Comment by lptr** [comment]
@bot-gradle test RfM please.

**Review by ljacomet — APPROVED** [review]
I confirmed this makes the docs generation performance issue go away.

**Pull request merged**
